### ISSUE TITLE
Web based Installer

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#10]
After talking with @sbwalker (always talk to Shaun Walker before starting any feature), I will start working on a web based installer similar to what I did with ADefHelpDesk (http://www.adefhelpdesk.com/ADefHelpDeskDocumentation/InstallAzure.html)

![alt tag](http://lightswitchhelpwebsite.com/images/InstallWizardAnimation.gif)

**Comment by ADefWebserver** [comment]
Still in progress... So far I have the installer working if you select the file database (this is working both in server side mode and client mode). I now need to get it working if you select SQL server. This should be easier because I should be able to use a lot of the code I have working for my ADefHelpDesk project...

![OqtaneFileInstaller](https://user-images.githubusercontent.com/1857799/58683294-c8a99c00-8328-11e9-95f9-0be175ea4588.gif)

**Comment by ADefWebserver** [comment]
It appears I cannot submit a pull request

![image](https://user-images.githubusercontent.com/1857799/58749924-9a1ee480-8440-11e9-98cf-c589375e7a9a.png)

So I zipped up the code and attached it :)

[oqtane_Installer.zip](https://github.com/oqtane/oqtane.framework/files/3243862/oqtane_Installer.zip)

**Comment by ADefWebserver** [comment]
### Features
•	Works in both server side and client Blazor modes
•	Provides options for file and SQL Server
•	Automatically upgrades database by determining what additional .sql scripts to run based on the current version detected
  
![image](https://user-images.githubusercontent.com/1857799/58749960-1e716780-8441-11e9-8819-050322f9ca10.png)
![image](https://user-images.githubusercontent.com/1857799/58749963-23361b80-8441-11e9-9698-0ee40b579602.png)


### Upgrade Process

![image](https://user-images.githubusercontent.com/1857799/58749972-2a5d2980-8441-11e9-9058-be0a3f98958e.png)

Add new scripts to the Scripts folder.
 
![image](https://user-images.githubusercontent.com/1857799/58749980-32b56480-8441-11e9-8d58-970ab0ca3991.png)

Update the TargetDatabaseVersion in the InstallWizard controller.

### Possible Recovery
![image](https://user-images.githubusercontent.com/1857799/58749983-3943dc00-8441-11e9-82a8-646d53dfb455.png)
 
Users, or a recovery process can edit the OqtaneDatabaseVersion table…

 ![image](https://user-images.githubusercontent.com/1857799/58749986-42cd4400-8441-11e9-98ff-00fc51b4aafd.png)

… and edit the value to control which scripts the installer starts with.


**Notes:**

•	It is recommended that this value always be controlled in the database rather than a configuration file because permission issues, such as the ability to read and update a configuration file, are frequently the reason for failed installations. 
•	By controlling the version number in the database, it ensures that the value is never updated unless the installation currently has access to the database, using a connection string that has been successfully written to the configuration file. 
•	This is why the InstallWizard controller repeatedly reads the connection settings rather than reads it once and caches it. 

### Code Changes

**Program.cs**
 
![image](https://user-images.githubusercontent.com/1857799/58749988-4660cb00-8441-11e9-8e2e-57fc9c8abbe9.png)

Removed file database configuration code

**Startup.cs**
  
![image](https://user-images.githubusercontent.com/1857799/58749990-49f45200-8441-11e9-88fb-6dd1bc1772db.png)
![image](https://user-images.githubusercontent.com/1857799/58749992-4d87d900-8441-11e9-85cd-cb76f132da8c.png)

Changed IConfigurationRoot to allow the appsettings.json to  be updated from a controller.
 
![image](https://user-images.githubusercontent.com/1857799/58749993-51b3f680-8441-11e9-9d09-f1489c5ca5b6.png)

Removed IStartupFilter

**Note:**

•	Over time there will be a lot of scenarios where careful custom code will be required to ensure users are able to upgrade the framework and recover. Therefore, handing this most important requirement to an outside component, that was not designed with these requirements in mind, is not recommended.

### Added Code
![image](https://user-images.githubusercontent.com/1857799/58749995-57a9d780-8441-11e9-896c-d1b0afb8c660.png)
 
The installer is contained in the Installer folder in the Client project and the InstallWizardController.cs in the Server project.
 
![image](https://user-images.githubusercontent.com/1857799/58749999-62fd0300-8441-11e9-9577-3c4e6d6a36ee.png)

The **App.razor** file was altered to detect if the Installation Wizard is to run on application start-up.

**Comment by ADefWebserver** [comment]
Here is the wizard in action...
![OqtaneFileInstaller](https://user-images.githubusercontent.com/1857799/58750059-1cf46f00-8442-11e9-8ed9-f7731d54515e.gif)

**Comment by sbwalker** [comment]
Manually integrated pull request. Implemented version only supports installation - not upgrades.

**Comment by ADefWebserver** [comment]
Final version...
![Oqtane](https://user-images.githubusercontent.com/1857799/61579309-72e7a980-aab8-11e9-9f8f-35673b9f05ca.gif)
