### ISSUE TITLE
Theme project updated to v.2

### ISSUE THREAD

**Issue by artmedia** [oqtane/oqtane.framework#1002]
Hi,
During Christmas holidays I'd like to learn how to develop custom Themes.
Cerulean theme is updated to version 1 of Oqtane
Is there a Theme project to download which is updated to v.2 of Oqtane?

**Comment by hishamco** [comment]
I think both Oqtane & Cerulean themes are work well in v 2.0.0

**Comment by sbwalker** [comment]
There are no architectural or breaking changes for themes between v1 and v2 - which is why the Cerulean theme created for V1 continues to work fine on V2.
