### ISSUE TITLE
Oqtane + Material Blazor Library

### ISSUE THREAD

**Issue by tanekim77** [oqtane/oqtane.framework#1003]
I am trying to use Material.Blazor library with Oqtane. I created a custom Theme folder in Oqtane.Client/Themes/MaterialTheme, but I don't know how to include    builder.Services.AddMBServices() in Program.cs and <MBAnchor /> in App.razer in the theme folder as in the instruction in the following link: https://material-blazor.com/docs/articles/Installation.html

 In normal project, I would just include these in Program.cs and App.razor, but in Oqtane, I believe touching Program.cs and App.razor would be a bad idea because it may cause conflict when upgrading to next version of Oqtane.

If anyone can upload a working solution that uses the Material.Blazor library, it would be appreciated.

**Comment by sbwalker** [comment]
There is an IClientStartup and IServerStartup interface which can be used for adding additional startup registration in custom themes and modules.
