### ISSUE TITLE
Bug in Oqtane.Client/Themes/ThemeBase.cs

### ISSUE THREAD

**Issue by tanekim77** [oqtane/oqtane.framework#1005]
In Oqtane.Client/Themes/ThemeBase.cs I found the following code,

  ```
      protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                if (Resources != null && Resources.Exists(item => item.ResourceType == ResourceType.Script))
                {
                    var scripts = new List<object>();
                    foreach (Resource resource in Resources.Where(item => item.ResourceType == ResourceType.Script && item.Declaration != ResourceDeclaration.Global))
                    {
                        scripts.Add(new { href = resource.Url, bundle = resource.Bundle ?? "", integrity = resource.Integrity ?? "", crossorigin = resource.CrossOrigin ?? "" });
                    }
                    if (scripts.Any())
                    {
                        var interop = new Interop(JSRuntime);
                        await interop.IncludeScripts(scripts.ToArray());
                    }
                }
            }
        }

```

But this is dangerous because some of razor components may call JsInterop that relies on some of the resources upon component initialization, but the resources won't be available at that time because they are only availalbe after Render. To fix this issue, the code above needs to be changed to 

```
        protected override async Task OnInitializedAsync()
        {
            if (Resources != null && Resources.Exists(item => item.ResourceType == ResourceType.Script))
            {
                var scripts = new List<object>();
                foreach (Resource resource in Resources.Where(item => item.ResourceType == ResourceType.Script && item.Declaration != ResourceDeclaration.Global))
                {
                    scripts.Add(new { href = resource.Url, bundle = resource.Bundle ?? "", integrity = resource.Integrity ?? "", crossorigin = resource.CrossOrigin ?? "" });
                }
                if (scripts.Any())
                {
                    var interop = new Interop(JSRuntime);
                    await interop.IncludeScripts(scripts.ToArray());
                }
            }
        }

```

**Comment by hishamco** [comment]
Could you please send a PR?

**Comment by tanekim77** [comment]
I just did:
https://github.com/oqtane/oqtane.framework/pull/1006

**Comment by sbwalker** [comment]
Can you please provide steps to reproduce the issue you are describing - we need to be able to validate the issue prior to introducing a fix.

**Comment by tanekim77** [comment]
Sure. To reproduce a problem, you can create a razor component that calls JsIntrop calls in OnInitialized that calls a javascript function that in turns rely on some of the resources.

Or, to reproduce it faster, you can install a Material.Blazor library, follow the installation guide in the link, and try to use MBTooltip component in any razor file. 
 https://material-blazor.com/docs/articles/Installation.html

It will throw an error in the browser's console because MBTooltip depends on an js object created by the resource `new Resource { ResourceType = ResourceType.Stylesheet, Url = "_content/Material.Blazor/bundled.min.css", CrossOrigin = "anonymous" }`, upon initialization but could not find it because the object is only available after render.

**Comment by sbwalker** [comment]
It was my understanding that JSInterop should only be called in OnAfterRender. See the guidance below from the Blazor team:

https://github.com/dotnet/aspnetcore/issues/21217

Calling JSInterop from OnInitialized does work in some scenarios but eventually you run into issues as it is not the recommended best practice. I believe this is what you are experiencing in your repro example.

**Comment by tanekim77** [comment]
It's weird how Blazor behaves in such scenarios.
I just found the following excerpt from the official documentation that calls Js from OnInitialized method. Maybe such documentation causes many library authors to follow bad practices.
```
@inject IJSRuntime JS

@code {
    protected override void OnInitialized()
    {
        StocksService.OnStockTickerUpdated += stockUpdate =>
        {
            JS.InvokeVoidAsync("handleTickerChanged",
                stockUpdate.symbol, stockUpdate.price);
        };
    }
}
```
https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0
