### ISSUE TITLE
Can we put oqtane in to the Docker?

### ISSUE THREAD

**Issue by icevld** [oqtane/oqtane.framework#1013]
Tell me please, is possible to deploy the Octane framework based on the Linux Debian distribution in a Docker container?
Or not? Sorry for my errors in english.

**Comment by sbwalker** [comment]
Yes it is possible to deploy Oqtane to Docker. Currently Oqtan relies on SQL Server as its database so you would need to configure that appropriately.

**Comment by icevld** [comment]
Thanks for the answer.

**Comment by Eagle3386** [comment]
@sbwalker sorry for kinda "resurrecting" this old issue, but would you mind adding some documentation on how to actually do this?

I'm running a WordPress blog on a Linux machine that I _eagerly_ like to migrate from WP to Oqtane - the sooner, the better - & I'd like to use the opportunity to switch to a Docker-based setup, too.
