### ISSUE TITLE
Question about extending User properies

### ISSUE THREAD

**Issue by tanekim77** [oqtane/oqtane.framework#1022]
When registering, I want to include more fields, like Date of Birth. Is it possible to extends the User.cs properties without touching User.cs file?

**Comment by hishamco** [comment]
There's a profile page that you can do what you asking for

**Comment by tanekim77** [comment]
@hishamco 
Do you mean this page? Is there a way to add a Date of Birth field on it? 
![image](https://user-images.githubusercontent.com/20119808/103175959-1b687400-483c-11eb-81a6-98947a65961b.png)

**Comment by hishamco** [comment]
First try to go to Profile Management

**Comment by tanekim77** [comment]
@hishamco 

Thanks! That solved 👍
