### ISSUE TITLE
Do not show LangSwitcher when only one language is defined

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#1024]
@hishamco what do you think about it?
![image](https://user-images.githubusercontent.com/7838468/103202006-9b044a80-48f1-11eb-80bb-576c76cd5505.png)

**Comment by hishamco** [comment]
I think the switcher should appears if it's two or more, I will push a PR soon, BTW it's great to see someone using the languages switcher especially with Czech ;)

Thanks

**Comment by sbwalker** [comment]
I agree @chlupac - it should not be visible if there is only a single language ( I actually thought the code had logic for this already but I guess not )
