### ISSUE TITLE
"Forgot Password" or SMTP not working

### ISSUE THREAD

**Issue by artmedia** [oqtane/oqtane.framework#1026]
Hello,
I'm trying to recover a user password using "Forgot Password" function but it seems not working.
First of all I config SMTP for the Site.
Actual configuration: 
Host: smtp.sendgrid.net
Port: blanc  
SSL Enabled: "No"
The above config works on another DNN site on the same server; but I tryed also different parameters: port 25, 587 and port 465 which requires SSL Enabled: "Yes"  
After every configuration change I click on the "Forgot Password" function for an account just created (with an correct email address) but never receive the email for pwd recover.
I'm using Oqtane 2.0.0 on IIS

I don't understand if smtp is not working or the "forgot password" function is not working.

PS: could be helpfull a "test smtp config" button

**Comment by hishamco** [comment]
Could you try to reset your password in another instance that doesn't have SMTP, so we can know from where the issue comes from?

**Comment by artmedia** [comment]
I don't understand... 
how can the password be reset without sending email?

**Comment by hishamco** [comment]
Oh God!! just forgot my comment ;) 

We may need to invistigate on this one ...

**Comment by sbwalker** [comment]
@artmedia did you enable the Notifications Job in Scheduled Jobs? By default on a new installation the Notifications Job is disabled so that it does not consume system resources unnecessarily.

**Comment by artmedia** [comment]
After enabling Notification Job I tryed again (click on the "Forgot Password").
Now Notification Job says Status Failed: "The specified string is not in the form required for an e-mail address".
The email address of the User is correct, I don't know what this message is referring to.

**Comment by sbwalker** [comment]
@artmedia I believe the problem you are experiencing is because you did not provide a value for the SMTP Username field in the Site Settings UI. If we review the logic in the NotificationJob we see:

```
mailMessage.From = new MailAddress(settings["SMTPUsername"], site.Name);
````

So you can see that it utilizes the SMTP Username as the Sender of the email. If you did not specify an SMTP Username then I suspect it could result in "The specified string is not in the form required for an e-mail address". Note that you only need to specify the SMTP Username - not the SMTP Password. Please confirm that this is the cause of your problem. If so, I think we can add some better validation/feedback to the user to help them identify the issue.

**Comment by sbwalker** [comment]
@artmedia I added some better validation/feedback in PR #1040

**Comment by artmedia** [comment]
I agree with #1043
In my case SMTP username is not an email address

**Comment by Raceeend** [comment]
In UserController.cs (server site) on line 386 is the link to the user-email missing
notification.ToEmail = "";  should be     notification.ToEmail = user.EMail;

(and please add this line also:   notification.ToDisplayName = user.DisplayName;)

**Comment by sbwalker** [comment]
UserController is not a problem - it is by design. You should only provide a ToEmail if a ToUserId is not provided. If you provide a ToUserId the ToEmail is populated from the User table.

**Comment by sbwalker** [comment]
See #1044
