### ISSUE TITLE
Lists in administrative interface should be ordered alphabetically

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#1027]
![image](https://user-images.githubusercontent.com/7838468/103405599-f33c8600-4b57-11eb-8b4d-80d71dab7a45.png)

It's difficult to find correct user here with few hundreds of users.

**Comment by hishamco** [comment]
It could be sorted in the UI that uses the lists but not in repositories or APIs because the entries should respect the creation datetime for instance the users page should display them with creation order but in roles page displaying them alphabetically make sense

**Comment by sbwalker** [comment]
Agreed @chlupac - the entries in the UI should be ordered alphabetically.

**Comment by hishamco** [comment]
As I said before I suggest to do this in dropdown lists, but not list pages because sometimes the record creation is valuable

**Comment by sbwalker** [comment]
@hishamco I agree that it would be easiest to order the list in the component where the data will be displayed.

**Comment by hishamco** [comment]
I can submit a PR if @chlupac not started yet ;)

**Comment by chlupac** [comment]
@hishamco great, submit it.
