### ISSUE TITLE
Oqtane Controls should consider global resources

### ISSUE THREAD

**Issue by nicpitsch** [oqtane/oqtane.framework#1029]
I'm looking for a solution with which i don't have to provide common localization strings like *Add.Text, Delete.Text, Edit.Text, Cancel* again and again for each razor component/page separated within each component's own resx file. This question is related to an external (monolitic) Module, containing a lot of components.

Using `IStringLocalizer` with *AspNetCore* components like *NavLink* works fine. But Oqtane Controls like *ActionLink* don't consider which type get's injected. Oqtane's *LocalizableComponent* base class doesn't consider that i'm injecting e.g. `IStringLocalizer<Messages>` and not the component type itself (`IStringLocalizer<Index>`). Subsequent example should explain what i mean (example external Module named Me.MyModule):

```c#
/*
'Placeholder' razor component/page as a reference for common localization strings: Messages.razor.
Resource file: ./Resources/Me.MyModule.Messages.resx, containing the common localization strings.
Component/Page: Index.razor:
*/
@inherits ModuleBase
@inject IStringLocalizer<Messages> Localizer
// AspNetCore component, localization is successful:
<NavLink class="btn btn-secondary" href="javascript:history.go(-1)">@Localizer["Cancel"]</NavLink>
// Oqtane Control, localization not functional:
<ActionLink Action="Add" Security="SecurityAccessLevel.Admin" Text=@Localizer["Add"] />
```

Am i missing something or is it realy not possible for Oqtane Controls to retrieve localization strings from another type then itself?

**Comment by hishamco** [comment]
@nicpitsch some of the Oqtane controls are inherit from `LocalizableComponent` to provide a localization services for their `ResourceKey`, but nothing prevent you to inject `IStringLocalizer<OfSomethingElse>`

I hope we add some docs to make the localization process clear enough, for your case be sure that resx has a valid path otherwise it will not work

**Comment by nicpitsch** [comment]
Thanks @hishamco, but how should i compose e.g. an *ActionLink* Component?

Subsequent are not functional (related to my example above):

* `<ActionLink Action="Add" Security="SecurityAccessLevel.Admin" Text=@Localizer["Add"] ResourceKey="Edit" />`
* `<ActionLink Action="Add" Security="SecurityAccessLevel.Admin" Text=@Localizer["Add"] />`

**Comment by hishamco** [comment]
You inject the localizer in the component that using `ActionLink` or the idea using another localizer within `ActionLink`?

**Comment by nicpitsch** [comment]
@hishamco i have created a repository with a sample external Module [*Me.MyModule*](https://github.com/nicpitsch/me.mymodule).

* The master branch is using a resource file *Me.MyModule.Index.resx* explicit for the *Index.razor*.
* The [develop branch](https://github.com/nicpitsch/me.mymodule/compare/develop) instead refers a resource file *Me.MyModule.ModuleInfo.resx*. The idea behind is to place there common strings like *Add.Text, Cancel*, which to use in other razor components within that Module (which would become even more useful if it is a [monolithic Module](https://github.com/oqtane/oqtane.framework/discussions/689#discussioncomment-52615)).

As you can see when you use the develop branch: the Oqtane's *ActionLink* Control doesn't take the resource string from *Me.MyModule.ModuleInfo.resx*, but the AspNetCore *NavLink* does.

**Comment by hishamco** [comment]
@nicpitsch I just saw you code the line https://github.com/nicpitsch/me.mymodule/blob/develop/Client/Index.razor#L9 will not work because `ModuleInfo` is not in `Me.MyModule` namespace, could you try to name the RESX file according to the class namespace

**Comment by nicpitsch** [comment]
Thanks @hishamco. But according to Oqtane we have to add `[Owner].[Module]` prefix to resx, where Me=Owner and Module=MyModule in *Me.MyModule.ModuleInfo.resx*. I have made clearer from where the resource strings are comming in the latest commit [ea14764](https://github.com/nicpitsch/me.mymodule/pull/1/commits/ea1476411a5c0be952c377ec847be9ce4a50000b) :

![2021-01-03_13-32-24](https://user-images.githubusercontent.com/1652835/103479088-71549300-4dcb-11eb-8e90-26746f0b4a3a.jpg)

So far thats' working as expected regarding the AspNetCore *\<NavLink/>* Control. But *LocalizedComponent.cs*, on which the Oqtane *\<ActionLink/>* Control is based, looks for the *ResourceKey* Parameter and loads *IStringLocalizerFactory* only based on ` Type.GetType(ModuleState.ModuleType)` which is the razor component Namespace: https://github.com/oqtane/oqtane.framework/blob/5ce7284a6b1c06d6806af98f669c6562e8dd7bf8/Oqtane.Client/Modules/Controls/LocalizableComponent.cs#L55

```#cs
if (!String.IsNullOrEmpty(ResourceKey) && ModuleState?.ModuleType != null)
	{
	var moduleType = Type.GetType(ModuleState.ModuleType);
	if (moduleType != null)
	{
	    using (var scope = ServiceActivator.GetScope())
	    {
	        var localizerFactory = scope.ServiceProvider.GetService<IStringLocalizerFactory>();
	        _localizer = localizerFactory.Create(moduleType);
	
	        IsLocalizable = true;
	    }
	}
}
```

*\<ActionLink/>* has no clue about the type `ModuleInfo` from within `@inject IStringLocalizer<ModuleInfo> Localizer` (which means the Localizer should look for the strings into *Me.MyModule.ModuleInfo.resx*).

**Comment by hishamco** [comment]
> Oqtane we have to add [Owner].[Module] prefix to resx

This should valid for the module resources

**Comment by hishamco** [comment]
One more thing regarding your issue's title, this may need a customization for your case, what you can do in your case change the `LocalizableComponent` so it could use a specific or global resource

I don't think we need to do this out of the box, because everything is stable from localization point of you especially for Oqtane admin, or we may add this as future enhancement

Hope that's answer your question

**Comment by nicpitsch** [comment]
> You are right, but if you are using `IStringLocalizer<T>` in your component it should work

Finally I understand how it is meant, thanks a lot @hishamco! 

In case any one out there is looking for how to retrieve common localization strings also for Oqtane Controls like *\<ActionLink*>* ([green=solution](https://github.com/nicpitsch/me.mymodule/compare/develop#diff-3122cd483e82fe28ddfd9759c8de0cd6e46a80b5b0bc15be705d7dfb53b24f96)). *ModuleInfo* is a class and the resx file containing localization strings is *./Resources/[Owner].[Module]/ModuleInfo.resx*):
![2021-01-03_14-45-45](https://user-images.githubusercontent.com/1652835/103480114-9c8eb080-4dd2-11eb-8eaa-8ccbd69d11f6.jpg)

**Comment by hishamco** [comment]
Happy to hear that's work!! but what you did is like of cheeting ;) because you supply a localized text to the component and ignore `ResourceKey` a proper solution would be to introduce a global resource that could be used in the `LocalizableComponent` if @sbwalker agreed this will allow deveopers to specify a global resource type to be used to localize the components
