### ISSUE TITLE
Error editing Module in Module management

### ISSUE THREAD

**Issue by artmedia** [oqtane/oqtane.framework#1036]
Hello,
in Admin Dashboard, Module management, any Edit button I click, I get this: "Error: System.InvalidOperationException: Object of type 'Oqtane.Modules.Controls.Label' does not have a property matching the name 'resource'"
I'm using version 2.0.0

![image](https://user-images.githubusercontent.com/4210561/103523283-ed0e1880-4e7b-11eb-919b-89e7047d7167.png)

**Comment by hishamco** [comment]
I will check this one ...

**Comment by hishamco** [comment]
I can reproduce the issue, working on it ..
