### ISSUE TITLE
SMTP EnableSSL change in select/option field

### ISSUE THREAD

**Issue by Raceeend** [oqtane/oqtane.framework#1042]
In Site settings (admin/site) the option SSL Enabled is a textfield, can this made in a select field like this?:
(line 147 in Oqtane.Client/Modules/Admin/Site/index.razor )
`<tr>
                <td>
                    <Label For="enabledSSl" HelpText="Specifiy if SSL is enabled for your server">SSL Enabled: </Label>
                </td>
                <td>
                    <select id="enabledSSl" class="form-control" @bind="@_smtpssl">
                        <option value="True">Yes</option>
                        <option value="False">No</option>
                    </select>
                </td>
            </tr>`

**Comment by sbwalker** [comment]
this was already done in #1040
