### ISSUE TITLE
NotificationJob in Error when SMTP username is NOT a email address

### ISSUE THREAD

**Issue by Raceeend** [oqtane/oqtane.framework#1043]
In the notification job for sending emails the From is constructed from SMTPUsername. This will not work when the username is not a email or (with testing/developement) there's is no username to be used.

Solution is maybe a Site Emailaddress with is used a From address.
(index.razor of site admin -> extra field Site Email

For example:
in index.razor
`<tr>
                <td>
                    <Label For="siteemail" HelpText="Enter site email address">Site email: </Label>
                </td>
                <td>
                    <input id="siteemail" class="form-control" @bind="@_smtpsiteemail" />
                </td>
            </tr>`
            

Extra lines for retrieving en storing the setting in the database
like this:      
   _smtpsiteemail = SettingService.GetSetting(settings, "SMTPSiteEmail", string.Empty);
   SettingService.SetSetting(settings, "SMTPSiteEmail", _smtpsiteemail);

In NotificationJob.cs (serversite)
  mailMessage.From = new MailAddress(settings["SMTPSiteEmail"], site.Name);

**Comment by sbwalker** [comment]
Yes I think this change makes sense. SMTP services like Gmail or Hotmail use an email address as a username but services like SendGrid have config details:

Server: smtp.sendgrid.net
Port: 25 or 587 (non-SSL) or 465 (SSL)
Username: apikey
Password: {hash key}

So you would need a Sender Email option. Obviously you would also need to conform to whatever rules the email service requires for sender authorization as most services will not allow you to send email on behalf of another user.

**Comment by sbwalker** [comment]
Implemented in #1044
