### ISSUE TITLE
Forgot Password don't send a email

### ISSUE THREAD

**Issue by Raceeend** [oqtane/oqtane.framework#1060]
Forgot Password or sending a notification to another user.
This has already been reported (and closed) but I am not getting it working.

When I look in the code I see that a notification has no ToEmail when the Job is executed and therefore no message can be sent (a mailadress need a valid email address).

However, the ToUserId is available.
It goes wrong on ines 86-90 in NotificationJob.cs:
if (notification.ToUserId! = null)
{
    mailMessage.To.Add (new MailAddress (user.Email, user.DisplayName));   <--- Error
   mailMessage.Body + = "To:" + user.DisplayName + "<" + user.Email + ">" + "\ n";
}

Is this a setting problem (do I something wrong) or else?

**Comment by sbwalker** [comment]
The code you posted above looks different than the code in the NotificationJob:

```
                            if (notification.ToUserId != null)
                            {
                                mailMessage.To.Add(new MailAddress(notification.ToEmail, notification.ToDisplayName));
                                mailMessage.Body += "To: " + notification.ToDisplayName + "<" + notification.ToEmail + ">" + "\n";
                            }
                            else
                            {
                                mailMessage.To.Add(new MailAddress(notification.ToEmail));
                                mailMessage.Body += "To: " + notification.ToEmail + "\n";
                            }
```

If ToUserId has been specified for a Notification then the system retrieves the ToEmail and ToDisplayName from the User table. If ToUserId has not been specified for a Notification then the system expects that the ToEmail has been explicitly provided.

**Comment by sbwalker** [comment]
Are you using the latest code in the dev branch? I am asking because there was an issue related to the Sender which was fixed recently in #1044

**Comment by artmedia** [comment]
Me too I'm trying to send password, without success.
After downloading the latest code in the dev branch (added Email Sender in SMTP config),
I click on "Forgot Password" and then in Notification Job I see this message:
"The parameter 'address' cannot be an empty string. (Parameter 'address')"

I don't understand which 'address' is.
In Profile Management I removed all field but FirstName and LastName, is it the reason for the message?
Anyway email was not sent

**Comment by sbwalker** [comment]
My apologies.... after further research I was able to determine that the original API was modified to prevent the leakage of user information which caused an impact to the sending of notifications. The original API included joins from the Notification table to the User table - which is how the FromEmail and ToEmail properties were populated. These joins were removed in PR #581. Thank you for reporting this issue - I will submit a new PR to fix the problem.

**Comment by sbwalker** [comment]
This should be fixed in #1065. The Notification API now relies on the ToEmail/ToDisplayName properties rather than ToUserId ( although if you only specify ToUserId and do not provide ToEmail/ToDisplayName it will retrieve them in the NotificationJob ). I also added some additional constructors to the Notification class to simplify the creation of objects and abstract the more internal properties.

**Comment by sbwalker** [comment]
@artmedia @Raceeend please let me know if the latest changes resolve your problem

**Comment by artmedia** [comment]
I confirm that now email to User Password Reset is sent succesfully.
Thanks

**Comment by Raceeend** [comment]
Sorry for mine late respons. But yes its working fine. The problem is solved. Thanks!
