### ISSUE TITLE
Dapr support

### ISSUE THREAD

**Issue by jpiquot** [oqtane/oqtane.framework#1068]
Hi,

I would like to add [Dapr](https://dapr.io/) to Oqtane to be able to have a distributed architecture.

Do you think that this is a feature that could be integrated into the Oqtane project?

The first step would be to add a Dapr Repository for the Oqtane Storage

Dapr is a Microsoft framework for building distributed applications and microservices.

**Comment by sbwalker** [comment]
this is not on the current roadmap
