### ISSUE TITLE
"Error Loading Module Container"

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#107]
**Steps to reproduce issue:**

1. Log in as Host.
2. Open hamburger menu
3. Select HelloWorld for Module
4. Select Top Pane for Pane
5. *Do not select a container* (leave it as 'select container')
6. Press the button to Add Module To Page

The screen will say "Error Loading Module Container"

**Expected Result:**

- The module will not show this error

Note: The only way to clear this is to go to the database and remove the latest record in the **PageModule** table and then the latest record in the **Module** table.

**Discussion**

- Rather than prevent a person from adding a module without a container, I suggest we allow a person to add a module without a container but not have it throw an error?

- I would be willing to work on this, but did not want to do so without guidance

**Comment by sbwalker** [comment]
A few comments... the HelloWorld module should not be in the Github repository - it was mistakenly checked in after doing a demo. That being said, this error would occur when you add any module to a page. Specifying a module container is actually a requirement in Oqtane, as the module container is what allows you to manage the location of the module, manage its settings, etc... So I think the solution is to select the first container in the dropdown by default. I can make these changes.
