### ISSUE TITLE
PWA question 

### ISSUE THREAD

**Issue by PhilipMur** [oqtane/oqtane.framework#1097]
Hello, 

Not sure where else I can find an answer to my question so I apologise if there is a forum somewhere else that I should post this question. 

Just a question on adding to the Web app PWA functionality.

I can see in the >>admin dashboard >>site settings that there is a section "Progressive Web Application Settings".

If I set it up to be a PWA here are the files 
manifest.json
service-worker.js
service-worker.published.js
wwwroot/index.html  (link elemnts) 
Etc... 
Supposed to be added automatically or are they to be added manually?

Philip

**Comment by sbwalker** [comment]
If you enable a site to be available as a PWA and you provide an App and Splash icon, Oqtane will dynamically generate the manifest and automatically include the service worker.

**Comment by PhilipMur** [comment]
Hello Shaun,

I have tried this in Debug mode, Release mode with no joy. 

The files needed are not being automatically created. 

I have uploaded an app icon 192x192.png and a splash icon 512x512.png and I have tried chrome, Edge, Firefox but still I don't get the little plus icon to install nor do I see the PWA files being created. 

I'm using framework version 2.0.0 with Visual studio 2019

**Comment by PhilipMur** [comment]
Here are the commercial free pictures used.
![pie-icon-512](https://user-images.githubusercontent.com/27295232/107531946-44a74e80-6bb5-11eb-9776-b0dd86520209.png)
![sphere-192](https://user-images.githubusercontent.com/27295232/107531998-51c43d80-6bb5-11eb-93a4-1aec3039f036.png)

here is the on saved log.
[PWA Log on save.txt](https://github.com/oqtane/oqtane.framework/files/5959172/PWA.Log.on.save.txt)

**Comment by PhilipMur** [comment]
Also I have the app settings.json file "Runtime" : "WebAssembly"

Also the management panel will not display when the Runtime is set to WebAssembly as I was going to take a screenshot of the system info. 

I have also tried in Debug and Release and published and different browsers and clear the cache etc.

**Comment by sbwalker** [comment]
So I did some testing and there does seem to be an issue. The script and manifest are all being created and linked properly, however some of the Urls in the manifest appear to be relative when they need to be absolute. I am still exploring further to try and identify the PR that caused this issue.

The dynamic injection of the script and manifest makes it a bit tricky to understand - you need to use the browser debugging tools ( I use Firefox Developer Edition ):

![image](https://user-images.githubusercontent.com/4840590/107555126-cb076480-6ba4-11eb-82a1-c52cf57fb531.png)


![image](https://user-images.githubusercontent.com/4840590/107555157-d35f9f80-6ba4-11eb-8b9e-f2ef027e214d.png)

**Comment by sbwalker** [comment]
Thank you for reporting this - it is fixed in #1098

![image](https://user-images.githubusercontent.com/4840590/107563579-40783280-6baf-11eb-8b76-2f6ba3f6ba53.png)

**Comment by PhilipMur** [comment]
Wow you don't waste anytime.

No problem, glad I can help in some way. 
Web development is not my strong point at the moment but this framework definitely speeds up the learning curve.
