### ISSUE TITLE
The "ResolveAssemblyReference" task failed unexpectedly when adding oqtane module nupkg as static dependency to other project

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1100]
Oqtane has flexible way to install custom oqtane modules in run-time using special implementation of nuget packages https://github.com/oqtane/oqtane.framework/issues/532.

I need other way around. I have 2 oqtane modules. The first one was packaged as nuget package. During development of the second one, when I add first oqtane module nuget package as common static dependency for Package project  (like adding any other normal nuget package dependency) I get error in Visual Studio Error	`MSB4018	The "ResolveAssemblyReference" task failed unexpectedly.`.

I need this to simplify creation of nuget package for a second oqtane module that needs to have a first oqtane module as part of same nuget package. In my case the first oqtane module is https://github.com/2sic/oqtane-imageflow and the second one is https://github.com/2sic/2sxc. 

Steps to reproduce are very simple.
1. Create first external oqtane module `ToSic.Module1` using module creator in oqtane instance.
2. Release `ToSic.Module1.1.0.0.nupkg`.
3. Create second external oqtane module `ToSic.Module2` using module creator in oqtane instance.
4. Install nuget package dependency `ToSic.Module1.1.0.0.nupkg` in `ToSic.Module2.Package` project.

<img width="500" alt="nuget-module1-in-module2" src="https://user-images.githubusercontent.com/2724850/107610007-d60fd280-6c40-11eb-8f45-75ff9d6289f5.png">
<img width="1017" alt="nuget-module1-in-module2-error" src="https://user-images.githubusercontent.com/2724850/107610013-dad48680-6c40-11eb-85ce-59228a18bb9c.png">

5. I get error.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolveAssemblyReference" task failed unexpectedly.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag.
   at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, List`1 idealAssemblyRemappings, List`1 idealAssemblyRemappingsIdentities, List`1 generalResolutionExceptions)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ToSic.Module2.Package	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2123
```

My workaround is:
1. Open `ToSic.Module1.nuspec`.
2. Comment dependency `<dependency id="Oqtane.Framework" version="2.0.0" />`.
![image](https://user-images.githubusercontent.com/2724850/107610384-c644be00-6c41-11eb-9dab-38f7908229a5.png)
3. Release `ToSic.Module1.1.0.0.nupkg`.
4. Install nuget package dependency `ToSic.Module1.1.0.0.nupkg` in `ToSic.Module2.Package` project without error.

Currently I do not see any functional drawbacks with this workaround, but it does not feels right.

**Comment by PhilipMur** [comment]
I thought there was supposed to be no punctuation on the naming of a module.

Example ToSic.Module >> tosic.module

That could be your issue?

**Comment by PhilipMur** [comment]
@tvatavuk take a look at this post with relation to copy local flag, it might help you. 
https://github.com/dotnet/msbuild/issues/4072

**Comment by sbwalker** [comment]
Issue #1099 and #1100 both seem to be related to a specific development approach which I am not understanding. The main question I have is why you would want to create an external Oqtane module to simply wrap the ImageFlow server-side class library, and then try to reference that module from another module? Why not include ImageFlow directly in your consuming module? For example the DNF.Projects example module ( https://github.com/oqtane/DNF.Projects ) uses RestSharp in its scheduled job to call the Github API and retrieve project metrics. The standard RestSharp Nuget package is referenced by the Oqtane module for developent and the RestSharp DLL is packaged with the module as part of the module's deployment package.

**Comment by tvatavuk** [comment]
The goal was to have a family of child oqtane modules, where each is developed separately and can be deployed and installed as standalone. Example is Imageflow oqtane module.
Than we have a parent module that depends on a child module (for now, only in runtime). The parent nupkg should  somehow contain child oqtane modules, so that all can be deployed and installed at ounce. Example is 2sxc oqtane module.

As You explained (and from what I see) several approach are possible. This specific approach was first selected because it had the minimal number of simple steps to include child module in parent module package (for first time, and latter with future updates of child module).

Thx for your explanation. I guess with more experience we will come to better strategy to package more child modules in some parent module.

**Comment by sbwalker** [comment]
Thank you for your explanation. In general I think modularity is a good thing... however you always need to keep in mind that if you physically decompose things to too granular of a level, it can make recomposition more challenging. And determining that tipping point is more of an art than a science - it really depends on the business requirements.

**Comment by sbwalker** [comment]
Discussion #985 may also provide some insight into this area. Rather than decomposing your solution into many physically isolated projects/packages, it may be easier for you to create a single project/package which internally contains a variety of modules and services.

**Comment by tvatavuk** [comment]
Thanks for Your explanations (and examples) on the benefits of keeping in the same solution, project, assembly and/or nupkg when a whole family of oqtane modules have to be deployed in the same Oqtane instance.

**Comment by sbwalker** [comment]
Closing as this issue appeared to be addressed through explanation above
