### ISSUE TITLE
Octane.Server.csproj using C# language version 7.3

### ISSUE THREAD

**Issue by kevin-weir** [oqtane/oqtane.framework#1108]
Was there a reason for the Octane server project to be constrained by using version 7.3 of C#.  I discovered this when trying to take advantage of the asynchronous programming model.

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    **<LangVersion>7.3</LangVersion>**
    <Configurations>Debug;Release</Configurations>
    <Version>2.0.0</Version>
    <Product>Oqtane</Product>
    <Authors>Shaun Walker</Authors>

```
I noticed the Task await async language features were not being implemented throughout the stack.  If used, it would certainly increase the overall robustness and responsiveness of the code base.

**Comment by sbwalker** [comment]
#834 was intended to remove the language version constraint, however it appears that is was not removed from the Server project - @hishamco do you recall why you did not modify the Server project?

**Comment by hishamco** [comment]
Let me check @sbwalker seems there's a reason or  I forgot it accidently , I will test this and come back to comment here ...
