### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by kevin-weir** [oqtane/oqtane.framework#1113]
Would there by any interest in me volunteering to **add asynchronous programming logic (Task, await, async)** to the code base and provide other optimizations for EF Core such as:

- AsNoTracking (queries) - perform queries without the overhead of change tracking
- SaveChangesAsync - save changes to the dbcontext asynchronously 
- AddDbContextPool - enables a pool of reusable context instances
- ToListAsync
- FindAsync
- and so on...

**Comment by sbwalker** [comment]
The next major improvement identified on the roadmap is Cross Platform Database Support described in in #964. I would not want to tackle the items you are suggesting until #964 is complete. That being said, there is nothing stopping you from implementing these EF Core optimizations to the Blog module ( https://github.com/oqtane/oqtane.blogs ). It would provide a smaller sandbox to prove the feasibility and impact of these changes to the framework. The only other thing I would mention is that if the goal of these changes is for performance optimization, then you would want to measure the performance before and after the changes are implemented ( I have seen some performance assessments actually result in degradation after introducing async methods ).

**Comment by kevin-weir** [comment]
I can certainly take a look at the Blog module.  Were you planning to create a dev or feature branch for it?

**Comment by PhilipMur** [comment]
Take a read off this
https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0

And this

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0

Might give you some ideas

**Comment by sbwalker** [comment]
@PhilipMur thank you for sharing - there are some very interesting tips in that first article. Obviously those articles focus on Client application performance, whereas @kevin-weir was referring to Server application performance. Ironically, the area where I have encountered the most performance issues in the past is in the communication between these two applications ie. the number of calls between client and server, and the latency of each call between client and server. This is usually the biggest performance bottleneck in any SPA. This is where much of the performance optimization has been focused in Oqtane to date - keeping the number of interactions between client and server to a minimum.

**Comment by kevin-weir** [comment]
I will hold off and see what happens with the Cross Platform Database Support...
