### ISSUE TITLE
Upload SVG throw error

### ISSUE THREAD

**Issue by erw13n** [oqtane/oqtane.framework#1120]
When upload `.svg` file from File Manager or upload Logo it throw an error :

![image](https://user-images.githubusercontent.com/792847/108285442-ad945500-71b9-11eb-94ef-19d12d93d943.png)

![image](https://user-images.githubusercontent.com/792847/108285524-d6b4e580-71b9-11eb-9c1b-f6fc8f0949d7.png)

Not much information on Logs, but when debugging, it throw error at `FileController > MergeFile`

What's weird is that the file uploaded to Physical Folder, but not listed in `FileManager`
![image](https://user-images.githubusercontent.com/792847/108286405-98202a80-71bb-11eb-9bca-d0db96e81373.png)

**Comment by leigh-pointer** [comment]
The issue is with svg files.  A svg image, is an object in the form of XML there for will not hold these attributes.

```
FileStream stream = new FileStream(filepath, FileMode.Open, FileAccess.Read);
                using (var image = Image.FromStream(stream))
                {
                    file.ImageHeight = image.Height;
                    file.ImageWidth = image.Width;
                }
```
I have put a fix forward for review.

**Comment by sbwalker** [comment]
Question on this item... there is a constant in the framework: 

ImageFiles = "jpg,jpeg,jpe,gif,bmp,png,svg,ico";

This constant is used as a filter in some areas to restrict the files which can be selected/uploaded by a user to only allow image files ( ie. when choosing a logo for a site, etc... ). This constant is also used in the FileController to determine whether the system should dynamically obtain the width and height of an image. Currently SVG is part of this list... but my question is whether this is valid or not?

**Comment by erw13n** [comment]
Can it just read height and width from the object xml, Svg-xml should have this attribute

**Comment by sbwalker** [comment]
@hishamco raised a valid point - SVG files pose a security risk https://wpglorify.com/wordpress-svg-support/. Perhaps the best short term option is to remove SVG from the ImageFiles filter.

**Comment by hishamco** [comment]
Long time we may sanitize the svg content to make it safe to upload such files

**Comment by sbwalker** [comment]
SVG removed as a short term solution
