### ISSUE TITLE
Deploy to Azure doesn't pull in code

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#1140]
The **Deploy to Azure** button appears to be broken.

It completes:

![image](https://user-images.githubusercontent.com/1857799/109327137-d9908580-780c-11eb-8a2f-fbb717b77b93.png)

But the source code is not there:

![image](https://user-images.githubusercontent.com/1857799/109327266-fe84f880-780c-11eb-9f25-96373cf85516.png)

I suspect it is because the _https://github.com/oqtane/oqtane.framework.git_ link in **azuredeploy.json**:

          "properties": {
            "RepoUrl": "https://github.com/oqtane/oqtane.framework.git",
            "branch": "master",
            "IsManualIntegration": true

Goes to the Dev branch now?
Otherwise I can't figure out what is wrong :(
cc: @jimspillane

**Comment by ADefWebserver** [comment]
I looked further in the logs and it appears to time-out

![image](https://user-images.githubusercontent.com/1857799/109328128-f5485b80-780d-11eb-98d5-f1f1ecf0d2d7.png)

![image](https://user-images.githubusercontent.com/1857799/109328165-ff6a5a00-780d-11eb-86b9-34aca3ff066d.png)

**Comment by ADefWebserver** [comment]
Neverminded, without doing anything, it later showed up (10 minutes later!)

![image](https://user-images.githubusercontent.com/1857799/109328958-e3b38380-780e-11eb-9876-61be588d257e.png)

(perhaps we can update the instructions?)

**Comment by jimspillane** [comment]
Sorry for the late response.  I experienced similar behavior on occasion and could not find the root cause.
