### ISSUE TITLE
Debugging External Module in Runtime WebAssembly configuration

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#1147]
I didn't succeed to debug code inside the Client project of the External Module. I have set Oqtane Runtime to WebAssembly in the configuration, because I have set of microservices behind the UI and I don't need server side. I tried to attach debugger in all possible ways, but it was not successful. I also understand what was described in this post: https://blazorhelpwebsite.com/ViewBlogPost/4 , and I checked my debug routines with the content of this post.

Is it possible at all? I hope yes. Any idea how?

Thanks, Vedran

**Comment by hishamco** [comment]
I will bing @ADefWebserver coz he already answered that before ;)

**Comment by ADefWebserver** [comment]
Sorry I have no experience debugging a Oqtane WebAssembly modules.

**Comment by sbwalker** [comment]
@vzdesic can you please explain what you mean by "I have set of microservices behind the UI and I don't need server side"? Are you saying that you created some service wrappers in your Client projct which use HttpClient to call API endpoints on another server? If so, then its important to realize that the hosting model is simply a run-time configuration decision. For development you can configure your environment to use the Server model ( which would allow you to follow @ADefWebserver's debugging instructions and step through your code ) and then when you deploy to production you can set your environment to use the WebAssembly model.

**Comment by hishamco** [comment]
> Sorry I have no experience debugging a Oqtane WebAssembly modules

WebAssembly is missy especially in debugging but you could use old school `Console.WriteLine()`

**Comment by vzdesic** [comment]
> @vzdesic can you please explain what you mean by "I have set of microservices behind the UI and I don't need server side"? Are you saying that you created some service wrappers in your Client projct which use HttpClient to call API endpoints on another server? If so, then its important to realize that the hosting model is simply a run-time configuration decision. For development you can configure your environment to use the Server model ( which would allow you to follow @ADefWebserver's debugging instructions and step through your code ) and then when you deploy to production you can set your environment to use the WebAssembly model.

Yes, this is more or less what I have. I will check this today.

I am not sure that I fully understand hosting model or run-time configuration. Can you elaborate a little bit about that? What is actually changed by setting Runtime from Server to WebAssembly?

**Comment by vzdesic** [comment]
Yes, it works fine if I set Runtime to Server. I will close this.

Still, I would like to understand better what is really different when this configuration parameter is set to WebAssembly.

**Comment by hishamco** [comment]
>  I would like to understand better what is really different when this configuration parameter is set to WebAssembly.

Simply there's no server side rendering and you are limited in terms of functionalities and APIs

**Comment by sbwalker** [comment]
@vzdesic this is a really a Blazor question - not an Oqtane question. When you run Oqtane on the "Blazor Server" runtime it essentially means your component UI is being generated on the server and the browser UI is being refreshed over a SignalR connection. When you run Oqtane on the "Blazor WebAssembly" runtime, your component UI DLLs are actually downloaded from the server to the browser during the initial connection and from that point on the browser UI is refreshed natively on the client using WebAssembly. It would most likely be helpful for you to watch this presentation so that you understand the fundamentals of Blazor https://www.youtube.com/watch?v=j-cj80ofIWI&feature=youtu.be

**Comment by vzdesic** [comment]
Thanks for the answer. Yes, I understand the Blazor basics. My question was related more to Oqtane, so it seems I have to stop assuming that Oqtane adds something onto it.

**Comment by vzdesic** [comment]
There is one more thing which bothers me and is related to debugging of the External Module. I want to confirm that with you, guys. It seems that it is not possible to have feature called - Hot Reload - during debugging of the External Module in any possible way. In order to refresh the page in case of a simple change on the External Module I have to **restart IIS manually**, there is no other way. It is time consuming, so, if somebody solved this issue other way, it will be great to know the solution. The order of actions I am doing are as follows:
- Oqtane Framework -> Debug -> Start Without Debugging -> Open the page with External Module
- If I want to debug External Module now, I will attach the Debugger, that is fine
- External Module -> make simple change on the UI, Client project source
- External Module -> Build -> Rebuild Solution
- DLLs and PDBs files are copied to output directory of the Oqtane Framework
- Page is reloaded, I can see reload action in the browser
- Check if change is visible on the page with External Module
- **Change is not visible**
- Oqtane Framework -> Build (Rebuild is not possible, because files are locked by IIS)
- Check if change is visible on the page with External Module
- **Change is not visible**
- **If I restart IIS manually, and start the site again, then change is visible**
In order to see the change I tried all standard ways of disabling cache or refreshing or reloading the page, like:
- Dev Tools -> Network -> **Disable Cache**, check box checked
- Dev Tools -> Application -> right click on Cache Storage -> **Refresh Caches**
- Dev Tools -> right click on Refresh button -> **Empty Cache and hard refresh**
- etc.
There is one more thing I can do to make this process automatic. I can create a script which will handle IIS restart and start the application for me, but before that I want to be sure if there is simpler way or if Hot Reload of the External Module is just not possible by your opinion.

Thanks in advance!

**Comment by vzdesic** [comment]
Until I receive some answer to above question, let's say that for example this Power Shell script (saved as file **iis_restart.ps1**):
```
$site = 'Oqtane.Server' # replace this by your site name (not case sensitive)
$process = Get-CimInstance Win32_Process -Filter "Name = 'iisexpress.exe'" | ? {$_.CommandLine -like "*/site:`"$site`"*" }
if($process -ne $null)
{
    Write-Host "Trying to stop $($process.CommandLine)"
    Stop-Process -Id $process.ProcessId
    Start-Sleep -Seconds 1 # Wait 1 second for good measure
    Write-Host "Process was stopped"
} else
{
   Write-Host "Website was not running"
}
dotnet run --project E:\Projects\Company\Oqtane\oqtane.framework\Oqtane.Server\Oqtane.Server.csproj
```
Will help me to simulate Hot Reload in a following sequence:
- Oqtane.Server -> Start Without Debugging
- ... do what you want here ...
- External Module -> make simple change on the UI, change Client project's source
- External Module -> Build -> Rebuild Solution
- Run script above -> **iis_restart.exe** -> Wait for all that to execute
- Click - **Reload** - on the Page with External Module
- **Change is visible**

**Comment by vzdesic** [comment]
I just realized, even only - dotnet run ... - command is enough. I don't have to kill Oqtane.Server site with first part of this script, because I will do it by pressing - Ctrl + C - in command line, in order to re-run the script or command. So, now it is simple enough.

**Comment by vzdesic** [comment]
After some testing, I found a process to attach the debugger. It is actually simple, I have to search by name of the process. I did mistake and did it hard way, I tried to search by process id, which requires some additional commands to execute.

Here is minimal routine which gives me ability to simulate Hot Reload feature:
- Start Oqtane.Server from command line: **dotnet run --project path/to/Oqtane.Server.csproj**
- External Module -> **make simple change on the UI**, change Client project's source
- External Module -> Build -> **Rebuild Solution**
- DLLs and PDBs files are copied to output directory of the Oqtane Framework
- Stop Kestrel by pressing **Ctrl+C** in command line
- Start Oqtane.Server from command line: **dotnet run --project path/to/Oqtane.Server.csproj**
- Click - Reload - on the Page with External Module
- Change is visible. Attach is possible. Find process - Oqtane.Server.exe - in case you have to attach debugger of the External Module.

Now, I am satisfied. It is the shortest routine which simulates Hot Reload. I hope it was also helpful for you guys.

**Comment by sbwalker** [comment]
@vzdesic this is excellent! The overarching theme of the Oqtane Philosophy is "speed" - and the developer "inner loop" is a very important aspect of that story. I am sure many developers will find the Hot Reload approach to be very helpful. Since this Issue item is Closed I am sure that most of the community have not seen your post above. I would suggest you move it to the Discussions area so that people are aware of your work.

**Comment by vzdesic** [comment]
>> I would suggest you move it to the Discussions area ...
Do you mean Reopen it or something else?

**Comment by hishamco** [comment]
No, Shaun means Open a new discussion using this [link](https://github.com/oqtane/oqtane.framework/discussions)
