### ISSUE TITLE
Event log Rows Drop down not changing the number of rows displayed

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1152]
When changing the rows drop down in the Event Log the display is not displaying the total number of rows selected.

**Comment by leigh-pointer** [comment]
further investigation it would appear that paging is not currently setup fully on most or all modules that use paging.

**Comment by sbwalker** [comment]
@leigh-pointer can you include a screen shot to explain what you mean?

**Comment by leigh-pointer** [comment]
![Capture3](https://user-images.githubusercontent.com/9447612/109976994-a4000680-7cfc-11eb-87bf-040e054a28f5.PNG)
currently the rows dropdown doesn't up date extend rows displayed.

after the update `<Pager Items="@_logs" PageSize="@_rows">` PageSize is added.
![Capture7](https://user-images.githubusercontent.com/9447612/109977354-06590700-7cfd-11eb-87bb-0cf6f407b36e.PNG)

**Comment by hishamco** [comment]
@leigh-pointer the pager is show up whenever you change the page size > 10, and it doesn't show the selected rows number instead it shows the `From Page` To `Total Pages` format

**Comment by sbwalker** [comment]
@leigh-pointer the Rows dropdown is intended to restrict the number of rows returned from the server API to the client ( as there can be a very high volume of log items over time ) - whereas the Pager component is intended to provide a manageable user experience on the client for tabular datasets. The default number of Pager rows is 10 - and that is consistent throughout all of the admin UI. So this module is working as expected - although it might still be confusing. Would simply changing the dropdown label to "Maximum Records" help?

**Comment by leigh-pointer** [comment]
@sbwalker @hishamco Thanks, ok I get it.  Personally I think the label "Rows:" is misleading and  "Maximum Records" would be better.
