### ISSUE TITLE
Exception thrown when alias not found from requested url in _Host.cshtml.cs

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#1156]
Before version 2.0.1 works fine. I'm using copy of database from live server for development. Alias of development machine is not present in aliases table. 

_Host.cshtml.cs:
![image](https://user-images.githubusercontent.com/7838468/109993130-42e02f00-7d0c-11eb-97dd-4123bacf28dc.png)

**Comment by chlupac** [comment]
try to solve with #1157.  
return default alias instead of null.

**Comment by sbwalker** [comment]
This logic was changed on purpose. The alias mapping must be explicit or else it opens up the possibility of abuse and confusion ( some may even construe it to be a security issue ). Obviously we do not want the system to throw an exception... it should check for the null condition in _Host and display a suitable error message ie. Site Not Found.

**Comment by chlupac** [comment]
OK, I understand, my solution is Q&D, I will cancel my PR.

**Comment by hishamco** [comment]
Can we close this issue too?

**Comment by chlupac** [comment]
@hishamco we have to solve error message when alias not found

**Comment by sbwalker** [comment]
@chlupac I had to Google "Q&D"... and I learned it means "quick and dirty" ;)

**Comment by hishamco** [comment]
> @hishamco we have to solve error message when alias not found

You are right, I thought you will update your PR but once you closed the I thought it's no longer needed ;)

**Comment by hishamco** [comment]
@chlupac how did the exception thrown in your case, `GetAliases()` will contains the root domain all the time, so I'm not sure when it will be `null`

**Comment by chlupac** [comment]
Still not fine, my solution in #1254 solves this problem partially.
