### ISSUE TITLE
Event Log strange behavior with the Paging control

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1158]
Page loads showing 10 rows.  Change to 50 rows, data is retrieved Pager numbering starts at 2
![Capture1](https://user-images.githubusercontent.com/9447612/110072668-6e9bfd00-7d7e-11eb-9a92-71b216052698.PNG)

Change Rows to 100, numbering starts at 6,  No response when clicking Navigate to the beginning " **|<** "
![Capture2](https://user-images.githubusercontent.com/9447612/110073100-216c5b00-7d7f-11eb-959e-6a69eb482757.PNG)

Then generally navigating though the pages the Pager display unusual behavior.

**Comment by sbwalker** [comment]
Fixed in #1171
