### ISSUE TITLE
Adding this to existing MVC project?

### ISSUE THREAD

**Issue by aloksharma1** [oqtane/oqtane.framework#1159]
Hello,

i have a use case where we built a mvc solution using plugin framework, now we want to do a few module using blazor so my app will contain razor as well as blazor, now my question is if i use your framework is it possible to connect both in single host application handling plugin modules (server side) and add wasm plugin project and deploy to existing production site?

thanks

**Comment by sbwalker** [comment]
Without knowing a lot more details about your existing solution it is impossible to answer this question. My initial gut reaction is that it is not impossible but based on the fact that Oqtane was never designed with this use case in mind, you would need to introduce some customizations to make it work in your specific environment.

**Comment by aloksharma1** [comment]
ok i will upload a sample project and update the link here to keep the discussion going.. if it works it would be great as i want to offload parts of mvc views to blazor spa [if it can be modularized].

**Comment by sbwalker** [comment]
Just to set the appropriate expectations, I personally do not have the time to invest into exploring this use case but perhaps other community members will be willing/able to assist.

**Comment by sbwalker** [comment]
This item would be better served in the Discussions area since it is not an "issue" with the framework - it is a question about a use case which is outside the current scope of the framework.
