### ISSUE TITLE
Issue with menu Icon Spacing.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1160]
Using the horizontal menu the child sub menu icons are not spaced away from the menu caption.  
![Capture1](https://user-images.githubusercontent.com/9447612/110117430-20581f80-7db9-11eb-9f3f-ee569567f619.PNG)
![Capture2](https://user-images.githubusercontent.com/9447612/110117449-277f2d80-7db9-11eb-9f58-126e31d45483.PNG)

The vertical menu renders the menu item ok
![Capture3](https://user-images.githubusercontent.com/9447612/110117459-29e18780-7db9-11eb-98f4-9f6bf2bef01f.PNG)

**Comment by hishamco** [comment]
I can verify from the UI bug, the PR on the way ...

**Comment by sbwalker** [comment]
fixed in #1163
