### ISSUE TITLE
Vertical Menu not correctly displaying sub sub menus

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1166]
When using the vertical menu the first child items are displayed ok but the sub sub child  items are not rendered as expected.
![vert Men](https://user-images.githubusercontent.com/9447612/110145950-43df9200-7dda-11eb-929f-09cebdc51f73.PNG)

**Comment by hishamco** [comment]
This is weird, could you please submit a PR, let me know if you need a help

**Comment by sbwalker** [comment]
I believe the default menu components were only optimized for 2 hierarchical levels - not unlimited. If someone needs to support more than 2 hierarchical levels then I would suggest they create their own custom menu component for their installation.

**Comment by hishamco** [comment]
@sbwalker I asked @leigh-pointer to handle this if he like, otherwise I will have a look to make it work for 3 levels or unlimted levels

**Comment by sbwalker** [comment]
Closing. If someone needs to support more than 2 hierarchical levels then they should create their own custom menu component for their installation.
