### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by IgnacioColmenares** [oqtane/oqtane.framework#1167]
HI,

certificate for https://oqtane.org/ has expired!
![Capture_x](https://user-images.githubusercontent.com/66320936/110209480-d6c01100-7e5a-11eb-8996-b303b4a8db67.PNG)

**Comment by hishamco** [comment]
I noticed a strange behavior in Edge browser yesterday, seems the origin issue from the certificate

/cc @sbwalker

**Comment by sbwalker** [comment]
I will look into it... it is using a Let’s Encrypt very which is supposed to auto renew

**Comment by sbwalker** [comment]
Resolved. Not sure why the Azure WebJob failed.
