### ISSUE TITLE
Profile controller after delete doesn't refresh the list

### ISSUE THREAD

**Issue by Raceeend** [oqtane/oqtane.framework#1175]
Removing a profile field does not update the profile list. 
After reloading the page (key F5) the list is displayed correctly.

**Comment by sbwalker** [comment]
The Delete event is missing a StateHasChanged() invocation to trigger a component refresh

**Comment by Raceeend** [comment]
It works when I add these two lines:
In Oqtane.Client / Modules / Admin / Profiles file Index.razor after line 44

```
_profiles = await ProfileService.GetProfilesAsync(PageState.Site.SiteId);
StateHasChanged();

```

**Comment by hishamco** [comment]
No need to call `GetProfilesAsync()` because it will be called in `OnInitializedAsync()`, my PR on it's way ...

**Comment by Raceeend** [comment]
As far as I understand OnInitializedAsync() is only called on page initialization. 
After removing, before calling StateChanged, I think the _profiles list should be updated first. 
Hence two lines, get the custom list first and then update the screen.

**Comment by hishamco** [comment]
Seems I wrong, the list doesn't refersh anymore

**Comment by hishamco** [comment]
Still don't think that we need to call `GetProfilesAsync()` twice

**Comment by hishamco** [comment]
I think you are right @Raceeend, could you please submit a PR for this one?

**Comment by Raceeend** [comment]
No idea how to do that.
I work with Visual Studio 2019
Where can I find information about that, to upload a Pull request to GitHub

**Comment by hishamco** [comment]
I advice you to read about Git and GitHub, I will try to handle this for now

Thanks a lot

**Comment by hishamco** [comment]
@Raceeend please reopen this, it will be closed once the PR is merged
