### ISSUE TITLE
Error removing user

### ISSUE THREAD

**Issue by Raceeend** [oqtane/oqtane.framework#1176]
In short, the user is not deleted but cannot be added / activated anymore. The identityuser is empty, but the user still exists in the oqtane table 'User'.

The error arises in UserRepository on line 50 (_db.SaveChanges ()):
_The DELETE statement conflicted with the REFERENCE constraint "FK_Permission_User". The conflict occurred in database "Oqtane-202103130820", table "dbo.Permission", column 'UserId'.
The statement has been terminated._

**Comment by hishamco** [comment]
Please which version you are using?

**Comment by Raceeend** [comment]
In the latest version, from 24 hours ago.

The problem can be solved by first deleting the user's folders before deleting the user himself.

For this I made the following adjustments (in Oqtane.Server).
IFolderRepository: add line: 
`void DeleteUserFolder(int userId);`

FolderRepository: add function:
```
public void DeleteUserFolder(int userId)
{
      string userFolderPath = Utilities.PathCombine("Users", userId.ToString(), Path.DirectorySeparatorChar.ToString());
      List<int> foldersToDelete = new List<int>(_db.Folder.Where(a => a.Path == userFolderPath).Select(a => a.FolderId));
      foreach (int folder in foldersToDelete)
      {
           DeleteFolder(folder);
       }
}
```

UserController: add line before _user.DeleteUser(id);
`_folders.DeleteUserFolder(id);`

**Comment by hishamco** [comment]
Please the steps needed to reproduce the issue

> The problem can be solved by first deleting the user's folders before deleting the user himself.

What's the difference if you delete the user folder later, while you have the `userId` I didn't look to the code, but I don't think there's much difference. Anyhow feel free to submit a PR
