### ISSUE TITLE
External module configuration settings

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#1179]
I have created external module. Oqtane runtime setting will be set to "WebAssembly" in the end but in order to debug the code fully, currently Runtime parameter is set to "Server". There is an independent API used only from that module, so its base address must be configuration parameter only on the level of that module. In the normal situation it will be part of the appsettings.json configuration file. 

What is best practice or suggested way to create, load and use configuration of the external module in the Oqtane? Where is the best place for external module configuration parameter to be set, loaded and used?

Thanks a lot!

**Comment by sbwalker** [comment]
Module configuration is usually managed in Module Settings. If you look at the example Blog module you will see there is a Settings.razor file which is a UI for entering settings and ModuleState contains a Settings property so they can be accessed from other module components.

**Comment by vzdesic** [comment]
Ok, so here is Setting razor component of my external module:
![image](https://user-images.githubusercontent.com/9677726/111131014-1fbd4700-8578-11eb-9c88-864664196d81.png)
Or here:
![image](https://user-images.githubusercontent.com/9677726/111131376-7d519380-8578-11eb-81c8-a33f859654eb.png)
I see only limited number of setting parameters, 5 in total. I don't see Add button to add new parameter?
If I add one row directly to the database:
![image](https://user-images.githubusercontent.com/9677726/111131697-cbff2d80-8578-11eb-9316-006e4e11a0ff.png)
then it is not visible in the Setting razor component. 

What I am doing wrong or what I don't understand? How to add new parameter named **BaseAddress** with value **http://localhost:5001/api/** ?

Thanks a lot!

**Comment by vzdesic** [comment]
Tnx!
