### ISSUE TITLE
Inject ModulState to the external module service

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#1182]
I want to ensure that my service which is part of the external module and inherits ServiceBase and IService, can read Module Settings and ModuleState object. Module Settings can be injected by standard DI routine. Still, in order to load settings I need ModuleId. How to pass ModuleId ie. ModuleState to my service class/object which also must be injected to the same razor component? 

The reason to do that is because I will read base address from module settings, and my HttpClient will use this base address, instead of default one, to fetch data.

**Comment by sbwalker** [comment]
For this scenario it may be better to store your service Url in appsettings and inject the Configuration class to access the value. Module Settings are generally used for storing information that is specific per module instance (ie. per ModuleId).

**Comment by vzdesic** [comment]
Yes, I also see it as an option. Still, I would just like to know, do you think that injection or some kind of the transfer of the ModulState to the external module service is possible?

**Comment by sbwalker** [comment]
The Service classes generated in the Client project are an optional piece of infrastructure - they only exist to provide strongly typed HttpClient access to the Server APIs. You can remove them and reference HttpClient directly from your razor components instead - in which case you would have access to ModuleState.

**Comment by sbwalker** [comment]
One other option if you want to retain the Service class is you could declare a ModuleState property in your class and then assign its value from your components Init method. Note that there are limitations to this approach due to the scope of a Service scope - but in your specific scenario where you have a single runtime instance of your module in your installation it should work.

**Comment by vzdesic** [comment]
I think that I will combine these few options, so, I think I will retain the Service, declare HttpClient property of the Service and assign its value from Init method.
