### ISSUE TITLE
Implementing MVVM pattern

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#1187]
I would like to follow MVVM pattern in the implementation of my external module if possible. I want to separate presentation from the data and business logic. In the same time, I am aware that SecurityAccessLevel, Resources, Actions, and similar properties are used by the Oqtane framework. They reside and are used directly from the razor component. 

I would like to know if there are some obstacles or if anybody have suggestions related to MVVM Pattern? Is this implementation possible at all without loosing some default features of the Oqtane framework (in other words, by changing resources loading, handling security, etc.)?

**Comment by hishamco** [comment]
If I'm not wrong RazorPages & Blazor which rely on the same tech are using a `Page` as ViewModel by creating a code behind for your view, this could be recommended when you view code becomes bigger and bigger

But I don't think there are something stop you to implement this patter while other Oqtane features such as `SecurityAccessLevel` and much more are accessible directly from within the view or DI

**Comment by sbwalker** [comment]
I have not seen an example of this pattern in Oqtane however I would assume it should be possible by using INotifyPropertyChanged. That being said, you may need to develop your own alternatives to native features which rely on module interfaces... or utilize a hybrid approach.

**Comment by vzdesic** [comment]
It seems better to avoid MVVM than to develop alternatives to the native features. It is a pity, because it is useful to have clear separation of concerns (presentation, data, logic). I will investigate this further to have it at least partially for my business logic and data.
