### ISSUE TITLE
Custom namespace of the External Module

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#1191]
**Proposal**: Enable defining custom namespace and/or project name for the External Module.
**Reason**: This will help to fit modules into namespace of some software product or company's library.

Location is fine, only new field could be introduced for project name, what will define module namespace.
![image](https://user-images.githubusercontent.com/9677726/111751690-16441f80-8895-11eb-8898-76b50790955d.png)

**Comment by hishamco** [comment]
Good suggestion, but this may leads to another issue if you like to support localization

**Comment by vzdesic** [comment]
@hishamco I would like to have multilanguage support in my application. What is exact issue?

**Comment by hishamco** [comment]
In ASP.NET Core, the localization rely on namespace so if your assembly doesn't match the namespace it will never work unless you are using `RootNamespaceAttribute` please refer to troubleshooting in asp.net core localization docs

**Comment by vzdesic** [comment]
For me using RootNamespaceAttribute is a valid option. I would rather have scaffolded External Module with custom namespace than option to change it manually across all code without that localization issue, but of course this is not my decision.
