### ISSUE TITLE
Independent running of the External Module

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#1192]
Can I independently run External Module generated by Module Creator (default source code)? If yes, how?

This can be useful during development. 

When I start Client project of my External Module I can see log messages:

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\...\Company.Test\Client\bin\Debug\net5.0

But I can't open any of these two locations on the port 5000 and 5001. Error is 404. What is Home Page actually in this case?

**Comment by hishamco** [comment]
In nutshell the Oqtane Framework allows the developers to create modules internally in the Oqtane solution or externally by creating another solution, in both ways the module should be hosted in Oqtane Application to be run

**Comment by vzdesic** [comment]
Ok, clear! I understand that routing is part of the Oqtane framework itself, so, it is logical that must be like this. I just wanted to be sure. Thanks!

**Comment by vzdesic** [comment]
@sbwalker More I think about this, more I see it as important feature. There must be solution to run and debug External Module independently. Maybe with additional Start project inside the Solution of the External Module which will be able to run it or something similar?

We can work without that, but it further helps teams to work more independently and speed up development and debugging in the local environment.
