### ISSUE TITLE
App have issue running against .NET 6 Preview 3 or later as "System.Drawing.Common" removed from Microsoft.AspNetCore.App shared framework

### ISSUE THREAD

**Issue by CancanTang** [oqtane/oqtane.framework#1208]
Hi, there is change about "Some assemblies removed from Microsoft.AspNetCore.App" in .NET 6 Preview 3 which will effect your app when running against .NET 6 Preview 3 and later, for details, please discussion see in dotnet/aspnetcore#31387. You might need add a PackageReference to the affected project for the removed assemblies.

**Comment by hishamco** [comment]
Oqtane is running on .NET Core 5, so I don't think this related to the Oqtane itself

**Comment by sbwalker** [comment]
Thank you for pointing out that this is currently a breaking change in .NET6. We do not plan to move Oqtane to .NET6 until it is officially released. Perhaps the issue may be resolved by then.... if not, we will need to address it in Oqtane.
