### ISSUE TITLE
RFC: Use Ant Design Blazor as the official UI components

### ISSUE THREAD

**Issue by ElderJames** [oqtane/oqtane.framework#1220]
Hi there, Ant Design Blazor is a set of enterprise-class UI components based on Ant Design and Blazor. 

It has a huge following and community, and also be supported by .NET Foundation. So I think it would be a win-win for the community if we could combine both Oqtane and Ant Design Blazor😊

**Comment by sbwalker** [comment]
I really like the work you are doing with Ant Design... it is great to see such a wide variety of UI components available for Blazor! Oqtane's goal is to be a generic application framework which allows developers to use their preferred UI component library. There are already examples where community members are using Telerik, DevExpress, SyncFusion, Radzen, MatBlazor, etc... The project has an official "philosophy" published here: https://www.oqtane.org/Resources/Blog/PostId/538/oqtane-philosophy and you will notice that one of the principles relates to minimizing dependencies in the framework... which further emphasizes our generic approach.  Keep up the great work... the .NET Foundation and ecosystem appreciates your contributions.
