### ISSUE TITLE
Redirect on log out

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1225]
not sure if this is by design but when logging out of the site the redirection is to the login page.  Not sure, but should it not redirect to the home page?

**Comment by sbwalker** [comment]
Logout is supposed to redirect to whatever page you are currently on.

**Comment by leigh-pointer** [comment]
Just realized what was going on. I was on a page that required permission, so of course when logging out the redirection would redirect me to log in.  So its not a bug, but does it make sense ?

**Comment by sbwalker** [comment]
resolved by #1246
