### ISSUE TITLE
Localization breaks Tab Control and Section Control

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1229]
Localization is localizing the Tab and Section Name property which breaks functionality.  The fix is to localize the Heading property but as this is an optional property the property is rarely used (the name is used as default).  Should we not make Heading mandatory (breaking change for modules that implement these controls).

**Comment by hishamco** [comment]
Is this breaking the Oqtane Admin, AFAIK everything was fine when we add the support for components localization

Please steps to reproduce so I can fix it

**Comment by leigh-pointer** [comment]
Yes I will break anything the translates the Name (or a referenced )Property.

I will explain further :)
In Tabs control the Name property is used to TabPanes, thouse references are not translated.

Below is taken from the Recycle bin index:

<TabStrip>
    <TabPanel Name="Pages" ResourceKey="Pages">
        @if (_pages == null)
        {

The (en) Resx replaces Pages.Name with "Pages" so the replacement wont cause and error.

other Resx will replace Page.Name with a translation.  

Using the Heading property of both controls fixes the issue and the Resx only to replace that value.

Pages.Heading | Pagina's...

**Comment by hishamco** [comment]
Let me check ...

**Comment by hishamco** [comment]
![ReycleBin](https://user-images.githubusercontent.com/3237266/113879844-9c33f600-97c3-11eb-8bbe-2fffe63a46f6.png)

The Tab is working at my side, I'm not sure why it breaks on your side

**Comment by leigh-pointer** [comment]
Ok now it makes sense.  My Dutch translation for **Page** is "**Paginan's**" the " **'** " is an illegal char to use in a Name reference.  I'm going to review all of my translations.  I think we need to handle this somehow as it will come back again.

**Comment by leigh-pointer** [comment]
@hishamco I have checked the dutch translations and that was the only fault.

**Comment by hishamco** [comment]
Happy to hear that
