### ISSUE TITLE
Module localization runs fine with WebAssembly but fails with the Server model

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#1238]
**Ok with core framework but problem with Developer module**

This is the Resources folder structure (Vietnamese)

![image](https://user-images.githubusercontent.com/6874322/114366605-cf9cc900-9ba5-11eb-970f-18e3e6bc9b48.png)

**Comment by sbwalker** [comment]
I am hoping @hishamco can clarify, as ensuring the Localization solution works with external modules was the top priority, and it is my understanding that he had it working.

**Comment by hishamco** [comment]
The localization works fine, please checkout the blog module. I am expecting you need to change the rootnamespace as I did in blogs module if it doesn't work please share a repository to reproduce the bug

**Comment by hishamco** [comment]
The localization works fine, please checkout the blog module. I am expecting you need to change the rootnamespace as I did in blogs module if it doesn't work please share a repository to reproduce the bug

**Comment by hishamco** [comment]
@lthoa did you try what I mentioned above?

**Comment by lthoa** [comment]
Hi @hishamco I am trying with the Blog module: [https://github.com/lthoa/oqtane.blogs](url)

**For WebAssembly**

This is Edit page, it's displays correctly...

![image](https://user-images.githubusercontent.com/6874322/115133261-086af100-a031-11eb-9134-d7ec0f78f1d0.png)

But the Settings - Other Settings page still in English.

![image](https://user-images.githubusercontent.com/6874322/115133270-1fa9de80-a031-11eb-8c2b-bf365632e95b.png)

For Server Model, the core framework part displays Vietnamese while the Blog section displays English
![image](https://user-images.githubusercontent.com/6874322/115133330-80391b80-a031-11eb-9932-4fad93395865.png)

**Comment by hishamco** [comment]
I will have a look to the Settings component, regarding the last screenshoot it's expected if you didn't copy the satellite assemblies for your component in the server project binaries

**Comment by lthoa** [comment]
Language module runs fine with Server model if copy Oqtane.Client.resources.dll file from **vi** or **en** directory to server directory, but it has same file name and will overwrite each other if you want to copy both language libraries

**Comment by hishamco** [comment]
This is the first step needed https://github.com/oqtane/oqtane.blogs/pull/12

**Comment by hishamco** [comment]
This will add some missing resources https://github.com/oqtane/oqtane.blogs/pull/13, the remaining part is `Settings` which is unlocalized for unknown resource, still I'm debugging to make everything done ...

**Comment by sbwalker** [comment]
@hishamco what is the status of this issue?

**Comment by hishamco** [comment]
Sorry @sbwalker for the delay I have an issue with my internet connection, regarding this I referenced two PRs that need to merge from your side, also there's unexpected behavior in settings components that I need to figure out to make everything works as expected. I will try to have a look today

**Comment by lthoa** [comment]
This error came back. Runs fine with WebAssembly but fails with the Server model

**Comment by sbwalker** [comment]
Please provide all of the necessary details to reproduce the issue so that it is possible to investigate.

**Comment by hishamco** [comment]
> This error came back. Runs fine with WebAssembly but fails with the Server model

Do you mean the one I fixed before?

**Comment by lthoa** [comment]
> Please provide all of the necessary details to reproduce the issue so that it is possible to investigate.

After I update the framework to the latest version, the language displays fine with the HtmlText module, but the Blog module always displays in English in Server mode

**Comment by hishamco** [comment]
Seems the Blog Module need to be updated too
