### ISSUE TITLE
Path not populated in the database for the Home page

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1242]
Path not populated in the database for the Home page
When using the PageService and request the GetPage for the Home the path property is empty.

**Comment by hishamco** [comment]
I expect the path should be "/" but I need to check the logic in the `PageService` may be empty path point to the root of the site

**Comment by sbwalker** [comment]
It is correct that the path to the home page is "" - this is by design. The name of the page is "Home" - the path is "" - they are different fields with different purposes.
