### ISSUE TITLE
Columns 'Path' and 'Name' in sql table dbo.Folder are small

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1269]
We commonly get the sql truncation error when adding new subfolders because the real path is too long for storing in 'Path' column that is only nvarchar(50).

Please can you enlarge space for cloumns:
- Path, nvarchar(1000)
- Name, nvarchar(250)

![image](https://user-images.githubusercontent.com/2724850/115688005-079ccc80-a35b-11eb-9479-b6324002c8b6.png)

**Comment by sbwalker** [comment]
Yes, this makes sense. It will need to be done using the new Migrations method for the 2.1 - which is still being stabilized.

**Comment by tvatavuk** [comment]
Super :-)

As a workaround, till then, we will enlarge space in these columns with SQL script in the installation of our oqtane module.
