### ISSUE TITLE
Permissions on Pages and Modules

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1271]
When creating/adding a page or adding a module to the page, I would expect the permissions to restricted and not public.  This would allow it be to built/configured before the page / module is set to live.

**Comment by leigh-pointer** [comment]
Yes, that is what I am getting at.

**Comment by sbwalker** [comment]
Please go ahead and make this change in the ControlPanel so that when a new module is added to a page it only provides View permissions to those users/roles which have Edit permissions to the Page.
