### ISSUE TITLE
Nuspec to include 'refs'

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1272]
Our oqtane module supports runtime compilation for in runtime created custom cshtml files.
Runtime compile-time references are required to be in folder `.\refs\`.
We need to deploy also this `refs` folder (and its content) as part of module installation.

I have a hard time finding the right way to specify in nuspec that the content of `refs` folder is extracted in `refs` folder in oqtane. 

In nuspec I used this (as it is simmilar to wwwroot).
```xml
<file src="..\ToSic.Sxc.Oqt.Server\bin\Release\net5.0\refs\**\*.*" target="refs" />
```

The content of `refs` folders ends in its `refs` folder in nupkg, but I got worrnings.

```
Attempting to build package from 'ToSic.Sxc.nuspec'.
Successfully created package 'C:\Projects\2sxc\2sxc\Src\Oqtane\ToSic.Sxc.Oqt.Package\ToSic.Sxc.11.90.0.nupkg'.
WARNING: NU5100: The assembly 'refs\Microsoft.AspNetCore.Antiforgery.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
WARNING: NU5100: The assembly 'refs\Microsoft.AspNetCore.Authentication.Abstractions.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
WARNING: NU5100: The assembly 'refs\Microsoft.AspNetCore.Authentication.Cookies.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
WARNING: NU5100: The assembly 'refs\Microsoft.AspNetCore.Authentication.Core.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
```

![image](https://user-images.githubusercontent.com/2724850/115710709-eea01580-a372-11eb-82c2-8ab1e85df826.png)

Issue it that after installing the module, all these dll's from `refs` folder are extracted in root-folder as normal dll's but that does not work in this case (for razor runtime compilation references).

On oqtane installation hosted in IIS it is expected to have `refs` folder as visible in screenshots.

### root-folder

![image](https://user-images.githubusercontent.com/2724850/115708426-44bf8980-a370-11eb-8fad-5c63e49ea552.png)

### `refs` folder

![image](https://user-images.githubusercontent.com/2724850/115708574-789aaf00-a370-11eb-89fb-799acce109b9.png)

**Comment by sbwalker** [comment]
/refs are currently not supported through the Oqtane Nuget package installer. I submitted a PR yesterday to enhance the installer to support satellite assemblies. It sounds like a further enhancement will be needed for /refs.

**Comment by sbwalker** [comment]
Based on the official Nuget documentation: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package refs are supposed to be included in a nuget package in the following path:

ref/{tfm}

which for Oqtane would be

ref/net5.0

And the Oqtane installer would need to move these files to

bin/ref ( ie. bin/Debug/net5.0/ref/... )

Does this sound correct?

**Comment by tvatavuk** [comment]
No, unfortunately, it is not working.
It is one among other combinations that I tested. Reference dll's are not deployed to `refs` (or `ref`) folders. 
While for runtime compilation to work reference dll's has to be in `refs` folder. It is not working when reference dll's are in `ref` folder.

**Comment by iJungleboy** [comment]
@sbwalker 

> I am trying to understand why you are using refs "Assemblies are added as references only for compile time; So nothing will be copied into project bin folder." Oqtane nuget packages are designed to be deployed into a production environment - not a development environment. So why do you need compile-time support?

We're just finishing 2sxc for Oqtane which (as of now) uses Razor and this is runtime compile. Users can just change the razor and in seconds see the result. Once this is stable we'll also try to get runtime compile to work for blazor as well, so this should be pretty amazing 😉. This is why we need to include the refs.
