### ISSUE TITLE
Error with Footer on Oqtane Theme

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1282]
The change to the theme to fix the footer to the bottom covers the bottom of the Main area.

The content is not visible and window scrolled completely to the bottom.
![image](https://user-images.githubusercontent.com/9447612/116062714-74c69f80-a684-11eb-8376-3d74b0312b3c.png)

![image](https://user-images.githubusercontent.com/9447612/116062464-33ce8b00-a684-11eb-8869-d39b141427bd.png)

**Comment by sbwalker** [comment]
please go ahead and submit a PR to fix this styling issue when the footer option is enabled
