### ISSUE TITLE
Version should be static readonly, not a constant

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1283]
The `Version` constant should be a static readonly. 

Reason is any other external code using a constant will end up having that constant compiled into their code - so the code won't be able to check the runtime version since their compiled code will always have the version at build time. 

Using static-readonly changes this, so that any third-party code will always use the value provided in the Oqtane DLLs.

**Comment by sbwalker** [comment]
@iJungleboy have you tested that this is not a breaking change?

**Comment by iJungleboy** [comment]
Oqtane rebuilds without a problem. 

But I don't think there is a conclusive / final way to test this, since any effect would pop up with third-party usage (which would have done the wrong thing till now).

I changed many such things in 2sxc because of the same issue and never ran into problems. But I didn't run a specific test on this. 

Note that I would also urge to do similar changes to other variables like `ContentUrl` because this too will otherwise run into similar issues some day.

**Comment by iJungleboy** [comment]
Code merged, so I guess we can close.
