### ISSUE TITLE
[Authorize(Roles = RoleNames.Everyone)] issue

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1293]
While using `[Authorize(Roles = RoleNames.Everyone)]` to decorate API controller I got access denied while testing with the `host` user. My expectation was that all users can access that endpoint and especially `host` user.

To test this more I created a new module `ToSic.Test3` using the external template in oqtane-2.0.2 install on IIS 10.
On all methods is `Test3Controller` I commented out default Authorize attributes. I did 2 tests.

# Test 1 with `[Authorize(Roles = RoleNames.Registered)]`
Decorated controller class with `[Authorize(Roles = RoleNames.Registered)]`, build and deployed.
After IIS 10 apppool restart I log in as `host` and open page with the Test3 module.
All looks OK.

![image](https://user-images.githubusercontent.com/2724850/116291738-3967c600-a795-11eb-93a2-0f45a1ae592f.png)

# Test 2 with `[Authorize(Roles = RoleNames.Everyone)]`
Decorated controller class with `[Authorize(Roles = RoleNames.Everyone)]`, build and deployed.

```cs
namespace ToSic.Test3.Controllers
{
    [Route(ControllerRoutes.Default)]
    [Authorize(Roles = RoleNames.Everyone)]
    public class Test3Controller : Controller
    {
        private readonly ITest3Repository _Test3Repository;
        private readonly ILogManager _logger;
        protected int _entityId = -1;

        public Test3Controller(ITest3Repository Test3Repository, ILogManager logger, IHttpContextAccessor accessor)
        {
            _Test3Repository = Test3Repository;
            _logger = logger;

            if (accessor.HttpContext.Request.Query.ContainsKey("entityid"))
            {
                _entityId = int.Parse(accessor.HttpContext.Request.Query["entityid"]);
            }
        }

        // GET: api/<controller>?moduleid=x
        [HttpGet]
        //[Authorize(Policy = PolicyNames.ViewModule)]
        public IEnumerable<Models.Test3> Get(string moduleid)
        {
            return _Test3Repository.GetTest3s(int.Parse(moduleid));
        }
```
After IIS 10 apppool restart I log in as `host` and open page with the Test3 module.
There is an error on the page.

![image](https://user-images.githubusercontent.com/2724850/116290405-b5f9a500-a793-11eb-821f-cd23bba5bf2b.png).

### Oqtane Event Log
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending, OrderedEnumerable`1 parent)
   at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at ToSic.Test3.Services.Test3Service.GetTest3sAsync(Int32 ModuleId) in C:\Projects\_Test\oqtane2\ToSic.Test3\Client\Services\Test3Service.cs:line 26
   at ToSic.Test3.Index.OnInitializedAsync() in C:\Projects\_Test\oqtane2\ToSic.Test3\Client\Modules\ToSic.Test3\Index.razor:line 52
```

### Test3Service.cs:line 23-27
```cs
        public async Task<List<Models.Test3>> GetTest3sAsync(int ModuleId)
        {
            List<Models.Test3> Test3s = await GetJsonAsync<List<Models.Test3>>(CreateAuthorizationPolicyUrl($"{Apiurl}?moduleid={ModuleId}", ModuleId));
            return Test3s.OrderBy(item => item.Name).ToList();
        }
```

### Index.razor:lines 48-59
```cs
    protected override async Task OnInitializedAsync()
    {
        try
        {
            _Test3s = await Test3Service.GetTest3sAsync(ModuleState.ModuleId);
        }
        catch (Exception ex)
        {
            await logger.LogError(ex, "Error Loading Test3 {Error}", ex.Message);
            AddModuleMessage("Error Loading Test3", MessageType.Error);
        }
    }
```

# Notes

Table [dbo].[ToSicTest3]
![image](https://user-images.githubusercontent.com/2724850/116292733-505ae800-a796-11eb-814e-855bd696be84.png)

Using Postman created first test GET request (with `host` credentials) directly to endpoint on controller decorated with `[Authorize(Roles = RoleNames.Registered)]` 

https://oqtane2-poc18.dev.sistemi.hr/1/api/test3/?moduleid=27 return HTTP 200 OK

![image](https://user-images.githubusercontent.com/2724850/116293483-3ff73d00-a797-11eb-823a-aaab1fa0d83c.png)

Using Postman created second test GET request (with `host` credentials) directly to endpoint on controller decorated with `[Authorize(Roles = RoleNames.Everyone)]` 

https://oqtane2-poc18.dev.sistemi.hr/1/api/test3/?moduleid=27 return HTTP 401 Unathorized

![image](https://user-images.githubusercontent.com/2724850/116294021-c449c000-a797-11eb-96e6-038876aee1f1.png)

The workaround was to use other role options:
`[Authorize(Roles = RoleNames.Host)]`
`[Authorize(Roles = RoleNames.Admin)]`
`[Authorize(Roles = RoleNames.Registered)]`

**Comment by sbwalker** [comment]
If you look at the Controllers in Oqtane.Server you will notice that none of them use [Authorize(Roles = RoleNames.Everyone)]. This is because [Authorize(Roles = RoleNames.Everyone)] means that there is no restriction in accessing the API method - it is essentially a method which allows public access. Public methods should not include any Authorize attribute - so you should never use [Authorize(Roles = RoleNames.Everyone)].

**Comment by sbwalker** [comment]
To provide a bit more background, the Web API [Authorize] attribute performs an IsInRole() validation check using the users roles which are encoded in the principal for authenticated users. RoleNames.Everyone is not a standard role - it is an internal concept which allows an administrator to provide public access to application resources such as pages, modules, or folders through the permission grid. An unauthenticated user does not have a principal, so it has no user roles - so there is no way that IsInRole() will ever return true.

**Comment by iJungleboy** [comment]
This is certainly confusing. Just for context, the reason why we wanted to use this is because `[AllowAnonymous]` is quite dangerous - it basically kills all security checks and AFAIK even Security-Token checks. So we avoid that at all cost. We thought `Everyone` would be the better implementation of this.

**Comment by tvatavuk** [comment]
> If you look at the Controllers in Oqtane.Server you will notice that none of them use [Authorize(Roles = RoleNames.Everyone)]. This is because [Authorize(Roles = RoleNames.Everyone)] means that there is no restriction in accessing the API method - it is essentially a method which allows public access. Public methods do not require any Authorize attribute - so you should never use [Authorize(Roles = RoleNames.Everyone)].

Thanks. Totally make sense. The solution is to go without Authorize attribute.
