### ISSUE TITLE
Update to .net core 3.1 for partial classes

### ISSUE THREAD

**Issue by fileman** [oqtane/oqtane.framework#130]
Should Oqtane be update to 3.1 preview 1 to support partial class for razor component and use code behind files?

**Comment by ADefWebserver** [comment]
I say we wait until AFTER 3.1 is released. I think this is expected to be December.

**Comment by sbwalker** [comment]
Oqtane should maintain its dependency on .NET Core 3.0... and we should only consider migrating after .NET Core 3.1 is released as RTM.
