### ISSUE TITLE
Add Page doesn't reload ContentPanel pages

### ISSUE THREAD

**Issue by fileman** [oqtane/oqtane.framework#131]
Add new page doesn't reload ContentPanel pages available.

I have to move to following code into OnParameterSet or there is another solution to reload it?

    protected override void OnParametersSet()
    {
        pages = new List<Page>();

        foreach(Page p in PageState.Pages)
        {
            if (UserSecurity.IsAuthorized(PageState.User, "View", p.Permissions))
            {
                pages.Add(p);
            }
        }
    }

**Comment by sbwalker** [comment]
I think your suggestion is the right solution

**Comment by sbwalker** [comment]
Fixed in latest PR
