### ISSUE TITLE
After adding an "External" developer module, getting: "package version 2.1.0" error

### ISSUE THREAD

**Issue by jasza2** [oqtane/oqtane.framework#1341]
Hello, I added a developer  "module  creator" and it correctly generated the module project as expected, however the project will not compile with the following error. 
I did try to reference the DLLS directly in the Ocqtane bin folder but it still gives this error:

```
Error	NU1102	Unable to find package Oqtane.Shared with version (>= 2.1.0)
  - Found 8 version(s) in nuget.org [ Nearest version: 2.0.2 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages	ScanMan.Scanner1.Package	C:\Users\User\source\repos\ScanMan.Scanner1\Package\ScanMan.Scanner1.Package.csproj
```

**Comment by leigh-pointer** [comment]
Hi @jasza2 looks like you are building a module with the next release.  Modify all project files and change the Oqtane references to version to 2.0.2 and the other packages to 5.0.0 that should help.

**Comment by jasza2** [comment]
perfect. worked. i downloaded the zip of v 2.0.2 and it worked as advertised.
i cant tell you how pleased I am to use this software, it includes every good feature from the old  DNN, but 10x easier to use. 
Thanks.
