### ISSUE TITLE
folder to find navigation bar data and basic code files

### ISSUE THREAD

**Issue by RohanNayaks** [oqtane/oqtane.framework#1364]
I am unable to find the navigation bar folder and basic data folder location. Can you please help me to find it.

I am using blazor template.

Thank you.

**Comment by sbwalker** [comment]
Oqtane is not a static web application created from a Visual Studio template. I would suggest you watch the Module development video series to become familiar with the development model:

https://www.youtube.com/watch?v=JPfUZPlRRCE&list=PLYhXmd7yV0elLNLfQwZBUlM7ZSMYPTZ_f
