### ISSUE TITLE
Begin code documentation

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1382]
I would like to invest a few hours to document some code which will also serve as a guideline for further code documentation. 

@sbwalker could you tell me which controllers / services / constants are probably the most important to start with?

**Comment by sbwalker** [comment]
I assume you mean class/method level documentation... I would suggest the public API would be the best place to start - so all Client Service methods and Server Controller methods. The repository is not meant to be a public API so its methods could be documented as a secondary priority.

**Comment by iJungleboy** [comment]
I just created a sample how I think it should be done

* https://docs.oqtane.org/api/Oqtane.Services.html 
    * the AliasService is now hidden
    * the IAliasService is there in the list with a short description
* https://docs.oqtane.org/api/Oqtane.Services.IAliasService.html 
    * Short description with cross-linking to Alias object
    * All methods described and where possible, cross-linked to Alias, Site and Tenant
    * Things I don't understand are marked as `todoc`
* https://docs.oqtane.org/api/Oqtane.Models.html
    * Shows short description of IAuditable and Alias
* https://docs.oqtane.org/api/Oqtane.Models.IAuditable.html
    * Just basic docs
* https://docs.oqtane.org/api/Oqtane.Models.Alias.html
    * Explains what an Alias is
    * Explains possible confusion of `AliasId` and `SiteId` (which I ran into 😉)
    * Cross linking to Site / Tenant
    * Inherits docs from the `IAuditable` interface

Pls have a quick peek, if OK I'll do some more in the same style and push the code with docs to the `oqtane.framework`. Pls also answer if it's ok to hide the concrete implementation if the interface should be used.

**Comment by sbwalker** [comment]
I agree with your approach for the documentation - and I agree with hiding the concrete implementation in favor of the interfaces.

**Comment by hishamco** [comment]
What's the status of this? Do you need any kind of help?

**Comment by sbwalker** [comment]
closing as substantial progress has been made on this item (thank you) and there is no reason why more PRs cannot be submitted following the existing examples.
