### ISSUE TITLE
Exception on first run (PrincipalValidator.cs)

### ISSUE THREAD

**Issue by Bitexirtz** [oqtane/oqtane.framework#1389]
PrincipalValidator.cs, Line 28, ab exception occurs on first run.

After I changed from "First" to "FirstOrDefault", I successfully execute.

line: 28: context.Principal.Claims.FirstOrDefault

**Comment by sbwalker** [comment]
When you say "first run" do you mean on a clean install or anytime you fire up the application?

**Comment by Bitexirtz** [comment]
Sorry. I mean clean install.
