### ISSUE TITLE
Module Development. - Data not being returned from framework

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1414]
Since upgrading my development environment my 2.0.2 framework modules do not return data when using the Get

```
MyBacklogIssue = await MyBacklogService.GetMyBacklogAsync(_BacklogItem.RecordId, ModuleState.ModuleId);
.....
CreateAuthorizationPolicyUrl(url, new Dictionary<string, int>() { { EntityNames.Module, entityId } })
"/1/api/MyBacklog/42?authmoduleid=27"
```

Returns null

**Comment by sbwalker** [comment]
it looks like you modified your 2.0.2 module code - as the snippet above is using the newer CreateAuthorizationPolicyUrl() method from 2.1.0?

**Comment by sbwalker** [comment]
If you want to modify your module for 2.1.0 you should look at this PR as it contains all of the code changes required to update the module creator template to 2.1.0

**Comment by sbwalker** [comment]
Note that your existing module DLL ( without any code changes ) should run on 2.1.0 without any issues. For example the sample Blog module runs fine on 2.1.0.

**Comment by leigh-pointer** [comment]
Yes the module run fine.
