### ISSUE TITLE
Profile Management

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#142]
An admin module is needed for managing Profile properties. This module should be developed in the standard manner ( with Index, Add, Edit, Delete capabilities ) and be exposed on the Admin Dashboard.

**Comment by ADefWebserver** [comment]
for now, community developers wanting to understand the "_standard manner ( with Index, Add, Edit, Delete capabilities )_ " can see this module: https://github.com/oqtane/oqtane.module.blogs

**Comment by sbwalker** [comment]
Actually in this case the module will be an internal "admin" module so should not be developed as an external module ( as per your suggestion above ). It should be added to the Oqtane.Client project Modules/Profile folder and use an approach to any of the other internal "admin" modules

**Comment by sbwalker** [comment]
Note that the entire back-end for Profile management is already built including the ProfileService which can be used for reading, writing, deleting Profile entities. So the only work remaining is the razor components.

**Comment by sbwalker** [comment]
done
