### ISSUE TITLE
Module creator solutions errors

### ISSUE THREAD

**Issue by mtxxx** [oqtane/oqtane.framework#1426]
You can use Module creator to create a 'new module' solution. The solution is created, but with errors.
1. There are references to not existed nugets packages. For example Oqtane.Shared v **2.1.0**. The latest version on nuget.org is Oqtane.Shared **2.0.2.**
2. If you change all Oqtane packages versions to 2.0.2, it's still not buildable. There are plenty of errors.

Please update a solution, created by a Module creator.

**Comment by sbwalker** [comment]
The Dev branch has Dev code which is not yet released. The module creator template has dependencies on 2.1 which is not yet released. You will need to choose "local version" until 2.1 is actually released.

**Comment by sbwalker** [comment]
The 2.1.0 packages are now posted on Nuget
