### ISSUE TITLE
Delete User Experience

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#143]
The current admin user experience in Oqtane diplays a Delete option for each entity record in the summary grid view. When the user selects the Delete option it displays a distinct Delete component where all of the fields for the entity are displayed in readonly mode. The user can choose to Delete or Cancel - and if they choose Delete it removes the record ( either via soft delete or hard delete depending on the entity ). 

The reason for this approach is that Delete is a serious/permanent action, so you want to provide the opportunity for a user to either confirm or cancel the action. Displaying a Delete component accomplishes this goal; however, the downside is that requires the development and ongoing maintenance of an additional component which contains more code/functionality than is truly necessary to accomplish the original goal.

Another common approach in product development is to simply display a Confirmation popup dialog when a user selects Delete from the summary grid view. This still provides  the opportunity for a user to confirm/cancel the action - and it eliminates the need for creating a separate dedicated Delete component. 

I would like to hear some feedback on whether Oqtane should transition to the Confirmation popup dialog approach.

**Comment by ADefWebserver** [comment]
It seems we need the "Confirmation popup dialog" either way, right? 

Meaning, I would not want to 'accidentally' click delete, not have a "Confirmation popup dialog", and then have to go hunting through the recycle bin each time...

**Comment by sbwalker** [comment]
The system already has a pseudo confirmation popup - it displays a dedicated Delete.razor component which has a Delete or Cancel option - which is the confirmation popup.

What I am asking is if we should move away from the current approach and display a simpler confirmation popup dialog from the main summary grid view.

**Comment by sbwalker** [comment]
One other item I should mention is that the framework already supports a mechanism so that you do not need to create a dedicated component for each action ( ie. Add, Edit, Delete, etc... ). In a module component you can specify a value for the IModuleControl.Actions property and the router will map the action on the route to this specification. So for example if you wanted to only create a single Edit.razor component which handled Add, Edit, and Delete functionality, you could specify the IModuleControl.Actions property to be "Add,Edit,Delete" and then when any of those actions were used in the route, it would render the Edit.razor component ( and within the Edit.razor you could use the PageState.Action property and the Id passed on the PageState.QueryString to control the flow of the logic ). I am mentioning this because there are currently no examples which utilize this feature in the framework but it is quite useful. However it does not address the original topic about what the standard Delete user experience should be  in Oqtane.

**Comment by ADefWebserver** [comment]
> I am mentioning this because there are currently no examples which utilize this feature in the framework but it is quite useful.

Can you provide so pseudo code so that I can try to incorporate that in one of the Blog posts I plan to do in the next two weeks?

**Comment by sbwalker** [comment]
In the code area of your component you would add the following declaration ( similar to SecurityAccessLevel ):

@code {
    public override string Actions { get { return "Add,Edit,Delete"; } }

This tells the framework that when a route contains an action of "Add", "Edit", or "Delete" it should render this component. This is essentially configuration-based routing rather than convention-based routing ( which is the default ).

**Comment by sbwalker** [comment]
Further to this topic of user experience, I believe the standard position for buttons when managing entities should be at the left side. This is because when you reduce the size of screen ( ie. on phones ) you want to make sure that the buttons are still visible and accessible. Currently the buttons in the Oqtane admin user interface are positioned at the right hand side ( ie. of modals and grids ) - which is more convenient for desktop users that typically use a right handed mouse, however, the user interface should be designed in an optimal manner for all form factors. 

Comments?

**Comment by ADefWebserver** [comment]
I vote left side 👍🏾

**Comment by sbwalker** [comment]
All admin UIs were modified to position action buttons on the left side of grids and ActionDialog was implemented throughout rather than using dedicated Delete.razor components
