### ISSUE TITLE
Impossible initialize Oqtane hosted in WebAssembly

### ISSUE THREAD

**Issue by bo-bac** [oqtane/oqtane.framework#1481]
1 clone repo
2 rebuild solution in VS
3 go to Oqtane.Server -> appsettings.json
4 change runtime to "Runtime": "WebAssembly",
5 comment //"RenderMode": "ServerPrerendered",
6 F5

Actual
![image](https://user-images.githubusercontent.com/4517566/122107487-c9d09780-ce23-11eb-91bb-e7dc6f8b3919.png)

Expected
![image](https://user-images.githubusercontent.com/4517566/122107842-3055b580-ce24-11eb-87ea-210064a8f629.png)

* the problem must be here
it is
`var culture = CookieRequestCultureProvider.ParseCookieValue(localizationCookie).UICultures[0].Value;`
should be
`var culture = CookieRequestCultureProvider.ParseCookieValue(localizationCookie)?.UICultures?[0].Value;`

**Comment by hishamco** [comment]
Thanks for reporting this, I will have look right now

**Comment by hishamco** [comment]
You are right @bo-bac , seems the occurs when the localization value is not present. This is not happen to my side because the localization cookie is already there in my browser ;)

Thanks again

**Comment by bo-bac** [comment]
yep, it is the problem on really first start
