### ISSUE TITLE
Error in Module templates

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1530]
The Get  `public Models.[Module] Get(int id)` method in the [Module]Controller has an incorrect IF statement which in turn returns nothing and logs an error

`if ([Module] != null && [Module].ModuleId != AuthEntityId(EntityNames.Module))`

the statement should be

`if ([Module] != null && [Module].ModuleId == AuthEntityId(EntityNames.Module))`

**Comment by sbwalker** [comment]
Please submit a PR

**Comment by leigh-pointer** [comment]
@sbwalker done

**Comment by leigh-pointer** [comment]
Added the correct operator.
