### ISSUE TITLE
Unable to Deploy Oqtane on IIS via Azure CI/CD  and Visual Studio 2019

### ISSUE THREAD

**Issue by KillDroner** [oqtane/oqtane.framework#1532]
Hey, I was trying to deploy latest Oqtane code on IIS and there are issues regarding that.
(Deployed via Azure Build Pipelines (DevOps))
- When I'm trying to build and deploy Oqtane project via Azure DevOps, there are only these files which are published in artifact.

![image](https://user-images.githubusercontent.com/44177865/124450633-4101a780-dda2-11eb-947b-ce0c603c9c97.png)

- I noticed this once I published this artifact from release pipeline.
- when I try to access the site after this deployment this is the page I get.

![image](https://user-images.githubusercontent.com/44177865/124452001-9be7ce80-dda3-11eb-91ce-2f93a1fa2c73.png)

- To confirm if you ask that I have to install the required .Net framework, I have already installed all the required dependencies.
- When I ran Oqtane.Server.exe file in Powershell I saw this issue.

![image](https://user-images.githubusercontent.com/44177865/124452801-5aa3ee80-dda4-11eb-991a-183403dfa5af.png)

- As this says it can't find the deps file in some path and there is no folder created by the name Runtime.

I'm not sure why there are these errors as I haven't made a single change to the project.
I tried to explain these issues as clearly as I could Please assist with this if you can.

(Note: When I run the Project in Visual Studio and run it without deploying it works fine)

![image](https://user-images.githubusercontent.com/44177865/124454972-afe0ff80-dda6-11eb-8bfc-629cde42879b.png)

**Comment by snickler** [comment]
A few things to try:

- Run `dotnet --info` on both your local computer and the server and make sure that you're running the same versions of the .NET SDKs.
- Check the TargetFramework in your projects and make sure that they aren't mixing `.netcoreapp3.1` and `net5.0`
- In your Azure Pipelines deployment (either Classic or YAML), make sure you're building/publishing the project using the same SDK/Runtime version that is defined in your project. Also enable the `system.debug` environment variable in your pipeline to show the full output of your run.

**Comment by KillDroner** [comment]
> A few things to try:
> 
>     * Run `dotnet --info` on both your local computer and the server and make sure that you're running the same versions of the .NET SDKs.
> 
>     * Check the TargetFramework in your projects and make sure that they aren't mixing `.netcoreapp3.1` and `net5.0`
> 
>     * Make sure your server has the ASP.NET Core Hosting Bundle that corresponds to the tfm in your project.
> 
>     * In your Azure Pipelines deployment (either Classic or YAML), make sure you're building/publishing the project using the same SDK/Runtime version that is defined in your project. Also enable the `system.debug` environment variable in your pipeline to show the full output of your run.

Thanks for the input, I have already validated all these details. The main issue I think is that when I build the project via Azure CI/CD and checked the artifact the process created it didn't had any referenced dll as you can see in the above image.

**Comment by snickler** [comment]
> > A few things to try:
> > ```
> > * Run `dotnet --info` on both your local computer and the server and make sure that you're running the same versions of the .NET SDKs.
> > 
> > * Check the TargetFramework in your projects and make sure that they aren't mixing `.netcoreapp3.1` and `net5.0`
> > 
> > * Make sure your server has the ASP.NET Core Hosting Bundle that corresponds to the tfm in your project.
> > 
> > * In your Azure Pipelines deployment (either Classic or YAML), make sure you're building/publishing the project using the same SDK/Runtime version that is defined in your project. Also enable the `system.debug` environment variable in your pipeline to show the full output of your run.
> > ```
> 
> Thanks for the input, I have already validated all these details. The main issue I think is that when I build the project via Azure CI/CD and checked the artifact the process created it didn't had any referenced dll as you can see in the above image.

Mind sharing the portion of your YAML file that does the build and publish? 

If you run `dotnet publish -c Release` locally, do you see the same set of files in your `bin\release\net5.0\publish` directory? The `publish` directory is the one you should be deploying to your servers if you haven't explicitly specified an output folder.

 Also, your screenshot is showing the `obj` folder, rather than `bin`.

**Comment by KillDroner** [comment]
> > > A few things to try:
> > > ```
> > > * Run `dotnet --info` on both your local computer and the server and make sure that you're running the same versions of the .NET SDKs.
> > > 
> > > * Check the TargetFramework in your projects and make sure that they aren't mixing `.netcoreapp3.1` and `net5.0`
> > > 
> > > * Make sure your server has the ASP.NET Core Hosting Bundle that corresponds to the tfm in your project.
> > > 
> > > * In your Azure Pipelines deployment (either Classic or YAML), make sure you're building/publishing the project using the same SDK/Runtime version that is defined in your project. Also enable the `system.debug` environment variable in your pipeline to show the full output of your run.
> > > ```
> > 
> > 
> > Thanks for the input, I have already validated all these details. The main issue I think is that when I build the project via Azure CI/CD and checked the artifact the process created it didn't had any referenced dll as you can see in the above image.
> 
> Mind sharing the portion of your YAML file that does the build and publish?
> 
> If you run `dotnet publish -c Release` locally, do you see the same set of files in your `bin\release\net5.0\publish` directory? The `publish` directory is the one you should be deploying to your servers if you haven't explicitly specified an output folder.
> 
> Also, your screenshot is showing the `obj` folder, rather than `bin`.

The Process for build I'm using is a classic pipeline which looks like this 
![image](https://user-images.githubusercontent.com/44177865/124698384-614a7700-df06-11eb-99a0-103d61e79dbb.png)

When I run `dotnet publish -c Release Oqtane.sln` locally it publishes the files in the same path as you mentioned but the required dll are present as well , this is the resultant folder for the above command 
![image](https://user-images.githubusercontent.com/44177865/124698807-37de1b00-df07-11eb-9832-c3ab9ec1cf3e.png)
there are other files as well but you get the idea.

Here's the output for the command 
![image](https://user-images.githubusercontent.com/44177865/124698884-68be5000-df07-11eb-9e1f-f803c5b42eb4.png)


Regarding the `obj` folder there's only that in the build artifact, there's no bin folder there. I don't think there should be any though what's missing in the build artifact is the `runtime` folder and the dll's it's supposed to deploy like in the above screenshot.

**Comment by snickler** [comment]
Is your `Build Solution` task publishing at all? If it's just building in release, that's not enough - you need to publish. 

Actually, since this is all a .NET 5 project, use the `.NET Core` Task, using the publish command.

![image](https://user-images.githubusercontent.com/4016293/124752547-fdb84d80-def5-11eb-8b00-8b67d6a93018.png)

**Comment by snickler** [comment]
I'd say this issue is more with .NET Core deployment from Azure Pipelines and not specific to Oqtane.

**Comment by KillDroner** [comment]
I have checked multiple times if the `Build Solution` is publishing the files. It's publishing all the files in the `Build.SourceDirectory` but when I check it's artifact directory There are not enough files to run the Project

- I have also checked that when I am running the build, somewhere in between the copy process the Visual Studio build process skips the package references 

![image](https://user-images.githubusercontent.com/44177865/124766617-b57c4800-df54-11eb-9af5-8dad39c76599.png)

I couldn't thinks of anything to get it to work. 

Today, I was trying to do the same publish process as you mentioned but it fails every time.  I'm trying to get the publish to work right now to validate if I can get all the files.

**Comment by KillDroner** [comment]
I'm not sure if this issue will be related to Azure deployment as I already have Oqtane 2.0.1 running with the similar pipeline and it works completely fine. This issue is only with the latest version.

**Comment by snickler** [comment]
> I'm not sure if this issue will be related to Azure deployment as I already have Oqtane 2.0.1 running with the similar pipeline and it works completely fine. This issue is only with the latest version.

Which part is failing during the publishing? Also, have you tried the `MSBuild Arguments` I provided in the `Build Solution` task?

It would be helpful to see some logs / config that you're able to share.

One other thing I just thought of since you're using the `Build Solution` task: Create a `Copy files` task that copies

`$(Build.SourcesDirectory)\Oqtane.Server\bin\$(Build.Configuration)\net5.0\` to `$(Build.ArtifactStagingDirectory)`. 

All of the examples you're showing is from the `Build.SourcesDirectory`, but nothing from the `Build.ArtifactStagingDirectory`.  You should not be deploying any files from the `Build.SourcesDirectory`. Those have entirely different paths.

Honestly, I'd look at using the YAML Pipelines instead of Classic. There are numerous tutorials out there for building and deploying to IIS with .NET that may be more beneficial, especially because a `dotnet publish` shouldn't be failing in the .NET Core Task at all, and based on what's happening here - this deployment problem isn't an issue related to Oqtane. 

https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive

**Comment by KillDroner** [comment]
> > I'm not sure if this issue will be related to Azure deployment as I already have Oqtane 2.0.1 running with the similar pipeline and it works completely fine. This issue is only with the latest version.
> 
> Which part is failing during the publishing? Also, have you tried the `MSBuild Arguments` I provided in the `Build Solution` task?
> 
> It would be helpful to see some logs / config that you're able to share.
> 
> One other thing I just thought of since you're using the `Build Solution` task: Create a `Copy files` task that copies
> 
> `$(Build.SourcesDirectory)\Oqtane.Server\bin\$(Build.Configuration)\net5.0\` to `$(Build.ArtifactStagingDirectory)`.
> 
> All of the examples you're showing is from the `Build.SourcesDirectory`, but nothing from the `Build.ArtifactStagingDirectory`. You should not be deploying any files from the `Build.SourcesDirectory`. Those have entirely different paths.
> 
> Honestly, I'd look at using the YAML Pipelines instead of Classic. There are numerous tutorials out there for building and deploying to IIS with .NET that may be more beneficial, especially because a `dotnet publish` shouldn't be failing in the .NET Core Task at all, and based on what's happening here - this deployment problem isn't an issue related to Oqtane.
> 
> https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive

I did that previously what you're suggesting, I made a copy files task using Powershell for that.

**Comment by KillDroner** [comment]
With the setting you previously suggested, this is the output I get in the artifact directory `$(Build.ArtifactStagingDirectory)`

![image](https://user-images.githubusercontent.com/44177865/125062355-ea5edb00-e0cb-11eb-8c2f-325b5e1b5d20.png)

**Comment by snickler** [comment]
> With the setting you previously suggested, this is the output I get in the artifact directory `$(Build.ArtifactStagingDirectory)`
> 
> ![image](https://user-images.githubusercontent.com/44177865/125062355-ea5edb00-e0cb-11eb-8c2f-325b5e1b5d20.png)



It looks like you used the option to zip projects. The `Oqtane.Server.zip` contains the published output that needs deployed to the IIS Server. You'll have to use another task to unzip that or just use powershell.

**Comment by KillDroner** [comment]
> > With the setting you previously suggested, this is the output I get in the artifact directory `$(Build.ArtifactStagingDirectory)`
> > ![image](https://user-images.githubusercontent.com/44177865/125062355-ea5edb00-e0cb-11eb-8c2f-325b5e1b5d20.png)
> 
> It looks like it zipped the projects. The `Oqtane.Server.zip` contains the published output that needs deployed to the IIS Server. You'll have to use another task to unzip that or just use powershell.

Thanks, I'll check that.
