### ISSUE TITLE
oqtane in 'readonly' state

### ISSUE THREAD

**Issue by rodrigoratan** [oqtane/oqtane.framework#1536]
I installed Oqtane in a subdomain of my site, it installed OK, but when I try to edit anything, it wont save (and wont raise an error either). I cant edit the content of an HTML module, can't edit my name in the profile, I dont see any error on the event log (neither in Oqtane nor in browser console)

The site is https://oqtane.ratan.com.br/ 

Any clue what might be happening?

**Comment by leigh-pointer** [comment]
@rodrigoratan 
Can you check that you have webDAV turned off?

**Comment by rodrigoratan** [comment]
I'll check now

**Comment by rodrigoratan** [comment]
![image](https://user-images.githubusercontent.com/964066/124651753-b1c3c500-de71-11eb-8e34-3a8bfa678f50.png)

Well (still searching), I dont find anything about WebDAV but the "Web Deploy Publishing" checkbox is unchecked

**Comment by leigh-pointer** [comment]
@rodrigoratan  Hold on....

**Comment by leigh-pointer** [comment]
@rodrigoratan update your web config to:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <modules>
        <remove name="WebDAVModule" />
      </modules>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
        <remove name="WebDAV" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Oqtane.Server.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
  <system.web>
    <compilation tempDirectory="D:\Inetpub\vhosts\studio-elf.ga\tmp" />
  </system.web>
</configuration>
```

**Comment by rodrigoratan** [comment]
It now works!!! THANKS! Saved my life, I have a meeting in 50 minutes to show Oqtane to a prospect client!!! :-D

**Comment by leigh-pointer** [comment]
@rodrigoratan pleased that it is sorted and good luck with your prospect.
