### ISSUE TITLE
Module creator - Module name change wont update its location

### ISSUE THREAD

**Issue by rodrigoratan** [oqtane/oqtane.framework#1540]
![image](https://user-images.githubusercontent.com/964066/124656786-0407e480-de78-11eb-9de6-c0b6a4901135.png)

When I'm creating a new module using Module Creator, I fill Owner, module name, description, template, framework reference... and then it informs me where it will be saved...

but then if I change the module name it wont reflect in the save location..

So I guess the UI should block editing the Module Name or the Save location should reflect the Module name changes...

**Comment by sbwalker** [comment]
When you click Create Module, the Location will be updated with the correct path/name.

**Comment by rodrigoratan** [comment]
Yeah, I was not thinking in 'realtime' but something event based, so when you "TextChanged" the Module Name it will reflect the Location always if template is already selected

The way it is now if you change your mind and change the module name BEFORE submitting the form it will not affect the location and this may confuse the user later finding the file (happened to me)... If I follow the form in the designed order it works fine!
