### ISSUE TITLE
Username readonly on Register form

### ISSUE THREAD

**Issue by GusBeare** [oqtane/oqtane.framework#1555]
Been having a play with Oqtane and trying to register a user.  But the user name is read only so I can't fill it in.
Am I doing something wrong?

![Capture](https://user-images.githubusercontent.com/5166509/125793888-0efb86f1-cdca-4fdd-852b-8370a177de90.JPG)

**Comment by leigh-pointer** [comment]
@GusBeare I see the issue. I will raise a PR to fix the issue.

**Comment by GusBeare** [comment]
thanks!

**Comment by sbwalker** [comment]
@leigh-pointer was this caused by the recent bootstrap5 changes in Dev?

**Comment by leigh-pointer** [comment]
@sbwalker no the readonly was there when it was in table form.

**Comment by sbwalker** [comment]
Looking at the history, I mistakenly made this change in 2.2.0 when I was doing some refactoring of the user management components.

**Comment by sbwalker** [comment]
@GusBeare I previously did some work on a DNN to Oqtane migration utility which was capable of importing a site export from DNN and creating all of the pages/modules/permissions in Oqtane. However one major limitation was that it could not  import the users - which is a fairly important use case. Do you think a utility like this would be valuable... or do you think most DNN site owners would rather rebuild their site manually?

**Comment by GusBeare** [comment]
@sbwalker interesting idea. It's hard to say. I've not worked with DNN for a few years now and many of those projects have already been ported to something else.  You'd have to ask the community.   I used to use Redgate Tools to transfer data between installations. It worked once I had tailored scripts set up but it was a fiddle and prone to error.
