### ISSUE TITLE
External Theme should by copied to Oqtane.Server

### ISSUE THREAD

**Issue by nicpitsch** [oqtane/oqtane.framework#1563]
**External Theme Template** (oqtane.framework/Oqtane.Server/wwwroot/Themes/Templates/External/)

Shouldn't the xcopy command in the 3th line of [debug.cmd](https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Server/wwwroot/Themes/Templates/External/Package/debug.cmd) be:
XCOPY "..\Client\wwwroot\*" "..\..\[RootFolder]\Oqtane.`Server`\wwwroot\" /Y /S /I
instead of
XCOPY "..\Client\wwwroot\*" "..\..\[RootFolder]\Oqtane.`Client`\wwwroot\" /Y /S /I

**Comment by sbwalker** [comment]
yes, I believe this is a bug - please submit a PR

**Comment by sbwalker** [comment]
fixed in #1564
