### ISSUE TITLE
Unable to create new page in certain circumstance

### ISSUE THREAD

**Issue by garethvdl2** [oqtane/oqtane.framework#1607]
1) Control Panel -> Add
2) Add a name
3) Select My-Page in Parent drop down
4) Select Site Root in Parent drop down
5) Add url path
6) Save

Error handling handles it to event logs but it is still a ' Object reference not set to an instance of an object.'
In \Oqtane.Client\Modules\Admin\Pages\Add.razor, ParentChanged has set the _parentid = -1 which is then not handled on line 297 on Save.

**Comment by sbwalker** [comment]
Thank you very much for reporting this issue... upon further inspection it appears to be a problem in both Add Page and Edit Page. The problem is related to inconsistent handling of the Site Root specification. I will resolve this today.
