### ISSUE TITLE
UTF8 Support

### ISSUE THREAD

**Issue by michalss** [oqtane/oqtane.framework#1608]
Hi is there a way how to make oqtane support UTF8 chars please ? For example chars like this ěščřžýáí.

Regards

**Comment by sbwalker** [comment]
Can you please elaborate on your question... in particular, where does Oqtane not support UTF8 currently?

**Comment by michalss** [comment]
Simple check pls this screens..
![image](https://user-images.githubusercontent.com/1000729/129591004-727b84d6-763d-4b3c-823d-46793b8d223c.png)

And after save it looks like this:

![image](https://user-images.githubusercontent.com/1000729/129592260-a8612bd9-249f-41b3-ad22-13d2a6c3504b.png)

It removes the special chars..

**Comment by michalss** [comment]
OK i found out why it is like this. It looks like DB tables has character set to latin and this set does not support special chars. It is my fould since i was the one who create the DB. Som please make sure what is your default setup for char set on mysql.. :)

**Comment by michalss** [comment]
OK i have to reopen, not works. I can change it directly in DB but it is not possible to do in Admin section..

**Comment by sbwalker** [comment]
This problem seems to be isolated to the mySQL database provider - it works fine on SQL Server. Have you tried to include a CharSet=utf8; command in your connection string for your MySQL database?

**Comment by michalss** [comment]
I did it does not work. it is the same....

**Comment by hishamco** [comment]
Set the collation in your database, for more information please refer to https://www.mysqltutorial.org/mysql-collation/

**Comment by michalss** [comment]
> Set the collation in your database, for more information please refer to https://www.mysqltutorial.org/mysql-collation/

This wont help you of course..

**Comment by hishamco** [comment]
Wait a minute, if the data in the database is right which what I see, the issue is encoding in the web side

**Comment by hishamco** [comment]
I can investigate on this, I will try to use Arabic instead

**Comment by sbwalker** [comment]
Are you running Oqtane on Server or WebAssembly?

**Comment by michalss** [comment]
Both the same..

**Comment by hishamco** [comment]
@sbwalker I'm trying the latest bits to reproduce this issue, nothing but during the setup I got this error **Invalid column name 'True'**

**Comment by sbwalker** [comment]
@hishamco thank you for letting me know. This new error is related to the change in PR #1603. I will back out the PR as it is not a valid solution. I am wondering if @cnurse has any thoughts on #1603.

**Comment by hishamco** [comment]
![UTF8](https://user-images.githubusercontent.com/3237266/130320083-8568547c-4739-4973-814d-9aa70afa6573.png)

I can verify this is not an Oqtane issue, please check your database collation or share that database are you using so I can try it from my side

**Comment by michalss** [comment]
Using MariaDB and collation in on the screens above..

**Comment by hishamco** [comment]
Any updates on this or shall we close it?
