### ISSUE TITLE
Module Suite and permissions

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1615]
I have created a suite of modules that reside in the same assembly.   
my first module is MyCompany.MyProject
the second is  MyCompany.MyProject.Module2
the third is  MyCompany.MyProject.Module3

Adding the modules the separate pages and setting the permissions to the same then the modules will render.

If first module is set to "Registered Users" and the second to "All users" then the second module will error with 
"Object reference not set to an instance of an object."

Question is:
**Is this by design or an Issue?**

**Comment by sbwalker** [comment]
The inconsistent use of namespaces may be causing some confusion when the module is loaded as the system uses the namespace as a prefix key to associate resources. The MyCompany.MyProject may be related to MyCompany.MyProject.Module2 the MyCompany.MyProject.Module2 namespace contains MyCompany.MyProject. I will need to investigate further but I would suggest that you use unique namespaces for all modules ie. MyCompany.MyProject.Module1

**Comment by leigh-pointer** [comment]
@sbwalker 
>  I would suggest that you use unique namespaces for all modules ie. MyCompany.MyProject.Module1

I will explore, thanks.
