### ISSUE TITLE
Typo in Folder Management modal

### ISSUE THREAD

**Issue by artmedia** [oqtane/oqtane.framework#1636]
![typo](https://user-images.githubusercontent.com/4210561/131343570-bd853c21-e0fa-46ac-bffa-fd0b68fd4f79.png)

just a typo in Folder Management, "Name" repeated in Folder Management modal (v.2.2.0)

**Comment by leigh-pointer** [comment]
This is not showing in the current codebase

![image](https://user-images.githubusercontent.com/9447612/131359210-8dea5430-d8b3-43f1-981c-b284e166a10b.png)

**Comment by sbwalker** [comment]
Yes this was already fixed in Dev
