### ISSUE TITLE
ServerPrerendered Oqtane 2.2 missing html output produced by dynamic components (themes, modules)

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1640]
When ServerPrerendered render mode is enabled in Oqtane 2.2, html output from themes and modules is missing in first render (server prerendered), effectively making **ServerPrerendered** feature not useful.

In Oqtane 2.2.0 for "Server" runtime, "**ServerPrerendered**" render mode is enabled.

![image](https://user-images.githubusercontent.com/2724850/131885688-e5431ddf-30bf-4131-87dc-c1381fadd549.png)

**appsettings.json** has correct runtime configuration.

```json
  "Runtime": "Server",
  "RenderMode": "ServerPrerendered",
```

Server prerendered html output is visible in browser as view source.

```html
<html>
<body>
<!--StartFragment-->

<!DOCTYPE html>
--
  | <html>
  | <head>
  | <meta charset="utf-8" />
  | <meta name="viewport" content="width=device-width">
  | <title>Oqtane</title>
  | <base href="/" />
  | <link id="app-favicon" rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
  | <!-- stub the PWA manifest but defer the assignment of href -->
  | <link id="app-manifest" rel="manifest" />
  | <link rel="stylesheet" href="css/app.css" />
  | <script src="js/app.js"></script>
  | <script src="js/loadjs.min.js"></script>
  |  
  | </head>
  | <body>
  | <input name="__RequestVerificationToken" type="hidden" value="CfDJ8JMqTNi6Rg9Lmit24AonDQAkydsiMGLBRQ4buFtLswQYrRo6k5XFf1hk1xtC0d_qcigsf_dlpTvIOR8OG61495OqCpw2PFMYSXaAcIIoLXChRm35y4FaaELmrpE1oXm0NncpJEe09o1y8sNXE0ap43A" />
  | <app>
  | <!--Blazor:{"sequence":0,"type":"server","prerenderId":"dca4b913b18b48309ecc7810f40fd0c5","descriptor":"CfDJ8JMqTNi6Rg9Lmit24AonDQBVgR9M8lt\u002Bg/Pi59cVeIl7ZlfNglViVB7Xkrc4danvzNhnz83EvHv0hzcvxcXKnP5XSgqlWD4UrnOLQg5\u002BYgwfc2UHYk3VeD6kATWsyy0uuf1KlLI9Q/nD2qEzXi/ZhfLBUN8mPmkw9AENMrhhHAnfBsX8nyr6n0h92r9r8hu7wEvXcOzgxB5tygc3L5EL0/\u002BVtK\u002BefY\u002BCpNQ2nMgsPKAgk014gpzaxuWGV8GfMrCn3KV3GpEUyguLLYIAXgmN0z2WU43HLvoaiDFRksbNuTVzkcYwL8aDCk8kCSjEWYzRXtZAukrixvEHuUSPNe\u002B51ViuWIa/4PUno/6Bh8nAyKF5"}--><!--Blazor:{"prerenderId":"dca4b913b18b48309ecc7810f40fd0c5"}-->
  | </app>
  |  
  | <div id="blazor-error-ui">
  |  
  | An error has occurred. This application may no longer respond until reloaded.
  |  
  |  
  | <a href="" class="reload">Reload</a>
  | <a class="dismiss">🗙</a>
  | </div>
  |  
  | <script src="js/interop.js"></script>
  |  
  | <script src="_framework/blazor.server.js"></script>
  |  
  | </body>
  | </html>

<!--EndFragment-->
</body>
</html>
```

This server prerendered html code contains **Blazor** starting and ending html comments with `prerenderId` that wraps server prerendered html output from App.razor component in _Host.cshtml.

```razor
<component type="typeof(Oqtane.App)" render-mode="@Model.RenderMode" />
```
**App.razor** component hosts **SiteRouter.razor** component that is responsible for activation of dynamic components (themes, modules).

The issue is that App.razor component server prerendered html output is empty. It is missing html output from themes and modules.

SiteRouter component execution is controlled by flag **_initialized**, that will become true in **OnAfterRenderAsync** event. This is too late for the first render. This disables html output from dynamic components on the first render.

https://github.com/oqtane/oqtane.framework/blob/ddeb05dfe26dbaacda483511cedaa6bbe31fd38b/Oqtane.Client/App.razor#L5-L54

In pre 2.2 Oqtane versions flag **_initialized** was set to true in **OnParametersSetAsync** event that happens before the first render.

**Comment by sbwalker** [comment]
The alias resolution was moved earlier in the lifecycle in 2.2 and the antiforgery token was added to the sitestate - and it can only be captured in OnAfterRenderAsync. It sounds like this impacted pre-rendering. This is going to require some investigation to determine a solution.

**Comment by sbwalker** [comment]
I just reviewed your suggested fix and it looks good - we would just need to test the behavior on Blazor Server and WebAssembly - during initial install as well regular site interaction to ensure there are no issues.

**Comment by sbwalker** [comment]
Investigating this further, the reason why the _initialized = true logic was moved to OnAfterRenderAsync in 2.2. was not because of the AntiForgeryToken or Alias resolution - it was because there was a very obvious "flicker" in the browser which occurs because content is being rendered prior to the CSS links being dynamically added to the page. The _initialized flag was delaying the rendering until later in the life cycle when the CSS links are available - creating a more seamless user experience. However it appears that this approach conflicts with the pre-rendering support - which is why you logged this bug. I would really like to find a solution which preserves the user experience but also supports pre-rendering but I am not sure if its possible.

**Comment by sbwalker** [comment]
One possible approach is to set _initialized = true in OnParametersSetAsyc when render mode is set to ServerPreRendered... and set  _initialized = true in OnAfterRenderAsync when render mode is set to Server. This would provide an option to preserve the user experience for web apps - but allow provide an option to enable server prerendering for web sites. @tvatavuk thought?

**Comment by sbwalker** [comment]
@tvatavuk I found a solution for this issue. I added a div wrapper to app.razor with a default style of display: none; and then in OnAfterRenderAsync I remove the style. This still allows the content to be sent to browser during pre-rendering but eliminates the browser "flicker" user experience issue.
