### ISSUE TITLE
After Delete Page, Cant create page of same name

### ISSUE THREAD

**Issue by rchibnik** [oqtane/oqtane.framework#1645]
I created a page named "CMS" and instead of turning off navigation, I deleted it.

When I try to re-create a page named CMS i get the error:
A page with path CMS already exists for the selected parent page. The page path needs to be unique for the selected parent.
but I can't find the page in my list of pages,  So the name CMS is no longer available to use as a page.

A minor defect - hopefully an easy fix.

I love Oqtane. Thanks for creating such an excellent framework. I look forward to using it for years to come.

**Comment by leigh-pointer** [comment]
The CMS page is not truely deleted until you clean out the recycle bin. This is found in the manager settings.

**Comment by hishamco** [comment]
> The CMS page is not truely deleted until you clean out the recycle bin

Good point, nothing but I suggest to be able to create a new page with the same name, similar to what Windows is doing while deleting a file

**Comment by rchibnik** [comment]
Thanks - found the recycle bin and confirmed that it works as designed.
