### ISSUE TITLE
UX issue on child site when moving module on page other than home page

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1647]
There is UX issue when moving module on page, that is not home page, on child site.

We have child site http://localhost:44357/s20
- with page P1 under home page http://localhost:44357/s20/p1
  - with 3 html modules on P1 page

On page P1, on second html module, in module action menu select **Move Up** option.

![image](https://user-images.githubusercontent.com/2724850/132471413-ca492ebf-719f-4974-81ee-2139205639c5.png)

After Move Up option is executed, the browser shows home page, that is in edit mode now. This is UX issue.

![image](https://user-images.githubusercontent.com/2724850/132471255-c85970d2-2844-4b24-a876-105823a0bbbc.png)

It is expected to stay on page P1, with page in edit mode.

Here is small screencast that demonstrate this ux issue.
- https://www.screencast.com/t/2q8Qgc6hne8Y

**Comment by leigh-pointer** [comment]
It appears that the PageState is incorrect.  Diving into the problem I see that the page state is created but references the default site. this in return holds the incorrect Alias.  So when the NavigationManager navigates to the desired route, it cant be found which in turn routes home!

**Comment by leigh-pointer** [comment]
Digging deep it seems to get more strange! 
![image](https://user-images.githubusercontent.com/9447612/132647871-7703589b-4a75-41ac-95d9-970fa58ae296.png)
