### ISSUE TITLE
Wish: Inner-Chanel for Pre-Release information

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1692]
Oqtane is still evolving quickly, and sometimes new features mean something breaks. This is to be expected and part of doing business. 

What would help though is if plugin-makers (like 2sxc) could get a heads-up ca. 1 Week before releasing another version, so we have time to test / adjust the plugin to survive changes. For example, Oqtane 2.2 had a few breaking changes like the removal of jQuery or changes in WebAPI authentication which meant 2sxc broke. 

I don't know yet if 2.3 breaks anything in 2sxc, but if it does, people may already have stress after upgrading and finding a broken system. So it would be helpful if we could subscribe to some kind of pre-release notification, so we know when the next real release (not bugfixes, but real releases) are about to come.

**Comment by leigh-pointer** [comment]
But you have full access to the code base! I cant see what more you could get, than that! Oqtane is very transparent and detailed in the road map!
________________________________
From: iJungleboy ***@***.***>
Sent: Monday, September 27, 2021 9:09:06 AM
To: oqtane/oqtane.framework ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oqtane/oqtane.framework] Wish: Inner-Chanel for Pre-Release information (#1692)


Oqtane is still evolving quickly, and sometimes new features mean something breaks. This is to be expected and part of doing business.

What would help though is if plugin-makers (like 2sxc) could get a heads-up ca. 1 Week before releasing another version, so we have time to test / adjust the plugin to survive changes. For example, Oqtane 2.2 had a few breaking changes like the removal of jQuery or changes in WebAPI authentication which meant 2sxc broke.

I don't know yet if 2.3 breaks anything in 2sxc, but if it does, people may already have stress after upgrading and finding a broken system. So it would be helpful if we could subscribe to some kind of pre-release notification, so we know when the next real release (not bugfixes, but real releases) are about to come.

**Comment by iJungleboy** [comment]
@leigh-pointer What I mean is that before a release third party plugins should be tested as early as possible.

But we cannot test it on every commit. For example, between v2.2 and 2.3 there was no release for ca. 3 months - so of course we cannot aggressively test during that time and work around things which may be temporary. 

What would help us is a kind of "next release should be out in 2 weeks" heads-up.

**Comment by sbwalker** [comment]
@iJungleboy I agree with you that a direct communication channel is important for developers building extensions. This could be facilitated by the registry on oqtane.net since this is the location where extensions are expected to be registered.
