### ISSUE TITLE
Remove Web.Config from Upgrade package

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1702]
It is required for Oqtane to run that WebDAV be turned off but, some hosting provider do not allow this option or is not available in the PLESK Hosting Control Panel.  The only way to disable WebDAV in this case is to modify the web.config to remove webDAV.  

These settings get overwritten with the new web.config file in the upgrade package.

**Comment by sbwalker** [comment]
this can be added to the release.cmd in the Oqtane.Package folder.
