### ISSUE TITLE
Need tooltips to explain what some of the input fields are

### ISSUE THREAD

**Issue by abukres** [oqtane/oqtane.framework#171]
There's no documentation and no tooltips to tell us what some of the vague options are.
For example, the Path field when creating a new page. I don't know what that this. A tooltip next to the label explaining what the field is for and an example value goes a long way.

**Comment by ADefWebserver** [comment]
@sbwalker Should  this be part of a broader discussion on localization?

**Comment by sbwalker** [comment]
In the short term I think it would be sufficient to solve this with a generic "Label" component which allows the developer to provide some HelpText and displays it as a tooltip ( much like the DNN Label https://uxguide.dotnetnuke.com/UIPatterns/LabelandInput.html ). In the longer term, both the label and help text would need to be localizable but I am hesitant to go down this path yet as there is no guidance from Microsoft on how to implement localization.

**Comment by hishamco** [comment]
@sbwalker I can help and participate on localization, I did many contribution in the localization APIs itself, many blogs and contribute to [SimplCommerce](https://github.com/simplcommerce/SimplCommerce) & [OrchardCore](https://github.com/OrchardCMS/OrchardCore) localization

**Comment by sbwalker** [comment]
Does it make more sense to create a custom Label component n Blazor - or to use the standard Bootstrap data-toggle="tooltip" syntax?

**Comment by ADefWebserver** [comment]
> Does it make more sense to create a custom Label component n Blazor - or to use the standard Bootstrap data-toggle="tooltip" syntax?

If we use the Bootstrap tooltip:

1. It is already there
2. One less piece of code for the project to maintain

**Comment by sbwalker** [comment]
The one downside to the Bootstrap approach is that for performance reasons the tooltip data-apis are opt in, which  means to use tooltips you must initialize them yourself with the tooltip() method. Which basically means you need to run some Javascript on every page.

**Comment by ADefWebserver** [comment]
> Which basically means you need to run some Javascript on every page.

I think that if this were enabled when in Administration mode that would be acceptable.

**Comment by sbwalker** [comment]
There are forms which are visible to non-Administrators as well - ie. registered users need to manage their user profile, unauthenticated users need to be able to register. So the solution needs to cater to all user scenarios. I have done more research on this and I am surprised at how a seemingly simply concept has so few viable solutions. The main problem is that the tooltip paradigm in HTML5 is based on hover - which obviously only works when using a traditional cursor - not in mobile/touch scenarios.

**Comment by hishamco** [comment]
What's the action needed here?

**Comment by sbwalker** [comment]
@hishamco it would be useful to hear/see a suggestion on how modern applications provide tooltips to end users on forms. If you could post a screen shot it would be helpful.

**Comment by hishamco** [comment]
AFAIK many of the Web Apps are using standard HTML tool tips, nothing but some are using placeholders or help text underneath the form control which both better because they don't require the user to hover

**Comment by sbwalker** [comment]
After fighting with bootstrap's native tooltip in Blazor - which does not work as expected due to Javascript interop issues - I added a CSS-only tooltip solution as well as a Label component which makes it simple to add field level help to forms. The tooltips are displayed on both hover and click actions - so they work on desktop and mobile.

**Comment by hishamco** [comment]
> After fighting with bootstrap's native tooltip in Blazor

What's the issue exactly, I think we already did something similar in OrchardCore

**Comment by sbwalker** [comment]
The problem is specifically with Blazor and how it interfaces with JavaScript. Regardless I am happy with the pure CSS solution as one of the goals of using Blazor is to limit the use of JavaScript.
