### ISSUE TITLE
There is no argument given that corresponds to the required formal parameter 'Restart' of 'IInstallationManager.InstallPackages(string, bool)'

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#175]
1) In visual Studio, switch from Debug to Wasm
2) Try to build
3) Get build error:

There is no argument given that corresponds to the required formal parameter 'Restart' of 'IInstallationManager.InstallPackages(string, bool)'	Oqtane.Server	C:\...\oqtane.framework\Oqtane.Server\Startup.cs	368

**Comment by sbwalker** [comment]
fixed
