### ISSUE TITLE
Create new site with new tentant does not create a user

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#1751]
So it's not possible to login to the new site.

![image](https://user-images.githubusercontent.com/76835718/139682249-f3adfca7-0f04-4e28-b95e-e36aa57ba26a.png)

![image](https://user-images.githubusercontent.com/76835718/139683087-b90d862e-cdb7-49a4-bece-aef454a696e8.png)

**Comment by sbwalker** [comment]
this was caused by the refactoring to offer flexibility in the default host user's username
