### ISSUE TITLE
Issues with offcanvas component on Bootstrap 5.1.3

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#1777]
Tried to upgrade the default themes to Bootstrap 5.1.3 and ran into issues with the offcanvas component. It appears to function properly at lower screen resolutions (ie. mobile) but at desktop screen resolution it does not behave properly. I am not sure if this issue is caused by Bootswatch's implementation of Bootswatch or Bootswatch itself. Offcanvas is a newer Bootstrap component that was introduced in Bootstrap 5.0 - and the functionality is critical to Oqtane as it is used to surface the Control Panel. So we will stick with Bootstrap 5.0.2 for now until there is time to investigate the problem further or Bootstrap releases a new version which fixes the problem.

![image](https://user-images.githubusercontent.com/4840590/141123753-7095b24c-905e-4e4c-88aa-e74ceb5c21ba.png)

**Comment by CebiConRepo** [comment]
Yes, I had already noticed when I was building a new theme. Then I'm back to BS 5.0.3

**Comment by leigh-pointer** [comment]
Added a PR for this issue https://github.com/oqtane/oqtane.framework/pull/1782

**Comment by sbwalker** [comment]
fixed in #1782 - thank you @leigh-pointer!!
