### ISSUE TITLE
Could not pull dev branch

### ISSUE THREAD

**Issue by joelfradkin** [oqtane/oqtane.framework#1779]
I tried to pull/clone dev branch using https://github.com/oqtane/oqtane.framework/tree/dev
but it aks for a user and password.
Sorry for asking dumb questions, but I dont understand how to get a working copy of the version 3 release that works with ,net 6

**Comment by leigh-pointer** [comment]
I suggest making a fork of the oqtane dev branch on github . That fork will appear in your repositories. From there clone it in visual studio.
