### ISSUE TITLE
Docs Maintenance: Are Migrations and Database public APIs?

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1794]
I see myself as the "guardian" of the docs 😉. As such, I want to make sure they are useful and not flooded with internal APIs which are not meant for people needing to learn Oqtane APIs, and also hiding internal APIs which will change a lot so shouldn't be used by others. 

ATM there are ca. 10 Namespaces related to Database and Migrations, which may be better of hidden - unless they are seen as an essential part of the public API. 

![image](https://user-images.githubusercontent.com/5321186/141354905-12b283f1-2aa4-41a4-bb5f-272c58868ba1.png)

@sbwalker I would like to tag them as `[PrivateApi]` to make them disappear from the docs. Is that ok, or do you believe other devs will need to use these APIs in their work?

**Comment by iJungleboy** [comment]
Bump?

**Comment by sbwalker** [comment]
Sorry for the delay.... yes, I believe the items above could be excluded from the docs as they are not part of the public API that a developer would utilize.
