### ISSUE TITLE
Still can not build and run v3

### ISSUE THREAD

**Issue by joelfradkin** [oqtane/oqtane.framework#1802]
I noticed you updated the version to 3 so figured I would try a clone using github desktop again.
It still gives me an error about system.security.principals.windows not supporting .net 6.
This is in VS 2022.
I am updating my vs 2019 to give it a try.
It fails to do a nuget restore on the server project and mentions details in error list, but only thing in error list is the security principal error.
I am working with the old master ok, so its not stopping my research, but e nice to use .net 6 if I can get it working.

Thank you

Joel

**Comment by sbwalker** [comment]
I have no idea why it would not work for you... I just did a live presentation at .NET Conf yesterday using Oqtane 3.0.0 on .NET 6 in VS2022 and everything worked fine. There is no reference to system.security.principals.windows in Oqtane.

**Comment by joelfradkin** [comment]
I know thats what is plaging me. I am loading the preview version of vs now I was v17 this will upgrade to v17.1 maybe thats the cause? It fails on nuget restore for server, but I dont see anything in error list except the message about the principal not working with .net 6, but since its not used it must be a dependency? I dont know worst case I stay on the .net 5 version. I can try unloading vs. net etc see if a clean re-load works, but I just grabbed vs 2022 and .net 6 this week
I appreciate the reply and the concern to help. Im glad its working for everyone else I can close this if you want

**Comment by joelfradkin** [comment]
Any suggestions for what I might try to fix it?
Im currently pulling release version of vs22 to up me from vs2022 v17 to 17.1

If you have any other ideas Im open to trying.

Thanks again

Joel

**Comment by sbwalker** [comment]
I am assuming that in addition to VS2022 you also installed .NET 6 using this link 

https://dotnet.microsoft.com/download/dotnet/6.0

Personally I installed the SDK 6.0.100 Windows Installer for x64 ( as this matches my development environment )

https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-windows-x64-installer

I also installed the ASP.NET Core Runtime 6.0.0 Windows Hosting Bundle so that I could test release/upgrade installations on IIS

https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-hosting-bundle-installer

**Comment by joelfradkin** [comment]
Yes I did all that (didn't have hosing bundle).
I just tried turning off all extensions and updated vs to 17.1, still no luck.
Really bizarre issue sorry to have bothered you. Probably has nothing to do with Oqtane.

Joel

**Comment by joelfradkin** [comment]
So I spent a great deal of time on this.

I did get it to compile.
I removed all nuget references and added them all back and it builds.

Doing a compare on the csproject file for server I see a difference.
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0-preview3.21293.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="3.0.1" />

I have no clue whats what, but I think I can move forward now.
I will try adding back in my extensions etc.

Maybe it means something to you?
I updated VS 2022 and still got error, I removed all extensions, still got error.
I removed and re added all nuget packages and it compiles?

Joel

**Comment by joelfradkin** [comment]
Seems just removing and adding the nuget packages (possibly SQLclient) fixed it

**Comment by leigh-pointer** [comment]
Do remember Sql.client get released on 20th November, or there round abouts!
________________________________

**Comment by sbwalker** [comment]
Microsoft.Data.SqlClient was not released as part of the official .NET 6 release... it is being released later this month. This is the reason why Oqtane 3.0.0 is referencing a "preview" package. However I am not sure why this package is causing you difficulty when it works fine for me in my environment. @leigh-pointer is it working fine for you? @joelfradkin what is your desktop operating system?

**Comment by joelfradkin** [comment]
Windows 10.
Just installed vs 2022 this week and updated today, but didn't help.
In the end I removed all nuget packages (probably could have started with just server as it was the only one giving me an issue) and re-added the latest ones.

Maybe its related to a username change on my side or something although that was a few weeks ago.

Joel
