### ISSUE TITLE
Implementing ErrorBoundary in ModuleInstance component

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#1814]
This helps to catch unhandled module exception on module instance level. Nice new NET6 feature.
sample module
![image](https://user-images.githubusercontent.com/7838468/142179565-21780885-7f75-4519-96a3-ea7538c45da7.png)

```c#
@inherits ModuleBase

<button type="button" class="btn btn-primary" @onclick="OnClick">Throw exception </button>
@code {
    protected void OnClick()
    {
        throw new Exception("Simulated exception");
    }
}
```

output for users 
![image](https://user-images.githubusercontent.com/7838468/142179973-2f933489-e0a9-428c-9250-6bc36577f8fc.png)

output for host
![image](https://user-images.githubusercontent.com/7838468/142180075-31291b18-88bb-40fc-997e-8f46fa723795.png)

**Comment by hishamco** [comment]
I think this should be closed now
