### ISSUE TITLE
Introduce IRepository<TType>

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#184]
IMHO introducing a `IRepository<TType>` will save time instead of creating `I{Type}Repository` for every entity

For instance `IJobRepository` will be:

```csharp
public interface IJobRepository : IRepository<Job>
{
}
```

instead of

```csharp
public interface IJobRepository
{
    IEnumerable<Job> GetJobs();
    Job AddJob(Job Job);
    Job UpdateJob(Job Job);
    Job GetJob(int JobId);
    void DeleteJob(int JobId);
}
```

or we could implement the generic repository directly from within `JobRepository`

Sometimes we may need to create custom on such `IUserRepository`:

```csharp
public interface IUserRepository<User> : IRepository<User>
{
    User GetUser(string Username);
}
```

**Comment by sbwalker** [comment]
I am definitely an advocate for making things simpler and requiring developers to write less code. The current repository implementation works but is quite verbose. I do not see any downsides of implementing a generic repository pattern - however I would want to fully implement it throughout the framework so that the approach is consistent. It is also important the the implementation can be leveraged in custom modules ( ie. in the Blog module project )

**Comment by hishamco** [comment]
I'm the one who follow the DRY principle, introducing such pattern will not only make things easier, but it will save time, especially in developing custom modules with plenty of entities

Anyhow it's fine to keep the current implementation Shaun

**Comment by sbwalker** [comment]
Maybe my earlier response was not clear - I am in favor of Oqtane using a generic repository pattern. If you would like to make this contribution, please submit a PR.

**Comment by hishamco** [comment]
Sure Shaun

**Comment by fileman** [comment]
@sbwalker you mean to use IRepository<T> even for oqtane core entities replacing current repositories?
And which names for methods:
- GetAll() + GetAll(object id)
- Get or GetById
- Add
- Update
- Delete

**Comment by hishamco** [comment]
@fileman this will be a default method names, but we anyone can customize and add as much as he/she want

**Comment by sbwalker** [comment]
It would probably be best to introduce the generic repository and implement it in 1 or 2 concrete repositories to review naming conventions and adaptability - and once we are satisfied, roll out the implementation throughout the framework. Does this make sense?

**Comment by hishamco** [comment]
Make sense, I will submit a PR ASAP

**Comment by PoisnFang** [comment]
What is the status of this implementation?

**Comment by hishamco** [comment]
The implementation is already done, but waiting for @sbwalker feedback for the `IRepository<TType>` principle in general

**Comment by sbwalker** [comment]
I have added this to the roadmap for V.Next on the main project page

**Comment by hishamco** [comment]
So, this will be on hold ...

**Comment by sbwalker** [comment]
Yes, at least until the MVP is released.

**Comment by sbwalker** [comment]
Closing this issue. Will revisit after V1.
