### ISSUE TITLE
Code change needed in 02030002_AddSettingIsPublic.cs for Postgres database.

### ISSUE THREAD

**Issue by dkoeder** [oqtane/oqtane.framework#1849]
Install will fail, if using Postgres, unless the line 22 is changed.

Current
settingEntityBuilder.UpdateColumn("IsPublic", "0");

Change that works for me
settingEntityBuilder.UpdateColumn("IsPublic", "0", "bool", "");

**Comment by hishamco** [comment]
Could you please submit a PR?

**Comment by sbwalker** [comment]
fixed in #1855
