### ISSUE TITLE
Issue with new SettingService.GetModuleDefinitionSettingsAsync

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1880]
I am unable to retrieve the ModuleDefinition settings when not logged in.  I can understand it being secure for Adding and Updating but ReadOnly should be available so the ModuleDefinition  settings can be used for the Module instance.

**Comment by sbwalker** [comment]
@leigh-pointer the ModuleDefinition settings are intended to be available to all users - however there is another dimension to consider as well. Similar to Site settings, there is an IsPublic property that must be set to True on a setting if the setting is safe to expose through the API. This allows settings to be properly filtered to avoid sensitive information disclosure.

**Comment by leigh-pointer** [comment]
Ok, will look into it and raise a PR

**Comment by sbwalker** [comment]
It should not require a PR. When you create your ModuleDefinitionSetting you should use the method which allows you to specify the isPublic property:

       public Dictionary<string, string> SetSetting(Dictionary<string, string> settings, string settingName, string settingValue, bool isPublic)

**Comment by leigh-pointer** [comment]
@sbwalker I actually need to raise a PR as the IsPublic was not being set on update.

**Comment by sbwalker** [comment]
It seems to be working in Site Settings? The collection of settings is loaded, the SetSetting() method is used to ensure IsPublic is set, and UpdateSettingsAsync() saves the values.
