### ISSUE TITLE
is this project stalled?

### ISSUE THREAD

**Issue by 274188A** [oqtane/oqtane.framework#189]
seems like low activity for a while - just curious if it's still alive

**Comment by ADefWebserver** [comment]
It is very much alive :)

**Comment by mikecasas** [comment]
Any update on the below:

> In terms of maturity, Oqtane will reach an MVP ( minimum viable product ) milestone this month which will signal the release of an official 1.0 version.

https://www.oqtane.org/Resources/Blog/PostId/537/oqtane-vs-dnn

**Comment by sbwalker** [comment]
I was trying to get a large enhancement finished off before declaring a 1.0 release. The enhancement includes support for user notifications as well user management such as email verification and password reset functionality. I submitted a large PR today which includes these changes.
