### ISSUE TITLE
Question - Oqtane Blazor Routing Diagram

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#190]
Is there a diagram / flow chart showing how the routing is handled for Oqtane? I am having a hard time trying to piece together in which order components are built buy the system to handle a routing request.

**Comment by sbwalker** [comment]
The Oqtane Page Compositing Model described on this blog post https://www.oqtane.org/Resources/Blog/PostId/539/migrating-from-dnn-to-oqtane is the best visual representation of the nested components. The main router is located at Oqtane.Client/Shared/SiteRouter.razor and it does the majority of the heavy lifting in terms of interpreting the Url, loading the metadata, constructing the cascading parameters, and then kicking off the composite UI generation. All of the components involved in the composite UI are in the Oqtane.Client/Shared folder - the SiteRouter loads the ThemeBuilder.razor which loads whichever theme is associated to the page in the database. A theme contains Pane.razor components which iterates through the list of modules associated to the page/pane in the database and for each module it loads the ContainerBuilder.razor which loads whichever container is associated to the module in the database. A container contains a ModuleInstance.razor component which loads the actual module component.

**Comment by PoisnFang** [comment]
Thank you very much this is extremely helpful!
