### ISSUE TITLE
Module.css not loaded at startup

### ISSUE THREAD

**Issue by nicpitsch** [oqtane/oqtane.framework#1907]
I'm submitting an issue about custom module css from *Module.css* not loaded at startup.

Reproduce: 

* Add new developer module with *Module Creator* at *Home* page.
* Add a noticable property to *Module.css* like `body { background-color: red; }`.
* Start resp. Debug Oqtane.
* Behaviour: Home page body background-color remains unchanged. Move to *My Page* and then again to *Home*: only now it's red and only now  Module.css link is loaded in page source.
* Expected behaviour: Home page background should be red at startup.
* Screen cast demonstrating behaviour: https://www.screencast.com/t/m34jCjXnk.

Environment:

* Oqtane 3.0.1.
* Hosting Model: Blazor Server, no prerender.

**Comment by sbwalker** [comment]
fixed in #1921
