### ISSUE TITLE
Problem starting over

### ISSUE THREAD

**Issue by MPatriot** [oqtane/oqtane.framework#1908]
Hello,

I really like what you have going here and am brand new to Oqtane, with that said, over the past few days I have just been trying to get familiar, which has involved a lot of trying things and starting over

In this round of starting over I didn't delete the project or the demo module I had created but deleted just the database stuff.

Cleared appsettings DefaultConnection
Deleted the LocalDb Database
Closed all open instances of Visual Studio
Reopened Oqtane.sln

Went through the initial setup again, this time using a different database name and username

VS debugger raised the following error:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Oqtane.Client
  StackTrace:
   at Oqtane.UI.SiteRouter.<Refresh>d__31.MoveNext() in C:\Projects\OqtaneTryout\oqtane.framework-master\Oqtane.Client\UI\SiteRouter.razor:line 142

After stopping and restarting I went and looked to see if new database had been created ... Yes
Looked in dbo.User and saw my new user had been created but with a very interesting possible source of the problem...

UserId: 1
Username: New user name (MHoey)
CreatedBy: Old user name (MPatTest)

Something must have been hardcoded somewhere...brand new database but the first user was created by a non existent user?

I suppose I could unzip the oqtane framework again, but this is definitely a bug and also I would then have to go through the process of learning how to add existing modules, which I will have to do as the framework evolves or when I get to adding or removing modules for different scenarios  but kinda wasn't  ready to dive into that

Thanks
Mark

**Comment by leigh-pointer** [comment]
@MPatriot good to hear you like Oqtane. 

One thing can be a gotcha is the Tenant table.  Look in there are make sure your connection string is the same as the appconfig.json.

**Comment by MPatriot** [comment]
I guess I am not sure what you mean leigh

looking in the new database I find a single Tenant interestingly enough, created by the old user from a database that doesn't exist

I also find new tables from not only from my only module but from other modules that were removed (deleted) not only with the admin interface but physically off the hard drive

If you look at the attached screenshot you will see that the error was raised in SiteRouter.Razor but deep enough in that it not only  got past the null site and the if (authState.User.Identity.IsAuthenticated) checks but fails when it tries to actually access the user

       if (site != null)
        {
            if (PageState == null || refresh == UI.Refresh.Site)
            {
                // get user
                var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
                if (authState.User.Identity.IsAuthenticated)
                {
                    user = await UserService.GetUserAsync(authState.User.Identity.Name, site.SiteId);
-->               user.IsAuthenticated = authState.User.Identity.IsAuthenticated;
                }
            }

I don't think it should have ever gotten that far in and still had a null user,  not really sure what is in the cookies but that might be where a lot of this comes from
![usernull](https://user-images.githubusercontent.com/20174265/148259928-fa6c27ee-c311-4473-8f54-dd1ed14a20de.png)

Thanks,
-Mark

**Comment by sbwalker** [comment]
The error is happening because your browser has a cookie for a user that existed in the earlier installation - but has since been deleted when you re-installed. The code above needs some defensive logic to check for a valid user object before assigning the property - I will add this.

As far as the database tables, the only way they can be created is if a module DLL exists in the /bin folder - as that is where the database migration logic resides. If you delete the DLLs from the /bin after the framework has been installed, the tables will still exist in your database. You can easily do a re-install at any time by simply resetting the connection string in Oqtane.Server\appsettings.json:

```
  "ConnectionStrings": {
    "DefaultConnection": ""
  },
```

**Comment by MPatriot** [comment]
Thanks Shaun

Well, hmm, I got the clearing the connection string thing down:)  Have had a lot of practice, and even using different database names...

I cleared the browser cookies and data (thinking it might also be cached data / local storage) unless Chrome isn't doing that

I deleted the dlls from the bin for the deleted modules and themes

After that didn't work completely(it stopped writing deleted stuff to the new database but still had old username  creating stuff and still got stuck one the original above)

I copied the whole directory and ran Oqtane.sln from copy, with new connection string

This time it didn't get stuck on the user but when looking at what was created, it still had the old user name creating stuff

It seems it may be more than just a cookie, but perhaps something else in the bin?

Anyway, Thanks

I assume I could login once with new user name now that the app runs from the copy and by repeating the above, with the same user name it would have the correct user creating stuff

**Comment by MPatriot** [comment]
Try this for fun...I won't bore you with all the trial and errors...

Create a brand new Oqtane project and add a module like your DNF example from a few years ago
build the module and close the Oqtane app, clicking the restart link never works for me...
Rerun Octane app and activate new module, then remove it

It should be deleted from Oqtane bin but still in the directory and in the database module table

Create a copy of just the new Oqtane project into a new directory and run it, after a try or two attaching debugger to browser it should run fine, even with the module from the original directory still in the database but not in the bin (eliminated cookie / user problem), don't login

Rename original directory, rebuild now unattached module and Oqtane project / run, renaming seems to get rid of user cookie problem but all kinds of problems occur trying to find files in old directory name even though rebuilt

Rename original directory back to original name, same kind of problems occur with it now trying to find files in the second original directory name, heck, even restart VS and / or your computer

I do get a script warning that I don't get in copy version:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	TS1003	(JS) Identifier expected.	Oqtane.Server JavaScript Content Files	C:\Projects\TryOqtane\oqtane.framework-master\Oqtane.Server\wwwroot\Modules\Templates\External\Server\wwwroot\Modules\[Owner].[Module]\Module.js	4	Active

Completely delete module from original directory and try again... no matter how many times you try, even past attaching to the debugger restarts its stuck looking for the second name of the original directory and the copy runs fine after initial debugging attachment failure... 

Perhaps this is a separate issue than the initial issue with the cookies, even with having the module still in the database but but deleted from the the hard drive it gave the copy no problems other than a few initial debugger attachment issues probably from switching back and forth between. 

Anyway, its getting late....:)

**Comment by leigh-pointer** [comment]
@MPatriot on a debugging note just add the Oqtane Server project (Oqtane.Server.csproj) to the Module solutions and set Oqtane.Server as startup project and hit F5. No more attaching the debugger!

**Comment by MPatriot** [comment]
Thanks leigh!

I kinda wanted the debugger:)

Anyway, I decided for now that I wouldn't do any folder renaming and always use the same user name while moving on in my exploration.  There is a good chance that most people resetup with the same user name and that is how the whole cookie thing got this far without being addressed.

Cheers!

- Mark
