### ISSUE TITLE
Label Control appending Class to LabelClass and SpanClass

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1914]
When modifying the Label control at runtime the classes are appended to the Class field which in turn does not render the correct class. 

```
    private string _spanclass = "app-tooltip";
    private string _labelclass = "form-label";

 _spanclass += (!string.IsNullOrEmpty(Class)) ? " " + Class : "";
_labelclass += (!string.IsNullOrEmpty(Class)) ? " " + Class : "";
```

I have toggled the Label from Bold to Normal text and the results are as follows:

`<label for="Text3" class="form-label fw-normal fw-bold fw-normal fw-bold fw-normal fw-bold fw-normal">Text3</label>`

I will submit a PR for this issue.

**Comment by sbwalker** [comment]
The classes on the label field are not intended to be modified at runtime - they are intended to be specified statically in your razor code.

**Comment by sbwalker** [comment]
My apologies... after looking at the PR I now understand the problem. The PR looks good - I will merge it.
