### ISSUE TITLE
Security problem with api

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#192]
curl -X GET "http://localhost:44357/~/api/User" -H  "accept: text/plain" return list of users !
Authorization is missing on api controllers.

**Comment by sbwalker** [comment]
Good catch! If you review all of the Controllers in the framework you will notice that an attempt has been made to implement authorization throughout - however a comprehensive review is definitely needed. Retrieving a list of users should be restricted - the question is, restricted to whom? The 2 simplest options are authenticated users or administrators. Administrators is more secure but we will need to determine if broader access is required.

**Comment by ADefWebserver** [comment]
Perhaps Administrators for now. For others, perhaps you can only pull up a user if you have their username. If a module needs a 'user search' they need to make their own server side controller methods.

**Comment by chlupac** [comment]
Administrators only. Sensitive data.

**Comment by sbwalker** [comment]
Fixed in #201
