### ISSUE TITLE
Show proper message when Password-Reset link expired

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1920]
I got a link to reset my password. 

Keep getting message that it doesn't match complexity requirements, despite passwords like `HoDI4qA5Dhn4` and even `Ob@^6nF1FORr` 

![image](https://user-images.githubusercontent.com/5321186/148677738-20cb5443-4b62-434c-88ca-526d289f66f8.png)

As of now, I can't log in, and I can't set a new password.

**Comment by sbwalker** [comment]
Oqtane uses the standard .NET Core Identity functionality for password reset... I am thinking that perhaps there is a problem with the security token it generates... I will have to investigate further.

**Comment by sbwalker** [comment]
@iJungleboy I have confirmed that the security token generated in the password reset email is only valid for 24 hours. I am guessing the password reminder email you received is older than 24 hours which means that the link it contains is no longer valid. You should visit the site again, go to the Login page, enter you username, and select the Forgot Password button. A new email will be sent to you with an updated link which allows you to reset your password. Please let me know if this resolves your problem ( I was able to verify that the logic works fine in my local installation ).

**Comment by iJungleboy** [comment]
I'll test. 
Note though that the UI never indicated this, so if your guess is correct, it would help to improve the error messages - ideally stop the user from entering a new password if the link already expired.

**Comment by iJungleboy** [comment]
It worked, so this was probably the cause. 

Best improve the UI so it complains about the expired link beforehand. I'll update the title for this issue.

**Comment by sbwalker** [comment]
Unfortunately there is no way in the .NET Core Identity system to test if the security token has expired. I have already improved the instructions in the password reminder email for the next release.
