### ISSUE TITLE
Edit buttons disappear on refresh

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#195]
I noticed that when I am on the modules page and I click refresh in chrome, after the refresh, the edit buttons are not visible.

Before refreshing.

![before](https://user-images.githubusercontent.com/11261164/74044642-5c903500-4999-11ea-9546-fb02704304db.PNG)

After refreshing

![after](https://user-images.githubusercontent.com/11261164/74044664-67e36080-4999-11ea-9872-7ee2dc67aa8f.PNG)

**Comment by fileman** [comment]
In ActionLink.razor after refresh "PageState.EditMode" is false so `IsAuthorized()` return false and no NavLink will be rendered `@if (authorized)
{
    <NavLink class="@classname" href="@url" style="@style">@text</NavLink>
}`

**Comment by sbwalker** [comment]
Sounds like a bug - we need to determine why EditMode is set to false after refreshing the browser. In the case of Admin pages the EditMode should be dictated by the EditMode field in the Page table in the database.

**Comment by sbwalker** [comment]
fixed in #206
