### ISSUE TITLE
Deploy to Azure failed

### ISSUE THREAD

**Issue by CebiConRepo** [oqtane/oqtane.framework#1953]
### Hi there,

I have already started some attempts to install Oqtane on Azure. I'm a total newbie and don't really want to bother you. I stick to the following instructions from 08/17/20 :

[Blazorhelpwebsite-Oqtane Deploy to Azure](https://blazorhelpwebsite.com/ViewBlogPost/40)

Unfortunately that does not work. The Azure Wizard aborts with the following error message: see images

In the file "azuredeploy.json" I find the following in the section:

```json
"dependsOn": [
            "[resourceId('Microsoft.Web/sites', parameters('BlazorWebsiteName'))]",
            "[resourceId('Microsoft.Web/Sites/config', parameters('BlazorWebsiteName'), 'connectionstrings')]"
          ],
```

is that correct? In addition, line 162 contains the entry:

```json
"properties": {
        "name": "[parameters('BlazorWebsiteName')]",
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('hostingPlanName'))]",
        "siteConfig": {
          "webSocketsEnabled": true,
          "netFrameworkVersion": "v5.0"
        }
      },
```

Framework 5? for Oqtane 3.0.2

![Settings](https://user-images.githubusercontent.com/36736217/150192790-e599e035-448b-41cd-bf90-2d5389fad2ee.jpg)
![Error](https://user-images.githubusercontent.com/36736217/150192786-5056891e-1aac-41fc-a69e-6d583811f14a.jpg)

thank you for the effort

**Comment by sbwalker** [comment]
I would suggest you use these instructions instead: https://blazorhelpwebsite.com/ViewBlogPost/1

**Comment by CebiConRepo** [comment]
Thanks for the information
