### ISSUE TITLE
Issue with Roles and Settngs

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1961]
I have a module that is trying to access the RolesService within the Module Settings component.  The module errors because the Default permissions of  View and Edit for Administrator do not exist in the Database and / or there are no permissions for the module in the database.

**Comment by sbwalker** [comment]
It is not clear what you are trying to do. Are you trying to use the RoleService or are you trying to manage Settings for a Role entity? Either way, the API for roles requires a user to be in the site administrator role. This is regardless of whether a user has Edit roles for the module or not.
