### ISSUE TITLE
Missing Preprocessor Directives during Runtime Compile

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1972]
.net 6 has a breaking change which drops preprocessor values in the `.deps` JSON file

https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/preservecompilationcontext-not-set-by-default

This causes trouble for runtime compile, because any code that runs on multiple platforms needs things like this: 

```cs
#if NETCOREAPP
 // .net core code
#else
  // .net Framework code
#endif
```

In Oqtane 2 this code did what you would expect, but in Oqtane 3 it doesn't because the runtime compiler doesn't set `NETCOREAPP`.

We believe that this is essential, and ideally would also define additional keys like `OQTANE` and `OQTANE3` so that code could be different if built for Oqtane vs. NopCommerce or version differences in Oqtane. That would then also allow code like:

```cs
#if OQTANE3
 // oqtane 3 code
#else
  // oqtane 2 code
#endif
```

Our recommendation

1. Enable the default .net keys to be added in the `.deps` file according to the [list by Microsoft](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives)
2. Also add an `OQTANE` key to make development easier for cross-platform components
3. Also add an `OQTANE3` key to make development easier for cross-version components, which may have to survive breaking changes in the platform
4. Optionally also add an `OQTANE3_0_OR_GREATER` which would be consistent with MS recommendations

@tvatavuk will create a pull-request for these changes to help you review if this makes sense to you.

**Comment by sbwalker** [comment]
@iJungleboy I agree with adding support for the default .NET keys, and also adding the OQTANE constant, however I would prefer to not include the version-based constants at this time unless there is an actual use case which can be provided that needs it right now - backward compatibility is part of the Oqtane philosophy and a lot of care goes into ensuring the public APIs do not have breaking changes.

**Comment by iJungleboy** [comment]
That's great. And makes sense. 
BTW just as a feedback: in case of 2sxc - probably the most sophisticated plugin ATM every release of Oqtane needed changes to ensure it works. Small things, usually done in a few hours, but there was always something to patch, and it did cause trouble because some newer version of 2sxc will break on older Oqtanes as well. 

This cannot be avoided as we move forward, maybe adding a max-version in the Oqtane.net catalog would help avoid some issues, and may also help pre-test an Oqtane before upgrading, if all installed modules are already compatible... just an idea...

**Comment by tvatavuk** [comment]
@sbwalker as You explained, I just updated [PR#1973](https://github.com/oqtane/oqtane.framework/pull/1973) to remove precompile symbol `OQTANE3_0_OR_GREATER`. I see now that it doesn't add value as it have the same long term meaning as `OQTANE` that is significant.

I took little liberty to keep less significant symbol `OQTANE3` still in list, so we will eventually have little more dev flexibility after update to `OQTANE4`, but if You hold strong opinion against it I will also remove that one in no time.

**Comment by sbwalker** [comment]
@iJungleboy we still have the following constants defined in the project file:

```
    <DefineConstants>$(DefineConstants);OQTANE;OQTANE3</DefineConstants>
```

can this safely be removed now?

**Comment by iJungleboy** [comment]
@sbwalker let me check this and get back to you.

my guess is that `OQTANE` would be really helpful if it stayed, but I must review w/ @tvatavuk

**Comment by iJungleboy** [comment]
@sbwalker you can just remove `OQTANE3` but I would `OQTANE` is quite important to us.

For example, code (such as 2sxc or even 2sxc Apps) which runs on Dnn and Oqtane needs it in various `#if` conditions.

Many thanks!
