### ISSUE TITLE
Nuspec to include 'content'

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1987]
Oqtane module have **content files**, that are not stored in `wwwroot`. 

In our case this content files are immutable custom json configuration files that should be accessible by oqtane module server side code. 

In the same time this content files should not be accessible over web, with url (and that is the reason why is not optimal to store them under wwwroot, as other common module assets, like css and js).

[Including content files](https://docs.microsoft.com/en-gb/nuget/reference/nuspec#including-content-files) covers our case in nuget specification.

Idea is to use common **files/file** node with  `target="content\..."` or `target="contentFiles\..."`  to specify this content files.

```xml
  <files>
      <file src="myconfig.json" target="contentFiles\any\any" /> <!-- this is for new format -->
      <file src="myconfig.json" target="content" /> <!-- this is for the old format -->
  </files>
```

Oqtane Server **InstallationManager** can be extended to support new targets.

Here is  our example from nuspec.

```xml
...
<file src="..\ToSic.Sxc.Oqt.Server\2sxc\.data\**\*.*" target="content\2sxc\.data" />
...
```

**Comment by sbwalker** [comment]
@tvatavuk I understand the use case and I think it makes sense to support this concept for modules. However one of the Oqtane philosophies is Encapsulation - which essentially means trying to avoid littering the run-time environment with a ton of static assets. The /Oqtane.Server/Content is already being utilized as a standard location for storing files which need to be secure - so your proposal aligns with the philosophy. However I would prefer to simply support 1 location via the nuspec - target="content" - I do not see the need to support target="contentFiles" as well. Less is more when it comes to framework design.

**Comment by tvatavuk** [comment]
@sbwalker thx 👍
Updated [PR #1988](https://github.com/oqtane/oqtane.framework/pull/1988) as You explained.
