### ISSUE TITLE
Installation fails on Sqlite

### ISSUE THREAD

**Issue by bhojim** [oqtane/oqtane.framework#1989]
Something about DropColumn not supported

**Comment by sbwalker** [comment]
Thank you for reporting this issue. 

SQLite supports a limited subset of ALTER TABLE. The ALTER TABLE command in SQLite allows the user to rename a table or to add a new column to an existing table. It is not possible to rename a column, remove a column, or add or remove constraints from a table. The process for removing a column is as follows:

- create new table with the column removed (including any PKs, FKs, or IXs)
- copy all data
- drop old table
- rename the new one

The simpler solution is to not drop the column when running on SQLite - which is the path I will take to resolve this issue. 

This is a good example of the challenges in creating a solution which supports multiple database platforms.
