### ISSUE TITLE
move code to page.razor.cs

### ISSUE THREAD

**Issue by fileman** [oqtane/oqtane.framework#199]
What you think about move code into page.razor.cs file?
Visual Studio has better intellisense in .cs than .razor files

**Comment by chlupac** [comment]
+1 for it. also better debug support.

**Comment by sbwalker** [comment]
This is a good suggestion for a future release after V1. For V1 the focus should be on features which enable developers to be productive building modules and on overall framework stability.

**Comment by hishamco** [comment]
We should be careful if we do it after V1, coz perhaps there will a breaking changes, I think if we see a great contribution on this we may consider it for V1. I see almost the planned features for V1 is already implemented, accepting a community contributions may accelerate the process

But the final decision is yours

**Comment by fileman** [comment]
I can do it if you want, v1 release has a planned date to respect?

**Comment by hishamco** [comment]
I can participate on this one too, coz there are many thing to be done

**Comment by chlupac** [comment]
Big plus is than here can be one base class for module, shared code between action.
But my candidate one for this refactoring is SiteRouter.

**Comment by sbwalker** [comment]
I am not sure how this enhancement would result in breaking changes? Regardless, I have added it to the roadmap for V.Next on the main project page.

**Comment by sbwalker** [comment]
Added to roadmap. Closing and will revisit after V1

**Comment by hishamco** [comment]
Im not sure if it's good to close the issues that are related to  `1.x.0` I think it will be nice to keep them open and change the milestone from the github

I see this pattern in ASP.NET Core repos and many OSS
