### ISSUE TITLE
Page management (edit)- save button doesn´t respond

### ISSUE THREAD

**Issue by dusekjaroslav** [oqtane/oqtane.framework#200]
When I want to edit page in Page management, the save button doesn't respond. When I create new page that has no module in content pane, the save button works fine.

**Comment by chlupac** [comment]
Sometimes happens. Probably some fields are not filled correctly. Validation is missing.

**Comment by sbwalker** [comment]
Are you able to narrow this down to which fields may be causing the validation issue?

**Comment by dusekjaroslav** [comment]
Chlupac is right. When I debuged Visual Studio again, "theme" field was not automaticly selected as before. And so the save button didn´t respond. I didn´t notice it.

**Comment by sbwalker** [comment]
Not sure what the requested action is for this item, so I am closing. If there is a specific issue which needs to be addressed in page management please explain the issue in detail so that it can be fixed.
