### ISSUE TITLE
Remain Logged-In after F5 Restart when using Chrome

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2018]
I could be doing something wrong, but here's my use case

I need to restart Oqtane a LOT during development. After every restart, I must login again - which just eats up my time. 

1. Is there a way to remain logged in through restarts during development?
2. Or could we implement a feature for dev-scenarios, to auto-login certain credentials - either automatically, or by link (which we would put on the start page to be more efficient)?

**Comment by leigh-pointer** [comment]
@iJungleboy not a problem here.  Using Edge and have "Remember Me?" option checked.

**Comment by iJungleboy** [comment]
I'm using Chrome, and it always opens a Guest-Window when I hit F5. 
I assume that this means cookies etc. are destroyed? So I'm not sure if it can survive browser sessions.

Are you using F5, or are you using IIS and just browsing normally to it?

**Comment by iJungleboy** [comment]
I found the solution - it has to do with how chrome starts - when you have multiple Chrome profiles. 

I'll try to explain it here for those that come after me and have the same problem. 

1. The trick is to define another browser in Visual Studio which loads the correct profile - this is explained here https://www.codeproject.com/Articles/1236613/Set-Which-Chrome-Profile-for-Visual-Studio-to-Use
2. In addition, you must figure out the name of the profile folder - default is `--profile-directory="Default"` but for others you must do what is explained here https://www.howtogeek.com/255653/how-to-find-your-chrome-profile-folder-on-windows-mac-and-linux/ - basically you must call `chrome://version/` to get the right directory

it works!

**Comment by leigh-pointer** [comment]
@iJungleboy I am using F5 and to also add I have tried with Chrome and have no issues.

My VS dev environ is set up for module dev.  I would also add that in my module solution I reference the Oqtane Server project and the Oqtane Server project is used as start up IISExpress.
![image](https://user-images.githubusercontent.com/9447612/155479975-f7f4a573-7e78-4c6f-a7d8-78af7b5f965b.png)

**Comment by iJungleboy** [comment]
I believe my issue was that my chrome has multiple profiles. 
It seems that the default is then "Guest Mode".
