### ISSUE TITLE
Trying to import large data set

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2021]
System not importing large sets of data (length 454608 chars) can this be overridden?

**Comment by sbwalker** [comment]
Are you referring to the module import process (ie. IPortable)? Is this in a custom module? What is the error or behavior?

**Comment by leigh-pointer** [comment]
@sbwalker using the import / export IPortable interface.   After pasting a large string and clicking the import button the is not reached.  I have tried with smaller strings and no problem.

**Comment by sbwalker** [comment]
Your response seems to be missing a word - "the ?? is not reached"? When performing an import through the UI the payload is sent to the server as an HTTP POST. I am sure there is an upper limit on what a web server allows for a POST operation.
