### ISSUE TITLE
Openning web from unknown alias

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#203]
Web crashes (white screen) when you try %subj%
Opinion is open root site.

**Comment by sbwalker** [comment]
This was a point of great debate in DNN as well. Some people consider it to be a security issue if a domain can be configured to point an IP, and the website related to that IP serves the default site regardless of whether the alias is explicitly mapped to it or not. Imagine a third party pointing a domain of www.{profanity}.com to your your IP and it maps it automatically to the default site. For this reason a 404 ( with some appropriate logging ) may be the better solution.

**Comment by ADefWebserver** [comment]
> For this reason a 404 ( with some appropriate logging ) may be the better solution.

This will also help in configuring URL settings. If the 404 page says "%subj% not found" rather than just show the default page, I will know I don't have my settings correct.

**Comment by chlupac** [comment]
404 will be great.
