### ISSUE TITLE
Fresh install with Postgres failed with "42703: column "settingname" does not exist POSITION: 43"

### ISSUE THREAD

**Issue by ghhv** [oqtane/oqtane.framework#2032]
Fresh install of Oqtane.Server V3.0.3 via VS2022 on Windows with Postgresql V12 database. 
I created a new Postgres database with default template0 and added an admin user with all rights.
Added config to Oqtane setup page and it came back with the error "42703: column "settingname" does not exist POSITION: 43".
A migration has indeed run on Postgres and there are now tables created but as per the error, the "tenant" table is missing a "settings" column.
![image](https://user-images.githubusercontent.com/13160762/155942999-0c79dab5-79ce-45ad-a092-c5dcde426d12.png)
![image](https://user-images.githubusercontent.com/13160762/155943369-6333c541-67d9-4508-b1cb-278a6f0bd188.png)
![image](https://user-images.githubusercontent.com/13160762/155943511-c0456c1c-d933-459f-a435-78c600bd9d1f.png)

I note the Tenant model class does not have a "setting" field, yet the "InitializeTenant" migration is trying to create an index with it. 

Error.log entry
`[2022-02-28 07:22:30+00:00] [Error] [Oqtane.Infrastructure.DatabaseManager] 42703: column "settingname" does not exist

POSITION: 43 `

thanks.

**Comment by ghhv** [comment]
So, using the default MSLocalDb SQL Server, it worked without issue (for a fresh install) and it doesn't have any settings column in the tenant table.. Actually looking back at the error, I don't know why I thought it's looking for that in the tenant table..  maybe from that Index command in "InitializeTenant".

Also, the broken Postgres install above won't start at all now.. message - "Site Is Either Disabled Or Not Configured Correctly".

**Comment by ghhv** [comment]
So found the problem - was very hard without a stack trace!
this code is updating a column 
![image](https://user-images.githubusercontent.com/13160762/156347600-a3765a7b-fd9e-4da4-8278-7f70ca2fabf9.png)

which calls this:
![image](https://user-images.githubusercontent.com/13160762/156355348-bbbff01f-0e0f-4193-9072-d5d8a8fe367b.png)

Note the WHERE condition field name..

But the database looks like this:
![image](https://user-images.githubusercontent.com/13160762/156355582-d7a06620-c004-43e4-a508-a2856cca3817.png)

The issue is the RewriteName/Value does not get applied to the "condition" clause.

**Comment by ghhv** [comment]
This update is also affected by the same bug

`settingEntityBuilder.UpdateColumn("IsPrivate", "1", "bool", "EntityName = 'Site' AND SettingName LIKE 'SMTP%'");`

EntityName should also be ReWritten.

**Comment by ghhv** [comment]
Here's working code.. I wasn't sure on what to do with creating a Pull request with the versioning in your migrations. 

`namespace Oqtane.Migrations.Tenant
{
    [DbContext(typeof(TenantDBContext))]
    [Migration("Tenant.03.00.02.02")]
    public class UpdateSettingIsPrivate : MultiDatabaseMigration
    {
        public UpdateSettingIsPrivate(IDatabase database) : base(database)
        {
        }

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var settingEntityBuilder = new SettingEntityBuilder(migrationBuilder, ActiveDatabase);
            settingEntityBuilder.AddBooleanColumn("IsPrivate", true);
            settingEntityBuilder.UpdateColumn("IsPrivate", "0", "bool", "");
            settingEntityBuilder.UpdateColumn("IsPrivate", "1", "bool", $"{RewriteName("EntityName")} = 'Site' AND { RewriteName("SettingName")} LIKE 'SMTP%'");
            settingEntityBuilder.DropColumn("IsPublic");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // not implemented
        }
    }
}`

`namespace Oqtane.Migrations.Tenant
{
    [DbContext(typeof(TenantDBContext))]
    [Migration("Tenant.03.00.02.01")]
    public class UpdateSettingIsPublic : MultiDatabaseMigration
    {
        public UpdateSettingIsPublic(IDatabase database) : base(database)
        {
        }

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var settingEntityBuilder = new SettingEntityBuilder(migrationBuilder, ActiveDatabase);
            settingEntityBuilder.UpdateColumn("IsPublic", "1", "bool", $"{RewriteName("SettingName")} NOT LIKE 'SMTP%'");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var settingEntityBuilder = new SettingEntityBuilder(migrationBuilder, ActiveDatabase);
            settingEntityBuilder.UpdateColumn("IsPublic", "0", "bool", $"{RewriteName("SettingName")} NOT LIKE 'SMTP%'");
        }
    }
}`

**Comment by sbwalker** [comment]
thank you for tracking this down... multi-database support is definitely a challenge based on the differences between different database platforms. Since nobody has reported this issue previously I am going to assume that PostgreSQL is not being used extensively - so I am inclined to simply apply the fix in the existing migrations. This will allow new installations to work properly - as well as any older installations to upgrade properly as well. Do you want to submit a PR or do you want me to make the change on your behalf?

**Comment by ghhv** [comment]
Hi Shaun, I've never done a PR and I didn't know what to do with that versioning.. so yes, you can do for now.. Maybe as I get into this more, I'll give it a go.
