### ISSUE TITLE
Latest code release (March 8th [GMT+11]) fails to create the admin user on start after database config. 

### ISSUE THREAD

**Issue by ghhv** [oqtane/oqtane.framework#2046]
I just downloaded the very latest Oqtane framework code from here and tried to start up Oqtane but the admin ID fails to work. I have tested with MSSQL LocalDb and Postgres. Same issue on both. 
![image](https://user-images.githubusercontent.com/13160762/157207783-ac896987-33a9-42e8-a15b-172edfabad8c.png)

The admin user is no longer created in the database:
![image](https://user-images.githubusercontent.com/13160762/157208033-935f373b-6cda-4662-bc52-2e6d136a6fdf.png)
 
This role error below was in the previous build too but only happened twice (happens many times here). I note that previously the "admin" user was only role 'admin' and never a registered user. 
```
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed. These requirements were not met:
RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Registered Users)
```
I will follow up with comparing start up log with previous code.. 

**Server start up log (MSSQL LocalDb) available here https://gist.github.com/ghhv/27310cc1393b08540d7001f9a3fca42d**

**Comment by sbwalker** [comment]
Ironically I added #2048 this morning to deal with this exact issue. Previously the host password was not being validated early enough in the installation process... and as a result you could end up with an installation without a host user created. Get the latest version and try again... you should get feedback immediately now if the password entered does not meet the policy requirements.

**Comment by ghhv** [comment]
And fixed thank-you. I can confirm the password complexity requirement is now working too. 

The server log is now getting a spray of these messages though:
```
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Identity.Application was not authenticated. Failure message: Unprotect ticket failed
```

And is this OK for the admin user? This was previous behaviour as well. 
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Registered Users)
```

**Comment by sbwalker** [comment]
As I mentioned in #2048, the Dev branch is still a work in progress in terms of the security enhancements - so do not expect it to be working correctly at this time.
