### ISSUE TITLE
New developer module has bad reference to Oqtane.Server?

### ISSUE THREAD

**Issue by ghhv** [oqtane/oqtane.framework#2047]
I think this is a tiny bug? - see pic with "Oqtane.Server (not found)" in a new developer module. 

![image](https://user-images.githubusercontent.com/13160762/157228424-98564e31-0b8e-4523-966b-2880ad282c0c.png)

Occurs with version 3.0.3 (downloaded 1st March 2022)

**Comment by leigh-pointer** [comment]
@ghhv remember that the paths have a base of Oqtane.Framework, install the framework to a different location then is error will appear.  If you have set up the code in Oqtane.Framework then there is something wrong.

**Comment by ghhv** [comment]
@leigh-pointer yeah, it's not that I think.. I've been able to reproduce with new installs. Parent path is correct.

**Comment by ghhv** [comment]
Testing on latest code base.

Steps:
Install Oqtane with MSSQL LocalDb
Login as admin
Open Develop Page, populate and click create.
![image](https://user-images.githubusercontent.com/13160762/157361174-7136f5c2-3318-44a8-b5d3-206458543527.png)
Open new solution in VS2022 - the Oqtane.Server reference appears again before I've done anything.
![image](https://user-images.githubusercontent.com/13160762/157361423-406064b4-5217-418d-a3c0-43347f03c829.png)

**Comment by ghhv** [comment]
So I figured out what's wrong - the parent path is hard-coded to "oqtane.framework" and my code unzip is defaulting to "oqtane.framework-dev"

**Comment by ghhv** [comment]
So testing again on fresh install with correct "oqtane.framework" path.

![image](https://user-images.githubusercontent.com/13160762/157365143-424c1625-ca4c-4402-aced-766bf46af9c4.png)

- the Activate module button still appears on module build and fails as before.
![image](https://user-images.githubusercontent.com/13160762/157365343-b789f1b7-26f4-4a26-ab16-ab9903d1df12.png)

- And as before, a proper server restart resolves the issue:
![image](https://user-images.githubusercontent.com/13160762/157365481-169004fd-9780-4987-a797-7c0c7fac6024.png)

Different issue now and minor but could be resolved.

**Comment by ghhv** [comment]
> @leigh-pointer yeah, it's not that I think.. I've been able to reproduce with new installs. Parent path is correct.

Yeah, I was wrong here - I see what you meant now.

**Comment by leigh-pointer** [comment]
@ghhv brilliant, happy coding :)
