### ISSUE TITLE
Invalid Site URL loses access to the site's admin?

### ISSUE THREAD

**Issue by ghhv** [oqtane/oqtane.framework#2054]
If you happened to create a Site with an invalid URL and you have not configured an alternative folder alias for example off the master site, it seems you are no longer able to get back to fix your mistake via the SITE MANAGEMENT page. 
e.g.
![image](https://user-images.githubusercontent.com/13160762/157835983-b10d3212-864c-4f85-821c-63e9054387ac.png)
Clicking EDIT or BROWSE here tries to take you to the bad URL (e.g. http://badtypo.com.zz/admin/site) and there seems to be no way to fix your mistake. 
I guess adding a temp record in the HOSTS file is an option but given this is editing from the MASTER site, should it not be using a route like this (http://localhost:44357/admin/sites/*/22/Edit) so access is guaranteed?

Note - this is all using latest code base on MSSQL localdb.

**Comment by ghhv** [comment]
And further to this, if there an alternative alias which still works, it is not visible as the list is only the default alias. 
![image](https://user-images.githubusercontent.com/13160762/157840603-75c2b211-d267-4036-a794-7b4805ddd150.png)

I had a look through the source for my own education.. tricky. The easy fix is just display all aliases and not just the default. 
![image](https://user-images.githubusercontent.com/13160762/157850262-b8513c22-b1a0-435e-ac3e-8cc0b697675c.png)
Grouping them would be an idea but the "Pager" component doesn't seem to have grouping built in (yet!). 

And I also had the thought, we could add the tenant name to the Site list but that was a lot more work too.

**Comment by ghhv** [comment]
Semi-related and probably a new issue but if you change the Site alias completely, the save fails.

![image](https://user-images.githubusercontent.com/13160762/158001480-9acd885a-2491-4eab-9d8e-17ca40b77c2c.png)
If you click 'View Details', it gives an unhandled exception
![image](https://user-images.githubusercontent.com/13160762/158001506-efa4670e-d7be-4756-ae64-223d606cce4d.png)
And this error in console and on server
```
blazor.server.js:1 
        
       [2022-03-12T03:04:38.692Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.UI.SiteRouter.Refresh() in C:\Data\git\Oqtane\OqtaneV3.0.3-March9\oqtane.framework\Oqtane.Client\UI\SiteRouter.razor:line 110
   at Oqtane.UI.SiteRouter.LocationChanged(Object sender, LocationChangedEventArgs args) in C:\Data\git\Oqtane\OqtaneV3.0.3-March9\oqtane.framework\Oqtane.Client\UI\SiteRouter.razor:line 278
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

**Comment by ghhv** [comment]
OK, just noticed another anomaly which was only obvious because I'm displaying the Site Ids on my Site Management  - after this error above, it seems to lose track of the next Site Id and is resetting to '1'. 
![image](https://user-images.githubusercontent.com/13160762/158003234-d8966dfe-a918-4d77-b8b8-f82127d42421.png)

**Comment by sbwalker** [comment]
All of the behavior described in this thread is by design.

Every site has a single Alias which is defined as the Default. All requests to non-Default aliases will be redirected to the Default. If you absolutely need to browse to a non-Default alias (ie. to fix a mistake) you can use the path /admin/site.

In a multi-tenant installation where you have multiple databases the SiteIds are an auto-increment column in each database... starting at 1.
