### ISSUE TITLE
Database username input field is read only

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#207]
Why did the username field change to read only for database configurations? When testing I usually use SQL Server on Docker and put in the SQL username/password.

I narrowed it down to this commit
https://github.com/oqtane/oqtane.framework/commit/0aed11e71ceb21ceab6747d76361d02c1ade49e9#diff-0ef3ddcdd51e2e8d9ee63623dfd01d37L62

![radonly](https://user-images.githubusercontent.com/11261164/74541335-6f61b700-4f0f-11ea-857f-cd0ee1d0dd87.PNG)

**Comment by sbwalker** [comment]
this is a bug introduced by mistake when the Site Admin username was made readonly. It is fixed in the latest PR #208
