### ISSUE TITLE
End up on https://localhost:44357/login?Returnurl=/tournamentregistration after Stripe-payment

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2080]
Hi!
I don't know if this is an error or not - so this is just for information.

I have struggled for the last two weeks that after a Stripe payment I end up on the page **https://localhost:44357/login?Returnurl=/tournamentregistration** instead of **https://localhost:44357/tournamentregistration**.

Site-Setup has been set to Prerender = Yes.

If I change this to Prerender = No then I end up on the right page.

**Comment by beolafsen** [comment]
Maybe...but it works fine if I set Prerender (in the Site-setup) = No.

**Comment by sbwalker** [comment]
As @leigh-pointer mentioned above, the usual reason a user would be redirected to the login page is because they do not have the rights to view the page they requested. So does the /tournamentregistration page in your site specify View rights for All Users? 

![image](https://user-images.githubusercontent.com/4840590/160177968-a3cb6502-6542-452c-87e1-97d9a8eb8602.png)

**Comment by beolafsen** [comment]
Thank you for helping. 
No, it does not specify View rights for all users. Only Admin and Registrated Users. 
When I do the test I'm logged in as host (admin).

For the test I have set the View permission to All Users.
When I do the payment with Prerender=No - it works fine. I came back to the /tournamentregistration page.

When I change to Prerender = Yes - it does not work.
After the payment I arrive on this page:
![Skjermbilde 2022-03-25 192335](https://user-images.githubusercontent.com/76835718/160179568-816fdc02-470f-4f6b-965f-27ecc0c42306.png)
As you can see from the picture - I''m still logged in after return from Stripe and I just have to select the tournamentregistration menu ("Påmelding") again. I don't have to login again. That means that I have the permissions?

**Comment by beolafsen** [comment]
Anohter observation:
This test is done by intialize payment  and when I'm into Stripe-payment page I just press back-arrow (not browser arrow - but Stripe-arrow). 
![Stripe_payment](https://user-images.githubusercontent.com/76835718/160183612-d2dc44d6-8fa3-464e-9d11-02960de68e78.png)


This is the network activity when Prerender (P) = Yes and No: (The test are done in the same way)

![PrerenderNo](https://user-images.githubusercontent.com/76835718/160183739-fefd2b25-f759-49ed-8f8f-5fe9e1951781.png)
![PrerenderYes](https://user-images.githubusercontent.com/76835718/160183751-3169c204-539c-43b8-a530-8030f5a68648.png)

**Comment by sbwalker** [comment]
It appears that a 302 redirect is happening in the second screen shot above and redirecting to the login page. This logic is located in the SiteRouter and it is only supposed to occur if the page path does not exist for the site and the user is not logged in:

// redirect to login page if user not logged in as they may need to be authenticated
NavigationManager.NavigateTo(Utilities.NavigateUrl(SiteState.Alias.Path, "login", "?returnurl=" + route.AbsolutePath));


I have no idea why Prerender would have any effect. Are you able to run the Oqtane project in Visual Studio and set a breakpoint in the Refresh method in SiteRouter.razor?

**Comment by sbwalker** [comment]
I believe Stripe requires you to pass a Success Url and Cancel Url to their service and it uses these Urls to redirect the user back to your site - so the Urls need to be absolute. What are you providing for a Cancel Url?

**Comment by beolafsen** [comment]
Hi!
The Success and Cancel Url are the same:
https://localhost:44357/tournamentregistration (in test)

I step through the logic in SiteRouter with Prerender set to Yes and No.
The difference I saw after returning from Stripe was:

Prerender set to NO:
The SiteRouter.Refresh is only done one time and the authState.User.Identiry.IsAuthenticated = True.

Prerender set to YES:
I SiteRouter.Refres is run 3 times and the authState.User.Identiry.IsAuthenticated has the following values the different times:
1.time - FALSE
2.time - FALSE
3.time - TRUE
![OqtaneDebug](https://user-images.githubusercontent.com/76835718/160195358-ba849de6-4655-4489-95b1-a4c7c6b151bd.png)

.

**Comment by sbwalker** [comment]
When pre-rendering is enabled, components are always executed twice - this is the expected Blazor behavior. The reason why it is executing 3 times is because of the 302 redirect (which adds 1 extra execution). The question is why would IsAuthenticated be False on the first execution... and then later change to True.

**Comment by sbwalker** [comment]
A bit of a long shot... try putting breakpoints in Oqtane.Server\Security\PrincipalValidator.cs in the ValidateAsync() method. I am curious if context.RejectPrincipal(); is hit on any code path - and if it is make a note of the Request Path.

**Comment by beolafsen** [comment]
I have been testing a lot today, and then suddenly it seams to work(in test - not in production) - without me doing anything. I see that the network log seams to be ok - like the one with Prerender set to NO. 
I will test the production tomorrow. Thanks for helping.

![PrerenderYes2](https://user-images.githubusercontent.com/76835718/160206641-85caf9b2-6add-4e2c-8e9b-51c7c631b26a.png)

**Comment by beolafsen** [comment]
Have just done a compile and publish it to IIS and it still fail when Prerender = Yes.
On the debug system - same application - it is ok now.
Strange!!! 
I go with the Prerender = NO - that works.

**Comment by sbwalker** [comment]
@beolafsen found this article on the Microsoft site: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#support-prerendering-with-authentication-1 which indicates "Prerendering content that requires authentication and authorization isn't currently supported" - which may be related to the behavior you were experiencing. I believe Microsoft intends to address this in .NET 7.

**Comment by beolafsen** [comment]
Very good. 

Thank you for the Feedback. 

Best regards  BEO
