### ISSUE TITLE
Username as email

### ISSUE THREAD

**Issue by sveinfolkeson** [oqtane/oqtane.framework#2083]
I agree with another contributor to skip the username and use the email instead as is the way to do it in most other systems.
Why not have an alternative login/register where you only add the email and let the system copy the email to the user behind the scenes. Then there shold not do any impacts on the system. Or?

**Comment by sbwalker** [comment]
I could certainly consider adding this option as part of the security enhancements in the upcoming 3.1 release

**Comment by sbwalker** [comment]
This will not be included in 3.1
