### ISSUE TITLE
Question - custom _Host.cshtml

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#211]
Is it possible to have custom _Host.cshtml per site ?

**Comment by sbwalker** [comment]
No it is not possible as Blazor expects a single entry point to the application ( and when running on Wasm the entry point is not _host.cshtml - it is index,html in the wwwroot of the Client project ). I think the more important question is why you are asking this question - and I am guessing it is because you would like to reference additional Javascript and CSS files. The optimal solution for this problem is to use JavaScript Interop and dynamically load JavaScript and CSS files based on the needs of the application. This keeps the static dependencies to a minimum.

**Comment by chlupac** [comment]
Yes, I will do it this way. Thank you.

**Comment by chlupac** [comment]
Actually I solved this problem with new project with custom _Host.cshtml page which loads Oqtane.  
I also need to register extra services and modify little bit startup.
I do not need to use wasm in this project. 
The advantage of this solution is that I can have references to my modules and themes here, which simplifies their development and debugging. 
My main is here:
```c#
using FluentValidation;
using Mfl.Data;
using Mfl.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Oqtane;
using Syncfusion.EJ2.Blazor;
using Syncfusion.Licensing;

namespace Mfl.Boot
{
    public class Program
    {
        public static void Main(string[] args)
        {
            SyncfusionLicenseProvider.RegisterLicense("");
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddConsole();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<MyStartup>();
                    webBuilder.ConfigureServices(x =>
                    {
                        x.AddSyncfusionBlazor();
                        x.AddDbContext<MyDbContext>(
                            ServiceLifetime.Transient);
                        x.AddTransient<IValidator<RegistrationModel>, RegistrationModelValidator>();
                    });
                });
        }
    }

    public class MyStartup : Startup
    {
        public MyStartup(IWebHostEnvironment env) : base(env)
        {
        }
    }
}
```

**Comment by chlupac** [comment]
I feel than this loader project can be startup point for using Oqtane as class library. I can imagine this as template for dotnet new. (https://devblogs.microsoft.com/dotnet/how-to-create-your-own-templates-for-dotnet-new/)
If somebody is interested I can prepare empty version of project and share it.
