### ISSUE TITLE
Adding user to Host role removes all other users roles

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.framework#2111]
I've seen this twice:  When you have a few users, and then you edit one of them and add them to the Host role, it deletes all the user-role mappings except root for everyone who is not Host.  Need to manually re-map all the user roles.

**Comment by sbwalker** [comment]
@markdav-is there is no role in the system named the "root" role - can you please explain what you mean?

**Comment by markdav-is** [comment]
@sbwalker I meant Host, not Root.  I've updated the ticket.  I know it was a short name.

**Comment by sbwalker** [comment]
@markdav-is once I understood that it was the "host" role I was able to reproduce the problem - it has now been fixed in #2116. Thank you for reporting the issue.
