### ISSUE TITLE
Adding Module requires app restart on server?

### ISSUE THREAD

**Issue by HybridSolutions** [oqtane/oqtane.framework#2133]
Hi just a quick question. After installing a module, it doesn't show up in available modules until the app is restarted. My question is, in a Tenant environment, with many clients, how would this work? For a client to be able to see/use a module just installed, he needs to request an app restart affecting all the tenants?

Wasn't Shadow Copy support launched with .NET 6, avoiding restarts?

Thanks!

**Comment by sbwalker** [comment]
You are correct, an app restart is required when you install new extensions. This has nothing to do with shadow copying - Oqtane's run-time installer is able to able extract all of the assets from a Nuget package and copy them to the appropriate locations. The technical limitation is that .NET Core does not allow you to add services to the services container after startup. I actually reached out to Microsoft with this exact question last year "Is there a way to register services in the container without a restart?" and the answer I received was "You're SOL here, there's no way to add services after startup."

**Comment by sbwalker** [comment]
So to better answer your question... you need to coordinate your deployments of extensions in Oqtane, exactly the same way you need to coordinate your deployments in any .NET Core application. Typically this involves an automated deployment process (ie. CI/CD) in most modern environments

**Comment by sbwalker** [comment]
If you are interested in my opinion, I definitely felt like I lost some capability in the transition from WebForms to MVC ( mostly in regards to UI component development and reusability )... however I feel that with .NET Core and Blazor I now have a development platform which checks all the boxes - the SPA architecture allows for more scalable apps and more responsive UI, the code is much cleaner, manages dependencies and integrations much better, and is much more maintainable.
