### ISSUE TITLE
Clean start, installation object is null

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.framework#2141]
Hi,

I just tried to start completely new oqtane framework instance/installation, in the following steps:
- Download and extract oqtane.framework zip file from github
- Set Oqtane.Server as Startup project
- Press Run
- Enter Administrator's data (username, password, ...)
- I didn't change Database Configuration
- Click Install Now

I get this error:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

In this line of code (Installer.razor, line 201):
200			var installation = await InstallationService.Install(config);
**201		if (installation.Success)**

What I am doing wrong?

Thanks,
Vedran

**Comment by pcancela** [comment]
I believe that is only broken in the dev branch. Did you try it on master?

**Comment by vzdesic** [comment]
> That happened to me too, I believe that is only broken in the dev branch. Did you try it on master?

Ah yes, master works. Thanks!
But, dev branch is more recent, so it will be good if it works for people who want to see recent changes.
