### ISSUE TITLE
CSS Display Issue - Nav Menu

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#2171]
When I click on an item in the nav menu, the previously selected item will have a dark blue border displayed around it:

![image](https://user-images.githubusercontent.com/4840590/166683073-3e46963b-043a-4de9-9245-077e22a93b15.png)

This is a 3.1.1 installation however I do not believe there were any CSS changes in recent releases which would have affected this. Has anyone else seen this behavior?

**Comment by sbwalker** [comment]
Its happening on oqtane.org as well

![image](https://user-images.githubusercontent.com/4840590/166693670-12447b64-93da-4a87-8776-d0b8109892f2.png)

So its not related to a specific theme - I suspect it must be related to a change in the Nav Menu.

**Comment by leigh-pointer** [comment]
Found this that might help is added to the Theme CSS
https://coderrocketfuel.com/article/remove-blue-outlines-from-links-in-chrome-and-firefox

**Comment by sbwalker** [comment]
thanks @leigh-pointer - the really strange thing is that I can not reproduce this issue in my local environment - it is only happening in the production environment - same Oqtane version and same Firefox browser!

**Comment by sbwalker** [comment]
This seems to be a modern browser accessibility feature. When you use the keyboard tab key to change the focus from one element to another, it displays a blue outline around the element with focus. It seems to behave differently across different browsers and even different versions of the same browser. I am going to close this issue as it is not related to Oqtane.
