### ISSUE TITLE
LastIPAddress not updated correctly

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2176]
The LastIPAddress field on the User class is not updating to the correct last ip of the remote user, but the server ip of where the framework is installed.

**Comment by sbwalker** [comment]
I assume you are running on Blazor Server? If so, this is because the "client" is actually running on the "server". There is a solution in Oqtane as the framework maintains the actual client IP Address as a property of SiteState - so this should be used to update the LastIPAddress.

**Comment by leigh-pointer** [comment]
Yes running Blazor Server.  Ok so there is the data.  Shall I create the PR?
