### ISSUE TITLE
Error in Module Creator if the template is not set

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2180]
![Skjermbilde 2022-05-05 162755](https://user-images.githubusercontent.com/76835718/166945681-aa47da16-4c20-4e25-a3f9-1b83f6bc4a22.png)

**Comment by sbwalker** [comment]
@beolafsen so you are saying the validation in the UI is not working, as it allows a user to create a module without choosing a template?

**Comment by beolafsen** [comment]
Yes - that is correct,
(I downloadet the latest version yesterday.)

I have testet it this morning and sometime I get the error and sometime not.

As you  can se here - I try to create  from Module Management. It works fine.
![image](https://user-images.githubusercontent.com/76835718/167080837-1073b651-6c76-4917-964a-bfc509a0a067.png)

Then I do the same from the Control Panel
![image](https://user-images.githubusercontent.com/76835718/167080989-09431d68-b429-4102-a67d-6e096fed2da4.png)


Then I get the error
![image](https://user-images.githubusercontent.com/76835718/167081075-5e021c1f-740f-4c8e-90eb-b348ea129746.png)
![image](https://user-images.githubusercontent.com/76835718/167081147-6b8af4a7-39d2-4cf3-a97a-cd6f06889569.png)
