### ISSUE TITLE
Upload photo fails with oqtane 3.1.1

### ISSUE THREAD

**Issue by manuellungoci** [oqtane/oqtane.framework#2184]
Hi there,

After a fresh install of oqtane 3.1.1

I think you forgot to add the antiForgeryToken in the header of the interop.uploadFiles request

Suggest this solution:
I sent the two parameters from FileService : Constants.AntiForgeryTokenHeaderName and _siteState.AntiForgeryToken

I called the setRequestHeader after request.open('POST', posturl, true); and everything works fine afterwards.
    var request = new XMLHttpRequest();
    request. open('POST', posturl, true);
    request.setRequestHeader(antiForgeryTokenHeaderName, antiForgeryToken);
  
  Regards,

**Comment by sbwalker** [comment]
already fixed in #2174
