### ISSUE TITLE
Alias handling - Sent to localhost on published version

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2185]
I have a database that I want to share between localhost and published trial version. I created the database in localhost and a record was added to the Alias ​​table.

![image](https://user-images.githubusercontent.com/76835718/167244076-8374ac9c-6337-4179-ba1e-b2cadcb3e37c.png)

Then I published the program and tried to start the published version (oqtanelibrarystaging.webzenter.com)- but it start localhost with the message : Err_connection_refused.

![image](https://user-images.githubusercontent.com/76835718/167244170-99303504-0256-4af6-9bb0-f3fef91bfa52.png)

Now - there are added one more line in the alias table:
![image](https://user-images.githubusercontent.com/76835718/167244270-1e2a8128-712c-4bc5-97eb-496a3362137c.png)

And for every time I try to start the publised version - it's added a new line in Alias table:
![image](https://user-images.githubusercontent.com/76835718/167244369-c418f496-0136-4ba5-877d-ec34c865c980.png)

If I try to set one of the other Alias records to IsDefault = true and Localhost recorden to False:
![image](https://user-images.githubusercontent.com/76835718/167244460-8a236523-d59a-44ec-977d-1845c9cf81e0.png)

Then the publised version is started - but I get the message - ERR_TOO_MANY_REDIRECTS
![image](https://user-images.githubusercontent.com/76835718/167244529-2e5378c5-a6e9-40c9-b74e-719542a96030.png)

After doing all this the alias tabel has been added with 105 records - where 104 of them are equal.
![image](https://user-images.githubusercontent.com/76835718/167244678-ed324cf7-f69a-4b60-9701-7d7e6f73d040.png)

If I change the Url in the Alias-record where I have set the IsDefault = true.
From "oqtanelibrarystaging.webzenter.com/"  to "oqtanelibrarystaging.webzenter.com" (I just remove the last slash).
Then I can start the published version and now it don't add more alias records.

So - I go back to my development system and try to run a debug against the same database. Then it start the published version instead of Localhost.

Then I change the localhost record in the alias-table where I set the IsDefault to True. Then the localhost is started from the debug and the published version is also started correctly(?? strange).

I think there are a problem with the backslash in the url-name - so for testing this I deleted all the records in the alias table except the localhost record. Then I started the publised version. It sent me - like before - to the localhost - and it added one record to the alias-table. I removed the backslash from the URL and then started the published version again.
![image](https://user-images.githubusercontent.com/76835718/167245771-c02461ce-df03-4810-95a1-5f05a5ddc26a.png)
It still send me to the localhost - also after restart of the application in IIS. BUT it don't add more records to the Alias table. I guess there are a test in the program where the url without backslash is testet against url with backslash.

Then I try to set the IsDefault to the true in the not localhost record. 
![image](https://user-images.githubusercontent.com/76835718/167246130-49a43e96-1e4a-4b6a-be7e-2efc7f438455.png)
It still send me to the localhost when I try to start the published application.
Then I try to restart the application In IIS - and then the published application start - but not the debug (localhost).

I don't know exactly  how the alias handling should work - but it would be fine if we can use the same db from a published app and a localhost app.

**Comment by sbwalker** [comment]
There can only be 1 alias that is flagged as IsDefault for a site. The behavior is described in this blog: https://www.oqtane.org/blog/!/1/oqtane-3-0-2-released. If you are trying to share the same database for both production and development (which is not recommended) you will need to modify the contents of the Alias table to swap the IsDefault field, as there is currently no support for this scenario.

**Comment by beolafsen** [comment]
OK - thank you for the clearification.
The idee was not to have a production and development shares the same db - but have a developent and pre-production (test production version) shares the same db. 

We have experienced that even if things work well in a development environment, after being installed on the production machine, the production machine will not start again. Therefore, we want a test-production machine to test the installation package before a possible installation in production. It is also nice to have a place to test the version on iPhone etc.
But - we will solve this by adding a new db for the pre-pdroduction.
Thank you for helping.
BEO

**Comment by sbwalker** [comment]
So the UI does not support this but I believe you can manually set IsDefault for multiple Alias records for a Site and the framework will not redirect if IsDefault is set.

**Comment by beolafsen** [comment]
Great - I will check it out.

**Comment by beolafsen** [comment]
When I set both (localhost and publised site) to IsDefault = true it works fine. But when I do a Save in SiteSettings - one of them are set back to False.

**Comment by sbwalker** [comment]
That is correct - that is what I meant when I said the UI does not support it.

**Comment by beolafsen** [comment]
I understand - but is there anything that could be changed in the octaine framwork or does it have other implications. I think it is a nice feature that maybe others will also benefit from.

**Comment by beolafsen** [comment]
Have you changed this function so that it is no longer possible to work around this by setting more URLs with IsDefault = true. After installing 3.1.2 I'm be sent to localhost even though I have defined IsDefault = true on the URLs

**Comment by sbwalker** [comment]
There was no change in 3.1.2 to this area.
