### ISSUE TITLE
I can't configure SMTP

### ISSUE THREAD

**Issue by elgransan** [oqtane/oqtane.framework#2204]
Hello I'm having throubles to set to my staging enviroment (on Azure) the STMP settings (I'm using SendGrid)

Site -> SMTP Settings:
![image](https://user-images.githubusercontent.com/9949584/168926699-c4f6798b-7289-482f-ad29-0f4ba7370844.png)

I'm getting from SendGrid this when I test the connection:
Scheduler Job Log:
Mailbox unavailable. The server response was: The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements

I did a "select * from notification" and I saw the from address is empty
![image](https://user-images.githubusercontent.com/9949584/168926639-85c397e8-1bff-4bbd-837b-4a9b3a9994fe.png)

It's taking the from address from another place?

**Comment by sbwalker** [comment]
Your screen shot cut off the Sender field which is the "from" address that SendGrid is referring to:

![image](https://user-images.githubusercontent.com/4840590/169024370-afbd4e41-d1b8-4d0d-a712-96ec4a7c975d.png)

**Comment by elgransan** [comment]
Yes sorry I cutted off the sender but it's complete

![image](https://user-images.githubusercontent.com/9949584/169060226-758516d4-0484-4704-a5b2-ef2cf9b26883.png)

**Comment by sbwalker** [comment]
I purposely included the help text for the Sender field as it contains the note "Please note that this email address may need to be authorized with the SMTP server". Is the "no-responder" email address authorized within your SendGrid account settings?

**Comment by elgransan** [comment]
Yes, at first I tried to authorize the SendGrid account (no-responder) from this app but I finally did it from outside smtp client and it's working, but in oqtane test button I still getting the error message. I'll try to configure a real notification ...

**Comment by sbwalker** [comment]
I use SendGrid in my Oqtane installs and it works fine

**Comment by elgransan** [comment]
Ok, I tried on my local and it's working with the same configuration, it seems a security related issue using smtp over Azure App Service.
