### ISSUE TITLE
Page - Manage Settings 

### ISSUE THREAD

**Issue by Domeman** [oqtane/oqtane.framework#2213]
Click on Manage Settings. Display On All Pages? Clicked Yes. It displays on all pages. 
Click No. It still shows on the Pages. 

Question or issue is should still display when Display On All Pages? is clicked No, after clicking Yes. 
Are you required to manual go and delete the page from all the places it showed?

**Comment by sbwalker** [comment]
This use case was not implemented yet - however I have a solution which I will check in shortly
