### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#2214]
@sbwalker I just started a new installation to create a proper fix for the localization issue, after clicking install I got the following error

An Error Occurred Executing Upgrade Logic. Invalid column name 'CaptureBrokenUrls'. Invalid column name 'RenderMode'. Invalid column name 'Runtime'. Invalid column name 'Version'. Invalid column name 'VisitorTracking'.

**Comment by sbwalker** [comment]
@hishamco what type of database are you using? Did you get the latest assets from the repo? In particular did you get the latest data provider packages located in \Oqtane.Server\wwwroot\Packages (the packages all have a *.bak extension). My guess is that your Oqtane environment has not been updated for quite a while. You might want to delete your local appsettings.json file as well so that a new one is created (in case you made customizations in the past).

**Comment by hishamco** [comment]
> what type of database are you using?

I tried LocalDb, then Sqlite same thing

> Did you get the latest assets from the repo?

I  just fetch the latest bits this morning

> In particular did you get the latest data provider packages located in \Oqtane.Server\wwwroot\Packages (the packages all have a *.bak extension).

I will check

> You might want to delete your local appsettings.json file as well so that a new one is created (in case you made customizations in the past).

I just fetch the latest so nothing tracking via Git

FYI after running the app, I saw the latest migration runs in `3.0.1.3` or `3.0.0.1` if I'm wrong, which indicates something not applied after

**Comment by hishamco** [comment]
![Backups](https://user-images.githubusercontent.com/3237266/170253502-0e92a000-2245-462a-a11d-e1860505868a.png)

**Comment by sbwalker** [comment]
I am not sure why it's not working for you... but it appears you do not have the latest database providers installed. This is supposed to happen automatically during upgrade. You can try to copy those *.bak packages to the Oqtane.Server\Packages folder and remove the *.bak extension. When you run Oqtane it will install the *.nupkg packages in that folder ie. extract the DLLs to the /bin. Hopefully that resolves your issue.

**Comment by hishamco** [comment]
Finally it works after removing the .bak, seems I faced an issue during the restore

Thanks

**Comment by hishamco** [comment]
BTW is the login required email verification? Seems there's a new change here from last time I used the source

**Comment by hishamco** [comment]
I notice something strange, no user has been added to `AspNetUsers` not `User` table?

**Comment by sbwalker** [comment]
I assume you entered the details for the initial user in the Installation Wizard during install? In the past, a user would sometimes not be created if you provided a password which did not meet complexity criteria - or you entered an invalid email address. However both of these issues were resolved in recent versions (passwords are now validated). Based on the other issues you reported I am wondering if you are using the latest code.

**Comment by hishamco** [comment]
Just a fresh installation, let me clean everything and try again

**Comment by hishamco** [comment]
I just disable the password validation at the beginning, remove all the changes makes things work fine

Thanks

**Comment by sbwalker** [comment]
@hishamco are you saying that there is a problem with the password validation logic? I have tested it myself and if the password entered does not meet the criteria, it provides feedback to the user and prevents installation. Is this not working for you?

**Comment by hishamco** [comment]
It wasn't working that's why I disabled the logic at the beginning, now everything is fine. Hope to find some time I need to push some PRs
