### ISSUE TITLE
Problem with site creation and logger

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#224]
Current logger is dependent and an error in the logger will cause the application to crash. 
Create new site :> save > logger is trying to save log for siteid == -1 , site is not created correctly.
It is not first time when logger causes crash. I think than log was fired before site was created,  cause of FK key exception in DB.

1. Use standard logging engine (for example https://github.com/BlazorExtensions/Logging) with configurable targets. Log cannot fire an exception to main app.

2. Use database transaction for complex changes, rollback when fail. In this case site was not created completely and cannot be edited or deleted

update: 
dbo.Alias after crash:

![image](https://user-images.githubusercontent.com/7838468/75115963-0d6a2580-5664-11ea-8c59-517458164338.png)

alias was created with siteid -1 it's main bug

**Comment by chlupac** [comment]
![image](https://user-images.githubusercontent.com/7838468/75115930-acdae880-5663-11ea-9303-e617055b69f1.png)
update: alias was created with siteid -1 it's main bug

**Comment by sbwalker** [comment]
Are you able to provide some context so that the error can be reproduced? ie. on a clean install you went to Site Management, clicked Add Site, entered x, y, z for the fields and clicked Save.

**Comment by chlupac** [comment]
checked now with most recent version
clean install > site management > add site > fill form > save
![image](https://user-images.githubusercontent.com/7838468/75134364-5ced3780-56de-11ea-8993-6d076e047f36.png)

**Comment by chlupac** [comment]
workaround is remove relationship between site and log (i thing is not necessary here).

\Oqtane.Client\Modules\Admin\Sites\Add.razor
`                List<Alias> aliases = new List<Alias>();
                urls = urls.Replace("\n", ",");
                foreach (string name in urls.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
                {
                    Alias alias = new Alias();
                    alias.Name = name;
                    alias.TenantId = int.Parse(tenantid);
                    alias.SiteId = -1;
                    **alias = await AliasService.AddAliasAsync(alias);**
*********************************************************************************************
alias added for unknown site > log fails
                    aliases.Add(alias);
                }

                Site site = new Site();
                site.TenantId = int.Parse(tenantid);
                site.Name = name;
                site.LogoFileId = null;
                int logofileid = filemanager.GetFileId();
                if (logofileid != -1)
                {
                    site.LogoFileId = logofileid;
                }`

**Comment by chlupac** [comment]
created PR with fix.

**Comment by sbwalker** [comment]
Is the Alias "klubovna.zitmebavi.local:44357" a unique value - or is it the same Alias you are already using for the default site created during installation?

**Comment by sbwalker** [comment]
I would like to ensure we are fixing the right problem here - and perhaps there is more than one problem but I am unable to reproduce the issue at this point. I am guessing it is related to your environment and the values you entered when you attempted to create the site. If the value "klubovna.zitmebavi.local:44357" was already used as the alias for your default site during initial then this would cause a problem as an Alias cannot point to 2 sites - that is illogical. If this is the problem then the solution is to do validation on the Alias values entered to ensure they are unique.

**Comment by mikecasas** [comment]
I get your last comment, but is the add site functionality working? I never get a clear response from the  page when I click save. Although when I go back to the Site Management page, I do see the site I entered, so it is being saved in the database,

**Comment by chlupac** [comment]
No, initial alias is localhost:44357, it's completely fresh install, Site was added as first step after install. It's about order.
Look at code: 
1. Saving alias ... site is not created yet, saved with siteid = -1 
2. App is trying log alias save event but here is FK constrain between site and log -> saving log failed, no try/catch on alias controller, whole action fail, site is not created. database is inconsistent.

**Comment by mikecasas** [comment]
Alias does get created in the table, but the site doesn't get created. I get a bad host error on the site i just created.

**Comment by chlupac** [comment]
mikecasas: and app is not responsive at this moment, sure? Because is crashed. Only alias was saved. Alias has id -1. This is same problem which i'm trying explain to Shaun.

Shaun, another error, when you register wrong alias, app crashed too. Lot of If  and try/catch statements is missing here.

i have this in host file for test multisite:
127.0.0.1  zitmebavi.local
127.0.0.1  www.zitmebavi.local
127.0.0.1  klubovna.zitmebavi.local

and i'm running web under kestrel, not under iis express 


paranoid site creation procedure should be:
1. Check alias for duplicate
2. check api on alias(es) if is responsive and if same Oqtane instance is here (maybe check generated guid of instance)
3 check tenant, database connection 
3 validate rest of fields
4. start database transaction
5. save site / aliases, generate site defaults
6. check and if successful, commit

**Comment by sbwalker** [comment]
I was able to reproduce the problem - and its actually a lot more complicated than it seems as it is related to multi-tenancy. At its core multi-tenancy is enabled by Alias values which are associated to Sites and Tenants. - so the order in which these objects are created is important. The logging error is a symptom - but it is not the primary cause. I have a partial solution but it needs to be tested to ensure it works under the scenario where you are using multiple Tenants(databases) - not just a single shared Tenant(database).

**Comment by sbwalker** [comment]
I am very happy that you are testing the framework and reporting issues, as stabilizing is exactly what is needed to reach an MVP milestone.

**Comment by chlupac** [comment]
I know than logging error i symptom, but independent configurable logger with various sinks is important and not so difficult to implement. 

I like Oqtane concept and I'm willing to participate.

**Comment by sbwalker** [comment]
This is resolved  with #228 . I will post a more lengthy explanation in this thread later this evening.

**Comment by sbwalker** [comment]
further changes in #229 to deal with additional scenarios

**Comment by sbwalker** [comment]
So the challenge here is related to multi-tenancy. In a client-server application, the front-end is disconnected from the back-end so you need to explicitly pass state between them. In Oqtane this is accomplished via the Url - all service calls from the front-end to the back-end are in the form of http://host/folder/api/Entity. The host and folder are used to map to an Alias ( a folder of "~" indicates that it is a root Alias ). An Alias is mapped to a Tenant and a Site in the Master DB. The Tenant identifies the database and all calls to repository methods need to know the Tenant, as this is where the connection string is stored. This all works fine except for the situation where you are operating within one Alias/Tenant/Site and try to manage some resources that are part of another Alias/Tenant/Site, as you are crossing a logical boundary.  Luckily the only use case in Oqtane where this is required is when you are creating a new site. I made a number of changes to handle this scenario and tested it with both isolated and shared databases and it seems to work. Again, this has nothing to do with Logging - it was a just a coincidence that logging was the first service called that could not handle the cross boundary communication. To test this I would encourage you to do the following:

- clean install
- login as host
- go to Tenant Management and add a new Tenant
  - call it Tenant2 and accept the default values for the database connection ( assuming you are using LocalDB )
- go to Site Management and add a new Site
  - select Tenant2 as the Tenant
  - enter a Site name and a unique Alias value - note that the easier way to do this is to add a folder to the url ( ie. localhost:44357/site2 is a valid Alias )

**Comment by sbwalker** [comment]
So the challenge here is related to multi-tenancy. In a client-server application, the front-end is disconnected from the back-end so you need to explicitly pass state between them. In Oqtane this is accomplished via the Url - all service calls from the front-end to the back-end are in the form of http://host/folder/api/Entity. The host and folder are used to map to an Alias ( a folder of "~" indicates that it is a root Alias ). An Alias is mapped to a Tenant and a Site in the Master DB. The Tenant identifies the database and all calls to repository methods need to know the Tenant, as this is where the connection string is stored. This all works fine except for the situation where you are operating within one Alias/Tenant/Site and try to manage some resources that are part of another Alias/Tenant/Site, as you are crossing a logical boundary.  Luckily the only use case in Oqtane where this is required is when you are creating a new site. I made a number of changes to handle this scenario and tested it with both isolated and shared databases and it seems to work. Again, this has nothing to do with Logging - it was a just a coincidence that logging was the first service called that could not handle the cross boundary communication. To test this I would encourage you to do the following:

- clean install
- login as host
- go to Tenant Management and add a new Tenant
  - call it Tenant2 and accept the default values for the database connection ( assuming you are using LocalDB )
- go to Site Management and add a new Site
  - select Tenant2 as the Tenant
  - enter a Site name and a unique Alias value - note that the easier way to do this is to add a folder to the url ( ie. localhost:44357/site2 is a valid Alias )

**Comment by sbwalker** [comment]
In regards to the comments about Logging, I originally tried to use the "standard" logging engine as well as SeriLog but I could not get it to work. This is because of the specific requirements in Oqtane:

- the logger needs to write to a database sink, as the main goal in Oqtane is that a user should be able to access the log information through the user interface and not be required to have access to the server to open a log file or need to use raw SQL to query the log.
- the database sink needs to support multi-tenancy with both isolated and shared databases - this was the biggest challenge with Serilog as how it obtains the connection string is not extensible.
- the user needs to be able to retrieve log information partitioned by site
- the logger needs to support both client-side and server-side scenarios

The current logger implementation satisfies these requirements. There was a bug that needed to be fixed to deal with the cross boundary multi-tenancy scenario during site creation but it is certainly not a reason to rip out the current logger and replace it with something else.

**Comment by mikecasas** [comment]
I was able to test the above and it worked. One question, how is routing handled when you have the default site and create a page named 'site2', and also have an alias/site named 'site2'? 

I tested it and when I click when on the site2 page from the default site, I am taken to the default page of the  site2 alias. I am logged in as host, so I know I have access to both sites, and that may not be the case with all users, but should we worry about page/site routing collisions?

**Comment by sbwalker** [comment]
Yes this is a known limitation that there is some potential for naming collisions between alias' and pages. This should be handled at a business level by naming your microsites appropriately to try and avoid naming collisions ( ie. dont name a microsite "home" )

**Comment by sbwalker** [comment]
The only technical way to handle this would be to have some delimiter or segment in urls to designate a microsite vs. a page ( ie. site.com/microsite/-/page )  - but then the user would lose some control of their clean url naming format, which is not a good solution.

**Comment by chlupac** [comment]
I'm testing this scenario with site in folder now. looks very unstable.

**Comment by sbwalker** [comment]
I am not sure what you are testing - but the "microsite" method have an alias in the form of site.com/folder is the main way I have been testing multi-tenancy since the beginning of the project - so it definitely works.

**Comment by chlupac** [comment]
yes, it works in way how is designed, but it's not bulletproof. We have to test any stupid scenario and input from user and application must not crash and action must be recoverable.

**Comment by chlupac** [comment]
About logging: 
I made a mistake in my analysis and thanks to your clarification I think we need to distinguish between two types of log:

1. The operating log to the database is fine as it is, just make sure it is robust and independent.

2. Diagnostic log for debugging and troubleshooting. ILogger service is already present in the application, used by .net framework. So just use the Ilogger service and it's done. Simple solution.

**Comment by sbwalker** [comment]
I think the topic of how to identify a microsite url should be raised in its own issue. And possibly logging, although I am not a fan for having 2 different logging techniques in the framework - it makes it very difficult for developers to know which one to implement in their modules, and difficult for administrators to know where to go to review their log messages. We had this dual approach in DNN and it was a nightmare. I would much prefer to focus on a single logging technique which captures all of the potential issues.
