### ISSUE TITLE
Unable to add new site/tenant with Postgres as it doesn't have a way to pass the db login details

### ISSUE THREAD

**Issue by ghhv** [oqtane/oqtane.framework#2245]
![image](https://user-images.githubusercontent.com/13160762/174557882-0b42324c-8d1e-4849-81e9-1d6346a3178f.png)

Maybe it's meant to use the captured details from the admin 'host' user but this isn't a Postgres login - I tried that as well.

**Comment by sbwalker** [comment]
This is strange as an initial installation of Oqtane allows a user to provide all of the necessary config details for PostgreSQL - and the Add Site feature should be using the same components. I will do some investigation.

**Comment by sbwalker** [comment]
@ghhv I just tried it myself and selected PostgreSQL from the Database Type field and it displays the config options (I had to choose Custom for Security to allow for the entry of User Id and Password ). Can you please try choosing different options in the Database Type field to see what happens? Are you using the last version?

![image](https://user-images.githubusercontent.com/4840590/174606654-1a641dde-eaa9-4a2f-9183-1209b64b0e4c.png)

**Comment by sbwalker** [comment]
I think I figured out why this was not working for you - the default database type was not being set correctly when the component was loaded.
