### ISSUE TITLE
BUG: email notification going out for Site Critical Notification even when notification threshold is set to None

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.framework#2259]
backstory in this discussion: https://github.com/oqtane/oqtane.framework/discussions/2014

I'm investigating a bug where we continue to get errors emails to us even when the site logging level is set to none. We keep checking the setting the option, but either the setting is not sticking or being ignored.  I was setting it using the UI under System Info - Options - Notifications = None (see attached screenshot) and I just verified that the server settings match (json below). So I'm going to look at the notification code is see if there is some logic setting that's off. I'll also restart the app service. 

"LogLevel": {
      "Default": "Information",
      "Notify": "None"
    }
![image](https://user-images.githubusercontent.com/311063/176049998-3cdb854a-39ce-4ff1-a82b-5116fc66b386.png)

**Comment by sbwalker** [comment]
I am unable to reproduce this issue. In my local installation I have notifications set to None:

```
  "Logging": {
    "FileLogger": {
      "LogLevel": {
        "Default": "Error"
      }
    },
    "LogLevel": {
      "Default": "Information",
      "Notify": "None"
    }
  },
```
And I added code to throw an exception to the Html/Text module in the OnParametersSetAsync() method. The SendNotification() method is called in LogManager however no notification is created because the config is set to None.

**Comment by sbwalker** [comment]
@markdav-is it would help if you included the details of the error message being sent in the notification so that the specific use case could be identified in the framework.

**Comment by markdav-is** [comment]
Thanks for trying to re-create.  The message we are getting notified about is a critical error of a missing image. 

```
NotificationId	SiteId	FromUserId	ToUserId	ToEmail	ParentId	Subject	Body	CreatedOn	IsDelivered	DeliveredOn	DeletedBy	DeletedOn	IsDeleted	FromDisplayName	FromEmail	ToDisplayName	SendOn
5404	1	NULL	5	redacted@trifoia.com	NULL	Site Error Notification	Please visit http://localhost:44357/admin/log for more information	2022-06-28 05:40:15.1195025	0	NULL	NULL	NULL	0			brandonm	2022-06-28 05:40:15.1195025
```
LogId	SiteId	LogDate	PageId	ModuleId	UserId	Url	Server	Category	Feature	Function	Level	Message	MessageTemplate	Exception	Properties
1931	1	2022-06-28 15:11:06.7167629	NULL	NULL	3	http://localhost:44357/api/file/download/1	MARKD	Oqtane.Controllers.FileController, Oqtane.Server, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null	FileController	Read	Error	File Does Not Exist 1 D:\repos\3031-selsg\src\oqtane.framework\Oqtane.Server\Content\Tenants\1\Sites\1\logo-white.png	File Does Not Exist {FileId} {FilePath}	NULL	{"FileId":1,"FilePath":"D:\\repos\\3031-selsg\\src\\oqtane.framework\\Oqtane.Server\\Content\\Tenants\\1\\Sites\\1\\logo-white.png"}

**Comment by sbwalker** [comment]
@markdav-is the records you shared do not seem to be correlated to one another - the notification was created at 2022-06-28 05:40 and the error log item was created at 2022-06-28 15:11 - nearly 10 hours apart. So I don't think this error log item triggered the notification. As a side note, in the 3.1.3 release the notification body now contains a link which includes the specific logid - so it is much easier to correlate the specific log item (thanks to @chlupac for this suggestion).

**Comment by markdav-is** [comment]
I might have found the error is not an error, but the developers also need to update their local configs to include the  setting
```

 "LogLevel": {
      "Default": "Information",
      "Notify": "None"
    }
```

**Comment by leigh-pointer** [comment]
@markdav-is nice :)

**Comment by sbwalker** [comment]
@markdav-is so this is not an issue, and should be closed - correct?
