### ISSUE TITLE
Publishing Oqtane version 2.0.0.0 From Visual Studio 2019

### ISSUE THREAD

**Issue by engsky** [oqtane/oqtane.framework#2267]
Extracting [Oqtane.Framework.x.x.x.Install.zip] to IIS works fine and deployed correctly, but i try publish the framework from my VS seems not published correctly. i try with and without connection string. may need some configurations, API operations, or Authentication ?  to correctly publish?

**Comment by engsky** [comment]
@leigh-pointer yes our project uses oqtane modular architecture

**Comment by leigh-pointer** [comment]
@engsky have you created the Modules using the Oqtane Module Creator ?  If so all really needs to be done is build your module in release mode and the framework will produce an installation package in the Packages folder.

**Comment by engsky** [comment]
@leigh-pointer I manully create the modules in identical manner that created by module creator also the packages and the dlls copied to the bin folder of the framework .. in debug works fine and the modules displyed but the problem only in IIS I cant login the api not working!  I stated prepared upgrading to 3.1.3 version and see if same problem exsist.  Thank you.

**Comment by leigh-pointer** [comment]
@engsky please verify with me that you have followed these step is setting up IIS https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis

**Comment by engsky** [comment]
There is a note in step 5 stated as : "
Note: Do NOT attempt to Publish a release directly from Visual Studio as there are critical build configurations which will not be included in the output if you try to use this approach." What is these build configurations ?

**Comment by leigh-pointer** [comment]
Everything you want to know about the configurations is in the Oqtane.Framework/Package folder.
