### ISSUE TITLE
Role and Permissions seem to have stopped working.  Oqtane 3.1.3

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2271]
I created a role called 'Editor' and assigned it to a user
on the MIT (HTML module)  license section of Oqtane I added the Role 'Editor' with View and Edit permissions.
I Logged in as the editor and (was expecting to be able to edit the HTML module) was not the edit the HTML module.

Also so a permission with edit rights can not save data to the database.  Unauthorised access message.

**Comment by leigh-pointer** [comment]
So the use case that you are describing is exactly what I was expecting (but with out step 3) so therefore Page Edit rights need to be assigned but assigning page edit will allow the user who can edit the module the ability to modify page settings which is not ideal. 

As to the database update for this role, I am at a loss because it has been working before.

**Comment by leigh-pointer** [comment]
@sbwalker just as a sanity test. I created 3.1.2 instance of Oqtane and the Editor user can save to the database with the Edit permission set.

**Comment by sbwalker** [comment]
@leigh-pointer it is not clear to me if you were reporting 1 problem or 2 different unrelated problems in your original post - can you please provide the exact steps to reproduce what you mean by "Also so a permission with edit rights can not save data to the database. Unauthorised access message."

**Comment by sbwalker** [comment]
@leigh-pointer Can you please try the steps below in your installation:

1. Login as Admin and create an Editor role
2. Create an Editor user and assigned the user to the Editor role
3. Modify the Home page permissions to provide the Editor role with Edit rights 
4. Log in as the Editor user
5. Click the pencil icon to go into Edit Mode
6. Selected the Edit button on the Welcome to Oqtane... Html/Text module
7. Edit the content and click Save
8. Verify if the content was saved successfully without any issues

The steps above rely on the user having module Edit permissions to change the module's content. So it will validate whether or not the Edit permissions are working in your installation.

**Comment by leigh-pointer** [comment]
@sbwalker 
I have followed thous steps and that works! So the role can save.
I was looking at the controller on my mos and saw that it had a [ValidationAntiForgeyToken] attrib on the Post and Put methods! Removing that solved my issue!

**Comment by leigh-pointer** [comment]
[ValidationAntiForgeyToken] attribute was applied to the Post and Put methods, removing the attrib resolved the issue.
