### ISSUE TITLE
Versioning for Language packs

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2275]
it would be beneficial to see what version of the LP's that are installed.

**Comment by sbwalker** [comment]
I am working on a solution for this item

**Comment by sbwalker** [comment]
@leigh-pointer #2292 should resolve the issue you mentioned in this issue. It will now display the version of the translation for a language in Language Management (if it exists).

![image](https://user-images.githubusercontent.com/4840590/179358226-40db4cb3-1b0b-42d7-8da5-fed6f20d488a.png)

**Comment by sbwalker** [comment]
The ability to install translations for modules or themes will be added next.

**Comment by leigh-pointer** [comment]
@sbwalker nice thanx
