### ISSUE TITLE
Webassembly ZipArchive exception 

### ISSUE THREAD

**Issue by engsky** [oqtane/oqtane.framework#2276]
In LoadClientAssemblies within program. cs Oqrane.Client there is exception happend due to the Internet Download Manager IDM when its directly pluggin in browser to download files automatically. This exception 
at System. IO. Compression. ZipArchive. ReadEndOfCentralDirecory(). Solved by remove the zip type from IDM file types.

So is there any solution to this issues without removing the zip file type from IDM?

**Comment by sbwalker** [comment]
Please see the conversion in this thread: https://github.com/oqtane/oqtane.framework/pull/1460 - the decision was made to use ",dll" as the extension for the ZIP file so that it would not conflict with IDM.

**Comment by engsky** [comment]
@sbwalker Thank you.

**Comment by sbwalker** [comment]
@engsky I am confused as you were reporting that you were getting an error from this method - do you not still have a problem?

**Comment by engsky** [comment]
@sbwalker I am not test that but I am sure it will be solved as not nessary to be in extension zip while the important thing is to download the dlls from server to client as compressed archive with any extension not catched by IDM
