### ISSUE TITLE
Environment Variable

### ISSUE THREAD

**Issue by Sen-Gupta** [oqtane/oqtane.framework#2277]
Hello Oqtane community,

We containerized and tried to pass connectionString from environment variables. 

The observation is that environment  variables are picked by containers but not being honoured by Oqtane.

It seems it is becuase of ConfigManager which just tries to read values from appsettings.

Please let me know if, I got it correctly.

Is there a reasoning behind not honouring environment variables?

**Comment by Rodien** [comment]
Please provide more information.

How are you storing and passing the environment variables?

Are you using azure? 

Show a code snippet. 

Provide more information and you may get help more quickly.

**Comment by sbwalker** [comment]
@Sen-Gupta are you referring to the ability to have appsettings.json files for each environment? ie. appsettings.development.json?

**Comment by sbwalker** [comment]
resolved by #2295
