### ISSUE TITLE
compiling error: missing Oqtane.Client, Oqtane.Server and Oqtane.Shared  when a new module is created

### ISSUE THREAD

**Issue by jaruiz-ual** [oqtane/oqtane.framework#2282]
I am using the last Oqtane release. I  have created a new module using the Module Creator utility. But when I try to compile the source code generated I get those compiling errors.
It seems the related assembly files are not included in the Visual Studio projects dependences. Also the Oqtane.Server Project is not found in the solution.
![image](https://user-images.githubusercontent.com/62284884/178787269-a133e6b3-79fe-4232-a110-cd43009bd4b8.png)

**Comment by sbwalker** [comment]
This usually happens when you modify the location of folders generated by the Module Creator, as it breaks all of the path dependencies. Did you move any of the folders?

**Comment by jaruiz-ual** [comment]
HI ShaunWhat I have just done ¡I have downloaded again the master Branch zip from the Oqtane.framework repository at GitHub.Then  the source code is unpacked, compiled, and executed  in Visual Studio 2022. The Oqtane software is installed with the default options.Using the module creator utility in the Developed page a new Module is created.When I open the solution file of the new module in Visual Studio I get these errors.The following assembly files, Oqtane.Client, Oqtane.Chared, Oqtane.Server are not found. Hope it help ..     Enviado desde Correo para Windows De: Shaun WalkerEnviado: miércoles, 13 de julio de 2022 21:22Para: oqtane/oqtane.frameworkCC: jaruiz-ual; AuthorAsunto: Re: [oqtane/oqtane.framework] compiling error: missing Oqtane.Client, Oqtane.Server and Oqtane.Shared when a new module is created (Issue #2282) This usually happens when you modify the location of folders generated by the Module Creator, as it breaks all of the path dependencies. Did you move any of the folders?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jaruiz-ual** [comment]
Hi There!,When moduleDefinition.Version == “local”  it seems that should exists a path “Oqtane.framework” with the files …. (¿?) It happends when the ListBox framework reference in the Module Creator  is  selected to “Installed Version”    I think, it should be necessary a warning  after cheking that those files are not there… Enviado desde Correo para Windows De: Shaun WalkerEnviado: miércoles, 13 de julio de 2022 21:22Para: oqtane/oqtane.frameworkCC: jaruiz-ual; AuthorAsunto: Re: [oqtane/oqtane.framework] compiling error: missing Oqtane.Client, Oqtane.Server and Oqtane.Shared when a new module is created (Issue #2282) This usually happens when you modify the location of folders generated by the Module Creator, as it breaks all of the path dependencies. Did you move any of the folders?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sbwalker** [comment]
You are correct... the module creator expects that the Oqtane Framework exists in a folder named "oqtane.framework" (the default folder name that would be used if you cloned the repo from Github)

**Comment by jaruiz-ual** [comment]
Hi there!I downloaded the zip file from the master branch.So the default name when unpacking is oqtane.framework-master ..!! If you also use the Installed Version option in the Framework Reference  when create a module then here is the problem ..!!If the initial path where Oqtune framework is installed is a requirement  in the installation process (for example) an adviser could be a help in order to avoid all this.Thankyou very much for your reply.Best regards  Enviado desde Correo para Windows De: Shaun WalkerEnviado: viernes, 15 de julio de 2022 17:52Para: oqtane/oqtane.frameworkCC: jaruiz-ual; AuthorAsunto: Re: [oqtane/oqtane.framework] compiling error: missing Oqtane.Client, Oqtane.Server and Oqtane.Shared when a new module is created (Issue #2282) You are correct... the module creator expects that the Oqtane Framework exists in a folder named "oqtane.framework" (the default folder name that would be used if you cloned the repo from Github)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sbwalker** [comment]
Apologies... there used to be a requirement for the framework to be installed in the "oqtane.framework" folder - however this was modified at some point to determine the location dynamically - so the behavior you were experiencing with project references was actually a bug.
