### ISSUE TITLE
Null reference exception when a module is deleted (Module Creator)

### ISSUE THREAD

**Issue by jaruiz-ual** [oqtane/oqtane.framework#2285]
![image](https://user-images.githubusercontent.com/62284884/178942486-c8142d69-a424-416e-b654-50ca2bfc17ec.png)

![image](https://user-images.githubusercontent.com/62284884/178943343-378084f6-aff2-4a27-b39c-f56c4e2cc2c3.png)

**Comment by leigh-pointer** [comment]
@jaruiz-ual try adding a null test `?` ::

`_permissionNames = ModuleState.ModuleDefinition?.PermissionNames;`

**Comment by sbwalker** [comment]
Please provide exact steps to reproduce the problem described above.

**Comment by jaruiz-ual** [comment]
Hi! Shaun I’m trying to reproduce the problem but  i can not do it.I do not remember what I did exactly because I was trying to install/uninstall DEMO31 module in several pages, in several ways… because  I could not do it. But it seems, it happens in some circumstances.I´ll keep trying.Best regards.   Enviado desde Correo para Windows De: Shaun WalkerEnviado: jueves, 14 de julio de 2022 14:55Para: oqtane/oqtane.frameworkCC: jaruiz-ual; MentionAsunto: Re: [oqtane/oqtane.framework] Null reference exception when a module is deleted (Module Creator) (Issue #2285) Please provide exact steps to reproduce the problem described above.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
