### ISSUE TITLE
Module management is not working as expected

### ISSUE THREAD

**Issue by jaruiz-ual** [oqtane/oqtane.framework#2286]
Sometimes a new module is installed but it is not shown in the Module Management list. 
Then it is installed again, and again  ..and then could appears several times. 
when one of these is deleted (clicking the delete button) nothing happens and the module is still there.
only when on every delete button is clicked it seems that all those modules are erased from the Module management list.

**Comment by sbwalker** [comment]
Please provide specific steps to reproduce the problem.
