### ISSUE TITLE
CREATE DATABASE permission denied in database 'master'

### ISSUE THREAD

**Issue by vmasanas** [oqtane/oqtane.framework#2309]
I'm trying to install latest version on SQLServer but I kept getting the error about permissions not being ok.
On my (local) sql I have created the database oqtane313, give the app pool permissions on the DB.
On the install page I selected
Database: SQLSERVER
Server: (local)
Database: oqtane313
Security: integrated

Doesn't matter if the database exists or not, always get the same error. 
Any suggestions?

**Comment by sbwalker** [comment]
The instructions for installing Oqtane on IIS are here:

https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis

Step 6 is focused on how to configure the App Pool. It mentions setting the Identity to "LocalSystem". Have you done this?

I know that @ADefWebserver uses a local SQL Server with Oqtane - maybe he has some tips. I generally use LocalDB or SQLite for local development.

**Comment by ADefWebserver** [comment]
I don't have any more tutorials that use local SQL Server with Oqtane. However, it should work if you connect to the database using username and password. See: https://blazorhelpwebsite.com/ViewBlogPost/1

**Comment by sbwalker** [comment]
@vmasanas were you able to resolve this issue?

**Comment by sbwalker** [comment]
No further feedback.... closing
