### ISSUE TITLE
Missing "wwwroot", can not display error.png

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#2336]
When loading an image, if the image does not exist, "error.png" image will be returned. Currently the path to the file "error.png" is missing "wwwroot" so there is an error.

Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.IActionResult'. Change to **return  new EmptyResult()**

**Comment by sbwalker** [comment]
Thank you for reporting this issue. After investigation this is a bit more complicated than it appears on the surface and will require a bit more investigation.

**Comment by leigh-pointer** [comment]
@sbwalker I had a quick look and help.png and error.png are constructed differently.  The quick solutions would be to follow the same method as help.png 

`<img src="images/help.png" />`

**Comment by sbwalker** [comment]
The error.png is relying on a private GetFolder() method - which was working properly at one point, but not any longer. This GetFolder() method is called in multiple places so I would like to determine the root cause before making any changes.
