### ISSUE TITLE
HtmlText module: Image should be inserted with relative path

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#234]
In case of server name change all images will be inaccessible.
![image](https://user-images.githubusercontent.com/7838468/75359707-0be36c00-58b5-11ea-914d-b7054ae867b8.png)

**Comment by sbwalker** [comment]
This is a valid point but a solution has some complications. To access an image for a standard site the relative url is "/~/api/File/Download/3". That first url segment ("~" ) is part of the alias logic used to determine which site the image belongs to. For a micro-site the relative url is "/{alias}/api/File/Download/3" - where {alias} is the folder name. I suppose the solution could be to store a url of "/api/File/Download/3" in the content and then dynamically append the "/~" or "/{alias}" at runtime based on the current alias the site is running under?

**Comment by chlupac** [comment]
for beginning, taking off a host part will be enough. 
in case when admin need to prepare web on some temporary address and switch to final address when done.

**Comment by sbwalker** [comment]
The scenario I was referring to is when someone creates a site at www.site.com/newsite as a quick way to create a new site and populate it with content, and then later they purchase a domain name www.newsite.com and add the alias to the site. This was a very common scenario in the DNN world ( as it also supported micro-sites ). In this scenario, the references to images in the HTML content need to be able to be served under both aliases. The only way to accomplish this is if the urls are saved as /api/file/download/## and dynamically at run-time the HTML content is modified to include the appropriate prefix ( ie. either "/newsite" or "/~" ).

**Comment by sbwalker** [comment]
Fixed in #251
