### ISSUE TITLE
GetAliasAsync in AliasService return wrong url in some cases

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#235]
`http://klubovna.zitmebavi.local:44357/29/Edit?id=22`
is translated to alias name 

klubovna.zitmebavi.local:44357/29
instead of 
klubovna.zitmebavi.local:44357

**Comment by sbwalker** [comment]
This is an interesting issue. Note that Oqtane supports 2 types of aliases - root host values ( ie. site.com ) and virtual folders ( ie. site.com/folder ). The logic used for validating an alias is:

1. Check if the host value including the first path segment is defined as an Alias in the database - so in your case it should first try to validate "klubovna.zitmebavi.local:44357/29" 
2. If #1 is not valid then validate just the host value as an Alias in the database  - in your case this is "klubovna.zitmebavi.local:44357"

So are you saying that in your Alias database table the value "klubovna.zitmebavi.local:44357/29" does not exist?

**Comment by sbwalker** [comment]
Sorry, I don't understand your comment. You said you have:

2 aliases and 2 sites, 1 tenant configured
Alias1 = "localhost:44375"
Alias2 = "klubovna.zitmebavi.local:44357"

are you saying that you cannot browse to Alias2?

**Comment by chlupac** [comment]
Yes, i can , but in some case in edit site strangely internally switches to default alias.

**Comment by chlupac** [comment]
problem is here, function wrong parses http://klubovna.zitmebavi.local:44357/29/Edit?id=22 
        public Alias Get(string name)
        {
            name = WebUtility.UrlDecode(name);
            List<Alias> aliases = Aliases.GetAliases().ToList();
            Alias alias = null;
            alias = aliases.Where(item => item.Name == name).FirstOrDefault();
            if (alias == null && name.Contains("/"))
            {
                // lookup alias without folder name
                alias = aliases.Where(item => item.Name == name.Substring(name.IndexOf("/") + 1)).FirstOrDefault();
            }
            if (alias == null && aliases.Count > 0)
            {
                // use first alias if name does not exist
                alias = aliases.FirstOrDefault();
            }
            return alias; 
        }

**Comment by sbwalker** [comment]
you are using the latest version correct - with a clean database install? As part of fixing the Site Add issue I had to modify the way that Site Edit/Delete work.

**Comment by chlupac** [comment]
yes, yes

**Comment by chlupac** [comment]
I'm torturing this version now

**Comment by sbwalker** [comment]
What is the actual value for of the parameter "name" which is passed to the Get() method in the controller?

**Comment by chlupac** [comment]
actual problem is in service on client
        public async Task<Alias> GetAliasAsync(string Url)
        {
            Uri uri = new Uri(Url);
            string name = uri.Authority;
            if (uri.Segments.Count() > 1)
            {
                name += "/" + uri.Segments[1];
            }
            if (name.EndsWith("/")) 
            { 
                name = name.Substring(0, name.Length - 1); 
            }
            return await http.GetJsonAsync<Alias>(apiurl + "/name/" + WebUtility.UrlEncode(name));
        }

and uri was http://klubovna.zitmebavi.local:44357/29/Edit?id=22

**Comment by chlupac** [comment]
i'm trying to reproduce error now

**Comment by sbwalker** [comment]
I think the bug is in the AliasController Get() method:

                // lookup alias without folder name
                alias = aliases.Where(item => item.Name == name.Substring(name.IndexOf("/") + 1)).FirstOrDefault();

should be:

                // lookup alias without folder name
                alias = aliases.Find(item => item.Name == name.Substring(0, name.IndexOf("/")));

**Comment by sbwalker** [comment]
Unrelated question... in order configure "klubovna.zitmebavi.local" I assume you added it to your hosts file ( pointing to 127.0.0.1 ) but did you need to do anything else in order to utilize it when debugging in Visual Studio?

**Comment by chlupac** [comment]
you have to debug oqtane.server.exe, not under iis express

**Comment by chlupac** [comment]
but i'm using rider as development tool

**Comment by sbwalker** [comment]
Awesome! That aligns perfectly with the philosophy ( https://www.oqtane.org/Resources/Blog/PostId/538/oqtane-philosophy ):

Tooling Agnostic

Although Visual Studio provides a powerful set of functionality for software development, it can sometimes be overkill for solving specific problems and is not always available or accessible to all software developers. As a result Oqtane should not rely upon or take advantage of any specific features in Visual Studio. It should be possible for developers to be productive on Oqtane using other development tools such as VS Code, JetBrains Rider, etc...

**Comment by chlupac** [comment]
![image](https://user-images.githubusercontent.com/7838468/75466889-2a1b9b80-598b-11ea-8f39-45972e0ca792.png)
i have it
reproduction is simple
fresh install
create site with another defautt theme
after creation, click edit page at control panel
theme changed and u are in alias 1 but in address line is alias 2

**Comment by sbwalker** [comment]
that code looks like it is behaving correctly as it does need to include the first path segment to the server. The problem is when when the server interprets in the Get() method.

**Comment by chlupac** [comment]
I'm able to do it visual studio too, it's not rider related
![image](https://user-images.githubusercontent.com/7838468/75467389-d9f10900-598b-11ea-8b42-28aeadb9b180.png)
u have to set launch project, not iis

**Comment by sbwalker** [comment]
This code which says it is doing a lookup of the alias without the folder name is clearly wrong - as it is actually removing the host name from rather than the folder name :(

            // lookup alias without folder name
            alias = aliases.Where(item => item.Name == name.Substring(name.IndexOf("/") + 1)).FirstOrDefault();

The code should be:

            // lookup alias without folder name
            alias = aliases.Find(item => item.Name == name.Substring(0, name.IndexOf("/")));

**Comment by chlupac** [comment]
great.

**Comment by sbwalker** [comment]
are you able to test the code change above?

**Comment by chlupac** [comment]
yes, it's in controller ?? can we use skype ?

**Comment by chlupac** [comment]
It looks correct

**Comment by chlupac** [comment]
![image](https://user-images.githubusercontent.com/7838468/75469512-6d780900-598f-11ea-9ac3-97633ff81827.png)

**Comment by sbwalker** [comment]
sorry i dont have skype on this system. can you submit this as a PR?

**Comment by chlupac** [comment]
done.

**Comment by sbwalker** [comment]
I believe this item is resolved

**Comment by chlupac** [comment]
yes, it is
