### ISSUE TITLE
Installation crash when connection string in appsetting.json is not empty

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#236]
reproduction:
install oqtane on sql server into specific database
drop oqtane tables
install again to same database with appsettings.json untouched

Idea: distinguish between installation versions (master, site) by the existence of the Alias table and the number of records in it (via AliasController) not by presence of connection string.

**Comment by sbwalker** [comment]
I like this idea

**Comment by hishamco** [comment]
Regarding this one, if we have a notion of table prefix, like some CMSs including DNN, this will be fine, unless the user choose the same prefix, then we can check the `Alias` or `Users` tables

I can start a PR for this one

**Comment by sbwalker** [comment]
Oqtane does not plan to use the {ObjectQualifier} or {DatabaseOwner} concept which existed in DNN.

**Comment by hishamco** [comment]
No problem, but this is very useful in case you wanna create multi tenant with the same database

**Comment by chlupac** [comment]
Solved with #306
