### ISSUE TITLE
Siterouter fail when Module has no definition

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#237]
I have class library with my custom modules. I realized than one of them is wrong and delete it.

in this case module lost his ModuleDefinition, but still has placement on one of pages
Api call  http://localhost:44357/~/api/Module?siteid=1
returns All modules for site, one of them with ModuleDefinition == null

`        private List<Module> ProcessModules(List<Module> modules, int pageid, int moduleid, string control,
            string panes, string defaultcontainertype)
        {
            Dictionary<string, int> paneindex = new Dictionary<string, int>();
            foreach (Module module in modules)
            {
                string typename = module.ModuleDefinition.ControlTypeTemplate;
 `
module.ModuleDefinition is  null here

IMHO create something like EmptyModule (only frame a title) and if ModuleDefinition is null use EmptyModule and log warning of nonexisting module.

**Comment by sbwalker** [comment]
Currently during startup the system compares the list of modules in the /bin with the list of ModuleDefinitions in the database, and if it finds an orphan it deletes the ModuleDefinition. It should probably delete any Modules which are associated to the ModuleDefinition as well as they are no longer valid.

**Comment by chlupac** [comment]
In this case must be deleted from pages. Better solution is put here a dummy module with error message, which can be deleted by admin or repaired by admin with new installation of invalid module.

**Comment by sbwalker** [comment]
@chlupac I agree with your suggestion and it is in fact the only way to deal with this issue, as ModuleDefinitions are in the Master database and Modules may be in separate Content databases. This is resolved with PR #251

**Comment by chlupac** [comment]
Great. I will test this update tomorrow.
