### ISSUE TITLE
Bug: Modules placed in panes which don't exist on a specific Theme are lost if theme doesn't have an "Admin" pane

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2386]
This is related to #2382 

## Updated Issue

If a user adds content to various panes with different names, and then switches to a theme without these names, the modules are shown in the `Admin` pane like this:

![image](https://user-images.githubusercontent.com/5321186/187496682-a8dde8e3-6207-4a32-be38-c010cf782bce.png)

But if there is no `Admin` pane in the theme (in my example, I didn't want one because it was confusing the users) this fails - the module is gone:

![image](https://user-images.githubusercontent.com/5321186/187496771-93b90fdc-4985-40dd-ae71-bc8e91cde584.png)

Of course the question is if `Admin` is a good pane name, but that's handled in #2382.

So my suggestion is that the mechanism continues to try to put modules in the default pane (I guess ATM `Admin`, I would prefer `Default`) but if it cannot find this, put it in the first pane found instead. 

## Previous Issue Description (left for completeness)

Let's say a user starts adding modules to a page with a theme that has many panes, for e.g.

* Admin,  Header, Footer, Right33, Middle33, Left33, ...

After a while he switches layouts to another theme which only has 

* `Default` and `Admin`. 

The modules he added to the other panes are now gone and he will never see them again. He will probably not even notice this for a very long time. To fix it, he/she would have to modify the data in the DB or find a theme with panes containing both the old and new names, move the modules, and then finalize his move. 

The problem is that if a module is registered for a pane which isn't available on the theme, these modules will just disappear. So people could switch themes and the lose modules which the system thinks are fully operational, but will never be seen again. They will be loaded, but never rendered. 

This can lead to real problems. To fix that, the logic should probably be:

1. Find all modules on the page which don't have a pane to show up in
2. Determine if there is a default pane `Default` (or maybe `Admin`) to put it into, and add it to that list
3. If no such pane can be found - let's say a beginner made a theme with only a `Dashboard` pane, it would ideally revert to the first pane in the theme and put them there.

**Comment by leigh-pointer** [comment]
> The modules he added to the other panes are now gone and he will never see them again. 
I am pretty sure it will default to Admin, just like DNN did with Content pane.

**Comment by iJungleboy** [comment]
@leigh-pointer 

You are actually right - I repeated some tests and can verify that it actually defaults to the `Admin` pane if the pane name isn't found. 

I guess the missing piece is that if there is no `Admin` pane (which I had not provided in some test-skins because it confused the editor), there is no fallback. 

So I guess the real issue isn't that anything is lost, things are only lost if there is no pane with the (IMHO fairly technical name) `Admin`. 

I'll update the description in the issue above.

**Comment by sbwalker** [comment]
As mentioned in #2382 there is 1 REQUIRED pane in every theme and it MUST be named "Admin". In the case that no Admin pane is provided I suppose the framework could display an error message on the page to alert the user of the problem (ie. to clarify why their modules are not being displayed).

**Comment by sbwalker** [comment]
Sorry... you included a lot of extra information in your initial post, so I missed your suggestion " if it cannot find the default pane, put it in the first pane found instead". There are a few things to keep in mind. A theme needs to contain both references to Pane components in the theme markup:

```
<Pane Name="@PaneNames.Admin" />
```

as well as override the Panes property in ThemeBase:

```
    public override string Panes => PaneNames.Admin + ",Top Full Width,Top 100%,Left 50%,Right 50%,Left 33%,Center 33%,Right 33%,Left Outer 25%,Left Inner 25%,Right Inner 25%,Right Outer 25%,Left 25%,Center 50%,Right 25%,Left Sidebar 66%,Right Sidebar 33%,Left Sidebar 33%,Right Sidebar 66%,Bottom 100%,Bottom Full Width,Footer";
```

So its possible that a designer may have forgotten to include the default "Admin" pane in their theme markup... or forgotten to override the Panes property value. The way that the fallback logic works is it validates the PageModule.Pane value against the Panes property value that was declared for the Theme. If the value does not exist it currently falls back to using PaneNames.Admin. However it should probably validate if PaneNames.Admin actually exists in the Panes property, and if it does not, then it could use the first pane defined in the Panes property (as you suggested). The only remaining problem is if a designer forgot to override the Panes property and its value is null. In this case I believe it should add PaneNames.Admin to the list automatically - as it is a required pane in every theme.

**Comment by iJungleboy** [comment]
@sbwalker I agree with your suggestion. 

I also think that force-adding `Admin` if null isn't ideal. I believe the newbie-developer would quickly discover during work that there is no pane suggested in add-module. I could even imagine that auto-adding `Admin` could lead to new issues where people get lazy and rely on this _feature_ which would cause new issues down the road. 

So IMHO a clear error-there-are-no-panes-defined would be better suited to ensure that we don't run into other problems down the road.
