### ISSUE TITLE
Unhandled exception when i'm trying to get non existing folder

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#239]
GET http://localhost:44357/~/api/Folder/0

Generally in code is lot of places where is missing nullcheck. And you cannot expect than url is well formed all times.

**Comment by mikecasas** [comment]
I get the same error.

**Comment by sbwalker** [comment]
Under what use case in the application is it requesting a non-existent folder? ( this would be a bug ). Or are you simply hitting the API directly and passing a non-existent folder id?

**Comment by chlupac** [comment]
This is fixed with #240
