### ISSUE TITLE
Bug: Errors when creating a new page with the same path as a deleted one

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#2399]
I've found some weird behaviours occurring when creating a new page that has the same path as a page that was deleted before. I'll leave some steps to get it.

Steps to reproduce:

1. Create a new page with path X.
2. Add an HtmlText module with some random text
3. Delete created page
4. Create new page with different name (same probably works too), but the same path X.
5. Enter the new created page, and the errors I've found are the following:

- You'll see that the HtmlText module appears, even though this page should be brand new. 
- The title/name for the page is the one associated with the deleted page. 
- If you try accesing the page by typing the full Url (localhost/X), you'll get a 404 Not Found, even though you can access it by entering through the Navigation Bar on the top (the button on the TopBar does display the correct name).
- If you are in the page and refresh (hitting F5), you also get a 404 Not Found. Basically you can only enter the page by using the NavLink in the TopBar.

Just by intuition, I believe that, when entering the page via the NavLink, it does indeed find that the path exists (because of the new page), but when iterating through existing pages, it might be returning the deleted one. On the other hand, when using the Url, it might be just finding first the deleted page, and directly returning the 404, instead of checking if some new page with that path exists.

Here I leave the database records for both pages:

<HTML>
<BODY>

<TABLE>
<TR><TD>PageId</TD><TD>SiteId</TD><TD>Path</TD><TD>Name</TD><TD>Title</TD><TD>ThemeType</TD><TD>Icon</TD><TD>ParentId</TD><TD>Order</TD><TD>IsNavigation</TD><TD>Url</TD><TD>UserId</TD><TD>IsPersonalizable</TD><TD>DefaultContainer</TD><TD>CreatedBy</TD><TD>CreatedOn</TD><TD>ModifiedBy</TD><TD>ModifiedOn</TD><TD>DeletedBy</TD><TD>DeletedOn</TD><TD>IsDeleted</TD><TD>IsClickable</TD><TD>Meta</TD></TR>

<TR><TD>39</TD><TD>1</TD><TD>test-page</TD><TD>Testing1</TD><TD>NULL</TD><TD>VisionSense.BlazoriseTheme.Default, VisionSense.BlazoriseTheme.Client.Oqtane</TD><TD></TD><TD>NULL</TD><TD>37</TD><TD>True</TD><TD>NULL</TD><TD>NULL</TD><TD>False</TD><TD></TD><TD>admin</TD><TD>04/09/2022 16:46:57</TD><TD>admin</TD><TD>04/09/2022 16:47:47</TD><TD>admin</TD><TD>04/09/2022 16:47:47</TD><TD>True</TD><TD>True</TD><TD>NULL</TD></TR>

<TR><TD>40</TD><TD>1</TD><TD>test-page</TD><TD>TestPage2</TD><TD>NULL</TD><TD></TD><TD></TD><TD>NULL</TD><TD>39</TD><TD>True</TD><TD>NULL</TD><TD>NULL</TD><TD>False</TD><TD></TD><TD>admin</TD><TD>04/09/2022 16:48:40</TD><TD>admin</TD><TD>04/09/2022 16:48:40</TD><TD>NULL</TD><TD>NULL</TD><TD>False</TD><TD>True</TD><TD>NULL</TD></TR>
</TABLE>

</BODY>
</HTML>

The Html module is indeed associated with PageId 39, not 40.

**Comment by sbwalker** [comment]
Are the pages and modules you deleted still in the Recycle Bin (in the Admin Dashboard)?

**Comment by sbwalker** [comment]
I am fairly sure this is a regression issue. The site router populates the PageState.Pages collection with pages which are not deleted (to avoid a lot of filtering logic in the majority of places where it is consumed). I have a feeling that the collection used to include deleted pages as well  - which was what the validation logic in Add Page was relying on. This is an easy to fix in the Add Page component but it raises a bit of a dilemma as I am not sure if there is other logic relying on deleted pages being included in that PageState collection. More investigation is required.

**Comment by mdmontesinos** [comment]
Were you able to reproduce the issue yourself?

I also saw you wrote before that I should check the Recycle Bin. I did, and upon entering the recyclebin page, I got an error, and this is the log obtained:

```console
System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Modules.Admin.RecycleBin.Index.<>c__DisplayClass0_1.<BuildRenderTree>b__12(RenderTreeBuilder __builder4) in MyLocalPath\oqtane.framework\Oqtane.Client\Modules\Admin\RecycleBin\Index.razor:line 61
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Oqtane.Modules.Controls.Pager`1.BuildRenderTree(RenderTreeBuilder __builder) in MyLocalPath\oqtane.framework\Oqtane.Client\Modules\Controls\Pager.razor:line 66
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

Basically, it's this line:
```html
<td>@PageState.Pages.Find(item => item.PageId == context.PageId).Name</td>
```

So yeah, there's an error somewhere with deleted pages. Thankfully, it's not so critical, take your time to investigate further.
