### ISSUE TITLE
Oqtane should work with SqlLite and ProgreSQL

### ISSUE THREAD

**Issue by cnurse** [oqtane/oqtane.framework#24]
One of the major advantages of .NET Core is that it is cross-platform.  We need to ensure that we support databases that are more commonly used on Linux and Mac, and avoid a specific dependency on SQL Server (even though it is now available on Linux)

**Comment by sbwalker** [comment]
Agreed. Migrating the current solution to use SQLite must be a priority. All data access is currently done using EF Core so this should not be an issue. The main effort will be refactoring the install wizard so that the database schema and seed data is provisioned without using scripts ( DBUp )
