### ISSUE TITLE
site created with invalid url, cannot be deleted

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#241]
I made typo in alias url, site cannot be deleted, edited

![image](https://user-images.githubusercontent.com/7838468/75561712-c5724680-5a47-11ea-888c-f293e76d2a3e.png)

**Comment by sbwalker** [comment]
True... because the Edit and Delete buttons currently need to construct a URL based on the alias value - and the alias value is invalid. I am fairly sure I know a way to resolve this.

**Comment by chlupac** [comment]
Resolved partially by my fix #244, aliases checked in moment of creation

**Comment by sbwalker** [comment]
#249 fixes this in a different manner than what was suggested in #244. Please test to determine if the solution meets your needs.
