### ISSUE TITLE
How to route to custom component of my module

### ISSUE THREAD

**Issue by mithang** [oqtane/oqtane.framework#2411]
<img width="1270" alt="Screen Shot 2022-09-10 at 18 46 56" src="https://user-images.githubusercontent.com/20384021/189481902-310489c5-c9c8-472a-93c3-0985d7938e9c.png">

Can you help me with how to route to a custom component of my module in the above picture?

Thanks

**Comment by sbwalker** [comment]
By convention the Action parameter should match the name of the razor component you want to load ie. if the razor component is called Edit.razor then the Action parameter would be "Edit".

**Comment by mithang** [comment]
Thanks reply!
But no work, component is empty!

<img width="1279" alt="Screen Shot 2022-09-11 at 22 01 00" src="https://user-images.githubusercontent.com/20384021/189534665-07718421-1aa2-43
<img width="1279" alt="Screen Shot 2022-09-11 at 21 58 59" src="https://user-images.githubusercontent.com/20384021/189534668-6447518f-8f79-43b9-8573-56fe6b04d536.png">
f9-9146-6bf70549ae6b.png">

please help me!

**Comment by sbwalker** [comment]
This would usually indicate there is an error in your component which is preventing it from rendering properly

**Comment by mithang** [comment]
My custom component is not includes:
- @namespace LMSoftware.Controls
- @inherits ModuleBase
Thanks, it is work
