### ISSUE TITLE
Notification module

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#243]
Should the notification module be part of the Admin dashboard?  I wanted to set email settings so users can login and and be sent an email to verify their address, but I couldn't find where to set the SMTP values.

I see in the NotificationJob.cs file there is a line looking for site settings, but I am not sure where to add those settings.

**Comment by chlupac** [comment]
On SiteSettings

**Comment by sbwalker** [comment]
You need to go to Site Settings and scroll to the bottom and expand the SMTP Settings section, enter your details and Save. In addition you will need to go to Scheduled Jobs and Enable the Notififications Job.

**Comment by mikecasas** [comment]
Sorry for the dumb question, but where do I go for the site settings? Is it on the admin menu? I see where I would go to enable the Notification Job, but just not the settings. Below is my admin screen.


![settings](https://user-images.githubusercontent.com/11261164/75639418-a79b1200-5bfe-11ea-8e65-c92c83e8ba40.PNG)

**Comment by sbwalker** [comment]
In a recent revision a Site Settings page was added to the database. You could fix this by removing the connection string value and reinstalling the database. Or you could manually add a Site Settings page and add the "Site" module to the page ( in the Admin modules category ).

**Comment by mikecasas** [comment]
Perfect thanks!
