### ISSUE TITLE
RFC: Switch from Newtonsoft to System.Text.Json

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2435]
## Background

Oqtane includes Newtonsoft by default - AFAIK it's also the subsystem responsible for json serialization for WebAPI calls etc. 

It's had a security issue recently https://security.snyk.io/vuln/SNYK-DOTNET-NEWTONSOFTJSON-2774678

Of course it's easy to update, but it does open the question if we shouldn't move to `System.Text.Json` instead. AFAIK it's mature and handles just about everything. 

This move is a bit complex though, because third party components such as [2sxc](https://2sxc.org) also configure their routes and possibly have custom Newtonsoft settings. For example, 2sxc has such settings. 

## Question

Should we move? I believe moving now would still be easier than in a year or so.

When would wo do this? Because there must be a transition time or it must happen on Oqtane 4.

**Comment by leigh-pointer** [comment]
@iJungleboy where is this referenced?  I have not seen it referenced anywhere in Oqtane.

**Comment by sbwalker** [comment]
Oqtane already uses System.Text.Json for the majority of its JSON serialization (ie. it uses it for WebAPI calls, etc...). I believe there is a single server-side use case where System.Text.Json did not contain a specific feature so NewtonSoft was used instead. One of Oqtane's philosophies is to minimize third party dependencies, so I would be in favor of removing NewtonSoft.

**Comment by sbwalker** [comment]
After further research, System.Text.Json does not support deserialization of JSON to a dynamic object (and Microsoft has indicated they are not planning on adding support for this in the future). This means there is no equivalent translation for the following code:

```
dynamic obj = JsonConvert.DeserializeObject<dynamic>(jsonString);
```

So Oqtane may need to retain this dependency.

**Comment by leigh-pointer** [comment]
@sbwalker I have done some work with json and dynamic.  I will have a look.  I think I know where in code, connectionstrings ?

**Comment by sbwalker** [comment]
Just search for "JsonConvert.Deserialize" in the source code. It is used as part of the ConfigManager which allows config settings to be written to appsettings.json. And it is used in DatabaseManager to add the Databases collection to appsettings.json.

**Comment by leigh-pointer** [comment]
@sbwalker this works and is dynamic using system.text.json

```
        private void ValidateConfiguration()
        {
            if (_configManager.GetSetting(SettingKeys.DatabaseSection, SettingKeys.DatabaseTypeKey, "") == "")
            {
                _configManager.AddOrUpdateSetting($"{SettingKeys.DatabaseSection}:{SettingKeys.DatabaseTypeKey}", Constants.DefaultDBType, true);
            }
            if (!_configManager.GetSection(SettingKeys.AvailableDatabasesSection).Exists())
            {
                string databases = "[";
                databases += "{ \"Name\": \"LocalDB\", \"ControlType\": \"Oqtane.Installer.Controls.LocalDBConfig, Oqtane.Client\", \"DBTYpe\": \"Oqtane.Database.SqlServer.SqlServerDatabase, Oqtane.Database.SqlServer\" },";
                databases += "{ \"Name\": \"SQL Server\", \"ControlType\": \"Oqtane.Installer.Controls.SqlServerConfig, Oqtane.Client\", \"DBTYpe\": \"Oqtane.Database.SqlServer.SqlServerDatabase, Oqtane.Database.SqlServer\" },";
                databases += "{ \"Name\": \"SQLite\", \"ControlType\": \"Oqtane.Installer.Controls.SqliteConfig, Oqtane.Client\", \"DBTYpe\": \"Oqtane.Database.Sqlite.SqliteDatabase, Oqtane.Database.Sqlite\" },";
                databases += "{ \"Name\": \"MySQL\", \"ControlType\": \"Oqtane.Installer.Controls.MySQLConfig, Oqtane.Client\", \"DBTYpe\": \"Oqtane.Database.MySQL.SqlServerDatabase, Oqtane.Database.MySQL\" },";
                databases += "{ \"Name\": \"PostgreSQL\", \"ControlType\": \"Oqtane.Installer.Controls.PostgreSQLConfig, Oqtane.Client\", \"DBTYpe\": \"Oqtane.Database.PostgreSQL.PostgreSQLDatabase, Oqtane.Database.PostgreSQL\" }";
                databases += "]";

                //_configManager.AddOrUpdateSetting(SettingKeys.AvailableDatabasesSection, JsonConvert.DeserializeObject<dynamic>(databases), true);
                JsonNode jsonDatabases = JsonNode.Parse(databases);
                _configManager.AddOrUpdateSetting(SettingKeys.AvailableDatabasesSection, jsonDatabases.ToJsonString(), true);
            }
        }
```

**Comment by sbwalker** [comment]
@leigh-pointer this looks good... do you have any thoughts on this method:

```
        public void AddOrUpdateSetting<T>(string file, string key, T value, bool reload)
        {
            try
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), file);
                dynamic jsonObj = JsonConvert.DeserializeObject(File.ReadAllText(path));
                SetValueRecursively(key, jsonObj, value, "set");
                File.WriteAllText(path, JsonConvert.SerializeObject(jsonObj, Formatting.Indented));
                if (reload) Reload();
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Oqtane Error: Error Updating App Setting {key} - {ex}");
            }
        }
```

This method is used in many places to manage appsettings.json. The important part is the SetValueRecursively method which uses the dynamic object internally to add.modify/delete nodes.

**Comment by leigh-pointer** [comment]
@sbwalker looking at this now.  From first glance look achievable , will also need to look at this function to `SetValueRecursively`

**Comment by sbwalker** [comment]
@leigh-pointer the recursive function proved to be a lot more challenging than I expected - mostly because the documentation and examples related to the more advanced functionality of System.Text.Json introduced in .NET 6 is sparse. I managed to get it all working and also made the logic more robust in the process.

**Comment by leigh-pointer** [comment]
@Shaun ***@***.***> the recursive function was really challenging but good that you cracked it and now a third party dependency is romoved from the solution.
________________________________
