### ISSUE TITLE
Flash of Ugly on every Reload - and Solution

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2439]
At the moment all Oqtane sites load in a bad way where it's ugly for just one second.

For example, the oqtane.org site looks good, then bad, then good again. When it looks bad, it looks like this for a brief moment: 

---
![image](https://user-images.githubusercontent.com/5321186/192585234-f64e6cf0-378e-4054-851d-f6a0c508551c.png)
---
Please watch this video to see it in action:

https://www.screencast.com/t/nQUPluRq

The reason seems to be a combination of two problems:

1. Difference in link-tag handling on server and browser related to the `type` attribute
2. Difference in URL handling on server and browser

## Fixing the Link-Tag Handling

The server doesn't add a type="text/css" to the tag. Because of this, the introp-JS feels that the tag hasn't been added yet, and replaces the tag in the browser. Changing the `_Hosts.cshtml` on line 458 to this fixes this part of the problem:

```c#
HeadResources += "<link " + id + "rel=\"stylesheet\" href=\"" + resource.Url + "\"" + CrossOrigin(resource.CrossOrigin) + Integrity(resource.Integrity)
 + " type=\"text/css\"" + " />" + Environment.NewLine;
```

Note the added `" type=\"text/css\"" +`. 

## Fixing the URL problem

Even after adding the fix above it flickers faster, but still not as expected. The problem is that if my resources have a path such as this:

```c#
public override List<Resource> Resources => new()
{
    new() { ResourceType = Stylesheet, Url = $"Themes/ToSic.Oqt.Themes.ToShineBs5/theme.min.css" },       // Bootstrap generated with Sass/Webpack
    new() { ResourceType = Script, Url = $"Themes/ToSic.Oqt.Themes.ToShineBs5/bootstrap.bundle.min.js" }, // Bootstrap JS
    new() { ResourceType = Script, Url = $"Themes/ToSic.Oqt.Themes.ToShineBs5/ambient.js", },             // Ambient JS for page Up-button etc.
};
```
_Note that I tried it with a leading `"/Themes/...` but that failed as well_

Here's what happens:

1. The server places the stylesheet `<link>` tags using a path like `href="Themes/...`
2. The interop JS then checks to see if it should change this, but it compares the `href` with `/Themes/` and not with `Themes/`
3. Because of the additional `/` in the interop-js, it assumes the tag is missing, and creates a new one
4. This forces the browser to flush/reload the CSS, resulting in that nasty flash

Here's a dummy workaround to prove that resolving this fixes the flashing issue (apply to `interop.js`:

```js
    includeLink: function (id, rel, href, type, integrity, crossorigin, insertbefore) {
        var link = document.querySelector("link[href=\"" + CSS.escape(href) + "\"]");
        // Temporary workaround to ensure it also realizes the CSS is there without the leading slash
        if (href.startsWith('/')) {
            var href2 = href.substring(1);
            link = document.querySelector("link[href=\"" + CSS.escape(href2) + "\"]");
        }
        if (link === null) {
```

As soon as this is added, the ugly-flicker is gone 🚀.

## From Proof to Solution

This was just some ugly patching to find the cause and prove the solution. I assume the final solution will be a bit different, because it's probably better to make sure the URL is handled the same way on JS/Server and not to monkey-patch it as I did in the example.

**Comment by sbwalker** [comment]
Thank you for reporting this issue. This is actually a result of a recent change which was made to support MAUI and it affects https://www.oqtane.org because the site is running a dogfood build from the dev branch (ie. newer than the official 3.2.0 release). The behaviors of the ModulePath and ThemePath properties were changed to use rooted paths (which are prefixed with a "base url" to make them absolute when running on MAUI). Obvously this caused problems with the JS Interop method - thank you for the diagnosis.

As a side note the recommended way to reference Resource Urls is to use the ModulePath and ThemePath properties so that you don't need to hardcode the paths ie.

```
public override List<Resource> Resources => new()
{
    new() { ResourceType = Stylesheet, Url = ThemePath() + "theme.min.css" },       // Bootstrap generated with Sass/Webpack
    new() { ResourceType = Script, Url = ThemePath() + "bootstrap.bundle.min.js" }, // Bootstrap JS
    new() { ResourceType = Script, Url = ThemePath() + "ambient.js", },             // Ambient JS for page Up-button etc.
};
```

**Comment by iJungleboy** [comment]
@sbwalker  Thanks for the additional hint on ThemePath() - is there a way to get that inside a service?

**Comment by iJungleboy** [comment]
Another note: I tried `ThemePath()` but I don't like it ;)

Reason is that my Path then becomes a bit uglier.

* My preference: `Themes/ToSic.Oqt.Themes.ToShineBs5/...`
* ThemePath(): `Themes/ToSic.Oqt.Themes.ToShineBs5.Client/...`

**Comment by sbwalker** [comment]
ModulePath() and ThemePath() use the namespace of the associated razor component. The Module Creator and Theme Creator generate razor components which have a namespace of:

```
@namespace [Owner].[Theme]
```

As you can see ".Client" is not included, so the ModulePath() and ThemePath() do not include ".Client" either in the path they generate. Obviously you are free to specify your own namespace preference and path preference - but I just wanted to explain the "ugly" behavior is not standard - it is because of your own customizations.

**Comment by sbwalker** [comment]
ModulePath and ThemePath could easily be added to ServiceBase - I just have never encountered a need for them in a service yet.

**Comment by iJungleboy** [comment]
@sbwalker Example of use in a service:

I create a special service to do all the interop for me - basically so I don't have strings of javascript-commands littered across my code. So there is something like a `JsPageControlService` which needs to initially load the correct JS. For this it needs to know about the current theme (it's part of the theme package). 

Of course it could be a completely standalone library - in which case I guess the file would be in `./_content/` - but I haven't figured that quite out yet ;)

**Comment by sbwalker** [comment]
Ok, that makes sense. On a different note I am glad you reported the issue about the "flash" before it ended up in an official release. I upgraded https://www.oqtane.org to include the latest fix so hopefully that should resolve the problem.

**Comment by lanthonyneville** [comment]
I am still seeing the "flash" on https://www.oqtane.org/ - as in the OP, it initially looks good, then bad for a fraction of a second, then good again.

**Comment by sbwalker** [comment]
@lanthonyneville I set throttling in my browser to slow the loading of resources and I am now unable to reproduce the behavior in the original post. What browser are you using?

**Comment by lanthonyneville** [comment]
Chrome

**Comment by sbwalker** [comment]
@lanthonyneville it turns out the site was not running the latest bits - there was something wrong with the deployment yesterday. I just redeployed and ensured the latest bits are running on the site... and I can no longer reproduce in Edge or Firefox (I do not have Chrome installed).

**Comment by leigh-pointer** [comment]
@sbwalker perfect in chrome, edge, firefox no flicker!

**Comment by lanthonyneville** [comment]
Yes, no longer occurs on Chrome!
