### ISSUE TITLE
I am getting an error that wont stop replicating.  Oqtane 3.2.0

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2453]
The error is below 

```
Error Loading Logs Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.

Microsoft.AspNetCore.Components.NavigationException: Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.NavigateToCore(String uri, NavigationOptions options)
   at Microsoft.AspNetCore.Components.NavigationManager.NavigateToCore(String uri, Boolean forceLoad)
   at Oqtane.Modules.Admin.Logs.Index.OnParametersSetAsync() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Admin\Logs\Index.razor:line 142
```

The only way I have reduced the number of emails and records is to restart the app.  My Notification table has 421055 messages to the host. The emails still come in but reduced.

Looking at the line 142 there is not test done to see if the "token" key exists?

`user = await UserService.VerifyEmailAsync(user, PageState.QueryString["token"]);`

Also noticed that in the email the log id is incrementing but the log table is not.

Anyone else seeing this?

**Comment by sbwalker** [comment]
By default the framework will create a Notification for Errors that are logged in the Event Log (this feature can be disabled). You should check your Event Log for Errors. I do not believe the error message above is the main issue - as it would only be raised if an Administrator browsed to the Event Log page in your site - which is a fairly low frequency event. 400,000 errors is a very high frequency event - I am guessing you have a custom scheduled job which may be throwing errors?

**Comment by sbwalker** [comment]
#2430 resolved an issue where the link to the Event Log item was not being created correctly. This may explain the error you posted above - but not the 400,000 error notifications.

**Comment by leigh-pointer** [comment]
@sbwalker Not sure how but had an orphan record causing a scheduled job to fail.  Have removed record and logging is back to normal. Thanks for your time.
