### ISSUE TITLE
Errors if Files in DB are out of Sync with real files/folders

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2457]
My understanding of the Oqtane files/folders is that similar to DNN, it will have a DB record for each folder and file in the system. 

I believe that the DB (not the real server folder structure) is also the part used when showing things such as the dropdown here:

![image](https://user-images.githubusercontent.com/5321186/195776767-21ad7618-569c-43d0-bba7-585a5f24f871.png)

The problem we're having is similar to a common DNN problem: if a user makes any changes to the folders/files manually or through FTP, the DB is then out of sync with reality. 

In DNN there was a button to sync the system, but in Oqtane there is no such functionality. Is there a way to do this, or could you add such a functionality?

I'm aware of course that oqtane has some additional features such as private-folders, so of course such a sync should probably inherit the type of the folder above.

**Comment by iJungleboy** [comment]
fyi @tvatavuk

**Comment by sbwalker** [comment]
There is no synchronization feature in Oqtane.
