### ISSUE TITLE
Texts on dialog buttons

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#246]
Cancel here is little bit confusing for me in this situation. Cancel what?

![image](https://user-images.githubusercontent.com/7838468/75604129-f39e6780-5ad5-11ea-8134-317b0747a08d.png)

**Comment by sbwalker** [comment]
In all cases where a modal dialog is displayed, there is a primary action button as well as a cancel button. The cancel button is used to indicate that you are finished with the current activity. In this case the dialog is invoked from the File Manager by selecting the Upload Files button. So the cancel button is the users way of saying that they do not want to upload any more files and return to the File Manager. I think this is consistent with other uses of the cancel button in the app.

**Comment by chlupac** [comment]
[Close] will be better here. But it's only cosmetic.
