### ISSUE TITLE
Timeline for (probably) V4 on .net 7

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2494]
We're about to release a new major version of 2sxc, which is the right time for breaking changes. 

I also assume that Oqtane for .net 7 will come out any day now, and will probably be a breaking change.

Since we would like to sync our release to this, it would help to know when you plan to release this next breaking release...

**Comment by sbwalker** [comment]
Please see this thread for discussion on .NET 7: 

https://github.com/oqtane/oqtane.framework/discussions/2465

On a side note, I do not expect there will be any breaking changes when Oqtane moves to .NET 7.

**Comment by iJungleboy** [comment]
Ok. I already participated in #2465 
And hearing that we probably don't need to change the plugin is promising. So unless you think this should be discussed more, feel free to close this. thx!
