### ISSUE TITLE
Error on SiteRouter.razor

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2502]
This section in `private async Task Refresh()` has a bug:

```
		if (querystring.ContainsKey("reload") || (!NavigationManager.ToBaseRelativePath(_absoluteUri).ToLower().StartsWith(SiteState.Alias.Path.ToLower()) && !string.IsNullOrEmpty(SiteState.Alias.Path)))
		{
			if (querystring["reload"] == "post")
			{

```
Can result in

![image](https://user-images.githubusercontent.com/5321186/202421296-6e077aed-4d0a-4de3-ba7f-65ed9286ec98.png)

Problem is that the first if is ok, even if the querystring doesn't contain `reload` but then accesses it - which causes as error. 

I have trouble explaining exactly when this fires, but I think it's when a url has `?something` and then a link goes to `#`

Should probably become

```
		var hasReload = querystring.ContainsKey("reload");
		if (hasReload || (!NavigationManager.ToBaseRelativePath(_absoluteUri).ToLower().StartsWith(SiteState.Alias.Path.ToLower()) && !string.IsNullOrEmpty(SiteState.Alias.Path)))
		{
			if (hasReload && querystring["reload"] == "post")
			{

```

**Comment by sbwalker** [comment]
The "reload" querystring parameter is used to do a full refresh of the page - which is generally only needed after a user authentication event such as login/logout to get the cookie from the server. The "post" value is a special scenario where the anti-forgery cookie needs to be refreshed (which occurs after a remote OIDC login). The other condition which is being evaluated is if the user is navigating to a different Alias path (ie. navigating from www.site.com/alias1 to www.site.com/alias2) which would also require a full page refresh to re-authenticate the user and refresh their cookies. Thank you for pointing out the logic issue.
