### ISSUE TITLE
Duplicate File upload 

### ISSUE THREAD

**Issue by ajahangard** [oqtane/oqtane.framework#2529]
Hi, 
If we upload a file to a folder while a file with the same name exists, the file will replace the existing file, but the database will not be updated because it tries to add to File table and there is a unique index on the <FolderId, Name>.

**Comment by sbwalker** [comment]
I believe this is fixed already in the Dev branch - in which version did you experience the problem?

**Comment by ajahangard** [comment]
Yes, it is fixed in this [commit](https://github.com/oqtane/oqtane.framework/commit/7489d9d186e68f07deb618e0503f176c19107338)
thanks
