### ISSUE TITLE
Bugs: NotificationJob.cs (2 fixes, code included here)

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#2534]
Sorry, I'm not up to speed on performing git pull requests yet, so I've included the code here.

Below is updated code that removes several lines that put notification field elements into the message body so the body renders as the content of notification.Body only.  These lines look like leftover debug info...

Also added code that corrects usage of FromEmail/FromDisplayName as current logic only allowed SMTPSender/SiteName.

`//  Removed superfluous entries that appended notification elements (from/to/sent/subject) into message body.  
//  Body now only contains content from notification.Body field.
//  Corrected logic where notification.FromEmail and notification.FromDisplayName were not being used when provided in the notification record.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using Microsoft.Extensions.DependencyInjection;
using Oqtane.Models;
using Oqtane.Repository;
using Oqtane.Shared;

namespace Oqtane.Infrastructure
{
    public class NotificationJob : HostedServiceBase
    {
        // JobType = "Oqtane.Infrastructure.NotificationJob, Oqtane.Server"

        public NotificationJob(IServiceScopeFactory serviceScopeFactory) : base(serviceScopeFactory)
        {
            Name = "Notification Job";
            Frequency = "m"; // minute
            Interval = 1;
            IsEnabled = false;
        }

        // job is executed for each tenant in installation
        public override string ExecuteJob(IServiceProvider provider)
        {
            string log = "";

            // get services
            var siteRepository = provider.GetRequiredService<ISiteRepository>();
            var userRepository = provider.GetRequiredService<IUserRepository>();
            var settingRepository = provider.GetRequiredService<ISettingRepository>();
            var notificationRepository = provider.GetRequiredService<INotificationRepository>();

            // iterate through sites for current tenant
            List<Site> sites = siteRepository.GetSites().ToList();
            foreach (Site site in sites)
            {
                log += "Processing Notifications For Site: " + site.Name + "<br />";

                // get site settings
                List<Setting> sitesettings = settingRepository.GetSettings(EntityNames.Site, site.SiteId).ToList();
                Dictionary<string, string> settings = GetSettings(sitesettings);
                if (settings.ContainsKey("SMTPHost") && settings["SMTPHost"] != "" &&
                    settings.ContainsKey("SMTPPort") && settings["SMTPPort"] != "" &&
                    settings.ContainsKey("SMTPSSL") && settings["SMTPSSL"] != "" &&
                    settings.ContainsKey("SMTPSender") && settings["SMTPSender"] != "")
                {
                    // construct SMTP Client 
                    var client = new SmtpClient()
                    {
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Host = settings["SMTPHost"],
                        Port = int.Parse(settings["SMTPPort"]),
                        EnableSsl = bool.Parse(settings["SMTPSSL"])
                    };
                    if (settings["SMTPUsername"] != "" && settings["SMTPPassword"] != "")
                    {
                        client.Credentials = new NetworkCredential(settings["SMTPUsername"], settings["SMTPPassword"]);
                    }

                    // iterate through undelivered notifications
                    int sent = 0;
                    List<Notification> notifications = notificationRepository.GetNotifications(site.SiteId, -1, -1).ToList();
                    foreach (Notification notification in notifications)
                    {
                        // get sender and receiver information if not provided
                        if ((string.IsNullOrEmpty(notification.FromEmail) || string.IsNullOrEmpty(notification.FromDisplayName)) && notification.FromUserId != null)
                        {
                            var user = userRepository.GetUser(notification.FromUserId.Value);
                            if (user != null)
                            {
                                notification.FromEmail = (string.IsNullOrEmpty(notification.FromEmail)) ? user.Email : notification.FromEmail;
                                notification.FromDisplayName = (string.IsNullOrEmpty(notification.FromDisplayName)) ? user.DisplayName : notification.FromDisplayName;
                            }
                        }
                        if ((string.IsNullOrEmpty(notification.ToEmail) || string.IsNullOrEmpty(notification.ToDisplayName)) && notification.ToUserId != null)
                        {
                            var user = userRepository.GetUser(notification.ToUserId.Value);
                            if (user != null)
                            {
                                notification.ToEmail = (string.IsNullOrEmpty(notification.ToEmail)) ? user.Email : notification.ToEmail;
                                notification.ToDisplayName = (string.IsNullOrEmpty(notification.ToDisplayName)) ? user.DisplayName : notification.ToDisplayName;
                            }
                        }

                        // validate recipient
                        if (string.IsNullOrEmpty(notification.ToEmail))
                        {
                            log += "Recipient Missing For NotificationId: " + notification.NotificationId + "<br />";
                            notification.IsDeleted = true;
                            notificationRepository.UpdateNotification(notification);
                        }
                        else
                        {
                            MailMessage mailMessage = new MailMessage();
                            mailMessage.Subject = notification.Subject;
                            if (!string.IsNullOrEmpty(notification.FromEmail) && !string.IsNullOrEmpty(notification.FromDisplayName))
                            {
                                mailMessage.From = new MailAddress(notification.FromEmail, notification.FromDisplayName);
                            }
                            else
                            {
                                mailMessage.From = new MailAddress(settings["SMTPSender"], site.Name);
                            }
                            if (!string.IsNullOrEmpty(notification.ToEmail) && !string.IsNullOrEmpty(notification.ToDisplayName))
                            {
                                mailMessage.To.Add(new MailAddress(notification.ToEmail, notification.ToDisplayName));
                            }
                            else
                            {
                                mailMessage.To.Add(new MailAddress(notification.ToEmail));
                            }
                            mailMessage.Body += notification.Body;

                            // set encoding
                            mailMessage.SubjectEncoding = System.Text.Encoding.UTF8;
                            mailMessage.BodyEncoding = System.Text.Encoding.UTF8;

                            // send mail
                            try
                            {
                                client.Send(mailMessage);
                                sent = sent++;
                                notification.IsDelivered = true;
                                notification.DeliveredOn = DateTime.UtcNow;
                                notificationRepository.UpdateNotification(notification);
                            }
                            catch (Exception ex)
                            {
                                // error
                                log += ex.Message + "<br />";
                            }
                        }
                    }
                    log += "Notifications Delivered: " + sent + "<br />";
                }
                else
                {
                    log += "SMTP Not Configured Properly In Site Settings - Host, Port, SSL, And Sender Are All Required" + "<br />";
                }
            }

            return log;
        }

        private Dictionary<string, string> GetSettings(List<Setting> settings)
        {
            Dictionary<string, string> dictionary = new Dictionary<string, string>();
            foreach (Setting setting in settings.OrderBy(item => item.SettingName).ToList())
            {
                dictionary.Add(setting.SettingName, setting.SettingValue);
            }
            return dictionary;
        }
    }
}`

**Comment by sbwalker** [comment]
Actually the current behavior is not a bug - it is by design. Most modern SMTP servers have restrictions related to sending emails from any account other than the one used to authenticate with the server. As a result the Notification Job always uses the Sender address which is configured in the SMTP Settings (alongwith the username/password) so that it can be assured messages will be delivered and not rejected by the SMTP server. And because a constant Sender is used for delivery, the body of the email includes information related to the actual user who sent the message.

**Comment by sbwalker** [comment]
One change which may address the "problem" you reported is if the Notification Job set the Display Name to the actual name of the user, while still using the Sender email address to ensure deliverability. A good example of this is GitHub where all email is sent from notifications@github.com but the display name is set to the user who made the post:

![image](https://user-images.githubusercontent.com/4840590/208737381-1034d8be-81c0-44c1-b653-c52833ec0070.png)

**Comment by W6HBR** [comment]
I do agree that default SMTP server behavior is to only allow sending from the authenticated account, but performing a relay send is also a very normal operation for internal corporate systems.  Even Gmail supports this feature using an authorized account sending via smtp-relay.gmail.com.  Why not allow the functionality?  At worst, if a user tries to send with an unauthorized account, their message won’t be delivered and they’ll need to correct their settings.

The notification api and db records already have all the necessary elements to allow the notification system to be leveraged as a general purpose message delivery system (e.g. user messages, bulk member messages, subscriber messages, etc.).  This allows sending by user accounts allowing responses to come back to the designated sending user’s inbox.  (Doing this also needs a clean body content as it was submitted via the api).  If someone does not provide the FromEmail & FromDisplayName when submitting via the API, then the default behavior will still use the system configured sender.

**Comment by W6HBR** [comment]
I was also going to suggest adding the property "IsBodyHtml" to the API & notification table with the corresponding line in NotificationJob.cs to allow utilization.

**Comment by sbwalker** [comment]
I am thinking that an additional SMTP Setting (in Site Settings) could be added which allows you to specify Relay Sending Enabled. Then the Notification Job could use this setting to determine whether it should send email on behalf of a user or from the Sender specified in settings. The Notification API currently expects that a Notification object contains either a FromUserId or a FromEmail and FromDisplayName - if all 3 of these are blank the Notification object is invalid. We would not want to change this behavior as it would be a behaviorial breaking change.

**Comment by sbwalker** [comment]
Relay Sending Enable is probably not the correct name for this setting, as the problem is not really related to relay sending - it is more related to anti-spam systems which restrict sending email from another domain. 

Basically if you want to send emails on behalf of a different user/domain, there are two solutions:

1. Send the emails through their mail server (however this usually requires knowledge of their authentication details for their server)

2. Configure their anti-spam settings (SPF, DKIM, DMARC, whatever) to allow your mail server to send emails using their SMTP domain in the sender address.

Neither of these options are feasible in the majority of cases. So as a result the common solution is to send email from a consistent authorized account. This is the reason the Notification Job uses this approach. 

There is one scenario however which is an exception to this rule - an internal application or intranet where all users are managed under the same domain. In this environment you have the ability to configure your mail server for deliverability, so it is feasible to send email on behalf of a specific user. I am not sure what the Setting should be named to identify this scenario?

**Comment by W6HBR** [comment]
> There is one scenario however which is an exception to this rule - an internal application or intranet where all users are managed under the same domain. In this environment you have the ability to configure your mail server for deliverability, so it is feasible to send email on behalf of a specific user. I am not sure what the Setting should be named to identify this scenario?

Yes, this is the specific case I am using with my installation.

Maybe a description like:
"Use override E-mail Sender" or just "Override E-mail Sender" or "Use submitted E-mail Sender"??

Then for the tooltip, something more descriptive:
"This option allows the notification record to be sent using the submitted "FromUserId" or "FromDisplayName/FromEmail" fields.  This is an advanced email configuration for relays and not used in most configurations."

**Comment by thabaum** [comment]
Something like "Send with Users Email Address (Relay)" would make sense to me.

**Comment by W6HBR** [comment]
> Something like "Send with Users Email Address (Relay Server)" would make sense to me.

Sending as the current user's email address is just one scenario.  The usage case can be whomever you have specified as the sender in the notification record submitted. Think about subscriber or mail lists where multiple users may generate content to send, but all using the same sender identity.

**Comment by thabaum** [comment]
Wouldn't this be more a component setting than an overall Octane app setting then?

I believe you can potentially set the "Reply To" while still using the same SMTP username email address configured in an application.

So for sending notifications for the mailing lists, in the component for the mailing lists you would set this feature setting.

So maybe a "ReplyTo" setting needs created and can be set within components would be a best solution, on top of this relay server setting which I feel should also be supported.

**Comment by thabaum** [comment]
Yahoo, Google and Outlook web apps all support "Reply-To" fields while using one email address to send.

https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.mailmessage.replyto?view=net-7.0

Looks like "ReplyToList" is what we should be thinking about in .NET 7

**Comment by W6HBR** [comment]
Using “Reply-To” works in many cases, but not all.  Even today, Gmail still has spotty issues with deliverability when using Reply-To.  I would view using “Reply-To” as a different use case.  Properly implemented, this would also require additional fields be added to the notification db & api as the current fields are designated as being “From” addresses.  

Using the "From" address is more reliable and has the added benefit that if you relay with a direct submit (e.g. using the specified domains mail server) email messages will appear in the sent folder of the “From” address used (on most mail systems).
