### ISSUE TITLE
Please Reconsider the Module Distribution Platform to not be NuGet

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2549]
As of now, all **Install** packages for Oqtane are published on NuGet.

IMHO this causes some problems which will grow with time. Here's why.

### 1. Misuse of the real purpose of NuGet

NuGet is IMHO like NPM, it contains libraries to use in your code. 

But this is not what an install-package for Oqtane is. 
Oqtane packages contain installation instructions, assets and more, which only make sense when deployed to a _running_ Oqtane environment. 

### 2. Confusion about packages which have real NuGets

We are about to release some libraries for [cr8magic](https://cre8magic.blazor-cms.org/) which are real libraries. 

At the same time, we should also release it as an install package.

As of now, our strategy is:

1. Real libraries would be `ToSic.Cre8Magic.Oqtane`
2. Install package will be something like `ToSic.Cre8magic.Oqtane.Install`

But I feel that this will often confuse people resulting in them picking and trying to install the wrong package - especially when using Visual Studio.

### Goals

1. I assume the core challenge is that we need a public, standardized location for the install packages. 
2. They should all be "in the same place" because we don't want to list links from all over the internet for all kinds of reasons
3. This location should be free and easy to use
4. It should offer some APIs for the Oqtane.net backend to verify things such as "does the file exist" etc.

### Recommendation

I believe that Github Releases would be more appropriate for the install packages.

**Comment by leigh-pointer** [comment]
You can actually specify where the package is downloaded.

![image](https://user-images.githubusercontent.com/9447612/211798712-1f89d56d-efe7-448d-a8fd-7b7e421c29a6.png)

**Comment by iJungleboy** [comment]
@sbwalker / @leigh-pointer thanks for this
