### ISSUE TITLE
Request for Docs regarding DLL handling of dependencies (I would help...)

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2559]
@sbwalker 

We have a setup where multiple Oqtane extensions would use the same third-party DLL dependencies. This could lead to version conflicts down the road.

So it's important to know how this is handled at installation. 
If you could just give me a brief summary of how it's done, I would then add it to the docs.

**Comment by sbwalker** [comment]
There is currently no special logic to handle this scenario. When a package is installed, and the location for a file is identified as "lib\" it will copy the file to the /bin folder. If there was already a file with the same name in that folder, it will be replaced. There is no logic for checking version number or other dependency concerns.

**Comment by mvit777** [comment]
@sbwalker

can you kindly point the relevant files/code where this identification and copy happen?

**Comment by sbwalker** [comment]
Nuget packages are installed in Oqtane.Server/Infrastructure/InstallationManager - InstallPackages method.

**Comment by iJungleboy** [comment]
Thanks. This will lead to problems, but it's best to document it as is.

I'll do this in a few days. 

I'm sure improving this would take a lot of work, but maybe a half-improvement could be done by backing up the old DLLs when they are replaced.
