### ISSUE TITLE
404 error or redirect to site and not the default site when page doesn't exist

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#257]
Is there a way to prevent a missing page from going back to the default site?

For example, if I have a default site and a site2, and I enter site2/foo (which doesn't exist), I am taken back to the default site home page. I would prefer to be taken back to the default page for site2 or even something like site2/404. Is this possible?

**Comment by sbwalker** [comment]
Yes this should be possible... we just need to track down the affected area.

**Comment by sbwalker** [comment]
#278   deals with the case where a page does not exist ( or a user does not have permission to view the page ). It will log the issue to the event log and it will redirect the user to the home page of the current site.

**Comment by mikecasas** [comment]
Just wanted to confirm that #278 did fix #257
