### ISSUE TITLE
Blazor MAUI - File Upload doen't work on .Net 7

### ISSUE THREAD

**Issue by Sen-Gupta** [oqtane/oqtane.framework#2572]
Hello @sbwalker, it may be already on your radar if .Net 7 upgrade is being attempted.

When Oqtane is upgraded to .Net 7, Under File Management, File Upload fails for both Windows and Android.

**Comment by sbwalker** [comment]
I have not began the journey to .NET 7 yet. It seems very strange that the File Upload would be broken as it does not rely on any specific Blazor functionality - it basically takes an HTML5 File Input, calls a  JavaScript method via JSInterop which splits the file into 1 MB chunks, sends the chunks in parallel asynchronously to a server endpoint, which reassembles the file using the chunks and registers the file entry in the database. I am assuming that you tested this on .NET 6 in your environment and it was working fine?

**Comment by leigh-pointer** [comment]
There was an issue mentioned with files in .Net7 in Carl Franklin's Blazor Train https://www.youtube.com/watch?v=YES8O6K1nGM&list=PL8h4jt35t1wjvwFnvcB2LlYL4jLRzRmoz&index=97&t=310s  full https://youtu.be/YES8O6K1nGM

**Comment by sbwalker** [comment]
@leigh-pointer thank you for the tip... I will watch the video to see if it is related

**Comment by sbwalker** [comment]
@Sen-Gupta do you have an actual exception message? It should be in your Event Log. Very difficult to track down without a detailed error message.

**Comment by Sen-Gupta** [comment]
@sbwalker as @leigh-pointer pointed out, it seems like a .Net 7 issue. I will share the details on Monday!

**Comment by sbwalker** [comment]
@Sen-Gupta please share the solution at your convenience
