### ISSUE TITLE
After upgrade to 3.3.1 I got a NullReferenceExeption in PageModuleRepository

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2574]
![image](https://user-images.githubusercontent.com/76835718/215743300-87664a0d-097a-4862-bd20-7823bb8b2f96.png)

I change the lineno 107 to get it work.

` if (_pageModule.Module.ModuleDefinition != null &&_ !string.IsNullOrEmpty(pageModule.Module.ModuleDefinition.PermissionNames) && pageModule.Module.ModuleDefinition.PermissionNames.Contains(":"))`

`

**Comment by sbwalker** [comment]
if _pageModule.Module.ModuleDefinition is null in your installation it most likely means you have an orphaned module in your database, as a module should always have a corresponding ModuleDefinition object. I can certainly add the failsafe logic you suggested to prevent a framework error- but it will cover up the fact that you have some corruption in your database.

**Comment by beolafsen** [comment]
Thank you for answer.
I will correct my database table.
You decide what to do with the framework code.
