### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2600]
Latest form GitHub 
(https://github.com/oqtane/oqtane.framework/commit/b3f7353582fdb59f9b18e56c64c0e8df6b4e6e74)

![image](https://user-images.githubusercontent.com/9447612/219362133-bf3f45bd-bf82-4727-8732-98f569f52846.png)

**Comment by sbwalker** [comment]
what is the Url of the broken image?

**Comment by leigh-pointer** [comment]
Me being not so clover.  New fork over an older database.

**Comment by leigh-pointer** [comment]
No issue
