### ISSUE TITLE
Backward Compatibility Issue 3.4.0 with Oqtane.Models.PermissionString

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2623]
Error from Oqtane due to a External module relying on **Oqtane.Models.PermissionString**

```
An Unexpected Error Has Occurred In StudioElf.DynamicForm, StudioElf.DynamicForm.Client.Oqtane: Could not load type 'Oqtane.Models.PermissionString' from assembly 'Oqtane.Shared, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null'.

System.TypeLoadException: Could not load type 'Oqtane.Models.PermissionString' from assembly 'Oqtane.Shared, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null'.
   at StudioElf.DynamicForm.Settings.OnInitializedAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at StudioElf.DynamicForm.Settings.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by sbwalker** [comment]
@leigh-pointer can you please provide some more details on how your module was using the PermissionString model? If your module is dependent on this model I am imagining there will be other issues you will encounter with the latest permission refactoring - as it assumes that the custom permission format was only used internally.

**Comment by sbwalker** [comment]
I can definitely add the PermissionString model back and give it an Obsolete attribute

**Comment by leigh-pointer** [comment]
@sbwalker I have actually refactored my module to use the new permissions.  I was using the PermissionString in a process to check what permissions have been set, but now a lot happier with the new implementation.
