### ISSUE TITLE
When Clearing modules from the Recycle Bin Records are Orphaned

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2625]
When the Modules are cleared from the Recycled bin only the PageModule record is deleted thus leaving orphaned records in tables;
Module, Permissions, Settings

**Comment by sbwalker** [comment]
The expected behavior is that if you delete a module from the recycle bin, the framework removes the PageModule instance. It then checks if there are any other PageModule instances for that ModuleId in the Site. If none are found then it deletes the Module record as well.

**Comment by leigh-pointer** [comment]
@sbwalker I will close #2625 and recreate as described.
