### ISSUE TITLE
Naming new theme files with the theme name

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2634]
Newly created theme files such as Theme1.razor and Container1.razor I propose should be named as follows:

[Theme]Theme.razor
[Theme]Container.razor

same with [Theme]ThemeSettings.razor and [Theme]ContainerSettings.razor

Let us developers make changes from there, it gives me a feeling that these files are to be edited if I was new to the arena.

This would take renaming the files in the template creation folder so I will wait on creating this PR until I hear community will accept the proposal.

**Comment by sbwalker** [comment]
The reason they are currently named with a numeric suffix is to provide a developer a hint that Oqtane supports multiple theme and container components within the same theme package. For example you may have a dedicated theme component for your site home page and another theme component for the rest of your site pages. And you may have a variety of container components with different look and feel as well. Some of this variability could be handled with Theme/Container settings however there still may be a need for multiple components of each type as well.
