### ISSUE TITLE
Dev - Control Panel Stays Open After Adding Module To Page

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2639]
Issue: 

After adding a module to a page I am expecting the control panel to close, I do see a toast message so maybe close after action could be a setting to enable/disable.  But if I add another module that toast message never dissolves and I don't know really what modules are added.

I can see leaving the control panel open while setting up a page, so maybe a checkbox at top to keep open next to control panel title?

However the toast messages need to reflect what module was added and where it was added so I know a `HtmlText <br/> Module Added to Page`  This should dissolve or another toast message overwrites it on next module added. 

Just one more click closing the control panel I could live without.  I usually work on one module at a time so the need for keeping the panel open is rare for me however I see it as useful for certain situations.  I just would like to know what module was added last with a module name at least in the toast message.

If we closed the control panel a toast message may need to be created as a popup that fades out.

![image](https://user-images.githubusercontent.com/13577556/222980641-f4fda439-1353-4f5e-a8c3-0cc72f5b777d.png)

**Comment by sbwalker** [comment]
This is by design. It enables an Admin to add multiple modules to a page without having to click the Control Panel icon repeatedly.
