### ISSUE TITLE
Version 3.4.0 - An error occurred while installing an additional tenant

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#2647]
Installing the Master version is OK, but when installing the second version, it gives an error.

If Database is selected as <Create Database>, the error is as follows:

![image](https://user-images.githubusercontent.com/6874322/223374177-b5ce1d94-3b13-4806-89b6-51938fc462e6.png)

If you choose a shared database (Master), the error is as follows:

![image](https://user-images.githubusercontent.com/6874322/223375971-5706f271-5fa8-4820-a4fa-2340a063a87e.png)

**Comment by sbwalker** [comment]
Your screen shots are truncated - what type of database are you trying to create? MySQL?

**Comment by lthoa** [comment]
Error occurs with both SQL and MySql.

**Comment by sbwalker** [comment]
I am able to reproduce... seems to be related to the recent permissions optimization. I will investigate.
