### ISSUE TITLE
How to get the context-data from OpenId Connect response

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2655]
Hi!
I have an external OpenId ConnectId login to the Norwegian Sports Association. This works fine. 

In the login response-  from the Norwegian Sports Association - they send this properties/data:
```
Context / dataobjekt:
{
  'sub': 'f:3b9fc540-4522-473d-a6fe-a2f3ec05a693:234319093',
  'name': 'Jan Johansen',
  'email': 'jan@johansen.tld',
  'gender': 'male',
  'birthdate': '1970-12-01',
  'bp_id_sub': '102349293',
  'given_name': 'Jan',
  'family_name': 'Johansen',
  'email_verified': False,
  'preferred_username': 'jan@johansen.tld'
}
```

Question 1:
How can I get this information from my Module-program - ex: "gender"-field.

Question 2:
Is there a way to map this fields to the UserProfile fields?

Best regards
Bjørn-Even Olafsen

**Comment by sbwalker** [comment]
Currently there is no way to extract additional metadata from the OpenID token - an enhancement would be required in order to extract and potentially map values to the User Profile.

**Comment by beolafsen** [comment]
Would this be something that you will be consider implemented? 
In Norway, all sports clubs and members are registered in the Norwegian Sports Association and we will be able to get all the necessary data (like firstname, lastname, birthdate, phonenr, gender, adresses, email, etc....) from them if this can be implemented.

I did a small testimplementation like this: (I know that more has to be done - but it seams to work fine)

Profile.cs
Added new field:
`public string? JWTMapping { get; set; }`

Added this to public static class OqtaneSiteAuthenticationBuilderExtensions  :
```
     private static void AddUserProfileData(User user, TokenValidatedContext context, HttpContext httpContext)
        {
            var alias = httpContext.GetAlias();

            // Get userprofiledata
            var settingRepository = httpContext.RequestServices.GetRequiredService<ISettingRepository>();
            var settings = settingRepository.GetSettings("User", user.UserId);

            // Get ProfileDefinition
            var profileService = httpContext.RequestServices.GetRequiredService<IProfileRepository>();
            var _profiles = profileService.GetProfiles(alias.SiteId);

            foreach (var item in _profiles.Where(p => !p.JWTMapping.IsNullOrEmpty()))
            {
                var claim = context.Principal.Claims.FirstOrDefault(p => p.Type == item.JWTMapping);
                if (claim != null) 
                {
                    var setting = settings.FirstOrDefault(p => p.SettingName == item.Name);
                    if(setting.SettingValue != claim.Value)
                    {
                        setting.SettingValue = claim.Value;
                        settingRepository.UpdateSetting(setting);
                    }
                }
            }
        }
```
And the rouine is called from ValidateUser(..)
 ```
              // manage user
                if (user != null)
                {
                    // create claims identity
                    var _userRoles = httpContext.RequestServices.GetRequiredService<IUserRoleRepository>();
                    identity = UserSecurity.CreateClaimsIdentity(alias, user, _userRoles.GetUserRoles(user.UserId, user.SiteId).ToList());
                    identity.Label = ExternalLoginStatus.Success;

                    // update user
                    user.LastLoginOn = DateTime.UtcNow;
                    user.LastIPAddress = httpContext.Connection.RemoteIpAddress.ToString();
                    _users.UpdateUser(user);
                    _logger.Log(LogLevel.Information, "ExternalLogin", Enums.LogFunction.Security, "External User Login Successful For {Username} Using Provider {Provider}", user.Username, providerName);

                    // BEO TEST _ UPdate profile
                    **AddUserProfileData(user, context, httpContext);**
                }
```

**Comment by beolafsen** [comment]
Another observation:
I downloaded a new browser (opera) that I never used before and I log in to my Oqtane website with OpenId (Github). I had to key in my username/passord/two-factor code into Github. After logging in -  I log out again. Then I choose to log in again and I use the GitHub login button - and I'm **automaticaly** logged in whitout any question about username/pw..... 
This is fine when I'm at home and only I use the computer - but if I'm do the same on a public it's not so good. Then everybody can come into my website after I have been the once.
How can this be prevented?

**Comment by sbwalker** [comment]
It appears we were both working on it at the same time :) Please see PR #2655 - I added a new User Option for User Profile Claims which allow you to specify a comma delimited list of claims and their mappings to the Profile. This is similar to what you described above with your JwtMapping field - but it follows the options pattern to support multi-tenancy and UI administration. In your case the mapping value might be "given_name:FirstName,family_name:LastName,gender:Gender".

![image](https://user-images.githubusercontent.com/4840590/224352987-01cf3fb3-56ef-4664-b32b-55637184f640.png)

The rest of the code is similar to what you described above - the main difference is that ValidateUser needed an extra parameter to be passed to it which contains the IdentityClaims. Please go ahead and test to determine if it meets your needs.

**Comment by sbwalker** [comment]
To answer your other question... in the scenario you described above you still have a valid Github token and never explicitly logged out so this means you are still authenticated.

**Comment by beolafsen** [comment]
Great - I will download and test.

About my other question:
How can I or the oqtane-sw delete this Github token when I log out from my Oqtane website. 
Is it me that thinking wrong - I see this as a big security risk!

**Comment by sbwalker** [comment]
Remote Logout could potentially be a security risk - it depends on your environment and how your site is intended to be used. The challenge with Remote Logout is that there is not a standard method for all identity providers - they each implement it in their own way. Generally for OIDC providers there is a Url but it often contains custom parameters based on the context (ie. it might require the remote user id or username which may not be available in the local system). And many basic OAuth2 providers do not provide any remote logout mechanism at all (ie. GitHub). These are the reasons why this capability was not included in the initial remote authentication implementation in Oqtane. It will require a lot more research in order to be able to handle it in a productized manner.

**Comment by sbwalker** [comment]
Apparently another way to deal with External Logout is to modify the configuration of your Remote Login. You can use the optional "prompt" parameter to affect the behavior:
 
"none" - (default) The Authorization Server MUST NOT display any authentication or consent user interface pages. 

"login" - The Authorization Server SHOULD prompt the End-User for re-authentication. 

"consent" - The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. 

"select_account" -  The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. 

An option could be added to Oqtane to control this behavior per site.

**Comment by beolafsen** [comment]
Great!
I downloaded the new version from GitHub and I found some issues:
1) If I key in wrong pw in the login  and have the TwoFactor set to required - the system ask for verification-code. It should only say - wrong pw. and it does never send a verification code to my email.
2) If I key in the correct pw in the login and have the twofactor enabled - it does not ask for twofactor verification-code.
3) I'm not able to login to GitHub (OAuth2) anymore - get the error: 
https://[localhost](https://localhost:44357/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=CfDJ8ITHcaoKPMhDogO0sy3csVCJ8gdlOCUGKwPbAs34M8FTFQ3IATjvhvXiyeT2eeC-98t8Qc0nFxDtJCGepQo_FEMDDG-zrFpi3-MvtpeyPNJde8GTIEUvXvEeVkh84eR9_mqqqDUkN2PGA3NsQI2Ri2R7oViKrUBrE4Vqfg7lG6ZzOuvPxg5bIPpm-1mwjlo8ndxZmuf84tE-qdAdutmj4KEgLLPU3zHNhu1Hu5FNym0Y):44357/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=CfDJ8ITHcaoKPMhDogO0sy3csVCJ8gdlOCUGKwPbAs34M8FTFQ3IATjvhvXiyeT2eeC-98t8Qc0nFxDtJCGepQo_FEMDDG-zrFpi3-MvtpeyPNJde8GTIEUvXvEeVkh84eR9_mqqqDUkN2PGA3NsQI2Ri2R7oViKrUBrE4Vqfg7lG6ZzOuvPxg5bIPpm-1mwjlo8ndxZmuf84tE-qdAdutmj4KEgLLPU3zHNhu1Hu5FNym0Y

This is the parameterset I use - same as I used in the "old" version of OqtaneFramework.:
![image](https://user-images.githubusercontent.com/76835718/224474405-73b73a01-16cc-47a3-b813-e58abb3d8544.png)

4) I'm not able to login to Norwegian Sport Assotiation (OpenIdConnect) - but I think that has to with their system. Will test it again on monday.

I went back to the "old" version of Oqtane Framework to test if can login there - and I found that:

1) This parameters work on OAuth2 - same parameters that does not work in the new version of Oqtane Framework
![image](https://user-images.githubusercontent.com/76835718/224472988-a8232c9a-6370-4275-af70-3176e582d21a.png)

2) When I try to add the Parameters : prompt=login - I get this error:
![image](https://user-images.githubusercontent.com/76835718/224473053-0a06c274-bff2-4cf4-bc90-063620aa1d3a.png)
![image](https://user-images.githubusercontent.com/76835718/224473086-d02d4b36-7536-4339-9a7d-3ec46a042496.png)

3) If I try the prompt=none - I got the same error.
System.InvalidOperationException: 'The provided identity of type 'System.Security.Claims.ClaimsIdentity' is marked IsAuthenticated = true but does not have a value for Name. By default, the antiforgery system requires that all authenticated identities have a unique Name. If it is not possible to provide a unique Name for this identity, consider extending IAntiforgeryAdditionalDataProvider by overriding the DefaultAntiforgeryAdditionalDataProvider or a custom type that can provide some form of unique identifier for the current user.'

4) prompt=consent
First I got this message:
![image](https://user-images.githubusercontent.com/76835718/224473358-3ee75ab4-b346-4597-9ee4-61efb308b341.png)

Then after click Authorize beolafsen I got the same message that I got earlier.
![image](https://user-images.githubusercontent.com/76835718/224473470-85678820-517b-4c54-a2f1-0797f5454094.png)


Tell me if there are something that is not clear - and I will try to explain better.

BEO

**Comment by sbwalker** [comment]
When you say "old" version are you referring to 3.3.1 (the last official release version)?

**Comment by beolafsen** [comment]
yes

Med vennlig hilsen
Bjørn-Even Olafsen


lør. 11. mar. 2023 kl. 15:43 skrev Shaun Walker ***@***.***>:

**Comment by sbwalker** [comment]
The Oqtane Marketplace (https://www.oqtane.net) uses GitHub authentication and is running the latest code from the Dev branch (3.4.0). Login is working fine for me - please try it yourself.

**Comment by sbwalker** [comment]
I just tested with OIDC using Azure B2C and I did find a minor issue with the new logic to capture user profile information - but it did not result in an error or failed login - it simply did not update the profile as expected. This has now been resolved.

I am not sure why you are experiencing authentication issues in your testing. Obviously there are a LOT of dependencies for the external login flow so it is difficult to isolate the scenario causing the problem for you. One thing you did mention is that you have 2 factor authentication enabled in your installation... so I am wondering if that may be causing the issue. Did you have 2FA enabled in 3.3.1?

**Comment by beolafsen** [comment]
When I got problems with the new sw - I wanted to take away my models so I
only started the oqtane framework and made a new db installation.
I did this for both sw-versions. I only added the *OAuth 2.0* parameters.
I see that you have tested with *OIDC - not OAuth 2.0*.  I was not able to
test OAuth 2.0 because - I think - there is a problem with the Norwegian
Sport Association system this weekend. I have to wait until Monday to test
this.
The 2 factor is not enabled in any of these test installations.

Would it help you to see the installations/problem? You are welcome to
connect to my computer - I have TeamView installed.


Med vennlig hilsen
Bjørn-Even Olafsen


lør. 11. mar. 2023 kl. 17:52 skrev Shaun Walker ***@***.***>:

**Comment by beolafsen** [comment]
I found the problem - and it's not in the sw.
When I downloaded the new version from GitHub - I forgot to change the http parameter to https in the debug properties.
Sorry for the inconvenience.

BEO

**Comment by sbwalker** [comment]
Very glad to hear this new feature works for you - I believe it is a valuable enhancement to the framework.

**Comment by beolafsen** [comment]
Hi!
I made a ProfileUpdate for OAuth2 in the OqtaneSiteAhthenticationBuilderExtensions.cs - ValidateUser. See if you want to use it as a base. Nice also to be able to update ex.Google-data to the profile.

```
                // manage user
                if (user != null)
                {
                    // create claims identity
                    var _userRoles = httpContext.RequestServices.GetRequiredService<IUserRoleRepository>();
                    identity = UserSecurity.CreateClaimsIdentity(alias, user, _userRoles.GetUserRoles(user.UserId, user.SiteId).ToList());
                    identity.Label = ExternalLoginStatus.Success;

                    // update user
                    user.LastLoginOn = DateTime.UtcNow;
                    user.LastIPAddress = httpContext.Connection.RemoteIpAddress.ToString();
                    _users.UpdateUser(user);

                    // user profile claims
                    if (!string.IsNullOrEmpty(httpContext.GetSiteSettings().GetValue("ExternalLogin:ProfileClaimTypes", "")))
                    {
                        var _settings = httpContext.RequestServices.GetRequiredService<ISettingRepository>();
                        var _profiles = httpContext.RequestServices.GetRequiredService<IProfileRepository>();
                        var profiles = _profiles.GetProfiles(alias.SiteId).ToList();

                        foreach (var mapping in httpContext.GetSiteSettings().GetValue("ExternalLogin:ProfileClaimTypes", "").Split(',', StringSplitOptions.RemoveEmptyEntries))
                        {
                            if (mapping.Contains(":"))
                            {
                                if (providerType == AuthenticationProviderTypes.OpenIDConnect)
                                {
                                    // OpenId Connect
                                    var claim = claimsPrincipal.Claims.FirstOrDefault(item => item.Type == mapping.Split(":")[0]);
                                    if (claim != null)
                                    {
                                        AddProfile(_logger, _settings, user, profiles, mapping.Split(":")[1], claim.Value);
                                    }
                                    else
                                    {
                                        _logger.Log(LogLevel.Error, "ExternalLogin", Enums.LogFunction.Security, "The User Profile Claim {ClaimType} Does Not Exist. The Valid Claims Are {Claims}.", mapping.Split(":")[0], claims);
                                    }

                                }
                                if (providerType == AuthenticationProviderTypes.OAuth2)
                                {
                                    // OAuth2
                                    var idClaimType = httpContext.GetSiteSettings().GetValue("ExternalLogin:IdentifierClaimType", "");
                                    var emailClaimType = httpContext.GetSiteSettings().GetValue("ExternalLogin:EmailClaimType", "");
                                    if (!claims.StartsWith("[") && !claims.EndsWith("]"))
                                    {
                                        claims = "[" + claims + "]"; // convert to json array
                                    }
                                    JsonNode items = JsonNode.Parse(claims)!;
                                    var claimValue = string.Empty;
                                    foreach (var item in items.AsArray())
                                    {
                                        var claimType = profiles.FirstOrDefault(item => item.Name == mapping.Split(":")[1]);
                                        var claimName = mapping.Split(":")[0];
                                        if (item[claimName] != null)
                                        {
                                            AddProfile(_logger, _settings, user, profiles, claimType.Name, item[claimName].ToString());
                                            claimValue = item[claimName].ToString();
                                            break;
                                        }
                                    }

                                }

                             }
                            else
                            {
                                _logger.Log(LogLevel.Error, "ExternalLogin", Enums.LogFunction.Security, "The User Profile Claim Mapping {Mapping} Is Not Specified Correctly. It Should Be In The Format 'ClaimType:ProfileName'.", mapping);
                            }
                        }
                    }

                    _logger.Log(LogLevel.Information, "ExternalLogin", Enums.LogFunction.Security, "External User Login Successful For {Username} Using Provider {Provider}", user.Username, providerName);
                }
 
```

And put Profileupdate to a seperat function:

```
       private static void AddProfile(ILogManager _logger, ISettingRepository _settings,User user, List<Profile> profiles, string profileName, string profileClaimValue)
        {
            var profile = profiles.FirstOrDefault(item => item.Name == profileName);
            if (profile != null)
            {
                if (!string.IsNullOrEmpty(profileClaimValue))
                {
                    var setting = _settings.GetSetting(EntityNames.User, user.UserId, profile.Name);
                    if (setting != null && setting.SettingValue != profileClaimValue)
                    {
                        setting.SettingValue = profileClaimValue;
                        _settings.UpdateSetting(setting);
                    }
                    else if(setting == null)
                    {
                        setting = new Setting { EntityName = EntityNames.User, EntityId = user.UserId, SettingName = profile.Name, SettingValue = profileClaimValue, IsPrivate = profile.IsPrivate };
                        _settings.AddSetting(setting);
                    }
                }
            }
            else
            {
                _logger.Log(LogLevel.Error, "ExternalLogin", Enums.LogFunction.Security, "The User Profile {ProfileName} Does Not Exist For The Site. Please Verify Your User Profile Definitions.", profileName);
            }

        }
```
