### ISSUE TITLE
More than one external login options pr. site?

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2672]
It would be nice to have the possibility to login with ex. Google and Microsoft accounts on one site.

Are there plans to accept more external login options per site?

BEO

**Comment by sbwalker** [comment]
It is not planned at this time.

**Comment by beolafsen** [comment]
One "easy" way to handle it - without change the way it is implemented - could be to add a cobobox on top of the "External Login Settings" where you can select the configuration no you would work with - like this:
![image](https://user-images.githubusercontent.com/76835718/224751311-2705f8ab-edb2-4561-bf33-f1bfdb93fbdb.png)


And then change the parameternames from xxxxxxx to xxxxxxxxx1 (for config no 1) 
ex:
 options.Authority = sitesettings.GetValue("ExternalLogin:Authority", ""); could be changed to
 options.Authority = sitesettings.GetValue(**$"ExternalLogin:Authority{configno}"**, ""); 

And then we need to find a way to tell every function  whitch configno it shall use.

I don't know if it's possible to do something like this - but it would be nice to have more than one external login.

BEO

**Comment by sbwalker** [comment]
It would be a very invasive change to the current implementation. I am not going to prioritize it at this time.

**Comment by beolafsen** [comment]
OK
Have back in your head for future releases. :-) 

BEO
