### ISSUE TITLE
3.4.1 Issue with Module Definitions and Deleting modules

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2679]
When a module is deleted and then remove via the Recycle Bin it seem like the ModuleDefinition cache is also emptied.  This is an issue because you can no longer add modules via the Control Panel.  Restarting the framework populates the cache.

**Comment by sbwalker** [comment]
I will have to investigate this further.

**Comment by leigh-pointer** [comment]
@sbwalker 
> not to mention that publishing a release from an airport using my tethered cell phone for Internet connectivity was painful

I cant believe you did that! I must have been a nightmare.

Anyways, all is tested and all looks good.
