### ISSUE TITLE
Version 3.4.1 - Error when creating new site in existing installation with MySql

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#2680]
![image](https://user-images.githubusercontent.com/6874322/225019790-f9cf9c83-dab5-4e82-a64e-bd37cd214dc3.png)

**Comment by leigh-pointer** [comment]
Also with SQLite
![image](https://user-images.githubusercontent.com/9447612/225027146-e8e2424c-cbcc-4e33-a82b-df7d77d320f5.png)
