### ISSUE TITLE
Oqtane not working on ubuntu linux 22.04

### ISSUE THREAD

**Issue by egarim** [oqtane/oqtane.framework#2688]
Hi 
I want to test Oqtane in linux, to do that  I downloaded the dev branch after this commit 

https://github.com/oqtane/oqtane.framework/commit/7d4cd04ce96efba34748ba09402829104ef56b66

if I run the code using "dotnet run Oqtane.Server.csproj" everything works fine, I'm able to create a database and run oqtane

if I compile using this command "dotnet publish --runtime linux-64" it compiles and I'm able to run it, the process seems to run fine and connect to the database, it shows that kestrel is running in http://localhost:5000 and  https://localhost:5001 when I go to any of those URLS i get redirected to https://localhost:44357 but nothing is running in there.

I recorded a small video showing what is happening

https://youtu.be/reb5e2z6UcY

my questions is, am I missing something in the compilation process?

**Comment by leigh-pointer** [comment]
@egarim the Oqtane publishing is completely different to dotnet publish.  Search this discussion and the topic has be discussed.
HTH

**Comment by leigh-pointer** [comment]
@egarim The best place for you to start is to look a the packaging in the oqtane.server folder
`..\oqtane.framework\Oqtane.Package`
There you will find the build scripts and I and sure this will help you out.

**Comment by egarim** [comment]
Thanks a lot @leigh-pointer I modified the release scripts to target linux, I create a post about it, just in case some else wants to do the same 

https://www.jocheojeda.com/2023/03/20/2-publishing-oqtane-3-4-to-target-ubuntu-linux/
