### ISSUE TITLE
Application permission issues on Windows Server 2022 with IIS

### ISSUE THREAD

**Issue by tranpl** [oqtane/oqtane.framework#2690]
I've spent a few hours trying to install this on a more secure server but having mixed results.
I successfully installed oqtane 3.4.1 on a windows server 2022 vm with IIS following the documentation. 
I have set the application pool setting to no managed code and localsystem(per doc).

I logged in as admin or host user, tried editing the Home page, via removing the modules added to the page, the Url changed to https:/domain/?refresh but doesn't do anything. I did another test and went into Site Settings to change the theme to blazor theme, but got "Error Saving Site":
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Modules.Admin.Site.Index.SaveSite() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Admin\Site\Index.razor:line 547

{"SiteId":1,"Error":"Object reference not set to an instance of an object."}
```
I get errors for trying modify application settings, module settings etc.

I tried modifying the content of the HTML module..for example the home page, it saves and updates but can't remove the module.

I looked into IIS server's logs and application event, nothing shown useful so far. It seems like the application is working but specific permissions are missing.

Am I missing a setting somewhere, maybe through IIS specifically for this application? I have some experience deploying applications but might be helpful if anyone has this similar issue.

Finally, I did try installing this on my local machine and everything seems to be working as expected, pointing tot he same database (SQL SERVER).  Also used the solution to compile and run development modules; that works. All these local stuff worked great until I tried deploying this on a 'real' environment...

**Comment by leigh-pointer** [comment]
Have you diabled WebDAV?

**Comment by tranpl** [comment]
Let me try, its currently enabled..

**Comment by tranpl** [comment]
> Have you diabled WebDAV?

It works!!! thank you

**Comment by leigh-pointer** [comment]
That is great can you close this with "Answered "
