### ISSUE TITLE
Create more permission options

### ISSUE THREAD

**Issue by trouble2** [oqtane/oqtane.framework#2695]
Wouldn't it be great to add extra permission options, next to 'view' and 'edit'.
Like 'add' and 'delete'...
I think this is one thing that is missing from dnn.
I believe Evoq has some extra permissions built in as well.

**Comment by sbwalker** [comment]
This already exists in Oqtane. A module can implement as many types of permissions as it needs.

**Comment by leigh-pointer** [comment]
@trouble2 In your module solution, go to the client project and in the class ModuleInfo add to the `new ModuleDefinition` 

`PermissionNames = Oqtane.Shared.PermissionNames.View + "," + Oqtane.Shared.PermissionNames.Edit + ",Add,Delete"`

This will add two extra permissions **Add** and **Delete**

**Comment by W6HBR** [comment]
@leigh-pointer I just tried this for one of my modules and the additional permissions do not appear.  It compiles fine with the additional code you outlined and runs fine, just no additional permissions to select from under "Manage Settings", "Permissions" within the module.  Are there any other requirements that need to be added to my module?  FYI - this is a module that was created prior to the new permissions features being added to the core.

**Comment by leigh-pointer** [comment]
@W6HBR This is a bug with.  Prior 3.4.0 the code mentioned above would add the custom permissions to the permissions table.
I will raise this as a new Issue.

@sbwalker seems that this slipped the net with the Permissions migration.

**Comment by sbwalker** [comment]
fixed in #2698
