### ISSUE TITLE
Issue when adding custom Permissions from External Module

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2696]
When In the module solution, in the client project , modifiying the class ModuleInfo and adding to the `new ModuleDefinition`

`PermissionNames = Oqtane.Shared.PermissionNames.View + "," + Oqtane.Shared.PermissionNames.Edit + ",Add,Delete"`

This code no longer addeds the custom Permissions.

**Comment by sbwalker** [comment]
The problem was actually related to the filtering logic for the ModuleDefinition model which was added in 3.4.0
