### ISSUE TITLE
RichTextEditor component should support raw and rich entry modes

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#270]
Currently the ability to switch to a raw text entry mode is implemented in the Html/Text module however it makes more sense if this was encapsulated in the RichTextEditor component so that any module could take advantage of it without any additional effort.

**Comment by ADefWebserver** [comment]
Just a few notes to whoever pick this up...

The Quill control uses a "[Delta](https://quilljs.com/docs/delta/)" format that *on purpose* will not always display the exact HTML that is *passed to it*. It will however *emit* valid HTML that can be saved to the database (and displayed to the end users).

The reason for this is that it is impossible to allow end users to enter HTML text and not have hackers have a field day with cross site scripting attacks.

Therefore, any future *RichTextEditor component* that allowed HTML input must have the ability to allow *HTML Text Input* to be turned off in the cases where non-Administrators need to create Rich Text.
