### ISSUE TITLE
404 on custom theme css file.

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#271]
When trying to create a new theme within the framework (not a separate module), I created a new css file and placed it in the wwwroot folder (this is where the custom theme module places it). When the page loads, the css file reports a 404. 

Where should the css file be placed? 

![theme-404](https://user-images.githubusercontent.com/11261164/76426866-fd4f8700-6381-11ea-9efc-88ef39053543.PNG)

**Comment by sbwalker** [comment]
#278 deals with the case where a page does not exist ( or a user does not have permission to view the page ). It will log the issue to the event log and it will redirect the user to the home page of the current site.

**Comment by sbwalker** [comment]
If you look at the bottom of this custom theme file: 

https://github.com/oqtane/oqtane.theme.custom/blob/master/Theme1.razor

You will see the call to AddCSS(). This is how a theme tells the framework how to find a CSS file.

**Comment by sbwalker** [comment]
My apologies... that was the wrong example. You should look at:

https://github.com/oqtane/oqtane.framework/blob/master/Oqtane.Client/Themes/OqtaneTheme/Default.razor

You will see the call to IncludeCSS(). This is how a theme tells the framework how to find a CSS file.

**Comment by mikecasas** [comment]
As always, thanks for your response. I did see this example, but after searching the repo for the Theme.css file, I see that it resides in the wwwroot of the Server project. Which makes sense now, but I was looking to place the css file in the wwwroot of the Client project.
