### ISSUE TITLE
New SiteMap functionality missing Settings

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2718]
I have started doing some SiteMap intergration and found that the settings are not populated.  My requirement is to read the settings of the module and act accordingly.  My first call of action was if I want the Sitemap to be generated for this module.

**Comment by thabaum** [comment]
I will be going through this myself 100% to submit PR's relating to all SEO and Analytics we can put for in-house recipes developers should enjoy.

Pretty much anything to do with multi-sites and SEO I am going to dial in prior to any major commitments.  I really am hoping V4 is going to be the one I can get started with for a few projects.  I will be double checking anything I can while in different areas getting familiar with the latest code updates and functionality.

Any wishlist items that you feel are a must for Oqtane and fit the project mission so I don't waste time please submit them now ;)

**Comment by sbwalker** [comment]
@leigh-pointer If you browse to https://www.oqtane.org/pages/sitemap.xml you can see that a sitemap.xml is being generated. By default it generates entries in the sitemap for the publicly accessible pages on a site. It also has an interface which a module can implement which allows a module to publish its own entries as well (as long as the module instance is accessible on a publicly accessible page on a site). The Blog module contains an example of how to implement the interface: https://github.com/oqtane/oqtane.blogs/blob/master/Server/Manager/BlogManager.cs - which is how the entries on https://www.oqtane.org are being generated.

**Comment by leigh-pointer** [comment]
@sbwalker I have successfull implented the Sitemap interface, that was ok but when I analyize the module Parameter there are no Settings.  It would be nice to have the Settings popualted on the moduel.Settings property.  If your oke with it I can create the PR

**Comment by sbwalker** [comment]
You are referring to the Module object which is passed by the GetUrls() method to the module - it contains the Module information but not the Module Settings (even though the model has a Settings property). Yes I think it makes sense to populate the Settings property before passing it through the interface.

**Comment by leigh-pointer** [comment]
@sbwalker would you like me to do this change ?

**Comment by sbwalker** [comment]
fixed in #2727
