### ISSUE TITLE
Localization Language Resource Files SharedResources and Oqtane Component Resources

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2732]
I am going through the language resource files as I wanted to update the Logs Detail page to say "Return to Logs" or "Return" or "Back" instead of "Cancel"

Since it is at the bottom on it's own line I figure there is room to include more description of the buttons function for clarity.

I figure since I am here I will probably look at the rest of them as components and modules for Oqtane should be able to share a lot of things so that you edit one file and it keeps things fairly simple to create and manage UI/UX.

Issues for example for the logs are as follows:

The naming conventions for the resources are not consistent, with some names using a period as a separator and others using a space.

There are duplicate resource names in the component logs module "index.resx" and "details.resx" files, which could lead to confusion when accessing these resources.

I am sure they all have a purpose but these are misleading to anyone looking for strict coding practices to follow.  It is very loose and does not keep with a standard.  Which is ok for a vendor component but not the framework itself in my opinion.

I was also thinking about adding the following to the SharedResources.resx

- 	Home		
- 	Close		
- 	OK		
- 	Apply		
- 	Select		
- 	Next		
- 	Previous		
- 	Submit		
- 	Refresh		
- 	Back		
- 	Return
-       New
-       View
-       Confirm
-       Error Message
-       Success Message

Since these are commonly used and we could of just used "Return" for example instead of "Cancel" and not bother with the "Return to Logs" resx speeding up development while maintaining UI/UX experiences.

Any thoughts on this I will put together a few PR's for review and then move forward so I can rest assured the framework will have these resources stock while developing on it.

We can always add the `:` to the end of a word however maybe there is a use case for having `message` and `message:` however it looks a bit redundant to me to have both for example.

The one in the logs that catches my eye the most is this one:
  ```
  
  <data name="Error.Log.Load" xml:space="preserve">
    <value>Error Loading Log</value>
  </data>
  
  and
  
    <data name="Error Loading Log" xml:space="preserve">
    <value>Error Loading Log</value>
  </data>
  
```  

Both dont follow C# standards which would be `ErrorLoadingLog` I believe and all our resource files should adhere to this going into the Framework, A module developer should and can do what they please.  But the Framework should follow more stricter guidelines or it looks sloppy and confusing.

I would say the `.` maybe help for extending that one language resource such as for help text.  But even that maybe should be `ErrorLoadingLogHelp` or `ErrorLoadingLogDescription` or `ErrorLoadingLogTitle` etc... However I don't mind `ErrorLoadingLog.HelpText` I just wish in this area it can stay uniform and inclusive to all common use cases in the Framework for clarity and ease of development.

Maybe I am missing something here so please enlighten me further or straighten me out so I can get cruising down the development path.  Bottom line is no way to have "back" without having it added to every module resource file along with a few other common ones we should have included fresh off the line.

**Comment by sbwalker** [comment]
Changing the key values for items in the default RESX files would be a breaking change for all translations which have been created to date (there are many translations in the Oqtane.Translations repo). So I would not be in favor of this change.

**Comment by thabaum** [comment]
I understand not changing what is existing, it's a shame it was added to begin with in respect to not keeping it in a standard format.  But I understand, no biggy right.

I still am advocating in favor of adding Home
```
Home
Close
OK
Apply
Select
Next
Previous
Submit
Refresh
Back
Return
New
View
Confirm
Error Message
Success Message
```

To SharedResources.resx at least most of these, and then changing the Log Details button and other buttons in the administration pages to reflect what you are going to do.  

So let's drop the issues of "changing of what is there" as I got that would be unacceptable breaking changes from the start. I am a little disappointed in it being here in this way, but can move on working through it as confusing as some of it may be, it is what it is now.

My issue and concern is giving basic language resources for all common functionality within the framework and module development.  So adding the ones suggested will help here avoid having other more confusing ones created later and with what is already present covers most use cases.

The cancel button here for example, it confused the hell out of me and I am a developer that works on Qqtane:

![image](https://user-images.githubusercontent.com/13577556/230196662-68cef242-06f8-4eac-ae59-aeb090932879.png)

**Comment by sbwalker** [comment]
Since the earliest versions of Windows, the Cancel paradigm has been used as the terminology for closing modal dialogs. So I would prefer to continue using Cancel for this scenario in Oqtane. If you do not like the terminology used in Oqtane you could certainly create your own translation (this is precisely the purpose of localization).

We could certainly add a few more "standard" actions to ShareResources.rex so that they are available to developers without having to declare them in their own resource files.

**Comment by thabaum** [comment]
The Cancel button typically allows the user to cancel a current action or transaction, such as filling out a form or making a purchase. When the user clicks on the Cancel button, any changes made to the current form or transaction are discarded, and the user is returned to the previous screen or page. The Cancel button is often used as a safety mechanism to prevent accidental or unwanted actions.

    The Return button, also known as the "Save and Return" button, is often used in situations where the user is completing a form or task and wants to save their progress and return to it later. When the user clicks on the Return button, any changes made to the current form or task are saved, and the user is returned to the previous screen or page. This button is commonly used in situations where the user may need to step away from the task temporarily or complete the task in multiple sessions.

    The Back button allows the user to navigate backward through the pages or screens they have previously visited. It is commonly used to allow the user to retrace their steps and correct mistakes or make changes. The Back button can also be used to return to a previous state or view, such as returning to a previous search result or returning to a previous step in a process.
    
    I was in favor of "Back" or the UX is downgraded.
    
    again I was seriously looking for something to do or some action I performed.  I thought I was on a different page than "Viewing" logs and wanted to go "Back to Dashboard" which is what I say it should say since there is room for it on it's own line for clarity.

**Comment by thabaum** [comment]
> Changing the key names for items in the default RESX files would be a breaking change for all translations which have been created to dat

@sbwalker would adding  a "Delete" function to the event log event details page be something to consider to give it an action?

**Comment by sbwalker** [comment]
@thabaum I am not sure I understand how your Event Log question relates to Localization? Could you please explain?

**Comment by thabaum** [comment]
@sbwalker  Well this issue went off topic a bit, so instead of starting a new discussion I felt like asking here.  The event log is what brought the Localization issue to my attention.  So your point you made got me thinking how to make that page more understandable giving it an action to cancel.  Another idea I have is adding a notes section and save to archive so you can track issues and how you may have resolved them for future reference.

Really this should be another issue I am not trying to merge the two.  Should I start a thread in discussions 'Ideas" relating to this specific issue?

**Comment by thabaum** [comment]
@sbwalker Well, never mind man this is not related 100% to Localization so no need to answer.  Enough said here in relation to the Localization issue topic, my original issue message was not clear enough.  My bad causing any confusion along the way.  Must of been a late night... no worries.  The admin panel for logs is fine as is.  I should focus more on building my own customization's.

My apologies.

Hoping the PR I created shines more light on what the original issue and proposed solution I had in mind originally.
