### ISSUE TITLE
host user can forbid access to module for himself, no way back 

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#275]
If I press Save now, Files module is lost and I can't reverse this action.
![image](https://user-images.githubusercontent.com/7838468/76431273-a366b580-63b1-11ea-878b-6fb7be3afa51.png)

**Comment by sbwalker** [comment]
the fix here should be to prevent a host user from removing the Administrators role from the permissions ( if the permissions grid component does not handle this already ). A user should never be able to to remove the Administrators role from any permission.

**Comment by sbwalker** [comment]
fixed in #279
