### ISSUE TITLE
Sitemap Url location could possibly create indexing issues.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2750]
Reading up here at [Sitemaps.org](https://www.sitemaps.org/protocol.html#location) we could potentially have an issue with the way search engines naturally index site pages.

```
Sitemap file location

The location of a Sitemap file determines the set of URLs that can be included in that Sitemap. A Sitemap file located at http://example.com/catalog/sitemap.xml can include any URLs starting with http://example.com/catalog/ but can not include URLs starting with http://example.com/images/.

If you have the permission to change http://example.org/path/sitemap.xml, it is assumed that you also have permission to provide information for URLs with the prefix http://example.org/path/. Examples of URLs considered valid in http://example.com/catalog/sitemap.xml include:


http://example.com/catalog/show?item=23

http://example.com/catalog/show?item=233&user=3453

 Note that this means that all URLs listed in the Sitemap must use the same protocol (http, in this example) and reside on the same host as the Sitemap. For instance, if the Sitemap is located at http://www.example.com/sitemap.xml, it can't include URLs from http://subdomain.example.com.

URLs that are not considered valid are dropped from further consideration. It is strongly recommended that you place your Sitemap at the root directory of your web server. For example, if your web server is at example.com, then your Sitemap index file would be at http://example.com/sitemap.xml. In certain cases, you may need to produce different Sitemaps for different paths (e.g., if security permissions in your organization compartmentalize write access to different directories).

If you submit a Sitemap using a path with a port number, you must include that port number as part of the path in each URL listed in the Sitemap file. For instance, if your Sitemap is located at http://www.example.com:100/sitemap.xml, then each URL listed in the Sitemap must begin with http://www.example.com:100.
```

Oqtane currently creates sitemap as follows:  `https://www.oqtane.com/pages/sitemap.xml`

I do not currently have a PR for this as I just noticed this while testing my other related PR.  

Not sure when I will get around to this or really how exactly @sbwalker would like to handle it.  Could we make it so we can edit it in site settings as desired?

**Comment by sbwalker** [comment]
This would not be a problem if you manually submit your sitemap Url to the Google Search Console or the ping method (https://www.google.com/ping?sitemap=FULL_URL_OF_SITEMAP)... however it would be a problem if you were relying on the Google search indexer to auto discover your sitemap - in which case you need to include the Url in your robots.txt file.

**Comment by thabaum** [comment]
https://github.com/sitemap

It would be nice if Oqtane created a page like Github's for example.  A human readable sitemap in root directory that shows all pages you can visit.

I am not relying on Google for nothing but burying me... I lost all hope there, although they have been forced to change their ways by Congress, I believe now days the "speed" of Googles searches are irrelevant as technology has caught up enough to where it don't really matter anymore.

I generally use them all, so it is important that sitemaps work for all search engines, not just Googles.

**Comment by sbwalker** [comment]
I was referring to an autogenerated page that would be part of every site which is created. It would differ from the sitemap.xml output as it would probably need to include all pages which the current user has access to (not just publicly accessible pages) and it would not contain the module-specific items from the ISiteMap interface.

**Comment by thabaum** [comment]
How does Oqtane handle Robot.txt?  Does it auto-generate this by chance?  Seems like some modules may want their own sitemaps included for something like an eCommerce module potentially or even the Blog.  It would be nice to have the Robot.txt updated as needed to reflect any sitemaps generated by Oqtane or Modules for search engines to naturally crawl Oqtane Framework and modules pages added with no work to an end user other installing and setting up a module or Oqtane Framework.  I have yet to explore here but something that I think makes sense.

**Comment by sbwalker** [comment]
Oqtane does not generate a robots.txt - however you can easily create one manually for your installation

**Comment by sbwalker** [comment]
Closing this as it is not a reproducible issue
