### ISSUE TITLE
How to turn off Antiforgery in a Webhook api

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#2756]
I have a Webhook for receiving payment updates from Stripe. I get this error when Stripe sending updates to the webhook api:

`Oqtane.Security.AutoValidateAntiforgeryTokenFilter: Error: [Oqtane.Security.AutoValidateAntiforgeryTokenFilter] AutoValidateAntiforgeryTokenFilter Failure For https://localhost:44323/api/webhook`

Is it possible to turn off the AutoValidateAntiforgeryTokenFilter for this api-controller?

Best regards
Bjørn-Even

**Comment by sbwalker** [comment]
Have you tried to use the standard [IgnoreAntiforgeryToken] attribute on your custom API method?

**Comment by sbwalker** [comment]
I am glad you were able to find a simple solution
