### ISSUE TITLE
Upgrading and House Keeping of External Module

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2758]
When running a module upgrade I have found an issue with removing files.  The only way I can see to do this is with a migration class but when removing files from the file system it does not execute in a release environment.  In design files are deleted but then the framework needs to restart and I am guessing that is the problem.

There has been talk of a IDelete interface, I think we also need an IUpgrade interface.  I have tried with IUpgradeManager but that is framework tied.

**Comment by sbwalker** [comment]
The IInstallable interface is intended to be utilized for any upgrade logic which your module requires - can you please provide more details on your scenario.

**Comment by leigh-pointer** [comment]
@sbwalker Thanks, I have now used the IInstallable interface

**Comment by sbwalker** [comment]
@leigh-pointer are you saying that there is an issue deleting files from within the IInstallable interface?

**Comment by leigh-pointer** [comment]
@sbwalker yes, but seems only to be a problem when the module is compiled and deployed. Code executes fine in dev mode.

**Comment by leigh-pointer** [comment]
@sbwalker just .css and .js

**Comment by sbwalker** [comment]
Deleting CSS or JS files should not trigger an app restart when running on .NET Core - this is strange behavior. Are there any more details about the runtime environment - ie. is this Azure or self-hosted?

**Comment by leigh-pointer** [comment]
@sbwalker so here is my delete code:

```
        protected void RemoveFiles()
        {
            WebApplicationBuilder builder = WebApplication.CreateBuilder();

            string packagename = "StudioElf.DynamicForm";
            string[] packages = Directory.GetFiles(Path.Combine(builder.Environment.ContentRootPath, Constants.PackagesFolder), packagename + "*.log");
            if (packages.Length > 0)
            {
                packagename = packages[packages.Length - 1]; 
            }

            if (!string.IsNullOrEmpty(packagename))
            {
                // use manifest to clean up file resources
                List<string> assets = JsonSerializer.Deserialize<List<string>>(System.IO.File.ReadAllText(packagename));
                assets = assets.Where(str => str.StartsWith("\\wwwroot") && (str.EndsWith(".css") || str.EndsWith(".js"))).Reverse().ToList();
                foreach (string asset in assets)
                {
                    // legacy support for assets that were stored as absolute paths
                    string filepath = asset.StartsWith("\\") ? Path.Combine(builder.Environment.ContentRootPath, asset.Substring(1)) : asset;
                    if (System.IO.File.Exists(filepath))
                    {
                        System.IO.File.Delete(filepath);
                    }
                }
            }
        }
```

**Comment by leigh-pointer** [comment]
```
        public bool Install(Tenant tenant, string version)
        {
            if(version == "1.0.6")
            {
                RemoveFiles();
            }           
            return Migrate(new DynamicFormContext(_tenantManager, _accessor), tenant, MigrationType.Up);

        }
```

**Comment by sbwalker** [comment]
@leigh-pointer my guess is that your code for obtaining the ContentRootPath does not work consistently across environments. In development it may be getting the expected location, but in production it is not.  If you added logging to your code you would be able to determine if the value of ContentRootPath is different than what you expect. 

I am not sure why you are using WebApplicationBuilder to obtain the ContentRootPath? In all areas of the framework it uses IWebHostEnvironment.

**Comment by leigh-pointer** [comment]
@sbwalker using IWebHostEnvironment now
