### ISSUE TITLE
Module management error when you forbid access to all

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#277]
Saving of this causes unhandled exception and module cannot be managed. 

![image](https://user-images.githubusercontent.com/7838468/76440470-2f7eda00-63be-11ea-86ce-2c924c5d3c93.png)

**Comment by chlupac** [comment]
It seems to be a bigger problem, permissions get lost sometimes between save and load same module.

**Comment by sbwalker** [comment]
The permission grid component needs to prevent users from locking themselves out.

**Comment by chlupac** [comment]
try to set permission here, save, load, set , save ...

**Comment by sbwalker** [comment]
I am able to reproduce this error as well. Very strange. I will try to track it down.

**Comment by sbwalker** [comment]
The strange behavior was an asynchronous issue where the nested component was trying to render some content before the outer component was finished loading it. I also modified the permissions grid to prevent removing the Administrator role and prevent denying access to All Users and Registered Users

**Comment by chlupac** [comment]
Good work.
