### ISSUE TITLE
Compiling a module deletes oqtane.*.dll files from  \oqtane.framework\Oqtane.Server\bin\Debug\net6.0\ folder

### ISSUE THREAD

**Issue by Tony20221** [oqtane/oqtane.framework#2778]
I created a module using the Module Creator. It created a folder and a solution for it which I opened in another instance of VS  2022.
I have Oqtane opened in an instance of VS. When I rebuilt Oqtane it creates Oqtane.Client.dll, Oqtane.Server.dll and Oqtane.Shared.dll in the \oqtane.framework\Oqtane.Server\bin\Debug\net6.0\ folder of Oqtane. So far so good.

When I compile the module, it deletes those files (or a combination of them) and I get compile errors like:
Error	CS0246	The type or namespace name 'Oqtane' could not be found (are you missing a using directive or an assembly reference?)

I have repeated this process several times and dlls always get deleted.

**Comment by leigh-pointer** [comment]
**Try using one instance to VS.**
open you module
Add an existing project, and that should be the Oqtane Server project.
Set the Oqtane Server project as you start up project
In the solution Configuration Properties, uncheck build Oqtane.Server

![image](https://user-images.githubusercontent.com/9447612/235843464-dbf0dbf5-0182-45fe-ad51-db4c83d74bc3.png)

Now when you run the solution your module will build and run.

**Comment by Tony20221** [comment]
Thanks.

**Comment by leigh-pointer** [comment]
@Tony20221 pleased to have helped, can you close as Answered please
