### ISSUE TITLE
Enhance - User Profiles:  Validation property to include a RegExp

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2789]
Issue:
User Profiles Allow Any Characters in Zip Code

Solution:

Conditional Validation Regex setting for profile properties.

Notes:

You can enter "dfas" and it accepts this as a zip code from a user.  If using this field for other purposes that only expect integers this could cause errors.

Looks like some Regex action is needed here and .NET 7 has some improvements for this I believe maybe worth taking a look to see if they can apply here and in other areas of Admin pages to help validate the information where users input data.

Phone Number also needs love in the Profile

**
![image](https://user-images.githubusercontent.com/13577556/236284764-896d470e-93e0-4d9b-b004-4e15f86a005d.png)
**

**Comment by thabaum** [comment]
@sbwalker looking at the logic it must be related to the User Profiles area, maybe give me some "what you expect" advice here and we can see what we can do to provide a solution or two I can doctor this up, unless this is being worked on.

**Comment by sbwalker** [comment]
The default user profile includes a "Postal Code" not a "ZIP Code". Postal Codes vary by country - ie. they are numeric in the U.S. but alphanumeric in Canada. 

The Options property allows you to specify a comma delimited set of options for the user to choose from. 

The addition of a Validation property to Profile to include a RegExp would be a useful future enhancement.

**Comment by sbwalker** [comment]
Conditional validation and dependency between profile fields would require a completely different solution and level of effort to accomplish, and although I understand the use case, I would not be in favor of prioritizing it at this time. If you need more complex functionality for your user profile in your own sites, you can obviously create your own profile management component and use it instead of the default version in the framework.

**Comment by thabaum** [comment]
Looks like something you want to think about and in the future so I will leave this open for you to close anytime or when you're ready to ignite this enhancement.

**Comment by sbwalker** [comment]
done in #2843
