### ISSUE TITLE
Enhance - Admin Pages: Smooth Scroll Up To Top Dashboard Page Notifications Similar To Site/Index.razor

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2790]
Issue:

Admin dashboard pages for example User Profile Save notification is at top of page, if a large profile page and a smaller screen or window a user may not see that the action was performed.  There is a notification alert sometimes high above a scrolled down screen with many options and user input on devices with small screens or small windows have a hard to getting these visuals to their attention.

This works as expected in Site\Index.razor page.

Solution:

Create all pages in the Oqtane Framework Admin Dashboard with notification actions at the top use the following from comment below suggested by @sbwalker :
> A very simple solution for addressing this UX concern can be found in Site Settings (Oqtane.Client\Modules\Admin\Site\Index.razor) in the SaveSite() method:
> 
> ```
> await interop.ScrollTo(0, 0, "smooth");
> ```
> 
> this is a JS Interop method which scrolls the browser to the top of the page and enables the message to be visible to the user.

**Comment by vnetonline** [comment]
I think rather then the notification at the top of the module it should be a toast down the bottom right corner which should show the notification

**Comment by thabaum** [comment]
I am not sure but is there a "IToastNotificationService" in Oqtane Framework?  Maybe we can put a module setting that enables/disables the different types of toasts/notifications along with some simple configurations (top/bottom/time displayed/user close).  Then this functionality would be something that can be streamlined into any module on any page for a developer with out having to customize it in the back end?  Does this sound like an idea we can build upon?

**Comment by sbwalker** [comment]
A very simple solution for addressing this UX concern can be found in Site Settings (Oqtane.Client\Modules\Admin\Site\Index.razor) in the SaveSite() method:

```
await interop.ScrollTo(0, 0, "smooth");
```

this is a JS Interop method which scrolls the browser to the top  of the page and enables the message to be visible to the user.

**Comment by vnetonline** [comment]
@thabaum which Admin Pages are you referring to i have implemented the change ion the User Profile screen 

Let me know the Admin Pages and I will add to those pages and package them up in one pull request 

```c#
await interop.ScrollTo(0, 0, "smooth");
```

**Comment by sbwalker** [comment]
Closing as there are no specific action items in this issue other than the user profile UI which has been resolved
