### ISSUE TITLE
Issue - Oqtane Theme: Navigation does not switch to a hamburger menu when expected.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2791]
The Hamburger Menu in Oqtane Theme is not switching when a large number of top menu pages top menu are present causing user options to drop below/above behavior in the navigation.

Here are the way things change depending on window size currently:

![image](https://user-images.githubusercontent.com/13577556/236294895-6d1e3f5c-513d-48b0-bad5-621a8126cdcc.png)
![image](https://user-images.githubusercontent.com/13577556/236293717-c65ed95c-2dcf-4788-991a-79aea2482782.png)
![image](https://user-images.githubusercontent.com/13577556/236293798-1fed230c-58c9-4d20-95d2-2049a87d30b6.png)
![image](https://user-images.githubusercontent.com/13577556/236293849-08d50c49-0b11-4cfc-a00b-0a3774244970.png)

**Comment by sbwalker** [comment]
Responsive design is difficult - especially in scenarios with dynamic content. Please keep in mind that the default Oqtane theme is primarily intended for local development. If you are building a custom site I would assume that you would want to create a custom theme which matches your branding and creative requirements. That being said, if you want to create some custom CSS which adapts the horizontal menu to handle an unlimited number of top level menu options please feel free to submit a PR.
