### ISSUE TITLE
Enhance - Site Settings:  Ability for Host to switch sites in Site Settings for all sites hosted

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2792]
Maybe a bit to implement but it would be nice to select sites hosted in the Oqtane Framework in the admin "Site Settings" page to allow modifying sites quickly.  Maybe even an "apply to all button" for things like themes.

Potentially a button that allows you to modify multiple sites with basic options you may want to apply to a number of sites that can be shared without bugging out a site only a Host account can perform or an admin with permission for more than one site.

This could potentially apply to more than just this one area such as:  Profile Management, Role Management.

![image](https://user-images.githubusercontent.com/13577556/236300171-18980943-cdeb-489d-a41e-c11d1334a1c2.png)

**Comment by sbwalker** [comment]
The Oqtane Server API cannot be used across different tenants - it much be used in the context of a specific tenant. This is by design for security purposes. So it is not possible to do what you are suggesting, and the framework will not be modified to accommodate this use case.
