### ISSUE TITLE
Enhance - Site Management:  Ability to delete sites.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2794]
Issue:
Currently under site management you can "edit" and "browse" a site, however no option to "delete" a site.

Solution:
Add the "Delete Site" button and logic to site management from site settings.

Notes:
A default site should not be allowed to be deleted and the current site maybe should take over as default site if the default is deleted.

If a misconfiguration of a site administrators currently are unable to "Delete Site" due to potentially no access to site settings.

**Comment by sbwalker** [comment]
The Oqtane Server API cannot be used across different tenants - it much be used in the context of a specific tenant. This is by design for security purposes. So it is not possible to do what you are suggesting, and the framework will not be modified to accommodate this use case.
