### ISSUE TITLE
Issue - Site Alias: When adding an alias with "Http://" it resolves "https://http//site.com"

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2795]
Issue:

When adding an alias with "Http://" it resolves "https://http//site.com"

Notes:

it looks like the :// is removed but not the Https or Http.  I remember working on this in the DNN Journal Module fixing the link types of posts.  Logic is there to handle this in similar way as it was changing HTTPS links to HTTP.  If this is hard set to be HTTP, should Oqtane Framework remove the HTTP:// and HTTPS://?

As shown in my other issue #2793 you can see the screenshots relating to the issue.  The alias is Http://domain.com as expected in the view so it is being saved to the database correctly as typed, however when resolved to navigate with the router it is doing some work on it that makes it created properly to be a valid url.

**Comment by sbwalker** [comment]
A protocol (ie. http:// or https://) is not valid when entering an alias name. The system should automatically remove the protocol if it is included, prior to saving it to the database.
