### ISSUE TITLE
Issue - Host Profile:  When visiting sites other than default Host user is unable to access its user profile.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2796]
Issue:  

When visiting sites other than default Host user is unable to access its profile due to limited access to the Host Profile Folder.

Reproduce by trying to access the host profile from another site other than the initial default site.

Notes:

Possibly something to do with a Host not necessarily being included as a member of a site so the folder is not getting permissions for the Host user to access that folder since it was created on another site.  Maybe this is expected behavior, or the host should access it's profile folder (profile) from any site related to the host.  Or the host needs to create a new profile for each site it plans to be an active part of.  Same would go for admins.  

This is a multi tenant issue so I feel the complexity here.  Site Groups users should be allowed to share the profile from site to site.  I have not tested other users and a "Site Group" type of setup yet.  I do plan on building a project site that does allow users to move between different sites on one Oqtane Framework instance with heir profile information following them and not having to log into each site using wildcard alias sub.domain.com, subsite2.domain.com, subsite.subsite.domain.com... so seeing this work as expected is very important to me right now.  

I had seen this issue while looking into another issue we resolved with accessing sites added.  I want to be sure this is still an issue but I cannot reproduce currently as I cannot access other sites added due to an alias issue in the framework potentially in latest release.  I have not heard yet if this is just me having the alias issue locally or something needs fixed.

**Comment by sbwalker** [comment]
The Shared Tenancy configuration (ie. shared database) supports sharing users across sites - but only from an authentication perspective (ie. login). Profile information is not currently shared, it is maintained independently per site. The concept of a Site Group does not currently exist. This feature will be considered in the future - but definitely not in the next release, as it will require thorough analysis to determine the appropriate approach based on the architecture.
