### ISSUE TITLE
Sites should be created based on ISiteTemplate

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#281]
I'm working on this now. Thinking about some helper methods and extensions to build site easily and refactoring friendly, without need of magic strings.
but type of module is liitle bit complicated and i'm not sure is how to describe module typeof(what?).Name

Next step can be Site installation wizard, where user can set options and select features to install.

```c#

public static void AddPage(this Site site, .........)
{
}
public static void AddModule<TModule>(this Page page, ....) where TModule is IModule
{
}
```
```c#
    public interface ISiteTemplate
    {
        void CreateSite(ISite site);
        string Name { get; }
        ??? Options {get;}
    }
```

**Comment by sbwalker** [comment]
So the approach I suggested yesterday is the following:

"What I am envisioning here is a simple interface ( ie. ISiteTemplate ) which has a Name property and a generic method for CreateSite(Site site). Within this method a developer would have full control over the site creation process. They could create any entities they desire ( ie. users, roles, pages, modules, folders, files, jobs, etc.... ). During installation and site creation the UI would provide an option for the user to choose from a list of templates which are available ( based on classes implementing ISiteTemplate )."

To elaborate more on what I started to implement... this would be an extensibility option and would function very similarly to Modules or Themes. Basically a developer could create a class which implements ISiteTemplate. During the install or site creation the system would find all of the custom classes which implement ISiteTemplate and would display a list of their Names in the UI. When a user selected a Name and chose to create a site, the system would create the Site entity and would then dynamically instantiate the class and call the CreateSite(Site site) method associated to the Name. Inside the CreateSite() method, the developer would have the ability to call any Repository method it wants - ie, AddPage(), AddRole(), etc... Basically for the default site template all of the code which is currently buried in the SiteRepository constructor would be moved to the CreateSite() method of a new class which derives from ISiteTemplate. And developers would have the freedom to create additional site templates as needed.

**Comment by sbwalker** [comment]
So I am not thinking of an interactive site creation wizard - I think that would be a totally different use case.

**Comment by sbwalker** [comment]
To provide a bit more context.... the focus of Oqtane is to allow developers to build web applications more productively. The requirement is that a developer may want to create a custom theme, some custom modules, and a custom site template. They would package these with Oqtane as a "distribution". When a user installs the system it would automatically install of the modules, theme, and site template to create a custom application for a specific business purpose. 

This use case is much different than a CMS/SiteBuilder where a user builds their system interactively by creating pages, adding content, applying themes, etc... Oqtane is not trying to be a CMS ( even if it has some CMS capabilities )

**Comment by chlupac** [comment]
I share this point of view, this is exactly what I think. Wizard is only idea, not necessary.

**Comment by sbwalker** [comment]
#294 includes enhancements for site templates. To provide some context:

- an ISiteTemplate interface was introduced which allows developers to create custom implementations. It contains a Name property and a CreateSite() method. The CreateSite() can contain any custom logic which may be required to configure a site.
- a DefaultSiteTemplate was created which creates default content for a site ( currently pages, modules, and a site logo )
- there are "core" entities which must be created for every site and these are still handled in the SiteRepository class 
- during the initial Oqtane installation there is no ability to choose a site template. This is on purpose as someone creating a distribution around Oqtane would want to force a user to use a specific site template during installation. This is possible by adding a "SiteTemplate": "{Your Fully Qualified Class Name}" in the appsettings.config. If you do not provide a config value the system will use the DefaultSiteTemplate.
- when creating a new site after installation, the Add Site UI has an option to choose from a list of available site templates.
- ad part of this enhancement all hardcoded permissionstrings were replaced with proper permission collections
