### ISSUE TITLE
Site alias http://localhost:44357/admin blocks administration of root site

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#288]
![image](https://user-images.githubusercontent.com/7838468/76773247-7b58c700-67a2-11ea-9ac1-8512fc00104b.png)

**Comment by sbwalker** [comment]
So you are saying you created a new micro-site with an alias of "admin" and you are no longer able to navigate to the "admin" page in the root site. In the event of a conflict ( ie. when there is both an alias AND a page with the same url route configured ) the system prioritizes the matching site over the matching page. I believe Mike Casas brought this up previously.

**Comment by sbwalker** [comment]
There are 2 possible approaches here:

1. Attempt to validate that aliases do not conflict with pages and vice versa.

or

2. Introduce a different url route pattern for micro-sites ( ie. www.domain.com/site/x ) where "site" is a static value added by convention which designates that the url is a micro-site. 

There are pros and cons to each solution, but most likely #2 is the better option as it is more explicit. The only downside is that a user would not have full control over their Url.

**Comment by mikecasas** [comment]
Maybe you can add it to the v.next road map. For now we just need to be aware of the possible collisions. 

Just wondering...what does a micro-site mean to you? Is it a full-fledged site/application with just different routing, or does it have a different connotation?

**Comment by chlupac** [comment]
ad 1. a little more complicated verification, but can be realized
ad 2. better solution for system stability, but downside is more complicated site url.

**Comment by sbwalker** [comment]
@mikecasas a micro-site is a full-fledged site with its own alias, content, roles, users

**Comment by mikecasas** [comment]
That's what I thought, thanks!

**Comment by sbwalker** [comment]
Maintaining current behavior for V1
