### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2882]
Once 4.0.0 is released there should be some focus on documentation which is much needed for this project. 

There is good discussions on the built features but hard to look for so a sprint or two should be dedicated to documentation.

The video series is now outdated and is not consistent with the new features for example sql scripts rather than migrations.

**Comment by sbwalker** [comment]
I totally agree that documentation could be much better - unfortunately it has been difficult to get the community to contribute in this area. DNN had this exact same problem so we eventually hired a tech writer to make progress.
