### ISSUE TITLE
[ENHANCE] - Update default module template to Oqtane 4.0.0 targeting .NET 7.0

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2887]
No, the default templates have not been updated yet... please go ahead and update them if you have time. Note that the Resources should not be specified as Site level in the templates.

_Originally posted by @sbwalker in https://github.com/oqtane/oqtane.framework/discussions/2848#discussioncomment-6020906_

**Comment by sbwalker** [comment]
resolved in #2888
