### ISSUE TITLE
Themes - Moving from Page to Page whilst firing OnAfterRenderAsync

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2912]
When the OnAfterRenderAsync event on a page is fired the first time the firstRender is true.  When navigating off the page and returning to that page the firstRender is not true when it should be.  

This has been working and now has stopped working.

**Comment by sbwalker** [comment]
I am guessing you moved your Resources declaration to ThemeInfo? If so, these Resources are handled by the ThemeBuilder component - and the ThemeBuilder component is not created/disposed on every page navigation - it is created once when the application starts up and is reused for the life of the application. So the behavior you are seeing is valid - firstRender will only be true on the initial page load and from that point on it is false. 

In contrast, if your Resources are declared in the theme component like they were previously, then they are handled by the component itself (ie. ThemeBase ) - which is created/disposed on every page navigation. So in this scenario the firstRender is true each time the component is first created, and false each time it is re-rendered.

If you want to retain the old behavior then you could declare your Stylesheet Resources in ThemeInfo and Script Resources in the component itself.

Reading the description above, it is clear that this difference in behavior is confusing. I will do some research into whether it would be possible to move the ThemeBuilder Script workload to ThemeBase for consistency.

**Comment by leigh-pointer** [comment]
@sbwalker That is clear now.  I will move the script to the Theme component.

**Comment by leigh-pointer** [comment]
@sbwalker using both Resource loaders.
First I put everthing back in the theme, that errored on load because the List was empty of style sheets.
Second moved styels to ThemeInfo and scripts to Theme.  Loaded but same issue.
Third all external resources (cdn) to theme component and internal styles to ThemeInfo.  Loaded but same issue.

**Comment by sbwalker** [comment]
Ok, I will take a closer look at this

**Comment by sbwalker** [comment]
@leigh-pointer I migrated the JavaScript handling logic from ThemeBuilder to the component's OnAfterRenderAsync method. Basically what this means is that regardless of whether you declare your Resources in ThemeInfo/ModuleInfo or within the theme/module component, it will be processed within the component's OnAfterRenderAsync method. This keeps the JavaScript processing encapsulated within the component and also means that the firstRender property will always behave as expected as it follows the standard component life cycle for create/dispose. Please give it a test by declaring all of your Resources in ThemeInfo (Stylesheets and JavaScript). And then move your Resources from ThemeInfo to the component and test again. You should see consistent behavior.

**Comment by sbwalker** [comment]
@leigh-pointer #2917 is a fix based on your testing from yesterday - "First I put everything back in the theme, that errored on load because the List was empty of style sheets"

**Comment by leigh-pointer** [comment]
@sbwalker Got the latest, #2917 tested ok.  However 
JavaScripts not loading any scenario. 

the other test OnAfterRender;
With CSS in ThemeInfo and JS in Theme OnAfterRender Event not fired.
With nothing in ThemeInfo and all in Theme OnAfterRender Event not fired.

**Comment by sbwalker** [comment]
@leigh-pointer I am not sure what you mean... the OnAfterRenderAsync life cycle event for a component ALWAYS fires (this is part of Blazor). If you have a component in your theme (ie. Default.razor) then it can choose to not implement the OnAfterRenderAsync method - in which case it will be processed by ThemeBase. If you choose to implement the OnAfterRenderAsync method in your own component then you need to ensure you still invoke the base class processing by calling  await base.OnAfterRenderAsync(firstRender); at the top of your method. In all cases the OnAfterRenderAsync is fired.

**Comment by leigh-pointer** [comment]
@sbwalker yeah sorry, the event is fired when moving to a new page but the FirstRender parameter is false.

**Comment by sbwalker** [comment]
@leigh-pointer I realize this is confusing but when you navigate from page to page it is important to note that the entire page is not being disposed and recreated as it would in a server application - the event is being handled client-side. So if you are using the same theme component on multiple pages in your site then the FirstRender parameter is only going to be true the very first time that the component is created. On subsequent navigations, the same component instance will be reused which means FirstRender will be false. If you have a different theme component assigned to a page then the first time that different component is created, FirstRender will be true for that component - and the original theme component will be disposed. This means that when you navigate to a page with the original theme component, it needs to create a new instance again so FirstRender will be true.

**Comment by leigh-pointer** [comment]
@sbwalker I am trying to interact with Interop on (FirstRender) but my JS files are not loaded yet

'Error: Microsoft.JSInterop.JSException: Could not find'

I have tried moving resources ThemeInfo and also in the Theme (Default) component, any suggestions?

**Comment by sbwalker** [comment]
@leigh-pointer were you using IHostResources previously?

**Comment by leigh-pointer** [comment]
@sbwalker no, not that i am aware.

**Comment by sbwalker** [comment]
@leigh-pointer based on the latest code it should not matter if you declare your Resources in ThemeInfo or in the Theme component (but you should only choose one location). They will be processed by the OnAfterRenderAsync() method int he Theme component. Did you try logic such as the following:

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
            // register JavaScript resources
            await base.OnAfterRenderAsync(firstRender);
            if (!firstRender)
            {
               // call JavaScript method
                var interop = new Interop(JSRuntime);
                await interop.YourMethod();
            }
    }
```

**Comment by vnetonline** [comment]
@sbwalker & @leigh-pointer I hate to say it guys but the flashingis back after the latest set of changes

My stylesheet and scripts are declared in ThemeInfo like below .... I also tired in the Component same result there us a flash

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/7fde4770-16a4-449a-a009-9e7061bd0d7a)

see below the flashing

![screen2gif-nicetheme-flashing-is-back](https://github.com/oqtane/oqtane.framework/assets/15242923/686e634d-e0b0-4bc8-9d17-96572385c9ff)

**Comment by vnetonline** [comment]
@sbwalker & @leigh-pointer my bad just re-tested in both ThemeInfo and The Component Default.razor see below the results 

Declarations in Component

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/498f9ae2-6753-402a-b7ff-db0dd1899d5d)

Result in Browser

![screen2gif-nicetheme-in-component](https://github.com/oqtane/oqtane.framework/assets/15242923/a8df7cc0-dd8e-4db7-9790-6ef8b4ba1a68)

Declarations in Theme Info 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/bf17b617-fc18-43ef-9a24-59b80354b62d)

Result in the Browser

![screen2gif-nicetheme-in-themeinfo](https://github.com/oqtane/oqtane.framework/assets/15242923/b07a1f93-2194-49f2-b4d7-befa6e0b2907)

**Comment by vnetonline** [comment]
@sbwalker as we can see when we navigate to a the page is set with different theme couldn't we put an overlay with a loading spinner so that the theme can load that way we wont get the F0UC issue

**Comment by sbwalker** [comment]
@vnetonline I already mentioned in another thread that switching between themes on the same site is problematic for many reasons in a SPA (wholesale replacement of all CSS, JavaScript library conflicts, etc...). The only solution guaranteed to work properly is to do a full page refresh in this scenario.

**Comment by sbwalker** [comment]
I just experimented with adding a full page reload in the scenario where you navigate to a page with a different theme, but it results in a poor user experience on Blazor Server is to shows the "Reconnecting..." message momentarily as SignalR reconnects. My gut feeling tells me that this is a scenario which may improve with .NET 8 as it really requires a fusion of server and client capabilities.

**Comment by sbwalker** [comment]
@leigh-pointer & @vnetonline can you please assist with closing out this thread...

1. This issue is focused on JavaScript and the behavior of OnAfterRenderAsync. Changes were made to force the JavaScript workload to be always be processed in the theme or module component - and it does not matter if the JavaScript Resources are declared in the Info class or the component itself.
2. There was confusion about the behavior of FirstRender - but it is behaving as expected (this is a standard Blazor behavior)
3. There was a question about how to declare JavaScript and call its methods within the same component - and I provided some sample code - @leigh-pointer did this answer your question and were you able to get it working? Is that why you Closed this issue?
4. @vnetonline you added comments to the issue after it was Closed related to CSS - which is completely unrelated (JavaScript and CSS are managed independently within the framework due to Blazor behaviors). The CSS comments are related to the scenario of using different themes within the same site. This should be moved to a different thread - however the bottom line is that this scenario only works under very specific circumstances - the themes must use the exact same Bootstrap libraries - both version and source location or else there will be undesirable behavior.

**Comment by leigh-pointer** [comment]
@sbwalker I was thinking about the same thing.  Your suggestion, will keep the flash/refresh issue away and further down the line, maybe the restrictions are removed.

It is also fair to note that it is possible to create a Web User and Web Admin themes in one package.  Your suggestion, will keep the flash/refresh issue away and further down the line, maybe the restrictions are removed.

**Comment by leigh-pointer** [comment]
> one suggestion is to modify the Add/Edit Page UI to only display Themes which are related to the Default Theme specified for the Site.
On reflection, I would be better to raise a warning that using a theme other than what is set up in the site settngs can cause adverse effects.  This way, viewing and testing modules with other themes is still possible.

**Comment by sbwalker** [comment]
@leigh-pointer you would still be able to test modules by changing the default theme in the Site Settings.

**Comment by sbwalker** [comment]
@leigh-pointer based on all of the discussion about this scenario in the past few weeks, I do not think a warning message will be sufficient (ie. users will not understand what is meant by "adverse effects" and will still raise support questions when they encounter strange behavior). If a feature is truly not supported then the system should prevent users from encountering it. #2921 restricts a site to using a single theme.

**Comment by vnetonline** [comment]
> @leigh-pointer & @vnetonline can you please assist with closing out this thread...
> 
> 1. This issue is focused on JavaScript and the behavior of OnAfterRenderAsync. Changes were made to force the JavaScript workload to be always be processed in the theme or module component - and it no longer matters if the JavaScript Resources are declared in the Info class or the component itself - they are all processed in the component.
> 2. There was confusion about the behavior of FirstRender - but it is behaving as expected (this is a standard Blazor behavior)
> 3. There was a question about how to declare JavaScript and call its methods within the same component - and I provided some sample code - @leigh-pointer did this answer your question and were you able to get it working? Is that why you Closed this issue?
> 4. @vnetonline you added comments to the issue after it was Closed related to CSS - which is completely unrelated (JavaScript and CSS are managed independently within the framework due to Blazor behaviors). The CSS comments are related to the scenario of using different themes within the same site. This should be moved to a different thread - however the bottom line is that this scenario only works under very specific circumstances - the themes must use the exact same Bootstrap libraries - both version and source location or else there will be undesirable behavior.

@sbwalker we can close this out, as long as we don't allow using different themes at the page level compared to the theme set in the site then we are all good!
