### ISSUE TITLE
Create Module change some files automatically for windows and Linux

### ISSUE THREAD

**Issue by AnjaSimons** [oqtane/oqtane.framework#2913]
I work successful with this project on Ubuntu with rider. I like this very much. But in creating a module, the automatically projectfiles are only for window. Please add two files named debug.sh and release.sh. 
debug.sh:
cp -f "../Client/bin/Debug/net7.0/xxx.Client.Oqtane.dll" "../../oqtane.framework/Oqtane.Server/bin/Debug/net7.0/"
cp -f "../Client/bin/Debug/net7.0/xxx.Client.Oqtane.pdb" "../../oqtane.framework/Oqtane.Server/bin/Debug/net7.0/"
cp -f "../Server/bin/Debug/net7.0/xxx.Server.Oqtane.dll" "../../oqtane.framework/Oqtane.Server/bin/Debug/net7.0/"
cp -f "../Server/bin/Debug/net7.0/xxx.Server.Oqtane.pdb" "../../oqtane.framework/Oqtane.Server/bin/Debug/net7.0/"
cp -f "../Shared/bin/Debug/net7.0/xxx.Shared.Oqtane.dll" "../../oqtane.framework/Oqtane.Server/bin/Debug/net7.0/"
cp -f "../Shared/bin/Debug/net7.0/xxx.Shared.Oqtane.pdb" "../../oqtane.framework/Oqtane.Server/bin/Debug/net7.0/"
cp -rf "../Server/wwwroot/"* "../../oqtane.framework/Oqtane.Server/wwwroot/"

And change the Package.csproj Target as follow:
```
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition="'$(OS)' == 'Windows_NT' And '$(Configuration)' == 'Debug'" Command="bash $(ProjectDir)debug.cmd" />
    <Exec Condition="'$(OS)' != 'Windows_NT' And '$(Configuration)' == 'Debug'" Command="bash $(ProjectDir)debug.sh" />
    <Exec Condition="'$(OS)' == 'Windows_NT' And '$(Configuration)' == 'Release'" Command="bash $(ProjectDir)release.cmd" />
    <Exec Condition="'$(OS)' != 'Windows_NT' And '$(Configuration)' == 'Release'" Command="bash $(ProjectDir)release.sh" />
</Target>
```
So the Project will also run in a linux environment. I have tried this right now. It would be nice, if a linux developer must not do this alway per hand.

**Comment by sbwalker** [comment]
Thank you for this enhancement - this is very appreciated. We will integrate for the 4.0 release.

**Comment by sbwalker** [comment]
@AnjaSimons you included the content of the debug.sh - but not the content of the release.sh. Note that the release file is expected to be executed in Release mode and creates a Nuget package and deploys it to the Oqtane framework (whereas the debug file copies the assemblies and static assets without creating a Nuget package)

**Comment by AnjaSimons** [comment]
Sorry, here is the code for release.sh
"..\..\oqtane.framework\oqtane.package\nuget.exe" pack modulename.nuspec 
cp -f "*.nupkg" "..\..\oqtane.framework\Oqtane.Server\Packages\"

This part I didn't test now.

**Comment by sbwalker** [comment]
@AnjaSimons I don't think this will work because nuget.exe is a Windows executable. There is a dotnet.exe which I believe is cross platform compatible however I will not have time to research. For now I will just include the improvements outlined above, which does work in Debug mode (which is the mode most Oqtane developers will use).

**Comment by sbwalker** [comment]
When running your proposed changes under Windows and Debug mode it results in an error:

"The command "bash C:\Source\Projects\Siliqon.Module.Test\Package\debug.cmd" exited with code 9009"

**Comment by sbwalker** [comment]
completed in #2924 - changes applied to Module and Theme external templates

**Comment by AnjaSimons** [comment]
I don't know, if you read this, but you had a problem with the release.sh for linux. I have researched this. If on the development linux system **mono** is installed, then it is possible to run nuget.exe. I m my case it is so. Otherwise you can use dotnet pack MyProject.csproj. This will create a .nupkg file in the bin/Debug or bin/Release directory, depending on your configuration. You can also use a .nuspec, but you have to add this in the project and add this in the package reference. So now there isn't any failure. I could help you to describe how to develop on Linux with rider in your documents, if you want.

**Comment by sbwalker** [comment]
@AnjaSimons I do not develop on Linux personally so I could really use your help to ensure the debug.sh and release.sh files are valid and function correctly on Linux
