### ISSUE TITLE
Suggestion to Improve Middleware Configuration in Startup.cs

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#2919]
I've been looking at the `Configure` method in the [`Startup.cs`](https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Server/Startup.cs) file within the Oqtane.Server project:

```cs
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ISyncManager sync, ILogger<Startup> logger)
```

The order of middleware configuration within this method is critical. Here's the existing configuration:

```cs
// execute any IServerStartup logic
app.ConfigureOqtaneAssemblies(env);

// allow oqtane localization middleware
app.UseOqtaneLocalization();

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseTenantResolution();
app.UseJwtAuthorization();
app.UseBlazorFrameworkFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();  
```

I propose to rearrange the middleware configuration by moving `app.ConfigureOqtaneAssemblies(env);` to come after `app.UseAuthorization();`. The revised configuration would look like this:

```cs
// allow oqtane localization middleware
app.UseOqtaneLocalization();

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseTenantResolution();
app.UseJwtAuthorization();
app.UseBlazorFrameworkFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

// execute any IServerStartup logic
app.ConfigureOqtaneAssemblies(env);
```

The benefits of this reordering are:
1. There would no longer be a need to duplicate the Oqtane middleware in a custom Oqtane module that uses `app.UseEndpoints(endpoints => ...);`. Example https://github.com/2sic/2sxc/blob/develop/Src/Oqtane/ToSic.Sxc.Oqt.Server/StartUp/OqtStartup.cs#L99-L182
2. It would avoid having duplicate Authentication (and other) middlewares in the pipeline, which currently could happens because of custom module.

I believe this change would enhance the maintainability and efficiency of the code. Please let me know your thoughts on this proposal.

Thank you.

![image](https://github.com/oqtane/oqtane.framework/assets/2724850/cd113aa2-1fb2-49ad-8fe6-70148c9725dd)

**Comment by sbwalker** [comment]
@tvatavuk the challenge with this suggestion is that there may be third party modules which are already using IServerStartup to inject middleware on startup - so rearranging the order could be a breaking change if a module is relying on the current order of operations. I am not sure how to validate if there is a high risk unless other module developers share information about the types of middleware they are injecting.

**Comment by sbwalker** [comment]
@tvatavuk I had come across a solution to this problem previously... I just needed to find it.

Please see this article: https://andrewlock.net/inserting-middleware-between-userouting-and-useendpoints-as-a-library-author-part-1/

In hindsight, IStartupFilter may have been the better approach rather than introducing IServerStartup.

**Comment by iJungleboy** [comment]
@sbwalker that sounds plausible yet very complicated - at least the blog you linked is quite a beast to read, but it sounds more or less what we need. 

Another option is patching it with `MapWhen` or similar. Here's an example of our current workaround:

```c#
            app.MapWhen(context => context.Request.Path.StartsWithSegments($"/{WebApiConstants.AppRootPathNdLang}"), appBuilder =>
            {
                appBuilder.UseOqtaneMiddlewareConfiguration();

                // endpoint mapping
                appBuilder.UseEndpoints(endpoints =>
                {
                    // Release routes
                    endpoints.Map(WebApiConstants.AppRootPathNdLang + "/{appFolder}/api/{controller}/{action}", AppApiMiddleware.InvokeAsync);
                    endpoints.Map(WebApiConstants.AppRootPathNdLang + "/{appFolder}/{edition}/api/{controller}/{action}", AppApiMiddleware.InvokeAsync);
                });

                // end of this middleware pipeline branch
            });

        public static IApplicationBuilder UseOqtaneMiddlewareConfiguration(this IApplicationBuilder app)
        {
            // Oqtane middlewares should be executed before configuration of 2sxc endpoint mappings
            // to avoid having duplicate middleware in pipeline (like we had before).
            // Order of middleware configuration is important, because that is order of middleware execution in pipeline.

            #region Oqtane copy from Startup.cs - L173

            // allow oqtane localization middleware
            app.UseOqtaneLocalization();

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseTenantResolution();
            app.UseJwtAuthorization();
            app.UseBlazorFrameworkFiles();
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            //if (_useSwagger)
            //{
            //    app.UseSwagger();
            //    app.UseSwaggerUI(c => { c.SwaggerEndpoint("/swagger/" + Constants.Version + "/swagger.json", Constants.PackageId + " " + Constants.Version); });
            //}

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub();
                endpoints.MapControllers();
                endpoints.MapFallbackToPage("/_Host");
            });

            #endregion
            return app;
        }
```

The main downside of this is the `UseOqtaneMiddlewareConfiguration` since it copies functionality from Oqtane, which could change from version to version. But maybe this approach could also work, if this method would be made available in Oqtane and we could be sure it's always updated or something...
