### ISSUE TITLE
When a Child Page is Deleted the Parent Page still has the HasChildren Property set to true 

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2941]
1. login as host
2. Add a Child Page called `Test` to `Home`
3. Delete the `Test` page and check the HasChildren property of the `Home` you will see it is still ``true
4. Go to `Home` The navigation menu will not have the `Test` page visible but the property `HasChildern1 will be true 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/23f7896d-27da-4f3e-90fb-72ed6e088219)

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/9721d299-8110-4079-a897-fc255a7bc9b7)

**Comment by sbwalker** [comment]
this is happening because the Page is soft deleted and the logic on the server which orders the list of pages in hierarchical order is not checking the IsDeleted flag
