### ISSUE TITLE
Manage Settings bug

### ISSUE THREAD

**Issue by rcpacheco** [oqtane/oqtane.framework#2958]
### Discussed in https://github.com/oqtane/oqtane.framework/discussions/2957

<div type='discussions-op-text'>

<sup>Originally posted by **rcpacheco** June 29, 2023</sup>
After activating the DNF.Project, per video 2, It activated properly and was able to create a project.
But when I tried to display the module's "Manage Settings" I got the following error:

![image](https://github.com/oqtane/oqtane.framework/assets/845725/3e803546-bf71-4d10-8fc5-56dd02e3ced3)

![image](https://github.com/oqtane/oqtane.framework/assets/845725/f9f381f6-1f62-4443-be50-0af2e2fb8d8c)
</div>

**Comment by sbwalker** [comment]
@rcpacheco very strange.... I am not able to reproduce this error on https://www.dnfprojects.com. I will keep investigating. Does Manage Settings work for any of your other modules in your site (ie. Html/Text, etc...)

**Comment by sbwalker** [comment]
Ok... it does not sound like a framework... more likely an issue in the DNF.Projects module itself. I will keep investigating.

**Comment by rcpacheco** [comment]
I did yesterday the exercise in a Windows 10 machine with the latest dev version.
Today I tried with a linux machine and got some interesting errors.
In linux I used dotnet console commands to build the project at inside the DNF.Module.Project folder. I compiled succesfully:
![image](https://github.com/oqtane/oqtane.framework/assets/845725/855bed5b-c966-4615-a624-ca74e9fa4d80)

But then I tried to check if the projects files where properly copied to the debug folder and saw:

![image](https://github.com/oqtane/oqtane.framework/assets/845725/b270400c-b40b-44b7-9f84-70a59839b5ad)

I noticed that strange ''$'\r' file.

I deleted it and repeat and manually run debug.sh with same result. Did cat to the file and copied the instrucctions from the console and executed them succesfully and got the content copied to the server project.
Launched the app again and while trying to activate the module got an error.

The message was:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending, OrderedEnumerable`1 parent)
   at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at DNF.Module.Project.Services.ProjectService.GetProjectsAsync(Int32 ModuleId) in /home/rpacheco/Documents/SaaS/DNF.Module.Project/Client/Services/ProjectService.cs:line 21
   at DNF.Module.Project.Index.OnInitializedAsync() in /home/rpacheco/Documents/SaaS/DNF.Module.Project/Client/Modules/DNF.Module.Project/Index.razor:line 53

```
Will repeat again the same exercise in windows, later in the day.

**Comment by sbwalker** [comment]
The Linux capabilities were recently introduced in 4.0 based on feedback from @AnjaSimons in #2913. If there is an issue with them I would appreciate any help you can provide as I do not develop in Linux.

**Comment by sbwalker** [comment]
The DNF.Projects error seems to be related to the module assuming data exists in your database. I will upgrade the module to .NET 6 and Oqtane 4.0 and ensure it is functional. If you want to experiment with Oqtane I would suggest you simply create a new module using the Module Creator in the Develop page of a new install.

**Comment by rcpacheco** [comment]
Sorry for the delay, but have been very busy.

Today I recreated the exercise in windows 10 with the dev branch commit 563695cd

I got the same error in trying to clic the settings option:

![image](https://github.com/oqtane/oqtane.framework/assets/845725/3a8ec543-cdcd-45b3-9f3e-276174a4da66)

![image](https://github.com/oqtane/oqtane.framework/assets/845725/720e4156-a268-4056-bc26-7a67079646ed)

I tried to find the missing type DNF.Project.Settings, DNF.Project.Client.Oqtane in the modules table, but did not find it: 
![image](https://github.com/oqtane/oqtane.framework/assets/845725/aea9ce54-2da2-4bb9-b9a1-13656ba57479)

Where should I look for it ?

**Comment by rcpacheco** [comment]
Does the fact that in the project Settings is under DNF.Module.Project an not under DNF.Project has something to do?

![image](https://github.com/oqtane/oqtane.framework/assets/845725/8e8f5aa8-f401-4f6b-a8b8-ba1f7e03db16)

**Comment by sbwalker** [comment]
I have not had time to uograde the DNF.Project module to .NET 7 yet.

**Comment by rcpacheco** [comment]
Yes indeed, I did so.  I used the same name, but the DNF project I created was no coming from any repo. It was created with the module creator tool. I just used the same name.

**Comment by rcpacheco** [comment]
> I did yesterday the exercise in a Windows 10 machine with the latest dev version. Today I tried with a linux machine and got some interesting errors. In linux I used dotnet console commands to build the project inside the DNF.Module.Project folder. I compiled succesfully: ![image](https://user-images.githubusercontent.com/845725/250125803-855bed5b-c966-4615-a624-ca74e9fa4d80.png)
> 
> But then I tried to check if the projects files where properly copied to the debug folder and saw:
> 
> ![image](https://user-images.githubusercontent.com/845725/250125460-b270400c-b40b-44b7-9f84-70a59839b5ad.png)
> 
> I noticed that strange ''$'\r' file.
> 
> I deleted it and repeat and manually run debug.sh with same result. Did cat to the file and copied the instrucctions from the console and executed them succesfully and got the content copied to the server project. Launched the app again and while trying to activate the module got an error.
> 
> The message was:
> 
> ```
> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
>    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>    at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending, OrderedEnumerable`1 parent)
>    at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
>    at DNF.Module.Project.Services.ProjectService.GetProjectsAsync(Int32 ModuleId) in /home/rpacheco/Documents/SaaS/DNF.Module.Project/Client/Services/ProjectService.cs:line 21
>    at DNF.Module.Project.Index.OnInitializedAsync() in /home/rpacheco/Documents/SaaS/DNF.Module.Project/Client/Modules/DNF.Module.Project/Index.razor:line 53
> ```
> 
> Will repeat again the same exercise in windows, later in the day.

Regarding the issue of the mysterious ''$'\r' file in linux, I changed the file endings of the debug.sh in the Package project  from CRLF line terminators to LF using the linux command dos2unix, and now the command ran properly and copied the module dll's, pdb's and files for the wwwroot\Modules directory.

Therefore, my recommendation is to change the file endings of the linux bash scripts (debug.sh and release.sh) in the template folder Oqtane.Server/wwwroot/Modules/Templates/External/Package and indicate git to preserve the line endings in the code repo using the  .gitattributes file with the following contents:
Oqtane.Server/wwwroot/Modules/Templates/External/Package/*.sh eol=lf

**Comment by rcpacheco** [comment]
> Does the fact that in the project Settings is under DNF.Module.Project an not under DNF.Project has something to do?
> 
> ![image](https://user-images.githubusercontent.com/845725/251598509-8e8f5aa8-f401-4f6b-a8b8-ba1f7e03db16.png)

Also, following up on this subject, it seem to me that since the path of the Oqtane.Server/wwwroot/Modules/Templates/External/Client/Modules/[Owner].Module.[Module]/Settings.razor file shows [Owner].Module.[Module]

I wonder if the line:
private string resourceType = "[Owner].[Module].Settings, [Owner].[Module].Client.Oqtane"; // for localization
should read instead:
private string resourceType = "[Owner].Module.[Module].Settings, [Owner].Module.[Module].Client.Oqtane"; // for localization

What do you think?
![image](https://github.com/oqtane/oqtane.framework/assets/845725/b62f3ef7-52a8-4ecd-805a-dc7fb4842d2d)

**Comment by sbwalker** [comment]
@rcpacheco can you please review/test #3019

**Comment by sbwalker** [comment]
@rcpacheco I have upgraded the DNF.Projects repo to .NET 7 - https://github.com/oqtane/DNF.Projects/issues/7
