### ISSUE TITLE
Version Numbers Issue

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2963]
Oqtane does not honor the 4 digit  paradigm (1.0.0.5) when looking for new versions from the market place.

**Comment by sbwalker** [comment]
correct, you will need to utilize a 3 digit version number

**Comment by leigh-pointer** [comment]
@sbwalker 

> The Marketplace admin site does allow the entry of 4 digit version numbers.

But in the Oqtane install module or theme area, a module or theme with a 4 digit version number will not be picked up and shown as an update.

**Comment by sbwalker** [comment]
@leigh-pointer  Sorry, I still do not understand what you mean by "will not be picked up". Here is a screen shot where a module with a 4 digit version is displayed:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/21a99747-70dc-481e-8331-5e2c434ce31e)

**Comment by leigh-pointer** [comment]
@sbwalker true but when in the module list the update button is not being displayed

**Comment by sbwalker** [comment]
Strange... as the logic uses standard .NET Version.CompareTo() to compare version numbers. You didn't change your PackageName I assume?

```
	{
		if (!string.IsNullOrEmpty(packagename) && _packages != null)
		{
			var package = _packages.Where(item => item.PackageId == packagename).FirstOrDefault();
			if (package != null && Version.Parse(package.Version).CompareTo(Version.Parse(version)) > 0)
			{
				return package.Version;
			}
		}
		return version;
	}
```

**Comment by leigh-pointer** [comment]
Package looks fine
```
    <id>StudioElf.DynamicForm.Beta</id>
    <version>1.0.6.5</version>
    <authors>StudioElf</authors>

```

**Comment by leigh-pointer** [comment]
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/0342b473-94fb-49ad-926d-51e351501022)

![image](https://github.com/oqtane/oqtane.framework/assets/9447612/3896126a-6796-48b6-9e0e-a59c3aef2b03)

**Comment by sbwalker** [comment]
@leigh-pointer what is the version number in the IModule interface for your module? The Version which is displayed in Module Management is retrieved from the IModule interface for your module.

**Comment by leigh-pointer** [comment]
Also 1.0.6.5
```
"StudioElf.DynamicForm - Is a Forms Designer lets you easily add controls to a form, and arrange them. The Form Designer gives you an object-oriented, visual environment for creating graphical forms and other user interface elements. Once your form is designed you are able to capture and display data in a presenter",
            Version = "1.0.6.5",
            ServerManagerType = "StudioElf.Dynamic
```

**Comment by sbwalker** [comment]
Sorry... I meant the "installed" version - not the new version. The version is showing as 1.0.6 in your screenshot. Please see this page for version comparison behavior:

https://learn.microsoft.com/en-us/dotnet/api/system.version.compareto?view=net-7.0

In  particular note:

```
Version 1.1 is older than version 1.1.0.

Version 1.1 is older than version 1.1.1.

Version 1.1 is older than version 1.1.2.3.

Version 1.1.2 is older than version 1.1.2.4.

Version 1.2.5 is newer than version 1.2.3.4.
```

**Comment by leigh-pointer** [comment]
Also 1.0.6

```
       public ModuleDefinition ModuleDefinition => new ModuleDefinition
        {
            Name = "StudioElf.DynamicForm",
            Description = "StudioElf.DynamicForm - Is a Forms Designer lets you easily add controls to a form, and arrange them. The Form Designer gives you an object-oriented, visual environment for creating graphical forms and other user interface elements. Once your form is designed you are able to capture and display data in a presenter",
            Version = "1.0.6",
            ServerManagerType = "StudioElf.DynamicForm.Manager.DynamicFormManager, StudioElf.DynamicForm.Server.Oqtane",
            ReleaseVersions = "1.0.0",
            Dependencies = "StudioElf.DynamicForm.Shared.Oqtane",
            PackageName = "StudioElf.DynamicForm"
            ,
            PermissionNames = Oqtane.Shared.PermissionNames.View + "," + Oqtane.Shared.PermissionNames.Edit + ",Compose,Designer,EditReadOnly"
        };
    }
```

**Comment by sbwalker** [comment]
@leigh-pointer please note that the PaclkageName in the IModule screenshot above is different than the package name you shared earlier in this thread  of "StudioElf.DynamicForm.Beta". These values need to be the same. The framework relies on the PackageName in the IModule interface to get the unique Paclage ID (it does not have access to the nuspec or nupkg). This mismatch in paclage names is causing the issue - not the version number.

**Comment by leigh-pointer** [comment]
@sbwalker I was getting to the same place. 

They have always been different, and the framework logic for this has hardly changed, strange how only now I pick it out.

Excuses .

**Comment by sbwalker** [comment]
@leigh-pointer no worries... I am glad this was not a framework issue. On a related note I am currently working on some changes to the Marketplace to improve the administrative UI and enable commercial modules and themes. The licensing service will be upgraded and a support service will also be included.

**Comment by leigh-pointer** [comment]
@sbwalker I am looking forward to this.  Any help needed I am happy to assist, this is something I have been holding out for.

**Comment by sbwalker** [comment]
@leigh-pointer I will definitely need help with testing as there are a lot of moving parts
