### ISSUE TITLE
No padding between Edit and Cog buttons

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2977]
I have noticed that there s no padding between the `Edit` and `Cog` in the `ControlPanel` component has this always been the case??

I am sure there was padding in between them 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/dfe3731e-16b9-4d67-b08f-4711dbbbdffa)

**Comment by sbwalker** [comment]
You are correct that there was some padding in 3.4.3... I am guessing the padding was lost due to a change in Bootstrap 5.3

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/485bee85-9ce2-41cf-a488-07e906f7ab61)
