### ISSUE TITLE
Can't publish new oqtane module release Error Loading App Store on Oqtane Marketplace

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#2986]
We are currently experiencing some issues with publishing a new release of our Oqtane module on the Oqtane Marketplace (https://www.oqtane.net/).

After attempting to log in at https://www.oqtane.net/registry, we are repeatedly presented with an error message stating 'Error Loading App Store'. This issue is preventing us from proceeding with the publication of our updated module.

![slika](https://github.com/oqtane/oqtane.framework/assets/2724850/6866fb5b-bf44-4e54-be9a-73146fc5d24a)

We have tried troubleshooting from our end, but the problem persists, and it appears to be originating from the platform itself. 
We did try with 2 different users, existing old oqtane.net user and new github user.

We were wondering if you could provide us with any guidance or assistance to resolve this issue.

**Comment by leigh-pointer** [comment]
@tvatavuk I think the module is not ready to accept new or modifiy at the moment.  After log in I am unable to edit any of my modules.

**Comment by sbwalker** [comment]
@tvatavuk & @leigh-pointer please try again... the issues you encountered should be resolved

**Comment by tvatavuk** [comment]
Thx😊! Issue is resolved👍.
