### ISSUE TITLE
Use C# String Interpolation for constructing Urls

### ISSUE THREAD

**Issue by kaypee90** [oqtane/oqtane.framework#300]
This is an improvement suggestion. For a cleaner code I suggest how the urls are constructed in the Client project services can improved by using interpolation or string.format.

**Comment by hishamco** [comment]
Could you please show a sample use case?

**Comment by sbwalker** [comment]
The Services in the Client project currently using string concatenation... and @kaypee90 is suggesting using string interpolation instead:

ie. current:

        public async Task<List<File>> GetFilesAsync(string folder)
        {
            return await _http.GetJsonAsync<List<File>>(Apiurl + "?folder=" + folder);
        }

after:

        public async Task<List<File>> GetFilesAsync(string folder)
        {
            return await _http.GetJsonAsync<List<File>>($"{Apiurl}?folder={folder}");
        }

I agree that string interpolation has some benefits.
