### ISSUE TITLE
Transparent background is lost for product logo on Oqtane Marketplace

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#3001]
The logo file `logo100.png`, which should maintain a transparent background, is incorrectly being displayed with a black background in the `Oqtane Marketplace`.

![slika](https://github.com/oqtane/oqtane.framework/assets/2724850/8eb54f72-60aa-4146-8dca-e306abf9b89a)

## Details:

- The file `logo100.png` is supposed to have a transparent background.
![100](https://github.com/oqtane/oqtane.framework/assets/2724850/aaba312a-e7ed-4084-a138-a7fef7dcff39)

- When the logo is used in `Oqtane Marketplace / Registry / Product Details` page, the background remains transparent as expected.
![slika](https://github.com/oqtane/oqtane.framework/assets/2724850/860d656e-46e9-4e2d-bb28-996acb386674)

- However, on the public `Oqtane Marketplace` page, the logo is presented with a black background, which is not the intended behavior.

Steps to reproduce:

1. Navigate to the public `Oqtane Marketplace` page for 2sxc module (on https://oqtane.net).
2. Observe that the `logo100.png` is displayed with a black background.

The expected result is that the `logo100.png` `https://www.oqtane.net/api/file/image/428/100/100/crop/center/000000/0/False` should retain its transparent background regardless of where it's used within the application.

![](https://www.oqtane.net/api/file/image/428/100/100/crop/center/000000/0/False)

**Comment by sbwalker** [comment]
@tvatavuk this is fixed
