### ISSUE TITLE
Market place after log out

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3002]
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/46f0e3fe-111b-450e-ba3f-6ea1765cf7ef)

**Comment by sbwalker** [comment]
This happens because you had a cookie in your browser which was created when the Marketplace was hosted on a different app service. Once you logout and then login again and get a new cookie on the new app service login/logout should work fine.
