### ISSUE TITLE
Market Place edit product

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3003]
I am not sure I agree with using "Submit Product" to edit exisitng products or adding new verions.  It is not clear for someone who just wants to edit an exising product.

![image](https://github.com/oqtane/oqtane.framework/assets/9447612/0e8477ce-5369-4307-9f5b-3310e3de1239)

**Comment by sbwalker** [comment]
I have seen "Submit Product" used on other marketplaces so I thought it would be best to follow conventions
