### ISSUE TITLE
Trying to add Icon to Translation in Market place

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3004]
Receive this error
`The Package Id Specified Has Already Been Registered Previously `

![image](https://github.com/oqtane/oqtane.framework/assets/9447612/5cfd8458-4ce5-4efb-b515-167b99a8d211)

Theme and Module I had no problem

**Comment by sbwalker** [comment]
@leigh-pointer this is fixed

**Comment by sbwalker** [comment]
@leigh-pointer are you able to edit your Product titles to include spaces rather than  "."? The title is intended to be a "friendly" title for the module - not a namespace or package name.

**Comment by leigh-pointer** [comment]
All completed and updated
