### ISSUE TITLE
Mobile Screen Menu Collapsable Site Pages Plus Admin + User Controls

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#301]
Mobile Screen Menu Collapsable Site Pages Plus Admin + User Controls

![image](https://user-images.githubusercontent.com/13577556/77255264-6c9b6580-6c23-11ea-9912-d471181e40a0.png)

Something like above styled for Oqtane.

Click on the icons and it opens the windows below with options such as pages, account details and admin options as vertical menus and pages

![image](https://user-images.githubusercontent.com/13577556/77255355-f814f680-6c23-11ea-832a-ed9d05dc98fe.png)

admin panel maybe 100% width even... could be an arrow at top corner of screen that expands collapses out as well and replace the hamburger for admin with site pages and put "fas fa-cogs" for example along with the page edit pen below it at top right of page that will expand out from top of page admin menu full screen full of options that can be added as panes for things such as analytic stats.  For now something like this works too.

![image](https://user-images.githubusercontent.com/13577556/77255417-7a9db600-6c24-11ea-8b02-ede97d718bff.png)

Just a thought is to incorporate other blazor projects code source and ideas into 

Here is one project I found with similar characteristics that is MIT 

https://blazorman.z22.web.core.windows.net/fetchdata

 I think Oqtane looks similar to above so it should be able to use for an example of ways this can currently be done using Blazor.
I like the menus coming out the sides.

![image](https://user-images.githubusercontent.com/13577556/77255603-efbdbb00-6c25-11ea-80fa-9f3a1a1c13d8.png)

**Comment by sbwalker** [comment]
Yes I agree that the default themes need to utilize responsive design to provide a good experience on mobile devices - and it should not be overly difficult since we are using Bootstrap 4 as a responsive CSS design system. Definitely the navigation menu needs to collapse when running on smaller screens and the administrative options need to be kept visible in the main view.

**Comment by sbwalker** [comment]
In case you were not aware there are actually 2 themes installed with Oqtane. The default theme is the standard Blazor look and feel. The other theme is the Oqtane theme and is based on Bootswatch Cyborg. You can apply the Oqtane theme by going to Site Settings in the Admin Dashboard and selecting the Default Theme = "Oqtane Theme - Default", Default Layout = "Oqtane Theme - SinglePane", and Default Container  = "Oqtane Theme - Container". This will completely transform the look of your site. I have just checked in a few minor modifications to deal with display issues in mobile - it still needs some more work but it is fairly usable.

**Comment by sbwalker** [comment]
![Mobile](https://user-images.githubusercontent.com/4840590/77551238-770a6900-6e88-11ea-89c4-865ee12e7dc5.png)

**Comment by chlupac** [comment]
Please use divs for forms, design can be more responsible and maintainable.

**Comment by sbwalker** [comment]
The entire suite of admin components use tables for forms currently, so it is a non-trivial task to modify all of them. This can be something which is added to the list of post-MVP items as it does not negatively impact the current functionality of the application.

**Comment by chlupac** [comment]
I agree, it's only wish for future.

**Comment by thabaum** [comment]
as long as we can div's later without causing breaking changes as needed along with classes to use for selectors in CSS as much as possible where needed.  This along with accessibility tab orders and such for overall user experience.

Just didnt look like it would take much to add it really as you said you had already done so I think.  

I am taking a few courses from Microsoft site that I am trying to get time to push through.  I have partially done one for razor pages which is laying the entire application framework down for me.  I should be able to be productive here soon as things calm down a bit more so I can put time into it.

So I am posting things for the MVP and looking for things to do for upcoming release with issues related to the functionality of things currently which should be more the focus I am understanding more here.  

I just want to be sure things get on some type of list here as I will be probably pushing out a variety of issues as I see them to reference later as well for my own use.

**Comment by sbwalker** [comment]
For V1.0  the main action item is that the default Blazor skin needs some design help to function better in mobile scenarios. The main problems are in the theme header - the nav menu needs to collapse into a left-hand hamburger menu  and the admin components at the right-hand side need to be visible.

**Comment by sbwalker** [comment]
@hishamco I have enlisted a designer to make both themes mobile friendly. However I agree that we should only include 1 theme with the framework and the other theme should be installable via Nuget. The question is which theme should be the default - the Blazor theme or the Oqtane theme? I will create a new issue for this and post screen shots to get some opinions.

**Comment by hishamco** [comment]
I can work on the themes if you don't mind

**Comment by sbwalker** [comment]
What are the changes you had in mind? My designer is already working on making the Blazor Theme responsive so I would not recommend making any changes to that one at the moment until the changes are checked in.

**Comment by hishamco** [comment]
> My designer is already working on making the Blazor Theme responsive

If is that go ahead, but again why we should rely on the default theme? instead we can create a light version of Oqtane theme instead

**Comment by sbwalker** [comment]
The Blazor theme has now been enhanced to be responsive / mobile friendly

![blazormobile](https://user-images.githubusercontent.com/4840590/80407675-ff1ecc80-8893-11ea-866d-47eb957ee22e.png)

**Comment by danielmoralesb** [comment]
Excelent! Glad to help @sbwalker . let me know if you need more help.

**Comment by hishamco** [comment]
Thanks for your effort @danielmoralesb
