### ISSUE TITLE
Page disappears if you unpublish a module on the page

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#3033]
- log in as host
- unpublish the first module on the page
- publish the same module on the page
- page will disappear as permissions are taken away from the administrator

![screen2gif-unpublish-publish-error](https://github.com/oqtane/oqtane.framework/assets/15242923/25f85c9b-7cfe-4713-9cc4-e35227144bb7)

**Comment by sbwalker** [comment]
resolved in #3034
