### ISSUE TITLE
Module Creator problem while using Postgresql

### ISSUE THREAD

**Issue by rcpacheco** [oqtane/oqtane.framework#3041]
In the page "My Page" I created a Module with owner: Sapo (toad) and Module name: Verde (green).
It was created properly and activated, but after activation I got an error while trying to display it.
I tested both in linux and windows with sql local (only win) and sqlite (both) with no problem, but in postgresql (both) was crashing.

Knowing that postgresql uses snake case in its tables and columns (UseSnakeCaseNamingConvention), I reviewed the extraction of data and realized that the problem was while trying to load de data in the repo:

 return _db.Verde.Where(item => item.ModuleId == ModuleId);

![image](https://github.com/oqtane/oqtane.framework/assets/845725/75ad59fd-9c2c-47df-9211-c1c255e94590)

That lead me to realize that the name of the table was defined with the Table attribute:

![image](https://github.com/oqtane/oqtane.framework/assets/845725/f047542a-2a66-4ddf-9123-dcad1d1cd69f)

Once I changed the Table attribute to match the name in the database in snake case, it worked.

**Comment by leigh-pointer** [comment]
@rcpacheco This is strange and the replace logic will not alter the case of the values entered in the Module Creator.

> I created a Module with owner: Sapo (toad) and Module name: Verde (green).

Then the Table attribute should be "SapoVerde"

**Comment by rcpacheco** [comment]
Yes, It Is strange. If you have the time, please give It a try, leaving the attribute as you sugest. Look forward to hear your results. Thanks a lot.

**Comment by leigh-pointer** [comment]
I have test with the current version of Oqtane and everything seems to be ok.

Step One
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/68de4826-9283-4584-b68b-b18b7ef205c3)

Step Two
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/4ed29b6c-5423-489b-b5c0-ee36cfb08879)

Step Three
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/56df396e-415f-4d6e-aaef-07413bcccdf5)

Step Four
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/540175fe-fae6-4c61-97ec-e74d25ab9705)

Step Five
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/a6cfeb32-644e-4ded-8a89-fdd115acf1bb)

Step Six
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/b832b69b-4b8e-409e-8cd3-4e1c5e8db5cb)

Step Seven
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/0f10227b-8a9b-4989-b5eb-27e9fb93503f)

Step Eight
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/cc5bbcdf-7b5e-40ed-a4e1-8fd982a990ce)

**Comment by rcpacheco** [comment]
Thanks for taking the time @leigh-pointer to do the exercise.

I repeated it saving the screens. The difference I find is that I'm running on Linux. Besides that, there are no obvious differences.

For reference I include my setup info:

![01_system_info](https://github.com/oqtane/oqtane.framework/assets/845725/5b08345b-37e8-46ba-8649-d52015c04404)

As well as my launch info for Visual Code:

![02_vc_launch_json](https://github.com/oqtane/oqtane.framework/assets/845725/a763ebc9-e4a9-494f-a093-322708d11c8d)

Here the database configuration:

![03_db_configuration](https://github.com/oqtane/oqtane.framework/assets/845725/5acc75fd-95eb-42c2-a593-576fec29b975)

Creating the module:
![04_create_module](https://github.com/oqtane/oqtane.framework/assets/845725/d07cbee3-0068-4641-b463-620593166188)

Once created, waiting for activation:

![05_module_created](https://github.com/oqtane/oqtane.framework/assets/845725/85750eeb-462d-45ff-a415-4e109d887fca)

I build the model:

![07_build_module](https://github.com/oqtane/oqtane.framework/assets/845725/ba8165ba-eed0-4bab-ad8d-02a5b816abfd)

Check that everyting cas properly copied to the Oqtane proyect:

![08_module_ready](https://github.com/oqtane/oqtane.framework/assets/845725/a0e46812-35d3-4ffb-9bb1-46f33d59be9b)

Run again and when I try to activate the module I get the error:
![10_error_on_activate](https://github.com/oqtane/oqtane.framework/assets/845725/257b46c5-32b7-47cd-9303-7850f98ab3e1)

Here the Event log generated:

![11_event_log_main](https://github.com/oqtane/oqtane.framework/assets/845725/dce2d9a3-ed5d-41b6-805d-8941e6679459)

The details:

![12_details_error_verde](https://github.com/oqtane/oqtane.framework/assets/845725/201af1ee-2d0d-4ac0-a3bf-ea955a17548e)
![13_details_error_verdeservice](https://github.com/oqtane/oqtane.framework/assets/845725/a54ee04a-8a61-4273-a5b0-fb98db05dc34)

The exception info copied from the detail:

![14_exception_info](https://github.com/oqtane/oqtane.framework/assets/845725/ed3bf848-9f91-4915-8d3c-96b2f0e820d0)

I tried to debug the module, doing some preparations for visual studio code in linux:
![15_module_debug_preparation](https://github.com/oqtane/oqtane.framework/assets/845725/e5e41c38-ba8f-47c3-b3f9-9244f484f0d4)

I set some breakpoints:

![17_breakepoint_1](https://github.com/oqtane/oqtane.framework/assets/845725/42cf7138-75ac-4407-9e47-c597a97176e9)

Upon hitting the first breakpoint I stepped into the GetJsonAsync instruction, and got a Status Code 500 in the response:
![21_getjson_response](https://github.com/oqtane/oqtane.framework/assets/845725/3998a240-28fe-40c9-9e53-e9d602c7959e)

It may not be the table name as you showed in your test @leigh-pointer , but clearly something else is causing that error 500 that I'm not identifying properly.

**Comment by leigh-pointer** [comment]
Change
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/78d5aae4-8b24-404e-89a3-032fb836fe10)

to

```
  public async Task<List<Models.Verde>> GetVerdesAsync(int ModuleId)
  {
      List<Models.Verde> Verdes = await GetJsonAsync<List<Models.Verde>>(CreateAuthorizationPolicyUrl($"{Apiurl}?moduleid={ModuleId}", EntityNames.Module, ModuleId));
      return Verdes.ToList();
  }
```
Compile and run again.

Error seem to be with Linq and ordering an empty list.

**Comment by rcpacheco** [comment]
I tried your suggestion unsuccessfully.
It look like the value returned is not an empty list but null. 

Therefore  We can not call Order or any other method for a null variable.

![image](https://github.com/oqtane/oqtane.framework/assets/845725/85c532fe-237e-4f22-a61f-3cfe233f8349)

The default value of T, in this case List<Models.Verde>>, is null, not an empty list.
Therefore the solution was do the following change:

![image](https://github.com/oqtane/oqtane.framework/assets/845725/20af1262-a69b-4bfb-86d4-f93ec58f817e)

**Comment by rcpacheco** [comment]
I tested the change both from a windows machine and a Linux machine pointing to the Postgresql database and it solved the problem. Should I generate a pull request or how would you prefer to handle it?

**Comment by leigh-pointer** [comment]
@rcpacheco generate a pull request or raise an issue then i can could action it.
