### ISSUE TITLE
ModuleInstance Oqtane.Modules.ModuleBase.ModuleInstance.get returned null.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3054]
I have an error in UpdateSettings and wish to display a message but it does not allow you to set a ModuleInstance.AddModuleMessage message.

**excption**:
System.NullReferenceException: 'Object reference not set to an instance of an object.'
Oqtane.Modules.ModuleBase.ModuleInstance.get returned null.

I have never hit an error in the HTMLText module settings but it also follows this paradigm 

```
            try
            {
            /....code...../
            }
            catch (Exception ex)
            {
                ModuleInstance.AddModuleMessage(ex.Message, MessageType.Error);
            }
```

**Comment by sbwalker** [comment]
AddModuleMessage relies on the module component being a direct descendant of ModuleInstance:

ModuleInstance.razor
  - YourModuleComponent.razor

When it comes to Settings components they are actually injected into the framework Settings.razor component

ModuleInstance.razor
  - Settings.razor
      - YourModuleSettingsComponent.razor

So it makes sense that AddModuleMessage does not work in Settings components. In this case I would suggest you use the ```<ModuleMessage>``` component in your Settings component instead.
