### ISSUE TITLE
Error with "You Are Already Signed In" navigation

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3065]
I am in a instance of Edge logged in to my site (instance of the Framework).  I have an emila with a link to the siite, I click a link to a module inside my site and it opens a new tab and renders You Are Already Signed In". If i am aready signed in, then I should be navigated to the correct area.

Pasting the link in to the address bar navigates me to the correct area.

**Comment by sbwalker** [comment]
@leigh-pointer please provide detailed steps to reproduce the problem. You mention Edge - is this a browser-specific behavior?

**Comment by leigh-pointer** [comment]
@sbwalker not it is not browser related.  Issue is with ?returnurl= to reproduce navigate to a page that is only for registered users and then the error will begin

**Comment by sbwalker** [comment]
@leigh-pointer there should be no difference in behavior between pasting a link in the browser address bar and clicking a link in an email. This is why I asked if the behavior was browser specific.

**Comment by leigh-pointer** [comment]
Edge
![DynamicFormAlreadySignedIn](https://github.com/oqtane/oqtane.framework/assets/9447612/b6bf6772-0f67-4eca-8e77-ad0ee958ba31)

Fire Fox
![DynamicFormAlreadySignedInFF](https://github.com/oqtane/oqtane.framework/assets/9447612/41074679-38e3-4abb-a1a4-fb8bb02189e5)

**Comment by sbwalker** [comment]
@leigh-pointer #3099 attempts to resolve this UX issue. There are a number of scenarios to consider:

Assuming a user is already logged in... and they navigate to the /login page...

1. No returnurl parameter specified - they will be redirected to "/" (home page)
2. returnurl points to a page which user has access to - they will be redirected to the page
3. returnurl points to a page which user does not have access to - they will be redirected to the 404 page

**Comment by leigh-pointer** [comment]
@sbwalker  I will check it out now.
