### ISSUE TITLE
Debug and release .cmd files 

### ISSUE THREAD

**Issue by MPatriot** [oqtane/oqtane.framework#3069]
Anyone know what the debug.cmd and the release.cmd files do?
I had to delete them as my web host doesn’t allow .cmd files and publish fails 
They say it’s a security issue 

Mark

**Comment by leigh-pointer** [comment]
These files are used when Visual Studio compiles the framework or a module.
You can safely delete them as they are not needed in production.  
There is a Install Oqtane which is just the compiled assemblies.

**Comment by MPatriot** [comment]
Thanks Leigh. That's what I was hoping and hadn't noticed any problems until I tried uploading file through admin: glad they aren't related

**Comment by sbwalker** [comment]
@MPatriot manually publishing a release from Visual Studio is not recommended. You should download an official release from GitHub (created using the release.cmd in the /Oqtane.Package folder which ensures all necessary static assets are included)

**Comment by MPatriot** [comment]
Hmm, not sure what to do.  The host server rejects it and support says they don't allow it.  This was never a problem on Winhost but when using SmarterASP.NET it seems to be a problem for them.

Thanks,
Mark

**Comment by MPatriot** [comment]
Yes,  I realized their purposes after seeing where they were located. I don’t see it as a problem to manually delete the four files: release and debug versions before uploading a production version. One can simply use a local copy to create a dev module or theme module. This seems easier than trying to keep track of multiple releases of the same thing and remembering which is which I am just glad to have figured out and now had confirmed what Leigh said from the beginning Thanks Sent from my iPhoneOn Jul 31, 2023, at 11:20 AM, Shaun Walker ***@***.***> wrote:
@MPatriot The official releases of Oqtane (https://github.com/oqtane/oqtane.framework/releases) include Theme and Module templates which streamline the development experience. These templates are essentially a collection of code artifacts which are used to scaffold a fully functional new Theme or Module project. The templates include cmd files for automating the deployment of DLLs to the /bin folder. You could certainly remove the templates from the release when you deploy to your environment, by deleting the following folders:
\wwwroot\Modules\Templates\External
\wwwroot\Themes\Templates\External
Since these templates are only intended to be used in development environments, perhaps they should not be included in the official "Install" or "Upgrade" release packages. We could either include a "Developer" package or rely on developers to get the framework code from GitHub - I would like to get feedback from other community members on which approach is preferable (my preference is to rely on GitHub).

**Comment by sbwalker** [comment]
@leigh-pointer @vnetonline what are your thoughts about not including the external module/theme template files in the actual release packages (ie. Install.zip, Upgrade.zip)? The real question is do developers use the release packages to do local development - or do they clone/download the Oqtane framework source code?

**Comment by leigh-pointer** [comment]
@sbwalker I am all for that.  

So with that in mind, the Module Creator module will be removed as well, and the Develop page will no longer be there when a new framework (install) is created?

**Comment by sbwalker** [comment]
@leigh-pointer you raise a good point... I would like to avoid customizing the release if possible. Removing the Develop page from the default site template will make it a bit less discoverable by new users, but should be OK. But I do not want to remove the Module Creator and Theme Creator components from where they exist in Theme/Module Management. They already display a message that they should only be used in Development environments - and if the external template files are not included in the release then the list of templates will be empty (as they are based on the files in the Templates folder) - so it will not be possible to create a module/theme. Does this make sense?

**Comment by leigh-pointer** [comment]
@sbwalker Sound like a good solution.  

Question: So I if I was to install Templates to the (install instance)  then everything should work as before?

**Comment by vnetonline** [comment]
Agree with this change it also will reduce size of the release.

**Comment by sbwalker** [comment]
@leigh-pointer if you include templates in the appropriate folder location for Modules or Themes, the framework will recognize their existence and will allow the user to choose them in the Module/Theme Creator UI. This will continue to be supported in an Install instance.
