### ISSUE TITLE
Publish a web site other than localhost

### ISSUE THREAD

**Issue by maxmontgmx** [oqtane/oqtane.framework#3071]
Hi all,
I run oqtane server from visual studio though IIS express.
the site is working on localhost, no problem.
Now I would like to expose the web site on the LAN.
For that, I modified launchSettings.json file to modify "applicationUrl" with IP address of my PC.
I launch VS as administrator but I get an exception in GetAlias function because the server URL doesn't match with Oqtane Web sites URLs.
So what is the best practice to move the web site from localhost to LAN?
Thanks for your help

**Comment by leigh-pointer** [comment]
@maxmontgmx  You need to follow the instructions her https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis

**Comment by leigh-pointer** [comment]
@maxmontgmx in that case you can add your ip address to the site aliases.
Log in as host
Navigate to site settings
On this page you will find Aliases, here you can add a new alias.

Open a new browser and it should respond.

**Comment by sbwalker** [comment]
In 4.0.1 the "Aliases" section in Site Settings was renamed to "URLs" as new Oqtane users are not familiar with the "Alias" terminology.

**Comment by maxmontgmx** [comment]
@leigh-pointer I follow your recommandations and it's working (need to modify also applicationhost.config file to add binding entry.
@sbwalker there was a misunderstanding. I need to add an alias on a web site, not add an indirection.

Thanks for your help
