### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by MPatriot** [oqtane/oqtane.framework#3072]
I'm not sure if this is the same issue mentioned elsewhere but checkout attached short mp4.

Notice it takes a bit for error to pop up, must be how long the service took to return.

I had the same problem on localhost

https://github.com/oqtane/oqtane.framework/assets/20174265/5ef5c702-33d6-487b-8d8d-626c4e096523

**Comment by sbwalker** [comment]
What is the size of the file you are trying to upload?

**Comment by MPatriot** [comment]
I intentionally chose a small file.  That one was 9.22 KB (9,450 bytes): I have uploaded much larger files in the past.  It doesn't seem to matter if its on localhost or the actual server but prior to that I did manage to finally get a much larger video file to 'upload' on localhost though I could not duplicate that on local host with any size file after that.

Thanks,

Mark

**Comment by MPatriot** [comment]
I'm starting to wonder if there is a problem creating the new folders required for Tenant/1/ect as it would be the first file saved on a new installation

**Comment by MPatriot** [comment]
hmm, I just got it to work with 103 MB mp4 file on local host.  I was still showing the error but the file ended up being there.  I'm going to publish it and see what happens there.

**Comment by sbwalker** [comment]
As I mentioned in another thread - you should NOT deploy Oqtane using the Publish option in Visual Studio. You should deploy an official release ie. https://github.com/oqtane/oqtane.framework/releases/tag/v4.0.1

**Comment by MPatriot** [comment]
Hmm, I suppose I didn't understand.  this is the first I have heard of that.  
So how does that work on a first install?  Download and unzip Octane and then upload it FTP?

**Comment by leigh-pointer** [comment]
@MPatriot download, unzip, ftp is how i did it. One important not is disable webDAV for you site in the web.config or at the IIS installation.  If this is not done then Oqtane wont save data and a few other things.

**Comment by MPatriot** [comment]
How silly of me!  After all this time and I am like the only one out of all the people here using Web Deploy! Must be another thing I missed in those Oqtane YouTube DNF Project / Intro videos. 

Thanks guys for letting me in on the big secret!  I feel like part of the club now....

Mark

**Comment by MPatriot** [comment]
Ok, back to kindergarten for me...

Unzip and build then upload via VS ftp or FileZilla?

Build my themes or dev modules adjacent to octane and then upload 

Or back to the first question and then just install my built modules from the server app now running via the package file?

Sounds elementary but I better be sure I get it before going through the struggles I have been that others don't seem to have.

Thanks,
Mark

**Comment by leigh-pointer** [comment]
@MPatriot do you use visual studio and build with Release mode set?
If so then you can just install the package via the framework web interface or ftp the package to the packages folder, both cases you will need to restart the framework.

**Comment by MPatriot** [comment]
Ok, but with Oqtane itself, it should not have any external packages built into it like it does when in dev mode correct?
For Oqtane itself do I build it locally and then upload the contents of the server directory to the root directory on the server?  With that, do I use a different ftp app than VS or is VS publish via ftp ok?
:)

**Comment by MPatriot** [comment]
I take it all back. The .cmd files exist in the unzipped package and SmarterASP.NET does not allow those either via IIS deployment or via uploading ftp

Furthermore, the file upload gives the error even when running on local host and never having done anything but unzip and run

The trick with the file upload seems to wait after it reaches 100 percent and don't close the pop up right away but sit back and have a cup of coffee or until you determine it's probably had enough time to process. You don't know exactly because your looking at the error message and no new confirmation message comes up

That was all with a fresh 4.1 version never uploaded and now I will see what happens on the server though I suspect it will be about the same but I will have to delete the .cmd files

**Comment by MPatriot** [comment]
OK, thanks leigh

There seems to be a fundamental problem with the file upload.

Trying various sizes on localhost sometimes works and sometimes doesn't.

I do this on localhost with a freshly unziped version of Oqtane 4.1

The worst offenders are larger sizes.  When trying up to a 103mb mp4 file, whether it works or not , I always get the error message and it also seems to be recorded in the database.  Sometimes, it actually gets saved most times not.

I have yet to have success with even very small image files as shown above but I have been trying various files on localhost to avoid this whole .cmd issue.

The folks at the webhost I have been trying this on insist that those file types aren't relevant to production though I see the argument that its about packages ect (though I may not understand that part of it.)

Eitherway, the whole thing seems to be rather hit or miss even on localhost.

Mark

**Comment by vnetonline** [comment]
@Mpatriot can you try #3057 pull request i have submitted

**Comment by sbwalker** [comment]
@MPatriot I am unable to reproduce this issue in any installation - I have tried both local and Azure installations. This would lead me to believe that that problem you are experiencing is related to your environment. It is difficult to determine from the details you have provided in this thread, but it sounds like you are using IIS? It also sounds like you did not follow the installation instructions outlined here - https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis. Instead you tried to publish from Visual Studio which would result in an unsupported configuration which is likely causing the file upload issue.

In regards to very large file uploads... Oqtane uses an asynchronous and multi-threaded approach for file uploads. As a result, when you upload a file, the UI needs to poll the server to determine if a file has been successfully uploaded. However it is configured to only poll for a specific time interval (to avoid scenarios where an error may have occurred which would lead to infinite polling which would tie up the UI thread). In the event that the time interval is exceeded (15 seconds), the system displays a message "File Upload Failed Or Is Still In Progress". If this occurs it is possible that the file upload may still be in progress and will eventually complete successfully.

**Comment by MPatriot** [comment]
Thanks @sbwalker,

I did end up resolving this issue: in part, by working with the webhost and them correcting the read / write permissions on the directory.  
I say, in part, because if I create a folder it is not physically created but only added to the database.  Whether or not this is intentional and the directory on gets actually created when a file is to be saved to it or should haven at the time of its creation I do not know: I have looked at the Oqtane source code much.  Either way, I can only save to the Root directory and wonder if the read write issues will just continue down the chain with every sub directory created.
I also noticed that if when waiting, it will upload larger files even with the warning, possible not if you leave the page? Not sure.

Thanks for spending time on this, I perhaps should have mentioned I had resolved some of it however it got late and you know how the next day goes, other stuff happens.

@vnetonline, I glanced at that initially, I figure if Shaun and the other contributors see it as a good thing then it will be in a future release.  I have done my very best from the beginning to not play with the source code but if find something lacking I can always make own variation in a module.This may be different for you, perhaps you are a contributor, if so I appreciate it as I do with all the contributors: namely @sbwalker and @leigh-pointer that I know of.

Mark

**Comment by MPatriot** [comment]
@sbwalker  Again, Thanks.  I like the concept of foreign / cloud file storage possible coming in the future.  One of the problems people might have using Cloudflare type services is it doesn't fundamentally work with Blazor apps: at least not the server type, WASM is different. Cloudflare caches its files so it fundamentally can't work on a direct UI like Blazor Server: plain Core is different as it is more like MVC and makes round trips to the server.  Sending the files to the client from a cache is fine because once the client has them, well, they are no longer cached.

I may play with some of this stuff when I get past some of the basic stuff I have been learning and implementing.  I have a file server that just uses and IP address and a password with and ftp / sftp type connection but haven't yet done anything with that in a Oqtane / Blazor context.

-Mark
