### ISSUE TITLE
Request PageState.Modules[n].ModuleDefinition.Version to be populated

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3074]
With in a Theme and my component inherits from ModuleBase, when querying PageState.Modules[n].ModuleDefinition.Version the version comes back with a empty string.

my line fo code is 

`PageState.Modules.Any(md => md.PageId == PageState.Page.PageId && md.ModuleDefinitionName.StartsWith("MyCompany.MyModule") && md.ModuleDefinition.Version = "1.0.3")`

Is it possible to have the version poputlated?  

**#** I had a quick scout but couldnt find where object is populated because I am happy to do the PR for this.

**Comment by sbwalker** [comment]
There is logic in ModuleDefinitionRepoistory to Filter the module definition objects returned to prevent information disclosure to clients apps. Only the properties required by clients apps are returned.

**Comment by leigh-pointer** [comment]
@sbwalker I think version number would be ok to return right, I can't see why not ? Or am i missing something ?

**Comment by leigh-pointer** [comment]
@sbwalker In my theme I need to check the module or modules on the page and their version number.

> Adding Version means that any anonymous browser client will be able to determine the specific version of a module which the site is using

forgive me but I am trying to understand how this would be a problem?

**Comment by sbwalker** [comment]
@leigh-pointer imagine if a module version had a known security vulnerability... a malicious actor would be able to easily determine if your site is running that specific module/version. However if the version number was not available then it would be much more difficult to determine if the site was vulnerable.

**Comment by leigh-pointer** [comment]
Resolved another way.

**Comment by leigh-pointer** [comment]
Well as this was for a theme and functionality is for Admin or Host i am reusing an instance of ModuleDefinitions which i already use in the theme. This is more tighter.
