### ISSUE TITLE
ModuleInfo Dependencies list

### ISSUE THREAD

**Issue by maxmontgmx** [oqtane/oqtane.framework#3078]
Hi all,

In ModuleInfo.cs, if we declare a list of dependencies like this : 
            Dependencies = "Firm.Module.MyModule.Shared.Oqtane, AnotherDLL",
It's not working. Why, because there is a space after comma (separator). And the space stay in the name of DLL file name.

In ModuleDefinitionRepository.cs, it could be good to add line before 215 with : 
                            assembly = assembly.Trim()

Thanks

**Comment by vnetonline** [comment]
Thanks @maxmontgmx submitted the pull request with credit to you!
