### ISSUE TITLE
Best practice for module development

### ISSUE THREAD

**Issue by maxmontgmx** [oqtane/oqtane.framework#3081]
Hi all,
What is the best method to develop a module.
For moment, I start debugger with module solution. But at each modification, I have to restart IIS express server.
I tried to start server with Oqtane solution and in parallel, compile module DLLs with module solution.
But the server doesn't hot detect modification without restarting and so doesn't send new DLLs to client.

Thanks for your recommandations.

**Comment by vnetonline** [comment]
@maxmontgmx you need to build the solution and ensure that the post tasks are running there is a debug.cmd in the package project this copy's the module Dlls from the module folder to the server project.

You need to have the external module at the same level as your Oqtane framework folder.

When I develop modules I usually just run the module which has the server project as the startup project

Let me know how you go.

**Comment by maxmontgmx** [comment]
@vnetonline , I'm using exactly this method. but starting server each time we do a modification is quite long and not reactive.
That's why, I try to find a better way.
Thanks for your advice.

**Comment by vnetonline** [comment]
There is a discussion #1194 which talks about hot reload did you try these steps ??

**Comment by sbwalker** [comment]
@maxmontgmx further to what @leigh-pointer mentioned above, if you scaffold your module using the Module Creator (ie. in the Admin Dashboard of your installation... Module Management... Create Module) it will create a fully functional module solution which includes a reference to Oqtane.Server. You should set Oqtane.Server as the Startup Project and then when you run on IIS Express in Visual Studio it will launch the Oqtane Framework and allow you to hit breakpoints in your module code (assuming you have added an instance of your module to a page in your installation).

**Comment by sbwalker** [comment]
@maxmontgmx I am closing this item as it is not an "issue" - it probably belongs in the Discussion area.
