### ISSUE TITLE
JWT - breaking change - username claim is now stored as "unique_name"

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#3082]
When attempting to use JWT authentication, queries were returning a server error 500.  Upon investigation, I determined that line 101 of UserSecurity.cs was throwing an error due to a null username being passed.
` identity.AddClaim(new Claim(ClaimTypes.Name, user.Username));`

The username passed to this is pulled from the JWT claims presented.  However, line 44 of JwtMiddleware.cs is trying to retrieve a claim of "name" for the stored username which results in the null value returned.  As can be seen in the screenshot attached, when Oqtane 4.x creates a JWT token, it now includes the Oqtane username as "unique_name" and not just "name".

If you are using a JWT token issued prior to upgrading to Oqtane 4.x, then it is still functioning as normal.  However, if you generate a new token that is using the "unique_name" claim, it now fails.

This appears to be a change in the JWT functions in .Net.  The previous version of System.IdentityModel.Tokens.Jwt used with Oqtane 3.x was version 6.10.0.  From my reading it looks like this version was using an incorrect claim of "name" and it is now changed in later versions of the package to use "unique_name".

Looks like it caused issues with some Azure stuff as well:  https://github.com/Azure/azure-signalr/issues/1606

![image](https://github.com/oqtane/oqtane.framework/assets/7365166/fb833994-bf28-437b-a72b-9342b777109a)

**Comment by sbwalker** [comment]
@W6HBR so is your suggestion is to modify JwtMiddleware.cs to reference "unique_name"? And for backward compatibility should it check for "unique_name" first and then fallback to "name"? Some additional validation logic would be useful as well if UserId or Username are not found in the claims - it could log a token validation error.

**Comment by W6HBR** [comment]
Yes, I would agree that "unique_name" should be first and then fallback to "name".  Additionally, I would suggest that "name" be deprecated and removed altogether at a future time when it is not likely to cause disruption.

On a related note, an enhancement to allow issuing tokens for other than Administrator users would be helpful.  As currently implemented, only an Administrator can create a token due to the location of the feature being on the User Mgmt / Settings page.  For my own needs, I've added the option to create JWT on the user profile page.  This allows the ability to create non-admin tokens with more limited rights.

**Comment by W6HBR** [comment]
Understood.  In my use case I have a 3rd party that is synching product data from my system to Shopify.  For that I'm using a long-lived token, but also restricting their access to only specific API endpoints - thus the need for a specific user token.  By moving the create token option to the profile page, it allows the 3rd party to self-service the renewal of their own token.

**Comment by sbwalker** [comment]
Please review #3097 and test the new logic if you are able
