### ISSUE TITLE
Error in Blog module

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#310]
Probably victim of rename refactoring. I tried to make PR but i do not have correct environment set up.

Exception causes endless loop and it's wrong. Maybe some bug or design flaw in core and example how exception in module can broke whole server.

System.TypeLoadException: Could not load type 'Oqtane.Infrastructure.ILogManager' from assembly 'Oqtane.Server, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)

**Comment by sbwalker** [comment]
Yes, changing the namespace of a core class library is a breaking change. This happened as part of the work in #245 - I see that ILogManager is now part of Oqtane.Infrastructure.Interfaces. Once we get to the MVP release we wont be able to make changes like this to the core. I can fix it.

**Comment by chlupac** [comment]
Thank you and sorry, it was a mistake.

**Comment by sbwalker** [comment]
No worries. I am very grateful for the changes you made as part of #245 - much better to do them now as they are impossible to do once v1 is released.

**Comment by thabaum** [comment]
It would be good to do all the "breaking changes" now possible while at least in beta.

**Comment by sbwalker** [comment]
Resolved today
