### ISSUE TITLE
Create a dev branch

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#313]
@sbwalker could you please add a `dev` branch for nightly build development and let `master` contains the latest stabilized release

**Comment by uzabumuhire** [comment]
As we are near the release of version 1.0.0, shouldn’t we take time to discuss the testing,  versioning and GitHub workflow strategy ?

**Comment by uzabumuhire** [comment]
How will new features be added ? What are the criteria for including a new feature ? Will each new feature require integration and unit tests ? Are existing features covered by tests ? Are we using semantic versioning (SemVer) standard ? 

Another aspect is the documentation of Oqtane to help new comers to get productive faster.

I would like contribute to documenting, testing and putting in place the contributor GitHub workflow and versioning release strategies. 

The goal should be to make Oqtane reliable for professional  production usage.

**Comment by hishamco** [comment]
Hope to hear @sbwalker opinion

**Comment by thabaum** [comment]
I thought it would be a good idea to put documentation on the Oqtane GitHub homepage if not in a second repository.

Maybe we can then create a fairly easy way to include search and browse features of the documentation from within Oqtane down the road.

We all I believe have the similar goals in mind with respect to Oqtane.  

My past experience as far as helping out with open source projects like this if you are willing to contribute just follow a few guidelines and you can get things submitted to Microsoft open source projects as I have in the past.

- Display your concern appropriately so it is easily understood by anyone.  Shorter to the point explanations with screenshots whenever you can post one.  Create your issue
- If you have a solution for that issue you then create a PR and present it.  If it does not get accepted find out why and move on.  You generally find out what the good, bad and ugly is.  
-  Don't be shy or scared  as these are collaborative efforts with a project lead with eyes looking clear down the sights at the target. Learn from each PR now to make yourself productive in any Open Source project is my goal.   
-  Try to follow any guidelines or formal layouts to submit requests to help expedite your issues and solutions.

As of right now up until v1 release we are fly by the night "dev" branch.  After this we will more likely have a "dev" branch as discussed here I believe you can bet on.

**Comment by hishamco** [comment]
@sbwalker it's the time to make this happen, please make `dev` the default branch, so it will be used for nightly builds

**Comment by thabaum** [comment]
call it vNext

**Comment by hishamco** [comment]
@sbwalker could please create `dev` branch so the stable release will be on the `master` branch?

**Comment by hishamco** [comment]
@sbwalker seems you forgot to create a `dev` branch after releasing `2.0.0` could you add it please, so the nightly builds should target `dev` branch

**Comment by sbwalker** [comment]
Yes I will create a dev branch. All enhancements for 2.1 will need to be done on the dev branch.

**Comment by sbwalker** [comment]
So I am assuming I should create a "dev" branch and make it the default branch - correct?

**Comment by hishamco** [comment]
Exactly, and let the `master` have the `2.0.0` version. It would be nice if you tag all the versions, please let me know if you need a help

**Comment by sbwalker** [comment]
The releases are all tagged

**Comment by sbwalker** [comment]
OK, "dev" is created and it is now the default branch. How do I retarget your PRs to the dev branch?

**Comment by hishamco** [comment]
> How do I retarget your PRs to the dev branch?

Let me check

**Comment by hishamco** [comment]
@sbwalker I retarget the branch for all the new PRs, ready to merge and it's the time to close this

**Comment by hishamco** [comment]
BWT don't forget to check the branch for old PRs before merge

Thanks

**Comment by hishamco** [comment]
@mikecasas @jimspillane @ADefWebserver please aware of the branch changes in your upcoming PRs
