### ISSUE TITLE
Logging Level not saved

### ISSUE THREAD

**Issue by artmedia** [oqtane/oqtane.framework#3130]
Hello,
I'm using v.4.0.0 on IIS with SQL Server (runtime server + prerender).
On production instance, when I try to change the "logging level" in Control Panel -> System Information -> Options
it is not saved
My procedure:
- change logging level from "Error" to "Debug"
- click on Save button
- click on Restart Application button
- app restated
- logging level is still Error 

The strange thing is that it works fine on dev instance (same configuration but on localhost)

thanks
Luca

**Comment by leigh-pointer** [comment]
@artmedia First you need to check that webDAV is disabled.

Add this to your web config

```
    <system.webServer>
      <modules>
        **<remove name="WebDAVModule"/>**
      </modules>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified"/>
        **<remove name="WebDAV"/>**
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Oqtane.Server.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="inprocess"/>
    </system.webServer>
  </location>
  <system.web>
```

**Comment by sbwalker** [comment]
@artmedia the logging level is stored in the appsettings.json file. Perhaps your environment does not have the rights to modify the file?
