### ISSUE TITLE
Module NuGet package not copied to Oqtane tree

### ISSUE THREAD

**Issue by markagama** [oqtane/oqtane.framework#3138]
In the example provided by @ADefWebserver found [here](https://www.syncfusion.com/succinctly-free-ebooks/custom-blazor-oqtane-modules-succinctly/create-the-help-desk-module) he writes:
Build the external module using release then
When we view the Oqtane.Server/wwwroot/Modules directory of the Oqtane solution, we see the NuGet package for the module has been copied to that location. When we run the Oqtane application, it will scan this directory and see that the module is to be installed or upgraded.

When I do this there is no NuGet package in the Oqtane tree.
Is this a bug?

**Comment by sbwalker** [comment]
If you compile the module in Debug mode the module DLLs are automatically deployed for you. If you compile in Release mode a nupkg is created and automatically deployed for you.

**Comment by markagama** [comment]
thx @sbwalker, I'm struggling to get a working module with syncfusion blazor controls. The examples that I've found are for earlier versions of Oqtane, and don't appear to work now. Any examples for Oqtane 4 that you know of, please let me know.
