### ISSUE TITLE
External vs inline module development

### ISSUE THREAD

**Issue by markagama** [oqtane/oqtane.framework#3139]
In the example provided by @ADefWebserver found [here](https://www.syncfusion.com/succinctly-free-ebooks/custom-blazor-oqtane-modules-succinctly/create-the-help-desk-module) he writes:
Set the Template to external

In Oqtane 4 there is no external nor inline option
Is this a bug?

**Comment by vnetonline** [comment]
@markagama  The develop page and the modules and theme templates were removed from release packages #3069

Clone the dev branch that's how I do my development.

**Comment by markagama** [comment]
Hi @vnetonline thx for the response. I just checked and I cloned the dev branch for Oqtane version 4.0.2

**Comment by vnetonline** [comment]
Can you see the modules and theme templates now ?

**Comment by markagama** [comment]
Hi @vnetonline, I was able to create a module that is external using ModuleCreator, but the drop down list did not include Expternal and Inline, like the example I'm following. There are not themes that I can see.

**Comment by vnetonline** [comment]
You create theme from the themes screen in admin dashboard

**Comment by sbwalker** [comment]
The Inline template option for modules and themes was removed in Oqtane 2.0 as it resulted in a tight coupling of the code which complicated the ability for a developer to upgrade the framework. There is now only a single External template option provided.

**Comment by markagama** [comment]
thank you @sbwalker
