### ISSUE TITLE
Oqtane module 4.0.2 nuspec

### ISSUE THREAD

**Issue by markagama** [oqtane/oqtane.framework#3140]
Created a module using ModuleCreator.
added files to the nuspec following the example [here](https://www.syncfusion.com/succinctly-free-ebooks/custom-blazor-oqtane-modules-succinctly/add-syncfusion)
Set build to release and rebuild all.
Warning:
Successfully created package 'C:\share\Repos\Syncfusion.Module.Helpdesk\Package\Syncfusion.Module.Helpdesk.1.0.0.nupkg'.
5>EXEC : warning : NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
5>- Add a dependency group for .NETCoreApp7.0 to the nuspec

the nuspec currently reads
 <dependencies>
   <dependency id="Oqtane.Framework" version="4.0.2" />	 
 </dependencies>

Is this to be expected? How to fix?

**Comment by vnetonline** [comment]
Can you share your release.cmd from the packages folder

**Comment by markagama** [comment]
attached - I edited the nuspec to try to fix the dependencies warning that I received. The debug.cmd was edited based on @ADefWebserver example on Syncfusion website.

**Comment by sbwalker** [comment]
You can ignore these warnings - they do not affect the ability to install a module or theme package.

**Comment by markagama** [comment]
thank ypu @sbwalker - if there is a working example for syncfusion controls in Oqtane 4, I would appreciate being pointed at the example.

**Comment by sbwalker** [comment]
Closing as the original item reported is not an issue in the Oqtane framework. General questions related to how to use Oqtane should be asked in Discussions.
