### ISSUE TITLE
Extra message that shouldn't be showing

### ISSUE THREAD

**Issue by Tony20221** [oqtane/oqtane.framework#3163]
I added a module creator to a page then deleted it as I wanted to start fresh.
Clicking the gear icon still shows 'Module Added to Page'. Had to refresh to make it go away.

![image](https://github.com/oqtane/oqtane.framework/assets/99626433/92ae1916-0c1c-4c41-876b-0165712a8903)

**Comment by vnetonline** [comment]
I will take a look at this and see what can be done

**Comment by leigh-pointer** [comment]
In my opinion the message should appear on the page and not in the control center! When you click to you are looking at the page ! Just makes sense!
