### ISSUE TITLE
Title is blank after adding a module

### ISSUE THREAD

**Issue by Tony20221** [oqtane/oqtane.framework#3164]
I gave a title to a new module creator and after it was added, the title field is blank.

![image](https://github.com/oqtane/oqtane.framework/assets/99626433/fe432e7c-90ef-4800-9044-c10d283539e3)

**Comment by vnetonline** [comment]
I am not sure what you mean I can see the title says `Tony's Blog`

**Comment by Tony20221** [comment]
The title box in the right side. Maybe it's used only for entering the title and not showing the current title. I guess it's OK.

**Comment by vnetonline** [comment]
Yes that's right it is only for entering title of the module you are creating .... you can have multiple modules on the page in different panes
