### ISSUE TITLE
Capitalizing the first letter of each word

### ISSUE THREAD

**Issue by Tony20221** [oqtane/oqtane.framework#3165]
Can I make a suggestion and not capitalize the first letter of each word in these type of sentences? This is a sentence and not a title. Also add a comma, after 'application' to properly segment the long sentence.
It makes it harder to read, adds cognitive load to the brain and just looks weird.

![image](https://github.com/oqtane/oqtane.framework/assets/99626433/eeaf8bb3-40ec-4b91-bd39-f763ec778cee)

**Comment by vnetonline** [comment]
I will fix this
