### ISSUE TITLE
Error loading module error

### ISSUE THREAD

**Issue by Tony20221** [oqtane/oqtane.framework#3166]
I keep getting this error message after activating the module creator module. 
I have deleted Oqtane's folder and the database and started fresh 3 times and I keep getting the same issue. I am cloning the repo.

Can the error message be more descriptive and tells me why Oqtane is having problems loading the module? Examples would be... its definition is not in the database, error loading a certain file, issue loading a certain dependency and so on.

![image](https://github.com/oqtane/oqtane.framework/assets/99626433/49a9ab90-4645-4c46-9f24-e6a8d0033360)

**Comment by vnetonline** [comment]
Can you copy and paste the whole error msg please

**Comment by Tony20221** [comment]
Error Loading Module {"ModuleId":31,"SiteId":1,"ModuleDefinitionName":"Tony.Module.Blog, Tony.Module.Blog.Client.Oqtane","AllPages":false,"DeletedBy":null,"DeletedOn":null,"IsDeleted":false,"PermissionList":[{"PermissionId":183,"SiteId":1,"EntityName":"Module","EntityId":31,"PermissionName":"View","RoleId":2,"RoleName":"All Users","UserId":null,"IsAuthorized":true,"CreatedBy":"tony","CreatedOn":"2023-08-20T05:23:07.8485664","ModifiedBy":"tony","ModifiedOn":"2023-08-20T05:23:07.8485664"},{"PermissionId":184,"SiteId":1,"EntityName":"Module","EntityId":31,"PermissionName":"View","RoleId":5,"RoleName":"Administrators","UserId":null,"IsAuthorized":true,"CreatedBy":"tony","CreatedOn":"2023-08-20T05:23:07.8485664","ModifiedBy":"tony","ModifiedOn":"2023-08-20T05:23:07.8485664"},{"PermissionId":185,"SiteId":1,"EntityName":"Module","EntityId":31,"PermissionName":"Edit","RoleId":5,"RoleName":"Administrators","UserId":null,"IsAuthorized":true,"CreatedBy":"tony","CreatedOn":"2023-08-20T05:23:07.8485664","ModifiedBy":"tony","ModifiedOn":"2023-08-20T05:23:07.8485664"}],"Settings":{"ModuleDefinitionName":"Tony.Module.Blog, Tony.Module.Blog.Client.Oqtane"},"PageModuleId":0,"PageId":0,"Title":null,"Pane":null,"Order":0,"ContainerType":null,"ModuleType":null,"PaneModuleIndex":0,"PaneModuleCount":0,"ModuleDefinition":null,"SecurityAccessLevel":0,"ControlTitle":null,"Actions":null,"UseAdminContainer":false,"CreatedBy":"tony","CreatedOn":"2023-08-20T05:23:07.846156","ModifiedBy":"tony","ModifiedOn":"2023-08-20T05:31:31.4443544"}

**Comment by Tony20221** [comment]
I don't get the logic in this method. IsAuthenticated is returning true for me. Why then it's an error?

   protected override async Task OnInitializedAsync()
   {
       Module module = await ModuleService.GetModuleAsync(ModuleState.ModuleId);
       if (UserSecurity.IsAuthorized(PageState.User, RoleNames.Host))
       {
		AddModuleMessage(string.Format(Localizer["Error.Module.Load"], module.ModuleDefinitionName), MessageType.Error);
       }

       await logger.LogCritical("Error Loading Module {Module}", module);
   }

**Comment by sbwalker** [comment]
The Module Creator can only be used by Host Users - which is the reason for the UserSecurity.IsAuthorized(PageState.User, RoleNames.Host) validation. If you added an instance of the Module Creator module to a page in your site and then browsed to that page as a non-host user then this error would be raised.

**Comment by sbwalker** [comment]
In the last release we removed the external templates and Developer option from the default site template. Does it also make sense to remove the Module Creator module so that it cannot be added to a page - and rely on the Create Module option in Module Management instead? This would prevent people from adding the Module Creator to pages which do not have appropriate permissions.

**Comment by sbwalker** [comment]
@leigh-pointer this is a different issue than the templates. Currently there is a Module Creator module which can be added to any page in a site via the Control Panel. There is also a Create Module option in Module Management. They both do the same thing ie. they scaffold a new module from a template. My question is if we need the Module Creator module or should just rely on the Create Module option.

**Comment by vnetonline** [comment]
@sbwalker I agree that the module creator module should be removed and developers should create modules from the module management page just like themes are created which provides consistency.

**Comment by Tony20221** [comment]
> The Module Creator can only be used by Host Users - which is the reason for the UserSecurity.IsAuthorized(PageState.User, RoleNames.Host) validation. If you added an instance of the Module Creator module to a page in your site and then browsed to that page as a non-host user then this error would be raised.

My Oqtane has only a single user. Myself, the user that was created when Oqtane was set up. My role is 'Host Users'. I get the error.  Maybe you can try it.

SELECT r.name FROM [User] u
JOIN UserRole ur ON u.UserId = ur.UserId
JOIN Role r ON ur.RoleId = r.RoleId

**Comment by sbwalker** [comment]
@leigh-pointer any concerns about removing the Module Creator module which is available in the Developer category in the Control Panel for adding to a page? This would require a host user to utilize the Create Module option in Module Management if they want to create a module.

**Comment by leigh-pointer** [comment]
@sbwalker I have no concern with removing it from the Control Panel.  I think it make more sense creating a new module from the Module Management area.

**Comment by sbwalker** [comment]
removed in #3193
