### ISSUE TITLE
Why there's ability to delete master database

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#317]

**Comment by sbwalker** [comment]
Can you please provide more detail. Are you asking why there is an ability to delete the Master Tenant?

**Comment by hishamco** [comment]
> Are you asking why there is an ability to delete the Master Tenant?

Exactly

**Comment by sbwalker** [comment]
I agree that the framework should prevent people from deleting the master tenant

**Comment by hishamco** [comment]
I will do a PR for this
