### ISSUE TITLE
Password notice & punctuation

### ISSUE THREAD

**Issue by MPatriot** [oqtane/oqtane.framework#3174]
Hello,

Even though Require Punctuation is off anyone notice the rule notice still says its required?

Not using punctuation does not raise an error so in most ways its not a big deal but its probably confusing to new users.

Mark

**Comment by leigh-pointer** [comment]
@MPatriot on investigation the complete list of settings are not being returned.  I think this is because of security permissions as the message is displayed at registration.

I will look further.

**Comment by leigh-pointer** [comment]
@sbwalker  is it, (Im guessing it is) necessary to have the IdentityOptions settings IsPrivate set to true?

**Comment by sbwalker** [comment]
@leigh-pointer IsPrivate indicates if a setting should be shared outside of the trusted server environment with untrusted clients (ie. via the Settings API). The majority of User Settings fall into this category, as they are confidential. However I believe you are specifically asking about Password Complexity options. You would need to evaluate the risk of disclosing this information to anonymous clients - does it make it easier for a malicious actor to attack the installation? Hypothetically it would allow someone to determine if a site is using weak passwords - which would then make it easier to target them for a brute force attack. So this is truly a tradeoff between security and user experience - as the Registration logic is designed to help a user choose a valid password (whereas it also provides hints to malicious actors).

**Comment by sbwalker** [comment]
One possible option might be... do not lower the IsPrivate requirement for Password Complexity options (ie. keep them secure)... and add a password requirements API method on the server which has the ability to access the options, construct the message within the method and return it to the client. This API call would be called by the Register module. It would still reveal internal information to anonymous users - however if a site owner had disabled user registration then it would not be possible to obtain this information.

**Comment by leigh-pointer** [comment]
@sbwalker that sounds like a good possible option.

**Comment by sbwalker** [comment]
@leigh-pointer I looked into this and its going to be fairly complicated to implement because of the localization requirements. I will investigate further because in its current form it does not actually serve its intended purpose - rather than informing the user what the password complexity rules are for the site, it will instead inform the user what the default password complexity rules are for an Oqtane installation.

**Comment by MPatriot** [comment]
Thanks for checking this out...

My main concern was more along the lines of functionality, not to worried about security.  Form never closes and its not clear to the user if anything happened or to go check mail ect.

I suppose I could add punctuation back as @leigh-pointer suggested, but what a pain for the user (including me)  Its a pain enough with all the other rules

I have also thought about making my own module which would then allow me to customize all of it and check for other things...customize the confirmation email ect.
I plan on it eventually anyway.

Thanks
-Mark

-Mark

**Comment by sbwalker** [comment]
@leigh-pointer this is resolved in #3192. Note that this required the use of a RESX file in the Server project. RESX files in the Server were always supported, there has just not been a need for any up until this point. However, what this means for translators is that there would be an Oqtane.Client.resources.dll and an Oqtane.Server.resources.dll. These DLLs could be packaged into a single Nuget package and will install fine into Oqtane.

**Comment by leigh-pointer** [comment]
I need to explore this! Now we currently ship a single resource dll! Therefore some build scripts will need to change.

**Comment by sbwalker** [comment]
@leigh-pointer Another option would be to change the API method to return a Dictionary which contains the specific password complexity settings - but only under the specific conditions implemented in the API method. This would keep the resources on the client so that there would not be a need to manage server resources. Would this be a better option?

**Comment by leigh-pointer** [comment]
@sbwalker ok. We cant give this info for free but it i very annoying when you dont know what is needed.

**Comment by sbwalker** [comment]
@leigh-pointer i think I will need to use the other option I outlined above as I just realized that although the UI thread has culture cookies set, the HttpClient which handles API calls does not - so the localizer may not be able to do the translation on the server without further code changes.
