### ISSUE TITLE
Tenant is null

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#318]
Getting an exception when starting the app that the tenant is null after adding an additinal site.

Steps to reproduce.
1) Pull latest commit c9b
2) Clean install
3) Start app - everything is fine
4) Add new site - everything is fine
5) stop app - I am using VS 2019, IIS express
6) start app - see error message below

![tenant](https://user-images.githubusercontent.com/11261164/78018448-e3b7b480-731b-11ea-8c62-d8714b1b5dae.PNG)

**Comment by chlupac** [comment]
Thanks for report, fix is on the way.

**Comment by chlupac** [comment]
done.

**Comment by mikecasas** [comment]
Closing as fix is tracked in #320.
