### ISSUE TITLE
Ampersand in module description causes failure to load projects

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#3231]
The inclusion of the ampersand in a module description causes each project of the solution to fail to load.  
Example description:  "**Lookup & reporting module**".

Trying to manually load the project will return the error:  
`The project file could not be loaded.  An error occurred while parsing EntityName. Line 8, position 32.`

Manually editing the project file and changing the offending character will resolve the issue.

**Comment by thabaum** [comment]
Have you tested using `&amp;` instead of `&` see if it works?

**Comment by sbwalker** [comment]
@W6HBR Thank you for reporting. The fields in the module and theme creator will either need validation or encoding to prevent this from happening.

**Comment by W6HBR** [comment]
> 

Yes, that does work, but it wouldn't be intuitive for people to type their description that way.  It needs to be encoded before saving.

**Comment by sbwalker** [comment]
@W6HBR the *.csproj file is an XML file so rather than encoding invalid XML characters I opted to validate the field and only allow alphanumeric characters and spaces.
