### ISSUE TITLE
Bug:  Page Content Body scripts not being added to source

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3236]
```
<script src="js/custom.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
```

After adding these lines to the Page > Body Content I do not see these loading in source.

they do not get loaded.

Add them to Site Settings and the tags are added.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/9ac0b2a8-e77d-4109-85dd-857e0b2e3634)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/fc94aef1-d839-4fba-8103-7eff59352e70)

**Comment by sbwalker** [comment]
@thabaum I beleive this issue is also caused by your changes in #3232

**Comment by sbwalker** [comment]
@thabaum Please note that scripts will not appear when you do a view source on the page because Blazor requires JS Interop to manage JavaScript (which is why they are removed from the Head component). The scripts are injected dynamically and will only be visible through the browser dev tools.

**Comment by sbwalker** [comment]
@thabaum you were correct that there was an issue with script injection in some specific scenarios - please test #3240

**Comment by thabaum** [comment]
The leftover `</script>` is gone as you can see from my testing screenshots below.

I am using the following respectfully:
```
Head
<script src="~/js/page-custom.js"></script>
<meta rel="page head content meta">
<script src="~/js/page-custom2.js"></script>
<meta rel="page head content meta 2">
<meta rel="page head content meta 3">

Body
<script src="~/js/page-custom4.js"></script>
<script src="~/js/page-custom3.js"></script>

```

Still an issue on top of this one is "Page Body Content" is not being rendered (no scripts are being added to body content from page settings)

Site Settings Page and Body Content BOTH render as I set them with "page" or "site" in the names to reflect where it was set.
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/47958786-6c54-44ee-b9f1-8d5f4d8ea31c)

As you can see site scripts load in both Body and Head Content areas however page Body/Head Content nothing gets added to be rendered for **scripts** and in fact I dont know what you can render for **page body content** to show up from the `Page Settings > Page Content > Body Content` edit page field:

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/0fb71e86-ed39-426a-9732-4c20e895958b)

**Comment by sbwalker** [comment]
Page Settings / Page Content / Head Content supports scripts, CSS references, meta tags, etc... The help text says:

"Optionally enter content to be included in the page head (ie. meta, link, or script tags)"

Page Settings / Page Content / Body Content only supports scripts. The help test says:

"Optionally enter content to be included in the page body (ie. script tags)"

There is no content other than scripts which is valid for injecting into the bottom of the body section of a page.

**Comment by thabaum** [comment]
Correct,
Currently the framework is:
- removing scripts from Page Settings > Page Content
- not including ANYTHING from Page Settings > Body Content

Is this what is to be expected?

**Comment by sbwalker** [comment]
@thabaum are you doing a View Source for the page in the browser or are you using the Browser Dev Tools (F12) to view the HTML markup? If you are using View Source you will not see the Page Content scripts as they are dynamically injected at run-time on the client - you will only be able to see them in the Browser Dev Tools (F12).

**Comment by sbwalker** [comment]
The current code in the dev branch works for me. I believe the issue you are seeing is because you are not using the Browser Dev Tools (F12) to view the HTML markup.

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/ea8acd1f-7ccf-4516-a9dc-60fe3fe9a74f)

**Comment by thabaum** [comment]
I see what you are saying here.  You are correct.  I was looking at generating the same results for Page Settings that the Site Settings creates for "view source" and also correct they are loading dynamically.  

I generally use Firefox or Edge and this explains things further I was just looking at it wrong.

Thanks for explanations as this clears this up for me.  Moving on...
