### ISSUE TITLE
How to create a lot of modules connect many orther database(mysql, postgresql server...)

### ISSUE THREAD

**Issue by mithang** [oqtane/oqtane.framework#3251]

**Comment by sbwalker** [comment]
Your custom modules can access whatever databases they need:

namespace YourCompany.YourModule.Repository
{
    public class YourModuleContext : DbContext, IService
	{
		private readonly IConfigManager _config;
		private readonly IDatabase _database;

		public YourModuleContext(IConfigManager config)
		{
			_config = config;
		       _database = Activator.CreateInstance(Type.GetType("{A Type Name Of An Oqtane Database Provider}")) as IDatabase;
		}
        
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
            optionsBuilder.UseOqtaneDatabase(_database, _config.GetConnectionString("{A Connection String Name From AppSettings.json}"));			
        }

        // DbSets
        public virtual DbSet<Models.YourModel> YourModel { get; set; }
    }
}

**Comment by sbwalker** [comment]
closing as this is not technically an "issue" - in the future please create questions like this in Discussions
