### ISSUE TITLE
Not possible to move menuitem to another submenulocation in PageManagement

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#3255]
It's not possible to move a menuitem to another sublocation (before/after)  in PageManagement. You only get a list of the mainmenu's - not the submenus.
![image](https://github.com/oqtane/oqtane.framework/assets/76835718/1b9a389d-58e5-4610-be80-1fe2eef156cc)

![image](https://github.com/oqtane/oqtane.framework/assets/76835718/dc372a0d-0a04-4382-9d87-6c32883f3793)

This is how it should look like (ex: from adding a new page):
![image](https://github.com/oqtane/oqtane.framework/assets/76835718/602dc57a-8e5a-46ee-b645-bf7710b493da)

**Comment by sbwalker** [comment]
@beolafsen please test #3257 - both for editing pages and adding new pages - there are so many different combinations related to changing the parent page and choosing where to move the page within the parent's pages.
