### ISSUE TITLE
Enhancement:  User Profile Setting for "Biography" TextArea or HTML WYSIWYG Component Options

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3276]
Enhancement to Profile Management supporting a TextArea set by adding more rows > 1 like ` rows="4" ` setting for creating profile properties?  If rows setting is greater than one then use TextArea input.

Also it would be even better to have an option to allow the HTML Editor module WYSIWYG and save HTML if allowed for Bio area with some basic word editor like options for general styling purposes to store content needed for a profile setting.

This would be for a profile setting such as a place for a user to set a biography.

I would post this in ideas but I think it is needed unless there is already an option I am overlooking to allow a profile setting like this to be available to administrators for their site users.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/b32e2c0b-f292-46cb-a204-871778d68f3b)

**Comment by sbwalker** [comment]
Support for a text area does make sense. Allowing users to enter HTML is a security concern which I would prefer to avoid.

**Comment by W6HBR** [comment]
TextArea's in the profiles would be a welcome addition.  

I did my own customization in UserProfile to support that, but it might not be the best way to add support to the base framework.  I made a modification that uses an embedded definition in the "DefaultValue" field. 
e.g. DefaultValue = "[TextArea,8]This is a default value with embedded TextArea definition."

Oddly enough, GetProfileValue() in UserProfile.Index.razor already supports filtering out an initial bracketed value (e.g. [TextArea,8]) when displaying the default values.  Not sure why that was implemented there already, but I used it to my benefit.

**Comment by thabaum** [comment]
> Support for a text area does make sense. Allowing users to enter HTML is a security concern which I would prefer to avoid.

I did have that security concern as well.  I was hoping maybe we could build something that is very primitive or limited in options like other CMS's have for user input.  Basic bold, italic, headings features along with user lists but nothing beyond that.

I would not mind making a `UserEditor` component to take some input more than basic, something very similar to what we are using now here in GitHub....

**Comment by sbwalker** [comment]
@W6HBR the "bracketed" values are an internal implementation detail which was added so that it is possible to indicate that a setting is [Private] or [Public]. In reality it is a "hack" but it was required in order to maintain backward compatibility for the Settings dictionary. I would highly recommend to NOT use your own "bracketed" values as it will conflict with the internal behavior of the Setting API (which only expects [Private] or [Public].

**Comment by sbwalker** [comment]
@thabaum support for textarea is fine, but we will not be adding HTML support to the user profile at this time.

**Comment by W6HBR** [comment]
@sbwalker Thanks for the background on why the bracket support was there.  Short-term, I'll probably keep my code in place until the TextArea support is added.  My usage is only for public values, but I see your point on why not to use this hack.

**Comment by sbwalker** [comment]
completed in #3362
