### ISSUE TITLE
Enhancement: Importing Pages with settings, modules, module settings and module data/content

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3277]
Similar to new feature introduced #3267 Oqtane could use logic to import pages with settings along with placing content including text/HTML into an Oqtane HTML module component on the page.  

This should be enhanced further to:
-  Import multiple HTML modules for each content block to be added along with location on the page layout if exists or places the HTML content into the HTML module with content displayed in default pane.  
-  Add other modules that exist in the installation to theme layout panes available in currently selected site theme for a page to import these module settings and data for other modules on that page that should exist these should also get included.

Some modules just need some settings set and away they go... others will need properties filled with data or an HTML Module with HTML or Text.

`Save Page as Template` is another feature that should branch off this along with`Save Site as Template` and maybe even `Save Module as Template` for a cherry on top.

This is probably already on the roadmap.  This is some feedback towards the feature if it can be included as I expect eventually it will.

**Comment by sbwalker** [comment]
@thabaum the framework already provides the ability to create a site from a Site Template, upgrade a site using a Site Migration,  or add pages/modules/content using Routable Modules (https://www.oqtane.org/blog/!/62/routable-modules). There is currently no plan to provide an import capability based on an uploadable flat file. However a module developer could certainly create one.

**Comment by sbwalker** [comment]
@thabaum based on your recent questions I am guessing you are looking for an automated migration path from DNN to Oqtane - is this correct? I agree that this would be a useful solution - however it does not belong in the Oqtane framework itself - it should be created as a third party module. I will be providing some information about this topic in the coming weeks as I was recently looped in to some of the current challenges in the DNN ecosystem.
