### ISSUE TITLE
[ENH] Themes - Navigation Menu Support For More Than 2 Levels

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3280]
Oqtane currently shows the Parent and it's child, but not a child of a child page.  There should be an arrow going to the right/left to expand out the next children of the parent page even if the parent page is a child of another parent page.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/36eba8ad-64cb-4335-9a3a-87b934e8c4ca)

I have a page that is included in menu that is a child of page `Child 1` and is not visible

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/4822c978-1c2c-4ce3-ada8-8c0d90cd7d7b)

**Comment by sbwalker** [comment]
The horizontal menu in Oqtane currently supports 2 level of navigation (I believe the vertical menu also only supports 2 levels). We can certainly include this on the roadmap for the future. If someone needs this capability today there is always the option to create your own menu component or use a menu component from a third party component library if you need to support more hierarchical levels in your themes.

**Comment by sbwalker** [comment]
@thabaum FYI... the new https://github.com/oqtane/Oqtane.Theme.Arsha theme example supports 3 levels of navigation in its menu. It uses CSS styles and structure which is specific to the BootstrapMade template it is based upon. But it demonstrates that Oqtane can support 3+ levels of menus.

**Comment by thabaum** [comment]
@sbwalker should this issue be closed as it is up to the theme to create this support.  A DDR Menu type of component that can be reused in themes(Navigation)/components(Modules)/pages(Panes) to display links and sub pages as custom desired with as many sub levels and setting which page is the parent for different trees a UI may need to display would be ideal potentially? Oqtane has many themes now so no sense trying to include this in all themes as Oqtane demonstrates it is up to the theme to set this currently.
