### ISSUE TITLE
DefaultLayoutType value is "string.Empty"

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#330]
I know there was some refactoring done, so now in Client/Modules/Admin/Sites/Add.razor when the layout type is null the DefaultLayoutType contains the value "string.Empty". Was this the desired result?

![add-site](https://user-images.githubusercontent.com/11261164/78354139-55406e80-7579-11ea-9d00-fcd7949ee833.PNG)

When adding a new site with the Blazor theme and no default layout I get this error.

![chul1](https://user-images.githubusercontent.com/11261164/78354267-8faa0b80-7579-11ea-9b3b-2ea64b95af7c.PNG)

**Comment by mikecasas** [comment]
Guess it's coming from here:

```
 <td>
            <label class="control-label">Default Layout: </label>
        </td>
        <td>
            <select class="form-control" @bind="@_layouttype">
                <option value=string.Empty>&lt;Select Layout&gt;</option>
                @foreach (KeyValuePair<string, string> panelayout in _panelayouts)
                {
                    <option value="@panelayout.Key">@panelayout.Value</option>
                }
            </select>
        </td>

```

**Comment by sbwalker** [comment]
@hishamco please see above.
