### ISSUE TITLE
Interfaces should be moved to correct namespace

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#331]
It's important question, breaking changes before 1.0. last chance to do it.
![image](https://user-images.githubusercontent.com/7838468/78362124-d61f5a80-75b9-11ea-8181-004d35ac388a.png)

**Comment by sbwalker** [comment]
yes, please go ahead

**Comment by hishamco** [comment]
Sometime the namespace are not corresponding to the file location, IMHO `Interfaces` folder is way to group the interfaces, but don't mean that should be in `Oqtane.Services.Interfaces`

I saw this in many OSS

**Comment by sbwalker** [comment]
Actually I agree with @hishamco. After reviewing the changes I really do not like the fact that a developer has to include a reference to 2 namespaces for the same concern - it seems totally unnecessary and redundant. Although refactoring tools might recommend folders should match namespaces it does not always make sense. I am inclined to roll this back.

**Comment by hishamco** [comment]
FYI there some places in the code where namespace doesn't match file location for instance `IDeleteable`, `IAuditable` .. etc

**Comment by chlupac** [comment]
ok, roll back ??  I have no problem with this decision.

**Comment by sbwalker** [comment]
@chlupac Thank for creating the PR to roll this back My apologies for wasting your time.
