### ISSUE TITLE
I am getting this error can't figure out why http://localhost:44357/api/Log 

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#3313]
2023-09-25 04:50:31+00:00] [Error] [Oqtane.Security.AutoValidateAntiforgeryTokenFilter] AutoValidateAntiforgeryTokenFilter Failure For http://localhost:44357/api/Log

**Comment by sbwalker** [comment]
This is not enough information to do any further investigation or analysis. This error occurs when there is a POST, PUT, or DELETE request which does not contain a valid Antiforgery token (meaning it may be an XSRF attack). You can read more in this blog:

https://www.oqtane.org/blog/!/42/customizing-antiforgery-behavior-for-cookies-and-bearer-tokens

In general I have only seen errors when a user is redirected to a third party site and then is redirected back to the Oqtane site, at which point their Antiforgery token is no longer valid. There is a technique for handling this scenario documented in this blog:

https://www.oqtane.org/blog/!/43/antiforgery-and-blazor

**Comment by thabaum** [comment]
I did notice a warning in Firefox with SameSite cookie being treated as "Lax" and if you want to work with any third party it would need fixed.

```
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “APP_VISITOR_1” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read [https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite](https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite) [localhost:44357](http://localhost:44357/)
Cookie “.AspNetCore.Culture” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read [https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite](https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite)
```
Not sure if part of the issue but I remember DNN going through some issues to get this resolved properly if I recall.

I was going to look further into this to see if it was something that needed resolved for Oqtane when I had more time then bring to attention if it was...

**Comment by sbwalker** [comment]
closing as not enough information to reproduce
