### ISSUE TITLE
BuiltOnBlazor: Screenshots are wrong

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#3314]
Sorry for posting his here, but I can't find a repo for built-on-blazor. If there's a better place to put this, just point me in the right direction 😉.

I just added https://blazor-cms.org/ but the screenshot is wrong. This is what is shown in https://builtonblazor.net/

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/c0fd1f6e-bec6-4e04-bc7a-49347aaf0f4a)

This is what it actually looks like:

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/525a27aa-5361-4065-8548-954000119cb6)

Not sure what's causing issues here, my guess is that it's not using a good server-side screenshot tool.

**Comment by leigh-pointer** [comment]
@iJungleboy there is no public repo for this. This a project of @sbwalker

**Comment by sbwalker** [comment]
builtonblazor.net is a site I created for the .NET community ~2 years ago. Screen shots are generated by a third party service using a scheduled job - https://restpack.io/. I am closing this issue as it is not related to Oqtane.
