### ISSUE TITLE
BuiltOnBlazor: Wish for Category and better browsing experience

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#3316]
The site already has 16 pages which are hard to navigate. 

Some recommendations:

1. Ability to add a category. I understand this could be tricky, because it would require more data to be stored - either requiring a login, or the website could add some open-graph header such as `og:article:section`
2. Improve pager to show a list of pages, allowing to skip to page 4...

**Comment by sbwalker** [comment]
Closing as not related to Oqtane

**Comment by sbwalker** [comment]
I do not plan on including a login capability for the BuiltOnBlazor site at this time.
