### ISSUE TITLE
When giving write permission in roles to admin

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#3338]
@sbwalker As I was clocking off for the day I have noticed that when you go to manage the roles module and give write permissions to admin the permissions table has the EntityId as -1 and the permissions don't stick.

I also notice that the roles repository is not adding the permissions like it is doing in pages repository 

Is this normal to have EntityId as -1??

**Comment by sbwalker** [comment]
yes, global permissions have an entityif of -1

**Comment by vnetonline** [comment]
When you say global you mean for that site right ?

**Comment by sbwalker** [comment]
correct

**Comment by sbwalker** [comment]
@vnetonline should I close this issue? There is not enough information to determine if it is actually a problem - and no steps to reproduce the problem.

**Comment by vnetonline** [comment]
Yup it's fine I figured it out ... thanks for checking @sbwalker
