### ISSUE TITLE
Error when try to edit page in PageManagement

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#3343]
I get this error when I try to enter a Page in PageManagement.
[ErrorPageManagement.zip](https://github.com/oqtane/oqtane.framework/files/12748849/ErrorPageManagement.zip)
![image](https://github.com/oqtane/oqtane.framework/assets/76835718/42eb6f76-bda5-4f88-a3b3-f9567cc90188)

![image](https://github.com/oqtane/oqtane.framework/assets/76835718/07777962-6de4-42c6-8afa-aaba48d98d8f)
![image](https://github.com/oqtane/oqtane.framework/assets/76835718/784c0f2b-f00c-4567-8226-ce7175ef38a9)

**Comment by beolafsen** [comment]
Version 4.0.4

**Comment by beolafsen** [comment]
In debug:
![image](https://github.com/oqtane/oqtane.framework/assets/76835718/170d8766-aad4-4b79-90d6-b542f3533851)

**Comment by leigh-pointer** [comment]
You need to upgrade to 4.0.5

**Comment by beolafsen** [comment]
Ok. Thanks. Mvh BEO28. sep. 2023 kl. 13:39 skrev Leigh Pointer ***@***.***>:﻿
You need to upgrade to 4.0.5

**Comment by beolafsen** [comment]
Thanks :-) It works.
