### ISSUE TITLE
Drag&Drop Modules between panes in edit mode

### ISSUE THREAD

**Issue by mohamad-asghari** [oqtane/oqtane.framework#3348]
Is it possible to add the ability to drag&drop modules between different panes?

**Comment by sbwalker** [comment]
yes it would technically be possible to add drag and drop... it has just not been a priority because Oqtane is not intended to be a "site builder" for non-technical users - it's target audience is developers.

**Comment by leigh-pointer** [comment]
I have actually been toying with the idea in RocketFuel as I think this functionality should Theme based and not Framework.

> Oqtane is not intended to be a "site builder"

**Comment by sbwalker** [comment]
I think this would be best implemented within a theme rather than in the framework
