### ISSUE TITLE
Language Selector menu alignment.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3368]
The menu should be right aligned for readability. 

@sbwalker  I have done some work for a PR but due to the fact that the **LanguageSwitcher** component is embedded in the **Control** component, A **Parameter** needs to passed down.  It works ok, and the default would be left as is, but Oqtane theme would need to change?
 
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/3b34f61d-891c-49b5-8aa4-9b855448d315)

![image](https://github.com/oqtane/oqtane.framework/assets/9447612/60967ec5-766c-4f62-903b-6468dac291f4)

**Comment by hishamco** [comment]
Can I handle this?

**Comment by sbwalker** [comment]
@hishamco I believe @leigh-pointer said he has already created the PR

**Comment by hishamco** [comment]
@leigh-pointer if you already have a PR then submit it or I will do a quick one

Thanks
