### ISSUE TITLE
Custom module exporting

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#338]
Any guidance on exporting a custom module that was created by the framework? I was going to start writing a PowerShell script to copy the files out to a project.

**Comment by sbwalker** [comment]
If you want to create an independent module you should look at the blog module for reference: 

https://github.com/oqtane/oqtane.module.blogs

There are a variety of modifications which are necessary.

**Comment by sbwalker** [comment]
The Blog module was updated today to be compatible with the latest framework changes.
