### ISSUE TITLE
Consistent Naming Convention Issue

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3389]
There are a few places I noticed could use some help with being consistent with current naming conventions within the Oqtane Framework code base.

Too many to list here, but not a huge amount.  I took some notes for most areas that may use some help in this area while created PR #3387.

If it sounds OK "to do" I can submit another PR today that can include these adjustments to some of the variable names within methods I am referring to.

A PR would not add any new features, fix any real identifiable bugs, add enhancements or generate framework issues other than making the code base more consistent while reading it.

@sbwalker Let me know I can do it as a contribution soon.  I maybe off thinking they are to be named camelCaseNames but that is the issue is some are lowercasenames or Upperlowercase.  I can submit them by sections of the framework instead of the entire framework at once like #3387 if you like for an easier review of the changes or put them all into one PR as you like.  Other option is it can be left as is.

**Comment by sbwalker** [comment]
@thabaum I left a note in #3387 -  but I will include it here as well. I will not merge PRs created by automated tools. When PRs are submitted which modify massive amounts of code there is no way to ensure that they do not contain regression bugs or breaking changes.

**Comment by thabaum** [comment]
I did not use an automated tool.  I did this entirely by hand looking into every file in Visual Studio, Then I created a branch in my Oqtane Fork, then I went through each file by hand and edited each file.  

I didnt use anything "Automated" it was a lot of work...

**Comment by sbwalker** [comment]
@thabaum if it was manual, then it concerns me even more. My point is that PRs must be highly focused so they they can bew reviewed in isolation, tested appropriately, etc... Please do not submit PRs which contain changes to hundreds of file - they will not be accepted.

**Comment by thabaum** [comment]
@sbwalker my apologies, it felt like a long time to do 100 PR's.  Dont accept it... there is a list of files there you can roll through and review when you want to clean up things.

After you get the updates done for .NET 8, maybe this will be helpful.

But I went through each file like it was each it's own PR and reviewed it carefully.  I can't see a reason from my experience programming these changes will cause conflicts, but you are far superior to my abilities and not trying to compete in any way.  Just trying to help.

I will close the issues, you can refer to them when you like, Some are just fixing spelling errors in comments, others are fixing some formatting issues, and others just remove namespaces Visual Studio was showing as not necessary.

Thank you.
