### ISSUE TITLE
Unable to add product to Sandbox market place

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3391]
I created a new account and entered the Owner Information.  Clicking on Products does nothing.

**Comment by sbwalker** [comment]
@leigh-pointer this should be resolved now - please try again

**Comment by leigh-pointer** [comment]
@sbwalker product created and uploaded.  Product not showing up in the sandbox marketplace.

**Comment by sbwalker** [comment]
@leigh-pointer thank you for letting me know... I am investigating

**Comment by sbwalker** [comment]
@leigh-pointer the issue with your product listing is that you specified a Version which is Compatible from 4.0.3 to 4.0.3 - which basically means this product is only compatible with a single Oqtane Framework release - version 4.0.3. You will want to change the "To" value to "< Select Version >" (to indicate it is compatible with all future releases after 4.0.3). I could probable improve the UX by including an option for < Not Specified > to make it clearer. Also the versions should probably be sorted in descending order - correct?

**Comment by leigh-pointer** [comment]
@sbwalker thanks, silly mistake.  As far as sorting, I think it is ok the way it is.  
On another point, is it possible to to get the license for my own site as I don't really want to be purchasing my products?

**Comment by sbwalker** [comment]
@leigh-pointer Yes. Once you have defined your Licenses you should see a "Keys" button in the grid for each type of license. This allows you to generate a license key for an installation.

**Comment by leigh-pointer** [comment]
@sbwalker  When creating the License I get this message.
"License Key Generated Successfully. A Notification Has Been Sent To The Email Specified And The User Will Be Able To Activate The Product In Their Installation." What do they activate is with because the only thing that is sent by email is : 

Product: StudioElf.Product
License: Commercial License
Installation: 540e6ba8-xxxxxxx-installation-key
Expiry: 31-Dec-9999
Email: leigh.pointer@email.com

There is no License Key sent.

**Comment by sbwalker** [comment]
@leigh-pointer I should also mention that you will want to generate keys from the production site - not the sandbox. The license keys generated in the sandbox are only valid for 7 days (to prevent abuse of the licensing service).

**Comment by leigh-pointer** [comment]
@sbwalker I remember you saying in the Market Place Talk you did.

**Comment by sbwalker** [comment]
@leigh-pointer I assume your module is using the Oqtane.Licensing component.... meaning that you have wrapped the main UI (index.razor) in a LicensedView component. When a user adds your module to a page in their site, the LicenseView will determine it is not yet licensed and will display a Licensing dialog. The user can select Activate and then Fetch license and then Fetch License and the component will retrieve the license from the server - it does not need to be entered manually. The only caveat is that if you are using your module in a localhost environment the Licensing dialog will not be displayed (as you are doing development) - but it can be forced with a querystring parameter &licensing=manual

**Comment by sbwalker** [comment]
@leigh-pointer I think I will need to record a video which walks through all of the scenarios in the marketplace - the earlier presentations focused too much on the "why" for the marketplace - not the "how"

**Comment by leigh-pointer** [comment]
@sbwalker not a bad idea.  I have successful added a product to the market place.  Is there a procedure that will allow for free upgrades and / or hot fixes?

**Comment by sbwalker** [comment]
@leigh-pointer there does seem to be an issue with the key generation, as I can see an error in the log. I will investigate further.

**Comment by sbwalker** [comment]
@leigh-pointer there are a number of errors in the log related to generating license keys - are you able to share some of the details of what you tried to do in the UI which resulted in the errors?

**Comment by leigh-pointer** [comment]
I tried to generate the license key after adding the installation id and email. I tried it a couple of times reloading the ui.

**Comment by sbwalker** [comment]
@leigh-pointer it appears that you have not activated the key yet... would it be ok if I removed the license you created and had you do it again so that I can try to figure out why an error is being generated? I have a number of products listed in the marketplace and I activated them on my own sites using the "Licenses" feature and it worked fine - so I need to determine what is different about your scenario.

**Comment by sbwalker** [comment]
@leigh-pointer actually I think I figured this out. You generated a trial license key. And then you generated a commercial license key. And then you tried to generate a commercial license key again 3-4 more times - however a commercial license key had already been generated for that installation and product license,  so a duplicated error was thrown but never communicated back to the UI.

**Comment by leigh-pointer** [comment]
@sbwalker so do i need to create two licenses? One trail and another commercial?

**Comment by sbwalker** [comment]
@leigh-pointer if a product allows trials, then when a user adds the module to their site a trial license will be automatically generated for them - which provides usage for a limited number of days. However a user can also choose to purchase a real license during the trial period and activate it as well. In this case there are 2 valid licenses but the non-trial should take precedence. In your case you generated a real license for your own installation - which should take precedence over the trial license.

**Comment by leigh-pointer** [comment]
@sbwalker so in the market place i only need to create the trail license, and the rest is manage by the system (market place)?

**Comment by sbwalker** [comment]
@leigh-pointer I do not understand your question. When you create a product in the marketplace you define whether it allows for a trial period by specifying the number of days (default is zero meaning no trial) - you do not create an actual Product License for the trial in the marketplace.

If a product allows a trial period it will be available for download from within the Oqtane Framework (similar to open source products). When a user downloads/installs it, and then adds it to a page, a trial license key will be automatically generated for them with an expiry based on the trial number of days allowed. Trials cannot be extended.

**Comment by sbwalker** [comment]
@leigh-pointer if you try to generate a commercial license key for an installation and product license which has already been licensed previously, the marketplace will no longer throw an exception - it will return the existing license key.

**Comment by leigh-pointer** [comment]
@sbwalker, just tried it. Thanks
