### ISSUE TITLE
Enhancement: Site Management -  Include Server/WebAssembly/Hybrid Runtime in site list.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3393]
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/f178d7da-159d-43ed-a594-3952f08ef140)

It would be nice to see what runtime each site is using without having to click edit next to the Url in the Site Management pager list.

A tooltip that shows more details would be awesome too without having to click edit?!  While testing I would like to see which site is setup for different uses. 

 I am currently running multiple instances for as many scenarios as I can from one upgraded instance of Oqtane to test .NET 8 and feel this enhancement of showing the runtime each site uses would be helpful.
 
 I do use "Site Name" as well to describe each site purpose but i cannot view (edit) if I created a site on a different database in "WebAssembly" or "Hybrid" runtimes.  The sites each have their own database but are not launching (blank site pages) all on different ports.

**Comment by sbwalker** [comment]
@thabaum this is a good idea... however the HostingModel information is located in the Site table - and based on the fact that an Oqtane installation can have isolated tenants (ie. multiple databases) it means that this information would have to be aggregated from multiple databases. In addition for security reasons, the current API does not allow you to make cross-tenant requests. So it will not be feasible to implement this enhancement.
