### ISSUE TITLE
Table Names/Prefix

### ISSUE THREAD

**Issue by bbakermmc** [oqtane/oqtane.framework#34]
Looking at the SQL Scripts, what do you think about prefixing all the tables with "oqt" or something, if applying this to an existing DB there could be conflicts, plus when running code generation it would be nice to say ignore tables starting with "xxx".

Also not sure what Alias is.  Can a Tenant have multiple sites?  This table seems to be a junction between Tenant and Site, so shouldnt the name be TenantSites?

I assume the Master DB is installed to its own db?

**Comment by sbwalker** [comment]
The project supports multi-tenancy using separate databases. The "master" database contains only the Tenant and Alias tables. 'Tenant" databases contain the other tables. Master and Tenant tables can be in the same database for simplicity - which is the way the project is configured by default. The Tenant table has the ability to specify a DBSchema field value which allows all tables in that tenant to have a unique schema ( which is similar to using a table prefix ).
