### ISSUE TITLE
Issue: .NET 8 - WebAssembly Hosting Model Site - Page Error Stops Rendering Resulting in Blank Page (Theme Background Only).

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3401]
Upgrade Oqtane Solution to .NET 8
Upgrade all .NET packages to latest
Create a site with server hosting model, switch to webassembly hosting model
OR
Create a site with webassembly hosting model 

The below are results found:

Page renders with only a background color (using "Blazor Theme" here "Oqtane Theme" would be a black background) 

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/3ce10f6f-c590-43a3-9a51-5733f13c8f45)

Source Image of Error:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/af49a12c-ffbc-43ca-82e9-5af1a19b3382)

Dev tools Error:

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/b0007a2b-40fa-46e7-9910-d68390ed7602)

```
Debugging hotkey: Shift+Alt+D (when application has focus)
blazor.webassembly.js:1  Error: Failed to start platform. Reason: TypeError: Cannot read properties of undefined (reading 'dotnet.wasm')
    at Vt (blazor.webassembly.js:1:62226)
(anonymous) @ blazor.webassembly.js:1
blazor.webassembly.js:1  Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at blazor.webassembly.js:1:37659
    at blazor.webassembly.js:1:38464
    at Object.start (blazor.webassembly.js:1:46018)
    at Vt (blazor.webassembly.js:1:62202)
```

Could be related to my upgrade however it builds using Preview and I did go through all the files including the ENTIRE solution looking for anything relating to net7.0 and even 7.0.  Only place left was in the readme file which I left alone.

From all the testing I had performed this was the only issue I had found which is a potential showstopper if can be verified.

**Comment by sbwalker** [comment]
Are you able to share your *.csproj file contents - this might help identify the issue

**Comment by sbwalker** [comment]
@thabaum all of your package references in your project files are still pointing to .NET 7 packages. You can take a look at this new branch I just created: https://github.com/oqtane/oqtane.framework/tree/net8

**Comment by thabaum** [comment]
Gotcha, I was wondering how-to upgrade the packages to preview. I will download that branch and work from within it.

**Comment by thabaum** [comment]
That seems to have fixed this issue, I am closing.
