### ISSUE TITLE
Extend models with navigation properties and data annotations

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#341]
Database model is not complete. POCO classes are not in sync with database representation.
For full use of linq and database possibilities, I miss navigation properties in model. Also data annotations should help for starting with validators. If we plan to move from DbUp to database migrations, we have also to implement model builder configuration. Maybe is time think about this topic because here will be necessary changes in some core classes.

DBSets in DBContext should be named in plural, eq
```c#
 public virtual DbSet<Site> Sites { get; set; }
``` 
to avoid confusion between model class name and dbset name

**Comment by sbwalker** [comment]
Using Migrations is on the roadmap for V.Next ( if it’s determined to be feasible as It has some major limitations in my experience ). Module developers should not be referencing repository classes - they should rely on the public API as it the layer where backward compatibility will be supported. So I don’t think I understand the comments about navigation properties.

**Comment by chlupac** [comment]
It's about core and core development, and it's about programming style. I'm used to have them from times of LinqToSql and edmx-based model in EF. For example if you have site, page and module navigation properties you do not need *Template classes and you can build site model graph directly and save it in one transaction. 
Also for permissions. What i do not understand is reason why permissions are packed and unpacked from-to a string again and again. It's not effective and complicated. 
I'm developing database applications where I have to do complex queries. I'm not able to do them effectively without navigation properties.
And finally, I'm not friend of Repository classes with 1:1 to tables. One generic repository for basic crud  is enough. I like to have DB context exposed and have full control what is loaded to graph and combine entities in query as I need. And repository in my point of view is place where business happens, all around is separation and communication. Should be task - oriented, no table - oriented. 
```c#
        public SiteRepository(TenantDBContext context, IRoleRepository roleRepository, IProfileRepository profileRepository, IFolderRepository folderRepository, IFileRepository fileRepository, IPageRepository pageRepository,
            IModuleRepository moduleRepository, IPageModuleRepository pageModuleRepository, IModuleDefinitionRepository moduleDefinitionRepository, IPermissionRepository permissionRepository, IServiceProvider serviceProvider,
            IConfigurationRoot config)
        
```
... this is overkill ... one (two) dbcontext is enough for task, why call repository classes in repository class

**Comment by sbwalker** [comment]
Fair enough. You might have certain preferences for the core framework architecture. I might have different preferences. And other developers who will contribute to Oqtane in the future will surely have preferences that are different than you or I. At this stage the core framework is functional and if the goal is to align the Oqtane 1.0 release with the release of Blazor WebAssembly in May then we need to focus on stability. As a result I am not in favor of exploring these types of impactful changes right now.

**Comment by chlupac** [comment]
We can close this discussion now. It's theme for future. And I have lot of ideas :). Maybe some of them will be acceptable, and I'm sure than lot of them not. It's good, and I really appreciate  than you are resistant to crazy ideas and you are leading project to 1.0.
