### ISSUE TITLE
Issue: UserProfile/Index.razor - Notification tab not focused after viewing/canceling or sending messages.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3417]
After you send or view a notification a user will no longer be focused on the notifications tab which is the area the would expect to be after clicking send or view-cancel (close).

**Comment by thabaum** [comment]
@sbwalker this one is a bit tricky since it changes the id attribute for the element dynamically within the TabPanel UI component.

Not sure if a "Return Url" can be set without passing a parameter or some trick code.

**Comment by sbwalker** [comment]
TabStrip allows for the specification of an ActiveTab parameter:

	[Parameter]
	public string ActiveTab { get; set; } // optional - defaults to first TabPanel if not specified. Can also be set using a "tab=" querystring parameter.

It also supports a Querystring parameter which may be an easier option here ie. when redirecting from Add or View component pass a Querystring parameter of "tab=Notifications"

**Comment by thabaum** [comment]
> It also supports a Querystring parameter which may be an easier option here ie. when redirecting from Add or View component pass a Querystring parameter of "tab=Notifications"

I believe this is what I was looking to do.  The issue is the button submit action url needs to focus on notifications and instead is taking to default tab instead of active tab.

I will work on this today along with the other PR to resolve issues as I would like to understand how to use the TabStrip component further and this allows me to play with this part of its features.

Thank you.

**Comment by sbwalker** [comment]
@thabaum I was able to get this working... it will be included with some other changes I will merge tomorrow (I noticed that the UserProfile/View.razor did not have localization implemented properly).

**Comment by thabaum** [comment]
I did notice the View.razor wasn't using the Oqtane Label control along with a resource key similar to the other components.

Since I did do the PR to resolve this discussed issue here, I will leave it up as I made and adjustment to simplify the @bind for you to review and possibly include with your changes.  Just close the PR when done reviewing don't need to include it if you have it worked out already.

One other note is the Close "X" button created by the Admin Modal was the only other issued noticed that will take a user away from the active tab.

That pretty much wraps up all bigger issues I have found in this user profile and notifications area while testing for .NET 8.

**Comment by thabaum** [comment]
PR #3443 knocks this baby out the park!

Nice work @sbwalker and thanks for explaining the `PageState.ReturnUrl` I think I had ran into this once before in another PR a while back so this should finally sink in ;)

Usernames can now be accessed to send messages to
Close X and Cancel now navigates to the proper tab

Its like I am living a dream here!

Thanks I am closing this issue.  You Rocked it!
