### ISSUE TITLE
Issue: Profiles/Edit.razor: Form Validation For Rows, Length and Order Input Fields

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3426]
Rows needs to allow numbers from 1 or greater for input validation.
If a value less than 1 is entered into rows or letters are entered in any other fields that should only accept numbers where numbers in the Edit.razor form the green check mark should be a red exclamation mark to show those inputs need set properly with valid input expected.

Reproduce the error placing characters where numbers are expected.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/9f5bf02e-cae2-4cf0-ad88-0b6faeeccfb9)

**Comment by thabaum** [comment]
@sbwalker I have fixed the validation for the rows,

The validation of Length and Order are next while I am here.

I understand Length is to be 0 or higher (Numbers only)

But for "Order" I want to be sure you will allow 0 which seems to be default or should this be 1 or greater?

**Comment by sbwalker** [comment]
@thabaum In general I would recommend fixing the specific issue and not adding other enhancements

**Comment by thabaum** [comment]
@ I kept it simple in the new PR using the ` type="number"` attribute in the input elements of the form.

**Comment by thabaum** [comment]
closed with #3347
