### ISSUE TITLE
Enhancement: Create Sites With "Biography" TextArea Input For Default User Profile Settings

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3428]
I propose an enhancement added to the Oqtane Framework default site creation of a "Biography" `textarea` input under the "Personal" category that displays the use of the new enhancement of `textarea` elements created when creating profile settings with `Rows > 1`.

**Comment by sbwalker** [comment]
Not approved. The default Profile settings for a site should be as minimal as possible. If someone wants to include additional profile items for a site they can create their own custom site template - that is the purpose of offering this extensibility option.

**Comment by thabaum** [comment]
We are able to add this to a "Site Template" ? as I was wanting to add a number of sites with a Biography plus others as they are "community" sites or applications.

**Comment by sbwalker** [comment]
Oqtane contains 2 site templates - Empty and Default. Developers can create their own - they simply need to implement the ISiteTemplate interface. This interface has existed since Oqtane 1.0 and provides flexibility to do anything you want ie. it is not constrained by any serialized file format.

**Comment by thabaum** [comment]
Great, music to my ears.  I am just taking things in steps to get into the entire framework while making a few final calls prior to .NET 8.  This project has helped me a lot and I really appreciate all the time and effort you put into this project and answering my issues while reviewing some off the hook pull requests and ideas.

Just have to be reminded time and again where the boundaries are exactly located and I know I have asked in the past some things like this back probably before version 1.  I just see if any budge goes one way or another.  It's great that we can introduce sections for a Biography and other fields users can input.

I guess my next real push will be to more understand all the templates for things like sites, modules and themes to build some other custom templates generating quick starting points for different types or versions.

Then start working on some sites in production I can maintain and upgrade.  I am actually more interested in the mobile application so when I get my new system setup for this I should be able to test those areas as well.  I am currently running my VS on a VM.  I should load a few more VMs for Linux hosting and some other models to test and configure like "web farms". 

I have been studying the custom router in Oqtane and look forward to seeing whatever changes you are working towards.  Microsoft cant afford anyone to answer questions like mine, but they can sure leach a good idea like no other.  Fun stuff, all part of the game right ;)

Closing the issue.
