### ISSUE TITLE
WebSocket error within high security environment

### ISSUE THREAD

**Issue by nicpitsch** [oqtane/oqtane.framework#3438]
### Describe the Issue

Calling a Blazor based Website from within a high security environment fails with a *Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.*:

![grafik](https://github.com/oqtane/oqtane.framework/assets/1652835/04b29a05-7027-4dc9-b65f-bbb0b984c5a5)

Having a citrix access within that environment I could reproduce it myself calling some Oqtane based websites like www.oqtane.org, www.oqtane-cms.org and my own website www.pitsch-ing.ch.  Every one of them with the above error.

### Reproduction steps

The high security environment is used within a governmental organization. I don't know the technical details. That's why I can't tell how to reproduce. 

### Discussion

As WebSockets is involved, the issue is Oqtane *Blazor Server* only based?

As www.blazorhelpwebsite.com doesn't fail **EDIT 1**:  ~~I supose it's Oqtane *Blazor WebAssembly* architecture, isn't it @ADefWebserver?~~ It's Blazor Server based: https://github.com/oqtane/oqtane.framework/issues/3438#issuecomment-1775981293

Trying some sites from https://trends.builtwith.com/websitelist/Blazor and https://github.com/AdrienTorris/awesome-blazor#sample-projects I didn't find one failing within the above environment. But I can't imagine the issue is limited to Oqtane?

The issue is Blazor based, as I didn't encounter problems launching other several websites.

**EDIT 2, 3**: After being called from within the above high security environment, the error.log of my website - which is Oqtane 4.0.6, Blazor Server - contains this message: *[2023-10-24 16:21:21+00:00] [Error] Unhandled exception in circuit 'e9f9J4Qx_6dx-UKitnT4n_TUx0Y0P0uB5w1KS2My8R8'.    at Oqtane.App.OnParametersSetAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\App.razor:line 83
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()*

**Comment by ADefWebserver** [comment]
@nicpitsch - Wow the only thing I can think of as to why BlazorHelpWebsite.com doesn't have the issue is that it is running a very generic version of Blazor Server only (See [https://github.com/ADefWebserver/Blazor-Blogs/blob/main/BlazorBlogs/BlazorBlogs.csproj](https://github.com/ADefWebserver/Blazor-Blogs/blob/main/BlazorBlogs/BlazorBlogs.csproj)) . Oqtane is more complicated because it allows for Blazor Server and Blazor WebAssembly.

**Comment by nicpitsch** [comment]
After being called from within the above high security environment, the *error.log* of my website - which is Oqtane 4.0.6, Blazor Server - contains this message: *[Error] Unhandled exception in circuit 'nVZyNePBu8Q9oScW61snYdg0mkBxh8jSINTveGuQ0DA'.    at Oqtane.App.OnParametersSetAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\App.razor:line 70
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()*

**Comment by nicpitsch** [comment]
@sbwalker I have launched http://www.oqtane.org at about [2023-10-24 15:33:34+00:00] GMT+2. Do you have an entry in your error.log?

**Comment by sbwalker** [comment]
This error seems to match the date/time you shared:

[2023-10-24 15:33:43+00:00] [Error] Unhandled exception in circuit 'UJPFen9Id40rvnhnT8LOtwEdGvHEqi9nLU6d2FSYVT0'.    at Oqtane.App.OnParametersSetAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\App.razor:line 83
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by thabaum** [comment]
Would a Try catch statement resolve this and maybe give more details?

IHttpContextAccessor has been deprecated and Microsoft.AspNetCore.Localization relies on a few packages to install.  Oqtane uses 3 of these deprecated namespaces:

```
Microsoft.AspNetCore.Localization
Microsoft.AspNetCore.Http
Micrsosoft.Net.Http.Headers
```

These are the build errors and do relate to this area of Oqtane.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/669da114-c6c8-43e4-aca9-b34422fc40a6)

Maybe the use of these namespaces needs to be investigated.

**Comment by nicpitsch** [comment]
It's the same message as I get for my website (see *EDIT 2* above), but my message points to *App.razor:line 70*, which is `SiteState.IsPrerendering = !accessor.HttpContext.Response.HasStarted;`

**Comment by sbwalker** [comment]
@nicpitsch please try this Url from within the high security environment to see what result you get:

https://www.oqtane.org/api/Installation/installed/?path=

**Comment by sbwalker** [comment]
It is strange that you have a different line number identified. In your case it is clearly coming from the call to IHttpContextAccessor.  This logic sets a flag indicating if the server is pre-rendering... however that IsPrerendering flag is not actually used anywhere in the framework - it was added when we were experiencing all of the challenges with getting JavaScript/CSS to register properly.

**Comment by sbwalker** [comment]
Is it possible that the high security environment is doing something which prevents an HttpContext from being created? There must be some explanation as to why this logic works fine in other environments (ie. I have never seen this error before).

**Comment by nicpitsch** [comment]
> It is strange that you have a different line number...

Sorry, my error messages from my Oqtane 4.0.6 website point to the same line number 83. I have tried some other from my testing websites and as it seems have mistaken.

**Comment by nicpitsch** [comment]
An Oqtane Server version 3.0.3 app is running within that environment without problems. I have  instructed them to install it according to e.g. https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis.

**Comment by thabaum** [comment]
@nicpitsch doing a little research on the issue here,

 [Enabling Web Sockets on IIS][(https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#iisiis-express-support](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#iisiis-express-support))

Has resolved similar issues relating to HTTPContext for others.

**Comment by nicpitsch** [comment]
@thabaum I have double checked WebSocket Protocol setup based on your url. It's mentioned in Step 1 in https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis.

**Comment by thabaum** [comment]
@sbwalker how does Oqtane handle [Website Origin Restrictions](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#websocket-origin-restriction)  Can you refer me to this logic?  The multi-tenancy maybe an issue?

@ADefWebserver does your site just run one?  I am pretty sure from past discussions the Oqtane site runs a few.  Correct me here if I am wrong.  Thank you.

**Comment by nicpitsch** [comment]
Maybe one of the DevTools messages would help?

```ini
Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

Warning: Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection. To troubleshoot this, visit https://aka.ms/blazor-server-using-fallback-long-polling.

Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'.
```

I don't understand how to setup e.g. `DetailedErrors: true`  for my website as it's a production environment.

**Comment by thabaum** [comment]
Does Oqtane support "Long Polling" ?

As this is the fall back when network-level restrictions prevent WebSocket communication like most likely Citrix would do along with many other VPNs with similar configurations.  I have used and supported Citrix in the past for clients so I know this is highly restrictive.

**Comment by thabaum** [comment]
@sbwalker As a final thought would a Try-Catch block be helpful handle this exception in the App.razor file?  I might try to create a virtual environment that makes this error using Linux.  Best of luck figuring it out!

**Comment by sbwalker** [comment]
@nicpitsch when I get some time this week, I will add some exception handling to the OnParametersSetAsync() and do a custom build and deploy to oqtane.org so that you can test accessing it from the high security environment. I would like to validate that the problem is actually related to HttpContext before we make any code changes.

**Comment by nicpitsch** [comment]
I made an Oqtane deploy on Azure based on [Oqtane Deploy to Azure](https://blazorhelpwebsite.com/ViewBlogPost/40). Calling that Oqtane website from within the high security environment fails with the same two first errors as reported in the initial issue description.

**Comment by nicpitsch** [comment]
@sbwalker I found a workaround by checking the existence of HttpContext in App.razor, line 68:

```c#
// if (accessor != null)
if (accessor != null && accessor.HttpContext != null)
```

The above change applied in Oqtane 4.0.6 master source, deployed  (by usage of release.cmd) to my production environment on Windows Server solves the issue. I discovered however that a login to my site within the high security environment fails.

This [comment in aspnetcore concerning an issue about 'httpContextAccessor.httpcontext is null'](https://github.com/dotnet/aspnetcore/issues/39485#issuecomment-1011971531) discourages the usage of HttpContextAccessor directly or indirectly in the Razor components of server-side Blazor apps (look at [NET 7](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0#ihttpcontextaccessorhttpcontext-in-razor-components), [NET 8](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-8.0#ihttpcontextaccessorhttpcontext-in-razor-components)).

**Comment by sbwalker** [comment]
@nicpitsch thank you for identifying the issue in the high security environment. 

As I mentioned above the logic which determines if the app is prerendering can be removed altogether as there is nothing in the framework which utilizes the property. 

The login issue is obviously related to HttpContext as well - but it will require some additional exploration. The interesting thing is that this logic has existed since Oqtane 1.0 and has never been reported as an issue previously - so it is very unique to your high security environment. The question is why... and I am guessing the answer is because the environment does not support web sockets so is falling back to using long polling - which means HttpContext does not exist and I assume there would be other side effects as well - especially related to performance as polling is not an efficient communication approach.

**Comment by sbwalker** [comment]
Interesting... it looks like Microsoft tried to disable long polling in .NET 6 due to the degraded user experience, but then reverted the change because of "some unforeseen effects of it"

https://github.com/aspnet/Announcements/issues/470

**Comment by nicpitsch** [comment]
> I am guessing the answer is because the environment does not support web sockets so is falling back to using long polling

The WebSocket based error messages listed in Dev Tools are:

1) *Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.*
2) *Warning: Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection. To troubleshoot this, visit https://aka.ms/blazor-server-using-fallback-long-polling.*

I have made some testing again by calling some sites I know or found in [Websites using Blazor](https://trends.builtwith.com/websitelist/Blazor). Presuming a site having `<script src="_framework/blazor.server.js"></script>` is Blazor Server hosting model (BS) and `<script src="_framework/blazor.webassembly.js"></script>` is Blazor WebAssembly hosting model (BW).

| Site | Hosting Model | WebSocket error | Site does load |
| --- | --- | --- | --- |
| www.oqtane.org | BS, Oqtane based | 1) 2) | no |
| www.pitsch-ing.ch | BS, Oqtane based, [fixed](https://github.com/oqtane/oqtane.framework/issues/3438#issuecomment-1793403680)  | 1) 2) | yes |
| xyz | BS, Oqtane based | no | yes |
| www.blazorhelpwebsite.com | BS, not Oqtane based? | 1) 2) | yes |
| childcarefinder.wisconsin.gov | BS | 2) | yes |
| ppg.com | BS | 1) 2) | yes | 
| baukasten.stadt-zuerich.ch | BW |  no | yes |

xyz = a solution that I provide to an administration, accessible within the high security environment (I don't tell the real url). Dev Tools state: *Information: WebSocket connected to [xyz]*.
