### ISSUE TITLE
Control Panel not allowing Publish Page or Delete Page

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3479]
![CantDeleteModControl](https://github.com/oqtane/oqtane.framework/assets/9447612/90ba7e08-5536-408f-bbc3-9517d730a30a)

**Comment by sbwalker** [comment]
@leigh-pointer is this happening when running the code in the dev branch? in Visual Studio 2022 17.8? I cannot reproduce.

**Comment by leigh-pointer** [comment]
@sbwalker these issues are running from an IIS installation. I built an install pkg from the recent dev branch and deployed to IIS. In dev i also had no issue but in IIS i did.

**Comment by sbwalker** [comment]
@leigh-pointer I tested installing the Oqtane.Framework.5.0.0.Install.zip package which I created using the release.cmd based on the latest code in the dev branch... on my local IIS install... and it works fine

**Comment by sbwalker** [comment]
@leigh-pointer based on the screen shot your installation has other custom modules, etc... installed as well... which is the only difference I can think of
