### ISSUE TITLE
Focus on Module Development

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#348]
One of the most important aspects of Oqtane is the ability to extend the core functionality with custom functionality via modules and themes. And as we prepare for the 1.0 release next month it is critical that the development/deployment experience for these types of extensions is as streamlined and optimized as possible. As a result I would appreciate if we could all shift our focus from refactoring the core framework, to testing/validating the module development experience. If I could use a metaphor... at some point you need to stop tuning the engine and take the car for a drive.

I am going to outline a few practical development scenarios for modules/themes below and try to provide some context for each one so that we can explore them in more detail...

1. Internal Development
  - create modules "in-line" within the framework code base ( current ModuleCreator facilitates this approach )
  - put the entire framework and your custom code in the same source control management repo
  - debugging/testing simply involves running the Oqtane solution and setting breakpoints in your custom code
  - deployment requires you to build the entire solution and deploy your assemblies ( which are a combination of Oqtane and your custom code )
  - automated install/upgrades would require a naming convention for your scripts so that they are executed during upgrade
  - synchronizing with the latest framework releases would require you to pull down the latest framework source code and overlay your existing code.

2. External Development or Class Library Development
  - create modules in their own independent folders ( current Blog example module uses this approach )
  - need to reference the framework as a class library dependency
  - put your custom code in source control management ( as well as the framework class library )
  - debugging/testing can be accomplished using the standard method of attaching to a process during debugging
  - deployment requires you to build your custom code and package it as a nupkg package, copying to /wwwroot/Modules for auto installation
  - automated install/upgrades supported as long as scripts are embedded in assembly
  - synchronizing with the latest framework releases would require you to pull down the latest framework class libraries and make sure your custom modules are compatible
  - development requires additional explicit references, etc.. which are not required for in-line development. Also if you want a module to function in both Server and WebAssembly modes you cannot use DI for your client service classes ( there is a technical limitation related to when/how WebAssembly downloads and loads DLLs to the browser )
  - for commercial vendors, nupkg packages can be distributed to other users and they can be installed interactively through the framework UI, or by copying them to the wwwroot/Modules folder.
  - for commercial vendors, nupkg packages can also be uploaded to Nuget.org and as long as they are tagged with "Oqtane" and "Module" they will be available for automated installation within the Oqtane UI. 

There are working examples of both of these approaches however I believe they could be improved to make them more productive and simple.

**Comment by aubrey-b** [comment]
Do you want comments and concerns posted as issues or raised in the chat?

**Comment by sbwalker** [comment]
Please post them here so that we can capture them in this issue

**Comment by aubrey-b** [comment]
OK, sorry I created a new issue, see #349

**Comment by sbwalker** [comment]
No worries... I am glad you are attempting to create a module. Please report any issues you find.

**Comment by mikecasas** [comment]
Not sure if this is what you are looking for, but I was able to write a method to return the Module Id of another independent module. Would it be helpful to have a method in the framework to do this? Also I am using the same basic logic to confirm that a module is installed in the site instance.

Small potatoes, but it could improve developer experience. Maybe there is already a more elegant way to achieve this?

**Comment by thabaum** [comment]
@mikecasas Maybe put together a PR for review?

**Comment by sbwalker** [comment]
The core admin modules have not required such a method so I think it would be helpful to understand the scenario you are trying to accomplish. I have been making someone suggestions to @aubrey-b in the Gitter channel for an application with a variety of modules. If you really need to find a ModuleId you can use the PageState.Modules collection and use Linq to find a Module.ModuleDefinition.ModuleDefinitionName matching a specific value.

**Comment by mikecasas** [comment]
OK, I will look there. Thanks. Yes, I was able to loop through the installed modules in a specific site and find the module id of my custom module.

**Comment by thabaum** [comment]
Maybe we can get a label setup for Accepted MVP Issue ideas to separate the tasks that are version 1.x milestone and those for MVP milestone.  I think this would also help build awareness to the current status, goals and workflow.

**Comment by mikecasas** [comment]
I agree, but I think MVP is closed unless there is something breaking.

**Comment by sbwalker** [comment]
Based on the use cases I described above for module development, I checked in an enhancement to the Module Creator today. It is now capable of scaffolding both Internal and External modules. It also allows you to namespace your modules properly, regardless of the approach.

The UI now asks for 2 additional pieces of information - an Owner Name and Template. The Owner Name will be used as the top level of your namespace to ensure there are no naming collisions with the Oqtane core framework. The template allows you to choose either Internal or External.

An Internal module is created inside of the Oqtane solution, just like it was previously. It scaffolds all of the necessary files and even implements advanced features such as module settings, content export/import, etc...

An External module is created outside of the Oqtane solution in a folder at the same level as the Oqtane framework. It scaffolds all of the same files as the Internal module template, as well as project and solution files which are already configured to build and deploy artifacts ( when building in Debug mode ) to the Oqtane instance for immediate testing. It also has the ability to automatically package a module into a Nuget package ( when building in Release mode ).

I believe this should make it much easier for developers to get started with module development on Oqtane. Please test this enhancement and provide any feedback you may have.

**Comment by sbwalker** [comment]
I should also mention that both the Internal and External module can be run on Blazor Server and Blazor WebAssembly without any modifications.

**Comment by thabaum** [comment]
So, I have "broke" my first installation of oqtane I believe once I tried installing the other theme.  I am trying to figure out why however thinking I need more than one instance of Oqtane to work on.  Any good solutions for this type of scenario.  For example how I should download the latest fixes to "overlay" on my development copy.   I probably should do this on just one however if I am working on an issue I don't want to lose my changes so setting up a solution for each issue seems to be what I need to do.  However one solution would be simply to test what you want done here.  The "Overlaying" is what I wish to do correctly and anything for setting up a second instance of octane in VS.  Thank you.

**Comment by chlupac** [comment]
@thabaum Use Git branches

**Comment by thabaum** [comment]
https://www.youtube.com/watch?v=c3482qAzZLQ
Long deep video explaining Git branches I found that covers the whole 9 yards of developing here I believe that seems like a pretty solid reference.   31 minutes into the video he talks about branches.  I have been doing all my editing in Github mainly while using VS to search files more or less... All this new stuff that is pretty old really is pretty cool but I would be more lost if I didnt ask.  Thanks.  I am trying to fully understand all the ways you can use Git.  I might need to put up a small project of my own to really play with it.

**Comment by thabaum** [comment]
I think you can label things that end could possibly be common issues people may have to include in documentation later.  Maybe a "To Document" and mention in the issue what to document for later so we can get a collection of helpful stuff together for release.

**Comment by sbwalker** [comment]
Added full support for uninstalling modules. Oqtane now allows you to include an Uninstall.sql script as an embedded resource which will be executed when you Delete the Module through the Module Management UI in the Admin Dashboard. This script should contain SQL commands to remove any database entities you may have created when the module was installed. In addition any references to the module will be cleaned up from the SchemaVersions database table ( an artifact of DBUp ). The uninstall capability was added to the ModuleCreator templates as well so it can be easily tested.

**Comment by ADefWebserver** [comment]
I blogged on the [Oqtane Module Creator](http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4374/Oqtane-Module-Creator.aspx)

**Comment by sbwalker** [comment]
Thank you Michael!

**Comment by tharris9d** [comment]
Very nice tutorial! Thanks Michael!
