### ISSUE TITLE
Unable to remove / delete modules

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3480]
From the module manager deleting a module does not work.  I installed Toast and without adding an instance to page tried to remove it.  The module will not remove.  Restarting the Framework didn't help as the DLL is still in the \bin folder.

![CantDeleteModuleDef](https://github.com/oqtane/oqtane.framework/assets/9447612/64981968-b993-4958-8b8a-189e0e43a687)

**Comment by sbwalker** [comment]
I am unable to duplicate this issue when running the code from the dev branch on .NET 8 in VS 2022 17.8.

**Comment by leigh-pointer** [comment]
@sbwalker these issues are in a deployed environment.

**Comment by sbwalker** [comment]
I am unable to reproduce in any of the 4 Azure environments where I am dogfooding Oqtane 5

**Comment by sbwalker** [comment]
@leigh-pointer do your packages match the size of below:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/fa915915-2a49-47ce-a5c3-ca0858abcf34)

**Comment by leigh-pointer** [comment]
@sbwalker there are the same!

**Comment by sbwalker** [comment]
@leigh-pointer I am not sure what to do with these issues logged for Oqtane 5.0 as I am unable to reproduce them. Have you tried to upgrade to the official 5.0 release (the issues you logged were related to a 5.0 package you built yourself prior to the release)?

**Comment by leigh-pointer** [comment]
@sbwalker i am going to install fresh from your release. Will keep you informed!

**Comment by leigh-pointer** [comment]
@sbwalker I have created a complete fresh installed on IIS and still the same.  When I run from my design environment in Visual Studio, everything appears to be ok.  So I'm guessing, seeing as you have no issues with IIS it must be something with my setup. The IIS hosting bundle is installed and IIS restarted, so I will continue to see what is going on.
