### ISSUE TITLE
Module file naming convention

### ISSUE THREAD

**Issue by aubrey-b** [oqtane/oqtane.framework#349]
I guess with all the refactoring I noticed that the Module.cs class file name changed to a ModuleInfo.cs file name. For example, in the HtmlText module (https://github.com/oqtane/oqtane.framework/tree/master/Oqtane.Client/Modules/HtmlText) there is a ModuleInfo.cs file name, but when I go to the oqtane.module.blogs repo, the original naming convention of Module.cs is there. Both classes do implement the IModule interface, but should there be one naming convention?

**Comment by sbwalker** [comment]
I have some changes to check in for the Blog module

**Comment by sbwalker** [comment]
Blog changes checked in

**Comment by sbwalker** [comment]
You won’t see them in Visual Studio because they are excluded from the project but they are located under the Oqtane.Client\Modules\Admin\ModuleCreator folder

**Comment by mikecasas** [comment]
Can those files be checked in too? 

Also after reading this issue, the ModuleCreator folder has a Module.cs file, do you want a PR to change it to ModuleInfo.cs?

**Comment by sbwalker** [comment]
The files are already checked in. See https://github.com/oqtane/oqtane.framework/tree/master/Oqtane.Client/Modules/Admin/ModuleCreator/Templates .

**Comment by aubrey-b** [comment]
@mikecasas I couldn't find the templates either. You have to select show all files in the solution to view them.

![ss](https://user-images.githubusercontent.com/62708151/78911605-85de4780-7a54-11ea-86be-1d6f72e4a3fd.PNG)

**Comment by sbwalker** [comment]
Correct. The template files are excluded from the project because they have tokens in them which result in compilation errors if they are included.
