### ISSUE TITLE
The Filemanager component does not allow uploading of specific extensions.

### ISSUE THREAD

**Issue by Raceeend** [oqtane/oqtane.framework#3493]
The Filemanager component has a test that cannot be modified via the component's parameters. For a project, files with the .cor extension must be uploaded. This extension is rejected because it is not included in Constants.UploadableFiles. In my opinion, the best solution would be to add an extra parameter to the filemanager. If this parameter is not empty, it will be used to check the extensions.
Used version: 4.0.6

**Comment by leigh-pointer** [comment]
@Raceeend This has been mentioned.  Currently the FileTypes are listed as a Const string in Shared

```
public const string ImageFiles = "jpg,jpeg,jpe,gif,bmp,png,ico,webp";
public const string UploadableFiles = ImageFiles + ",mov,wmv,avi,mp4,mp3,doc,docx,xls,xlsx,ppt,pptx,pdf,txt,zip,nupkg,csv,json,xml,rss,css";
```

These need to be made soft and amendable by the Host and/or Admin.

**Comment by hishamco** [comment]
It would be nice to move them as settings in the `appsettings.json` instead of constants, @sbwalker if you agree with the change I can push a PR

**Comment by sbwalker** [comment]
The general philosophy in Oqtane is to avoid storing settings in appsettings.json as it does not support multi-tenancy and is not easily upgradeable. The list of file extensions should be managed per Site - and could be stored in the SiteSettings (much like a variety of other settings).

**Comment by hishamco** [comment]
Exactly, but it's the host responsibility to manage such media settings if we don't prefer the `appsettings.json`

**Comment by sbwalker** [comment]
Similar to SMTP settings, the Allowable File Extensions option could be managed in the Site Settings UI - but only editable by Host Users.

**Comment by leigh-pointer** [comment]
@sbwalker we did discuss moving the extensions to the Site Settings UI, I think in version 3, but I guess it fell through the net.

**Comment by leigh-pointer** [comment]
Implementation PR complete #3528

**Comment by sbwalker** [comment]
completed in #3528
