### ISSUE TITLE
DB Connections Support Azure SQL Access Tokens

### ISSUE THREAD

**Issue by bbakermmc** [oqtane/oqtane.framework#35]
Ability to support connecting to Azure SQL using Managed Identities.  We host our DBs in azure, we create a managed identity for the app, and give it auth to the DB it needs, this means we don't need to store usernames and passwords in the connection string thus its more secure.

I would think a toggle on the tenant creation.

REF:
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi

```c#
public MyDatabaseContext(SqlConnection conn) : base(conn, true)
{
    conn.ConnectionString = WebConfigurationManager.ConnectionStrings["MyDbConnection"].ConnectionString;
    // DataSource != LocalDB means app is running in Azure with the SQLDB connection string you configured
    if(conn.DataSource != "(localdb)\\MSSQLLocalDB")
        conn.AccessToken = (new AzureServiceTokenProvider()).GetAccessTokenAsync("https://database.windows.net/").Result;

    Database.SetInitializer<MyDatabaseContext>(null);
}
```

**Comment by sbwalker** [comment]
We will be adding an installation wizard and could consider a SQL Azure option
