### ISSUE TITLE
i18n: Configure available languages per site (feature)

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#3536]
## Background

At the moment language packs can be installed at the system level. This automatically implies, that all sites support all these languages. 

## New Feature

An important step going forward is the ability to specify which of these languages should be available on each site, since activating a language doesn't automatically mean, that all sites support this language.

## Implementation

1. The UI for site settings should have an option as to what languages / cultures are enabled
    1. Ideally true/false toggle "Use all installed languages"
    2. if that is set to false, then allow the admin to select languages from the list of languages (ideally with a comment that additional cultures need to be activated in the system languages section
    3. Store the data in a reasonable place in the DB
2. Some kind of API to access the list of activated languages, probably on the site object
3. Optimize the language menu to only show the cultures which are activated in the site

Note: if this feature is approved in this or a similar manner, we (2sic) could also contribute the development for it

**Comment by sbwalker** [comment]
@iJungleboy I am confused... Oqtane already contains a Language Management admin capability which allows you specify the Languages which are enabled for a specific Site in an installation:

http://localhost:44357/admin/languages

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/3c0bceb2-1d48-4e47-b226-ea4d528f7b0a)

This configuration is used to load the list of languages displayed in the LanguageSwitcher component (ie. the dropdown of available languages for a site).

**Comment by iJungleboy** [comment]
In that case I might have missed something. 

I presumed the UI was "global" - but you're saying it's already site-specific. 

If that's the case, then this issue could be closed. 
thx
