### ISSUE TITLE
i18n: Preserve current language in route (feature)

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#3537]
At the moment the user can change the UI language with a menu.

But there is no way to link to the same page in a clean way, while preserving that language selection - at least not allowing the user to just copy-paste the current url and expect the other user to see the same thing (on multi-language solutions). 

The cleanest way to implement this is that we would have urls such as:

* https://blazor-cms.org/ - this would be the language unspecific domain; ideally the language would be detected as it is now, and then forwarded to the correct sub-path
* https://blazor-cms.org/en (example) - this would be the url which would bypass the automatic selection and use this language
* https://blazor-cms.org/de (example) - same

Ideally then when you toggle the language, the route would also change, so that forwarding this specific link would preserve the language choice. This would also mean that the behavior would change so that (if this is configured) a language switch on https://blazor-cms.org/en/contact going to German would switch over to https://blazor-cms.org/de/contact

I understand that this does require some configuration, such as:

1. specify activated languages per site - see #3536 
2. enhance the site alias configuration to for a specific language
3. since the language-menu should go to that route, it should then probably either try to best-match the route (in case there are many for that language), or it would need a primary flag, to be used when a user switches languages. Another option could also be to put the language-selection behavior into a service, which could be overriden by an alternate service if the behavior should change
4. Probably extend the `Site` object to contain information about what language it's configured for

Note: if this feature is approved in this or a similar manner, we (2sic) could also contribute the development for it

**Comment by sbwalker** [comment]
@iJungleboy as discussed previously (https://github.com/oqtane/oqtane.framework/issues/2499) there is no plan for Oqtane to support Content Localization within the same "site" (in this context "site" means a single instance within a multi-tenant installation). Content Localization should utilize the existing multi-tenant/virtualization concepts:

SiteId:1 = Alias: blazor-cms.org
SiteId:2 = Alias: blazor-cms.org/en 
SiteId:3 = Alias: blazor-cms.org/de 

Obviously this is a different approach than some other products (ie. DNN) however I have already explained why this approach is preferred over other approaches. Please note that it is already possible in Oqtane for a site to have multiple Aliases... so it is already possible to configure a site using:

SiteId:1 = Alias: blazor-cms.org, blazor-cms.org/en, blazor-cms.org/de 

With this configuration you could already obtain the Url segment containing the Url - however this would not be the recommended configuration for developing a content localization solution.

**Comment by iJungleboy** [comment]
@sbwalker I understand your position on content-localization. 

Basically we've created hundreds of multilanguage sites and I don't agree 😉.

But I think that's not important for this request. 

Basically I believe that even without content-localization baked in, a method to link to the UI in a expected language just makes sense anyhow. 

Of course I then plan to try some content-localization on top of that, but I believe the request has merits even without that.

**Comment by iJungleboy** [comment]
If we would add multiple aliases, is there a possibility to override a specific service, so that it would result in setting the UI culture?

**Comment by sbwalker** [comment]
@iJungleboy you could certainly include your own custom code in a theme or module which sets the UI culture based on the alias.

I am closing this issue as there is no further action required.
