### ISSUE TITLE
Bootstrap Icons

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#355]
https://github.com/twbs/icons

Currently this project is in Alpha, but open source and FREE no strings attached.  I know I can add these to my own projects but thinking for Oqtane maybe this could be something to consider for a community developed addition along side of bootstrap.

To have these as part of the Oqtane icon set would be pretty cool for dressing up the ride.  I think maybe MVP could use this added to the feature list available for developers.  Need to wait for a release as they are changing so much now can't trust it :)

I will consider contributing to the Bootstrap Icon set if adopted here ;)

**Comment by sbwalker** [comment]
Oqtane already has an icon set - Open Iconic ( https://useiconic.com/open ) and @chlupac was kind enough to add an Icons class in Oqtane.Shared so that it is easier to work with them. We will not be adding another icon set at this time. Closing issue.
