### ISSUE TITLE
WebAssembly and Oqtane License Component

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3563]
Changing the framework to run as web assembly I get an error with Oqtane License Component.

Running from within Visual Studio

![image](https://github.com/oqtane/oqtane.framework/assets/9447612/071c0454-8ee9-4ed1-bc05-bac6a568c68e)

**Comment by sbwalker** [comment]
@leigh-pointer anytime you create a module that needs to run on WebAssembly you need to specify the module's Client dependencies in the Dependencies property of the IModule interface (ie. ModuleInfo.cs). This is how the Oqtane Framework is able to determine which assemblies need to be downloaded to the browser. The Module Creator only includes the module's Shared assembly by default. You would need to include Oqtane.Licensing.Client.Oqtane and Oqtane.Licensing.Shared.Oqtane if you are creating a licensed module that needs to run on WebAssembly.

**Comment by leigh-pointer** [comment]
@sbwalker thanks, all fixed now!
