### ISSUE TITLE
Issue: Logo if bigger than 90px in height pushes navigation menu on top of content pane.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3571]
Logo bigger than 90px or so will overlap the content making things like titles of modules or pages hidden from users along with any notifications on top of the page in the event a user uploads an image with a 300px height for example.

**Comment by sbwalker** [comment]
please provide a screen shot at full width as well as in responsive design mode (ie. mobile view) to validate the display characteristics

**Comment by sbwalker** [comment]
restricting the dimension of the logo should be implemented in a theme - as each theme will have different display requirements
