### ISSUE TITLE
[BUG] Oqtane.Maui - "Remember Me" Control Not Functioning Properly in the .NET Maui application.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3581]
# Issue: "Remember Me" Control Not Functioning Properly in Oqtane Framework

## Problem Description

The "Remember Me" control in the Oqtane.Maui application is not functioning as expected, particularly in scenarios related to user login. The current implementation does not effectively leverage browser capabilities to remember accounts through cookies, impacting user experience.

## Proposed Solution

It is recommended to utilize the official MAUI API for setting cookies, as outlined in the [official documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-8.0&pivots=devices-android#set-cookies). By adopting this approach, we can enhance the "Remember Me" functionality and improve the seamless retention of user credentials.

## Steps to Reproduce

1. Open the Oqtane.Maui application on Windows 11 with the default Firefox browser.
2. Log in using the "Remember Me" option.
3. Observe that the password does not auto-complete upon subsequent openings of the application.

## Screenshots
(Firefox is my IDE default browser here, but should have same results in Edge as well)

.NET MAUI APP LOGIN
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/5a9c9b21-3166-45d7-8c87-6641c929d6b9)

## Additional Notes

- The suggested solution involves integrating the MAUI API for cookie management.
- This enhancement aims to allow the browser to effectively remember user accounts through cookies, ensuring a smoother login experience.

**Comment by thabaum** [comment]
@sbwalker as I said I would clean up these issues, this one seems to be my next concern while in the area of cookies with .NET MAUI is the login + remember me control.

**Comment by sbwalker** [comment]
@thabaum  the "Remember Me" functionality in Oqtane relies on cookies (like most web-based applications). Cookies are only applicable for interactions between a standard web browser and a server. Blazor Hybrid relies on a WebView component - which is NOT a standard browser. In fact it is just a wrapper around a native WebView component which is specific to each platform. For Windows, the native WebView is called WebView2 and is based on Edge - but does expose all of the same functionality as the Edge browser... by default it does not support cookies. There are ways within a MAUI application to add custom configurations for the WebView for each platform... however I have never seen a functional example for cookies. 

I will not be spending any time on this item, as it is not a high priority in comparison to other Oqtane items. The login is fully functional in its current form.

**Comment by thabaum** [comment]
@sbwalker Not a priority for Oqtane Framework, so this will be one I can work on and provide a pull request when I can zero in on the solution.  Thank you for the added context it will help me with a possible solution.  I will of coarse share anything I find out with the community.

**Comment by sbwalker** [comment]
I am going to close this issue as it is a very low priority
