### ISSUE TITLE
Issue: Site Management - When on a site listed there is no need to browse or navigate to that site URL.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3584]
Should clicking "Edit Settings" on the site you are on should navigate to the site settings page instead of opening a browser?  If using the app and you wish to edit the app settings related to that site should just go directly to that page instead of a new browser for the site you are on when visiting that page and no browse button since you are on that site.  I suppose both work and give options for both.  I wasn't going to make an issue just a note of this behavior.

Shown in the Maui application it should navigate directly to the site settings page for that site instead of a new tab or browser opened.

Should be a fairly simple fix if I am clear on the issue.  I will look at it if needed to show the results I believe would be more desirable with respect to navigating to the site settings component.  I can navigate to the site setting page from within the app if I go through the control panel.  No need to open a new browser on a user for the site they are on.

The site you are on maybe could be in **bold** and have something letting you know it is the current site (or site group).

Site groups should be on the same tenant or DB so to speak correct? They would share users, components, pages... so on.  So when on "Site Settings" being able to switch between the sites here should not impose issues that keep that feature from being active for all tenants/sites?  Sites that are grouped together could be shown organized together in Site Management as well.

That is digging a bit deep into some past conversations and a little off topic.  Just some added feedback as I clear some thoughts here.

**Comment by sbwalker** [comment]
@thabaum a MAUI client application is bound to a specific domain which is specified in the client's appsettings.json file. If a site contains links to a different domain and a user clicks it, it will spawn a browser window. This is the standard behavior for a MAUI client application. Multi-site management is not a supported use case when using a MAUI client app - a MAUI client app is intended for providing a mobile or desktop experience for a specific site in your installation.

**Comment by thabaum** [comment]
@sbwalker all works well so to speak, but the navigation is opening a new browser link instead of navigating to the page.  I think this is fine as it should open up other browsers to manage sites within the Maui app.  I just felt for the site you are on it should not open a browser link or if it does go ahead and navigate to settings page or homepage and not open a browser.  I think this behavior can be resolved with a solution that would allow managing site settings and going to the homepage to browse the site from within the Maui app while using the buttons in Site Management.
