### ISSUE TITLE
[BUG] Oqtane.Maui - App closes when navigating site If server is down.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3588]
# Issue: 

App Closes Without Warning When Navigating Site in Oqtane.Maui and Server is Down

## Reproduction Steps:

1. Launch Oqtane.Server project from one instance of Visual Studio.
2. Launch the Windows App configured and installed after deploying the application.
3. Navigate the site successfully from Oqtane.Maui Windows 11 application.
4. Stop the Oqtane.Server instance from running in Visual Studio.
5. Navigate in the Oqtane.Maui Windows application while the server instance is not running (server is down).
6. Observe that the application either errors or closes immediately with no warning message or noticed errors.

## Expected Behavior:

A user should receive a clear message indicating a connection issue, such as a redirect back to the app's index.html page with an enhancement for a Maui app connectivity error message. This enhancement should allow users to reload or "retry" when they feel the connection issues may have been resolved.

## Additional Notes:

This particular issue requires further consideration as it involves a website running inside the Maui app. Suggestions and testing from the community are welcome to find a solution that enables Oqtane to handle this scenario effectively out of the box.

Potentially related ASP.NET Maui Issue:
Support Global Exception Handling Mechanism for .NET MAUI:  https://github.com/dotnet/maui/issues/5535 and is going to possibly be part of .NET 9 release.

**Comment by sbwalker** [comment]
@thabaum this is a similar issue which happens when running Oqtane in Visual Studio on Blazor Server or WebAssembly and you navigate to the Sytem Info page and select Restart Application. Visual Studio terminates the client application immediately. However if you run the framework in a real world environment (with a proper server) the server will restart and recover and the client browser will reconnect and continue.

**Comment by thabaum** [comment]
@I was only running the server in Visual Studio, I was running the deployed app after build as it installs it on the system you are working on.  Then you can run the app natively without visual studio.  This results in a close of app if the server is down while clicking on a link.

Run with visual studio the maui app and it will go to an error in code of the maui app.

I will test this further with an installation of server running on IIS but I can't see it having a difference.

**Comment by thabaum** [comment]
@sbwalker Hope all has been well.  I have not been working on the .NET 8 Maui project for couple weeks now as I have been wrapping my mind and time around some other things, but I did try to get an IIS instance going on my IDE to test more of a production setup.  

I had issues, not sure if something with my OS, IIS or Oqtane.  I want to get this process down and double check it against current documentation.  I will be working in this area today in fact and test the new commits relating to administration of sites behavior while running the .NET 8 Maui Oqtane Framework project application from desktop.  I wish to run tests both from IIS directly (production) and from inside Visual Studio.

I know I had it all working in the past, I just got used to localdb and F5. Now that I have been using the SQL Server again I can more confidently set this up and troubleshoot more effectively my current environment or application issue with IIS.  

Issue is trying to run the release build files copied from folder in framework to a folder dedicated to IIS (wwwroot) as I have done in the past. I ran into a server application error(s) trying to launch it in a browser (500 I believe).

I will report back by end of the day how things went using the current dev branch with these test scenarios I previously mentioned.

Thank you for taking time to understand these issues and working them out as needed.

**Comment by thabaum** [comment]
production site running on IIS with SSL signed still same issue.  The Maui App crashed, but I was running the app with debugging

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/e671e420-428a-4fcf-868f-44c3e840a602)

I will test the app deployed next.  When I shut down the server and tried to start it again 500.30 error generated the site would not startup again.  I am investigating this now.  I am running my version that has all the CORS edits not sure it has anything to do with it.

**Comment by thabaum** [comment]
FYI: The above error no longer exists in previous message relating to dynamic component parameters as I believe it was resolved in 5.02 or the upcoming 5.1 - dev branch - recently.  

The ongoing issue with the unhandled exception messages unavailable in .NET Maui WebView to enhance user experience. I put an issue at the top of this thread that shows it is a known issue along with a number of relating issues.

From what I read and believe to understand Microsoft is planning to introduce a solution in .NET 9.  

This does jam things up a bit when you want to go production and have all the angles covered for the UX.  Moving forward without an alternative solution as there currently is no choice but to just let the app close and put up a support FAQ for this issue to help limit support costs.
