### ISSUE TITLE
Issue: Getting issue with stripe.net

### ISSUE THREAD

**Issue by sumitasingharay** [oqtane/oqtane.framework#3594]
I have added an oqtane module and installed stripe.net (43.8.0.0) in that module server project. But I am getting this below error while invoking any stripe objects @sbwalker could you please help me on this?

![image](https://github.com/oqtane/oqtane.framework/assets/111213680/d8c2840e-7e09-445b-91f9-e53a3e63d8b5)

**Comment by leigh-pointer** [comment]
@sumitasingharay try adding this to your project file

	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

**Comment by sumitasingharay** [comment]
@leigh-pointer Its already included in the project and not working

**Comment by sbwalker** [comment]
@sumitasingharay when you create a module as a separate razor class library... you need to understand that when you compile the module, the assemblies will be created in the module's bin folder... and will need to be deployed to the Oqtane /bin folder. The module's Package project contains a debug.cmd file which is executed as a post build step to copy assemblies to their proper location. You will need to add the Stripe assembly (and any other assemblies which Stripe depends on) to the debug.cmd.

**Comment by sumitasingharay** [comment]
@sbwalker Thank you for letting me know this. It's working as expected.
