### ISSUE TITLE
Database creation failed with SqlServer instance : Oqtane 5.0.1

### ISSUE THREAD

**Issue by techravi007** [oqtane/oqtane.framework#3604]
### Version : 5.0.1
**Steps to produce-**

1. download the latest source code form github.
2. open the Oqtane.sln file in visual studio, run the Oqtane.Server project.
3. On installation page, choose the Database option to - SqlServer
4. Provide SqlServer and host details and click on install button
5. Installation throws exception- "An  error occurred creating the database"

![image](https://github.com/oqtane/oqtane.framework/assets/36012444/6e1a78f5-f1af-41dd-bef9-6a92148b2457)

### Debug Info-
**`var type = Type.GetType(databaseType);`**
Type.GetType() Always returns **`null`** for SqlServer instance
so Activator.CreateInstance() throws the error-
**`Activator.CreateInstance(type) as IDatabase;`**

![image](https://github.com/oqtane/oqtane.framework/assets/36012444/8c4492ff-09d4-4041-a668-dd44d1766a5d)

**Comment by sbwalker** [comment]
@techravi007 after you opened the Oqtane.sln file in Visual Studio, did you you build the solution (Build / Rebuild Solution)? The error message seems to indicate that the SQL Server Data Provider assembly is missing... however the only way it would not exist is if the SQL Server Data Provider project was not compiled (the project is part of the Oqtane.sln).

**Comment by sbwalker** [comment]
@amalsharief after you opened the Oqtane.sln file in Visual Studio, did you you rebuild the entire solution (Build / Rebuild Solution)? I suspect the Database Providers do not exist in your installation. You can verify by looking in your Oqtane.Server\bin\Debug\net8.0 folder and check for the existence of the Oqtane.Database.SqlServer.dll assembly.

**Comment by thabaum** [comment]
I have verified the issue, and verified that if you build the project first it will connect to a local MS SQL Server using Integrated Windows Security.

I was successful only after using either "Build" or "Rebuild" options.

**Comment by sbwalker** [comment]
@amalsharief based on the screen shot it appears that the Oqtane.Database.SqlServer.dll assembly exists in the /bin (which means that you successfully built the solution). And you are saying that now when you select Debug / Start Debugging (F5) in Visual Studio it displays the Install Wizard but when you click the Install button it displays the error related to Type.GetType() ?

**Comment by techravi007** [comment]
@sbwalker, After rebuilding the individual project **`Oqtane.Database.Sqlserver`** it works.
thanks.

**Comment by sbwalker** [comment]
@thabaum if you have time can you please test PR #3613 - in the scenario where a developer has not compiled the solution prior to running Oqtane, it should display a message when the user clicks Install of "The Database Provider xxx Does Not Exist. If This Is A Development Environment Please Ensure You Have Performed A Full Compilation Of All Projects In The Oqtane Solution Prior To Running The Application."

**Comment by thabaum** [comment]
@sbwalker I will take a look at this today let you know results later.

**Comment by thabaum** [comment]
@sbwalker looks like it works as expected delivering a helpful message

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/183ba52d-ea9e-449d-aeff-3c57280f089b)

I also tested the after rebuild with a wrong connection string to see message.

It is very very long massive message when you just enter the wrong credentials.  Maybe we can do a smaller message with a view error details popup from that with all the extra technical stuff.  Generally this is going to be displayed mostly when a wrong connection string as in wrong host address or username/password.  Maybe we can have docs fully explain all the common scenarios and give a good example of how things should look and put a link to the docs here for troubleshooting installations at some point.  But it works as is.  I wish this error message had a little more formatting showing a message... then a line break to the error to allow me to get a general idea of what might the issue be with a drill down from there if needed.  It is very hard to look at that huge message and quickly determine the potential issue which in this case is simply wrong host.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/b8bf230d-b0cd-4755-b0fb-6daf005b84f7)

**Comment by sbwalker** [comment]
@thabaum thank you for testing the issue related to a missing data provider - hopefully this guidance will be helpful for developers. In regards to the suggestion of including the /bin folder and specific assemblies in the GitHub repo - it is generally a bad idea which should be avoided.

The entry of an invalid connection string is not related to this specific issue. However in regards to your comment, the first part of the message "An Error Occurred Creating The Database. This Is Usually Related To Your User Not Having Sufficient Rights To Perform This Operation. Please Note That You Can Also Create The Database Manually Prior To Initiating The Install Wizard." is the "friendly" part of the message - the rest is the actual exception thrown  by the system which often contains helpful information that allows you to diagnose the problem with the connection string.

**Comment by thabaum** [comment]
I think there should be a line break between the friendly message and the error message so it is easier to read quicker.

> "An Error Occurred Creating The Database. This Is Usually Related To Your User Not Having Sufficient Rights To Perform This Operation. Please Note That You Can Also Create The Database Manually Prior To Initiating The Install Wizard."

Server Setting can be wrong as sometimes I put (localhost) or localhost or whatever address you may think is correct and actually you are entering it it wrong for connecting to that server.

"An Error Occurred Creating The Database. This Is Usually Related To The Server Setting Or Your User Not Having Sufficient Rights To Perform This Operation. Please Note That You Can Also Create The Database Manually Prior To Initiating The Install Wizard. For Further Assistance, Refer To The [Documentation](https://docs.oqtane.org/) For Detailed Instructions Or Seek [Support](https://github.com/oqtane/oqtane.framework/discussions)"

Maybe a link to docs and support forum would be nice enhancement?  Can include this support information on more messages in this area with some default links to be included as a template to help with this on-boarding process.  Support link can go to Oqtane.org support which can then introduce all the professional and community support options.

**Comment by sbwalker** [comment]
@thabaum I would prefer to leave the message as-is for now
