### ISSUE TITLE
Oqtane Loader

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#361]
Loader for Oqtane framework https://github.com/chlupac/Oqtane.Loader

- Use custom _Host.cshtml
- Control of startup procedure
- Allow reference custom module projects for easy development and debugging
- works in both modes (server, webassembly)

**Comment by chlupac** [comment]
I forgot to include  URL to project https://github.com/chlupac/Oqtane.Loader

**Comment by sbwalker** [comment]
You should get @mikecasas to link to this repo on the awesome-oqtane page
