### ISSUE TITLE
Breaking Issue:  Dev Branch - Unable to startup the Oqtane Setup page - Null Exception Error in ShouldRender() Method

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3617]
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/6a82f05a-6289-4b5d-a1d8-ebe54ee37956)

## Issue

After building and running the app to start configuration page for the first tenant and host credentials:
`PageState.RenderId == ModuleState.RenderId;` 
returns as null.

#### Location
ModuleBase.cs 
Line 118 
Current dev branch zip download 

## Notes

#3614 is where this logic for `RenderId` was introduced.
[https://github.com/oqtane/oqtane.framework/pull/3614/files](https://github.com/oqtane/oqtane.framework/pull/3614/files)

All the solution projects built successfully on my initial attempt but threw this exception shown at top once it ran.

Beware you may need to download the [5.0.1 master branch](https://github.com/oqtane/oqtane.framework/tree/master) of Oqtane Framework if anyone new is testing this out until this issue is closed.

### Maybe A Solution

I submitted a fix or workaround depending on how it is reviewed.

I changed the line as follows:
`return PageState != null && ModuleState != null && PageState.RenderId == ModuleState.RenderId;` 

This way Oqtane checks if PageState or ModuleState is null and if one is null it will create a `false` boolean result.  Something else introduced in #3614 is probably causing this problem I am guessing without taking time to review it all.

The solution in the PR I provided gets the Oqtane.Server project started up in Debug mode, but I am not 100% sure what results are expected here to say this is the only issue, more a fail-safe.

Now that I have a site created as I found this working on testing the database connectivity issue if this PR does not resolve I can test the other database scenario out where it is not loading the initial Oqtane Installation Configuration Page.  I was going to attempt to see if Oqtane works if you connect to a database that is already running with an installation manually editing the `appsettings.json` configuration file was the idea.  

I am going to pass doing that now that I found a solution to workaround it until can be investigated and reviewed further.

Hope this helps, cheers!

**Comment by sbwalker** [comment]
I am not sure why the Install Wizard triggers a method in ModuleBase as the install wizard component is a not a module. However I am glad you identified this scenario. It has now been addressed in #3620
