### ISSUE TITLE
Major Enhancements on Docs 🚀

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#3640]
This is already solved - just did a major update on [docs](https://docs.oqtane.org/) 🚀

Thanks a lot to @thabaum for his initial work to get docfx upgraded and .net 8 setup.

I had to do some more changes because docfx had various breaking changes, but fortunately I had already lost countless hours fixing https://docs.2sxc.org so I had a good reference to fix it. 

New version is:

1. Bootstrap 5
2. Has day / night mode 🤩
3. Has a really good JS search built in
4. Tree structure for API docs
5. ...and way more 

again shoutout to @thabaum for his work here!

**Comment by thabaum** [comment]
@iJungleboy I am happy all that time and effort came to use and you said it, "countless hours".  I would of got onboard sooner I just was still feeling out all the situations here  I can't wait to take the docs for a spin!

This is great to hear this update and awesome shout out with some much appreciated love, but I think this should be moved to discussions.  When I get heading in that direction again I will provide what additional support I can.  Maybe at the meetups currently being planned some of this can get discussed for those contributing to this important part of the Oqtane community driven support docs.

Thank you @iJungleboy for taking on this task of helping us all have such a repository as a resource we can all contribute to.

You rock helping us keep the heat on in the Oqtane community! :fire:

**Comment by iJungleboy** [comment]
@thabaum you're welcome ;)

Reason I created an issue instead of a discussion is so Shaun is aware of it and remembers to include us in the next releases contributors ;)
