### ISSUE TITLE
Enh: Profile Autocomplete Attribute Added To Profile Properties

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3651]
# Autocomplete Attribute Enhancement

## Description

I propose adding the ability to set the `autocomplete` attribute for profile properties in the framework. This enhancement would allow developers to control whether the autocomplete feature is enabled or disabled for specific profile fields.

## Use Case

This enhancement is beneficial for scenarios where developers want to customize the user experience by enabling or disabling autocomplete for certain profile properties. For example, they may want to disable autocomplete for sensitive information like passwords.

## Current Behavior

Currently, the framework does not provide a way to control the autocomplete attribute for profile properties.

## Proposed Enhancement

I propose adding a new setting or property to profile properties that allows developers to specify whether the autocomplete attribute should be enabled or disabled by entering in text such on "on" or "off" or "given-name".

@sbwalker I have a working pull request I will submit for review.

**Comment by leigh-pointer** [comment]
@thabaum if you are only allowing three values it would be better to make the control an option select control.

**Comment by sbwalker** [comment]
I do not fully understand this proposal. Profile properties already support general text input and drop down lists where you can define the list of allowable options to select from. Autocomplete is best used in scenarios when there are many standardized values to choose from... so in the context of profile properties where is this large set of standardized values supposed to come from?

**Comment by thabaum** [comment]
The PR explains things better I was hoping.  The logic handles it all.

1. If you do NOT enter anything the autocomplete form field `autocomplete=""` as in... this attribute will not be added to your input fields you created... most input fields wont need this
2. If you enter something (a string) into the autocomplete field the input field now includes a value and will get included in the input element used for that profile property, this can be ANYTHING millions of possibilities... so a drop down select is not solution.
3. Real world scenarios include "given-name" "address" "postalcode" and so on so this form can be autocompleted by a user with data that is from other forms that are similar they filed out.

This helps users autocomplete profile information faster.

**Comment by sbwalker** [comment]
Sorry... I thought you were referring to the Oqtane AutoComplete control - not the HTML autocomplete attribute. The HTML autocomplete functionality can cause a lot of problems - it has been a personal pet peeve of mine for a long time. There have been a number of mysterious issues logged in Oqtane in the past where it turned out the browser autocomplete had overwrote input values in hidden sections of a form and caused major functional problems. I will review this enhancement this week (I generally try to prioritize issues first before adding enhancements which could introduce new issues).

**Comment by thabaum** [comment]
@sbwalker thanks for taking time to review, this would only be for the profile management.  I will be adding this to "options" as well since if you have a form with country and state this would need an autocomplete entry as well to allow a user to quickly fill things out from what the browser has saved.
