### ISSUE TITLE
Bug: After Saving Admin Site Settings, Visible Image File Extensions Are Not Being Set In The Database, Causing User Profile Image To Be Unviewable

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3663]
## Issue Description

After Saving Admin Site Settings, Visible Image File Extensions Are Not Being Set In The Database, Causing User Profile Image default to an error image.

## Environment Information

    Oqtane Version: 5.0.1

## Steps to Reproduce

1. Login to Oqtane as Host and upload an image for your profile and save your profile.
2. Navigate to Site Settings in the Host Dashboard.
3. Save Site Settings
4. Navigate to view the Host user profile image results with a error image placeholder shown.

## Expected Behavior

The profile image uploaded earlier is shown.

## Actual Behavior

Error image is shown.

## Screenshots
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/007fb497-e2c2-433f-bfb0-27aff8887e06)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/2854cd8b-bddc-4a93-ad24-fa4407342a47)

Additional Information
related to issue #3656 

When site setting button is used to save no value is assigned to the setting generated which is supposed to force the framework to use Image Extensions related constants. Although these values are visible in the UI, they are not being used.  Image Extensions constants are not being loaded when blank as expected behavior.  
- A checkbox to use constants that is checked by default would allow unchecking this to edit and not use Image Extensions constants allowing both approaches to be used avoid breaking changes.

**Comment by sbwalker** [comment]
resolved in #3667
