### ISSUE TITLE
File Upload Failure on .NET MAUI Client

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#3669]
## Issue Description

When using the .NET MAUI Blazor Hybrid client application and attempting to perform a file upload, the upload fails and an error message is displayed.

## Environment Information

All Oqtane versions up to and including 5.0.1

## Steps to Reproduce

1. Open the Oqtane.sln in Visual Studio and run the Oqtane.Server Blazor project
2. Open the Oqtane.Maui.sln in Visual Studio and run the .NET MAUI project
3. Login to the .NET MAUI client 
4. Navigate to the Admin Dashboard / File Manager /  Upload Files
5. Select a folder, browse to a file, and select Upload

## Expected Behavior

The file is uploaded successfully

## Actual Behavior

Upload fails and error message is shown:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/d92633b2-31cc-4631-a01f-e934dc499c57)

Additional Information
related to issue #3580

**Comment by sbwalker** [comment]
This is caused by the XmlHttpRequest call which is being made by the uploadFiles() method in the interop.js file. This is the only scenario within Oqtane where an XmlHttpRequest call is being utiized. And it works fine on both Blazor Server and Blazor WebAssembly hosting models when using a browser client.

The first problem is that the .NET MAUI client application runs on https://0.0.0.0 whereas the Oqtane.Server is running on http://localhost:44357. The difference in the domain origin triggers a CORS issue. This can be resolved by adding a CORS policy to the Oqtane.Server startup:

            services.AddCors(options =>
            {
                options.AddPolicy("AllowBlazorHybridOrigins",
                    policy =>
                    {
                        policy.WithOrigins("https://0.0.0.0", "http://0.0.0.0", "app://0.0.0.0")
                            .AllowAnyHeader().AllowCredentials();
                    });
            });

           ...

           app.UseCors("AllowBlazorHybridOrigins");
 
( note that this application of CORS is much too broad and would need to be modified to isolate it to only the API logic which needs to allow the .NET MAUI origin)

The second problem is the AntiForgeryToken. When running in  .NET MAUI there is no need to validate the anti-forgery token. However the logic to bypass this behavior is currently based on User-Agent - and there is no way to set the User Agent on an XmlHttpRequest.

Oqtane.Server\Security\AutoValidateAntiforgeryTokenFilter.cs

            // ignore antiforgery validation if client is a MAUI app
            if (context.HttpContext.Request.Headers["User-Agent"] == Constants.MauiUserAgent)
            {
                return false;
            }

The third problem is authentication. The XmlHttpRequest call is not passing the Principal of the logged in user to the API. An attempt was made to modify the uploadFiles() JavaScript method to include:

                request.withCredentials = true;

But this did not resolve the authentication issue.

**Comment by thabaum** [comment]
@sbwalker I believe a JWT token is the way to go.

Some questions if we do use the Jwt Token:
- Would this secret for the JWT Bearer token be needed for each installation per tenant, or per instance of Oqtane shared by all tenants?

- Will some logic randomize the secret(s) for Oqtane websites when installed?

- If this is going to be something any file upload UI control for Oqtane developed would need, would having this new ability to use Jwt Tokens be a new resource to build other features on top of?

**Comment by sbwalker** [comment]
@thabaum Oqtane has supported Jwt Tokens since Oqtane 3.1 (.NET 6) - https://www.oqtane.org/blog/!/37/oauth-2-0-and-openid-connect

**Comment by sbwalker** [comment]
Fixed in #3671 - note that you need to specify a Secret in the User Settings / Token Settings for this to produce a Jwt token:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/735ff8f4-57ab-4403-835d-ff2b8fe46245)

**Comment by sbwalker** [comment]
Final result in .NET MAUI:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/c37da10d-bf09-4267-a365-3b7365b312aa)

Note that if you open the Windows file picker repeatedly there is a known bug in WebView2 where it will crash the .NET MAUI application. This is not an Oqtane issue.
