### ISSUE TITLE
Replace IIdentity with existing (custom) Authentication/Authorization?

### ISSUE THREAD

**Issue by majorimi** [oqtane/oqtane.framework#3670]
Hi guys,

First of all thanks for the work this project looks very impressive. It provides a lots of features. For us now the page editor (CMS or not) capability is interesting and theming. And for future proof the update feature is also interesting.

However there are few deal breakers which blocks using it in a restricted environment. So few things must be figured out. Without too many details to bloat the post. We have an existing WebSSO provider with 250k user. It manages registrations, PW, tokens, cookies etc. Also has multiple instance in DMZ, internal network where it works with Windows credentials, etc... So complex system which we have to use...

My issue is more of a question/feature request. 
**Is it possible to dynamically replace the current Identity provider in your project? What I mean is like implementing a module and "install" it like a component?**
I was checking the code and it seems not really... Sure I can fork and reimplement `IUserManager`, `ClaimsPrincipalFactory`, etc. So I could replace it but then I might introduce issues by not replacing something and the Update functionality is gone, right?

**Comment by majorimi** [comment]
@sbwalker Thanks for the quick response. This is bad news for us. 
Unfortunately current SSO is Broadcom SiteMinder with LDAP, and bunch of custom services written around it. Never version is capable to support OAuth flows but this version is Cookie based... Which is not the best I know, for a while I urge for an update but it will happen probably next year. My project starts now so no time to wait....

I will find something which is capable of dynamic UI editing, CMS functionalities, etc.

Thanks, keep up the good work.

**Comment by sbwalker** [comment]
@majorimi there is nothing wrong with cookies... in fact the industry is embracing cookies once again as tokens have some limitiations - the Backend-for-Frontent (BFF) security architecture approach relies on cookies. Oqtane uses the BFF pattern:

https://www.oqtane.org/blog/!/39/backend-for-frontend-bff-architecture

**Comment by majorimi** [comment]
Yes Cookies are fine for server rendered frontend. However nowadays cookies become to be a swearword due to privacy etc... Also since our SSO only provides cookies it is used for APIs as well. Which by default does not have Microsoft provided Anti forgery token protection... But anyway this is a specific issue here not concerning this project.

**Comment by sbwalker** [comment]
Oqtane uses anti-forgery protections with its cookie implementation to ensure security best practices.
