### ISSUE TITLE
Easy Menu theme fix

### ISSUE THREAD

**Issue by ctwoodwa** [oqtane/oqtane.framework#3680]
I recommend white-space: nowrap be added to the default theme .app-menu .nav-item to prevent sub menu items from wrapping.

**Comment by thabaum** [comment]
@ctwoodwa Welcome to Oqtane!  Can you submit a pull request with some screenshots of before and after so we can review the update if you have the time?  I would love to refer you to [docs.oqtane.com](https://docs.oqtane.org/guides/docs/index.html) page where I can send a link on how to do this, but I am not sure it exists yet (possibly coming soon).

My process is to do it in GitHub, I usually do the following:

- locate the file I want to edit especially for quick pull requests like this 
- edit the file in GitHub editor, which creates a branch in your fork repository.  
- After saving the file I locate that branch in my repository by viewing all branches and edit the name of it to relate to its purpose.  
- You will see a notification to compare and generate pull request.  It should walk you through the rest of the process.

I just thought I would share, hope this helps if interested!

Cheers!
