### ISSUE TITLE
Running MAUI in android emulator doesn't seem to load the assemblies

### ISSUE THREAD

**Issue by pyramidsbuilder** [oqtane/oqtane.framework#3691]
I am trying to use Oqtane.Maui in android emulator, it fails, it seems that it cannot load the assemblies as it should

**Comment by thabaum** [comment]
@pyramidsbuilder Welcome to Oqtane! Thanks for reporting this. If you find a solution or any additional information in logs along with any screenshots please don't hesitate to share with us what you find.  

I will test Android and iOS next week as this is on my to-do list I have not made it to yet.  I run my IDE on a Hyper-V so I am unable to launch it.  I do have another system I am going to prep as an IDE with the hardware needed to accelerate the graphics so these can run.  I have an iPhone ready to test as well, along with a Droid phone and emulator.  I would love to assist as I can in this area of Oqtane.

Cheers!

**Comment by pyramidsbuilder** [comment]
@thabaum thank you very much,
It worked only on live server for me, it was a problem with connecting the emulator/maui to localhost, it didn't work on localhost even with enabling cleartext on Android settings, or using ssl.
Thanks

**Comment by thabaum** [comment]
@pyramidsbuilder thanks for the update!

**Comment by thabaum** [comment]
@pyramidsbuilder I believe the issue is with using a Self-Signed certificate as an FYI, Oqtane does not handle these very well in IIS Express so maybe relating.
