### ISSUE TITLE
Reload Problem

### ISSUE THREAD

**Issue by PfaffIC** [oqtane/oqtane.framework#3735]
We sometimes run into a problem where oqtane does not seem to load correctly after logging in via oauth (maybe also via oqtane login):
![image](https://github.com/oqtane/oqtane.framework/assets/131237130/1ce8aa40-f157-42a9-9442-4b587f90cecf)
  
The problem seems to occurr randomly. We got this error reported by our end users but struggle to recreate it and get more information on it.

Oqtane (Version 4.0.6) is running on IIS.

Maybe someone can take a guess on the errors cause based on the little information provided and has a solution to solve it / prevent it from happening.

**Comment by sbwalker** [comment]
without a way to reproduce this problem, it is not possible to investigate further.
