### ISSUE TITLE
Enh: Ability To Set Theme Navigation Bar Horizontal Menu Component Bootstrap Responsive Breakpoint

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3736]
# Issue

Theme Navigation Toggle Menu Items Are Not Very User Friendly Creating Challenges For Theme Developers Due To The `MenuHorizontal.razor` component limitations.

https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Client/Themes/Controls/Theme/MenuHorizontal.razor

## Current Behavior

The breakpoints for when things change on the menu are not set to bootstrap standards for md.  Changing this alone would at least make things break at the same point as the CSS bootstrap library does.

## Expected Behavior

The menu nav items break point works with number of menu items displayed.

## Solution

Proposing Enhancement For Theme Navigation Bar Horizontal Menu Component and CSS.  This could be by allowing a theme developer to pass a parameter to set the navigation menu breakpoints in bootstrap ie. ...-sm-md-lg-xl-...

Potentially some logic can count the total characters in the menu and dynamically set the breakpoints, however the issue is the CSS would need updated as well so might need something to override the responsive styling.   Doing it manually will allow instructions to set this, or logic needed to edit the css file as a few ideas.

## Screenshots
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/710dec1e-0b6d-440d-9c67-843785c60d96)

covers title of html module as seen here:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/78599a60-f293-4764-bc81-8ed512696d66)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/a1f0d718-7455-49f9-bb77-5c9e066be94f)

and if width set just right you get this:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/f024ca23-ae73-49ca-948f-74d08cd06249)
This is due to the media minimum width allowing about 1px of space and rare screen size but can be handled by updating this to `767.98px`.  PR #3765 will close this issue.
## Additional Context

If components are to be built per theme to be used and these are templates to build these components from we should focus on the themes Oqtane supports by default and set this to Bootstrap sizes `lg - 991.98px` for the responsive CSS and bootstrap classes used in these components.  This will allow more pages to be created without causing an extra line covering up parts of the app page content at the top when using the Oqtane Theme and Theme Creator Template.

I have a pull request I will submit to display the desired results. If this is a breaking change I will make the original default value when not set and if a theme passes it a value it can set the other breakpoints.

The example is: When you log in as host, you have 3 default pages, this will make it break before those three pages plus maybe one more drop to a new line.

**Comment by pyramidsbuilder** [comment]
@thabaum it is possible for theme developer to write custom component instead of MenuHorizontal.razor and also custom MenuItems components, so I guess this can be done on theme level?

**Comment by leigh-pointer** [comment]
@pyramidsbuilder yes it is possible.  Simply create your theming components in your theme project and use.  

A tip would be to included also the Oqtane.Client project for reference to Oqtanes theming components.  I found it handy when first starting off.  If you follow this tip, in Solution Configuration Manager, turn off build for Oqtane.Client in debug and release modes.  This is not needed.

**Comment by pyramidsbuilder** [comment]
@leigh-pointer  thanks for the tip, yes , I meant this issue may be not a "framework issue" as the MenuHorizontal.razor limitations can be avoided by creating custom Menu components

**Comment by thabaum** [comment]
@pyramidsbuilder Thanks for the feedback. For sure we can create a version of this entire app, modules, components and themes.  The issue is not an "issue" but an enhancement request.

The idea is to help make the framework have places to hook into it from the beginning to rapidly produce a working application.  Once we get a full discussion going here I will be able to lay out the ground work to paint a better picture of what I am proposing here.

The %^&* about the nav-bar is that it has who knows how many pages, so who knows for any given tenant/site how many pages it has, how long those page names are, and where to set the break point so things don't look ugly right?  

So what I would like to do is see if we can produce some sort of solution that would allow an administrator (one level below the developer) to set this OR potentially have the Oqtane Framework figure this out by adding up all the characters and setting the variables to set these setting accordingly.

This break point is hard coded and needs to be dynamic setting and located in theme settings in my opinion.  The CSS can be modified by whomever as they set the new bootstrap break point.

So if you are a theme developer and want to be sure your themes work with Oqtane, this is an issue IMO.  How does a theme developer set this in the stock UI controls we may want our theme to work with.

I am imagining themes that are built mostly for a generic application set of classes that allows styling very easily along with the flexibility to of coarse add your own controls, components, you name it...

I am not looking at this enhancement for myself, but for the community of developers we have now and to come.  Both component developers and theme developers that will provide marketplace products to enhance the Framework.

This can go either way, and just a thought for now.  My current fix is to just make it so the break point allows more than 2 pages while logged in, to set to lg instead of md and update css to do the same.  

I actually have 2 fixes currently for review that all relate and one if not both are not going to happen, but something will as the current breakpoint in CSS can be updated to at least fix the odd behavior while resizing a window on desktop.   Mobile this works great, you get a mobile menu.  On desktop this can use a better approach for at least allowing more pages by breaking to the mobile menu.

Again, theme related for sure.  A new theme that rewrites all these controls is always an option.  These controls are built for bootstrap.  So if you generate one out of Material you will most likely rewrite all of these controls.   But if your making a bootstrap theme you might just want to focus on styling the UI controls that come stock with Oqtane Framework.

The real issue is the break point is set for only a couple pages, the enhancement will be to allow you to set this break point as an administrator at least as described earlier.
