### ISSUE TITLE
Registration Emails Localization - Server app missing localization 

### ISSUE THREAD

**Issue by pyramidsbuilder** [oqtane/oqtane.framework#3794]
Currently the texts on server app are not localized for example the email verification email content is hardcoded, 
I think using resx files won't be a good solution and the framework may need some new entity like "LocalizedContent" to be managed from the Dashboard (Language Manager?)
Any ideas?

**Comment by sbwalker** [comment]
Personally I believe server-side resources should be localized using a consistent approach as the client-side. This will enable translators to localize the client and server using the same tooling and process. It will also be aligned with the current translation Nuget package distribution approach which allows for simple installation for administrators.

**Comment by pyramidsbuilder** [comment]
@sbwalker,  Yes I think the same but sites may require "per site" templates, example saying "MySite Email Verification" 
I think this is more templating than localization.
I will do the resx files for now

**Comment by thabaum** [comment]
Maybe the HTML editor can be incorporated to safely edit these resx entries as templates?

**Comment by hishamco** [comment]
> I think using resx files won't be a good solution and the framework may need some new entity like "LocalizedContent" to be managed from the Dashboard (Language Manager?)

We need to differentiate between localization resources and content localization. IMHO we should use a standard ASP.NET way for localizing resources using `IStringLocalizer` I know the `ResourceManager` is the default implementation which is fine for static resources, but might not be good for some corner cases such as Pluralization

Let me know if you need any help on this also I might create a PR for it

**Comment by sbwalker** [comment]
@hishamco you are correct that content localization is a different scenario than localized resources. Content localization is not on the product roadmap at this stage - there are other items which are higher priority.

**Comment by hishamco** [comment]
Hope to see any localization related feature ASAP :)

**Comment by sbwalker** [comment]
merged
