### ISSUE TITLE
Enh: NavigateTo Dashboard UI Button Control Located On Administration/Host Dashboard Pages.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3799]
## Enhancement Request

Add an "Admin Dashboard" button on admin pages to go to directly to the admin dashboard page or open dashboard panel, closing/canceling things if clicked to navigate away.  Some pages only have "Save" for example.  This would also help limit so many clicks to get to the next admin page you may need to view down to 2.  This can be introduced next to the current admin page component button(s) for each of the administration dashboard parent pages.

**Comment by sbwalker** [comment]
I would prefer to not include additional buttons in all Admin components
