### ISSUE TITLE
Registration: New User is redirected to "returnurl" before verification

### ISSUE THREAD

**Issue by pyramidsbuilder** [oqtane/oqtane.framework#3805]
When new user registers he is redirected to the "returnurl" before completing his verification or a message on how to complete

Expected: when user registers he should see an informational message to check his email to continue

**Comment by pyramidsbuilder** [comment]
#a7b7230180fe0a3083face25f3560c26b990e71a

**Comment by pyramidsbuilder** [comment]
#3806

**Comment by sbwalker** [comment]
@pyramidsbuilder thank you for reporting this issue and submitting a PR. I would like to provide some context on a few items:

1. At the moment the dev branch is undergoing a major migration to the new Blazor approach in .NET 8 (ie. adding Static rendering support). As a result I am not merging any bug fixes or enhancements which do not directly relate to this migration. This provides an explanation for why recently submitted PRs are not being merged.

2. It is generally not a good idea to include multiple fixes or enhancements in a single PR. This makes code reviews difficult to perform. In some cases in the past I have had to reject PRs for this reason. It is recommended in the future that you submit separate PRs for each fix or enhancement.
