### ISSUE TITLE
Script Tag not rendering data attributes

### ISSUE THREAD

**Issue by eahughes3** [oqtane/oqtane.framework#3807]
I have added a script tag to the Page Content and it renders but without the attribute.  Has anyone else seen this?

![Screenshot 2024-02-15 185049](https://github.com/oqtane/oqtane.framework/assets/5582243/2884d1f0-f577-42ee-9001-2b02cd866bc0)

![Screenshot 2024-02-15 185604](https://github.com/oqtane/oqtane.framework/assets/5582243/5a36dd9d-f138-4c1e-9583-cbe045342e0c)

**Comment by sbwalker** [comment]
@eahughes3 are you using the code from the dev branch, master branch, or a prior official release?

**Comment by zyhfish** [comment]
Submitted PR to keep the data attributes in the render content. but I have another question that the page.BodyContent will not be render when first load the page, but only render after click the navigate link, if this is a bug, then I will submit a new issue to handle it.

**Comment by eahughes3** [comment]
> @eahughes3 are you using the code from the dev branch, master branch, or a prior official release?

I am using release 5.0.2
