### ISSUE TITLE
"Refs" accidentally lost in latest dev source

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#3811]
### Issue Description
In the latest Oqtane v5.0.2 source release version and older, the `Oqtane.Server.csproj` file contains the setting `<PreserveCompilationContext>true</PreserveCompilationContext>` at line 20, which ensures the generation of the `refs` folder necessary for runtime compilation. 2sxc module depends on this .net fetaure since first Oqtane versions.  This folder can be found at `oqtane.framework-5.0.2\Oqtane.Server\bin\Debug\net8.0\refs` after building the Oqtane.Server.csproj.

However, in the recent Oqtane v5.1.0 development source, this setting appears to be missing. Consequently, the `refs` directory is not generated during the build process, which impact 2sxc module runtime compilation capabilities.

### Workaround for Developers
Developers can manually add the `<PreserveCompilationContext>true</PreserveCompilationContext>` setting back into their `Oqtane.Server.csproj` to temporarily resolve this issue. This workaround allows the `refs` folder to be generated during build, ensuring runtime compilation can proceed as expected.

### Permanent Solution Needed
Although the workaround addresses the issue for developers, it does not solve the underlying problem for the Oqtane release, as the `refs` folder will still be missing from the Oqtane release deployment package. It is crucial to reintegrate the `<PreserveCompilationContext>` setting into the project to ensure the `refs` folder is correctly generated and included in future Oqtane releases .

Thank you for your attention to this matter.

**Comment by sbwalker** [comment]
this was removed in an effort to make the project files consistent with the settings in .NET 8 - I have now added it back

**Comment by tvatavuk** [comment]
Thank you for the update, @sbwalker. I appreciate your effort in adding it back following the feedback.
