### ISSUE TITLE
Migration to System.Net.Http.Json is breaking change

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#382]
External module services should reflex this change.
- Service constructor should call base(http)
- http. GetJsonAsync(...) shhould be changed to  GetJsonAsync(..) and so on
- module creator templates should be updated

**Comment by sbwalker** [comment]
module creator templates are already updated as part of #381

**Comment by sbwalker** [comment]
this was resolved in the Blog sample module yesterday.
