### ISSUE TITLE
Bug: Admin - New Installs, Scheduled Jobs Will Not Load Default Installed Jobs On First Visit Flashing A Notification To Restart Stuck In A Loop (5.1.0)

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3838]
### Description
**Scheduled Jobs** component in the **Control Panel > Admin Dashboard** has a notification that flashes repeatedly by clearing itself and then appearing again in a loop and does not stop until navigating to a new page and also the page needs to be refreshed as it will be keeping the output logs in VS busy until you do.  This will make the **Control Panel > Admin Dashboard** UI button control inactive as well.

https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Client/Modules/Admin/Jobs/Index.razor

### Screenshots

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/4cb0fcc2-05f7-4025-9e6d-1d4ea9065f30)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/2285be3f-29ee-4593-b531-9f96a51718ea)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/0faf27bd-74d9-43f9-998d-f7f6ed4aa38e)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/4a2b7baf-e370-41fa-9943-49ab1a65346a)

### Additional Context
I have also noticed the double flashes (2 page UI reloads/refreshes) within the pages for static SSR and wonder if some caching or something needs to come into play to smooth that out to feel like it is one page load?

I just happen to be clicking through all of the admin pages today to discover this issue as I looked to see if any admin pages didn't double flash in Visual Studio IIS Express.  Currently this is the only page with this odd of a behavior with this notification loop.

More info...

After investigating more it went away, so I almost closed the issue.  But then I noticed how there where 2 scheduled jobs, and 0 showing before.

So after you stop the site in visual studio, or restart the app (only stable way is with stopping VS) then starting it again the problem goes away.

This was seen in all render modes.  It is a fresh install issue only on first visit, then restart and it goes away displaying the two jobs shown below.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/a97a49bb-b9f1-4fbe-9748-32a2dfcc8fdf)

Out of all pages tested located in the admin control panel dashboard parent pages it felt like admin/system/Index.razor or "System Info" loaded the quickest without any double flashing going on, just the form and UI is loaded, then data in the form comes later as you would expect.  Site Settings will load the entire UI twice compared to System Info, or at least it feels this way.

**Comment by zyhfish** [comment]
Hi @thabaum , is there a clean reproduce steps or any screencast to help to understand the issue? thx

**Comment by thabaum** [comment]
@zyhfish hello, here are some steps to reproduce.

This should reproduce, although I have not tested on todays branch.

1. Create a clean visual studio instance from the dev branch (5.1.0)
2. Install in instance of Oqtane from within visual studio after building it for the first time.
3. Login as host.
4. Click on the admin dashboard button from inside the control panel.
5. Click on Scheduled Jobs.
6. Watch the behavior described (flashing notification to restart)
7. Close or stop the debugging.
8. Run the application again ( a restart for Oqtane since doing this in app while running visual studio will pretty much force you to do the same).
9. Notice this issue is no longer a problem and 2 scheduled jobs are installed that did not show up prior.  As if they are being installed on the first visit.

The images follow along with where I was going and didnt have time to toss all this in.  Thanks for asking hopefully someone can reproduce.  It is odd and only happens on first visit to Scheduled Jobs administration page.  After that there are no issues as these get installed and the app is restarted.

**Comment by zyhfish** [comment]
Hi @thabaum , thx so much for the information. I tried to analyze the issue and found several issues need to be fixed here:
1. RenderModeBoundary.AddModuleMessage will call to StateHasChanged to refresh the render, but this will trigger the module control component re-render as well, in this case there will be a infinite loop which cause the error, to verify this, you can add below code to avoid the infinite loop in Oqtane.Client\Modules\Admin\Jobs\Index.razor:
`private List<Job> _jobs;
private bool _rendered = false;

public override SecurityAccessLevel SecurityAccessLevel { get { return SecurityAccessLevel.Host; } }

protected override async Task OnParametersSetAsync()
{
    _jobs = await JobService.GetJobsAsync();
    if (_jobs.Count == 0)
    {
        if(!_rendered)
        {
            _rendered = true;
            AddModuleMessage(string.Format(Localizer["Message.NoJobs"], NavigateUrl("admin/system")), MessageType.Warning);
        }
        
	}
}`
We need to find out the root cause of this infinite loop issue and make a real fix there.
2. the jobs list is empty when first load the website.
3. if we delete all the jobs, then restart the application, the jobs will come back.

I will continue to check and see whether can provide a complete fix here.

**Comment by thabaum** [comment]
@zyhfish I have also verified that deleting the default jobs if they are already exist, revisit the page (F5 or hit refresh in browser), will trigger this issue.  Restart the app and the jobs re-appear in the Scheduled Jobs.
