### ISSUE TITLE
Save Functionality Generates Incorrect URL for Pages with Spaces in Page Names

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3937]
**Description**:
When using the save functionality to add a new page, the system automatically generates a URL for the page. However, if the page name contains spaces, the generated URL includes "%20" instead of replacing spaces with hyphens ("-"). For example, entering "Page Home1" results in a URL like "http://localhost:44357/page-home/page-20home1".

**Steps to Reproduce:**
Log in to the system.
Navigate to the page management.
Enter a page name containing spaces (e.g., "Page Home1").
Save the page.
Observe the generated URL.

**Expected Behavior:**
When saving a new page with a name containing spaces, the system should replace the spaces with hyphens ("-") in the generated URL. For example, entering "Page Home1" should result in a URL like "http://localhost:44357/page-home/page-home1".

**Actual Behavior:**
The system generates a URL where spaces are replaced with "%20" instead of hyphens ("-"), resulting in URLs that appear incorrect and potentially confusing.

**Additional Notes:**
This issue affects the readability and aesthetics of the generated URLs, potentially leading to user confusion and inconsistency in URL structures.

**Comment by sbwalker** [comment]
fixed in #3941
