### ISSUE TITLE
HtmlText module includes superfluous hard breaks

### ISSUE THREAD

**Issue by BCS-JonW** [oqtane/oqtane.framework#396]
Lines 11 & 13 of Oqtane.Client\Modules\HtmlText\Index.razor contain hard breaks that render below each HtmlText module.  It looks like there were put in for spacing the "Edit" button when in page edit mode, but they are not conditional, so they also output in page view mode which gives unexpected spacing to the page content.

**Comment by sbwalker** [comment]
Good observation. This should be removed or wrapped in a conditional @if (PageState.EditMode) { }
