### ISSUE TITLE
Crash on adding '/files' or '/files/' to URL

### ISSUE THREAD

**Issue by dkr98** [oqtane/oqtane.framework#3984]
Hello!

I found a small bug, when I just add /files or /files/ to the root URL I get the following crash on Files.cshtml.cs:

![Screenshot 2024-03-13 125247](https://github.com/oqtane/oqtane.framework/assets/131379326/733f4a70-8d0e-4612-90bf-53f2ecb9e65c)

**Comment by thabaum** [comment]
I can confirm this issue, should resolve 404?

Get an HTTP Error 500 on IIS site.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/335d3577-c126-4c2b-a246-e978073b7819)
