### ISSUE TITLE
Enh: HTML/Text - Quill Setting Option That Removes The Extra <br> HTML Element Inside <p> Elements on Blank Line Returns (Enter Key) In The Rich Text Editor.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3989]
# Enhancement

## Description

HTML/Text Editor Creates Extra `<br>` HTML Element Inside `<p>` Elements on Returns (Enter)

## Steps to reproduce

1. Edit an `Html/Text` module content by clicking the edit button within module UI while in page edit mode.
2. In the `Rich Text Editor` hit the `enter` key to add new lines.
3. Switch to `Raw HTML Editor`
4. Click `Synchronize Content`
5. View the `<p><br></p>` adding 2 new lines if you have one that is empty.
6. Also notice in the screenshot below that if you enter something into the paragraph element it does NOT include the extra line break

## Additional Info

After investigating it looks like this is a known or expected behavior.  It also looks like there maybe a way to control this.  I am reviewing `quill-interop.js` for ways to add an enhancement potentially.  This is not a "bug" anymore and may be closed if something isn't provided shortly.

I am guessing we may need an options for the keyboard and clipboard to `matchVisual: false` type of settings so `<br>` elements are not introduced into the HTML raw source code inside of empty `<p>` elements resulting in the `<p><br></p>` when using the enter key.  Quill does this by design but there is looking like a way to control this behavior.  It is just a question of how should this be done right for Oqtane Framework if introduced as an HTML Editor default configuration setting for a site/tenant.

I think for most rich text editors a new paragraph is expected on enter, and shift + enter would give a `<br>`, but as of now, both provide both.  This results in 2 lines and is annoying to work with.

I am going to test out the idea of finding 
```
<p><br></p>
```
replace with 
```
<p></p>
```

Notice the behavior as you add either or and both to raw data, hit synchronize content, and even save and see the results how this can really be a pain/issue.

We could start testing Quill 2 RC 2 as well... seems like some things are being added/removed.

If you copy and paste the HTML into the raw editor and save it... or remove it there manually the extra lines will not be saved as work around.  I believe this happens only once you have viewed the Quill Rich Text Editor tab.

#### Resourceful Links

- [Quill Documentation](https://quilljs.com/guides/how-to-customize-quill)
- [Quills keyboard related source functionality](https://github.com/quilljs/quill/blob/1.3.7/modules/keyboard.js)

## Screenshots
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/94caeed8-638b-4a14-bfd4-3e66c1e0952f)

**Comment by sbwalker** [comment]
This can be explored as part of #4007
