### ISSUE TITLE
need help/support concerning navigation/breadcrumb

### ISSUE THREAD

**Issue by mundl21** [oqtane/oqtane.framework#399]
Navigating deeper with parameters by "querystring", everythings works fine. 
Navigating back using breadcrumb "querystring" is empty. 

page 1 -> page2 (with Parameter) -> page 3 (with Parameter) 

page 1 <- page 2 (querystring is empty) <- page 3 

How to solve it? Any idea welcome…

Thanks

**Comment by hishamco** [comment]
I'm suggesting to pass parent menu item as a part of URL, so whenever you click the menu item it will know its parent, say:

Page1 -> Page 2 -> Page 3

Page 1 Link: domain.com/page1/?parent= or domain.com/page1

Page 2 Link: domain.com/page2/?parent=page1

Page 3 Link: domain.com/page3?parent=page2

**Comment by mundl21** [comment]
Hi hishamco,

I am not sure, if vou have understood my concern. The problem is navigating back using the same Parameter, which i have used to navigate to a deeper page. The current breadcrumb don't  has the possibilty to use parameters.
My idea is to use a static array to store the url with Parameter. Or could you propose a better solution?
Thx for you support.

**Comment by hishamco** [comment]
> The current breadcrumb don't has the possibilty to use parameters

I thought you implement your own, anyhow, give me a screenshot for the current breadcrumb, I will have a look to the source then

**Comment by mikecasas** [comment]
Hi @mundl21, not sure if the this will help.

I tried creating a three-tier page with Animals -> Cats -> Felix, and the breadcrumb brings you back to it's parent page.

![bread](https://user-images.githubusercontent.com/11261164/80308144-3b223680-879b-11ea-81e5-93eab5286584.PNG)

**Comment by gf21** [comment]
@hishamco 
Until now I have not implemented my own breadcrumb

@mikecasas 
Sorry for my bad english, i think you have not understood my concern, i try again.

Let's take your example with the animals. I don't want the animal species to be shown in a submenu, but as a list on the animals page (e.g. cats, dogs and so on). If I now select the animal type "cats", I pass the parameter "cats" to the next page, which then shows all cats as a list. In the BreadCrumb I now have "Animals -> Animal Category". I select now a special cat, e.g. Felix and pass the parameter "Felix" to the next page to show all details about this cat, the BreadCrumb now contains "Animals -> Animal category -> Animal details". The drill down works perfectly. However, I now mark the item "Animal Category" in the BreakCrumb, here it is no longer known which Animal Category it was. I think that this problem can only be solved via a static class (currently the breadcrumb is dynamically built using the ParentId's) or have you other ideas?

Thx for your support.

**Comment by mikecasas** [comment]
@gf21 Just conceptual, but maybe create a cascading parameter that stores your animal category and the animal details that you selected.

Then as @hishamco said create a new breadcrumb that uses this parameter, and build your breadcrumb routes accordingly.

If I have time I will try and construct a sample.

**Comment by gf21** [comment]
Hi mike,
thank you for your hint. I have expanded now the class "Pagestate" with a navigation stack and fill it in the siterouter , works perfektly..

**Comment by mikecasas** [comment]
@gf21 Great, glad that it works. Can I see how you did it? If it's useful for others maybe we can commit  it to the framework.

**Comment by gf21** [comment]
Hi Mike,

 

yes gladly.

 

1.       The new class for saving the navigation:

public class NavigationStack

    {

        public string Path { get; set; }

        public int PageId { get; set; }

        public string Params { get; set; }

        public int OrderId { get; set; }

    }

and additional property in the class “PageState”:

        public List<NavigationStack> NavigationStack { get; set; }

 

2.       Code in the Refresh method of the SiteRouter:

 

List<NavigationStack> stack = new List<NavigationStack>();

…..

// check if page has changed

            if (page.Path != path)

            {

                page = pages.Where(item => item.Path == path).FirstOrDefault();

                reload = Reload.Page;

                editmode = page.EditMode;

                designmode = false;

              

              // New code for navigation

                // go back

                if (PageState.NavigationStack.Select(m => m.PageId).ToList().Contains(page.PageId))

                {

                    foreach (var p in PageState.NavigationStack)

                    {

                        if (p.PageId == page.PageId)

                            break;

                        else

                            stack.Add(p);

                    }

                }

                else

                {

                    // go forward

                    if (page.ParentId.HasValue)

                        if (PageState.NavigationStack.Select(m => m.PageId).ToList().Contains(page.ParentId.Value))

                            stack = PageState.NavigationStack;

                }

 

                // add new navigation Page

                string param = string.Empty;

                if (_absoluteUri.IndexOf("?") != -1)

                {

                    param = new Uri(_absoluteUri).Query.Substring(1);

                }

                stack.Add(new NavigationStack { PageId = page.PageId, Path = page.Path, Params = param, OrderId=stack.Count() });

 

            }

…

              At the end of this method:

                    pagestate.NavigationStack = stack;

                    OnStateChange?.Invoke(pagestate);

 

3.       Breadcrumb code replaced by:

string breadcrumbs = "";

 

    protected override void OnParametersSet()

    {

        breadcrumbs = "";

 

        foreach (var p in PageState.NavigationStack.OrderByDescending(m=>m.OrderId))

        {

            string param = string.Empty;

            if (!string.IsNullOrEmpty(p.Params))

                param = "?" + p.Params;

            breadcrumbs = "<li class=\"breadcrumb-item" + ((p.PageId == PageState.Page.PageId) ? " active" : "") +

                    "\"><a href=\"" + NavigateUrl(p.Path) + param + "\">" + p. Name + "</a></li>" + breadcrumbs;

        }

        if (breadcrumbs != "")

        {

            breadcrumbs = "<ol class=\"breadcrumb\">" + breadcrumbs + "</ol>";

        }

}

 

That’s it. 

 

Thank you again.

 

Gisela

 

Von: Mike Casas [mailto:notifications@github.com] 
Gesendet: Freitag, 1. Mai 2020 17:51
An: oqtane/oqtane.framework <oqtane.framework@noreply.github.com>
Cc: Gisela <g.fromm@4isoftware.com>; Mention <mention@noreply.github.com>
Betreff: Re: [oqtane/oqtane.framework] need help/support concerning navigation/breadcrumb (#399)

 

@gf21 <https://github.com/gf21>  Great, glad that it works. Can I see how you did it? If it's useful for others maybe we can commit it to the framework.

**Comment by mikecasas** [comment]
Thanks...I'll look at this eventually.

**Comment by sbwalker** [comment]
Another option is that you could build your own Breadcrumb component and use it in your theme
