### ISSUE TITLE
Bug: 5.1.0 - Default Personalizable Page Renders First, Then The Users Page Is Displayed Causing UI/UX Issue

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3998]
# Issue

## Description
After creating a user personalizable page after clicking on the pencil as a registered user a user then is creating their own personalizable page they can modify currently by adding/removing modules and editing them.

This part is working now, however a new issue is when you select "My Page" you will see the default page first render, then forwarded to the user page.  This will cause a user experience issue seeing both UI's when they click on their personalizable page.

## Steps to reproduce
From a fresh 5.1.0 dev branch VS installation:
1. Create a registered user
2. Login as registered user and navigate to the personalizable "My Page".
3. Click Edit Pencil to generate a personalizable page for the registered user.
4. Navigate to and from this page after changing title adding an extra character for example an `s` to make `My Pages` for the title of the default HTML/Text module to notice the behavior.

## Screenshots
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/0f784362-bacd-4099-b06d-533be3245aa0)

**Comment by sbwalker** [comment]
Supporting both static and interactive render modes is going to be a challenge... as the runtime characteristics are a lot different. Fixing a bug in static mode can very easily break the functionality in interactive mode.
