### ISSUE TITLE
[BUG] Interactive/Auto - Users Experience Long Delays Logging Into Oqtane With `Interactive/Auto`  Versus `Interactive/Server` Site UI Component Settings.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3999]
# Issue

## Description
Logging into and out of Oqtane seems to come with longer delays I don't think where experienced before.

## Steps to reproduce

1. Set to `Interactive/Auto` UI Component Mode as shown in screenshot below using the 5.1.0 latest dev branch to experience this issue while logging in.
2. Log out.
3. Login and wait for the page to load to notice the different behaviors while changing between `Interactive/Server` and `Interactive/Auto` and repeating these steps with the two UI component modes in `Site Settings`.

Note:
_Log out and wait for next page to load.  (long period to logout is with all render modes and can be logged as an enhancement to potentially review down the road)_

## Additional Context
- Interactive/Server seems faster at logon. Logging in using Interactive/Auto should be as fast as it is for Interactive/Server mode.
- The logout takes time for all modes. So logging out has the expected behavior for now as maybe this experience can be improved all around.
- Interactive Static has the best experience for logging into the app. It has the quickest feeling response time.

I noticed below are my settings in screenshot.  `Interactive/Auto`

I switched to `Interactive/Server` and `Static/Server` and Login was quick, but logout same experience.

Maybe a spinner/loading feature can be added here?

Maybe 2 issues here to review:
1. `Interactive/Auto` should be as snappy as logging in with other the UI component modes.
2.  Logging out should be just as quick as logging in.

This could be an IDE issue as well, not sure but `Static/Server` seems to be working very well.

## Screenshots
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/9b463e2b-8d9f-40d4-8184-72df069514e0)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/5ed3861f-a785-4ff8-a9e4-f6e8a0717b93)

**Comment by sbwalker** [comment]
If you have interactivity set to Auto it essentially means you are using WebAssembly. This means that browser needs to download the DLLs to the browser to run it. When you login or logout it initiates a server-side web request to set the auth cookies - which means that the browser initiates the download of the DLLs again. This is the reason for the delay.

**Comment by thabaum** [comment]
Just wondering if maybe there should be a spinner if it is expected.  I figured in Auto mode the components would be set to auto mode and give a server load first and load the web assembly in the background.  So you should not really see much of a performance loss.

**Comment by thabaum** [comment]
@sbwalker I will also retest this area once we get the HttpClientFactory utilized.

**Comment by thabaum** [comment]
#4064 may produce a bit different behavior here.  It seems to log out now takes less than a blink of an eye or better, but logging in takes time still.  It should run server then web assembly, so everything should be as fast as server as well.

**Comment by sbwalker** [comment]
@thabaum note that #4059 is related to the behavior of Auto mode as well

**Comment by thabaum** [comment]
@sbwalker thanks I will review.

**Comment by sbwalker** [comment]
@thabaum note that I am not going to hold up the release of 5.1 for this item as it only affects 1 very specific configuration

**Comment by thabaum** [comment]
@sbwalker from what I can tell switching through pages in interactive/auto mode runs GREAT when not clicking logon or logout UI controls.

**Comment by thabaum** [comment]
@sbwalker A few more notes: 
- Interactive/Server seems faster at logon.  Logging in using Interactive/Auto should be as fast as it is for Interactive/Server mode.  
- The logout takes time for all modes. So logging out has the expected behavior for now as maybe this experience can be improved all around.
- Interactive Static has the best experience for logging into the app.  It has the quickest feeling response time.

**Comment by thabaum** [comment]
@sbwalker The difference in modes can be seen when you use F12 developer tools in the browser and look at the network requests total on the network tab.  It is over 53 when in Interactive/Auto vs about 19 in Interactive/Server.  It really looks like maybe duplicate requests possibly.  Log out and back in to see the differences in the different render modes.  You can also notice the page requests to the HTML modules on the page.  Issue is page should load on the first request and seems like it is held up until the final double request takes place.

This could all be expected with one being for server and the other webassembly but something worth a review.

**Comment by sbwalker** [comment]
@thabaum note that when you are running Interactive/Server the Html/Text module is loading the module content directly from the server (because it is running on the server) - whereas on Interactive/Auto the Html/Text module is first loading the module content on the server (ie. pre-rendering) and then reloading the content on the client using HttpClient API calls.

**Comment by thabaum** [comment]
@sbwalker When stream rendering attribute is commented out of the app and components I have experienced the site going blank (black) while testing this (switching between the three interactive modes Server/Client/Auto).  I have had this happen more than once so I wanted to make a note of it see if anyone else experiences it.  This could just be a Visual Studio issue with Oqtane switching modes frequently.

On another note: In Static/Auto mode it is handling 24 requests on a login, blink of an eye fast UI experience.  Interactive/Client was over 70+.. Static/Server is the least at 17 logging into Oqtane with the home page as the return url.

**Comment by thabaum** [comment]
@sbwalker Yes, the Interactive/Server vs Interactive/Auto Login UI control button/action differences in redirected page lag time issue still exists in the latest dev branch Oqtane Framework along with the latest .NET and Visual Studio updates.

System Info:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/c041c759-1db4-4efe-b934-ee5c5315391e)

The Logout button action is the only place I notice this redirected page load time delay.  Fast in Server mode, very very slow in Auto mode, similar to logging in which has almost the same delay.  

Keeping on the Home page, fresh installation, using host account page results:

---

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/f273d1ba-31cc-476d-b642-2f7a2a79b155)


**Interactive/Auto Logout:**
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/bedf70a4-3d17-4bd0-9bcd-7416d799e69c)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/3cc5d405-0bba-4bc9-b8ba-b1818be58b56)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/1288d246-5566-4c97-8dbe-52b142005694)

**Interactive/Auto Login:**
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/dac98a58-5cec-4ddc-aa1a-e782f5870a1d)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/98a82471-332a-4ae3-b004-4b7bd8e7a61a)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/2c0b58ee-dfdc-425a-aefb-061ccb6830fd)

---

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/28537e26-384c-40b9-815b-48151f48c54e)

**Interactive/Server Login:**
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/bd64de3b-a870-4218-b7a3-6306c0a21297)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/0842e052-037e-4dc3-995a-9b6fdf09ddc6)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/69449b44-c4d6-4ccc-9e58-7d9e643346cd)

**Interactive/Server Logout:**
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/5b2331e2-e9b4-49b8-9164-6d43c93afaa3)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/b9c92e8a-dd5b-43bd-a01d-0deca5d14c35)

These screenshots of results should show there is a difference in Login/Logout actions from Home page load times.

**Comment by thabaum** [comment]
@sbwalker While switching between the default site template pages there is also an awful HTML content load time noticed between the time you see the Title of the HTML module and the HTML module Content while in Interactive/Auto.  The title and content for the HTML module should be blink of an eye same time you would think without any noticeable delays.  Seems like it requests a lot of the same authentication information for each piece of the HTML module component resulting in a lot of repeated requests.

I was wondering if it had a different ID instead of 1, 2, 3 in order of loading, something more unique it would remove this effect?  Maybe `authmoduleId=1ModuleTitle` would work so that the DOM knows this is something unique and if it does not exist anymore on a page render then don't put any information there updating its content if/when this information is available.  Module Title can be shortened but long enough to ensure it will most likely be unique.  Something of this nature that gives each module a more unique way to identify each module and if the content will be the same or not.

Maybe this issue is expected behavior, or should another issue be logged?  Just thought I would mention it since it relates to Interactive/Auto and maybe a clue to the issue here to the extra delay.

**Comment by sbwalker** [comment]
@thabaum I think the problems with Auto mode are not related to Oqtane, but rather with how it was implemented in Blazor. Based on all of the issues I have seen logged in the Blazor repo, it does not appear to work as described in the marketing propaganda from Microsoft. I think it was most likely tested on the default Blazor app template which has no services or data access and therefore does not represent a real world app scenario. At this point I would recommend using Server or Client for Interactivity, as both of these hosting models have been  proven over many years of usage. When using Client it is important to note that HttpClient is used for all interaction with the server - therefore there will be higher latency than when you are running Server (which performs data access directly on the server). In addition, when running in Interactive render mode, prerendering is enabled by default which means that data access is usually occurring twice (once during prerendering and again during component rendering). You can turn off Prerendering in Site Settings and it will eliminate 50% of the data access (but also means that your content would not be indexable by search engines).
