### ISSUE TITLE
Enhancement: Edit html text dialog is opening slow when loading first time.

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4002]
The "Edit Html/Text" dialog when open slowly when loading first time. it will take several seconds to display the full layout, and UI is hang up during the loading time.

Reproduce Steps:
1. enter the edit mode of home page.
2. click the "Edit" button of a html module.

Expected Result:
the "Edit Html/Text" dialog should display quickly so that user can edit the content.

Actually Result:
the UI is hang up for seconds to wait for the dialog fully loaded. but it will display quickly next time after the dialog is loaded for the first time.

**Comment by zyhfish** [comment]
This issue will only occur when running the instance from visual studio directly.

**Comment by sbwalker** [comment]
@zyhfish I have never experienced this - are you referring to when the Site is running Static or Interactive render mode?
