### ISSUE TITLE
Enh: HTML Editor Reset Content Button

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4008]
# Enhancement Request

## Description
Enhance the HTML editor with a "Reset Content" button to allow putting the HTML information back to the original.

Additional Context:

PR #3997 is suggested to remove the synchronize button. I believe we can change this to the reset button which will bring back your editor information instead of having to hit cancel and click edit again to bring up the window which is costly on the server.

Below is a solution:

---
#### RichTextEditor.razor

Below would be the modified version with changes to removing the additional methods unless they introduce some added benefit working with it more precisely?  This includes the "Reset Content" button logic for resetting the content...

---
line 22 about add the reset button (remove the synchronization button if syncing between tabs): 
```
@if (AllowRawHtml)
{
  <button type="button" class="btn btn-secondary" @onclick="ResetContent">@Localizer["ResetContent"]</button>
  @((MarkupString)"&nbsp;&nbsp;")

}
```
---
same in the next `else` tab panel ui control (remove the synchronization button if syncing between tabs):
```
  <button type="button" class="btn btn-secondary" @onclick="ResetContent">@Localizer["ResetContent"]</button>&nbsp;&nbsp;
```
---

Add this function at the bottom of the` @code`:

```
public void ResetContent()
{
  _richhtml = _originalrichhtml;
  _rawhtml = _originalrawhtml;
  StateHasChanged();
}
```

---
#### RichTextEditor.resx

add (remove related entry for synchronize content if not used anymore)
```
  <data name="ResetContent" xml:space="preserve">
    <value>Reset Content</value>
  </data>
```
---

**Comment by sbwalker** [comment]
Closing as I already explained that a Reset button is no better than a Synchronize button from a user experience perspective. The Rich Text and Raw HTML editors need to be treated as independent elements.

**Comment by thabaum** [comment]
sync content does not "Reset Content", are you sure you understand this clearly?  I think it is a nice enhancement as explained but that is OK.

Personally I find it handy as I explained, as a user.  If I mess up the HTML, I currently have to hit "Cancel" then "Edit" again.  Doesn't this tax the server an additional call, and the user some additional time?

Synch content you need to be able to see what the rich editor has, which I believe sync between tabs OR two different HTML Modules need created.

**Comment by sbwalker** [comment]
@thabaum if you modify content and want to revert/reset wouldn’t you use Control-Z?

**Comment by thabaum** [comment]
@sbwalker FYI, I am going to see about moving the insert image into the toolbar, I see the reset content button if included being next to the cancel or save button to not take up another line of UI if included since the synchronize button is now removed.
