### ISSUE TITLE
Enh: HTML/Text Module Insert Image Button Changed To Toolbar Icon

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4014]
# Enhancement Request

## Description
Move the "Insert Image" button to the toolbar for the Oqtane HTML/TEXT component module.

Requirements:

1. Rich text Editor Tab Panel displays button in toolbar
2. Raw HTML Editor Tab Panel retains the insert image button.

## Additional Context
- Insert Image button is all alone at the top now that the synchronize content button has been removed.  We can save some real-estate if we can move this into the toolbar of the Quill Editor while the Rich Text Editor component is being used.

- Maybe raw HTML Text editor Insert Image button control can be moved next to Cancel button control at the bottom? 

I have not started working on this yet, so if anyone is up for the challenge please be my guest.  I may attempt it today.

## Screenshots

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/285599b7-744c-44bc-832b-0a929b0bb1fd)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/77ac8500-2f50-4f34-8af6-412819837960)

**Comment by sbwalker** [comment]
Personally I like the fact that the way to insert images is consistent between the Rich Text and Raw HTML editors.

**Comment by thabaum** [comment]
Closing as the "Insert Image" button does grow on you, especially now that it is focus along with the UI it displays above this in fact should not be touched.
