### ISSUE TITLE
Enh: Add Support For Copy Existing Module to Control Panel

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4030]
Reproduce Steps
1. Create a new page, use "Add existing module" function to copy a module from home page.
2. edit the module with some new content.
3. browse to the home page.

Expected Result:
home page should keep it's original content.

Actually Result:
After make changes in the new page, home page's content will also be affected. at least we should give an option for whether it's a copy or reference action to avoid any confuse.

**Comment by sbwalker** [comment]
The option for "Add Existing Module" only supports copy by reference - so this behavior is actually valid. I think it is only confusing to you because you have experience with DNN which has additional options. For users who are not familiar with DNN I think the current option makes sense. Perhaps in the future we could add a Copy option but for 5.1 I would like to focus on stabilizing the release.

**Comment by sbwalker** [comment]
The Control Panel could be enhanced to include an additional option in the dropdown for "Copy Existing Module" which would allow the Admin to choose the page/module (similar to Add Existing Module). For copying the module content, this would need to rely on IPortable - however not all modules implement the interface so it would only be useful for a subset of modules.

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/95bacdd7-4941-45d5-a7c3-488a0a2e1789)

**Comment by thabaum** [comment]
Another idea would be to add a `Copy (Mirror)` and `Sync (Duplicate)` select options to the `Add Existing` module UI.  This would help for clarity.
 and added tool tip information:
```
    Copy Module:
        Description: This option duplicates the existing module, creating an independent copy that can be edited separately.
        Use Case: Choose this option if you want to create a standalone copy of the module with no connection to the original.

    Mirror Module:
        Description: This option creates a mirrored instance of the existing module, ensuring that any changes made to one instance are reflected in the other.
        Use Case: Select this option if you want changes made to one instance of the module to automatically propagate to the other instance.
```

```
[Add Existing Module]
[Select Page]
[Select Module]
[Select Mode]  <- Sync (Mirror)/Copy (Duplicate)
[Title]
...
```

I also remember an option of "Is Shareable" in DNN to allow or not allow sharing the module with other pages or group sites.

Just tossing in some feedback along with some additional ideas while we are discussing.

**Comment by sbwalker** [comment]
One of the reasons the "Copy Existing" was not included in the Control Panel is because there is already the ability to accomplish this for modules which support IPortable. Basically you can use the Export/Import option for those specific modules which support it. The goal with Oqtane is not to replicate the functionality of DNN... it is to reduce the baggage and focus on creating a lean and high performance framework.

**Comment by thabaum** [comment]
I agree with keeping it lean and mean while reviewing what options are ready to be cherry picked as needed to accomplish anything an app similar to DNN or any CMS can be designed to do.  Building an app with component modules that can be inserted, moved and removed, we should look to add all the developer features at the core needed to provide this use case as well.  

Although similarities can fool someone Oqtane is definitely NOT DNN and is in a more raw form, at the same time we should be able to build DNN with Oqtane.  I suppose the "Shareable" feature could be introduced into module settings and would be another issue to create.  

I was just feeling that if you do not want certain modules to accidentally get shared or copied on another page by another administrator this could be a way help keep them from being displayed in the list.  I also liked how if you uncheck this feature or remove it from being mirrored it will set that module as it's own instance with the imported data going forward.

Enough said there, overall keeping on point I like the "Copy Existing" idea feature suggested.
