### ISSUE TITLE
[ENH]: Javascript resources from reusable module are not included

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4038]
Possible bug as per described in #4037.

Modules that can be reused in others, like RichTextEdit, should be able to include its own Javascript resources (not css) but they are not loaded nor inserted in the body/head when the modules are rendered in Static mode.

As a workaround, all resources from a child component must be defined in the calling (parent) module.

**Comment by mdmontesinos** [comment]
Something else to note is that the onUpdate function of a js resource set with Reload=True is called 8 times in a single page transition... (when returning back to the page where the module is)

![image](https://github.com/oqtane/oqtane.framework/assets/90258222/c3e4388c-b07d-479e-8157-15bcb143762a)

The module in only included once in the page, with a single instance of it.

This could become problematic when many modules are reloaded and their onUpdate functions are more complex, perhaps adding too much overhead.

**Comment by mdmontesinos** [comment]
So we do need to set Reload to true for every js resource in modules that will be used in static mode, right?

Also, I'm not very js proficient, but the current js generated in the module template seems to not be compatible with this approach.

```js
/* Module Script */
var [Owner] = [Owner] || {};

[Owner].[Module] = {
};
```

Should be replaced with something like:
```js
/* Module Script */
function initialize[Module]() {
    "use strict";

    const hello[Module]Function = () => {
        console.log('Hello World from [Module]');
    }
}

export function onUpdate() {
    initialize[Module]();
}
```

And I should just invoke it like hello[Module]Function() ?

**Comment by sbwalker** [comment]
@mdmontesinos if you take a look at the [Arsha](https://github.com/oqtane/Oqtane.Theme.Arsha) theme I published this week you will notice that there are a variety of JavaScript resources - however the majority of them are JavaScript libraries which are not executable - they simply need to be included in the page output. There is only 1 JavaScript file which is actually executable and needs the Reload set to true.

**Comment by sbwalker** [comment]
The module.js file in the module template contains no implementation - it just demonstrates how to include the resource. An Interop.cs is also included in the Client - which is the way that JavaScript needs to be called in Interactive Blazor - but it has no example implementation either.

In general, JavaScript is the most difficult technology to integrate with Blazor... and Static Blazor does not make it much easier (due to Enahnced Navigation)

**Comment by sbwalker** [comment]
@mdmontesinos is Reload the right name for this property? It's accurate from a Blazor perspective but from a standard JavaScript perspective, Load might be more appropriate? I can envision that in Interactive Blazor there may be support for this property ie, it could call a Load method without having to write the JS Interop logic yourself in your module.

**Comment by mdmontesinos** [comment]
@sbwalker I believe Reload is the right name for the property (compared to Load), at least when considering its use case in static mode. If you rename it to Load, I believe it could be confusing because, why wouldn't you set Load=True for all js resources? Don't I want to load them in my module? Reload kind of indicates better that the resource could be "unloaded" in some cases and you must use this property. Also, Reload relies on the use of the onUpdate which is triggered often, so it's important to stand that out in the naming. Lastly, and I might be wrong, but many Blazor/Oqtane developers are usually not very proficient in js as they come from typical .NET apps, so maintaining a Blazor perspective for the naming seems most appropriate for me.
