### ISSUE TITLE
Issue with compilation in Oqtane 5.1.0 when copying source files over existing version

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4072]
Description:
When attempting to compile Oqtane 5.1.0 after copying source files over an existing version, a compilation error is encountered. The error specifically relates to an ambiguous reference to 'Runtime', which is present in both 'Oqtane.UI.Runtime' and 'Oqtane.Shared.Runtime'. This issue is hindering the compilation process and needs to be addressed.

Severity: High

Error Message:
Severity	Code	Description	Project	File	Line	Suppression State	Details Error CS0104 'Runtime' is an ambiguous reference between 'Oqtane.UI.Runtime' and 'Oqtane.Shared.Runtime' Oqtane.Client D:\source\_Oqtane Instances\_Oqtane\Oqtane.Client\Themes\Controls\Theme\Login.razor 12 Active
Steps to Reproduce:

Copy source files of Oqtane 5.1.0 over an existing version.
Attempt to compile the project.
Observe the encountered error related to ambiguous reference to 'Runtime'.
Expected Behavior:
The project should compile successfully without encountering any ambiguous reference errors.

Actual Behavior:
Compilation fails due to an ambiguous reference error to 'Runtime'.

**Comment by leigh-pointer** [comment]
To fix this it requires a manual delete of the following files:

- Oqtane.Client\UI\Runtime.cs
- Oqtane.Server\Pages\_Host.cshtml
- Oqtane.Server\Pages\_Host.cshtml.cs

**Comment by sbwalker** [comment]
@leigh-pointer Oqtane has never officially supported copying source files over an existing installation. If you are using a local source version of the framework you will need to reconcile any source code changes manually.

**Comment by sbwalker** [comment]
@leigh-pointer it would be useful to post this in the Discussions area, as it is more of a discussion than an issie

**Comment by leigh-pointer** [comment]
@sbwalker  just onto that :)
