### ISSUE TITLE
What's the roadmap for Oqtane?

### ISSUE THREAD

**Issue by abukres** [oqtane/oqtane.framework#41]
What's the roadmap for Oqtane? I would like to see what features are intended to be released in every quarter or even better every month.

Personally, I would like to see this framework evolve into one that supports modules/plugins/extensions and themes like DNN. Modules should be able to use third party UI controls without affecting the framework or other installed modules.

**Comment by ADefWebserver** [comment]
The items you mention are being discussed in the Oqtane forums: https://www.oqtane.org/Forums

**Comment by sbwalker** [comment]
The framework is already constructed in a modular manner so that it can accommodate third party modules and themes. The next step is to create an installer so they can be integrated easily.

**Comment by sbwalker** [comment]
I have added a Roadmap section to the project home page on Github
