### ISSUE TITLE
Custom theme not being picked up as the default.

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#410]
When you do a new site install and set a custom theme in appsettings, it doesn't get picked up. The ```installer.razor``` file just uses the defaults that are in the constants class. There is logic sitting in ```DatabaseManager.cs```, to read the config settings, but it is not called on the initial install.

Should logic be added to SiteRepository to read the Theme in app config? Or should that logic be placed somewhere else?

https://github.com/oqtane/oqtane.framework/blob/master/Oqtane.Client/UI/Installer.razor#L190-L192

**Comment by chlupac** [comment]
Settings in Install section are used during automatic (silent) installation without gui.

**Comment by sbwalker** [comment]
when installing through the install wizard it picks up the SiteTemplate from config so it would make sense that it could also pick up the DefaultTheme, DefaultLayout, DefaultContainer if they were specified.

**Comment by chlupac** [comment]
Solved by #416, #415 is obsolete.
