### ISSUE TITLE
[ENH] Theme arsha, and some feedback, updates

### ISSUE THREAD

**Issue by fasteddys** [oqtane/oqtane.framework#4115]
### Oqtane Info

Version - 5 - dev branch
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
Hello, this theme Arsha looks much more polished and beautiful 🏖️  thanks the default theme (which IMHO does not do justice to octane).

_____________
- [ ] Also is there a template css, to retorfit our previous or pre-existing themes, this would be nice.
- [ ] Would that theme zip go in the module?
- [ ] I saw your intro video on your site and replayed it a few times, but the module section was nice, however confused me, since you referring to inserting into a pane. Lets say I wanted to build scheduling app/calendar app, would the controllers and views go in the module, and then be uploaded?
- [ ] So, I was trying this theme, but its not showing in the market place, is there a zip file to upload.
- [ ] BTW - great job on in place updates 👏 , in that scenario what happens to our code customization's, is there a way to separate that from being over written.
_____________
- [ ] In the docs, a docker steps section would help as well.
- [ ] How can we upload users from excel?
- [ ] How to import fake data, do you have that as well in the market place?
- [ ] How can we list and publish modules
- [ ] can we build widgets for dashboards, check out tuxboard here .. https://rb.gy/vp3w0h
- [ ] how to build up social links/networking, lets says tags or related users?
- [ ] Memory wise for 30 to 50 concurrent users, how much hosting is recommended, maybe consider a discounted affiliate :) for your kickback and discounted hosting for oqtane lovers 😄 

Is this going to be free for developers to modify and host sites

**Comment by sbwalker** [comment]
@fasteddys I am going to move this item to the Discussions area as the "Issues" area should be devoted to specific bugs or enhancements for Oqtane
