### ISSUE TITLE
Issue with ReplaceTokens in CreateModule

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4121]
### Oqtane Info

Version - 5.1.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
I have a custom module template that is incorrectly parsed. The Token Replace fails on string that starts with [[. ie 

[Module] == MyNewIdea

string jsonSettings = ModuleState.Settings[[Module]Settings.SETTINGS_KEY];
gets parsed to 
string jsonSettings = ModuleState.SettingsMyNewIdeaSettings.SETTINGS_KEY];

### Expected Behavior
Correct parsing where [Module] == MyToDoList
string jsonSettings = ModuleState.Settings[[Module]Settings.SETTINGS_KEY];
to 
string jsonSettings = ModuleState.Settings[MyNewIdeaSettings.SETTINGS_KEY];

### Steps To Reproduce
Create a template with the same replacement string combination.

### Anything Else
The replacement worked fine before the TokeReplace enhancement.

**Comment by zyhfish** [comment]
Hi @sbwalker , seems the regex is not able to capture this format, let me check how to resolve it.

**Comment by zyhfish** [comment]
Hi @sbwalker , can we change the token identifier from "[]" to "[$$]" so that it can avoid most of this edge case, like change "[Module]" to "[$Module$]"?

**Comment by sbwalker** [comment]
@zyhfish what exactly is this TokenExpression supposed to represent:

        private const string TokenExpression = "(?:(?<text>\\[\\])|\\[(?:(?<source>[^{}\\]\\[:]+):(?<key>[^\\]\\[\\|]+)|(?<key>[^\\]\\[\\|]+))(?:\\|(?:(?<format>[^\\]\\[]+)\\|(?<empty>[^\\]\\\\[]+))|\\|(?:(?<format>[^\\|\\]\\[]+)))?\\])|(?<text>\\[[^\\]\\[]+\\])|(?<text>\\[{0,1}[^\\]\\[]+\\]{0,1})";

It appears there is a lot more context in this expression than just just simple [Token] elements.

**Comment by zyhfish** [comment]
Yes, the last text match part "(?<text>\\[{0,1}[^\\]\\[]+\\]{0,1})" will not work in this case.

**Comment by sbwalker** [comment]
@zyhfish my actual question is related to the functionality of the TokenReplace class. Is is simply intended to provide a clean abstraction for replace [Token]s with dynamic values - or it is trying to provide a lot more advanced functionality as well? I am asking to determine if perhaps the implementation in the theme/module templates was a mismatch - as the theme/module templates have very basic token replacement requirements.

**Comment by zyhfish** [comment]
Hi @sbwalker , Yes, I want to introduce this class is hope to handle more scenarios, such as:
- Email template
- Notifications
- dynamic display content based on current context

**Comment by sbwalker** [comment]
Can you please provide some more information about the token format supported ie. if it is intended to support more than just [Token] then please provide some examples

**Comment by zyhfish** [comment]
Hi @sbwalker , here is some examples of complex tokens:
1. formatted output: like [CreateTime|mm/dd/yyyy]
2. default value when empty: [UserName|Hello,{0}|Not Login]

anyway, the formatted content hasn't been implemented yet, it's marked as a TODO task.

**Comment by sbwalker** [comment]
@zyhfish in regards to "Yes, the last text match part "(?\[{0,1}[^\\]\[]+\]{0,1})" will not work in this case" - what is the purpose of this "last text match" - is it actually implemented in the TokenReplace class or was it included for future scenarios. If its not implemented, could it be removed so that at least the main use cases work properly?

**Comment by zyhfish** [comment]
Yes, this is needed to match the token, but it has an issue for the nested square brackets, it will ignore the duplicated one.

**Comment by sbwalker** [comment]
I am curious if you could simply replace “[[“ with “[[[“ before calling TokenReplace.

**Comment by zyhfish** [comment]
Hi @sbwalker , thx so much for the suggestion, replace "[[" with "[[[" won't work but I try to replace "[[" to "[$_[" to avoid the issue, please check whether it good to go.

**Comment by leigh-pointer** [comment]
Can confirm, my template parsed correctly.
