### ISSUE TITLE
[BUG] I CAN NOT INSTALL OQTANE  

### ISSUE THREAD

**Issue by jaruiz1961-ual** [oqtane/oqtane.framework#4138]
### Oqtane Info

Version - 5.1.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
I get an error: "No database provider has been configured for this DbContext...." when I try to install Oqtane from Visual Studio 2022 (localhost).

![image](https://github.com/oqtane/oqtane.framework/assets/102952323/ca6f0fe4-440c-42e7-aed8-a317f0dafd28)

**Comment by jaruiz1961-ual** [comment]
I know where  the problem is.  It is in the appsettings.json file, ConnectionStrings section because the commented line  !!!! 
"ConnectionStrings": {
  //  "DefaultConnection": "Server= ..... ;"
  "DefaultConnection": ""
  
    //Server=(localdb)\\MssqlLocaldb;Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Oqtane-4444.mdf;Initial Catalog=Oqtane-4444;Integrated Security=SSPI;Encrypt=false;"
},

**Comment by sbwalker** [comment]
I will close this issue as it appears you modified the appsettings.json file - you should leave the default connection string blank so that the install wizard is displayed.
