### ISSUE TITLE
RichTextEditor - the image is usually inserted at the start of the content

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#4158]
### Oqtane Info

Version - #.#.#
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
When editing content with the RichTextEditor module, if an image is inserted at the cursor position, the image is usually inserted at the start of the content (index=0). The cause of this phenomenon is that when you click the InsertImage button to open the FileManager module, the status of the modules changes, causing the cursor position in Quill's editing area to be reset to 0.

The solution is to get the cursor position before the FileManager module is opened and then pass it to the InsertImage method.

### Javascript
getCurrentCursor: function (quillElement, html) {
      var Delta = Quill.import('delta');
      editorIndex = 0;
      if (quillElement.__quill.getSelection() !== null) {
          editorIndex = quillElement.__quill.getSelection().index;
      }
      return editorIndex;
},
insertQuillImage: function (quillElement, imageURL, altText, editorIndex) {
    var Delta = Quill.import('delta');
    return quillElement.__quill.updateContents(
        new Delta()
            .retain(editorIndex)
            .insert({ image: imageURL },
                { alt: altText }));
}

**Comment by mdmontesinos** [comment]
I'm also facing this behaviour.
