### ISSUE TITLE
[BUG] Customizing RichTextEditor toolbar makes it reload previous content

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4160]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

I have validation that verifies that the RichText is not empty but when trying to save it with empty content, it writes back the previous content I deleted. Validation is working fine and the message displays, so the GetHtml call is actually returning an empty string, but somewhere in the code it's writing again the previous content in the RichTextEditor, even for another RichTextEditor that was not empty but still modified.

Here's the sample video:

[screen-capture (1).webm](https://github.com/oqtane/oqtane.framework/assets/90258222/bf9a8d46-7927-4b08-9521-0e6875b6f02f)

You can also see for a few frames after successfully saving that the previous content appears on the RichTextEditors although the modified content is correctly saved.

The issue occurs when you add a custom ToolbarContent to the RichTextEditor.

To replicate, simply replace the current RichTextEditor in the Html/Text module with:
```razor
<RichTextEditor Content="@_content" AllowFileManagement="@_allowfilemanagement" AllowRawHtml="@_allowrawhtml" @ref="@RichTextEditorHtml">
    <ToolbarContent>
        <select class="ql-header">
            <option selected=""></option>
            <option value="1"></option>
            <option value="2"></option>
            <option value="3"></option>
            <option value="4"></option>
            <option value="5"></option>
        </select>
        <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-italic"></button>
            <button class="ql-underline"></button>
            <button class="ql-strike"></button>
        </span>
        <span class="ql-formats">
            <select class="ql-color"></select>
            <select class="ql-background"></select>
        </span>
        <span class="ql-formats">
            <button class="ql-script" value="sub"></button>
            <button class="ql-script" value="super"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-header" value="1"></button>
            <button class="ql-header" value="2"></button>
            <button class="ql-blockquote"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
            <button class="ql-list" value="check"></button>
            <button class="ql-indent" value="-1"></button>
            <button class="ql-indent" value="+1"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-link"></button>
            <button class="ql-clean"></button>
        </span>
    </ToolbarContent>
</RichTextEditor>
```

It basically adds some new other format options for the Quill toolbar, but they shouldn't require any extra configuration.

In fact, it doesn't matter what options you set in the toolbar. Just by specifying a custom toolbar the issue will occur.

You should see this behaviour, in which it's clearly seen that the content is written again to the editor when saving. In this case it seems just like a UI issue, but if the execution is stopped due to any error/validation before navigating back, you would stay with the previous content, like in the previous video.

[screen-capture.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/af2ae2c0-efef-471a-80e0-52e24bd4d388)

### Expected Behavior

Customizing the toolbar shouldn't make the RichTextEditor revert back to the previous saved content when editing, nor display it after saving for a few frames.

### Steps To Reproduce

Customize the toolbar for the RichTextEditor in the Html/Text module.

**Comment by zyhfish** [comment]
This is because when a component has child components, the SetDirectParameters function will be called every time and will trigger the OnParameterSet event handler. one possible solution is overwrite ShouldRender method in RichTextEditor to always return false to prevent the re-render. @sbwalker , could you please check whether this is ok?

**Comment by sbwalker** [comment]
@zyhfish i can take a look on Monday

**Comment by sbwalker** [comment]
@zyhfish ShouldRender cannot be disabled as there is a use case where the parent component may change the content - in which case the richtexteditor needs to display the changed content.

**Comment by sbwalker** [comment]
@mdmontesinos please test with #4185

**Comment by mdmontesinos** [comment]
@sbwalker It seems to be working fine now. Thanks for the fix!
