### ISSUE TITLE
[BUG] - Sites does load when logged in have to press refresh page in production 

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4162]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
I am experiencing Stanger behaviour on the LearnOqtane.com production site where on first load the server servers up a blank page.

No errors are produced in the log or event log

### Expected Behavior
The site should load every time.

### Steps To Reproduce

Just surf to [LearnOqtane.com](https://LearnOqtane.com) and you will see you get a blank page 

I have just discovered that it doesn't load when you login have to press the refresh button for it to load ..... still no errors in the event log or error.log 

### Anything else?

**Comment by vnetonline** [comment]
https://github.com/oqtane/oqtane.framework/assets/15242923/3f4922ee-60d9-47d7-97dd-64fa9b1d2780

**Comment by sbwalker** [comment]
@vnetonline This is a known problem with the initial release of Blazor in .NET 8. You need to make sure you have the latest SDK / Hosting Bundle (8.0.4) installed in your environment.

**Comment by sbwalker** [comment]
@vnetonline was this resolved by upgrading to .NET SDK 8.0.4? Can I close this issue?

**Comment by vnetonline** [comment]
Yes, this is fixed because I got my Hosting provider [SmarterASP.Net](https://www.SmarterASP.NET/index?r=vnetonline) to upgrade to 8.0.4, and this issue got fixed
