### ISSUE TITLE
I have just noticed this error is back in 5.1.1

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4163]
I have just noticed this error is back in 5.1.1

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/07c3b7f2-1db9-4048-93ed-8199cc6ebe22)

_Originally posted by @vnetonline in https://github.com/oqtane/oqtane.framework/issues/4116#issuecomment-2068013552_

**Comment by vnetonline** [comment]
this has gone away in 5.1 when StreamRendering attribute

**Comment by sbwalker** [comment]
@vnetonline as per my comment on your other issue, please make sure you have .NET SDK 8.0.4 installed in your environment.

**Comment by vnetonline** [comment]
got my provider SmarterASP.NET to upgrade to SDK 8.0.4
