### ISSUE TITLE
[BUG] HTTP 404 Error on Admin Dashboard Access in Subfolder Installation

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#4165]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Client
Database - SQL Server

### Describe the bug

After performing a clean installation of Oqtane v5.1.1 on Windows IIS and creating a new site in a subfolder, accessing the Admin Dashboard results in an HTTP 404 error. The URL appears to be malformed, potentially missing a slash between the site subfolder and the admin route.

### Expected Behavior
Clicking on the [Admin Dashboard] should navigate to the dashboard page without any errors.

### Steps To Reproduce

1. Perform a clean install of Oqtane v5.1.1 using the release ZIP from [Oqtane.Framework v5.1.1 Release](https://github.com/oqtane/oqtane.framework/releases/download/v5.1.1/Oqtane.Framework.5.1.1.Install.zip).
1. Navigate to Site Management and create a new site (sc01) in a subfolder (https://oqtane-poc306.oqtane.me/sc01).
  ![image](https://github.com/oqtane/oqtane.framework/assets/2724850/64a86b3e-852f-4dc3-9746-6342ec749db5)
1. Click on [Save] to create the new site and navigate to it.
1. In new site https://oqtane-poc306.oqtane.me/sc01 attempt to access the [Admin Dashboard] by clicking on the corresponding link.
  ![image](https://github.com/oqtane/oqtane.framework/assets/2724850/562d10f6-16cf-4f2c-ad81-15ef607d8cf1)
1. A 404 error page is displayed instead of the Admin Dashboard.
  ![image](https://github.com/oqtane/oqtane.framework/assets/2724850/4b0a54bc-cbc1-4401-8fe5-fc00ce6e37a9)

### Anything else?

The browser displays an HTTP 404 error page. The URL seems incorrect, suggesting a possible missing slash:
```
https://oqtane-poc306.oqtane.me/sc01admin/*/40/Index?returnurl=%2Fsc01
```

The expected URL format might be something like:
```
https://oqtane-poc306.oqtane.me/sc01/admin/*/40/Index?returnurl=%2Fsc01
```

**Comment by sbwalker** [comment]
@tvatavuk thank you for reporting... I am able to reproduce :(
