### ISSUE TITLE
[BUG] Translation failure in Oqtane.Client\Modules\Admin\Profiles\Index.razor

### ISSUE THREAD

**Issue by marceloatoledo** [oqtane/oqtane.framework#4173]
Oqtane Info
Version - 5.1.1

Describe the bug
In the Oqtane.Client\Modules\Admin\Profiles\Index.razor file, the "Text" property is missing from the ActionLink:
This causes translation to other languages to fail

ActionLink Action="Edit" Parameters="@($"id=" + context.ProfileId.ToString())" Security="SecurityAccessLevel.Edit" ResourceKey="EditProfile" 

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/28f20009-d87c-4b81-aead-54638a0f9334)

Expected Behavior
For the Edit button to be translated

ActionLink Action="Edit" Text="Edit" Parameters="@($"id=" + context.ProfileId.ToString())" Security="SecurityAccessLevel.Edit" ResourceKey="EditProfile" 

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/41764f03-c68b-4676-ad1b-c8e19dcd9f94)

Steps To Reproduce
Install other languages and in the language bar switch to anything other than English

**Comment by sbwalker** [comment]
resolved by #4169
