### ISSUE TITLE
[BUG]   Translation failure in Oqtane.Client\Modules\Admin\Visitors\Index.razor

### ISSUE THREAD

**Issue by marceloatoledo** [oqtane/oqtane.framework#4174]
Oqtane Info
Version - 5.1.1

Describe the bug
In the Oqtane.Client\Modules\Admin\Visitors\Index.razor file, the "Text" property is missing from the ActionLink:
This causes translation to other languages to fail

ActionLink Action="Detail" Parameters="@($"id={context.VisitorId}")" ReturnUrl="@(NavigateUrl(PageState.Page.Path, $"type={_type}&days={_days}&page={_page}"))" ResourceKey="Details"

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/a27d7b56-8792-4762-9a66-54336eacde68)

Expected Behavior
For the Edit button to be translated

ActionLink Action="Detail" Text="Detail" Parameters="@($"id={context.VisitorId}")" ReturnUrl="@(NavigateUrl(PageState.Page.Path, $"type={_type}&days={_days}&page={_page}"))" ResourceKey="Details"

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/dbc68457-3d60-496b-8bc5-1d15bf355307)

Steps To Reproduce
Install other languages and in the language bar switch to anything other than English

**Comment by sbwalker** [comment]
resolved by #4169
