### ISSUE TITLE
[BUG] Translation failure in Oqtane.Client\Modules\Admin\Log\Index.razor

### ISSUE THREAD

**Issue by marceloatoledo** [oqtane/oqtane.framework#4175]
Oqtane Info
Version - 5.1.1

Describe the bug
In the Oqtane.Client\Modules\Admin\Log\Index.razor file, the "Text" property is missing from the ActionLink:
This causes translation to other languages to fail

ActionLink Action="Detail" Parameters="@($"/{context.LogId}")" ReturnUrl="@(NavigateUrl(PageState.Page.Path, AddUrlParameters(_level, _function, _rows, _page)))" ResourceKey="LogDetails"

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/fbccba51-fbe2-491f-b0bf-cdca710b469b)

Expected Behavior
For the Edit button to be translated

ActionLink Action="Detail"  Text="Detail" Parameters="@($"/{context.LogId}")" ReturnUrl="@(NavigateUrl(PageState.Page.Path, AddUrlParameters(_level, _function, _rows, _page)))" ResourceKey="LogDetails"

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/a4642e67-a91b-4f2a-aea5-03e31be356a3)

Steps To Reproduce
Install other languages and in the language bar switch to anything other than English

**Comment by sbwalker** [comment]
resolved by #4169
