### ISSUE TITLE
[ENH] - Add Prerender IModuleControl property (similar to RenderMode) to enable and disable prerender at component level 

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4178]
@sbwalker, I am having a rethink about this. I think this property would be beneficial for specific components. 

I have an Action (Add Course) that needs to be interactive to add courses. This ACtion is front facing the `OnInitializedAsync` and is triggered twice, causing flickering. If I was to disable prerender for this Action then it wouldn't flicker.

Can we add this property?

_Originally posted by @vnetonline in https://github.com/oqtane/oqtane.framework/discussions/4128#discussioncomment-9195637_

**Comment by sbwalker** [comment]
implemented in #4179
