### ISSUE TITLE
[BUG] Translation failure in Oqtane.Client\Modules\Admin\Themes\Index.razor

### ISSUE THREAD

**Issue by marceloatoledo** [oqtane/oqtane.framework#4180]
Oqtane Info
Version - 5.1.1

Describe the bug
In the Oqtane.Client\Modules\Admin\Themes\Index.razor file, the "Text" property is missing from the ActionLink:
This causes translation to other languages to fail

ActionLink Action="Edit" Parameters="@($"id=" + context.ThemeId.ToString())" ResourceKey="EditTheme" 

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/718bad2c-3d9c-4a17-84e1-15adf0659787)

Expected Behavior
For the Edit button to be translated

ActionLink Action="Edit" Text="Edit" Parameters="@($"id=" + context.ThemeId.ToString())" ResourceKey="EditTheme" 

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/489b55fc-8fed-4cda-90c0-f26a4b1343ab)

Steps To Reproduce
Install other languages and in the language bar switch to anything other than English

**Comment by sbwalker** [comment]
resolved by #4169
