### ISSUE TITLE
[BUG] Translation failure in Oqtane.Client\Modules\Admin\Jobs\Index.razor

### ISSUE THREAD

**Issue by marceloatoledo** [oqtane/oqtane.framework#4182]
Oqtane Info
Version - 5.1.1

Describe the bug
In the Oqtane.Client\Modules\Admin\Jobs\Index.razor file, the "Text" property is missing from the ActionLink:
This causes translation to other languages to fail

ActionLink Action="Edit"  Parameters="@($"id=" + context.JobId.ToString())" ResourceKey="EditJob" 
ActionLink Action="Log" Class="btn btn-secondary" Parameters="@($"id=" + context.JobId.ToString())" ResourceKey="JobLog" 

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/c8cf3802-6657-41bd-8283-d9536cf46aa9)

Expected Behavior
For the Edit button to be translated

ActionLink Action="Edit" Text="Edit" Parameters="@($"id=" + context.JobId.ToString())" ResourceKey="EditJob" 
ActionLink Action="Log" Text="Log" Class="btn btn-secondary" Parameters="@($"id=" + context.JobId.ToString())" ResourceKey="JobLog"

![image](https://github.com/oqtane/oqtane.framework/assets/7347896/61c8e2f9-0b48-4a06-a23f-fbadffe11553)

Steps To Reproduce
Install other languages and in the language bar switch to anything other than English

**Comment by sbwalker** [comment]
resolved by #4169
