### ISSUE TITLE
[BUG] HttpContext is null after calling NavigationManager.NavigateTo() in Interactive Blazor Server

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#4191]
### Oqtane Info

Version -5.1.1
Render Mode - Interactive
Interactivity - Server
Database - SQL Server

### Describe the bug

When in Interactive render mode using Server Interactivity and you invoke a feature which calls NavigationManager.NavigateTo(url, true) to perform a full page reload, an exception is thrown in the Oqtane.Server\Modules\HtmlText\Services\HtmlTextService.cs:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/5e050427-3a4d-4349-b4e6-7a5da371df05)

### Expected Behavior

- page will refresh without an exception

### Steps To Reproduce

- login and set Site Settings - UI Components - Render Mode to Interactive, Interactivity to Server (SignalR)
- go to Admin Dashboard, Language Management, add an additional Language
- browse to Home page
- choose the other language from the Language Selector at the top left
- an exception will be thrown 

### Anything else?

Initially the HttpContext is fine

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/b28670d1-173c-45bc-8074-6097e0aba0e7)

then the NavigationManager is called:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/1674ae70-6c6d-4679-98c4-62891b387d58)

which results in the exception when the page reloads

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/f3fc943e-043c-4c40-aa1c-7cea06565338)

Note that this appears to only be a problem in Interactive - Server. If you configure the site to use Interactive - Client (WebAssembly) it works fine because it utilizes HttpClient to call the API which calls the Service class on the server (and has HttpContext)

**Comment by zyhfish** [comment]
I'm not able to reproduce it with the same steps and the dev branch.

**Comment by sbwalker** [comment]
@zyhfish perhaps this is simply another manifestation of the NavigationManager.NavigateTo() issues in Visual Studio in .NET 8 which have already been documented here: https://github.com/dotnet/aspnetcore/issues/53996

**Comment by sbwalker** [comment]
@zyhfish #4195 resolved this issue - thank you!
