### ISSUE TITLE
[BUG] Translation failure in Oqtane.Client\Modules\Admin\Modules\Settings.razor

### ISSUE THREAD

**Issue by marceloatoledo** [oqtane/oqtane.framework#4209]
### Oqtane Info

Version - 5.1.1

### Describe the bug
In the Oqtane.Client\Modules\Admin\Modules\Settings.razor file:

the "Heading" property is missing from the TabPanel: This causes translation to other languages to fail

TabPanel Name="Permissions"  ResourceKey="Permissions"

Translation failure in ????:
TabPanel Name="ModuleSettings" Heading="@_moduleSettingsTitle" ResourceKey="ModuleSettings"
TabPanel Name="ContainerSettings" Heading="Container Settings" ResourceKey="ContainerSettings"

### Steps To Reproduce
Install other languages and in the language bar switch to anything other than English

**Comment by leigh-pointer** [comment]
The section
Translation failure in ????: moved to #4211
TabPanel Name="ModuleSettings" Heading="@_moduleSettingsTitle" ResourceKey="ModuleSettings"
TabPanel Name="ContainerSettings" Heading="Container Settings" ResourceKey="ContainerSettings"
