### ISSUE TITLE
[BUG] - The ShowProgressIndicator() is not showing loading sign any more

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4230]
### Oqtane Info

Version - Dev Branch (latest)
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

- When calling the `ShowProgressIndicator()` the loading sign doesn't appear any more 

### Expected Behavior

- The loading sign should come up 

### Steps To Reproduce

1. Create a button
2. Call a Method as follows 

    private async Task GenerateCode()
    {
        ShowProgressIndicator();
        Tawaitask.Delay(1000);
        HideProgressIndicator();
    }

3. You will see now that the Progress Bar doesn't appear

**Comment by sbwalker** [comment]
@vnetonline it is working fine within Interactive components... so I am guessing you are trying to use it in a Static component. Can you please provide a more functional example of what you are trying to do? In static components you cannot use buttons in the same way as in interactive components - so please explain how you are triggering the above method in your static component.

**Comment by vnetonline** [comment]
I have a module that has a `Save & Generate` button. My site and component is is running in Interactive mode Prerender at Server 

When I Hit the `Save & Generate` button I am trying to `ShowProgressIndicator()` but it doesn't display

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/0e0b0966-4a75-43f5-bf00-90db0383a744)

**Comment by sbwalker** [comment]
I just scaffolded a new module using the Create Module feature in Oqtane and I modified the Index.razor to include a button:

```
    <button type="button" class="btn btn-success" @onclick="Test">Test</button>
```

and added an event handler:

```
    private async Task Test()
    {
        ShowProgressIndicator();
        await Task.Delay(5000); // 5 seconds
        HideProgressIndicator();
    }
```

I added the module to a page and clicked the button:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/2e5a97be-524b-498e-9370-9f9d99f43253)

The indicator was displayed for 5 seconds

I have no idea why it is not working in your module... but I cannot reproduce the problem.

**Comment by vnetonline** [comment]
My Code had StateHasChanged it wasn't displaying the progress bar sorry for the trouble @sbwalker
