### ISSUE TITLE
Bug: Problem with DbUp when another resource types presents

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#424]
I tried today implement localization resources from Syncfusion. 
DbUp takes them and tries use them as upgrade script. which causes startup fail.
We should implement more exact resource script filters.

**Comment by sbwalker** [comment]
My latest PR I submitted today uses more restrictive filters for DBUp - did you try with latest code?

**Comment by chlupac** [comment]
It fails at module upgrade phase, its redesigned, works now correctly.
