### ISSUE TITLE
Missing Data when Oqtane installation is executed.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4248]
### Oqtane Info

Version - 5.1.1.
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
The CreatedBy, ModifiedBy  Fields are not poputlated.

### Expected Behavior
Field to be populated

### Steps To Reproduce
Install Oqtane.

**Comment by sbwalker** [comment]
@leigh-pointer when Oqtane is installed, the user is not logged in (as the User table does not even exist - it is created at the end of the installation process). The CreatedBy and ModifiedBy fields are populated based on HttpContext.User - which is null in this scenario.
