### ISSUE TITLE
extremely slow response on mobile

### ISSUE THREAD

**Issue by rrourk12** [oqtane/oqtane.framework#4267]
### Oqtane Info

Version - 5.1.1
Render Mode - Interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
Pages take 30-60 seconds to render on mobile (wifi or 5g) - likewise if the browser is throttled to fast 3g it is similar. Non throttled 500ms - throttled 48seconds

### Expected Behavior
I expect a slow down but not such a disparate response

### Steps To Reproduce
Use Edge/Chrome and use dev tools to throttle the site to fast or slow 3g, refresh the page.

**Comment by sbwalker** [comment]
@rrourk12 have you tried to browse to an actual Oqtane site (ie. https://www.oqtane.org) on a mobile device? It is definitely not taking 30-60 seconds to render content - the home page is displayed in 1-2 seconds. I also just tried using 3G throttling and no cache in my browser dev tools to load the site and it does not exhibit the performance you described. The performance testing metrics conducted with the Oqtane 5.1 release are included below:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/198ff67f-f442-4d4a-ba07-c9930f011401)
