### ISSUE TITLE
[BUG] Password Provided Does Not Meet The Complexity Policy

### ISSUE THREAD

**Issue by dvdobrovolskiy** [oqtane/oqtane.framework#4290]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
The Password Provided Does Not Meet The Complexity Policy. Passwords Must Be At Least 6 Characters In Length And Contain Uppercase, Lowercase, Numeric, And Punctuation Characters.
During install

Passwords tried
S6U£cx)fDCpOIgxS88>A>7^^NKXixaBHF9S36/a1w&}?nE<i=W
.rD89cQf2K0F4i.mx*A+)%M2VN-DwmGNjnMYrYd^Bi>yUq!x4gkR_*7_4?HLFHU^X#MXqFy4vzjsJ2#j0#N*^*Ar8HW)#x4%AYbk
p+~_}zq%3Y6x_
Pppp1,
K#0>r>^#:0wLgH>>G.tUu).}x)X,1=hjr2Az*A~~}H3RHn)u).p
![1](https://github.com/oqtane/oqtane.framework/assets/7299951/0186eb71-a839-416a-86f7-540344d8b7ee)

**Comment by zyhfish** [comment]
I'm not able to reproduce it neither with 5.1.1 nor 5.2.0 version, is there any specific settings on your environment?

**Comment by dvdobrovolskiy** [comment]
IIS + MS SQl. Last time I digged into problem I found this error triggered not by password itself by some other reason. sorry, delayed reserch and forgot. In 5.2.2 cannot reproduce error
