### ISSUE TITLE
[QUERY] - ? at the end of download file  

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4297]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the Question

![screencast-amazing-oqtane-download](https://github.com/oqtane/oqtane.framework/assets/15242923/e3284cfc-f3b6-419f-95ca-43c1c0034d5a)

I have the following code. When executing this code, the download file has a `?` at the end of the `file.url`.

```
    private async Task Download()
    {

        var zipFileName = _solution.Namespace.Replace("[Owner]", _solution.Owner).Replace("[Module]", _solution.Module) + ".zip";
        var moduleZipPath = Utilities.PathCombine(_solution.RootPath, zipFileName);
        var file = CodeGenService.CreateZipedModuleSolution(_solution.Location, moduleZipPath, zipFileName);
        NavigationManager.NavigateTo(FileUrl(PageState.User.FolderPath, zipFileName, false));
        await logger.LogInformation("File Downloaded Successfully From Url {Url}", file.Url);

    }
```

Download works, but why the `?`

**Comment by sbwalker** [comment]
@vnetonline I cannot see in the video what the Url generate is - the video is too small

**Comment by sbwalker** [comment]
closing as not enough information provided
