### ISSUE TITLE
Lack of documentation comments

### ISSUE THREAD

**Issue by abukres** [oqtane/oqtane.framework#43]
I noticed there's no documentation in the code. This was a big issue with DNN which had no documentation comments for many years before some users started adding them. Lack of proper documentation was a major pain for DNN. I hope this is not repeated again with Oqtane. Starting to add documentation comments early on before it becomes a daunting task will make it simpler and encourage developers to participate in advancing the framework. These comments help a lot also when using a documentation generator.

**Comment by sbwalker** [comment]
Absolutely! I totally agree that documentation is a key requirement as the project stabilizes and reaches a state where it is production-ready.
