### ISSUE TITLE
[BUG] - When clicking on Activate button in development mode

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4306]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

- I have released a commercial module called Amazing Subscriber 
- While testing the module in the local development environment using the `licensing=testmode` parameter
- There is no option to enter the license manual

### Expected Behavior

- There should be an ability to manually enter a license key and click Validate as the documentation says.

### Steps To Reproduce

- Include the licensing module in your project and try it

### Anything else?

- I have setup the product to test in the Sandbox

**Comment by sbwalker** [comment]
@vnetonline can you please move this issue to the repo: https://github.com/oqtane/Oqtane.LicensedModule
