### ISSUE TITLE
[BUG] page index will not be reset when perform a new search

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4318]
### Oqtane Info

Version - Latest
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
the page index will not reset when perform a new search after there is search results display and switched to other pages.

### Expected Behavior
the page index should be reset to the first page when perform a new search.

### Steps To Reproduce
1. add more than 10 pages with a same keyword in the name.
2. wait for the search index job to run.
3. search for the keyword, you will see more than one page in the pager list, click some page numbers to browse to the pages other than the first page.
4. change the search keyword to perform a new search.

**Comment by sbwalker** [comment]
fixed by #4336
