### ISSUE TITLE
Icons and Graphics

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#432]
I was wondering if there is a need to create any forms of icons or share ideas for ways to help promote the framework?

We can add community contributions possibly in this issue for now.  Create PR's for adding images accepted by the community as awesome enough to include.

**oqtane pump**
![oqtane_pump](https://user-images.githubusercontent.com/13577556/80923264-70003180-8d37-11ea-89ec-02dbcbdd382e.png)

**oqtane car**
![oqtane_car](https://user-images.githubusercontent.com/13577556/80923361-177d6400-8d38-11ea-81ef-deff7fd4f7e0.png)

**oqtane station**
![oqtane_station_car_fueling](https://user-images.githubusercontent.com/13577556/80924472-f586e000-8d3d-11ea-8ad8-3aed61c796d8.png)

Everyone is welcome to go ahead make adjustments to your own versions to help inspire other ideas. 

I can also spend some more time to make the car or gas pump in different ways obviously if a more sporty look for example is desired.

For example:
The nozzle on the gas pump I had moved higher for the station image.  It makes it look like the gas nozzle is in the front of the pump station.   If lower it looks like it is on the nozzle is on the side of the station pump house.

Modern pumps the nozzles are generally on the front so I liked the adjustment made after looking at it and left it as is.

I spent more time on the pump than I did on the car... it can go all over the place so it is something simple to start as a concept.

The station I added the .NET Foundation as the fuel station brand name sign in the background along with an open-source neon sign which could possibly be a full worded OPEN-SOURCE neon sign similar to an OPEN sign for storefronts.

Another idea is to put an oqtane sign up using the logo instead of the .NET Foundation sign.

A 1200 x 1200 image should be created that is attractive for when someone shares a link this image shows up in the post square or cropped (Top and bottom removed generally) looking good.  When www.oqtane.org is shared on social media platforms it will help grab a little extra attention.  

It was fun to produce a few ideas for concept here.

 Thank you.

**Comment by thabaum** [comment]
Heres is the oqtane pump with "self-serve" using all lowercase similar to CSS classes naming convention...

![oqtane_pump](https://user-images.githubusercontent.com/13577556/80926491-82d13100-8d4c-11ea-8531-4054933ca870.png)

**Comment by sbwalker** [comment]
I do not think we should distribute marketing images with the Oqtane framework distribution - but if they were available somewhere else and linked to the awesome-oqtane repo it would be great for the community.

**Comment by sbwalker** [comment]
It also looks like some high resolution versions of the logo are needed ;)
