### ISSUE TITLE
Internal Module Creator Error

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#434]
Issue:
After creating a module that is "internal" the new module added to the page throws an error.
![image](https://user-images.githubusercontent.com/13577556/81000784-9daeae80-8dfb-11ea-97cf-d81fdbfe7ee3.png)

![image](https://user-images.githubusercontent.com/13577556/81000287-eade5080-8dfa-11ea-80a7-8ed2c270ad62.png)

Linkss.Services.LinksService.GetLinkssAsync(int32 ModuleId) 
in
Links\Services\LinksService.cs line 32  
at
Links\Index.razor 73

I noticed it says Links**s** with an extra 's' after Links, is that correct?

**Comment by jimspillane** [comment]
Yes, that could be correct if the Module Name was _Links_ when it was created.

![image](https://user-images.githubusercontent.com/15007083/81001237-6ea53680-8e15-11ea-8f18-a9c8fb024049.png)

**Comment by thabaum** [comment]
@jimspillane Got me there thanks!  Glad this is just a test run I can take this back to the dealer when I am done driving it around :)

**Comment by jimspillane** [comment]
Take it back? I have a lot full of them!

I believe the error is being thrown because the module is on a page that does not require a registered user. The Linkss controller has an Authorize attribute with a role that is not anonymous.

**Comment by sbwalker** [comment]
An error is thrown because the Module Creator currently does not add the Embedded Resources to the Oqtane.Server project file for Internal modules. This is on the list of things to be completed for 1.0.

**Comment by sbwalker** [comment]
The short term workaround for Internal modules is to manually mark the generated script files as EmbeddedResources after you create the module - or open the script files and manually execute them against the database ( either using the SQL admin module in Oqtane or SQL Server )

**Comment by thabaum** [comment]
Will it do this for external modules?  And if I delete this module should I be able to run the Client debug?  As since this issue occured I can only run server debug to get Oqtane to fire up.

**Comment by sbwalker** [comment]
External modules have their own independent project files, and yes they include the embedded resources. I do not understand your other question... the Oqtane.Server project must ALWAYS be defined as the startup project.  Why do you want to set the Oqtane.Client project as the startup project?

**Comment by sbwalker** [comment]
this is resolved in #488
