### ISSUE TITLE
Module Creator Not Working

### ISSUE THREAD

**Issue by mikesmeltzer** [oqtane/oqtane.framework#4340]
### Oqtane Info

Version - 5.1.2   (Clean install)

### Describe the bug

When using the module creator you get an error that a template needs to be selected but the dropdown is empty.

![image](https://github.com/oqtane/oqtane.framework/assets/39993943/53defc88-57d7-425a-b04a-a376a093af10)

**Comment by leigh-pointer** [comment]
@mikesmeltzer just checked the release, looks like the module and theme templates where not included!

**Comment by mikesmeltzer** [comment]
@leigh-pointer Is there a way for me to get them and manually place somewhere?

**Comment by leigh-pointer** [comment]
@mikesmeltzer you could extract from the here github. They will be in the Server Project 
Oqtane.Server\wwwroot\Modules\Templates
Oqtane.Server\wwwroot\Themes\Templates

Or you could download the CodeBehind templates in the Marketplace.  look for this icon 
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/32f3614f-6073-46dd-9cb0-e7fe8d03039d)

**Comment by sbwalker** [comment]
The templates were removed from the Install and Upgrade packages starting in version 4.0.2 (Aug 2023) based on issue #3069
