### ISSUE TITLE
Module developement : best practice

### ISSUE THREAD

**Issue by maxmontgmx** [oqtane/oqtane.framework#4357]
Hi all,

I'm discovering this fantastic framework.
I'm using Oqtane dev branch (4.2.0). 
I created a module (wizard) with current version.
The module is working perfectly on me dev machine.
When I deploy the module to the official server under 4.1.2, I upload de package and after I restart server but it ignores the package.
I think it's normal because in the nuspec file, there is the dependency Oqtane.Framework 5.2.0
So I try to rebuild the package with dependency 5.1.2.
But after reboot, the server crashs. I guess that it's normal because the dependency dll doesn't exist.

So my question is how developing module with current Oqtane dev branch and deploy on a server with the previous official version?

Thanks in advance for your help

**Comment by sbwalker** [comment]
@maxmontgmx you should develop using the Master branch if your goal is to deploy your module into an environment running the last official release.

**Comment by maxmontgmx** [comment]
thank you @sbwalker for your great support. it's working perfectly.
