### ISSUE TITLE
Unable to run your project. The "RunCommand" property is not defined.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#436]
Issue:
Error running project using F5 after changing and saving one file (Admin\Logs\Detail.razor)

Error:  Unable to run your project. The "RunCommand" property is not defined.
![image](https://user-images.githubusercontent.com/13577556/81008384-b2913f00-8e07-11ea-8c57-fe4639367638.png)

Notes:

I still had the browser running when I hit the save button, then build, then F5 to receive this error.  After restarting Visual Studio I still get this error trying to launch this project.  This project does contain the "Linkss"  module I recently created using the Internal template for the Module Creator on this instance.  Oqtane ran after I installed the new module.  After I saved a file in the source framework I then received this issue.

**Comment by thabaum** [comment]
Figured out that if I debug in "Oqtane.Server" it would run, however if I run it "Oqtane.Client" it threw this exception.

It was working Oqtane.Client prior to saving Detail.razor.  Am I missing something here?

**Comment by chlupac** [comment]
You have always to run Oqtane.Server. This is startup.
