### ISSUE TITLE
[BUG]Admin Dashboard include deleted pages

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4375]
### Oqtane Info

Version - 5.1.2
Render Mode - Interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
The Admin Dashboard include deleted pages.

![image](https://github.com/oqtane/oqtane.framework/assets/76835718/b980d154-0e9c-41d0-b4bc-e90cfe06b3a3)

![image](https://github.com/oqtane/oqtane.framework/assets/76835718/cfdbb1dc-afa8-4eb7-94ef-31754cbb3771)

**Comment by sbwalker** [comment]
this was not a problem in the 5.1.2 release - it was only a problem in the Dev branch (5.2.0) based on the recent scalability enhancements
