### ISSUE TITLE
[BUG] Bash files missing from generated Themes/Modules

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4392]
### Oqtane Info

Version - 5.1.2

### Describe the bug

I'm working on documenting what the build process does, and while trying to explain it, I stumbled over this in the `...Package.csproj`

```xml
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition="'$(OS)' == 'Windows_NT' And '$(Configuration)' == 'Debug'" Command="debug.cmd" />
    <Exec Condition="'$(OS)' != 'Windows_NT' And '$(Configuration)' == 'Debug'" Command="bash $(ProjectDir)debug.sh" />
    <Exec Condition="'$(OS)' == 'Windows_NT' And '$(Configuration)' == 'Release'" Command="release.cmd" />
    <Exec Condition="'$(OS)' != 'Windows_NT' And '$(Configuration)' == 'Release'" Command="bash $(ProjectDir)release.sh" />
  </Target>
```

Obviously it should run the `debug.sh` and `release.sh` files on non-Windows systems, but these files don't appear to be created in new themes or modules.

### Expected Behavior

I don't use Linux or Mac, but I assume that these files should also be added to the auto-generated modules/themes.

**Comment by leigh-pointer** [comment]
@iJungleboy 
Those files are in the source code download. Templates are no longer deployed in the install or upgrade packages.

**Comment by iJungleboy** [comment]
Ok. 

Note that I just re-verified and actually the files are there. 

I was using the Arsha theme to explain the build process, and there the files are missing. But in Oqtane generating a new module actually has them, so my bad, I'll close.
