### ISSUE TITLE
[BUG] Cannot delete page Icon

### ISSUE THREAD

**Issue by dvdobrovolskiy** [oqtane/oqtane.framework#4398]
### Oqtane Info

Version - 5.1.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

You can change page icon to any (oi oi-align-right for ex) but if you left this field blank - icon will remain. 
New pages are created with blank icons no probs

**Comment by sbwalker** [comment]
@dvdobrovolskiy so you are saying that this issue is specific to the Edit Page functionality - and is related to specifying no Icon when an Icon had been specified previously?

**Comment by dvdobrovolskiy** [comment]
yes, If Icon was specified previously I cannot delete it. Mean if I make Icon field blank - Icon will remain. And if next time you edit page - icon field keeps previous icon name
