### ISSUE TITLE
[BUG] Page Management - Modules Tab

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4499]
### Oqtane Info

Version - 5.2.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
When in the page management and the modules tab is selected there should be a list of module that are residing on that page.  What is being displayed as a module is the "Page Management" module.
![image](https://github.com/user-attachments/assets/a6beec2e-53d2-46b7-bc17-df4bc57f8cfc)

### Expected Behavior
The framework should display a list of the current modules on the page

### Steps To Reproduce
Log in host, navigate to Page Management, select modules tab

**Comment by lanthonyneville** [comment]
Also seeing this in 5.2.0 - the modules list shows "Page Management" as the only module, for every page
