### ISSUE TITLE
[ENH] Linux hosting and sizing

### ISSUE THREAD

**Issue by ridingmower** [oqtane/oqtane.framework#4511]
I like the self install experience in oqtane

### Oqtane Info

Version - 5.2.0
Render Mode - Static 
Interactivity - Server
Database - postgress/mongoDB

### Linux / digital ocean or other linux / cpanel hosting

Since Linux hosting is much cheaper with droplets like digital ocean & linode, hostinger VM, please consider allowing us to add and host there.

- [ ] Sizing, please let us know how to calculate memory needed for hosting on linux, for e.g 35 or 100 simultaneous visitor/members
- [ ] How to do host in Linux hosting, some sample configuration and steps/script dependencies

**Comment by thabaum** [comment]
@ridingmower "There is a separate [Documentation repository](https://github.com/oqtane/oqtane.docs) which contains a variety of types of documentation for Oqtane, including API documentation that is auto generated using Docfx. The contents of the repository is published to Githib Pages and is available at https://docs.oqtane.org/"

This is from the readme which points you towards our community contributed documentation.  There you will find a lot of helpful information on setting up Oqtane in both Windows and Linux environments with links to resources that will help you along the way.

For Linux there was a thread that also may give you clues if this does not meet your needs.  I also recommend anyone working in different environments to suggest, provide solutions for improving our docs to help with issues like this.  If some create issues relating to anything I can assist and provides the steps/info needed to cut out any confusion I am all in on helping and supporting this for our docs project.  We can also use extra hands here as there is so much still to document and it is a 100% community contributed only project.

I hope the docs I submitted myself relating to your issue may help assist.  Here is the direct link to this part of the docs:

https://docs.oqtane.org/manuals/admin/installation/index.html

and here is the link to the relating discussion that may assist:

https://github.com/oqtane/oqtane.framework/discussions/3695

I was able to assist with a general setup of an Ubuntu Linux environment on Alibaba networks... so maybe help with yours as well if needed as I am unfamiliar with them but they all generally work the same just different UI/UX.  I know a few other community members are diving into this so starting a discussion relating can help others down the road.  And again anything worth documenting please mention and someone will get it included if not you can add it as a contributor and it would be awesome and  welcomed.

>  Sizing, please let us know how to calculate memory needed for hosting on linux, for e.g 35 or 100 simultaneous visitor/members

Maybe someone has this answer?  Would this get included in the docs section or would there be a system calculator component needed to be developed to stress test an environment?  IIS/APache/WIndows/Linux memory size per user load.  I think we had or have something in the works for this if I recall.  This part I am not 100% on what enhancement would get you what is desired here in this proposal.  If you can give more details on how this information should be provided to us?  Again until someone shares this information with us or we automate the load somehow to stress test the different environments I am not sure we can constantly update this as .NET improves over time it's speed and ability to take on more loads (hopefully).

Cheers!

**Comment by sbwalker** [comment]
closing as this is not an "issue" - it would be better suited for discussions
