### ISSUE TITLE
[BUG] Index error in Migration("Tenant.05.02.01.01")

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4517]
### Oqtane Info

Version - #.#.#
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
In the startup I get an error in the [Migration("Tenant.05.02.01.01")] on the stmt 
` visitorEntityBuilder.AddIndex("IX_Visitor", new string[] { "SiteId", "IPAddress" }, true);`

The message I get is:
![image](https://github.com/user-attachments/assets/a0998232-65f7-4b3e-b5ce-c11a058142ff)

I have several  Visitors-records that have the same SiteId and IpAddress in my db.
![image](https://github.com/user-attachments/assets/93ecac1d-def8-44c3-8d18-4f93afd86190)
![image](https://github.com/user-attachments/assets/c2e4fd5f-9d0d-4a2a-b749-546e8e7f137d)

The problem with this Error is that it don't run my migration and update my db.
I deleted all the Visitors and then it works fine.

**Comment by sbwalker** [comment]
@beolafsen thank you for reporting this issue. It appears that it was possible for duplicate records to be created as there was not a unique index to prevent it from happening in the past - which makes it impossible to introduce the unique index at this stage without remediating the data (and simply deleting the records is not an option as you would lose valuable history). I will review this further.

**Comment by sbwalker** [comment]
@beolafsen I removed the code to add the unique index on  upgrade. After reviewing the logic, there is an option for "Correlate Visitors?" and if it is disabled then multiple users with the same IP address can be added to the Visitor table.
