### ISSUE TITLE
[BUG] site level scripts rendering in head tag breaks MudBlazor based themes

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.framework#4525]
### Oqtane Info

Version - 5.2.0 - 5.1.1
Render Mode - Interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
Site level scrips are rendered in the Head tag and should be rendered in the body with the other scripts.  Mudblazor interactions will not happen when the script is loaded in the head.  We used to be able to work around this by using the site settings page content body content and pasting a script reference in there.  this work-around broke in version 5.1.1 and now body content is rendered after the   

### Expected Behavior
Mudblazor controls will be interactive when site level scripts are defined and MudBlazor controls are on present in the theme.

### Steps To Reproduce
1. create a new theme using the studio-elf/mudblazor module
2. add a mudblazor control to your theme
3. notice that it's not interactive.

### Anything else?
this is the commit where the page content body content was moved to after the _framework scripts moved (in my fork) : https://github.com/OpenEugene/oqtane.framework/commit/0ba94f3bc976911b2cc3ee2f0c2459c8dcc3cc64

Proper script placement:
![image](https://github.com/user-attachments/assets/9217248e-e199-4104-bf42-b92bcf9c9fe1)

**Comment by sbwalker** [comment]
@markdav-is when you define Resources for a module you can already specify if a Resource is expected to be injected in the Head or Body using the Location property:

```
new Resource { ResourceType = ResourceType.Script, Url = "~/Module.js", Location = ResourceLocation.Body, Level = ResourceLevel.Site }
```
