### ISSUE TITLE
[ENH] create new theme scoped resource level

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.framework#4526]
### Oqtane Info

Version - 5.2.0
Render Mode - Interactive 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
To properly support 3rd party libraries like MudBlazor for developing themes, it's important to register the JS libs in the body tag and keep them present for any pages that use that theme.

proper library placement example

![image](https://github.com/user-attachments/assets/d43beaaa-7ecc-4287-940d-6988febd7c9d)
 
### Anything else?
The Site level is currently placing SIte level JS references in the head tag so changing that might be problematic

Maybe consider a new ResourceLocation enum  and extend Resource class to have a Location member with options for Head, BodyBeforeScripts, BodyAfterScripts  

I'm willing to do this work, it's currently blocking some projects, but I'd like to get a solid approach from the core team first.

**Comment by markdav-is** [comment]
this change allows for the old work-around to keep working.  I don't know if that's a "works for mudblazor but breaks X" sort of fix.  I'm assuming there was a reason to move those injection points. 
![image](https://github.com/user-attachments/assets/dc219f67-ab58-4b56-b218-0a1fecdd16c2)

**Comment by sbwalker** [comment]
@markdav-is when you define Resources for a module you can already specify if a Resource is expected to be injected in the Head or Body using the Location property:

```
new Resource { ResourceType = ResourceType.Script, Url = "~/Module.js", Location = ResourceLocation.Body, Level = ResourceLevel.Site }
```

**Comment by markdav-is** [comment]
awesome thanks!  But the bug question is:  does it put it before or after the _framework scripts.  I'll test it!
