### ISSUE TITLE
[BUG] NavigationException when trying SEARCH after new installation

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4533]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
I cloned the latest version of Oqtane and built up a new database. After that was done, I logged in and entered a search term in the Search field. Got this error:

![image](https://github.com/user-attachments/assets/b6faad55-6c71-4061-927c-3516cecc45ef)

![image](https://github.com/user-attachments/assets/c994d6fe-5dd1-45aa-96d3-757a482a3e89)

![image](https://github.com/user-attachments/assets/a0383c38-56ce-41c3-96fc-a0a0e8113361)

Then I tried to key in a new search word in the "http://localhost:44357/search?page=1&q=" page and then I got this error:

![image](https://github.com/user-attachments/assets/5bcad6a8-156f-4701-8cee-59b7b463fde5)

![image](https://github.com/user-attachments/assets/5b28290c-408b-4bec-8370-4c51ee36e269)

**Comment by leigh-pointer** [comment]
The first issue is an .net core issue i believe, and if you select "except in Oqtane.client.dll" the exception passes through.

**Comment by beolafsen** [comment]
OK - Thanks.

Med vennlig hilsen
Bjørn-Even Olafsen


tir. 20. aug. 2024 kl. 14:02 skrev Shaun Walker ***@***.***>:
