### ISSUE TITLE
[BUG] Site Settings / UI Component Settings sometimes shows old value after save

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4545]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
After changing the UI Component Serttings in Admin Dashboard / Site Settings and press the Save button the values are updated on disk - but not always on screen.
I guess it has to do with the cache.
See video.

### Anything else?
[UIComponentVideo.zip](https://github.com/user-attachments/files/16707069/UIComponentVideo.zip)

**Comment by sbwalker** [comment]
Yes, I am able to reproduce this. In production you should not be changing your UI Component Settings often so this issue is more of an annoyance during testing/development.
