### ISSUE TITLE
[BUG] Error in logging because Category field is to small

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4559]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
If I get an error in the Controller (and maybe other places?) - the error are not logged because the Category field is to small.

The Category field has a limitation on 200 byte, but my **AssemblyQualifiedName** is bigger than that.

`
           Type type = @class.GetType();
           if (type != null && type != typeof(string))
           {
               **_log.Category = type.AssemblyQualifiedName;_**
               log.Feature = Utilities.GetTypeNameLastSegment(log.Category, 0);
           }
           else
           {
               log.Category = @class.ToString();
               log.Feature = log.Category;
           }
  
`

![image](https://github.com/user-attachments/assets/2d24dbcc-886f-40d0-8c4e-474adda510c6)

Is it possible to have the Category field set to MAX length?

**Comment by beolafsen** [comment]
The value in AssemblyQualifiedName;:

![image](https://github.com/user-attachments/assets/74274eaa-b7a5-4fed-84a2-0392033dfa09)

**Comment by sbwalker** [comment]
That is a really large AssemblyQualifiedName - it basically contains 2 AssemblyQualifiedNames merged together. I am guessing this is because you are using generics and .NET creates some strange names in these scenarios. You are the first person to ever encounter this limitation - this logging code has been the same for 4-5 years - so congratulations ;)

**Comment by beolafsen** [comment]
You are right - I use generic routines. 

The problem is that we do not know if an error has occurred - because it is not logged. We then lose two loggings. The one that should be logged and the one that happens in the log routine. I have previously looked in the log for errors that I expected to be there, but not found. Have not investigated it further before now.

**Comment by beolafsen** [comment]
This is possibly a good enough solution to this problem.

Med vennlig hilsen
Bjørn-Even Olafsen


man. 26. aug. 2024 kl. 18:08 skrev Shaun Walker ***@***.***>:
