### ISSUE TITLE
[ENH] Possibility to add Time field in Migration

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4575]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
To be able to use the Syncfusion Timepicker in a GridColumn I need to define the field as Time.
Is it possible that you also add this datatype Time to the Migration.

**Comment by sbwalker** [comment]
Are you referring to the old TimeSpan or the new TimeOnly data type:

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sql-server-date-and-time-now-scaffold-to-net-dateonly-and-timeonly

**Comment by beolafsen** [comment]
TimeOnly.

Med vennlig hilsen
Bjørn-Even Olafsen


tor. 29. aug. 2024 kl. 03:48 skrev Shaun Walker ***@***.***>:
