### ISSUE TITLE
[BUG] https://oqtane.net/ is down

### ISSUE THREAD

**Issue by ijaz-saeed** [oqtane/oqtane.framework#4585]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
![image](https://github.com/user-attachments/assets/00bb9bf2-069b-4c64-a327-8d3230b90c2a)

**Comment by ijaz-saeed** [comment]
@sbwalker

**Comment by sbwalker** [comment]
Already reported here: https://github.com/oqtane/oqtane.framework/discussions/4584

I am still waiting for Microsoft to fix my Azure subscription :(
