### ISSUE TITLE
[ENH] Update default to a modern theme

### ISSUE THREAD

**Issue by ridingmower** [oqtane/oqtane.framework#4595]
### Oqtane Info

Version - 5.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
Can you please update the default theme, looks unprofessional
Also, add sample comments, so we can follow that a learning or starting point to create our own theme

In the documentation, orchard and others lack visual diagrams of the components or various items, dependencies, optional vs required, and the sequence of flow to understand the development, hopefully in Oqtane, diagrams will be included to help guide the developer.

**Comment by sbwalker** [comment]
The default Oqtane theme is already using the most modern version of Bootstrap. It is not intended to be used as a theme on a production website - it is intended for developers to use in their local environments when developing modules (this is why it has minimal UI elements). If you are looking for a theme to create a website you should explore the open source example: https://github.com/oqtane/Oqtane.Theme.Arsha.
