### ISSUE TITLE
Adding additional services from external modules does not work when running Blazor-WASM

### ISSUE THREAD

**Issue by lizard-prime** [oqtane/oqtane.framework#460]
## Description
Currently there is no way to add additional (scoped, transient, singleton) services through external modules when the WebAssembly runtime is selected. This works during server-side runtime when the IService interface is added to the implemented class, but does not when running WebAssembly. 

## To reproduce
- create a fresh external module through the ModuleCreator
- add a new I[ServiceName] service interface and its implementation [ServiceName]
- add the I[ServiceName] and the oqtane IService interfaces to the implementing class
- use dependency injection on Index.razor to inject the new service
```razor
@inject [IServiceName] [ServicePropertyName]
```
- build the external module
- build and run oqtane

## Expected behaviour
The created service should be registered and available for injection.

## Actual behaviour
- When running server-side Blazor the module behaves as expected and injection is possible without errors.
- When running client-side (wasm) Blazor the service can not be injected into the module because there is no value registered for injection.

## Diagnosis
The described behaviour seems to be the case because the download of the additional assembly DLLs happens to late to register them during startup. This causes an unhandled invalid operation exception because there is no value available for injection.

**Comment by mikecasas** [comment]
Check out @sbwalker post at:
https://www.oqtane.org/Resources/Blog/PostId/523/assembly-loading-in-blazor-and-net-core

Also check out the discussion around:
https://gitter.im/oqtane/community?at=5ea072ad727e88014a0cf4ea

**Comment by sbwalker** [comment]
Correct. It is not technically possible to use dependency injection for services when running on WebAssembly. I have spoken to Microsoft about this and they are aware of the limitation. I was told that they are working on a solution in .NET 5 which will allow assemblies to be downloaded during startup ( currently this is not possible ).

**Comment by sbwalker** [comment]
You will notice that as a result of this limitation Oqtane modules do not use dependency injection for their services - they instantiate the service manually and call the methods:

            DogService = new DogService(http, sitestate, NavigationManager);
            _Dogs = await DogService.GetDogsAsync(ModuleState.ModuleId);

**Comment by chlupac** [comment]
@sbwalker Say again not possible :)
solved in #463

**Comment by chlupac** [comment]
```c#
    public class ClientStartup : IClientStartup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IaaaaService, aaaaService>();
        }
    }
```
should be added to client assembly for service registration

**Comment by sbwalker** [comment]
I was mistaken as Microsoft has now added the ability to make async HttpClient calls from startup. This has now been implemented in the framework. You can either use the IClientStartup method mentioned above or simply decorate your service class with the IService interface stub for auto DI registration ( see the HtmlTexr module service class for an example )

**Comment by sbwalker** [comment]
closing as this is now complete
