### ISSUE TITLE
[INFO] Is it possible to setup GitHub action or not for a module

### ISSUE THREAD

**Issue by kolliLakshmaiah1219** [oqtane/oqtane.framework#4603]
we are developing a module , Is it possible to set up a GitHub action or not

**Comment by sbwalker** [comment]
@kolliLakshmaiah1219 please ask general questions such as this in the Discussions area - the Issues area is reserved for actual issues or enhancement requests to the framework

**Comment by kolliLakshmaiah1219** [comment]
ok
