### ISSUE TITLE
[ENH] Add Site name if not a logo exsist 

### ISSUE THREAD

**Issue by JanOlsmar** [oqtane/oqtane.framework#4604]
### Oqtane Info

Version - 5.2.1
Render Mode - All 
Interactivity - All
Database - All

### Describe the enhancement
If you don't need a logo, it can be good to show the Site name instead.
Change the Logo.razor theme control as follow

`@if (PageState.Site.LogoFileId != null)
{
    <span class="app-logo">
        <a href="@PageState.Alias.Path">
            <img class="img-fluid" src="@Utilities.FileUrl(PageState.Alias, PageState.Site.LogoFileId.Value)" alt="@PageState.Site.Name" />       
        </a>
    </span>
}
else
{
    <span class="app-logo">
        <a class="navbar-brand" href="@PageState.Alias.Path">
            @PageState.Site.Name
        </a>
    </span>
} `

### Anything else?
Add css for the two standard Themes.
.app-logo .navbar-brand {
    padding: 0 5px 0 25px;
    font-size: x-large;
    color:white;
}

**Comment by sbwalker** [comment]
I added this enhancement however I included a ShowName parameter with a default of False so that the change does not impact any existing sites (ie. sites which are relying on the behavior of the Logo component rendering nothing if a logo has not been specified in Site Settings).

**Comment by JanOlsmar** [comment]
The changes you did regarding css will not be good. navbar-brand should be used not site-name. Also should my sugested css addtions be added to respective default themes not to app.css. Your changes will not work well with Botstrap colors and  dark /light.

**Comment by sbwalker** [comment]
@JanOlsmar your feedback is valid. #4613 includes navbar-brand and changes the name of the component parameter to make its purpose more clear. The padding style was added to app.css so that themes do not always need to explicitly override this style - they should only override it it is necessary in a specific theme.
