### ISSUE TITLE
[BUG] Site HeadContent scripts are added twice 

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4607]
### Oqtane Info

Version - 5.2.2 (latest dev branch)
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

Scripts that are added manually to the HeadContent in the Site settings are included twice in the html output.

![image](https://github.com/user-attachments/assets/f35a1fae-a620-4881-83c1-33f6ed9b5d17)

As you can see in the image, they are added first as expected with the comments they included. However, they are then included again and parsed without the comment.

### Expected Behavior

They should only be added once.

### Steps To Reproduce

Add any script to the Site HeadContent via the admin page and check the HTML ouput.

### Anything else?

I believe this occurs because the HeadContent is set twice, in the App.razor and the ThemeBuilder.razor. See both snippets:

App.razor Line 195
```c#
_headResources += ParseScripts(site.HeadContent);
```

ThemeBuilder.razor Lines 47-51
```c#
AddHeadContent(headcontent, PageState.Site.HeadContent);
if (!string.IsNullOrEmpty(PageState.Site.HeadContent))
{
    headcontent = AddHeadContent(headcontent, PageState.Site.HeadContent);
}
```
Also the first call to AddHeadContent here seems useless.

It seems the one on the ThemeBuilder adds all the head content without parsing it in Static mode, so it includes the comments (as it should). The one in App parses only the scripts and removes any extra elements.

**Comment by sbwalker** [comment]
This is a regression issue related to #4435. Oqtane supports both fully Interactive (SPA) and Static (Web) render modes - and the JavaScript integration requires totally different approaches for each - which is why the logic above may not appear to make sense (however if you ran Oqtane in Interactive mode you would see why it is necessary). I will have to review #4435 again.

**Comment by hishamco** [comment]
I just noticed this bug in the code and planned to fix it

**Comment by sbwalker** [comment]
@hishamco since I have all of the historical context of how scripts are handled in Blazor for the various run-time scenarios it might be better if I tackled this one.

**Comment by hishamco** [comment]
Not all the cases can be discoverable by humans :)

**Comment by mdmontesinos** [comment]
@sbwalker I just updated to the latest dev branch that contains the fix but, unfortunately, it's not working. Scripts are still added twice with the same behaviour I mentioned previously.

**Comment by sbwalker** [comment]
@mdmontesinos I tested the fix with script, style, meta, comments, etc... can you please share what you are specifying in the HeadContent field so that I can investigate further.

**Comment by mdmontesinos** [comment]
Of course! This the content added:

```js
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'ID');
</script>
<!-- Another -->
<script>
  console.log("test");
</script>
```

Also, I just double-checked that I've pulled the latest changes and rebuilt the solution.

**Comment by sbwalker** [comment]
I will re-open and investigate

**Comment by mdmontesinos** [comment]
Thanks, if you require anything else from my part, please let me know.

**Comment by sbwalker** [comment]
@mdmontesinos please verify the latest PR. I had to update my testing scenarios for the various types of Resources which Oqtane manages:

Scripts:

![image](https://github.com/user-attachments/assets/5334069d-afdf-4ea1-ae8d-d7cc49b6acdc)

Stylesheets:

![image](https://github.com/user-attachments/assets/63266873-20df-4f4d-86f3-61791d7034e9)

Other Resources (meta, style, link, comments, etc…)

![image](https://github.com/user-attachments/assets/e8793344-e923-4e0b-93f0-80ab9c871a06)

**Comment by mdmontesinos** [comment]
@sbwalker It is fixed with the latest PR. Thanks!
