### ISSUE TITLE
[ENH] Return URL for ModuleActions -> Settings should contain URL parameters

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4628]
### Oqtane Info

Version - 5.2.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement

Currently, if you go into Edit Mode and access the settings when in a page with url parameters, the return url does not contain the parameters, so it's a great inconvenience for content managers.

For example, if I am in a page "news/!/the-latest-news" and I enter the module settings (Edit Mode -> Module Actions -> Settings), after saving or cancelling, I will be returned to "news?edit=true". This is really annoying when editing many pages, as perhaps the setting I changed only can be visualized when the page has that parameter. In that case, I need to again navigate back to parametrized page.

Therefore, the return url should also contain the page parameters and query.

**Comment by mdmontesinos** [comment]
@sbwalker Thanks, it's working as expected!

**Comment by sbwalker** [comment]
@mdmontesinos #4640 fixes this for all module actions

**Comment by sbwalker** [comment]
@mdmontesinos I know why that is happening... I will resolve today
