### ISSUE TITLE
[ENH] User Profile Option To Force Log Out All Instances

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4638]
### Describe the enhancement

Ability to choose to log out of all logged in instances to force re-logging in from account profile.

**Comment by sbwalker** [comment]
@thabaum you will need to provide more details as I do not understand what you are requesting

**Comment by thabaum** [comment]
For example, you have been logged in on multiple devices. A way to log them all out simultaneous to ensure they have to all re-sign-in.

**Comment by thabaum** [comment]
Multiple browsers would test this functionality.  as in log into a site with firefox then same username with edge.  Log out of one should just log that one out.  But if you share that info or feel you have been compromised you might feel the need to ensure all instances of that user being signed in get signed out.

**Comment by sbwalker** [comment]
With the recent enhancements in 5.2.2, if you change your password and Save a new SecurityStamp will be generated which will result in your account being signed out everywhere. So what you are asking for is a button to do the same thing without having to change your password.

**Comment by thabaum** [comment]
Correct, in security section of your profile generally there is a button to force logout similar to the password reset.

**Comment by thabaum** [comment]
Also, there is  usually a notification of anyone logging in from a new device/browser.  This helps monitor when/who/where a login may have happened.

**Comment by sbwalker** [comment]
,NET Identity does not keep track of past devices, etc.. used during login

**Comment by sbwalker** [comment]
Added a Logout Anywhere button to the User Profile:

![image](https://github.com/user-attachments/assets/d21c311f-e2d0-4139-a9fe-344b1cc82262)

Also added IP Address to logging for Login:

![image](https://github.com/user-attachments/assets/5555b8f5-1518-4c5b-8f4e-9471260f4b94)

**Comment by thabaum** [comment]
rock and roll! thanks @sbwalker that should help keep our sites/apps even more secure!
