### ISSUE TITLE
[ENH] Ability to log into a site with multiple accounts and switch between them as "linked".

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4639]
### Describe the enhancement
Ability to log into a site with multiple account profiles and switch between them.

Linking profiles, so if you log into one, you log into both.

**Comment by sbwalker** [comment]
The ability to "impersonate" another user will not be added to Oqtane. There are way too many security implications of this functionality. If you truly need this capability you will need to implement it as a custom module.

**Comment by thabaum** [comment]
OK, but I am not sure "impersonation" is the correct term here.  On X.com for example, you can create two accounts and then connect them so you can be logged into both and switch between them.  Maybe it is impersonation, but this is not an admin feature request.

**Comment by thabaum** [comment]
A use case: If you have a business and personal account on the app you have to use 2 browsers.  This would remove the need for two browsers.

**Comment by thabaum** [comment]
I can see this being a custom module if needed and so I just wanted to clarify in case it can be reconsidered as an option that can be enabled.

**Comment by sbwalker** [comment]
The .NET Core Identity does not support this use case of being logged in with 2 different accounts - essentially you can only have 1 auth cookie active at a time. So what you are referring to would require a significant amount of customization to the entire auth system - which is not on the roadmap.

**Comment by thabaum** [comment]
This is something we can discuss when things are more calm and after the web farm along with other security features get enhanced.  Even if 1 year from now as .NET may make it more easier to implement.  Hoping to plan the seed for maybe a future enhancement as this is a big contribution, I agree.
