### ISSUE TITLE
[BUG] Switching to different Default Bootstrap Themes Causes Oqtane.Blog Module Not To Render

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4647]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
When you switch to a "default" theme other than the Oqtane Default Cyborg Theme, the blog module will not render.

**Comment by sbwalker** [comment]
@thabaum I am not sure what you mean... the blog module is being used on this page: https://www.oqtane.org/blog which is using a custom theme (not the default Oqtane theme).

**Comment by sbwalker** [comment]
The blog module utilizes a "template" which is defined in the module settings... so if you use a different theme then you might need to adjust the template to use different styles.

I am closing this issue, as any issues pertaining to the Blog module should be logged in the Blog repository
