### ISSUE TITLE
[ENH] System Update Download Spinner/Progress Bar

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4654]
### Oqtane Info

Version - 5.2.1
Static

### Describe the enhancement
Although generally a quick download, but after hitting the download button it would be nice to have something let us know it is being downloaded such as a message saying "Downloading ." "Downloading .." "Downloading ..." repeating until downloaded then the message as shown below for successful download or error:

![image](https://github.com/user-attachments/assets/840aa2d3-a72c-47a4-a00d-29b4b43f5cac)

![image](https://github.com/user-attachments/assets/7ae0b01e-724b-4f14-a60b-c38fdfdaa703)

Spinner "Downloading" would be cool, progress bar or message as described above.

**Comment by zyhfish** [comment]
The upgrade page has already been updated to display the progress bar and status message.

**Comment by thabaum** [comment]
@zyhfish this is correct.  I am discussing a progress bar similar to the File Upload Manager while uploading, but one for downloading as well so we know that something is being downloaded instead of no notification of "Downloading" in the notification area at the top:
![image](https://github.com/user-attachments/assets/dff23526-b13b-4cf0-a95e-d5822de70c8d)

This notification area could say "Downloading" then the "Success" message as shown above for example when clicking on this button:

![image](https://github.com/user-attachments/assets/b0894a9f-078e-4c61-beb0-ae9ecf6d74d4)
