### ISSUE TITLE
[BUG] Autocomplete of fields of user logged in for SMTP username/password and enabled by default without being configured

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4655]
### Oqtane Info

Version - 5.2.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
The username and password cannot be deleted from the SMTP settings'

SMTP settings should be disabled by default

![image](https://github.com/user-attachments/assets/48b00ff3-4ead-477a-8339-98393c078e79)

### Expected Behavior

Username and password fields do not get autocomplete populated
### Steps To Reproduce
Save a password to your browser for logging into the site as administrator
Navigate to site settings in dashboard
Under SMTP Settings notice the field is autocompleted

### Anything else?
![image](https://github.com/user-attachments/assets/c2811b9b-d2f2-465f-b543-a4957d7d55d6)

Blank will always populate

As a workaround set a random username
![image](https://github.com/user-attachments/assets/b7ae10c6-d867-413c-a9d1-c9817c20f91d)

SSL Enabled should be true by default

![image](https://github.com/user-attachments/assets/06535ef6-7ec2-4d31-931f-5a45716a1d30)

This can be an issue if you have a host visit an account, and the password can be seen once set if HOST or another admin logs in and saves site settings without this being set.

![image](https://github.com/user-attachments/assets/7a9d00b9-079c-4421-be8d-069fad0af11b)

`<input id="password" type="password" class="form-control">`

'<input id="username" class="form-control">'

should these fields include `autocomplete="off"`

https://www.w3schools.com/howto/howto_html_autocomplete_off.asp

I will create a PR if OK and not a breaking change?

**Comment by thabaum** [comment]
#4657 should resolve the issue if browsers honor the form field attribute setting `autocomplete="off"`

**Comment by thabaum** [comment]
There maybe more to resolve here with the defaults of SSL Enabled to `Yes` and SMTP Enabled to `No`  2 other issues which would be in the defaults for the script that creates the database entry for each site when created.

I can create this PR as well if needed, or you can if you like @sbwalker not sure if this would be desired settings.

**Comment by sbwalker** [comment]
@thabaum most browser password managers completely ignore autocomplete="off" however I am not against including the attribute for the minority of cases where it actually works as expected.
