### ISSUE TITLE
[BUG] 5.2.3: Unable to Install Oqtane On Windows IIS

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4667]
### Oqtane Info

Version - 5.2.3
Render Mode - Static 
Interactivity - Server
Database - SQL Server or LocalDB
Web Server - Standalone Production IIS Server (no control panel such as plesk)

### Describe the bug
https://github.com/oqtane/oqtane.framework/discussions/4665
Unable to Install Oqtane On Windows IIS (have not tested via Linux/Apache)

### Steps To Reproduce
Attempt to Install Oqtane using LocalDB OR MS SQL (With database already created) using IIS Express or IIS.

### Anything else?
https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues

Error:
`An Error Occurred Creating Site. System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913. at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection() at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1.AsyncEnumerator.MoveNextAsync() at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable1 asyncEnumerable, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable1 asyncEnumerable, CancellationToken cancellationToken) at Microsoft.AspNetCore.Identity.UserManager1.FindByNameAsync(String userName) at Oqtane.Repository.UserRoleRepository.UpdateSecurityStamp(Int32 userId) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\UserRoleRepository.cs:line 168 at Oqtane.Repository.UserRoleRepository.AddUserRole(UserRole userRole) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\UserRoleRepository.cs:line 75 at Oqtane.Infrastructure.DatabaseManager.CreateSite(InstallConfig install) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 592`

> this specific scenario (ie. creating a new site in a multi-tenant environment using an isolated database) may have been affected by the recent enhancements in 5.2.2 to support SecurityStamp:
> 
> Oqtane.Repository.UserRoleRepository.UpdateSecurityStamp(Int32 userId) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\UserRoleRepository.cs:line 168
> 
> This method relies on the .NET Identity library - which appears to be throwing the DbContext exception. Perhaps the .NET Identity library is not using DbContextFactory (which is the recommended approach in Blazor). This will require more investigation.

Upgraded from 5.0.1 successfully. Lost the login and dashboard controls/button, gained search feature as an FYI default template.

Additional sites also cannot be created with new databases from within an existing Oqtane instance.

**Comment by thabaum** [comment]
@sbwalker I was able to reproduce this issue in Windows 11 using IIS and LocalDB to simulate the production environment.

![image](https://github.com/user-attachments/assets/ab255556-53bd-44dd-8a62-2d6a8002df87)

**Comment by thabaum** [comment]
@sbwalker Creating a website from scratch creates this error and is a showstopper for anyone trying to get started.

![image](https://github.com/user-attachments/assets/141ae789-b38c-479b-a82b-022621e04203)

I dont think it is related to creating a database, but populating it as this database was manually created, unable to create a site.   I will update the issue.

**Comment by sbwalker** [comment]
@thabaum I am not able to reproduce this in a local development environment running in Visual Studio. And in @JanOlsmar's original discussion post he mentioned that he was able to install 5.2.3 on Windows IIS just fine - he did not encounter an error until he tried to create another site in the installation with a separate database. So what you are reporting is different than what @JanOlsmar reported - it would be helpful to understand why you are getting different results.

**Comment by thabaum** [comment]
@sbwalker I had this instance shown working on another database instance and upgraded it, then tried to make a sub-site with another database being created using LocalDB and integrated security.  Oqtane created everything in the master database but I dont believe the actual LocalDB was created for the second instance of databases.

So in a way this is two issues in one as I am getting the same error trying to create a site from scratch as I normally would, and which I believe was trying to be explained. 

Sorry last edited post shows more screenshots I had removed to simplify finding a solution that I believe is related to both issues.  It shows the error log entry which function was throwing the error.

I will be back in a few to test more.

**Comment by thabaum** [comment]
@sbwalker in a local dev environment from Visual Studio it installs without an issue with LocalDB

![image](https://github.com/user-attachments/assets/4abe7a11-03f9-4ab4-acd5-752af98ec2f6)

This is strictly an IIS issue which can be reproduced by setting up Windows 11 with IIS Express to install a fresh copy.

**Comment by thabaum** [comment]
https://docs.oqtane.org/manuals/admin/installation/windows-iis-express-sql-express.html

This should reproduce the issue

**Comment by thabaum** [comment]
Information pulled from related issue Microsoft thread:

Avoiding DbContext threading issues

Entity Framework Core does not support multiple parallel operations being run on the same DbContext instance. This includes both parallel execution of async queries and any explicit concurrent use from multiple threads. Therefore, always await async calls immediately, or use separate DbContext instances for operations that execute in parallel.

When EF Core detects an attempt to use a DbContext instance concurrently, you'll see an InvalidOperationException with a message like this:

    A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe.

When concurrent access goes undetected, it can result in undefined behavior, application crashes and data corruption.

There are common mistakes that can inadvertently cause concurrent access on the same DbContext instance:
Asynchronous operation pitfalls

Asynchronous methods enable EF Core to initiate operations that access the database in a non-blocking way. But if a caller does not await the completion of one of these methods, and proceeds to perform other operations on the DbContext, the state of the DbContext can be, (and very likely will be) corrupted.

Always await EF Core asynchronous methods immediately.
Implicitly sharing DbContext instances via dependency injection

The [AddDbContext](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext) extension method registers DbContext types with a [scoped lifetime](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#service-lifetimes) by default.

This is safe from concurrent access issues in most ASP.NET Core applications because there is only one thread executing each client request at a given time, and because each request gets a separate dependency injection scope (and therefore a separate DbContext instance). For Blazor Server hosting model, one logical request is used for maintaining the Blazor user circuit, and thus only one scoped DbContext instance is available per user circuit if the default injection scope is used.

Any code that explicitly executes multiple threads in parallel should ensure that DbContext instances aren't ever accessed concurrently.

Using dependency injection, this can be achieved by either registering the context as scoped, and creating scopes (using IServiceScopeFactory) for each thread, or by registering the DbContext as transient (using the overload of AddDbContext which takes a ServiceLifetime parameter).

**Comment by thabaum** [comment]
Should the installation method CreateSite be changed to an asynchronous task method?

**Comment by sbwalker** [comment]
@thabaum i was referring to being able to reproduce the issue in a way where I can trigger the exception and actually see the specific runtime context - which is not possible in a log message.

**Comment by sbwalker** [comment]
In regards to the DbContext error it is being thrown from inside the .NET Identity library - so not from Oqtane code. So will probably require looking on the .NET Identity source code on GitHub to see how it handles DbContext.

**Comment by thabaum** [comment]
correct, no easy way which is what I was trying to explain earlier, we have to do this one the hard way, at least I would have to... trial and error.  Make sure whatever fix you think works in Visual Studio first, then apply it to a production installation (From IIS).

**Comment by thabaum** [comment]
@sbwalker I am happy to test any solution you think might work once you apply it to the code base.

**Comment by thabaum** [comment]
>  i was referring to being able to reproduce the issue in a way where I can trigger the exception and actually see the specific runtime context - which is not possible in a log message.

@sbwalker would a try catch block on that method help gain insight?

**Comment by thabaum** [comment]
https://github.com/dotnet/aspnetcore/tree/main/src/Identity

This is the source we need to review closer, correct?

**Comment by sbwalker** [comment]
I was able to reproduce the error using IIS and LocalDB. I have a resolution but I want to validate a number of other scenarios before I submit the PR.

**Comment by sbwalker** [comment]
#4672 resolves the problem by not executing the UpdateSecurityStamp logic (introduced in 5.2.2) during Installation. This is a viable solution because there is no valid reason to update the security stamp in the scenario where a new user is being created - the security stamp is intended for scenarios where the user already exists and their security information is being modified.

**Comment by FloLaz** [comment]
I downloaded 5.2.3 release and got the error on my Windows server with IIS. After reading this I downloaded 5.2.1 and it worked.
After updating to 5.2.3 I created a new site with a dedicated database and I faced the same error.

**Comment by thabaum** [comment]
@FloLaz you would need to create all sites first in 5.2.1, then upgrade.  Once you upgrade you cannot create sites or sub-sites until 5.2.4 is released.

**Comment by osblock** [comment]
I have Installed as per the Blog but receiving the error : "Your connection is not private"  I have not enabled the HSTS, I am using the IIS 10 on Windows 11

**Comment by osblock** [comment]
I am able to solve the above problem but when I am installing the by using MS SQL Server using custom configuration, I am receiving below error 

**An Error Occurred Creating Site. System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed.** This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913. at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection() at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync() at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken) at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName) at Oqtane.Repository.UserRoleRepository.UpdateSecurityStamp(Int32 userId) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\UserRoleRepository.cs:line 168 at Oqtane.Repository.UserRoleRepository.AddUserRole(UserRole userRole) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\UserRoleRepository.cs:line 75 at Oqtane.Infrastructure.DatabaseManager.CreateSite(InstallConfig install) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 592

**Comment by nicpitsch** [comment]
@osblock I faced the same error *A second operation was started..*. Therefore I supose you have made a new installation of Oqtane version 5.2.3. A new 5.2.3 installation is not possible. As @thabaum mentions here https://github.com/oqtane/oqtane.framework/issues/4667#issuecomment-2400494482 you have to start with 5.2.1.

**Comment by sbwalker** [comment]
5.2.4 will be released which addresses this IIS install issue

**Comment by osblock** [comment]
> 5.2.4 will be released which addresses this IIS install issue

Thank you @sbwalker - I have resolved my current issue for now as per @nicpitsch.
