### ISSUE TITLE
[BUG] Issue with Login on Subdomain-Based Tenant Configuration

### ISSUE THREAD

**Issue by mithang** [oqtane/oqtane.framework#4679]
### Oqtane Info

Version - 5.2.3
Render Mode - Static 
Interactivity - Server
Database - Postgres

### Describe the bug
When configuring tenants (tenant1, tenant2) using the site URLs like localhost:44357/tenant1 or localhost:44357/tenant2, login works fine. 
However, when configuring tenant1 and tenant2 using subdomains(tenant1.localhost:44357,tenant2.localhost:44357), the login fails, as shown in the screenshot below.
![page 1](https://github.com/user-attachments/assets/cc4c9906-0b2a-4322-95c8-73d61ac34357)
![page 2](https://github.com/user-attachments/assets/630e4785-94aa-4e37-bf16-039922eba2c5)

### Anything else?
Please help me fix these issue! @sbwalker s

**Comment by sbwalker** [comment]
I am using subdomains on many production sites (ie. https://sandbox.oqtane.net) and it works fine. Perhaps the problem is related to using subdomains with localhost and port#'s - however this does not seem like a real world scenario?

**Comment by zyhfish** [comment]
I tried with domain "sandbox.localhost:34567" but doesn't meet any error, could you please provide the detail reproduce steps?
