### ISSUE TITLE
[BUG] 404 when page exists?

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4704]
### Oqtane Info

Version - 5.2.3
Render Mode - interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
Not sure if bug or design.  When not logged in and I click a link to a page that exists but requires authentication, i get 404 Page not found.

### Expected Behavior
Because the page does exist thenI should be taken to the log in page.

### Steps To Reproduce
Create link to a page for Registered users, log out and click the link.

**Comment by sbwalker** [comment]
I cannot recreate this problem locally. The existing Private page is only visible to Registered Users. I added a link to the Home page Welcome module:

```<p><a href="/private">Private</a> </p>```

Then I logged out and clicked the link on the Home page:

![image](https://github.com/user-attachments/assets/62173743-5694-42ad-9fdc-0e665a26f5b5)

Also if I enter the Url http://localhost:44357/private directly into the browser address bar and navigate I see:

![image](https://github.com/user-attachments/assets/4c078409-b72b-4fc8-95cd-d07ce4ee7fd1)

**Comment by thabaum** [comment]
IF an admin page it would go 404
