### ISSUE TITLE
[BUG] Warning - Layout was forced before the page was fully loaded. 

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4709]
### Oqtane Info

Version - 5.3.4
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Firefox warning which may lead to a "flash" of unstyled content.

Warning in Firefox Browser: 
` Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.`

### Expected Behavior
Oqtane stylesheets are loaded prior to layout to avoid a `flash of unstyled content.`

### Steps To Reproduce

I am not 100% sure as I was switching between languages testing culture cookie noticed this issue while running the instance in Visual Studio.

### Anything else?

I will report more when I know more.  I am not able to reproduce currently as refreshing the page resolved the issue.   Not sure if this would be a .NET issue, Oqtane issue or Visual Studio issue.

**Comment by sbwalker** [comment]
closing this issue as there is no way to reproduce/investigate. If you are able to identify the steps to reproduce it can be reopened.
