### ISSUE TITLE
[BUG] Page is not reloading/refreshing when switching languages in navigation menu UI

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4711]
### Oqtane Info

Version - 5.3.4
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
After switching languages in the LanguageSwitcher.razor component the page is not reloaded or refreshed to show the language did in fact change.

### Expected Behavior
Language in the UI will change once the language is changed in the navigation menu control.

### Steps To Reproduce
1. Install multiple languages in the language management control panel.
2. Switch between languages and notice how the language of the administration page for languages and the UI control for switching languages does not update in the UI to reflect the new language selected.

### Anything else?       

`NavigationManager.NavigateTo(NavigationManager.Uri.Replace($"?culture={culture}", ""), true);`

I updated the line in `LanguageSwitcher.razor` like above still same results, the UI does not update without refreshing the page manually in the browser to the view the language selected.

?culture={culture} will appear in the URL for a moment then gets removed with the culture variable replaced with the selected language abbreviation.

This was discovered while working with the issue in discussion https://github.com/oqtane/oqtane.framework/discussions/4703

Issue https://github.com/oqtane/oqtane.framework/pull/4493/files was working in the area of the cookie which was thought to have had been the issue updating the httpOnly setting to false, however I was not able to reproduce any different results as a page refresh would display the changes to the UI updated with the language selected.

**Comment by thabaum** [comment]
I am thinking maybe an issue with "Enhanced Navigation" potentially thinking more about the issues we have had in the past relating.

**Comment by sbwalker** [comment]
@thabaum with the latest changes and using Static Rendering, I am not able to reproduce what you are describing above. If I have multiple languages in my site and I select a language from the Language Switcher I can see the cookie being updated in my browser dev tools and when I click the down arrow in the Language Switcher I can see that the new language is highlighted.

**Comment by sbwalker** [comment]
I think what you may be referring to is the list of Languages in the Language Switcher is not being localized based on the item selected by the user. This is actually a caching issue, as the list of languages is cached for the site - not based on the UI culture of the current user.

**Comment by thabaum** [comment]
@sbwalker yes this is the issue.  The admin page is not changing, but if you are navigating around after switching it seems OK.  I dont see any other way to test langauges on different pages switching between. I am not sure what language packs are even updated such as for the control panel I see english when using dutch.

![image](https://github.com/user-attachments/assets/7d08770b-0d7e-463f-9dc2-239f0967e792)

So to see it in action like you described, the Language Management has been what I have used to see the updates.  I have to hit refresh to see them update in static mode only I believe.

**Comment by thabaum** [comment]
![image](https://github.com/user-attachments/assets/bbd15524-22ae-4bc6-b297-9a113358829f)

it fixes it in this area

but the language manager still stays the same

![image](https://github.com/user-attachments/assets/b9092091-6ba1-4e16-884b-dcc6e8518367)

**Comment by sbwalker** [comment]
The labels in the UI and the list of language names in the Language Switcher are actually based on totally different concepts. UI labels will not change unless you have a translation package installed for the language you choose from the Language Switcher - if no translation package exists, it will display the fallback which is English

**Comment by thabaum** [comment]
I hit refresh and I get this:

![image](https://github.com/user-attachments/assets/af52f5a8-65ef-4aec-9471-64e35f5ae524)

**Comment by sbwalker** [comment]
The Language Management UI is currently displaying the language names stored in the database

**Comment by sbwalker** [comment]
Ok I will need to look into Language Management tomorrow - it is probably a caching issue as well

**Comment by sbwalker** [comment]
#4732 resolves this issue. It requires the use of ``` data-enhance-nav="false"``` to force a full page refresh on the language hyperlinks. The user experience is not optimal when using a full page refresh - but it is consistent with the experience when using fully interactive render mode. 

I discovered a few other oddities while investigating this problem and will log a separate issue to describe them.
