### ISSUE TITLE
[BUG] Oqtane Installation Does Not Create Host User If Username Contains A Special Character

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4752]
### Oqtane Info

Version - 5.2.4
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Creating a new site on IIS production does not create an initial host user to login and manage system if it has a special character in the username field.

### Expected Behavior
Host User Is Created

### Steps To Reproduce
Install on IIS Production Environment and Run Setup Wizard

### Anything else?
I ran this a few times to see if it would work, didn't work each time.  Maybe something in the password is an issue?  I had a password that firefox created one attempt and I got an error stating I did not follow password policy although there looked to be all conditions satisfied.

![image](https://github.com/user-attachments/assets/94823769-eb7d-4c8d-a185-31a7e5971ca5)

**Comment by thabaum** [comment]
I did 2 things to resolve this issue. 
1.  I had to upgrade my instance of MS SQL Server I noticed it had a patch which was recently released
2. I used a simpler username and password that did not contain a certain character.

I will test but I am guessing the update to the SQL server patch was what fixed it to work with 8.0.10 packages.

**Comment by thabaum** [comment]
Reopening issue as it was #1 above that caused the problem and I was able to reproduce.  I will get more info once I can verify if it was the password or the username used.

I believe found 2 issues with the Username/Passwords being set that we should address.  I will provide more details soon.

**Comment by thabaum** [comment]
I have updated this issue to reflect the fact if you use a special character in the username, no user is created.  Logic needs to be put in place to verify users do not have special characters, or ability to use special characters needs fixed.

**Comment by sbwalker** [comment]
Oqtane uses .NET Identity which has a default validation rule for usernames:

```
options.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
```

Any of the .NET Identity default options can be overridden in the appsettings.json file if you wanted to allow extended characters.

The main issue is that Oqtane is not validating the username when the form is submitted in the Installer... which basically means that the user is not getting immediate feedback that the username is invalid. The Installer should be enhanced to validate the username based on the criteria defined for .NET Identity and provide feedback - similar to how passwords are validated currently.

**Comment by thabaum** [comment]
> The main issue is that Oqtane is not validating the username when the form is submitted in the Installer... which basically means that the user is not getting immediate feedback that the username is invalid. The Installer should be enhanced to validate the username based on the criteria defined for .NET Identity and provide feedback - similar to how passwords are validated currently.

@sbwalker basically this is what needs to happen and why I reported.

Looks like fix #4752 I can test and see how things go.

This should also be reviewed in the User Management area.  I want to create users as well and be sure they do not cause any issues with passwords/emails/usernames used when created.

**Comment by thabaum** [comment]
`options.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";`

After further investigation the forms for user registration, user management > add user and for the installation need validation checks or get errors or a blank user unable to login as host for installation.

They should check against allowed characters and send a message back to the user relating to the issue instead of logging an error.

![image](https://github.com/user-attachments/assets/d0163aad-332f-4e5d-aa1c-4758c96187a8)

![image](https://github.com/user-attachments/assets/84086cd5-2578-4de9-9047-c56e1da2bc8c)

**Comment by thabaum** [comment]
also tool tips should inform a user what is allowed as well.

**Comment by thabaum** [comment]
@sbwalker this issue seems to be fixed, however the allowed characters in the error message could be updated to allow alphanumeric characters and `-._@+` am I correct?  This would allow users and admins know that it is OK to use an email address for example.

I can create this PR if that is desired.

**Comment by sbwalker** [comment]
@thabaum yes the RESX value should be updated to reflect the actual allowable criteria
