### ISSUE TITLE
[BUG] My DLL's are replaced with older DLL's in bin/debug/Net8.0 when startup in debug-mode.

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4757]
### Oqtane Info
My DLL's are replaced with older DLL's in bin/debug/Net8.0 and projects DLL's that are deleted are added to the same directory.
The responsible routine seams to be the InstallPackages(string webRootPath, string contentRootPath) in InsattaltionManager.cs.

This does not happen all the time - but it seams to happen after I have compiled for Release and the Debug. When I then startup in debug-mode  I can see (in the filebrowser) that my projectfiles are changed a lot of times before it fails.

After compile (for debug) I have this files in the bin/debug/net8.0:
![image](https://github.com/user-attachments/assets/47be6038-77c4-467a-a7fa-f08010847f38)

When I start the debug my files are changed in the filebrowser, but it looks like this when I get the error in startup.
![image](https://github.com/user-attachments/assets/45187683-fbdc-443c-b97a-993faaa941be)

The ClientSFO project are deleted some months ago - and if its in the debug directory I get error later in the startup process.

What should I do? Delete all the old packages?

I try to send a video where you can see the changing of dll's in the debug-directory. The size was to large so I send you a link to dropbox:

https://www.dropbox.com/scl/fi/1j395a74wkt94iq86nuy2/OqtaneDLLproblem.zip?rlkey=y9okqzopoydts0fygvzcdg29a&st=qq6hrwix&dl=0

Version - 5.2.4
Render Mode - Static 
Interactivity - Server
Database - SQL Server

Best  regards
BEO

**Comment by sbwalker** [comment]
@beolafsen If you build your module in Debug mode, it will copy the DLLs to the Oqtane /bin folder using the debug.cmd file in the module's Package project folder. If you build your module in Release mode, it will create a Nuget package using the Nuspec file in the module's Package project folder and then copy the Nuget package to the Oqtane /packages folder where it will be extracted the next time you run the framework. My guess is that your Nuspec is not configured correctly and is including DLLs from an older .NET version. Please check the "files" section of the Nuspec to ensure the paths are correct:

```
  <files>
    <file src="..\Client\bin\Release\net8.0\Oqtane.Blogs.Client.Oqtane.dll" target="lib\net8.0" /> 
    <file src="..\Client\bin\Release\net8.0\Oqtane.Blogs.Client.Oqtane.pdb" target="lib\net8.0" /> 
    ...
```

**Comment by beolafsen** [comment]
Hi!

After compile everything looks fine in the /bin folder. It is when I start the application that the changes happens,

I can see ( in the FileExplorer) that the dates on my DLL-files are changed when the application runs - and this seams to happens when the system is in the InstallPackages routine.

My nuspec looks like  this:

<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
	<metadata>
		<id>OqtaneLibrary</id>
		<version>1.4.4</version>
		<authors>OqtaneLibrary</authors>
		<owners>OqtaneLibrary</owners>
		<title>OqtaneLibrary</title>
		<description>OqtaneLibrary</description>
		<copyright>OqtaneLibrary</copyright>
		<requireLicenseAcceptance>false</requireLicenseAcceptance>
		<license type="expression">MIT</license>
		<projectUrl>https://github.com/oqtane/oqtane.framework</projectUrl>
		<icon>icon.png</icon>
		<tags>oqtane module</tags>
		<releaseNotes></releaseNotes>
		<summary></summary>
		<dependencies>
			<dependency id="Oqtane.Framework" version="5.2.4" />
		</dependencies>
	</metadata>
	<files>
		<file src="..\Client\bin\Release\net8.0\OqtaneLibrary.Client.Oqtane.dll" target="lib\net8.0" />
		<file src="..\Client\bin\Release\net8.0\OqtaneLibrary.Client.Oqtane.pdb" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\OqtaneLibrary.Server.Oqtane.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\OqtaneLibrary.Server.Oqtane.pdb" target="lib\net8.0" />
		<file src="..\Shared\bin\Release\net8.0\OqtaneLibrary.Shared.Oqtane.dll" target="lib\net8.0" />
		<file src="..\Shared\bin\Release\net8.0\OqtaneLibrary.Shared.Oqtane.pdb" target="lib\net8.0" />

		<file src="..\Server\bin\Release\net8.0\Microsoft.AspNetCore.SignalR.Client.Core.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Microsoft.AspNetCore.SignalR.Client.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Microsoft.AspNetCore.Http.Connections.Client.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Microsoft.AspNetCore.Http.Connections.Common.dll" target="lib\net8.0" />

		<file src="..\Server\bin\Release\net8.0\Syncfusion.Blazor.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Syncfusion.Licensing.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Syncfusion.PdfExport.Net.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Newtonsoft.Json.dll" target="lib\net8.0" />

		<file src="..\Server\bin\Release\net8.0\AutoMapper.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\Stripe.net.dll" target="lib\net8.0" />

		<file src="..\..\..\ClassLibraries\CL_CSharp\bin\Release\net8.0\CL_CSharp.dll" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_CSharp\bin\Release\net8.0\CL_CSharp.pdb" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Extensions\bin\Release\net8.0\CL_Extensions.dll" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Extensions\bin\Release\net8.0\CL_Extensions.pdb" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Audit\bin\Release\net8.0\CL_Audit.dll" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Audit\bin\Release\net8.0\CL_Audit.pdb" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Shared\bin\Release\net8.0\CL_Shared.dll" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Shared\bin\Release\net8.0\CL_Shared.pdb" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Stripe\bin\Release\net8.0\CL_Stripe.dll" target="lib\net8.0" />
		<file src="..\..\..\ClassLibraries\CL_Stripe\bin\Release\net8.0\CL_Stripe.pdb" target="lib\net8.0" />

		<file src="..\Server\bin\Release\net8.0\LinqKit.Core.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\LinqKit.Microsoft.EntityFrameworkCore.dll" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\CommunityToolkit.Diagnostics.dll" target="lib\net8.0" />

		<file src="..\Server\bin\Release\net8.0\appsettingsServer.json" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\appsettingsServer.Production.json" target="lib\net8.0" />
		<file src="..\Server\bin\Release\net8.0\appsettingsServer.Development.json" target="lib\net8.0" />


		<file src="..\Server\wwwroot\**\*.*" target="wwwroot" />
		<file src="icon.png" target="" />
	</files>
</package>

**Comment by sbwalker** [comment]
please review your release.cmd file in module's Packages project. I suspect it is missing the delete command:

ie.

```
del "*.nupkg"
"..\..\oqtane.framework\oqtane.package\nuget.exe" pack Oqtane.Blogs.nuspec 
XCOPY "*.nupkg" "..\..\oqtane.framework\Oqtane.Server\Packages\" /Y
``` 

if it does not have a delete command then the Packages folder will contain Nuget packages for every prior version of the module you have ever created. And when you compile your module in Release mode, it will copy ALL of those Nuget packages to the Oqtane framework /packages folder. And then when you run Oqtane, it will extract the contents of ALL of the Nuget packages - which may lead to the behavior you are describing.

**Comment by beolafsen** [comment]
Thank you - the delete stmt was missing.
