### ISSUE TITLE
[BUG] Admin - Site Settings: No notification when saving settings successfully.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4760]
### Oqtane Info

Version - 5.2.4
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Admin - Site Settings: No notification when saving settings successfully.

### Expected Behavior
a notification at the top of the page is shown with an error or success message

### Steps To Reproduce
expand sections in site settings so you need to scroll up.
save site settings
notice no success or error message message to let a user know an action was performed.

**Comment by sbwalker** [comment]
this is because a full page refresh is required in Site Settings to handle scenarios where the theme, UI component settings, etc... have been modified.

**Comment by zyhfish** [comment]
how about to add a query string in the redirect URL, then we can display successful message when the query string is appended.

**Comment by sbwalker** [comment]
@zyhfish although that solution would work, it feels more like a workaround than a proper solution.

**Comment by sbwalker** [comment]
@zyhfish actually, I am not opposed to this approach in this specific scenario - please go ahead and submit a PR
