### ISSUE TITLE
[ENH] Theme Management Should Not Have "Create Theme" Option In Production Environments

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4790]
### Oqtane Info

Version - 6.0.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
Theme Management Should Not Have "Create Theme" Option In Production Environments.  I believe this should only be for "Development" environments.

### Anything else?
![image](https://github.com/user-attachments/assets/06f9b455-356f-449e-ac0c-6a48f6a7888f)

**Comment by leigh-pointer** [comment]
Is there not a wrning like there is when creating a module?
I do know that templates are not shipped in the prod package.

**Comment by thabaum** [comment]
I am just not sure it should be there and if Oqtane detects it is "Production" as it does in System Info this button can be removed easily.

If creating a module button shows up it can also be easily removed as this is not something you should even get warned about.  Maybe a host feature can enable it to allow if you are developing in a production environment?

I am just confused why it is here as this should be a development environment feature, not a production environment feature unless Hosts need to have the ability to develop in production.

I have not tested creating a module or theme in production but I thought it would be worth discussing what should be and not be to avoid any potential issues in production environments.

Does anyone develop themes and modules in production environments?

**Comment by sbwalker** [comment]
If you are in a production environment and you select the Create Theme option in Theme Management, the UI says:

"Please Note That The Theme Creator Is Only Intended To Be Used In A Development Environment"
