### ISSUE TITLE
[BUG] Module Management : Upload  a large module (bigger than 1GB) results in an unusable installation file.

### ISSUE THREAD

**Issue by HQuast** [oqtane/oqtane.framework#4795]
### Oqtane Info

Version - 5.2.4
Render Mode - Static 
Interactivity - Server
Database - Postgres

### Describe the bug
Uploading a module package that is larger than 1 Gb  results in a an unusable installation file (nupkg).  That happened when running in a Docker container.  The reason is that the the chunked files are merge in the order they are stored. But they should be merged in the ordered by the file naming. 

### Anything else?

Solution: 
File :oqtane.framework\Oqtane.Server\Controllers\FileController.cs  Commit: #3adb7ecb1cabcc579b68350e51061299f86b20e9 
   
Class : public class FileController : Controller
    Method: private async Task<string> MergeFile(string folder, string filename)

LIne: 520
  Replace the line   
        foreach (string filepart in fileparts)
   With 
       foreach (string filepart in fileparts.Order())

**Comment by sbwalker** [comment]
@HQuast I am unable to reproduce this on a standard installation (ie. not using Docker). So this makes me wonder if Docker is changing the behavior of this following System.IO method:

```
string[] fileparts = Directory.GetFiles(folder, filename + token + "*"); // list of all file parts
```

**Comment by HQuast** [comment]
@sbwalker Sorry, I mean MB. In my test the upload was splitted in two file chunks. And the files are merged in reverse order. I could only reproduce this when running in a docker container. On a local installation the problem didn't occurs.

**Comment by sbwalker** [comment]
Ok, so you are saying the call to:

```
Directory.GetFiles(folder, filename + token + "*");
```

is resulting in a list of files which is not in alphabetical order when run in Docker... very strange.

**Comment by sbwalker** [comment]
In the documentation:

https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-8.0

It actually says:

"The order of the returned file names is not guaranteed; use the Sort method if a specific sort order is required."

Is the Docker container running Windows or Linux?

**Comment by HQuast** [comment]
It is a Linux container.
