### ISSUE TITLE
[ENH] Use Microsoft.IO.RecyclableMemoryStream

### ISSUE THREAD

**Issue by adamradocz** [oqtane/oqtane.framework#4797]
### Describe the enhancement
In the code, new `MemoryStream()` could be optimized with pooling by using the [Microsoft.IO.RecyclableMemoryStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) nuget.

**Comment by sbwalker** [comment]
Oqtane will be adopting the new HybridCache approach now available in .NET 9:

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?view=aspnetcore-9.0
