### ISSUE TITLE
[ENH] Gitignore extra folders/files in wwwroot

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4835]
### Oqtane Info

Version - 6.0.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement

If you add new folders from a module that are copied into Oqtane wwwroot, they should be gitignored to avoid having dozens of files pending in Git.

For example, in my case several folders ended up in version control:

![image](https://github.com/user-attachments/assets/433e68e8-aa60-408f-b56c-14fd89b0137c)

After the change, the only file in version control is the appsettings:

![image](https://github.com/user-attachments/assets/9ad61f63-2864-4ca7-89d3-aa28f3012668)

**Comment by sbwalker** [comment]
These changes to gitignore would creates issues as there are specific folders/files within wwwroot which do need to be monitored/maintained in GitHub and included as part of the release build process. I would suggest you create your own gitignore if you need different rules to manage the Oqtane source code in your local environment.
