### ISSUE TITLE
[BUG] IIS Express Worker Process use up to 26 GB memory while startup OqtaneFramework in Debug mode

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4839]
### Oqtane Info

Version - 6.0.0 but same problem with earlier versions
Render Mode - Static  / Interactive
Interactivity - Server / Server
Database - SQL Server

### Describe the bug
When I startup my Oqtane application the IIS Express Worker Process start to grow up to 26 GB memory. After a while I get problems with the Client/Server connection. Then the memory usage drops (in IIS Express Worker Process) and after a while I get the connections again and then it starts to build up the memory usage. And this loop continue.

![image](https://github.com/user-attachments/assets/7c928aa8-3db2-4f19-b36e-fe79dd9d9fbc)

To find out where the problem comes from, I tried to only work with the original OqtaneFramwork application.
First I tried to reproduse the same error with OqtaneFramework - and the same happens - the memory usage go up to 26 GB.

After this I deleted the bin directory in OqtaneFramework and the I compiled the OqtaneFramework before I run it. Then I don't get the problem with memory.

Then I compile my Oqtane application (with copy of DLL's to OqtaneFramework) - and then I start the OqtaneFramework application again and then I got the same problem with memory usage.

It looks like my Oqtane Server DLL is causing some problem even though I'm only running a pure OqtaneFramework application. 

Any ideas on what could be the problem?

Div pictures:
![image](https://github.com/user-attachments/assets/8dc43bb8-71e1-4c15-8028-39b6e3ced8d0)

![image](https://github.com/user-attachments/assets/1c92807e-2ae4-4dd4-93f3-307086814b5a)

**Comment by beolafsen** [comment]
Video of startup Oqtane Framework.

[recording (2).zip](https://github.com/user-attachments/files/17784397/recording.2.zip)

**Comment by beolafsen** [comment]
The problem started when I upgraded from VS 17.10.6 to 17.11.5.

**Comment by beolafsen** [comment]
Then I tried to upgrade to VS 17.12.0 and 17.13.0-Preview 1.0 but I have the same problem with the memory.
Then I went back and installed VS 17.10.6 again and the problem disappeared.
Any ideas?

**Comment by sbwalker** [comment]
I have noticed that when running Oqtane in the Visual Studio debugger the memory allocation is quite high and it increases as you navigate around the application. This behavior is very different from the way Oqtane runs in production so it seems to be related to Visual Studio. In fact I experience the same behavior with any Blazor application in Visual Studio - not just Oqtane.

**Comment by beolafsen** [comment]
The problem here is that it only takes about 2 minutes from when I press RUN DEBUG until IIS Express Worker Process has allocated 26GB of memory. And in those 2 minutes, I haven't navigated or done anything else in the application. Only waited.

Since this is a problem that happened after upgrading VS 2022, I also think that it is a problem with VS. At the same time, I wonder if it could also be something with Oqtane since it only happens when my OqtaneLibrary.Server.dll is placed in the Oqtane.Server directory (even though I am not running my Oqtane version - only Oqtane Framwork). What is Oqtane doing with the DLLs that are in the BIN catalog?
I have reported this issue to VS Community - but without response.

**Comment by leigh-pointer** [comment]
Kestral runs faster!

**Comment by beolafsen** [comment]
Yes - but the result is the same regarding memory allocation.

![image](https://github.com/user-attachments/assets/859dfb3c-bb2c-4ac7-9538-b05696ba93e9)
![image](https://github.com/user-attachments/assets/f54c1f34-d74b-4f41-a556-c094f1d3b007)

This is how it is when I use VS version 17-10-6
![image](https://github.com/user-attachments/assets/a9852a2b-34bb-422d-b844-666439b183ca)

**Comment by sbwalker** [comment]
Oqtane is a modular framework which means it needs to load assemblies which are part of the Oqtane environment into the app domain during startup. It uses a file naming convention to determine which assemblies in the /bin need to be loaded. If an assembly contains the term  "oqtane" then it is loaded:

```
        public static bool IsOqtaneAssembly(this FileInfo fileInfo)
        {
            return (fileInfo.Name.Contains("oqtane", StringComparison.OrdinalIgnoreCase));
        }
```

Oqtane has followed this approach since version 1.0, as it is simple and performs very well (ie. it targets a subset of assemblies and does not need to use reflection or other expensive operations to inspect the assemblies).

So if you have a custom assembly named  OqtaneLibrary.Server.dll then it will be loaded during startup. And if this assembly is very large then it will consume a lot of RAM. If this assembly should not be loaded then you would want to give it a different name. Generally the recommended approach is to name assemblies so that they reflect their owner and purpose ie. YourCompany.Library.Server.dll

**Comment by beolafsen** [comment]
Is there any restrictions on the namespace names?

ex: @namespace OqtaneLibrary.AuditListe

**Comment by sbwalker** [comment]
Assemblies are loaded based on the file name convention I explained above - not namespace.

Note that Oqtane also loads satellite assemblies (ie. *.resources.dll) if they exist. Does your custom module have large satellite assemblies?

This problem seems to be specific to your environment, as I am unable to reproduce it locally. So at this point there is nothing in Oqtane which could be "fixed" to resolve your problem.

**Comment by sbwalker** [comment]
Also note that if the assembly being loaded has dependencies, Oqtane will load them as well (assuming they exist in the /bin folder). So if your custom library has large dependencies then they could consume a lot of RAM.

**Comment by beolafsen** [comment]
Now - I don't have large DLL's.
OK - thank you for looking into it.

Best regards
Bjørn-Even Olafsen


man. 18. nov. 2024 kl. 14:29 skrev Shaun Walker ***@***.***>:

**Comment by beolafsen** [comment]
Just to be sure about the naming of assemblies.

My Solution looks like this:
![image](https://github.com/user-attachments/assets/ba4ad654-25a2-4a02-be25-2513b05483f8)
(yellow is the Framwork solution and green is my client, server and shared project)

When I compile this soulution - the Client, Server and Shared (marked with green) get the assembly names:
OqtaneLibrary.Client.Oqtane.dll
OqtaneLibrary.Shared.Oqtane.dll
OqtaneLibrary.Server.Oqtane.dll
Is this wrong. Should it be called someting like MyCompany.Client.dll or should it be MyCompany.Client.Oqtane.dll?
I tried with MyCompany.Client.dll - but then I don't see any Modules in my Module list. 
![image](https://github.com/user-attachments/assets/1035d538-6a6b-4037-a979-74920ee855ba)

so I guess the right name is : MyCompany.xxxxxx.Oqtane.dll

**Comment by sbwalker** [comment]
I would strongly recommend that you create a module using the Create Module capability within Module Management as it includes all of the required files and configuration. The UI will prompt you for the Organization Name and Module Name (and the validation rules actually prevent these values from containing the term "oqtane"). The default namespace created for the module will be OrganizationName.Module.ModuleName (although the ".Module" middle segment is not actually required). The project files which are scaffolded will append a ".oqtane" to the assembly name. This is required for the Oqtane framework to be able to identify the assembly files during startup so they will be loaded into the app domain. 

Your solution screen shot above appears to have some issues. This is what a standard Oqtane module solution should look like:

![image](https://github.com/user-attachments/assets/1b983030-0d81-4ebe-ab65-acbf1643f6d1)

You should not have the Oqtane.Client or Oqtane.Shared projects linked to your module solution. You should reference Oqtane.Server, Oqtane.Client and Oqtane.Shared using Nuget package references within the module's project files. Oqtane.Server is included in the module solution as a Startup Project to allow for F5 debugging within Visual Studio - but is technically not necessary.

**Comment by sbwalker** [comment]
@beolafsen can you explain why your module solution has references to the Oqtane.Client and Oqtane.Shared projects?

**Comment by beolafsen** [comment]
Hi!

I don't need to have the projects Oqtane.Client and Oqtane.Shared added to
my solution, but I find it easy to have them there. Then I can easily debug
Oqtane Framwork and see how e.g. some of the functions you use work. I also
then get quick access to Framwork source code and can look at how you have
solved the different modules, infrastructure,  etc.

Best regards
Bjørn-Even Olafsen


ons. 20. nov. 2024 kl. 15:38 skrev Shaun Walker ***@***.***>:

**Comment by sbwalker** [comment]
Ok, my concern is that this configuration is somehow causing Visual Studio to consume so much RAM on your machine. I cannot reproduce the problem so I am tempted to close this issue, but I would like to understand why your environment is is having this problem.

**Comment by beolafsen** [comment]
Thanks - I have been running this configuration since I started with Oqtane
- approx. 2 years ago without any kind of problems.

I'm reasonably sure that this has nothing to do with Oqtane Framwork so you
can close the case.

The solution works fine as long as I'm running with VS 17.10.6, but newer
versions give problems.

As mentioned earlier, the memory problem also occurs when I open the
OqtaneFramwork solution and there is an OqtaneLibrary.Server.Oqtane.dll in
the bin directory. If there is no OqtaneLibrary.Server.dll in the bin
directory then there is no problem with memory during debug of
Oqtane Framwork

When I look at the memory allocation in task management, it looks like
there is a lot of activity going on in the application even if I don't
press a single button. I only start the Oqtane Framwork application in
debug mode and then I don't touch it anymore.
To check if oqtane framwork is working with my server dll, I have set up
many stop addresses around the application, but nothing happens after the
application is launched.

Today I have made a copy of my solution and then I have gone in and deleted
file by file in my server project. For each file I delete, I have run a
compilation of my solution to create a new server.dll and then I have
started the oqtane framework in debug-mode to see if it still allocates a
lot of memory. So now I've found some routines in a controller that seem to
be the reason for the memory allocation. I can't understand that there is
any problem with these routines so I think there is a problem with VS. I
will continue to test this tomorrow and possibly remove the routines that
are the cause of this problem.

Ex: of a routine that seam to give me memory allocation problem - I don't
get any compile error on it.

Thank you for helping.

Best regards.
Bjørn-Even Olafsen




ons. 20. nov. 2024 kl. 16:29 skrev Shaun Walker ***@***.***>:

**Comment by beolafsen** [comment]
@Leigh Pointer OK - Thanks.

Best regards
Bjørn-Even Olafsen


ons. 20. nov. 2024 kl. 17:01 skrev Leigh Pointer ***@***.***>:

**Comment by beolafsen** [comment]
I changed a metode interface from

`    public async Task<IEnumerable<T>> GetAllEntities(string siteid, string moduleid, string include = null, string filterstring = null, Expression<Func<T, bool>> filter = null)
`
to

`    public async Task<IEnumerable<T>> GetAllEntities(string siteid, string moduleid,  string include = null, string filterstring = null)
`
and now the memory allocation is "normal".
