### ISSUE TITLE
[BUG] edit page permission will throw exception

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4872]
### Oqtane Info

Version - dev branch
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
edit page permission will throw exception.
![image](https://github.com/user-attachments/assets/4b246b24-5fe1-4bb6-9d9f-7c8184070ba5)

### Expected Behavior
edit page permission should save without any error.

### Steps To Reproduce
1. create a new page.
2. change to permissions tab, make some changes in the grid.
3. click save button.

**Comment by sbwalker** [comment]
The is resolved by rolling back #4871 and #4828
