### ISSUE TITLE
[BUG] JWT Authentication broken after 5.2.2 SecurityStamp changes

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#4885]
### Oqtane Info

Version - 5.2.2 to 6.0.0
Render Mode - Interactive & Static
Interactivity - Server
Database - SQL Server

### Describe the bug
Cannot use JWT bearer token for authentication.  Returned user is always null.  Issue started with addition of SecurityStamp in version 5.2.2.

### Expected Behavior
Should be able to issue JWT bearer token and use for API authentication.

### Steps To Reproduce
- Perform Fresh install
- Go to User Management > Settings > Token Settings
- Set "Issuer" value & save
- Select "Create Token"

Use created token from external application (Postman for easy testing).  If running in debugger, you will see exception at line 71 of JwtMiddleware.cs.   Problem is line 61/62 always return null for user.  External reply is always a 200 response.

### Anything else?
I created fresh installs of 5.2.0, 5.2.1, 5.2.2, 5.2.3, 5.2.4 & 6.0.0.  This functionality works fine for 5.2.0 & 5.2.1, but fails in all versions from 5.2.2 and on.

![image](https://github.com/user-attachments/assets/ca45462f-3ff8-45e0-9d64-eed43c7988ef)

![image](https://github.com/user-attachments/assets/4fa2e1a9-6e05-4e59-84ae-568a99d65a98)

**Comment by sbwalker** [comment]
I will investigate this further

**Comment by W6HBR** [comment]
@sbwalker  I can confirm that your suggested solution does resolve the issue. Ref:  https://github.com/oqtane/oqtane.framework/pull/4892


@zyhfish https://github.com/oqtane/oqtane.framework/issues/4885 could be resolved by simply changing this 1 line:

var user = _users.GetUser(userid, alias.SiteId); // cached

to

var user = _users.GetUser(int.Parse(userid), alias.SiteId); // cached
