### ISSUE TITLE
[BUG] Unexpected ModuleDefinition ID Changes

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4891]
### Oqtane Info

Version - 6.0.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Unexpected ModuleDefinition ID Changes
I've observed an intermittent issue where the ModuleDefinition ID is changing unexpectedly. This occurs after saving ModuleDefinition settings. The system continues to retrieve the correct data for a period, but eventually fails to do so. Upon inspection of the database, it's evident that the ModuleDefinition ID has been altered.

### Expected Behavior
The ModuleDefinition ID should maintain its original value consistently throughout the lifecycle of the module.

### Steps To Reproduce
While the exact reproduction steps are challenging to pinpoint, I suspect the issue is related to the loading process of installed modules into the Oqtane framework.

### Anything else?
This bug presents significant challenges for module persistence and data integrity. It may be linked to how the framework manages module definitions during runtime or database operations. Further investigation into the module loading and saving processes could provide valuable insights into the root cause of this issue.

**Comment by sbwalker** [comment]
Note that during startup, Oqtane reconciles the list of modules which are installed in the /bin folder with the list of modules which are stored in the database. So if you have deleted/uninstalled a module and then restarted the application the ModuleDefinition will be removed from the database - and then if you re-install the module a new ModuleDefinition will be added to the database (with a different ModuleDefinitionId). Is it possible that this is what you are seeing in your environment?

**Comment by leigh-pointer** [comment]
@sbwalker yes that is what is happening, but what I have seen is on Install of the framework my ModuleDefinitioId's started at 1 upto 33, Then, for some reason 1-33 was deleted and recreated 34 - 66.  I issue is, if the moduledefinition is recreatd and has settings then the settings EntityId needs to be modified when , or we can end up with orphaned data.

**Comment by sbwalker** [comment]
A ModuleDefinition record should never be deleted from the database unless the assembly was removed from the /bin. Can you please provide more information on how to reproduce? Was this in an environment where there was manual manipulation of assets outside of the framework?

**Comment by leigh-pointer** [comment]
@sbwalker Ok, The Oqtane.Server bin folder  was not maniputlated but what I had done is deleted the bin and obj foldered from all projects.  Maybe that had something to do with it?

**Comment by sbwalker** [comment]
Yes, if assemblies were manually deleted it would leave the environment in an "unsupported" state which could lead to unexpected results.
