### ISSUE TITLE
[BUG] Marketplace fails to show details on non-modules

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4912]
### Describe the bug

When you apply any non-module filter the UI fails to show details:

![image](https://github.com/user-attachments/assets/fb048317-b758-49a7-b34b-0006fba7c77f)

![image](https://github.com/user-attachments/assets/448671e0-281b-447a-8a6f-882b92c39f0f)

**Comment by sbwalker** [comment]
Thank you for reporting this issue... I will investigate

**Comment by sbwalker** [comment]
This is fixed now
