### ISSUE TITLE
[ENH] Parameter field in ModuleInfo whitch I can use

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4916]
### Oqtane Info

Assumes that most of the fields defined in ModuleDefinition are in use by Oqtane Framework. Are there any of the fields that can be used by me to set a parameter associated with the module? If this does not exist -  would it be possible to have a field created for that purpose?

Best regardes
BEO

**Comment by leigh-pointer** [comment]
@beolafsen You are able to save settings for a ModuleDefinition.

`[Inject] public ISettingService SettingService { get; set; }`

`Dictionary<string, string> settings = await SettingService.GetModuleDefinitionSettingsAsync(ModuleState.ModuleDefinition.ModuleDefinitionId);`

`SettingService.SetSetting(settings, "YourSettingName", "YourSettingValue");`

`await SettingService.UpdateModuleDefinitionSettingsAsync(settings, ModuleState.ModuleDefinition.ModuleDefinitionId);`

Hope that helps?
