### ISSUE TITLE
[BUG] Viewing non-host user roles hangs when loading (issue with #4881)

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#4946]
### Oqtane Info

Version - 6.0.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server & SQLite

### Describe the bug
Unable to display/edit user roles from User Manager

### Expected Behavior
User Manager edit screen should load and allow viewing/editing of users roles.

### Steps To Reproduce
- On a fresh install, add a new (non-host) user. After saving, select "Roles" for the user to assign new role.  Interface will hang at "Loading..."
![image](https://github.com/user-attachments/assets/b2debda7-03a2-41cb-9185-26f9d3b75b5f)

### Anything else?
Reverting changes of #4881 resolves issue.

**Comment by enfJoao** [comment]
This happens on my install at "User management" => Roles and at "Role Management" => Users

**Comment by sbwalker** [comment]
@enfJoao the work around currently is that you can use Role Management to add a User to Role (instead of using User Management to add a Role to a User)

**Comment by enfJoao** [comment]
@sbwalker As stated, to me this happens in both menus. Unless I'm missing something. Page permissions still work, so I can assign individual user permissions. Not a critical issue.
