### ISSUE TITLE
[BUG] User unable to login after changing password via self-service reset

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#4957]
### Oqtane Info

Version - 6.0.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
User unable to login after changing password via self-service reset (aka "Forgot Password").  The password is properly updated, but when the user attempts to login, it appears to be a successful login, but the "Login" prompt does not change to "Logout" and no additional protected pages/navigation appear for the user.

### Expected Behavior
User should be able to change password and then immediately login.

### Steps To Reproduce
Fresh install, create new (non-host) user.  Perform self-service password reset via Forgot Password.  Password does get changed, but user unable to login.

### Anything else?
Recycling the Oqtane application will allow the user to successfully login with the newly set password.  Also, at some future period, the user can successfully login (possibly after the app does an app pool recycle??).  Since it can be resolved with an app restart, it seems like possibly some type of caching issue.

**Comment by sbwalker** [comment]
@W6HBR thank you for reporting. You were correct that it was missing some logic to refresh the user object in the cache.
