### ISSUE TITLE
[BUG] Get Roles from user (that is not logged in) gives Forbidden

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4958]
### Oqtane Info

Version - 6.0.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
I am logged in as HOST. Try to see Roles added to the different users but only possible to see roles from the user that is logged in - in my case HOST. 
![image](https://github.com/user-attachments/assets/543e3d91-5873-401e-8276-369a9a39f50d)

The other user gives this message:
![image](https://github.com/user-attachments/assets/49404f0a-7f1f-4723-b9eb-b4f1ce6f4b4e)

Event log:

![image](https://github.com/user-attachments/assets/f2a823a7-f6b5-4d18-a295-f148d029553e)

![image](https://github.com/user-attachments/assets/40ce61f4-9143-4af8-add0-6446f3c318d6)

**Comment by leigh-pointer** [comment]
@beolafsen this is fixed in PR #4946
