### ISSUE TITLE
Recommended Name Changes

### ISSUE THREAD

**Issue by mitchelsellers** [oqtane/oqtane.framework#5]
Based on the terms used in other platforms, I would suggest a rename of the Skins concept to be Theme.  This more closely aligns to other tools, which will help with understanding/adoptions.

I would gladly submit a PR for this, but would want to be sure it was desired before I do

**Comment by sbwalker** [comment]
I agree that Theme is a more industry standard terminology. If you submit a pull request for this item I will definitely accept it.
