### ISSUE TITLE
Moving Auth to IdentityServer

### ISSUE THREAD

**Issue by yehia2amer** [oqtane/oqtane.framework#504]
Is there any plans to Add [IdentityServer ](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio) Support ?

I Think this would give us a lot of benefits:
1) Separation of concerns for the whole Authorization & Authentication part to Authorization Server.
2) OpenID Connect has become the leading standard for single sign-on and identity provision on the Internet using simple JSON-based identity tokens (JWT), delivered via OAuth 2.0 flows designed for web, browser-based and native / mobile applications.
3) Easy integration with any OpenIdConnect systems & Social Logins and even Enterprise SSO.

**Comment by erangell** [comment]
I am also interested in support for Azure AD authentication for use in a corporate intranet environment with the database on Azure SQL Server.

**Comment by sbwalker** [comment]
It is on the roadmap for V.Next

**Comment by yehia2amer** [comment]
Great to hear that !

**Comment by bakes82** [comment]
Is there a road map with date/qtr estimates?  Is v.net targeted for like Q4 '20 or Q1 '21?  We also need the ADFS support for login.

**Comment by sbwalker** [comment]
closing as IdentityServer will no longer be available under a compatible open source license in .NET 5: https://leastprivilege.com/2020/10/01/the-future-of-identityserver/

**Comment by vzdesic** [comment]
I know that some companies will still rely on Identity Server 4 for some time, which will stay free and open source.
Regarding that, does it make sense to add support for version 4? If yes, I am ready to help and contribute.

**Comment by sbwalker** [comment]
Including a dependency on ID4 does not align with a number of principles in Oqtane's philosophy https://www.oqtane.org/Resources/Blog/PostId/538/oqtane-philosophy. Currently multiple database support is the major feature on the roadmap for V2.1... I would expect alternate authentication to be a V2.2 enhancement.

**Comment by hishamco** [comment]
Also we could provide an example to support another AUTH provider in case we don't have alternative one, while our infrastructure is customizable notthing impossible

**Comment by vzdesic** [comment]
@hishamco Do you still plan to provide mentioned example or focus is completely on the 2.2 release?
