### ISSUE TITLE
Tooltips verification

### ISSUE THREAD

**Issue by svreic** [oqtane/oqtane.framework#512]
Currently tooltips are not consistent.

Some are capitalizing every word and others are only capitalizing the first word in the sentence. Tooltips should be using proper English format.

It is also not entirely sure if all the tooltips are accurate in terms of describing the purpose of the field they related to.

**Comment by jimspillane** [comment]
This might be good to include in the V.Next Static Localization discussion.

**Comment by sbwalker** [comment]
Agreed we can revisit with Localization
