### ISSUE TITLE
Discussion: Http Status code patterns

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#520]
Going forward, how should we handle http status codes throughout the framework? I see that we are currently using the below:
```
 HttpContext.Response.StatusCode = 401;
```
Would it be better to use:

```
 HttpContext.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
```

Just documenting things for better on-boarding.

**Comment by jimspillane** [comment]
I like the readability of the second one.

 `HttpContext.Response.StatusCode = (int)HttpStatusCode.Unauthorized;`

**Comment by mikecasas** [comment]
I agree @jimspillane, I read @sbwalker 's comment in gitter after posting this issue about focusing on stability, but something like this could be a good 'Help Wanted' or 'Good First Issue' for those wanting to help.
