### ISSUE TITLE
Developer Module Creator pluralisation  

### ISSUE THREAD

**Issue by stephanlotter** [oqtane/oqtane.framework#526]
The Module generation logic needs to be improved to deal with some edge cases. I have a scenario where I want to create a module that provides Inventory enquiry features.

The module name I want to use is **InventoryEnquiry**. The issue is that the default pluralisation leads to **InventoryEnquirys** when I expected it to be **InventoryEnquiries**.

If it's fine by you I'm happy to make the necessary changes to the code and submit a pull request.

I would modify it to instead of

```c#
moduleDefinition.ServerManagerType = moduleDefinition.Owner + "." + moduleDefinition.Name + "s.Manager." + moduleDefinition.Name + "Manager, " + moduleDefinition.Owner + "." + moduleDefinition.Name + "s.Server.Oqtane";
```

do this

```c#
moduleDefinition.ServerManagerType = moduleDefinition.Owner + "." + Pluralize(moduleDefinition.Name) + ".Manager." + moduleDefinition.Name + "Manager, " + moduleDefinition.Owner + "." + Pluralize(moduleDefinition.Name) + ".Server.Oqtane";
```

and for 

```c#
filePath = filePath.Replace("[Module]", moduleDefinition.Name);
```

something like

```c#
var regex = new System.Text.RegularExpressions.Regex(@"\[Module\]s");
filePath = regex.Replace(filePath, Pluralize(moduleDefinition.Name))
```

The Pluralize function then returns the correct plural of module name.

**Comment by sbwalker** [comment]
There is a LOT more involved in making this change than what is described above. Almost every template file would need to be renamed as well. I would not consider this to be high priority in relation to the other items at this point, but we can add it to the backlog of enhancements,

**Comment by stephanlotter** [comment]
After posting this issue I went ahead and implemented the change. I did not have to change the template solution. After making the chance I was able to create a module and compile and use it.

Have a look at this commit.

https://github.com/stephanlotter/oqtane.framework/commit/a0775fbca3bd1d04e115f4cbb58e4ef28d067c54

**Comment by sbwalker** [comment]
Clever solution. I guess my only comment is that this only covers the edge case of plural English nouns ending in -y. What about other plural nouns? Nouns that end in -ch, -x, -s, -sh add '-es' to the end of the word. Most nouns ending in -o preceded by a consonant also form their plurals by adding '-es'. And what about non-English?

**Comment by stephanlotter** [comment]
I modified the Pluralization class to use [Humanizer.Pluralize()](https://github.com/Humanizr/Humanizer#pluralize) as suggested by @medboz.

See this commit. https://github.com/stephanlotter/oqtane.framework/commit/6dfcb366186d1d904d6eace67b22f624f6f5f999

**Comment by sbwalker** [comment]
I would recommend that you read the Oqtane philosophy as we have established a set of high level guidelines that we are trying to follow in this project:  https://www.oqtane.org/Resources/Blog/PostId/538/oqtane-philosophy. You will notice that we have a specific policy about taking dependencies on third party libraries. So although adding a dependency on Humanizer to accommodate this edge case may solve the problem, it would not be an approved approach. 

If pluralization is a high priority issue perhaps the best solution to accommodate all use cases/languages is a solution which simply uses whatever name is provided by the user without modification/pluralization.

**Comment by stephanlotter** [comment]
Thanks for the link. I read the Oqtane philosophy and it makes perfect sense. I guess then the last part of you comment makes sense too. Pluralisation needs to be remove all together from the Module creator context.

**Comment by PoisnFang** [comment]
I would agree on this. I think it'd be best to remove the pluratisation all together.
