### ISSUE TITLE
Unable to Select Inherited Layouts

### ISSUE THREAD

**Issue by ahoefling** [oqtane/oqtane.framework#527]
**Scenario**
On a page that uses an inherited site theme, I would like to update the layout to use one of the available layouts

**Steps**
1. Install oqtane v1.0.0
2. Log in as host user
3. (in my case, but this applies to all pages) Navigate to the 'Private' Page
4. Tap the gear icon to open the control panel
5. Under 'Page Management' tap the edit button
6. At the bottom of the 'Page Management' window open the Appearance section
7. In the 'Layout' dropdown select something other than '<inherit from Site>'

**Expected Behavior**
* All of the layouts available for a theme should be present

**Actual Behavior**
* There is only 1 option and it is the default '<inherit from Site>'

**Workaround**
If you update the theme to use the same theme that is in use by the entire site, then the 'Layout' dropdown allows you to select from the available layouts. So if I need this feature for now I can just manually update the theme on the pages I am concerned with

**Screenshot**
Here is a screenshot of the problem
![image](https://user-images.githubusercontent.com/17751436/82667885-b5ad6d00-9c06-11ea-8965-4c9afdf7d0bf.png)

**Notes**
I am not sure if this behavior is as designed, but appears to me that the UX should allow the user select layout when inheriting their theme on each page.

**Comment by mikecasas** [comment]
A better UI may be needed, but if you select the Blazor theme, there are no layouts, so the dropdown is basically empty. The Oqtane theme has two layouts, so when you select that theme the dropdown will be populated.

**Comment by ahoefling** [comment]
This particular page was using the inherited (oqtane) theme, I would expect the same layout options to be available as if I explicitly selected the Oqtane theme.

Maybe I have a misunderstanding on how this is supposed to work with inherited vs selecting themes on the page.

**Comment by sbwalker** [comment]
What Andrew is suggesting makes sense however the complication is if someone sets the Layout at the Page level and then goes into Site Settings and changes the Theme at the Site level - the Layout would no longer be compatible. In order to deal with this, the framework could spin through the Pages in the Site and clear the Layout setting - or it could detect that the Layout is incompatible when displaying the Page and ignore it. Either way, it is more involved than it appears on the surface to resolve it.

**Comment by mikecasas** [comment]
Yes, I was just thinking of hiding the dropdown, when it was empty. Just a little Ui help for users.

**Comment by thabaum** [comment]
I like what @mikecasas suggesting.  We have a lot of UX for the dashboard to work on this is one thing I think would work for a simple solution is hiding if there are no options to set for a lot of the dashboard items if not all so things only appear as needed to help cleanup the UX. 

Of coarse a complete new component can be created to handle managing themes that can show examples and such of the themes with images along with editors.  Simple fixes for now keeping existing interface until a few ideas and proposals are created for different moving parts here like this one as an example managing themes.

For v1 what Mike is suggesting should work to help clear up confusion in the current UX.

**Comment by sbwalker** [comment]
Some of these UX issues were addressed in recent versions
