### ISSUE TITLE
Unable to Change Page Theme

### ISSUE THREAD

**Issue by ahoefling** [oqtane/oqtane.framework#528]
**Scenario**
While in Page Management attempt changing the page theme

**Steps**
1. Install oqtane v1.0.0
2. Log in as host user
3. (in my case, but this applies to all pages) Navigate to the 'Private' Page
4. Tap the gear icon to open the control panel
5. Under 'Page Management' tap the edit button
6. At the bottom of the 'Page Management' window open the Appearance section
7. In the theme dropdown, select a different option other than `<inherit from Site>`

**Expected Behavior**
* The theme for the particular page should update

**Actual Behavior**
* An error appears at the top of the page management popup

**Logs**
Exception
```
Error Saving Page null Object reference not set to an instance of an object.
```
Stacktrace
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Modules.Admin.Pages.Edit.SavePage() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Admin\Pages\Edit.razor:line 470
```

**Screenshot**
![image](https://user-images.githubusercontent.com/17751436/82669056-b6df9980-9c08-11ea-9e2c-b4e43b7e195a.png)

**Notes**
I checked this in both 1.0.0 and the latest dev code. It does not appear to work in the 1.0.0 release but my local copy of Oqtane that I am using for development still works.

**Comment by mikecasas** [comment]
Are you just changing the Theme or are you also changing any other options? I was able to change the theme to the Blazor or Oqtane theme and there was no error.

**Comment by ahoefling** [comment]
I did this on a clean installation of 1.0.0 and I only tried changing the theme nothing else

**Comment by sbwalker** [comment]
This sounds like a problem specific to the 1.0 release package. Will need to investigate further.

**Comment by thabaum** [comment]
Are you sure you are running 1.0?  Are you downloading the source from the website? 

I tried reproducing on latest repo and downloading the source with no issues.

Can you try downloading the source package to a new folder and run the solution from there to see if the problem still persists.

Thank you.

**Comment by thabaum** [comment]
#537 is a similar issue maybe this is how the error is made.

Also email addresses can get saved as email and not me@mail.com as there is no form validation.  I think they all relate to the dashboard UX problems.

**Comment by ahoefling** [comment]
@thabaum 
> Are you sure you are running 1.0?

![image](https://user-images.githubusercontent.com/17751436/82905170-84e47500-9f31-11ea-917d-5c5c6e06bd48.png)

**Comment by ahoefling** [comment]
This morning I was looking at this again and noticed that the UI displays a generic error message but if you close the admin panel the page updates the theme correctly. Looks like something during the save routine is breaking, but still allowing the theme to change

**Comment by thabaum** [comment]
this needs investigated further.  When you delete a theme there is a bug as well I believe.  I will start changing, installing and deleting themes.

**Comment by sbwalker** [comment]
I believe this is fixed
