### ISSUE TITLE
Oqtane and Nuget

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#532]
Nuget is a package management system. It allows developers to download package references in the form of Nuget packages ( *.nupkg ) from a Nuget server and statically link them into your project. Nuget is only a development concern - it is not responsible for deployment of your application. 

Oqtane is a modular framework which relies on dynamic loading rather than static linking. It is intended to be used by developers as well as site administrators. One of its goals and unique characteristics is to simplify and automate the deployment of dynamic extensions into the framework at run-time.

In order to accomplish its goals, Oqtane utilizes Nuget for managing its extensions. Specifically it uses Nuget's package distribution capabilities, its *.nuspec manifest, and its *.nupkg package format. However it does not use the typical Package Management features in Visual Studio because it needs to avoid static linking. Oqtane also takes some liberties with the Nuget specification in order to support its run-time deployment requirements. Specifically it utilizes its own target folder concepts in order to determine how to deploy assets. It attempts to do this while still adhering as closely as possible to the standard Nuget specification so that the process still feels familiar to developers.

If we focus on the most simplistic aspects of the deployment requirements, there are essentially two locations which are important in Oqtane:

1. bin folder - This is where DLLs and PDBs need to be deployed so they are discoverable by Oqtane
2. wwwroot folder - This is where static assets such as images, stylesheets, script files need to be deployed. This is the standard location recommended by Microsoft for Razor Class Libraries when working with these types of assets. In order to support the modular requirements of Oqtane they need to be organized based on the extension type and name.

In practical terms:

\Oqtane.Server
..\bin ( maps to a specific location at run-time such as \bin\Debug\netcoreapp3.1 )
..\wwwroot
....\Modules
......\Module1 - static assets for Module1 ( can have additional subfolders )
......\Module2 - static assets for Module2 ( can have additional subfolders )
....\Themes
......\Theme1 - static assets for Theme1 ( can have additional subfolders )
......\Theme2 - static assets for Theme2 ( can have additional subfolders )

In order to make development intuitive, the approach for creating an external Oqtane extension attempts to mirror the core framework as closely as possible. For example if we focus on Module1 from above, the organization of the Module1 project would be:

\Module1.Server
..\bin
..\wwwroot
....\Modules
......\Module1 - static assets for Module1 ( can have additional subfolders )
 
When developing Module1 it must copy the assets from the respective folders above to the associated areas in the Oqtane core framework so that when you run the core framework it can find and load them. The current Module Creator templates automate this for you by including a command script Package\debug.cmd which is executed during Build in Debug mode.

So what about third party libraries? You can certainly use third party libraries in your Oqtane extensions. Third party libraries are comprised of DLLs, PDBs and possibly other static web assets. You can use standard Nuget to download a third party library into your Oqtane extension project. However you need to remember that the assets from any libraries which your Oqtane extension depends upon also need to be deployed to the Oqtane framework instance in order for it to function properly. So you will need to adjust the Package\debug.cmd file ( if using the Module Creator templates ) to include references to the third party library assets. This will include DLLs, PDBs and possibly additional folders which will need to be copied to the Oqtane framework. Please note that you will need to organize the third party library assets according to the folder structure of the deployed Oqtane framework. The easiest way to do this is locate the shared .nuget\packages folder on your system and copy the static assets for Library1 to a subfolder in the module's wwwroot folder:

\wwwroot
..\_content
....\Library1 - Library1's static assets

We have covered development but what about deployment? If you want to create a package which can be deployed to an instance of Oqtane at run-time you need to create a Nuget package. Again, the Module Creator templates automate this for you by including a nuspec file and command script called Package\release.cmd which is executed during Build in Release mode. If you look at the contents of an Oqtane *.nupkg package you will see that it contains the following "target" folders:

\lib - the location for deploying DLLs and PDBs ( this is part of the Nuget standard )
\wwwroot - the location for deploying static assets ( this is a custom location used by Oqtane )

Note that if you are using third party libraries in your extension, you will need to ensure that they are included in your Nuget package. You will need to adjust the Package\*.nupec file to include references to all third party library assets. This will include DLLs, PDBs and possibly additional folders for static assets which will need to be deployed to the Oqtane framework. 

So in my *.nuspec I will need to include the DLL:

    <file src="..\Server\bin\Release\netcoreapp3.1\Library1.dll" target="lib" /> 

And I will need to include the static assets from the shared Nuget location on my system. If I followed the recommendation above and copied the shared .nuget\packages folder on my system to a subfolder in my module's wwwroot folder then the static assets will be picked up automatically by the following line in the *.nuspec file:

    <file src="..\wwwroot\**\*.*" target="wwwroot" /> 

The *.nupkg package can be deployed through a variety of ways - it can be uploaded through the user interface, it can be manually copied to the Oqtane.Server\wwwroot\Modules folder, or it can be downloaded from Nuget.org ( if the creator of the package uploaded it to Nuget.org previously ). In all of these cases, simply restarting the Oqtane application will allow it to find the package, extract its contents to the proper locations, and perform any necessary installation steps such as executing scripts.

Overall the process should be seamless. The biggest challenge for most developers is understanding that Oqtane is a dynamic system - not a traditional static web application - and because of this it leverages Nuget in a slightly different manner than you are used to.

**Comment by sbwalker** [comment]
One item which needs to be addressed in the current model is related to external modules. Currently the Module Creator templates include references in the project files to Oqtane framework DLLs:

  <ItemGroup>
    <Reference Include="Oqtane.Client">
      <HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\netcoreapp3.1\Oqtane.Client.dll</HintPath>
    </Reference>
    <Reference Include="Oqtane.Shared">
      <HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\netcoreapp3.1\Oqtane.Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

These references should be replaced with a package reference to the Oqtane framework:

  <ItemGroup>
    <PackageReference Include="Oqtane.Framework" Version="1.0.0" />
  </ItemGroup>

However currently you are only able to add a package reference to the external module Server project. If you try to add the package reference to the Client or Shared projects, it complains because .NET Framework versions do not match. Note that Oqtane framework DLLs are targeted at different .NET Frameworks:

Oqtane.Client.dll = netstandard2.1
Oqtane.Server.dll = netcoreapp3.1
Oqtane.Shared.dll = netstandard2.1

The problem is most likely in the Nuspec file used to package the framework. However it is unclear to me if the DLLs should identified in a generic lib:

    <file src="..\Oqtane.Client\bin\Release\netstandard2.1\Oqtane.Client.dll" target="lib" /> 
    <file src="..\Oqtane.Server\bin\Release\netcoreapp3.1\Oqtane.Server.dll" target="lib" /> 
    <file src="..\Oqtane.Shared\bin\Release\netstandard2.1\Oqtane.Shared.dll" target="lib" /> 

or with the specific framework they belong to:

    <file src="..\Oqtane.Client\bin\Release\netstandard2.1\Oqtane.Client.dll" target="lib\netstandard2.1" /> 
    <file src="..\Oqtane.Server\bin\Release\netcoreapp3.1\Oqtane.Server.dll" target="lib\netcoreapp3.1" /> 
    <file src="..\Oqtane.Shared\bin\Release\netstandard2.1\Oqtane.Shared.dll" target="lib\netstandard2.1" /> 

or if there needs to be 2 separate framework packages created - one for the netcoreapp3.1 DLL and another for the netstandard2.1 DLLs.

If anyone has experience in this area, it would be helpful.

**Comment by thabaum** [comment]
Very cool, thank you for taking the time to explain this.  I am looking to create a fun practice module pulling libraries from different places this will help a lot!

**Comment by mikecasas** [comment]
Pardon the ignorance, but if i place a dll (foo.dll) in the Oqtane.Server bin folder, and then when the below is called:

``` var assemblies =AppDomain.CurrentDomain.GetAssemblies();```

should that dll be included in the list?

**Comment by sbwalker** [comment]
The answer is No. I suggest you read this blog: https://www.oqtane.org/Resources/Blog/PostId/523/assembly-loading-in-blazor-and-net-core Oqtane has to do a lot of magic to deal with assembly loading.

**Comment by sbwalker** [comment]
The "magic" I am referring to is actually fairly simple... if DLL has the word "oqtane" somewhere in its name, the framework will load it into the app domain. If that DLL has static dependencies on other assemblies ( ie. foo.dll ) then it will load them as well into the app domain.

**Comment by mikecasas** [comment]
I get it to work by just hard coding the assembly load in the ```LoadAssemblies``` method. I will look into the static dependencies issue.

**Comment by iJungleboy** [comment]
I've been messing around with this a bit. As a more JS/Web developer coming from DNN, it doesn't feel seamless yet. Here are my concerns as of now:

1. Zips just felt much simpler, and also feel like I can quickly open them to see what's inside. This is valuable if someone sends me something and I'm reasonably critical to not just dump it on my system. 
1. Seing nugets listed from nuget.org just because they have been published feels like an uncontrolled state of "suggested" packages. Basically any attacker could just post a few packages there and wait for some greenhorn to just try it out. I'm sure such an attack wouldn't be noticed for months. 
1. I'm working on a more complex theme containing various common features like package.json, node_modules and more. Of course when I package it, some things should be included and others not. I'm sure I'll end up figuring it out, but it does feel like a learning curve just to get this right.

**Comment by sbwalker** [comment]
@iJungleboy your points are all fair assessments. Although Oqtane uses a lot of the "concepts" from DNN it is obviously a totally different framework in its approach and implementation. The most significant difference is that Oqtane is not intended to be a CMS - it is intended to be a modular application framework ( which is what DNN was during its most impactful years from 2003-2008 ). And of course Oqtane is version 1.0 so there are plenty of kinks to work through.
