### ISSUE TITLE
Change JavaScript namespace from interop to Oqtane

### ISSUE THREAD

**Issue by jimspillane** [oqtane/oqtane.framework#533]
Currently, the JavaScript namespace for the interop functions is _interop_. I propose renaming the namespace to _Oqtane_ which will help reduce collisions by using the brand name.

![image](https://user-images.githubusercontent.com/15007083/82744710-35902000-9d4a-11ea-967b-e917d0ed20e9.png)

The current functions can be relocated to a namespace like Oqtane.Core or Octane.System.

Additionally, guidelines could be established for modules to be structured like the following to keep them separated:
Oqtane.modules.Module1
Oqtane.modules.Module2
Oqtane.modules.Quill

Thoughts?

**Comment by sbwalker** [comment]
Funny... I was just reading this doc: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1 and it appears that some aspects of the JS Interop implementation have changed since I originally implemented it in Oqtane. In order to avoid JS Interop conflicts we should definitely require that components use their own Scope - this is essential in modular architecture. In fact I would say that the fact that the Quill interop and Core interop share the same Scope is actually a bug - they should have a different scope.

**Comment by jimspillane** [comment]
I added a change in #516  to temporarily address the issue with the Core and Quill.  But we should agree on a namespace structure for the future.

**Comment by sbwalker** [comment]
My feeling is that modules and themes should use their namespace as the scope for consistency. For example if a module's namespace was MyCompany.MyModule then the scope would be MyCompany.MyModule as well. The core framwork would use "Oqtane.Interop".

**Comment by sbwalker** [comment]
I am going to remove the [Enhancement] tag from the title as I actually think this is a bug and the changes you made in #516 should be resolved using the approach described above.

**Comment by jimspillane** [comment]
I like that structure which is consistent with the module creator.  Plus it does not pollute or risk clobbering the Oqtane namespace.

Do you think the same can be done with the Oqtane namespace by using _Oqtane.RichTextEditor_ rather than _Oqtane.Interop.RichTextEditor_?

This will help keep the number of namespace levels to a minimum. The invocation would look like the following:

```
public Task CreateEditor(
            ElementReference quillElement,
            ElementReference toolbar,
            bool readOnly,
            string placeholder,
            string theme,
            string debugLevel)
        {
            try
            {
                var response =
                _jsRuntime.InvokeAsync<object>(
                    "Oqtane.RichTextEditor.createQuill",
                    quillElement, toolbar, readOnly,
                    placeholder, theme, debugLevel);
                return Task.CompletedTask;
            }
            catch
            {
                return Task.CompletedTask;
            }
        }
```

**Comment by sbwalker** [comment]
Absolutely. Do you want to make this change?

**Comment by sbwalker** [comment]
You would need to back out the change you made in #516

**Comment by jimspillane** [comment]
I will make the modifications today.  #516 will be impacted, so I will roll all the changes into a new PR and close #516
