### ISSUE TITLE
Idea: Pages and modules should be set hidden / admin only

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#543]
I'm thinking about possibility to simply hide elements / set them admin only. I know than I can do it with permissions, but this can be lot of clicks instead of one. Especially with complex permission settings.

Real use cases:  
- I want to prepare some action for users which have to be shown for limited time. 
- Page is in construction and I want to publish when it's done
- Page content is wrong and I want to quickly take it down for repair

**Comment by sbwalker** [comment]
I am not sure if I am understanding correctly... but in DNN when a page was first created, by default it did not provide All Users with View permission - so this meant that the page was hidden from everyone except the Administrator. The Administrator could then add modules to the page, add content to the modules, etc... without the risk of anyone viewing the page. There was an option in the Control Panel for Publish Page. If the Administrator selected this option the system would grant View permissions to All Users for the Page ( and modules on the page ). This would make the page and content visible. The Publish Page option in the Control Panel would then toggle and become an Unpublish Page option. And if the Administrator selected this option it would remove the View permission for All Users for the Page. Essentially this provided a one-click publish and unpublish capability. A similar option existed on the Module Actions dropdown menu for Publish Module/Unpublish Module - which essentially did the same thing - added or removed View permission for All Users for that specific module. Basically these options used the standard security model but simplified the user experience.

**Comment by chlupac** [comment]
Yes i mean this functionality

**Comment by sbwalker** [comment]
This was implemented last week
