### ISSUE TITLE
Error when installing module

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#550]
When trying to install the Blog module in my Azure instance, the module installation crashes. 

This error message is slightly different then the one referenced in #546.

![module](https://user-images.githubusercontent.com/11261164/83128761-dd3e8280-a0a9-11ea-973c-a72e2fe44aec.PNG)

**Comment by sbwalker** [comment]
When modules or themes are installed, the server application must be restarted so that it can complete the installation and load them into the appdomain. The errors in your browser console are related to the server restarting. What is the specific problem you are reporting?

**Comment by sbwalker** [comment]
#546 has been fixed in #548

**Comment by sbwalker** [comment]
@mikecasas did you see the standard Blazor Server error message when this happened: "Could not reconnect to the server. Reload the page to restore functionality"?

**Comment by mikecasas** [comment]
@sbwalker OK, I get it now, but yes then page just hangs - sits there and does nothing.  Maybe we can add a message like....Close Browser and Restart???

The first error message in the browser is:
```
blazor.server.js:1 [2020-05-28T17:41:54.982Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'.
```
But after I do a hard refresh of the site, I am able to add the blog module to my page and use the blog module (add,edit,delete blogs).

**Comment by sbwalker** [comment]
Blazor Server is supposed to display a message "Could not reconnect to the server. Reload the page to restore functionality" when the SignalR connection is lost. This did not happen for you?

**Comment by mikecasas** [comment]
No, I didn't see that...basically what I am seeing

![error1](https://user-images.githubusercontent.com/11261164/83175902-ab014500-a0ea-11ea-85a9-c5c43f7c40f4.PNG)

**Comment by sbwalker** [comment]
this is a good thread related to SignalR disconnects: https://github.com/dotnet/aspnetcore/issues/12442

**Comment by sbwalker** [comment]
this thread also has some good discussion: https://github.com/dotnet/aspnetcore/issues/10496 It would seem that when the server connection is lost we would provide a managed experience where we give the user the ability to reload the page

**Comment by mikecasas** [comment]
ok, for now I am just happy the module loads and works. I will close this issue.  If you want me to add this improvement to a list, let me know.
