### ISSUE TITLE
ThemeRepository does improper Namespace-Prefix-Matching

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#554]
I have two themes in the Oqtane.Client, one called `BootstrapInstant` and one called `BootstrapInstant4`. Both have a container called `Invisible`. Now the UI always crashes claiming that the same Container is being added multiple times to a dictionary. 

![image](https://user-images.githubusercontent.com/5321186/83179840-da33a880-a122-11ea-8501-8bff861e75bc.png)

Turns out the code in `ThemeRepository.cs` is incorrectly checking the namespaces, by just doing a trivial string-prefix check, so that all the containers in `BootstrapInstant4` also get assigned to `BootstrapInstant` since the start the same way. 

![image](https://user-images.githubusercontent.com/5321186/83179763-c1c38e00-a122-11ea-8274-feb68cb029e3.png)

I'll work out a fix and push asap.

**Comment by sbwalker** [comment]
themeNamespace + "." ;)

**Comment by iJungleboy** [comment]
Tried that first, didn't work ;). 
Reason is that often the namespace doesn't have anything else afterwards, so most need ==, but some need + "."
But I pushed a fix, check it out.

**Comment by iJungleboy** [comment]
BTW Off-topic ...
Code-Style convention: I usually use `var` for most stuff (and that's also what Resharper recommends etc.). But of course I don't want to mess up your conventions and introduce by own for the bits I touch. 

Is there any preference or common style you're following; or would you mind if I do things Resharper suggest?

**Comment by sbwalker** [comment]
We are trying to follow https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines#coding-guidelines - so var usage is fine. Not all developers are using Resharper and we have rejected some Resharper suggestions ( ie. distinct namespaces based on folder structure )

**Comment by sbwalker** [comment]
PR looks good and I will merge it once the CLA is done

**Comment by iJungleboy** [comment]
done 👍
