### ISSUE TITLE
If Themes or parts are missing, Should perform automatic Fallback

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#560]
I'm working on creating some themes and templates, and keep running into this problem:

Basically if I create a theme and set the site to this theme, and later on decide to rename something (namespace, theme-name, layout-name, etc.) then everything breaks. Even the Admin-UI fails to work, since it tries to load the theme but can't. 

Recommendation
1. Determine a primary fallback theme, layout and container
1. At each level, if the configured theme is missing, fallback to the default

Of course I'm aware that in this case, some kind of a message or something would be reasonable so people realize that this is not normal. So my suggestion is that the fallback theme / layout / container shows error messages that the configuration is faulty, and only serves this purpose.

**Comment by chlupac** [comment]
You can use #454 for renaming items in database

**Comment by iJungleboy** [comment]
@chlupac DB changes are ok for the last clean-up. But ATM the site becomes unusable during Theme development, just because I cannot access site administration any more.

**Comment by sbwalker** [comment]
Agreed. This is resolved in #576. It provides fallback support to the default Oqtane theme, layout, and container.
