### ISSUE TITLE
RFC: Auto-Clean-up Names of Themes/Layouts/Containers

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#562]
Challenge: a Theme folder can have 3-20 files, but the names for developers may not really match what the user should see. 

So as a developer, I would like to have containers together, layouts together etc. - maybe like this:
![image](https://user-images.githubusercontent.com/5321186/83278532-0a874f80-a1d4-11ea-8b27-4959fd272caf.png)

For the user, this isn't cool though, as the names in the drop-down will then look like this:
![image](https://user-images.githubusercontent.com/5321186/83278590-212da680-a1d4-11ea-9ebc-c9a6a446f930.png)

I believe the developer should be able to organize his work efficiently, but still provide a reasonable output for the user. I believe that there are ca. these options

1. Live with it
1. Convention: if a Container starts with Container, it's truncated
1. Metadata using @attribute or [attribute] in code-behind 
1. Metadata using additional objects (kind of like ThemeInfo.cs)
1. adding properties to IThemeControl, ILayoutControl, and IContainerControl

My personal preference would be metadata using attributes, as it opens up more possibilities in future like adding icons etc. This is the approach that 2sxc uses for DataSource objects [example](https://github.com/2sic/eav-server/blob/master/ToSic.Eav.DataSources/DataSources/Paging.cs#L16-L20). Using code-files has the advantage of ever more runtime flexibility (like translating the name), but I would tend to attribute decorators. 

What do you think, and what would be preferred mechanism to generalize in Oqtane?

**Comment by mitchelsellers** [comment]
I would second a request for "Attribute" based designation as that would allow for better formatting etc as well.

**Comment by sbwalker** [comment]
One of the aspects to consider for any RFC will be compatibility. We just released 1.0 so we are trying to avoid breaking changes at this point so that developers have a chance to build extensions with some level of stability.

**Comment by sbwalker** [comment]
Most likely adding properties to IThemeControl, ILayoutControl, and IContainerControl would be the approach which would preserve compatibility and achieve the goals.

**Comment by iJungleboy** [comment]
What if there were a generic IUiMetadata? Something like

1. Label
1. Icon
1. HelpText

which would be - either part of IThemeControl, ILayoutControl, etc. - or then in the attribute?

BTW: I'll add the fourth option extending IThemecontrol etc. to the list above.

**Comment by sbwalker** [comment]
This was implemented in #576 to allow for friendly names and thumbnails to be defined for Themes, Layouts, and Containers. I tested this enhancement with existing themes to ensure it is backward compatible.
