### ISSUE TITLE
Bug: Trying to delete Theme crashes Oqtane

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#563]
I created a theme and to run installation tests, tried to delete it. 

Result is that the browser loses connection and Visual Studio stops at a this break point:
![image](https://user-images.githubusercontent.com/5321186/83281253-1a089780-a1d8-11ea-806f-768f7931d188.png)

Basically saying `_tenant` is null. 

Here's the call stack:
![image](https://user-images.githubusercontent.com/5321186/83281337-39072980-a1d8-11ea-89dc-d16347413e25.png)

And what `ThemeController.Delete` is trying:
![image](https://user-images.githubusercontent.com/5321186/83281427-605df680-a1d8-11ea-9f20-673b023afcaa.png)

My guess is that something is reset, and that just trying to log it requires a new DBContext and then something is missing and crashes.

**Comment by thabaum** [comment]
I think there needs to always be a fallback theme.

Same would happen when you selected no theme in the dashboard so this is actually related I believe and is a known issue.  I believe @sbwalker we discussed an exception handler for when the database theme is null or does not exist anymore?

Part of the delete theme method needs a fallback theme.

**Comment by thabaum** [comment]
@iJungleboy can you check the db to see if it is still set to try to use the theme deleted?

**Comment by svreic** [comment]
After some investigations I have found the problem:
During the deletion of a theme the ThemeController tries to log messages via the LogManager. The LogManager logs messages using the LogRepository. The LogRepository uses the TenantDBContext which is - like the name says - tenant specific. But the ThemeController is called by TenantService with tenant agnostic api calls. So during the log process no tenant can be resolved which leads to an exception in the TenantDBContext.

Imho there are 2 possible solutions for the problem:

1. Remove the loggin calls from the ThemeController. This will be a quick win but it will be only a symptom cure and does not solve the root problem.
2. Refactoring of the Logging mechanism to support also tenant agnostic logs. For me it is not clear why logs are tenant specific. @sbwalker maybe you can clarify the logging strategy of octane a bit in detail. Imho logging should be a more general thing and not tenant specific.

**Comment by sbwalker** [comment]
The correct fix is to modify ThemeService to use a tenant aware Url:

        private string Apiurl => CreateApiUrl(_siteState.Alias, "Theme");

I am sure it is mistake that it is not using a tenant aware url already - most likely introduced during a refactoring of alias management. Oqtane is multi-tenant and supports the ability to have a different database per tenant so the logging information for a specific tenant is maintained within that tenant so that the database is encapsulated and portable.

The alternate approach ( which we are not using ) is to have centralized logging - but even in this scenario you would need to maintain a key identifier to be able to differentiate the logging for each tenant. So even in this scenario you would need to use a tenant aware url.

**Comment by svreic** [comment]
@sbwalker thank you for clarifying the logging strategy. My solutions were based on the assumption that it is correct that the ThemeService is tenant agnostic.

I will test the suggested solution and create a PR fixing it.

**Comment by svreic** [comment]
I have tested the suggested solution with the current master but it produces some strange behavior. So i will investigate the problem(s) in more depth to see what is causing the strange behavior.
