### ISSUE TITLE
Docs: Create docs.oqtane.org auto-generated with Docfx

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#570]
I notice that ATM various levels of documentation would need to be collected from many sources, incl. issues, Q&A etc. which is why I would like to suggest that I setup a `docs.oqtane.org` with the same system as I already did it for https://docs.2sxc.org/. 

Here's how that would work:

1. Docs are built using docfx 
1. they contain automatic [code-documentation](https://docs.2sxc.org/api/dot-net/ToSic.Eav.Apps.Assets.IAsset.html)
1. separate pages like [how-to](https://docs.2sxc.org/how-to/customize-edit-ux/toolbars.html) or [specs](https://docs.2sxc.org/specs/content/index.html)
1. ..as well as combined pages which merge code-comments with .md files like [here](https://docs.2sxc.org/api/dot-net/ToSic.Eav.DataSources.EntityIdFilter.html)
1. I also use a attribute like `[PublicApi_Stable_ForUseInYourCode]` or `[PrivateApi]` etc. to mark code that is to be published on docs. Only things marked `PublicApi` are actually published, and in that I can still mark some methods/properties with `[PrivateApi]` so they are never mentioned in the docs, allowing me to keep things secret which are not yet prime-time.
1. The docs project is (on 2sxc) just part of the main solution - this could be also be a standalone repo if we expecte loads of changes and prefer an easier review process for such content. 
1. It's published using git-pages - so the generated docs are pushed to https://github.com/2sic/2sxc-docs and the rest is handled by github, we just have a DNS pointing to them

### Questions

1. Would this fit the needs of Oqtane? Or what would need to be different?
1. Would you like me to set this up (I'm only good at docfx, couldn't help much with other tools)?
1. Anything else?

**Comment by sbwalker** [comment]
I had an earlier discussion with @david-poindexter  about using the documentation system which was developed for the DNN open source project - as it was developed with the exact same requirements that are needed in Oqtane. How does you system compare and why would you choose one vs the other? The other option is to use a static site generation like Statiq Web which is highly integrated with Github ( we just transitioned to this solution for the .NET Foundation website ).

**Comment by iJungleboy** [comment]
@sbwalker I don't have the experience to compare a bunch of stuff. But the basic setup of docfx is similar to a static generator, except that it first scans your source code for comments and builds an code documentation first, then merges in your markdown to generate rich source-code documentation + static pages. 
I also host docs.2sxc.org on github, but the page generation happens in docfx. I believe just static generaters could never generate source code documentation. 
BTW: I just checked: https://www.dnndocs.com/api/ uses docfx as well. So we're both suggesting the same solution ;). Possibly just with a different build process.

**Comment by thabaum** [comment]
I have been contributing to it and like the potential it lays out myself for contributions.  Something we are all familiar with I think is best practice for everyone 👍

**Comment by david-poindexter** [comment]
@sbwalker I am happy to look into this when things lighten up a bit for me (heavy workload at the moment).

**Comment by sbwalker** [comment]
@iJungleboy I think we should move forward with your docfx solution. I assume that it relies on the triple slash format for comments:

/// <summary>
///  This is a hello world program.
/// </summary>

If so, the first step will require going through the entire Oqtane codebase and adding these comments.

**Comment by iJungleboy** [comment]
@sbwalker Here's the gist of it

## Work
1. The main solution needs another project for the docs
1. In there, you configure what code to use as the source
1. You also add / configure a bunch of template files which will generate the result
1. In addition, you can create specially crafted .md files which are merged with the `///` comments
1. You then build & publish the results, here we have various options (see below)

I can get the basics all set up end of July (I'll be gone starting tomorrow) if nobody else did it first :)

## Not Publishing All APIs

Here's just my recommendation from working on 2sxc. I have a lot of APIs which are public, but not really meant for external use as they can still change. For this I created a set of attributes like `[PublicApi]` or `[PrivateApi("with comment")]` or `[PrivateApiJustFyi("comment")]`. 

I can apply these to both classes or specific methods. The code generator is then configured to _only publish_ `[PublicApi]` or the `[PrivateApiJustFyi("comment")]`. This lets me officially release APIs step by step. I strongly suggest to do something similar. 

## Publish
We'll then need to decide how to publish. There are basically [three ways to do this](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) and let github host it:
1. Into an own repo - this my preference, which is what I'm doing with https://docs.2sxc.org which is here https://github.com/2sic/2sxc-docs
1. Into a `gh-pages` branch (kind of tricky, don't like that)
1. Into a `/docs` folder in the main code repo (really don't like this - too many changes)

I personally prefer the separate repo, because the docs can have a lot of changes - even when just rebuilding - and I wouldn't want those changes to clutter my timeline. 

Sound ok?

**Comment by thabaum** [comment]
What does Microsoft Docs use?

**Comment by JustCallMeAD** [comment]
@thabaum it looks like Microsoft are using DoxFx too:
https://github.com/MicrosoftDocs/TeamBlogFeedback/issues/76

**Comment by JustCallMeAD** [comment]
Saw this tweet and thought it might be useful :)

_In this episode of #OnDotNET, @DennisCode shows us how to get started using #DocFX, an open source, static site generator that can produce docs from source code and Markdown files. Check it out: https://msft.it/6010TlmLA_

https://twitter.com/dotnet/status/1280292954280792069

**Comment by iJungleboy** [comment]
@sbwalker I'm back from vacation and will spend some time on the docfx implementation - AFAIK nobody else started with this. 

I'll create a VS project in the folder Octane.Docs. Can you confirm that we'll use my other recommendations above? Specifically

1. Create attributes like `[PublicApi]` to mark stuff which will be published in the docs
1. That we'll publish it using github pages into an own repo
1. Could you also create a repo for this - probably `octane.docs` and give me permissions on that to admin it? this will help a lot to get everything set up.

**Comment by sbwalker** [comment]
You are correct that nobody started this effort yet. I will try to provide some answers to your question...

1. In terms of API documentation I feel like there are 3 distinct areas in Oqtane which would need to be included:

Oqtane.Client - Services - these are the API wrappers which developers are expected to use in their razor components
Oqtane.Server - Controllers - these are the raw APIs which developers can also use to interact with the framework
Oqtane.Shared - Models - these are the models shared by the client and server

Nothing else would be considered part of the "public api". Are you saying that the attribute would be used at the Class level to determine which items to include in the docs?

2. Yes I would like to use Github pages
3. Yes, I would prefer to use a separate repo - which I can create for you.

**Comment by iJungleboy** [comment]
@sbwalker Thx for the answers, as soon as the targets are ready I'll start with this. Basically it will probably take me about 1-2 days in terms of effort (8-16h).

In regards to the `[PublicApi]` - yes, it's to mark things for public docs at the class or property level. I find this very important, because it 

1. Publishes "official" APIs which we actively decide that they are for public use
1. Increases developer sensitivity when changing such calls, because the developer knows this is one that must remain stable for long
1. Also allows us to mark things like `[InternalApi_MayChangeAtAnyTime]` or something - this gives people a very good understanding of what they are doing and what APIs are "too deep" or maybe even `[ExperimentalApi] `

Here some examples from 2sxc

1. This interface is stable/public https://docs.2sxc.org/api/dot-net/ToSic.Eav.Metadata.Target.html
1. This interface exists and is documented, but use-with-caution https://docs.2sxc.org/api/dot-net/ToSic.Eav.Run.IContainer.html as it's an abstraction for the module-context in DNN, and as we put 2sxc on more platforms, we may have to make bigger changes

**Comment by sbwalker** [comment]
@iJungleboy I have added the new repo and added you as Admin

**Comment by iJungleboy** [comment]
thx, looks good. I'll see that I can start next week.

**Comment by iJungleboy** [comment]
@FrancoisMongeau awesome :). thx!

I'm currently preparing the initial setup with layout, hosted output pages etc. Then your contributions will be most welcome!

**Comment by iJungleboy** [comment]
@sbwalker I have a first version ready - which I would like to discuss with you soon.

You can see this initial version on https://oqtane.github.io/oqtane.docs/index.html

In the meantime, could you create a dns-entry for docs.oqtane.org with points to the same IP as `https://oqtane.github.io/` so I can continue configuration?

**Comment by iJungleboy** [comment]
ping @sbwalker

**Comment by hishamco** [comment]
I'd like to suggest to keep any issues or features related to docs may moved into the docs repo if it's created

Thanks @iJungleboy for your amazing efforts

**Comment by iJungleboy** [comment]
ping @sbwalker I've been waiting for 15 days now ;)

**Comment by hishamco** [comment]
@sbwalker can we take the needed action here

**Comment by sbwalker** [comment]
@iJungleboy can you help me with what the IP is for https://oqtane.github.io/? I get nothing back from ping and when I browse to it I get a 404

**Comment by iJungleboy** [comment]
Hi Shaun

I get a ping
![image](https://user-images.githubusercontent.com/5321186/94820546-e09f9d00-0400-11eb-97dc-29b673ffb831.png)

And you get a 404 because the home doesn't have anything, it's currently on the subfolder https://oqtane.github.io/oqtane.docs/ 

Once we have the domain, it will be in the root.

**Comment by sbwalker** [comment]
@iJungleboy docs.oqtane.org is now provisioned

**Comment by sbwalker** [comment]
Yes I can make that change. I initially thought CNAME was the right approach but you indicated that it should point to an IP and only an A record can do that, so thats how I added it.

**Comment by sbwalker** [comment]
ok docs is changed to a CNAME pointing to oqtane.github.io

**Comment by iJungleboy** [comment]
@sbwalker thx. 
Where can I DM you to organize a telco? Mail, Facebook, Twitter, etc.?

**Comment by sbwalker** [comment]
shaun.walker at siliqon.com

**Comment by iJungleboy** [comment]
I'm all ready!

oqtane.docs now contains all of docfx and build works. I also added more explanations for cross-linking, images etc. 

Just accept the pull request https://github.com/oqtane/oqtane.framework/pull/802

Then we can close this 🚀💃
