### ISSUE TITLE
Bug: .map files seem to be blocked by the blazor server

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#571]
When creating professional js/css solutions, tools like Webpack etc. create optimized packages + additional `.map` files. These are used in debuggers like Chrome-F12 to see what real code was used to cause an issue. I believe that .map files are not being delivered - but I'm not sure where I could enable this for a simple pull request. Here's what chrome shows me during debug.

![image](https://user-images.githubusercontent.com/5321186/83348423-ae840e80-a32c-11ea-8bcc-15cd3ac9c053.png)

**Comment by sbwalker** [comment]
I do not have experience in this area. I do know that the Quill rich text editor was referencing a .map file from within its Javascript file - and it was throwing 404 errors even though the .map file actually existed. The .map reference was removed from the Javascript file to resolve the issue. This sounds like a Blazor problem - not an Oqtane problem - however it would be good if someone could investigate further.

**Comment by iJungleboy** [comment]
I've done some more investigation and would like to share my findings:

1. It seems that `.map` files are served. You can't see them in chrome, but with Fiddler you would see that they were requested and properly delivered (see marked lines 72/74): 
![image](https://user-images.githubusercontent.com/5321186/83533489-ee472380-a4ef-11ea-8322-033174ab9f1b.png)
1. It then again seems that chrome seems to re-map the folder for the source to the wrong location - in this case it's trying to get /Theme/Src/theme.ts which of course the source-map wouldn't have. See lines 77/78 in image above.

So I don't have a definite answer yet, but it may also be that my source maps are faulty. I'll keep looking into this.

**Comment by thabaum** [comment]
Since Edge is now same as Chrome and is open source project along with Blazor maybe this is something that can be further discussed as an issue on one of those repo's for a potential answer?
