### ISSUE TITLE
RFC: object ownership and more granular permissions

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#587]
for example : module blogs. 
In my app I have group `Authors` who can create `Blogs`.
I can add to `Blogs` permission `AddBlog` on module level for group `Authors`. Easy.
When Author creates Blog he becomes `Owner` of this particular Blog. 
And I want to set 'Edit' 'Delete' 'Publish' permissions only for  `Owner`  of this particular `Blog`.

'Owner' can be special role visible in permission grid  only for modules with implemented 
```
public interface IOwnership
{
        bool IsOwner { get; }
}
```

Next goal is set permissions for particular Blog (limit viewing, ...). It can be done with current permission system, (permissions for custom entity `Blog`, question is how correctly establish permission settings page for particular `Blog`

**Comment by sbwalker** [comment]
I believe this is already supported in the framework - or at least it was designed with this use case in mind as this is a common requirement for modules. All of the current core permissions ( ie. Page, Module, Folder, ModuleDefinition ) utilize a common permission system which is extensible and can easily accommodate other types of entities - basically it simply expects that entities have a name and a unique ID to identify them. If you want to include permissions for your own custom entity then you usually need a way for users to be able to specify the permissions through the UI and a way for your code to be able to verify the permissions. 

If we consider the Blog example then the entity name is "Blog" and your database table would have a unique ID of BlogId. If you follow the existing code patterns in the framework then you should have everything you need to implement permissions.

1. Use the PermissionGrid component in your module
```
<PermissionGrid EntityName="Blog" PermissionNames="Edit,Delete,Publish" Permissions="@_permissions" @ref="_grid" />
```
Your module needs to pass a collection of permissions to the PermissionGrid for the specific BlogId  (these permissions would be stored in a Permissions property on your Blog model ). You can retrieve the permissions entered by a user by calling _grid.GetPermissions(), set the Permissions property on your Blog model and pass them to your BlogController to be saved to the database. There are already methods which exist to simplify getting and saving Permissions in the PermissionRepository.

2. Validate permissions in your module:

In your module components you can use UserSecurity to validate permissions:
```
UserSecurity.IsAuthorized(PageState.User, "Edit", blog.Permissions)
```
And in your Controller you can use UserPermissions:
```
_userPermissions.IsAuthorized(User, "Blog", blog.BlogId, "Edit")
```

**Comment by sbwalker** [comment]
I should probably also mention that if you would like an example of an "Owner" scenario you should look at the "personalized page" feature in the framework. Basically it allows a user to create a version of a page which they "own". It does this by using the existing permission system and granting View and Edit rights to their UserId.

**Comment by chlupac** [comment]
Thank you for tip

**Comment by sbwalker** [comment]
closing as I believe the framework already supports this
