### ISSUE TITLE
RFC: Validate owner name for a new module before adding the module

### ISSUE THREAD

**Issue by louyo** [oqtane/oqtane.framework#588]
Assigning non existent owner to a module creates build failure: "<name> is a namespace but is used like a type" error.
User error (mine was typo), but makes a mess. Suggest you validate owner name for a module before adding the module.
Create new page, create module on the page, give it an invalid/non-existent owner name. When you rebuild, you get the error.
Lou

**Comment by thabaum** [comment]
I know there are a number of ways we can deal with this.

https://github.com/oqtane/oqtane.framework/pull/591

creates a new way we can handle creating the form for dashboard and admin components if accepted.  It will take some work we can do things one component at a time I believe.  I was going to start with the registration and login components.  This could be simpler in a way however I think there needs to be a check if the user exists, and auto-complete users that you have permission to view as well which is another UX issue I see here.

- Form Validation
- UX component for selecting available Oqtane users.

**Comment by sbwalker** [comment]
Can you please explain what you mean by "Owner" - this is not a term which is used in the Control Panel when you add a module to a page.

**Comment by louyo** [comment]
![owner](https://user-images.githubusercontent.com/6570793/84037344-7738e180-a96c-11ea-87e0-2d830dab6c73.PNG)

**Comment by sbwalker** [comment]
Oh... you were trying to use the Module Creator. Your error report said that you were simply trying to create a module on a page - which is a completely different scenario. The Module Creator simply needs some validation to ensure an owner name is entered.

**Comment by sbwalker** [comment]
There is already validation in the Module Creator to ensure that an Owner Name and Module Name is provided. Are you saying that you did not provide an Owner Name and you clicked Create Module and it did not display the message "You Must Provide An Owner, Module Name, And Template"

**Comment by louyo** [comment]
No, I made a typo and put a non-existent user name for Owner.

**Comment by sbwalker** [comment]
Are you able to share what you entered for Owner Name so that it is possible to determine what type of validation is required? There is already validation to ensure that a user does not leave the field blank.

**Comment by louyo** [comment]
OK, I will stop bothering you folks. I can't create this every time. Here are 2 screenshots but they are not continuous. Note the period inserted into the module name. My story (and I am sticking to it) is that the original failing iteration did not have a period in the name. But, if you do put period in there, this is what happens. My apologies for taking up your time. 
![jimmodule](https://user-images.githubusercontent.com/6570793/84053026-56c65280-a97f-11ea-85d1-cc98c8f2c95b.PNG)
![jimfailCapture](https://user-images.githubusercontent.com/6570793/84053037-5a59d980-a97f-11ea-853a-c1a9c7cb3e35.PNG)

**Comment by sbwalker** [comment]
Yes, punctuation in the name can definitely cause issues with the scaffolding so there needs to be some validation ( in addition to the help text )

**Comment by sbwalker** [comment]
I am going to close this item, as the help text instructs the user to avoid entering punctuation or spaces.
