### ISSUE TITLE
BUG: Unhandled exception when trying to edit MyPage.

### ISSUE THREAD

**Issue by louyo** [oqtane/oqtane.framework#589]
Not sure about this. I have gotten several, non-repeatable, unhandled exceptions. Mostly while working with users and pages. This one happened when I added a new user and tried to figure out what I had to do for him to see pages added by the host user. I logged in as that user, went to "My Page" and clicked on the edit Icon. See attached screen shot. I am running on W10, VS-2019 Community, 16.6.1. My problems may be due to new user, you are busy enough. I will wait to try oqtane again when things settle down.
![oqtaneex](https://user-images.githubusercontent.com/6570793/83955047-eef7f680-a81c-11ea-8461-af9e7607ebd4.PNG)

**Comment by louyo** [comment]
Oops, I lied. This happens when I log in as that user and click on My Page. Never gets to the page.

**Comment by sbwalker** [comment]
this is probably a bug that needs to be investigated

**Comment by sbwalker** [comment]
This was indeed a bug - most likely introduced during the refactoring of permissions. It was tricky to track down but it is working now.
