### ISSUE TITLE
Bug: Unable to use <EditForm> element

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#590]
## Summary
In order to use ```<EditForm></EditForm>``` Blazor forms and validation are missing the following 2 namespaces:

```System.ComponentModel.DataAnnotations```
and 
```Microsoft.AspNetCore.Components.Forms```

## References
Microsoft Docs
https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputtext?view=aspnetcore-3.1

This is referenced as being still under development:
https://www.nuget.org/packages/Microsoft.AspNetCore.Components.DataAnnotations.Validation

> Provides experimental support for validation using DataAnnotations.

This package was built from the source code at https://github.com/aspnet/AspNetCore/tree/5da314644ae882ff22fb43101d0c3d89a35c40e9

## Screenshots

![image](https://user-images.githubusercontent.com/13577556/83961298-9f2e2500-a846-11ea-8dcf-79ab71c83ac6.png)

![image](https://user-images.githubusercontent.com/13577556/83957299-e94de100-a81b-11ea-8960-96ec43e87574.png)

**Comment by sbwalker** [comment]
When you create custom modules you are free to include whatever using statements, etc... that you need. We are not using EditForm in the core framework at this time - it is on the roadmap for V2 but needs to be done in a comprehensive manner ( please see the Consistency paragraph in the Oqtane Philosophy ).
