### ISSUE TITLE
Module Title cannot be changed at runtime.

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#592]
I want to be able to set module title. 
But changing 
`ModuleState.ModuleTitle = newValue' actually does nothing. 
I thing than here should be mechanism to call 'StateHasChanged()' on module container level to update state of module including head and container. Automatically or manually.

**Comment by sbwalker** [comment]
The ModuleState cascading parameter is intended to be a read-only cache. You should not be updating its contents directly. If you want to update the page title value then you should update the value using the ModuleService.

**Comment by chlupac** [comment]
ModuleService ???
I need title dependent on content of module. For example display current count in famous counter module.

**Comment by sbwalker** [comment]
Couldn't you simply use the "No Title" container so that the standard ModuleTitle component is not displayed, and then inside your custom module you can render whatever dynamic title you want based on your specific content? I don't think it makes sense for the core framework to support this.

**Comment by chlupac** [comment]
Yes, I can, I'm doing it this way. But I was not sure if here is a way how to do it by framework.  I think it is very common scenario and will be nice to be supported. I have to explain to site admin which container is good for particular module.
