### ISSUE TITLE
Question : Image caching.

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#593]
I have page with images stored in Oqtane filestore. These images are downloaded again and again on every request, because of dynamic content. 
I thing we have to implement middleware or modify headers to convince browser than image is static and store to cache.

**Comment by thabaum** [comment]
A cache on/off switch should be created for this so you can make the framework act either way you choose.  Potentially even a module option?  So when you download a component if it is info that will not change anytime soon it can be "static" although created dynamically in the back-end of Oqtane.

**Comment by thabaum** [comment]
I always thought HTTPS/2 was suppose to take care of this type of stuff in the browser, we really need to dive into that part of Oqtane and test how we can achieve desired results for different situations potentially?

**Comment by chlupac** [comment]
best place imho will be DownloadControler on request level with url query or path, if it is possible. 
i have no experiences with this, maybe i'm wrong.
now it is 
```
        // GET api/<controller>/download/5
        [HttpGet("download/{id}")]
        public IActionResult Download(int id)
        {
```
maybe we can add 
```
        // GET api/<controller>/static/5
        [HttpGet("static/{id}")]
        public IActionResult DownloadStatic(int id)
        {
```
and developer will choose which variant suits his needs

**Comment by jimspillane** [comment]
Should files that require authorization be cached?

**Comment by thabaum** [comment]
potentially not.  Maybe only content that is declared "public" ?

**Comment by sbwalker** [comment]
This needs to be researched further as I am fairly sure that the default response caching middleware will not cache requests that contain cookies - and Oqtane is using cookies for auth currently.

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-3.1

**Comment by chlupac** [comment]
I have caching implemented now. Together with image sizing/thumb-nailing engine in custom controller. It works wit oqtane filesystem.
```c#

        [ResponseCache(Duration = 1200)]
        [HttpGet("{id}/{size?}")]
        public async Task<IActionResult> Get(int id, string size)
        {
            var errorpath = Path.Combine(GetFolderPath("images"), "error.png");
            var file = _files.GetFile(id);
            if (file != null)
            {
                if (_userPermissions.IsAuthorized(User, PermissionNames.View, file.Folder.Permissions))
                {
                    var filepath = Path.Combine(GetFolderPath(file.Folder), file.Name);
                    if (System.IO.File.Exists(filepath))
                    {
                        var opts = new ImageThumbnailOptions("", "");
                        var req = new ThumbnailRequest {RequestedPath = HttpContext.Request.Path, ThumbnailSize = ParseSize(opts, size), SourceImagePath = filepath};
                        req.ThumbnailImagePath = GenerateThumbnailFilePath(filepath, req.ThumbnailSize);
                        if (IsSourceImageExists(req))
                        {
                            if (!req.ThumbnailSize.HasValue)
                                //Original image requested
                                return PhysicalFile(req.SourceImagePath, "image/jpeg", file.Name);
                            if (!IsThumbnailExists(req))
                                //Generate, cache and send.
                                GenerateThumbnail(opts, req, HttpContext.Response.Body);
                            return PhysicalFile(req.ThumbnailImagePath, "image/jpeg", file.Name);
                        }
                    }
```
` services.AddResponseCaching();` and `app.UseResponseCaching();`  should be added to startup.
  
and it works. url template:  /{site}/api/images/{fileid}/{size?}
size : 
full - returns uncompressed image
200 - returns resized image in 200 x 200 frame
200x100 - returns 200 x 100 
200x0 returns resized image with image aspect ratio, width 200
0x200 same, but height

Should I implement it to Oqtane ?


![image](https://user-images.githubusercontent.com/7838468/84473995-58975b00-ac8a-11ea-884d-f4cfd5fd2e0a.png)

**Comment by sbwalker** [comment]
Yes I think we should include this as it aligns well with the overarching philosophy of performance. I am guessing we may want to add another ContentUrl() overload method in the base classes to make it consistent/easier for developers to utilize this feature.

**Comment by chlupac** [comment]
I have `ImageUrl(int id, string size = null)` method

**Comment by sbwalker** [comment]
Currently ContentUrl() is used throughout the framework to load images. I am not sure if it would be a good idea to introduce another method with the same purpose with a different name. The first question a developer would have is why would I use one versus the other. And the answer would be there is no reason - so they should have the same name.

**Comment by chlupac** [comment]
One is cached, one not, file/download is for general use,
question is : new controller, or file/image ??

**Comment by sbwalker** [comment]
so you are saying that all references in the framework which are loading images currently should be changed to use ImageUrl()?

**Comment by sbwalker** [comment]
When developing a framework it is important to keep the methods to a minimum so that it is intuitive for developers to determine how to use it effectively. This is the reason I am asking these questions. If you have 2 methods in different classes or with different names that essentially do the same thing then it becomes confusing. And it increases the maintenance effort in the long term. And it introduces more risk of people fixing one method but not realizing they need to fix the other. And it increases the risk of someone mistakenly thinking that the ContentUrl() method is missing caching and submit a PR. I have been down this road before so I have experienced all of these scenarios.

**Comment by chlupac** [comment]
or we can make couple of new overloads
ContentUrl(int id, string size = null) 
which uses caching and file/image
and 
`ContentUrl(int id, bool useCache)` where I can switch off cache
and use file/download or file/image

**Comment by sbwalker** [comment]
If you think we need ImageUrl() in addition to ContentUrl() its fine - we just need to be sure they are different/distinct in their purpose, and we need to be 100% consistent in how we use them throughout the framework so that it is clear to developers. My gut feeling is that the majority of cases where ContentUrl() is used currently is for serving images - and they would want to be able to benefit from this caching enhancement.

**Comment by chlupac** [comment]
cache headers are driven by attribute, maybe here is way to add them in code and to have only one controller method. I agree than one ContentUrl() method with overloads is better.

**Comment by sbwalker** [comment]
A similar thought process should be applied to the Controller methods as they are essentially the API counterparts to the Url() convenience methods in the UI. Obviously there are different technical limitations in Controllers so I will leave it to you.

**Comment by thabaum** [comment]
very cool @chlupac I will have to look at this more when I have some time!

**Comment by sbwalker** [comment]
I am going to close those this as #635 appears to replace it
