### ISSUE TITLE
RFC:  Icon set for Oqtane

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#594]
https://github.com/iconic/open-iconic

I found this browsing around as an open source MIT licensed icon solution that looks pretty fresh in design.

We can always fork this project to create our own as well so this is what interested me about it if I am correct?

I know everyone has their own icon sets but for the framework itself as an option could it use something like Iconic open source?

I know you can set some icons currently where do these come from?  Is it Font-Awesome?

**Comment by chlupac** [comment]
```
namespace Oqtane.Shared
{
    //Open Iconic icons set
    public static class Icons
    {
        private const string Prefix = ""; //oi- 
        public const string AccountLogin = Prefix + "account-login";
        public const string AccountLogout = Prefix + "account-logout";
        public const string ActionRedo = Prefix + "action-redo";
        public const string ActionUndo = Prefix + "action-undo";
        public const string AlignCenter = Prefix + "align-center";
        public const string AlignLeft = Prefix + "align-left";
        public const string AlignRight = Prefix + "align-right";
        public const string Aperture = Prefix + "aperture";
```
already in oqtane

**Comment by thabaum** [comment]
you guys rock, we are like on the same wave length i swear I just need to catch up here ;)
