### ISSUE TITLE
BUG: Unhandled exception opening a user's profile

### ISSUE THREAD

**Issue by louyo** [oqtane/oqtane.framework#600]
Unhandled exception when trying to go to user's profile. Intermittent. I was adding users and going back and forth to their profiles and Home page. When I clicked on the user name to go to the profile, I got the unhandled exception shown below. Seems to happen more often in Firefox than  Chrome. Tested this, downloading the current Zip and installing on one system running VS Preview and one VS standard, both up to date. Not sure it ever happens with only the host user. Not that I spend my day clicking on Home and User but that is how I recreated it after the first time.

![dbconnectUE](https://user-images.githubusercontent.com/6570793/84166781-60b18980-aa43-11ea-8763-8834e91bdc1a.PNG)

**Comment by louyo** [comment]
![clickhost](https://user-images.githubusercontent.com/6570793/84166969-9c4c5380-aa43-11ea-8f6c-8ea80cf08400.png)

Rats, wrong exception above, this is from the above problem

**Comment by louyo** [comment]
FWIIW, the first one is what I got when I updated all the nuget's. Won't do that again.

**Comment by thabaum** [comment]
two browsers up, two different users, left one idle for a while came back booya same exact error above.

I think maybe it has to do possibly with timeout maybe as it happened after I was away for a while?!

**Comment by louyo** [comment]
Funny, I thought it might be because I  was switching too fast. Probably some race condition or some such. Seems to happen more often using Firefox.

**Comment by thabaum** [comment]
This bug seemed to happen if I tried to send a notification just now as well.

**Comment by thabaum** [comment]
maybe related to being sent back to the page?

**Comment by thabaum** [comment]
I was able to reproduce now just going around the website for a while playing with the file manager everything was fine then going to user profile for first time crashed same error.

**Comment by thabaum** [comment]
What I find is odd is it works then all sudden it don't

And this issue really happened for me after I updated VS recently (up to date with updates applied today)

I am not sure if this has anything to do with it but I have read how other people in the past have had bugs like this.

**Comment by thabaum** [comment]
I just now have it down to where I need to hit 

- visit user profile
- select notifications tab
- view a notification
- close the notification window
- error

**Comment by louyo** [comment]
Well, I had it fail in Chrome, took longer. 
Maybe it is OK with the new version, but I never thought real friends should let friends run Edge. 
I am also not convinced that Blazor is a stationary target yet. More reason to give kudos to Shawn.

**Comment by sbwalker** [comment]
@thabaum I think the error in the Notification area you are experiencing is because you did not execute some of the recent database script changes:

ALTER TABLE [dbo].[Notification] ADD
	[FromDisplayName] [nvarchar](50) NULL,
	[FromEmail] [nvarchar](256) NULL,
	[ToDisplayName] [nvarchar](50) NULL
GO

I had a conversation with @chlupac about this and I think he convinced me that we need to support granular scripts ( although I am going to change the naming convention for them ).

**Comment by thabaum** [comment]
OK I will take a look next week thank you.  I believe I downloaded a fresh copy from here then ran for testing this issue.

I will look into this SQL when I have time to fire things up again.

**Comment by sbwalker** [comment]
This was related to a race condition. The Profile tab was referencing the settings() collection but it was not ensuring the collection was loaded in OnInitializedAsync(). This is a common issue in asynchronous development and it is hard to reliably reproduce these types of issues.

**Comment by thabaum** [comment]
Thank you for the update.  This code fix is what was in my mind.  Nice to see verification I was on the right track.
