### ISSUE TITLE
Bug:  Unable to update user profile "Passwords Entered Do Not Match"

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#601]
## ISSUE

Password fields if you have saved for site will auto fill form in Identity tab causing passwords do not match.  This forces a user to first go back to Identity tab, clear the fields to save profile changes.

## STEPS TO REPRODUCE

0.  Have a user password saved in browser for the Oqtane website.
1.  Click on gear
2.  Click on Admin Dashboard
3.  Click on User Management
4.  Add User and save
5.  Click Edit User Button
6.  Notice Password field is autocompleted  (Confirm Password is not)
7.  Switch to Profile and make a change
8.  Click save and get error that passwords do not match.

## SCREENSHOTS

![image](https://user-images.githubusercontent.com/13577556/84188641-c81e0800-aa48-11ea-93f8-53b7457fc800.png)

![image](https://user-images.githubusercontent.com/13577556/84188733-eedc3e80-aa48-11ea-9f55-5fe454846e02.png)

**Comment by sbwalker** [comment]
There is a way to disable autocomplete but it is not recommended ( if you turn off autocomplete, you are breaking rule 1.3.5: Identify Input Purpose in WCAG 2.1 ). 

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

I am not sure if we should consider this a "bug" or by design ( since its really a personal browser preference )?

**Comment by chlupac** [comment]
this is not bug, but it is confusing for users. Good way should be hide "change password" section and show it on demand.

**Comment by thabaum** [comment]
Hiding for on-demand is a good option.  

I just see other forms not have this issue... I think there is something that controls which field an autocomplete fills out and we can just simply change that to password-reset instead of password for id I believe?! change the logic to use PasswordReset instead of Password for field ID I think is how it is handled but I need to refresh my mind in that relm.

Otherwise have the fields disabled and enable with a button is another option.

**Comment by thabaum** [comment]
`autocomplete="new-password"`

I believe this is what we are after I will test this next week while I am working in this area next week.

**Comment by sbwalker** [comment]
@thabaum your suggestion for autocomplete="new-password" does sound like the right solution https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password

**Comment by thabaum** [comment]
I will get a pr done for this as well.  Once we get things responsive I would also like to be sure accessibility is nice for anyone taking Oqtane for a run.

**Comment by JustCallMeAD** [comment]
@sbwalker @thabaum Google has moved away from the web standard for autocomplete and just does it's own thing. This has been going on for many years and here are some discusssions on the topic:

https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7

https://bugs.chromium.org/p/chromium/issues/detail?id=914451&can=2&q=Autofill%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
