### ISSUE TITLE
Unhandled exception should not make page/site frozen.

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#605]
Errors happens.
In case of unhanded exception page looks frozen.  Site goes alive only after full page refresh. 
It's bad user experience. Users complains about it.  We have to find mechanism how to display error state, log it, report it, handle it and allow user to redirect to "safe zone".

**Comment by jimspillane** [comment]
Maybe adding the gold bar might help the end-users.
[Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1)

![image](https://user-images.githubusercontent.com/15007083/84413839-28df4900-abdf-11ea-9d07-f7829fca4ae7.png)

**Comment by chlupac** [comment]
yes. it will definitively help. Thank you for tip.

**Comment by sbwalker** [comment]
yes we should definitely add this.

**Comment by chlupac** [comment]
![image](https://user-images.githubusercontent.com/7838468/84470437-a52b6800-ac83-11ea-9a40-ddbc6c0bdc49.png)
It works. Great. 
here is issue, I cannot return to main page from this line. solved in blazor 5.0 preview 4
https://github.com/dotnet/aspnetcore/issues/19635

**Comment by chlupac** [comment]
![image](https://user-images.githubusercontent.com/7838468/84470678-2551cd80-ac84-11ea-8995-10a1e11ea2d3.png)
It works. Great. Thank you.
btw. here is issue in current version of blazor.
https://github.com/dotnet/aspnetcore/issues/19635

**Comment by sbwalker** [comment]
It seems there is a comment in that thread "To achieve the behavior you are looking for, I would recommend changing the class name on the Reload button to prevent the default event handlers from being registered to it then attaching your own event handlers to redirect to the desired route." - dd you get it working?

**Comment by chlupac** [comment]
no, i did not try

**Comment by chlupac** [comment]
```
    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            Objevil se problém, který není na vašem přijímači. Za případné nepohodlí se omlouváme. Můžete zkusit stránku
        </environment>
        <environment include="Development">
            Objevil se problém, který není na vašem přijímači. Za případné nepohodlí se omlouváme. Můžete zkusit stránku
        </environment>
        <a href="~/" class="">Obnovit</a> a poté se vrátit 
        <a href="~/" class="reload">na hlavní stránku</a>
        <a class="dismiss">🗙</a>
    </div>
```
actually first `<a/>`  clears url and second one correctly reload main page

**Comment by sbwalker** [comment]
addressed by #614

**Comment by sbwalker** [comment]
@chlupac I added this in #614 but the link in the form <a href="~/" class="reload">reload</a> does not work correctly

**Comment by jimspillane** [comment]
I changed the CSS from bottom : 0; to top : 0; and the z-index to 10000.

**Comment by chlupac** [comment]
```
        <a href="~/" class="">#1 Clear Url</a>  and then  
        <a href="~/" class="reload">#2 return to main page</a>
```
It's dirty workaround of dotnet/aspnetcore#19635 it requires click in order to two url's
first one clears ling and second one redirects :) I'm not strong enough in js to do it better.
