### ISSUE TITLE
RFC: SQL Performance Impact of Unique Index

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#620]
Here is an article about the impact of the Unique Index on performance  getting the most out of the SQL performance.  I was wondering if this was something to investigate further for Oqtane.

Sebastian L mentioned it on DNN github and caught my attention as something that may be of interest here as well.

This article is about a job done to increase performance of an app without touching the source code.

https://blog.sqlauthority.com/2019/07/24/sql-server-performance-impact-of-unique-index/

> In the various tests, I have done in the past converting existing non-clustered index a unique non-clustered index always helped with the performance.

**Comment by jimspillane** [comment]
There are many non-clustered unique indexes currently being used in the [database](https://github.com/oqtane/oqtane.framework/blob/master/Oqtane.Server/Scripts/Tenant.00.09.00.00.sql#L414-L459).  Do you see any that are missing?

**Comment by thabaum** [comment]
I have not looked into it yet.  I did want to go through and take a look.

**Comment by sbwalker** [comment]
@thabaum once you are finished with your investigation and if you identify any indexes which are missing please raise an issue or submit a PR. I am closing this issue for now.
