### ISSUE TITLE
Unhandled Exception adding a page after deleting page with same name

### ISSUE THREAD

**Issue by louyo** [oqtane/oqtane.framework#626]
Here I go again, probably another user error but I don't think one should ever get an unhandled exception.
New iteration with download today.
1. Add User, with Administrator role
2. Log in as the new user.
3. Add a page.
4. Go to the page.
5. Tried to add internal module to page, wouldn't react to Create Module button. Wouldn't remove the add module stuff from page.
6. Delete page.
6. Add page back, same name.
Unhandled exception. Duplicate Key Row.
No clue why I couldn't add a module. 
![readdpage](https://user-images.githubusercontent.com/6570793/85086371-66783f00-b1a8-11ea-89bc-f2f36a65fa35.PNG)

**Comment by jimspillane** [comment]
It looks like that user would be denied because they are not assigned to the [Host Users role](https://github.com/oqtane/oqtane.framework/blob/master/Oqtane.Server/Controllers/ModuleDefinitionController.cs#L166).  I don't know the answer to your next question, how to assign a user to the Host Users role ;)

The error thrown by adding the page appears to be an issue from the soft page delete conflicting with an index.

**Comment by louyo** [comment]
Yup, permission thing I would think. If you are not King, you shouldn't see the add module choice. O also threw an exception when I tried to log out on that page, to fix as Host. 
I don't like it that, when you add the module (as Host), it crashes Chrome and you have to restore pages. I guess it is all a part of the testing/fixing process. Would not ignore the advice about using for production. I am amazed at all the work that has been done here.

**Comment by chlupac** [comment]
Deleted page is only marked as deleted. Definitively deleted is from recycle bin. But this should not throw exception, it's a bug.

**Comment by louyo** [comment]
Well, being curious (also a glutton for punishment) I installed of Oqtane on a Ubuntu VM and results were similar, except I can't install a module even  as Host. Assume that this is not supported, but was an interesting exercise.  Would save some licensing money.

**Comment by mikecasas** [comment]
@louyo where was the sql server, on your VM?

**Comment by louyo** [comment]
Yes, installed mssql-server on Ubuntu.

**Comment by louyo** [comment]
BTW: Also works in Ubuntu accessing the oqtane database on a Windows Server running SQLEXPRESS 2019. Very good response, but then again they are on the same LAN.
