### ISSUE TITLE
RFC: Oqtane filesystem extensions

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#635]
Based on our discussion about Thumbnailing and caching files #617, and my current development, I suggest following changes to Oqtane filesystem:

1. changes in model:
* `File` Add fields
  - `int TotalSize` the sum of the sizes of all files belonging to this record
  - `string Caption` for usage as file description in various modules
* `Folder` add fields
  - `string ThumbnailSizes` delimited string  with allowed thumbnail sizes in folder, null or empty means no thumbnail generated, "any" means any requested size will be generated,
  - `bool AllowResponseCache` allow files to be cached in ResponseCaching middleware
  - `bool AllowBrowserCache` allow files to be cached in browser cache
  - `int MaxAge` Maximum age in seconds for items to live in cache
  - `long Quota` Limit size to folder

**Comment by chlupac** [comment]
2. Changes in API

Thumbnail naming convention:
`filename.ext`  - original file name
`filename.thumb.size.quality.ext` - thumbnail file name

* Check user / folder quota when adding file
* display / delete thumbnails belongs to file
* display /delete all thumbnails in system
* delete thumbnails when file is deleted

api functions for
* copy file
* move file
* rename file
* set caption

3. Changes in controller
* Add and configure ResponseCaching middleware
* Use  `PhysicalFile(filepath, file.Name.GetMimeType(), file.Name)` method for sending file instead of reading file to memory / send as stream.
* Add dynamically http headers to response to drive caching by folder settings
* Dynamically create thumbnails on demand constrained to folder settings

4. Changes in UI
* Allow configure new fields from admin ui
* Show file thumbnails (count, total size, details)

**Comment by sbwalker** [comment]
From a security and resource management perspective in Oqtane, files are related to folders and folders have permissions. We should not introduce security or resource management at the file level. A user has their own folder for managing their personal files.

**Comment by sbwalker** [comment]
Some of the items in this RFC overlap with #604 ( ie. ability to move or rename a file )

**Comment by sbwalker** [comment]
Based on our discussion about Thumbnailing and caching files #617, and my current development, I suggest following changes to Oqtane filesystem:

1. changes in model:
* `User`  Add  field `long Quota` to limit total file size quota for user
> not required - it should be associated to the users personal folder. It should still be possible to add a field to the User Management to set this value - but the value would be saved in the Folder entity
* `File` Add fields
  -  `int Owner` 
> not required - Files should utilize the current security model where ownership is defined using permissions at the Folder level
  - `int TotalSize` the sum of the sizes of all files belonging to this record
> not required - each File should be treated as its own entity
  - `string Caption` for usage as file description in various modules
> would there be a default caption? who is allowed to change the caption?
* `Folder` add fields
  - `bool AllowThumbnails`
  - `string ThumbnailSizes` delimited string  with allowed thumbnail sizes in folder
> if ThumbnailSizes != "" then wouldnt it mean the same thing as AllowThumbnails == true? Is there a use case where AllowThumbnails == true but ThumbnailSizes is not specified?
  - `bool AllowResponseCache` allow files to be cached in ResponseCaching middleware
  - `bool AllowBrowserCache` allow files to be cached in browser cache
  - `int MaxAge` Maximum age in seconds for items to live in cache
  - `long Quota` Limit size to folder
> Yes to all of the above

**Comment by sbwalker** [comment]
More comments:

2. Changes in API

The main concern that needs to be addressed for thumbnails is related to the security surrounding the creation of files. Even with resource quotas in place there is potential for abuse if the system allows for creation of files by non-authorized users. As a result I believe that the Folder Edit permissions need to be enforced for thumbnail file creation.

**Comment by chlupac** [comment]
> would there be a default caption? who is allowed to change the caption?

Default caption = null; Update rights have person with edit privilege in folder. Editable by modules. I'm developing two modules now - Downloads and Gallery which can utilize this field without need of additional tables in database. 

> what is the default value for Thumbnail sizes? 

null

> Is there a use case where AllowThumbnails == true but ThumbnailSizes is not specified?

In site design / development / testing stage when you want easily allow all thumbnail sizes.
or we can add keyword `ThumbnailSizes = "any"` for this scenario, and this `bool AllowThumbnails` is obsolete.
and `ThumbnailSizes == null` mean no thumbnails

>   As a result I believe that the Folder Edit permissions need to be enforced for thumbnail file creation.

Thumbnails can be generated:

1. On demand based on Url - unconstrained or constrained by `ThumbnailSizes` and/or permissions
2. Manually on command by `ThumbnailSizes` in folder - here must be interface/api for delete / recreate thumbnails
3. Automatically in moment of image upload

**Comment by sbwalker** [comment]
In no situation would we want to support an option which allows completely unconstrained creation of files. This is true for all environments - development through to production. So let's review the constraints:

Folder Quota - restricts total size of files in folder. However if there was an "unlimited" option then this constraint could be ignored.
Folder Sizes - restricts thumbnails to specific sizes. However if there is an "any" option then this constraint could be ignored.
Permissions - Folders are managed by permissions in the framework - Edit permission indicates who is allowed to create files. This should be enforced regardless of environment. Host users have full permissions in all folders in all sites so they would not be restricted.

Does this sound correct?

**Comment by sbwalker** [comment]
The reason I was emphasizing that there can be no completely unconstrained creation of files option is because if there was even a single folder in a site which is completely unconstrained, a third party could call the API endpoint with FileIDs and non-default dimension parameters until they found a combination which generated a file ( ie. the Folder quota is set to unlimited and folder size is set to allow any ) - and then they could iterate through various dimensions until they flooded the server with images. This may seem farfetched but after seeing that lengths that malicious users go to spam sites, I would not want to expose such a known vulnerability.

**Comment by sbwalker** [comment]
I believe my concern above could be mitigated by enforcing that a folder must always have either a quota <> unlimited or a sizes <> any. If this was enforced then it would be impossible to have completely unconstrained file creation in any environment. And thumbnail creation would not need to rely on Edit permissions.

**Comment by jimspillane** [comment]
Is there a need to resize images to any size?  Maybe a list of allowable widths in the settings would work, something like 96,320,640,1024. Image responses could be rounded up to the nearest width and let the CSS set the dimensions.

**Comment by sbwalker** [comment]
@jimspillane the solution suggested by @chlupac includes a property for ThumbnailSizes in the Folder table to limit the image files that can be created. However he also mentioned that it could be set to "all" ( unconstrained ) which is why I voiced my concern above.

**Comment by sbwalker** [comment]
Closing as the majority of this feature was added to 2.3 - including security to ensure images can only be created under specific circumstances.
