### ISSUE TITLE
RFC: Tutorials with Videos

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#646]
## Request for Comments on Video Tutorials

A lot of discussion on the community gitter about Oqtane Docs and some video tutorials being created.  There is already a discussion on the docs side of things #570 .  My issue here is more on the side of tutorials and how we should try to create them to help educate anyone using the Oqtane Framework.

I have found that 3 minute videos that discuss each step or technology being used to accomplish something in a series discussing a much broader topic has been very popular and successful in helping people learn new things like .NET Core in the past.

- Installation Series
- Administration Series
- Theme Development Series
- Module Development Series
- Framework Development Series

Some of these may have the same videos that can be shared for steps being created in the docs area and playlists created on YouTube for example.

Each video should not be longer than 3 minutes on average similar to an LP or records back in the day as this is about when people start to tune out.

Stay to the point make 1-5 minute videos (like a song) each discussing each talking point or step along the way that deserves some time to fully explain in detail that one thing.  Then when stuck 

-  you can find that one thing and not have to go through 1 hour of video.
-  if a step is off you just redo that one video and replace it in the docs steps playlist
-  you don't need to do all the videos at once, you can keep expanding on them as you can explaining in detail each talking point or step to reach a goal.
- generally more clear and easy to follow directions when an instructor is not trying to fly between many topics in one long video.

[Great Blazor Video Series Example](https://www.youtube.com/watch?v=uuzi3SmCLVo&list=PL6n9fhu94yhVowClAs8-6nYnfsOTma14P)

And if you like to get a little more fancy add some music at the beginning using a small clip of something public domain and/or royalty free.

**Comment by sbwalker** [comment]
I think you make some valid points @thabaum but there is also a saying “beggars can’t be choosers”... and considering the lack of support content available currently, I would be happy with any tutorials which the community wants to step up and create.

**Comment by thabaum** [comment]
Just trying to help anyone trying to make effective tutorials... do what you please as this is what I do :)

**Comment by sbwalker** [comment]
These are probably not at the level which you were hoping @thabaum but I did create a 7 part Oqtane video series last month:

https://www.youtube.com/playlist?list=PLYhXmd7yV0elLNLfQwZBUlM7ZSMYPTZ_f

I would be happy if other people created additional video content for Oqtane as well.

**Comment by thabaum** [comment]
Those are great, I will love watching them each as I have a break.  It beats 1 hour videos any day thank you for breaking those up!!!

**Comment by thabaum** [comment]
Can you label what each chapter is focused on in the title?
