### ISSUE TITLE
Add/Edit Profile: order & required

### ISSUE THREAD

**Issue by wcrisafu** [oqtane/oqtane.framework#676]
Hi,

Just starting with Oqtane, so it may not be an issue but:
1) When you add a new profile, if you forget to put the order # (leave 0), save and then you try to edit, it does not update the record (same for field size). I had to open the table an update manually + siteID is "null" (that may be by design?)
2) Required. I created a new profile and set required to yes, then created a new use. No way to know what profile fields are required + did not enter any value for the field. user saved, no error, no prompt. I can see the data has been saved somewhere but i am still looking for the table that holds the profile info :)

**Comment by sbwalker** [comment]
I believe this is a valid issue as I don't think the required property is being utilized properly in the code currently. The ordering of the profile fields will need to be investigated further. Thank you for reporting these items.
