### ISSUE TITLE
Module Creator

### ISSUE THREAD

**Issue by bakes82** [oqtane/oqtane.framework#728]
Is there any way to have the module created w/out all extra table/sql/Repos?  (Toggle?)
Minor inconvenience to pull delete it when some modules need to interface with an API layer instead.

Also could we get a "download" button so when we make an external module we dont need to pull it from the site, we can download it as a 7z or whatnot.

Is there a more in depth module creator documentation.
IE how do we make make sure all the dependence like 3rd party nugets get registered and packaged.  (IE syncfusion blazor controls.)

**Comment by sbwalker** [comment]
At this point you will need to manually remove any aspects of the module you do not want. It is too difficult to construct a fully functional module based on various toggles.

I do not understand the concept of a Download button. The main use case for module creator is to utilize it in your local development environment to scaffold module code so you can open it immediately in Visual Studio. It is not meant to be utilized in a production site.

There is limited documentation currently - we are hoping the community steps up and creates some. I would recommend looking at some of the blogs on this site https://blazorhelpwebsite.com/. Modules with dependencies are more complicated but you can look at this example https://github.com/oqtane/DNF.Projects to see how RestSharp is included as a Nuget package.

**Comment by sbwalker** [comment]
I would also suggest you watch the video series https://www.youtube.com/watch?v=JPfUZPlRRCE&list=PLYhXmd7yV0elLNLfQwZBUlM7ZSMYPTZ_f

**Comment by bakes82** [comment]
Right so I deployed this to Azure for dev, when you make a new external module you need to go out to the ftp and pull the files.   I didnt clone the repo down or anything yet, was just seeing what was out of the box and looking at the module creation template, but if you saying module creation should be done via a dev box could just be a CLI script ;)

**Comment by nohorse** [comment]
@bakes82 I've been running my dev solution locally and pointing to the azure database.  We also publish to azure, but that's more of a shared dev instance of Octane and we deploy modules there the same way you would for a production site.  You certainly can make your client call whatever API you like.  Oqtane makes an API for you, so it's a choice where your APIs live.  One things you might find handy is a Module mono-repo with various modules in a sinle solution.  that way you have less scaffolding and can copy/paste UI bits quickly. see https://github.com/oqtane/oqtane.framework/discussions/689

**Comment by bakes82** [comment]
When I look at the process they have wired up with the post scripts it seems weird to me honestly, shouldn't the proper way to install modules be install the nuget via the Prod UI?  Not republish the prod site.  If we want everything to be up gradable we shouldnt have any reason to touch the stock install and all our changes should be done via modules.  Thus why when we pressed the deploy to azure button and made the new module Id assume we should be able to download it from the UI otherwise its kind of pointless to have the UI make it and should be a stand alone app that the devs use.  For dev it works but when we go to prod we shouldnt need to push base code, and with auto updating there shouldnt be a reason to.  We make modules on our machines push the nugets out (It would be nice if we could link a nuget via ui instead and it would be like VS where we can publish to our nuget server and it will say there is a new per-release or prod version.)
