### ISSUE TITLE
Theme - No navigation

### ISSUE THREAD

**Issue by bakes82** [oqtane/oqtane.framework#729]
Is there a theme example with no navigation?  Use case would be a landing page, or maybe hidden from navigation form pages.

I deployed to azure, setup, I see the cerulean theme.  Press download, then install and it doesnt error loading spinner spins and then just comes back to same page to say install the theme again.

**Comment by sbwalker** [comment]
The Cerulean theme source code is available here: https://github.com/oqtane/oqtane.theme.cerulean. For a theme without navigation you could copy Default.razor to create a new component ( ie. NoNav.razor ). Remove the < Menu Orientation="Horizontal" / > from the markup.

**Comment by bakes82** [comment]
And by making it a new component that would make it toggle from the page ui when you select it I guess.  Still going thru everything.

**Comment by nohorse** [comment]
I build a theme with custom navigation here: https://github.com/DarkMatterOregon/oqtane.theme.newco
To remove or change the navigation, edit the default.razor file

**Comment by bakes82** [comment]
Im looking for 1 theme, where when you make a page you can say this page doesnt have navigation.  So Im trying to figure out what needs to be done to make that toggle.  Im not sure how the Default is being inherited down and where the other pages are placing their code.
I assume it should be working something like the old master page template system but its just not clicking for me yet lol.

**Comment by nohorse** [comment]
I guess picking a base theme would be good, then you can copy it.  give it a new namespace, then delete the nav from default.  I crated the NewCo theme from Cerulean that way.   The trick is avoiding hacking away on your local copy of the fremework, but you can start there for some quick progress.  You can find the theme components in client/themes 
![image](https://user-images.githubusercontent.com/311063/92151194-91e8ee00-edd5-11ea-96b1-e717d03ffd3f.png)

**Comment by bakes82** [comment]
I think your repo is private.

**Comment by nohorse** [comment]
it's public now!

**Comment by bakes82** [comment]
@sbwalker I tried installing the cerilium theme, doesnt install, restart the project it now wont start and tells me that that theme is missing assets.json.

Also when using the oqtane multi pane view, any page saved with this doesnt seem to do anything, I press edit again the theme is blanked out/reset I dont see any way to make a module go to the Left/Right/Top/Center/Bottom.  Is there a demo environment.  Im assuming all is configured correctly.

**Comment by sbwalker** [comment]
It appears that there is a bug in the theme installer logic. I will investigate further.

**Comment by sbwalker** [comment]
I confirmed there is a bug in the theme installer/uninstaller. In addition, there is a bug related to Layouts in the Router. I am testing fixes for both right now.

**Comment by bakes82** [comment]
Thanks, things didnt seem right to me, glad I wasnt just confused :P

**Comment by sbwalker** [comment]
Fixed in #748
