### ISSUE TITLE
Page Actions in Modules are Case Sensitive

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#769]
@sbwalker Previously in the gitter group you said:

>Shaun Walker @ sbwalker Jul 09 04:54
@ cody in my earlier post I suggested that alias names and page paths should be case insensitive, and parameters must be case sensitive. The case insensitive elements of the url should be converted to lowercase for consistency. There is no site setting that is needed for enabling or disabling this as it is not a “feature” - it is expected behavior.

I believe that actions on Page Actions in Modules should be case insensitive. I keep running into the problem where I will route to a page action use a lower case e.g. `add` vs `Add` and the browser caches the lower case version so if I try to route to the other it automatically changes back to lower case...

**Comment by sbwalker** [comment]
@PoisnFang can you elaborate a bit more on the scenario which is causing you problems?

**Comment by hishamco** [comment]
Related to this issue, when you hit the Url http://localhost:44357/admin/roles/*/15/add for instance the Add Role dialog will not show up, while it's working fine with http://localhost:44357/admin/roles/*/15/Add

**Comment by PoisnFang** [comment]
@sbwalker Sorry, I forgot to respond to this, but the scenario is exactly what @hishamco is describing. Module actions are case sensitive, as well as URL parameters. It is my belief that only queries should be case sensitive.

**Comment by PoisnFang** [comment]
If we ran comparisons when searching for these using `ToUpper()` then we could solve this.

**Comment by hishamco** [comment]
PR will be there soon ...

**Comment by PoisnFang** [comment]
Also I believe we still need to do this with subsites

**Comment by hishamco** [comment]
Could you please elaborate?

**Comment by PoisnFang** [comment]
@hishamco it was something mentioned by @mikecasas back in gitter, that when you make a subsite the site is site sensitive.

**Comment by PoisnFang** [comment]
the pages themselves are case sensitive, like you cant go to http://localhost:44357/Admin/users

**Comment by hishamco** [comment]
I will try to cover that in my PR

**Comment by sbwalker** [comment]
This should be fixed in #968
