### ISSUE TITLE
Create Language Switcher component

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#772]
@sbwalker it would be nice to create a language switch components to allow the Oqtane users select their favorite language instead of dealing with cookies

I will push a PR if sounds looks good to you

**Comment by hishamco** [comment]
@sbwalker your though about this one

**Comment by sbwalker** [comment]
Yes, I think this is a good idea. The component should be added to the Themes/Controls folder as it would typically be a component that someone would include in a theme rather than a module.

**Comment by hishamco** [comment]
After `2.0.0` we could add a language setting for the admin, which is different that language switcher to allow the admin to localize the admin part of Oqtane

This need a design because ASP.NET Core is using a special localization cookie, but in this case we need to track both front-end and back-end cultures

**Comment by hishamco** [comment]
I think I will work on this tomorrow after `2.0.0` is released, no need to more PRs at this time, so it will be a feature for `2.1.0` release

**Comment by hishamco** [comment]
I will create a PR for this soon, coz I'm working with this right now, but we could defer it after the release

**Comment by sbwalker** [comment]
Yes, let’s defer this until after 2.0

**Comment by hishamco** [comment]
I already started working on this two days ago:

- The strategry to set the culture is limited in Blazor to Cookies and providing a UI to choose the culture

- What I'm suggeesting is let Blazor Server work with Cookies to align with Oqtane phylosophy and Blazor Web Assembly could use local storage

After everything is goes fine I will try to use cookies everywhere
