### ISSUE TITLE
InvalidOperationException on GetSite()

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#780]
@sbwalker is there any regression bug on the PRs that you merged today, I'm getting **The entity type 'CustomAttributeData' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.'**

**Comment by sbwalker** [comment]
The PR I checked in had no database impact at all. What are you trying to do when the error occurs?

**Comment by hishamco** [comment]
I'm not sure what happen, I tried with a new installation too, when I was trying to implement localizable labels, I will close this for now and I will check everything from my side

Thanks

**Comment by hishamco** [comment]
@sbwalker I just updated to the latest master whenever I start a new setup this error show up:

**There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
e.log @ blazor.server.js:19**

Any idea?

**Comment by hishamco** [comment]
I fix it the problem with the label component that I have added in the Default component, just leave my earlier component

**Comment by sbwalker** [comment]
So you are saying this is happening on a new install - ie. when remove the connectionstring and reinstall using the Install Wizard? If so, I am guessing it has something to do with recent code merges - perhaps related to localization as that was the biggest change. I did a reinstall yesterday as part of my .NET 5 testing and did notice an issue ( ie. the SignalR connection disconnected ) but thought it was related to .NET 5 - but perhaps its the same issue you reported here?

**Comment by hishamco** [comment]
Just enable the above setting and it will show the error details, I will try it with .NET 5.0 too, my issue was happening with a new installation but I forgot that I have added a label component that throws render fragment issue

**Comment by hishamco** [comment]
No no everything is fine now no worry and I will try the experience with .NET 5.0 today

**Comment by sbwalker** [comment]
Since I have all the changes for .NET 5 done should I merge them?

**Comment by hishamco** [comment]
Could you please create a PR before you merge, so I can test it now, I will test the localization stuff too

**Comment by sbwalker** [comment]
see #788
