### ISSUE TITLE
Action link always display page in modal and it's ready only

### ISSUE THREAD

**Issue by mixlplix** [oqtane/oqtane.framework#798]
Just recently all my ActionLinks now bring up a modal with my Edit page, but everything is disabled.  I can't click any buttons or fill out any fields.  Also, is there a way to navigate to the page and not have it be in a modal?  Here is my code:

<ActionLink Class="btn btn-primary" Action="Edit" Text="Add New" Parameters="@($"id=0")" />

**Comment by mikecasas** [comment]
To eliminate the modal use the following in your component:

``` public override bool UseAdminContainer => false;```

From IModuleControl:

```
 bool UseAdminContainer { get; } // container for embedding module control - defaults to true. false will suppress the default modal UI popup behavior and render the component in the page.
```

**Comment by mixlplix** [comment]
Brilliant, that worked.  To be clear for anyone reading this in the future, the above public override goes in the page being linked to in the ActionLink not the page with the link on it.  In my case it is the Edit.razor page .
