### ISSUE TITLE
Cleanup Reused/Duplicated Code Relating to Themes

### ISSUE THREAD

**Issue by mitchelsellers** [oqtane/oqtane.framework#8]
Currently, in the Client library, multiple .cshtml files are performing the same actions with the results from the IThemeService (Formerly ISkinService).

These operations should be condensed and moved to a method implementation inside of the IThemeService to prevent fragility in management of the code-base going forward.

Items to consider moving to a method implementation:

* Available Themes
* Available Containers

This will substantially reduce the on-view code levels greatly. 

I'll submit a PR for this, after my other PR is processed, but wanted to get this documented.

**Comment by nvisionative** [comment]
I concur - great idea @mitchelsellers !
