### ISSUE TITLE
Module Message doesn't work on Installer Page

### ISSUE THREAD

**Issue by TonyValenti** [oqtane/oqtane.framework#806]
When doing a fresh install of Oqtane, give it invalid/missing parameters and try to install.
An error will occur because PageState.User is null.

**Comment by hishamco** [comment]
Are you using the latest bit, coz I doing a fresh install two or three days ago and it works fine

**Comment by bryfa** [comment]
I have the same issue with the lates version. PageState.User is null.

**Comment by mikecasas** [comment]
@bryfa So do you get to the main installation page?

**Comment by sbwalker** [comment]
yes, I believe that is an issue as the Install Wizard is not served through the router and does not have PageState set. This is a simple one to fix in ModuleMessage.razor:

        @if (Type == MessageType.Error && PageState != null && UserSecurity.IsAuthorized(PageState.User, Constants.HostRole))

**Comment by bryfa** [comment]
@mikecasas @sbwalker yes it was on the main install wizard page.

**Comment by sbwalker** [comment]
fixed in #817
