### ISSUE TITLE
Audit Usage of Constants vs Static Properties

### ISSUE THREAD

**Issue by TonyValenti** [oqtane/oqtane.framework#810]
In .NET, ```const``` and ```static``` values can behave similarly but when it comes to how they are allocated in memory they are very different.

The C# compiler will inline (embed) ```const``` values at the call site but it cannot do this with static values since their value cannot be known at compile time.  As an example, consider the following code:
```
using System;

namespace ConsoleApp5 {
    class Program {

        public const string ConstValue = "Hello World";
        public static string StaticValue { get; private set; } = "Hello World";

        static void Main(string[] args) {
            var C1 = ConstValue;
            var C2 = ConstValue;
            var C3 = ConstValue;

            var S1 = StaticValue;
            var S2 = StaticValue;
            var S3 = StaticValue;

            var Data = new[] {C1, C2, C3, S1, S2, S3 };

        }
    }
}
```
Decompiling this code results in the following:
```
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApp5
{
    internal class Program
    {
        public const string ConstValue = "Hello World";

        public static string StaticValue
        {
            get;
            private set;
        }

        static Program()
        {
            Program.StaticValue = "Hello World";
        }

        public Program()
        {
        }

        private static void Main(string[] args)
        {
            string str = "Hello World";
            string str1 = "Hello World";
            string str2 = "Hello World";
            string staticValue = Program.StaticValue;
            string staticValue1 = Program.StaticValue;
            string staticValue2 = Program.StaticValue;
            string[] strArray = new string[] { str, str1, str2, staticValue, staticValue1, staticValue2 };
        }
    }
}
```

In most apps, this only results in slight memory bloat and app size bloat because you have multiple copies of the same string floating around.  But With Component-based frameworks like Oqtane, this creates a brittle infrastructure that is waiting to surprise a component developer.  Here is what causes the problem:
1.  In your ThirdParty.DLL, reference FirstParty.Program.ConstValue.
2.  Build and ship ThirdParty.DLL
3.  Change FirstParty.Program.ConstValue.
4.  Run your app without recompling ThirdParty.dll

Because the value was embedded, you will get unexpected results.

I've seen this issue come up alot over the years and I've most recently seen issues the .NET5 runtime team has had to resolve because they forgot about the above.

I would recommend auditing Oqtane's usage of ```const``` values and making the members static whenever possible (not used in an attribute).

**Comment by TonyValenti** [comment]
I seem to remember an issue like this happening with DNN a number of years ago because a default (const) value was changed and it essentially broke all module vendors until they recompiled.

**Comment by hishamco** [comment]
I agree on the principle that we can use constants for the things that never change at all, an example I faced few days ago `CurrentVersion` it could be `readonly static` but not `const`
