### ISSUE TITLE
Factor out Common Strings into appropriately name static classes

### ISSUE THREAD

**Issue by TonyValenti** [oqtane/oqtane.framework#812]
1.  In Oqtane, there are a number of magic strings that exist throughout the application.
2.  Some of these are just "dumped" in Oqtane.Shared.Constants 

As a developer, referencing values like ```Constants.HostUser```, ```Constants.HostRole```, etc. is not ideal because the items in Constants are of different types.  It also does not give a good "Enum-Like" developer experience for new developers who may adopt the platform.

PR https://github.com/oqtane/oqtane.framework/pull/805 creates a handful of enum-like classes that contain common string values that are used throughout the application and updates other places to use the Enum-like casses.  Specifically, the following classes are added:

```
    public class ControllerRoutes {
        public const string Default = "{alias}/api/[controller]";
    }
    public class PaneNames {
        public const string Admin = "Admin";
    }
    public class PolicyNames {
        public const string ViewModule = "ViewModule";
        public const string EditModule = "EditModule";
    }
    public class RoleNames {
        public const string Everyone = "All Users";
        public const string Host = "Host Users";
        public const string Admin = "Administrators";
        public const string Registered = "Registered Users";
    }
    public class TenantNames {
        public const string Master = "Master";
    }
    public class UserNames {
        public const string Host = "host";
    }
````

The following changes were also made:
1.  The associated members in ```Constants``` now point to the related enum-like class.
2.  The associated members in ```Constants``` are now [Deprecated] and suggest the appropriate class.
3.  Any places that called the ```Constants``` member now calls the enum-like member.

This is a relatively small PR that (I think)  cleans up the code a bit and segments things out better.  It is also my first PR into Oqtane.  It would be great if it would be accepted and I could take any additional feedback you might have.

**Comment by erikvb** [comment]
This is great, but I would hope the long term solution for these constants is to have these localizable.

**Comment by hishamco** [comment]
> but I would hope the long term solution for these constants is to have these localizable.

@erikvb localization is just start to shine, hope to see more localization features in the upcoming releases

**Comment by sbwalker** [comment]
@erikvb take a look at #749 if you are interested in how localization is taking shape in Oqtane
