### ISSUE TITLE
Minor Adjustment to <Label> Tag Helper

### ISSUE THREAD

**Issue by TonyValenti** [oqtane/oqtane.framework#814]
Currently it renders the help icon to the right like this:
![image](https://user-images.githubusercontent.com/13609558/96299645-f644c300-0fb9-11eb-8469-4f7ff8800d53.png)

It will look better and be more accessible if the help icon is to the left like this:
![image](https://user-images.githubusercontent.com/13609558/96299659-fc3aa400-0fb9-11eb-9390-5a8155a6ae65.png)

It will look better because items will be aligned and it will encourage consistent help-text creation because if help text is inconsistently applied, it will stand out.

**Comment by hishamco** [comment]
Agree & disagree ;)

Agree that the alignment is not appropriate for accessibility, disagree with moving them to the left probably we align the element to the right

**Comment by TonyValenti** [comment]
@hishamco - That's an even better idea!  Can you make it happen?

**Comment by hishamco** [comment]
Sure, I will try to create a PR for it, but before that I can share a screenshot, so all guys can see the final result

**Comment by sbwalker** [comment]
There was already a long discussion about form, label and helptext many months ago and there was a consensus on using the current approach. And usually when it comes to platforms, rather than forcing a change of the current default pattern for everyone, it is generally better to add options so that the pattern can be customized based on user preference.

**Comment by hishamco** [comment]
Agree, but I think it would be nice if the platform can handle it for you, for example in case of RTL languages like Arabic & Persian the Labels should be align to the right, but in case to display the help text properly it can align to the left instead
