### ISSUE TITLE
Custom module error on mac

### ISSUE THREAD

**Issue by bmckenzie93** [oqtane/oqtane.framework#847]
When building a custom module or theme there are dll's that get compiled and copied over to the framework. These files are copied over using `XCOPY` commands for windows. I am developing on a Mac, so to get my files copied over from theme to the framework I have written a script that uses the `cp` command for mac.

This is working great for my themes to send the files over, but it is not working for my custom modules. After building my custom module and getting the files copied over to the framework I keep running into an error. 
![Screen Shot 2020-10-20 at 2 55 24 PM](https://user-images.githubusercontent.com/57681347/96933347-17535b00-1475-11eb-838e-4c4b78e173f1.png)

I have also tried having a co-worker zip up their working copy of the framework with all theme and custom module files in tact and send it to me. When I run their copy of the framework I get the same error. They, however, are developing on Windows.

**Comment by mikecasas** [comment]
Make sure you are copying over all the 3rd party dll files and their dependencies.

**Comment by sbwalker** [comment]
@mikecasas is correct. If you are building an external module then you need to copy its dependencies to the Oqtane /bin folder:

![image](https://user-images.githubusercontent.com/4840590/97001568-8f1d9600-1506-11eb-8389-62b829aebf8c.png)

**Comment by hishamco** [comment]
@bmckenzie93 try what the guys are mentioned above, if the problem is still, please create a minimal repo that reproduce the issue
