### ISSUE TITLE
Loading additional JS dependencies in oqtane module

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#852]
To load more custom JS files in custom oqtane module in Client project, in index.razor I just specified additional Resource items in Resources list.

```cs
    public override List<Resource> Resources => new List<Resource>()
    {
        new Resource { ResourceType = ResourceType.Stylesheet, Url = ModulePath() + "Module.css" },
        new Resource { ResourceType = ResourceType.Script, Url = ModulePath() + "Module.js" },
        new Resource { ResourceType = ResourceType.Script, Url = ModulePath() + "Custom.js" }, // Oqtane will not load this script
    };
```

From all script resources only `Module.js` is loaded. It is expected that `Custom.js` is loaded also. For some reason oqtane will load only first script resource in list and skip others. 

I'm using Oqtane.framework v1.0.4.

**Comment by sbwalker** [comment]
Is Custom.js located in the same folder as Module.js? They would both need to be in the Oqtane.Server\wwwroot\Modules\YourModuleName\ folder

**Comment by sbwalker** [comment]
This logic definitely works. If you look at Oqtane.Client\Modules\Controls\RichTextEditor.razor you will see that it loads multiple scripts:

    public override List<Resource> Resources => new List<Resource>()
    {
        new Resource { ResourceType = ResourceType.Script, Bundle = "Quill", Url = "js/quill1.3.6.min.js" },
        new Resource { ResourceType = ResourceType.Script, Bundle = "Quill", Url = "js/quill-blot-formatter.min.js" },
        new Resource { ResourceType = ResourceType.Script, Bundle = "Quill", Url = "js/quill-interop.js" }
    };

Note that it uses the Bundle property in this case to ensure the scripts are loaded in order to observe the dependencies

**Comment by sbwalker** [comment]
is there a reason why there is a comma after the third Resource object declaration?

**Comment by tvatavuk** [comment]
> 
> 
> This logic definitely works. If you look at Oqtane.Client\Modules\Controls\RichTextEditor.razor you will see that it loads multiple scripts:
> 
> ```
> public override List<Resource> Resources => new List<Resource>()
> {
>     new Resource { ResourceType = ResourceType.Script, Bundle = "Quill", Url = "js/quill1.3.6.min.js" },
>     new Resource { ResourceType = ResourceType.Script, Bundle = "Quill", Url = "js/quill-blot-formatter.min.js" },
>     new Resource { ResourceType = ResourceType.Script, Bundle = "Quill", Url = "js/quill-interop.js" }
> };
> ```
> 
> Note that it uses the Bundle property in this case to ensure the scripts are loaded in order due to the dependencies between them

Thank a lot! Adding **Bundle** property **with same value** to each script resource was solution in my case to load additional Custom.js script.

```cs
    public override List<Resource> Resources => new List<Resource>()
    {
        new Resource { ResourceType = ResourceType.Stylesheet, Url = ModulePath() + "Module.css" },
        new Resource { ResourceType = ResourceType.Script, Bundle = "CustomModule", Url = ModulePath() + "Module.js" },
        new Resource { ResourceType = ResourceType.Script, Bundle = "CustomModule", Url = ModulePath() + "Custom.js" }
    };
```

![image](https://user-images.githubusercontent.com/2724850/97841415-12e53880-1ce6-11eb-9d01-ab7292f17cc5.png)

**Comment by sbwalker** [comment]
I am glad you were able to make this work. However the fact that you needed to specify a Bundle property is a bug I believe as it is not supposed to be required. I have looked at the JavaScript and I cannot see where the bug is happening. It is supposed to iterate through the list of scripts and if the bundle property was not specified it is supposed to set the bundle property to the href value. Maybe LoadJS does not like a bundle property value with path delimiters.

    includeScripts: async function (scripts) {
        const bundles = [];
        for (let s = 0; s < scripts.length; s++) {
            if (scripts[s].bundle === '') {
                scripts[s].bundle = scripts[s].href;
            }
            if (!bundles.includes(scripts[s].bundle)) {
                bundles.push(scripts[s].bundle);
            }
        }

**Comment by sbwalker** [comment]
Fixed in #865. This was a really tricky problem. Basically using JavaScript Promises within a for loop does not work as expected due to their async nature. The includeScripts() method needed to be reworked to push all promises into an array and execute them at the end of the method using Promise.All().

**Comment by egarim** [comment]
I have a question about a related case,I want to create a module that display an instance of monaco editor (https://github.com/serdarciplak/BlazorMonaco) and for that  I need to load js and CSS that are resources in a nuget package , something like this

<head>
    <link href="_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.css" rel="stylesheet" />
</head>
<body>
    ...
    <script src="_content/BlazorMonaco/lib/monaco-editor/min/vs/loader.js"></script>
    <script>require.config({ paths: { 'vs': '_content/BlazorMonaco/lib/monaco-editor/min/vs' } });</script>
    <script src="_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js"></script>
    <script src="_content/BlazorMonaco/jsInterop.js"></script>
    ...
</body>

is this scenario supported in Oqtane ?

**Comment by leigh-pointer** [comment]
@egarim the short version is yes.  If you have a look at this blog post you will be able to intergrate into Oqtane https://blazorhelpwebsite.com/ViewBlogPost/47
