### ISSUE TITLE
ModuleCreator Invalid character use in naming fields

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#889]
Using invalid characters is allowed which results in the module not being able to compile.
Entering in **This-Is>Not&Allowed**  in the owner input or the module input will be excepted but creates unusable code.

**Comment by hishamco** [comment]
Could you please move this to the ModuleCreator repo

**Comment by sbwalker** [comment]
The field level help say "It should not contain spaces or punctuation" - but I agree that it should do actual validation on the information entered.

@hishamco there is no ModuleCreator repo - the module is in the core framework

**Comment by hishamco** [comment]
I remembered you referred to me into another repo last time, when I asked about ModuleCreator to create an external module

**Comment by hishamco** [comment]
It's my fault ;) I thought this is the repo https://github.com/oqtane/DNF.Projects seems it's a module that uses the ModuleCreator. @leigh-pointer could you please add a PR for this one?

**Comment by sbwalker** [comment]
This should use a RegEx of "[A-Za-z_][A-Za-z0-9_]*" for the Owner Name and Module Name

**Comment by sbwalker** [comment]
fixed in dev branch
