### ISSUE TITLE
Upgrade Oqtane to .NET Core 3.0 Preview6 

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#9]
Microsoft released .NET Core 3.0 Preview 5 on May 6. Currently Oqtane only runs on Preview 4 and will not compile on Preview 5. We should try to stay up to date with the latest Microsoft releases.

**Comment by cnurse** [comment]
I am currently using Preview 5 without any issue (although I have only tested the Blazor/Server version)

**Comment by sbwalker** [comment]
Did you update the csproj file to point to Preview5? If you want to test the client-side simply switch your build configuration in Visual Studio to Wasm and build and run.

**Comment by iJungleboy** [comment]
I was running it with preview 5 and it seems to work flawlesly. also using VS Code.

**Comment by sbwalker** [comment]
Updated title to Preview6 as it was released yesterday

**Comment by sbwalker** [comment]
Resolved
