### ISSUE TITLE
Localize Logs Messages

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#933]
We should localize the static logs, coz the dynamics logs are tricky but we could may find a good solution to localize them

**Comment by sbwalker** [comment]
You are talking about localizing the static portions of the log messages, correct? For example:

            await Log(_alias, LogLevel.Error, string.Empty, ex, "Error Loading Site {SiteId} {Error}", _alias.SiteId, ex.Message);

You want to localize the ""Error Loading Site" static text and allow the dynamic parameters for {SiteId} and {Error} to be populated by the environment without any explicit localization.

I agree.

**Comment by hishamco** [comment]
Exactly!!

**Comment by hishamco** [comment]
I did some progress here, I come up with idea to reduce the RESX files into 1 which is cool and easy to manage, during my testing I notice the dynamic parameters {Param} are sometimes a JSON object like what I saw when creating a new role. I'm not sure if it's necessary to do that, IMHO we could use role name in this case and keep the JSON object on the properties as its for detail info
