### ISSUE TITLE
Webassembly version cannot find system.runtime.dll

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#936]
I tried to publish and run Oqtane on v2.0 but when I swapped it from server to web assembly ot says it cant find system.runtine.dll I will post the screen shot in the morning.

**Comment by hishamco** [comment]
Thanks for reporting this and waiting for your screenshots

**Comment by sbwalker** [comment]
@markdav-is reported an issue in the Cerulean theme repo a few days ago: https://github.com/oqtane/oqtane.theme.cerulean/issues/3. My concern is that Microsoft changed the linker behavior in .NET 5 ( https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/ ) and it is possible that a release build of Oqtane is trimming required DLLs - because of its dynamic capability and the fact that the linker is only aware of static dependencies.

**Comment by PoisnFang** [comment]
@hishamco @sbwalker  Here is the screen shot: 
![image](https://user-images.githubusercontent.com/60050783/99847268-10cc0800-2b35-11eb-9573-00c98bd801f1.png)

It seems to be working fine on my local machine now, but this is still breaking on my web server. Not sure if I am missing a config with Nginx...

**Comment by markdav-is** [comment]
I was thinking that we might need to rebuild the module and theme templates using a .net5 targeted solution.  I'm not sure what would be involved there.

**Comment by PoisnFang** [comment]
If you publish the v1.0.4 and the v2.0.0 version side by side you can see the difference.

v1.0.4 makes 81 items
v2.0.0 makes 55 items

**Comment by sbwalker** [comment]
So the .linker is most likely trimming a bunch of required DLLs during publish because of the changes in .NET 5 (  https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/ )

**Comment by PoisnFang** [comment]
@sbwalker Perhaps... It seems weird though cause I made my own package with a similar architecture to Oqtane and it does not have this problem...

**Comment by PoisnFang** [comment]
Here are the published files: https://drive.google.com/drive/folders/1CNZOSUX3WAdX10wieFm2tMSZcOSD4qFo

**Comment by sbwalker** [comment]
It seems weird because every application has a different set of dependencies... and since Oqtane relies on dynamic loading for so many features it means that the linker will not be able to resolve the dependencies. It appears that Microsoft made significant breaking changes with the linker in .NET 5 when it comes to Blazor:

Blazor Web Assemblies

One of the biggest needs for size reduction is in the context of Blazor web assemblies. The 3.2 release of Blazor in May was based on the Mono framework. The .NET 5 release will use the .NET 5 framework, which is larger, and we didn’t want to regress the size of Blazor Apps.

The following trimming approach is being taken for Blazor Apps in .NET 5:

    - Assemblies from the shared framework/runtimepack get member-level trimming
    - Microsoft.Extensions.* assemblies get type-level trimming from TrimMode=Link
    - Assemblies from Microsoft.AspNetCore.* are trimmed via hand generated XML file
    - All other assemblies are not trimmed

**Comment by markdav-is** [comment]
I think you can tune down the rimming in the project settings.  https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-5.0  
``` <PropertyGroup>
  <PublishTrimmed>false</PublishTrimmed>
</PropertyGroup> ```

**Comment by PoisnFang** [comment]
SUPER WEIRD this had to go into effect in the last 48 hours because it was publishing just fine for me with my other app and now its not! @markdav-is I just tried that and it didn't solve it... This is straight up a dotnet issue I think

**Comment by sbwalker** [comment]
So... I am assuming that the PublishTrimmed needs to be set in Oqtane.Client. However what about modules and themes? In .NET Core 3.x there was a setting in the module/theme Client project called BlazorWebAssemblyEnableLinking and it was set to false. This setting was critical in allowing Oqtane to load the modules/themes dynamically when running on WebAssembly. Is this setting still relevant on .NET 5? I only see it mentioned on .NET Core 3.1 https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1

**Comment by sbwalker** [comment]
@PoisnFang is the difference that you recently did a build in Release mode?

**Comment by PoisnFang** [comment]
@sbwalker Ah yes, it would appear that I did!

**Comment by PoisnFang** [comment]
Ok I was wrong about it changing overnight, I was doing a self-contained deployment. BUT I did try my other project my my custom package using .NET 5 and it works fine. So **THE ISSUE** is has something to do with `AssemblyExtensions.cs` and whatever is it trying to get on load...

**Comment by PoisnFang** [comment]
@sbwalker @hishamco  :/ well I am a goober, looks like its a module issue due to my custom module....  Another good example of how this doesnt speed up my development... sorry to waste your time!

**Comment by sbwalker** [comment]
can you explain what the problem was, as the error looks similar to what @markdav-is reported for the Cerulean theme

**Comment by PoisnFang** [comment]
Here is the Error in Debug mode (gives more details!) 
![image](https://user-images.githubusercontent.com/60050783/99854386-f8161f00-2b41-11eb-96d0-b1ccbbd02f6a.png)

**Comment by PoisnFang** [comment]
I am using the BlazorInputFile package and its causing a problem, I need to convert over to the new file input field. IDK if it would be something similar to the Cerulean theme error

**Comment by sbwalker** [comment]
thank you for sharing!

**Comment by PoisnFang** [comment]
There might be something more here, I am running more errors of similar nature...
