### ISSUE TITLE
Use Mysql instead of mssql

### ISSUE THREAD

**Issue by michalss** [oqtane/oqtane.framework#942]
Is there posibility to use MySql or MariaDB.  See many ppl not using MSSQL since they hosting on Linux, also for example mysql is very popular and to be hones much better then mssql

**Comment by jimspillane** [comment]
Hi @michalss 

It is in the roadmap, @sbwalker provides details in discussion thread #851

**Comment by michalss** [comment]
Nice but there is nothing about if this will be added or not. Like this framework but if mysql is not implemented then it is useless for linux users and you are stick with expensive window servers :(

**Comment by sbwalker** [comment]
Based on the number of requests, I believe support for multiple databases should be the major feature for 2.1.0.

**Comment by hishamco** [comment]
As I see there 're many issues filed to request multiple database support, could we add a new discussion describing what the databases should be supported? What are the challenges? Then we could close all the opened issues to make it easy for tracking

**Comment by sbwalker** [comment]
@hishamco I will start a new Discussion for this item to outline the high level requirements for multiple database support.

**Comment by chazgorman** [comment]
Sharing a rough port of oqtane to support Postgres over in this branch:

https://github.com/chazgorman/oqtane.framework/tree/postgres

Some of the key modifications:

1. Change of fields named 'Order' to 'OrderVal' in SQL scripts to avoid conflict with SQL keyword. (This may have been better solved by "quoting" keyword to avoid conflict:

https://github.com/chazgorman/oqtane.framework/blob/66040e6f2414cd7bd25dd3e2530a2582a7861775/Oqtane.Server/Scripts/Tenant.00.09.00.00.sql#L43

2. Swapped 'UsqSqlServer()' database context configurating for 'UseNpgSql()':

https://github.com/chazgorman/oqtane.framework/blob/66040e6f2414cd7bd25dd3e2530a2582a7861775/Oqtane.Server/Startup.cs#L134

https://github.com/chazgorman/oqtane.framework/blob/66040e6f2414cd7bd25dd3e2530a2582a7861775/Oqtane.Server/Repository/Context/DBContextBase.cs#L38

**Comment by hishamco** [comment]
Thanks for your input @chazgorman hope to copy it into https://github.com/oqtane/oqtane.framework/discussions/964

**Comment by sbwalker** [comment]
@chazgorman thank you for your efforts! I have tried to outline the goals and changes required in #964 - one of the main items being a transition to EF Core Migrations. So we would not be relying on SQL scripts in the future - mainly for the reason you outlined above in (1) where SQL Scripts are not compatible across different database platforms and we do not want developers to have to create unique scripts for each database.

**Comment by hishamco** [comment]
@sbwalker shall we close all the related issues and focus in one place #964?
