### ISSUE TITLE
Single Sign-On support

### ISSUE THREAD

**Issue by m-ratnikov** [oqtane/oqtane.framework#944]
Hi there! 

I couldn't find the ability to use Single Sign-On (SSO) feature in the oqtane. 
But I see in the roadmap "OAuth Support" feature.
Can you please clarify a few things? 

1) Does "OAuth Support" feature implies SSO functionality support.
2) If not. Is there some workaround solution for this?
3) Can you give an approximate date of the "OAuth Support" feature release?

Thanks!

**Comment by sbwalker** [comment]
There are literally hundreds of single sign-on solutions that are available so you would need to be more specific about your needs.

**Comment by m-ratnikov** [comment]
I'm looking to use IdentityServer or Amazon Cognito.

**Comment by sbwalker** [comment]
At the moment there is some uncertainty related to auth solutions due to the recent announcements about IdentityServer - https://github.com/dotnet/aspnetcore/issues/26489

**Comment by ADefWebserver** [comment]
Because there is a [**free** tier](https://azure.microsoft.com/en-us/pricing/details/active-directory/external-identities/), I recommend implementing **Azure B2C** support to allow SSO. See: [Blazor and Azure B2C: The Big Picture](https://blazorhelpwebsite.com/ViewBlogPost/42)

**Comment by jimspillane** [comment]
News regarding IdentityServer: [Introducing Community Edition](https://blog.duendesoftware.com/posts/20201210_community_edition/)

**Comment by sbwalker** [comment]
@jimspillane thanks for posting this news. It is good for the .NET ecosystem - but my gut reaction is that it will not work for Oqtane as we cannot include a component unless it is offered under a license which is at least as liberal as Oqtane itself. This rules out the Community Edition of IdentityServer  as well as the RPL licensed open source option.

**Comment by VictorioBerra** [comment]
If Octane was OAuth2/OIDC spec-compliant, users should be able to plug in any OAuth2/OIDC secure token server that they desired.
