### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#945]
@hishamco after your recent changes to implement localization throughout the Admin UI I am seeing:

![image](https://user-images.githubusercontent.com/4840590/100115296-5859d900-2e40-11eb-920c-05fb360270ad.png)

My understanding was that if someone is not using localization, then the user interface should be displayed in the fallback default language (English). Is that your understanding as well?

**Comment by hishamco** [comment]
Sorry Shaun, I have an issue with my hard disk, I will have a look ASAP, the fallback should be the default value which defined in the buttons (English)


Just assign this to me and I will try to figure out what's going on
