### ISSUE TITLE
Deploy to Azure Button not working

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#959]
It appears the Deploy to Azure button is broken with the .NET 5 version

![image](https://user-images.githubusercontent.com/1857799/100518555-28b01700-3147-11eb-8d2f-e2a5fa941593.png)

```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}
```

```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}
```

```
Command: "C:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET Core Web Application deployment with MSBuild16.7.0.
'"\MSBuild.exe"' is not recognized as an internal or external command,
Failed exitCode=1, command="\MSBuild.exe" /restore "C:\home\site\repository\Oqtane.Server\Oqtane.Server.csproj" /p:DeployOnBuild=true /p:configuration=Release /p:publishurl="C:\local\Temp\8d893ad40ff5dd3"
operable program or batch file.
An error has occurred during web site deployment.
'"\MSBuild.exe"' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nC:\Program Files (x86)\SiteExtensions\Kudu\90.21106.4900\bin\Scripts\starter.cmd "C:\home\site\deployments\tools\deploy.cmd"
```

This may help:
https://docs.microsoft.com/en-us/answers/questions/166759/azure-deployment-failed-with-following-error.html

**Comment by ADefWebserver** [comment]
Also tracking this issue here: https://github.com/ADefWebserver/Blazor-Blogs/issues/53

**Comment by sbwalker** [comment]
Thank you for testing this Michael. Hopefully you will be able to find a solution. I assume this just affects the Deploy to Azure button - but if you did a manual deployment to Azure it would work fine?

**Comment by ADefWebserver** [comment]
@sbwalker - A manual Azure deployment works. If this is not resolved in the next two weeks, that will be my suggestion to move forward. This weekend I want to try simply updating the azuredeploy.json file. Blazor-Blogs has the same problem, and I am able to do my testing there. Also, we can't have the only projects that has this issue, so I hope Microsoft will respond to my forum posts.

**Comment by ADefWebserver** [comment]
Until this is fixed, the best method to use to install Oqtane on Azure is: [Installing Blazor Oqtane](https://blazorhelpwebsite.com/ViewBlogPost/1)

**Comment by ADefWebserver** [comment]
@sbwalker I have spent days on this and I cannot come up with a Deploy To Azure template that works anymore :(  My recommendation is to remove the button from the README.md page.

**Comment by ADefWebserver** [comment]
@sbwalker - I made a Forum post with Microsoft: https://docs.microsoft.com/en-us/answers/questions/185823/deploy-to-azure-not-working-for-net-5-github-appli.html

**Comment by jimspillane** [comment]
@ADefWebserver try the patch in the PR is created.

**Comment by ADefWebserver** [comment]
@jimspillane - Thanks. I will try it tonight!

**Comment by ADefWebserver** [comment]
@jimspillane - I implemented your fix in [Blazor-Blogs](https://github.com/ADefWebserver/Blazor-Blogs) and I can confirm it works 👍🏾🙌🏾

However, I cannot confirm it in[ your Repo](https://github.com/jimspillane/oqtane.framework/tree/FixAureDeploy) because the Deploy to Azure button there points to the unmodified azuredeploy.json at: https://github.com/oqtane/oqtane.framework/blob/dev/azuredeploy.json

**Comment by jimspillane** [comment]
Sorry, I did not want to change the URL in the button.  Try this link that points to the branch [Deploy to Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjimspillane%2Foqtane.framework%2FFixAureDeploy%2Fazuredeploy.json)

**Comment by ADefWebserver** [comment]
@jimspillane - I know you **have** to code your PR the way you did for it to work when it is merged 👍 

I tested the link you provided and while it said it failed, it still worked!

![image](https://user-images.githubusercontent.com/1857799/101203100-0e7ea900-361f-11eb-9af7-877b9da20b19.png)

![image](https://user-images.githubusercontent.com/1857799/101203147-19d1d480-361f-11eb-93bd-e5884a9d2d2b.png)

![image](https://user-images.githubusercontent.com/1857799/101203159-1dfdf200-361f-11eb-8376-edadf253f2d5.png)

**Comment by jimspillane** [comment]
That's interesting. I will try it again and see if I can get the error to pop up.
