### ISSUE TITLE
Can Oqtane identity management integrate easily with an Identity as a service platform like Auth0?

### ISSUE THREAD

**Issue by nissan** [oqtane/oqtane.framework#965]
I really do like how Oqtane is built, thank you for a great example code base. One question I've been exploring the code to figure out the level of effort needed to customise to do is as follows:
Currently the ASP.Net Core Identity Model is used inside of the default Oqtane deployment if I understand correctly to handle storage of users and roles inside each tenant database.
I want to change this to use either Azure B2C or a service like Auth0 for either a specific or all tenants inside a deployment. How much effort would this require and where would I start to look in terms of classes or documentation to understand how to do this? Happy to share the code back to the project via PR if it's not too complex a task for me to do so I can wrap my head around this bit of how it all works. Thanks again for any pointers here.

**Comment by hishamco** [comment]
I think AUTH is one of the focused areas after 2.0.0, @nissan if you can share your though about it, I will be thankful

**Comment by nissan** [comment]
Ii can speak from the perspective of an Enterprise software developer, which is where I am really keen to use Oqtane at the moment to help onboard our team to building new applications with Blazor. From a technical standpoint, it already is supporting OAuth from what I see, but being able to specify the auth server or service via configuration explicitly would also be good, so that an Oqtane deployed module is configurable to use any enterprise deployed option like Azure AD, Azure B2C, Google, Amazon Cognito, Auth0, Okta, Ping etc for identity access management. The need to set SSO among custom apps is already very real in enterprises. It would be a huge win if we were able to do this out of the box between a rich set of modules provided by an Oqtane deployment, and non-Oqtane based enterprise apps that may already exist in a business that might want to adopt it as a platform for development with Blazor. Oqtane could retain its rules for modules regarding roles and permissions applied to each module, but the auth server or service would be charged with enriching the user token returned when a user logs in with the required roles and permissions to match what is set on a per module basis.

**Comment by hishamco** [comment]
Thanks @nissan for your explanation, BTW I saw a related issue #944 that may help us to do AUTH right way. @sbwalker your thought about AUTH while it was in 2.1.0 but seems move to future milestones

**Comment by nissan** [comment]
I found that @sbwalker did indeed blog about the Auth bits in Oqtane https://www.oqtane.org/Resources/Blog/PostId/527/exploring-authentication-in-blazor with sufficient technical details to get me started researching the problem of how to switch to another auth server or service more, if I figure it out I will of course share what I do back here. Thanks!

**Comment by vzdesic** [comment]
@nissan Did you do mentioned research on how to switch to another Auth service? Anything useful to share with the rest of us?
