### ISSUE TITLE
Two tests are failing

### ISSUE THREAD

**Issue by justSteve** [oqtane/oqtane.framework#966]
I've tried against both Dev and Master. The two tests that use the _returnUrl=_ param are not producing expected URL. The navigatedUrl includes a **'!'** in the path:

`"/contoso/login/!/returnUrl=/admin"`

The runtime behavior is correct -- only the tests display the problem.

**Comment by hishamco** [comment]
I will check those and push the fix soon, @sbwalker that's why CI/CD is useful ;)

**Comment by hishamco** [comment]
I can reproduce the issue,  I'm working on it ...

**Comment by hishamco** [comment]
@sbwalker why the ! included instead of ? in the return url?!! Or is there something changed in Blazor?

**Comment by justSteve** [comment]
FWIW, I've been looking for a project in need of some tests as an excuse to just put my head down and plow thru until I gotten my head around the subject. I'm not in a position to make _toolset_ or '_starting point_' decisions but if anyone would like to define that starting point I have an hour or two per day for the next few weeks to contribute.
