### ISSUE TITLE
RFC: Support Source Generator

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#993]
Hi @sbwalker, could you please specify the target framework for Oqtane.Shared project to **netstandard2.0**? 
Because the Source Generator is a .NET Standard 2.0 assembly that it is usable in environments where .NET Standard components can be loaded and run. I found .NET Standard 2.0 to be enough for Oqtane.Shared project as well.

Thank you very much.

**Comment by sbwalker** [comment]
Are you referring to the new .NET Source Generator? 

https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/

The Oqtane.Shared project was moved to .NET 5 alongwith the rest of the Oqtane solution when we released version 2.0. The Oqtane.Shared project contains shared models and utility methods currently. We would need to understand your use case in more detail to determine if it makes sense to retarget the Oqtane.Shared project to netstandard2.0.

**Comment by lthoa** [comment]
Yes, I am referring to the new .NET Source Generator (SG).

I just define the Model and use the SG to create every other paths of the stream from the blazor page to the API, to Repository ... 

![image](https://user-images.githubusercontent.com/6874322/101800153-89742200-3b3f-11eb-8b47-24b9e1f6af96.png)

The problem is some Models needs to inherit from **Oqtane.Models.IAuditable**, because inherit from new5.0, I need target  my Shared project to net5.0 framework, with net5.0 target framework we can not to import and run with .NET Source Generator.

![image](https://user-images.githubusercontent.com/6874322/101800478-e53eab00-3b3f-11eb-9281-04a6a5b9f789.png)
(https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/)

The .NET Source Generator is really cool, Write Code that Writes Code, and I hope Oqtane will support SG maximum.

Now I need forked and downgrade Oqtane.Shared to netstandard2.0 to compatible with CG.

Thank you.
